### DISCUSSION TITLE
[Tempo-traceToLogs] allow mapping of attributes to Loki labels

### DISCUSSION THREAD

**Discussion by secustor** [grafana/grafana#41392] [Data Sources]
At the moment the name of the attribute has to exactly the same as the label ingested into Loki. 

This results in problems if using the semantic conventions introduced with OpenTelemetry which contain dots, e.g. ( `k8s.namespace.name` ). This problems surface as Loki does not support dots in its label keys. 

My proposed change is to replace the string array of [tags](https://github.com/grafana/grafana/blob/e9d90231e0c30ec250405c516abd0a4091444eb2/public/app/core/components/TraceToLogsSettings.tsx#L14) with key value pairs. This would allow to map any trace attribute to a label.

```yaml
   - name: Tempo
     access: proxy
     editable: false
     orgId: 1
     type: tempo
     url: http://tempo:3100
     version: 1
     uid: default_temp
     jsonData:
       nodeGraph:
         enabled: true
       tracesToLogs:
         datasourceUid: default_loki
         tags:
           - k8s.namespace.name: namespace
           - k8s.pod.name: pod
``` 
This example would map `k8s.namespace.name`, if it is found,  to the Log label `namespace`.
