### DISCUSSION TITLE
Allow reading datasource client TLS key/cert from files

### DISCUSSION THREAD

**Discussion by TLATER** [grafana/grafana#44296] [Data Sources]
Sorry if I'm overlooking a discussion of this in the past, but I've not found anything on this, except a PR for PostgreSQL which seemed more accidental than intentional.

To explain my use case, I'd like to set up an authenticated connection between Grafana and Prometheus, the latter of which somewhat recently gained support for TLS with client authentication.

This [is clearly possible](https://grafana.com/docs/grafana/latest/administration/provisioning/#json-data), and actually quite well documented after a series of pull requests here, however, currently the only option is to set the certificates in the "secure" json data setting, which must be set in plaintext in the configuration file if it's to be configured outside of the GUI.

While that works, it makes it more difficult to ensure that secrets stay secret, because this way the Grafana configuration cannot be stored in plain text anywhere, since that would leak the key. I now have a trade-off between keeping my configuration version controlled and keeping my key secret - not a great trade-off to make.

This also has the downside that the key must be placed inside a yaml file in plaintext, which makes for a somewhat complex file requiring proper knowledge of the yaml file syntax (this admittedly isn't terribly complex, but some users do seem to be having problems with this, see [here](https://community.grafana.com/t/how-to-format-tls-certs-in-yaml-for-grafana-datasource-provisioning/7779/3)).

It would be nice if instead I could specify files from which to read my key/certificate in `jsonData`, like so:

```yaml
datasources:
  - name: Prometheus
    jsonData:
      tlsAuth: true
      tlsAuthWithCACert: true
      tlsCACertFile: <filepath>
      tlsClientCertFile: <filepath>
      tlsClientKeyFile: <filepath> 
```

There are a handful of benefits to this approach:
- The file paths aren't confidential, and can therefore just be stored in the configuration file, which can now be public and version-controlled.
- This doesn't require the awkward multi-line string syntax.
- Secrets can be generated at run-time and supplied to Grafana via file paths, without having to generate the whole configuration file from a template, which is often more awkward.
- Access to these secrets can be controlled with more granularity using UNIX user/group permissions when combined with encryption at rest.
- Certificate expiry can be handled more easily (just update the file vs. remove and re-add data source, going through awkward templating again, this time at runtime).

There is actually precedent for this already:

- For (I believe) historical reasons the PostgreSQL data source [does already support specifying a file](https://github.com/grafana/grafana/pull/30353). It would be nice if this could be extended to the general HTTPS data sources, resolving the inconsistency and covering this use case at the same time.
- The server-side key/cert can be supplied using files.

Is there a reason this isn't currently implemented like this? Fear of scope creep on the JSON data perhaps, because now it looks like *all* secrets might want to be specified in two ways? Would pull requests for this be welcome?

**Comment by gunjangarge** [comment]
In case you are stuck on this. 

You can use expanders, I recently found it out from a PR [25075](https://github.com/grafana/grafana/pull/25075/files#diff-26f85f1179bb43a675f61feda442ea0035ac4f408f18320acd934b97c72ea8d3)

Below worked for me.

```
      jsonData:
        tlsAuth: true
        tlsAuthWithCACert: true
        tlsSkipVerify: true
      secureJsonData:
        tlsCACert: $__file{/cert/ca.crt}
        tlsClientCert: $__file{/cert/tls.crt}
        tlsClientKey: $__file{/cert/tls.key}
```

TLS ca/cert/key is present in secret which is mounted on the mentioned path on grafana pod.
