### DISCUSSION TITLE
Provisioning post 8.x

### DISCUSSION THREAD

**Discussion by OlaSegha** [grafana/grafana#47160] [General]
Pre 8.x, we used providers to upload dashboards,  alert notification channels configurations and datasources to grafana instance. 
Post 8.x, while some of the providers still work; notifier provider seems to be broken (or non existent).... at the least, i can not see my configured notifier in the new instance. This might be due to the move to unified_alerting (which is fine) but i cant find any documentation around how to provision contact points or notification policies post 8.x.

Sample notifier provider (pre 8.x)
```
                notifiers:
                - name: Team
                  type: slack
                  uid: Team
                  org_name: Main Org.
                  is_default: true
                  send_reminder: true
                  frequency: 1h
                  disable_resolve_message: false       
                  settings:
                    url: [[.slack_url]]
                EOH

                destination = "local/provisioning/notifiers/team.yaml"
                }
```
Are we to expect this will be fixed or should we just move on to some other forms of provisioning?
