### DISCUSSION TITLE
Label Extraction from Graphite Series Names in Rules

### DISCUSSION THREAD

**Discussion by reyjrar** [grafana/grafana#47170] [Alerting]
In Data Sources, when I add a Graphite datasource, I can specify "Label Mappings" in the form:

```
servers.(location).(build).(hostname).(module).*
```

And it will extract labels for Loki, like:

`servers.dc1.webapp.webapp1.loadavg.01` to:

```yaml
---
location: "dc1"
build: "webapp"
hostname: "webapp1"
module: "loadavg"
```

Any chance we could get this exact behavior added to the Unified Alerting Rules? Ideally, there could be global mappings, as well as mappings specific to a particular alert, but honestly, I'd take either.
