### DISCUSSION TITLE
Grafana helm chart

### DISCUSSION THREAD

**Discussion by yaztriumph** [grafana/grafana#55944] [General]
Hi all, our stack is `EKS`, `Route53`, `Azure AD SSO` login, `Istio VirtualService`, `Grafana helm chart`.  
I was able make it work almost. When I login through domain name getting errors: 
After sometime it's kicking out the user. Below configuration files. 

Grafana pod logs error: 
```
level=error msg="Failed to look up user based on cookie" error="user token not found"
```

Browser Network
```
Search:

Request URL: https://grafana-istio.us-west-2.dev.equipifi.int/api/search 
Request Method: GET
Status Code: 401 
Remote Address: 10.6.7.181:443
Referrer Policy: strict-origin-when-cross-origin
Home:

Request URL: https://grafana-istio.us-west-2.dev.abc.int/api/dashboards/home
Request Method: GET
Status Code: 401 
Remote Address: 10.6.7.181:443
Referrer Policy: strict-origin-when-cross-origin
Frontend-metrics:

Request URL: https://grafana-istio.us-west-2.dev.abc.int/api/frontend-metrics
Request Method: POST
Status Code: 401 
Remote Address: 10.6.7.181:443
Referrer Policy: strict-origin-when-cross-origin
```

configmap: 
```
analytics]
check_for_updates = true
[auth.azuread]
allow_sign_up = true
allowed_groups = 123123123123123
auth_url = https://login.microsoftonline.com/68a2828c-12321-123123-123-e419adcdf65c/oauth2/v2.0/authorize
client_id = 12312312312312312
client_secret = 123213213123213
enabled = true
name = Azure AD
scopes = openid email profile
token_url = https://login.microsoftonline.com/1321232-e419adcdf65c/oauth2/v2.0/token
[grafana_net]
url = https://grafana.net
[log]
mode = console
[paths]
data = /var/lib/grafana/
logs = /var/log/grafana
plugins = /var/lib/grafana/plugins
provisioning = /etc/grafana/provisioning
[server]
domain = grafana.us-west-2.dev.abc.int
enable_gzip = true
enforce_domain = false
root_url = https://grafana.us-west-2.dev.abc.int
```
Virtualservice: 
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: grafana-vs
  namespace: istio-system
spec:
  gateways:
  - abc/gateway-gtw
  hosts:
  - grafana.us-west-2.dev.abc.int
  http:
  - route:
    - destination:
        host: grafana.istio-system.svc.cluster.local
        port:
          number: 3000
```

Also found [this](https://stackoverflow.com/questions/63689505/expose-grafana-publicly-using-istio) and implemented still didn't work.
