### DISCUSSION TITLE
Add curl package to docker image

### DISCUSSION THREAD

**Discussion by perrfect** [grafana/grafana#60936] [General]
Hello.
Please add `curl` package to grafana docker image.

I use docker image - `grafana/grafana-oss:latest` in a docker-compose file. And also use the next healthcheck:
```
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 1s
      timeout: 3s
      retries: 30
```
Everything works fine, but healthecheck all time generates errors in logs, which look like this:
```
level=error msg="Request error" error="Context.HTML:write tcp 127.0.0.1:3000->127.0.0.1:46474: write: broken pipe
level=error msg="Request error" error="Context.HTML:write tcp 127.0.0.1:3000->127.0.0.1:46531: write: broken pipe
```

It is happening, because `wget`  returns the next response:
`wget: can't open 'health': Permission denied`

I can use `curl` instead `wget` for the healthchek, but this package didn't install in the docker image and I want to use your image, not my own with preinstall `curl`.
