### DISCUSSION TITLE
Handle Alerts Provisioning in K8s in same way it's done for Dashboards and Datasources

### DISCUSSION THREAD

**Discussion by dragoangel** [grafana/grafana#61603] [Alerting]
### Idea
It will be much better if Grafana will have dedicated `grafana-sc-alerts` container which will have the possibility to find alerts configmaps in any K8s Namespace by `grafana_alert=1` label which will allow people to create own Helm charts with both Project, it's Grafana dashboards and alerts in the same place, in own Namespace.

### How its done now in Grafana 9.3
Mount `ConfigMap` to `/etc/grafana/provisioning/alerting` folder of Grafana container.

### Problematic of current implementation (Grafana 9.3)
Having all alerts in one Helm chart (for example `kube-prometheus-stack`) will create big secret quickly which will reach K8s API limits and developers will have to develop many Helms to separate alerts in a smaller charts. These charts need to be deployed in the same namespace with Grafana and Grafana needs to mount all of them in the provisioning folder via `values.yaml` of `kube-prometheus-stack`. This is not a nice approach that in end someday will lead to missed mount and not user friendly in general.

I'd better add a comment here: https://github.com/grafana/grafana/discussions/39510 but the discussion is locked.

**Comment by dragoangel** [comment]
Hi @JohnnyQQQQ, what you think about such idea?

**Reply by JohnnyQQQQ** [reply]
What would this container do? I'm not sure if I'm following along.

My understanding so far is as follows:

- The container would watch for the label on configmaps
- If any configmap exists with a matching label set, it would download those rules
- The API would be used to create/edit the rules on the grafana instance which is running in another container

Is this correct or am I missing something?

**Reply by dragoangel** [reply]
As I know from `grafana-sc-dashboards` (sc - is sidecar) logic:

- The container would watch for the label on configmaps (label name to watch can be adjusted) in own namespace (or in any/filtered namespaces)
- If any configmap exists with a matching label set, it would create files in provisioning folder on the pod (container `grafana-sc-dashboards` lives on same pod where `grafana` lives so can put files there)
- Provisioning as usual just watch for files in folder, take them and do their job

**Reply by JohnnyQQQQ** [reply]
For dashboards this might work, but for all other objects we have, this does not work, as we only load them once on startup. The dashboard provisioning on the other side is watching the directly and reloading every x seconds. 

As we have an API endpoint to reload files, you could create such a container for alerts or any other object type besides dashboards, which currently is outside our priorities.

**Reply by dragoangel** [reply]
Sorry, but I do not fully get why this not allows using proposed behavior.

Admin will need to drop pod to get settings reloaded, right?
Currently changing configmap with alerts without adding new files to configmap also does not recreate a Pod.

Automatic reload is cool and I by both hands up to this, but I don't think luck off it should be a blocker to manage alerts over sidecar. Plus:
- adding new more advanced provisioning way will not block usage of old one (mount configmaps as volume to provisioning directory with subpath filled up, or even without subpath if `readOnly` will set to `false` on mountpoint as it stated in Grafana docs).
- `grafana_datasource` is also added by sidecar, even though they load themselves only at the start 😊. As alerts can have big sizes it really will helpful to have the ability to scan them over many configmaps of many namespaces, even if they will be applied only after manual recreation of the pod.

Thank you in advance :)

**Reply by JohnnyQQQQ** [reply]
It is best practice to have a checksum in the annotations of your configmap so it will do a rolling update on any change.

As I said, it's possible but not one of our priorities.

**Reply by dragoangel** [reply]
Okay, I found actually how to handle it, it's just basically a luck of documentation and examples. Discussion can be closed.
```
grafana:
  sidecar:
    alerts:
      enabled: true
      label: grafana_alert
      labelValue: "1"
      searchNamespace: ALL
```

**Reply by dragoangel** [reply]
> Okay, I found actually how to handle it, it's just basically a luck of documentation and examples. Discussion can be closed.
> ```
> grafana:
>   sidecar:
>     alerts:
>       enabled: true
>       label: grafana_alert
>       labelValue: "1"
>       searchNamespace: ALL
> ```

@mwilfried

**Reply by mwilfried** [reply]
Thx you  @dragoangel  but I was talking about the configmap containing the rule(s). 

I've modified my  values.yml according to your, then I create a configmap with data the content of a rule , but nothing visible in the UI

I see the yaml or json created in /etc/grafana/provisioning/alerting

**Reply by dragoangel** [reply]
@mwilfried ok, clear, alert configmap should look something like this:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-rules
  labels:
    grafana_alert: "1"
    app: grafana
data:
  example.yaml: |-
    apiVersion: 1
    groups:
      - orgId: 1
        name: Example
        folder: Example
        interval: 60s
        rules:
          - uid: ExampleRule
            title: ExampleRule
            condition: B
            data:
              - refId: A
                queryType: ""
                relativeTimeRange:
                  from: 300
                  to: 0
                datasourceUid: elk
                model:
                  alias: some_metric
                  bucketAggs:
                    - field: '@timestamp'
                      id: "2"
                      settings:
                        interval: auto
                        min_doc_count: 0
                        trimEdges: 0
                      type: date_histogram
                  datasource:
                    type: elasticsearch
                    uid: elk
                  intervalMs: 1000
                  maxDataPoints: 43200
                  metrics:
                    - field: select field
                      id: "1"
                      type: count
                  query: '"some_query"'
                  refId: A
                  timeField: '@timestamp'
              - refId: B
                queryType: ""
                relativeTimeRange:
                  from: 300
                  to: 0
                datasourceUid: "-100"
                model:
                  conditions:
                    - evaluator:
                        params:
                          - 3
                          - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                          - A
                      reducer:
                        params: []
                        type: sum
                      type: query
                  datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                  expression: ""
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: B
                  type: classic_conditions
            noDataState: NoData
            execErrState: Error
            for: 1m
            annotations:
              __dashboardUid__: Example
              __panelId__: "1"
              summary: ExampleRuleSummary
              description: ExampleRuleDescription
            labels:
              namespace: example
              severity: critical
---
```
I usually create rules manually and use curl+yq to convert response from Grafana API JSON to YAML and use them in my configmaps.

**Reply by mwilfried** [reply]
@dragoangel  Thx, for your help ! I've found why it's not working. 

I get the alert through API,  then i convert the json to yaml but while doing this, I don't get all the part of the file needed by grafana, it is missing this part  :

```
    apiVersion: 1
    groups:
      - orgId: 1
        name: Example
        folder: Example
        interval: 60s
        rules:
          - uid: ExampleRule
            title: ExampleRule
            condition: B
```

Grafana 9.4.3 allows the export of Alert directly in yaml format with all the good informations (but not yet available in kube-prometheus-stack)
