### DISCUSSION TITLE
Configuring the Loki Ruler to be managed from Grafana

### DISCUSSION THREAD

**Discussion by spyder007** [grafana/grafana#62701] [Alerting]
I'm having a heck of a time getting the above to work. 

Previously, I was using `loki-distributed`, and the connection between Grafana and Loki worked when I enabled the ruler with appropriate S3 (Minio) backed storage.  

I recently stood up a new instance of Loki using the new `grafana/loki` Helm chart and moved my log collection to that.  I was not worried about log history and didn't want to migrate, so I just created a new one.  I pasted both the old and new values.yaml files below for reference.

The new Loki instance is running and collecting logs.  It has no problem acting as a Loki datasource for my Grafana instance is able to query all of the logs,  however, I am unable to create alerts.  When I attempt to save, I get the following error:

![image](https://user-images.githubusercontent.com/4701399/216091753-fda1130b-c91d-44f0-a598-927730dfeb8d.png)

I tried using `cortextool` to see the rules for my loki instance (and to see if it's even running), and I get these messages:
![image](https://user-images.githubusercontent.com/4701399/216092204-3e776e9c-79d0-4469-8c5f-fbe372dd329a.png)

There isn't much in the [Grafana documentation](https://grafana.com/docs/grafana/latest/alerting/alerting-rules/create-mimir-loki-managed-rule/) around the appropriate configuration needed for Grafana to create alerts, other than ensuring that I'm not using local storage.  As best I can tell, I have S3 storage configured correctly, but there is no data in the bucket.  I also don't see any pods that are running the ruler, are those now handled via the read/write nodes?

Do i have to pre-seed this ruler with a fake group, rule, or alert in order for Grafana to be able to add/edit alerts?

My old `loki-distributed` values.yaml:
```yaml
loki-distributed:
  querier:
    autoscaling:
      enabled: false
    extraArgs:
      - -config.expand-env=true
    extraEnvFrom:
      - secretRef:
          name: minio-secret
    persistence:
      enabled: true
      storageClass: nfs-client
  ingester:
    autoscaling:
      enabled: false
    extraArgs:
      - -config.expand-env=true
    extraEnvFrom:
      - secretRef:
          name: minio-secret
    persistence:
      enabled: true
      storageClass: nfs-client
  distributor:
    autoscaling:
      enabled: false
    extraArgs:
      - -config.expand-env=true
    extraEnvFrom:
      - secretRef:
          name: minio-secret
  queryFrontend:
    autoscaling:
      enabled: false
    extraArgs:
      - -config.expand-env=true
    extraEnvFrom:
      - secretRef:
          name: minio-secret
  gateway:
    autoscaling:
      enabled: false
    ingress:
      enabled: true
      hosts:
        - host: "loki.mattgerega.net"
          paths:
            - path: /
              pathType: Prefix
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/service-upstream: "true"
      tls: []
  ruler:
    enabled: true
    persistence:
      enabled: true
      storageClass: nfs-client
    extraArgs:
      - -config.expand-env=true
    extraEnvFrom:
      - secretRef:
          name: minio-secret
  loki:
    podAnnotations: 
      linkerd.io/inject: enabled
    authEnabled: false
    revisionHistoryLimit: 1
    structuredConfig:
      storage_config:
        boltdb_shipper:
          cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
          shared_store: s3
        aws:
          s3: <my_minio_endpoint>
          s3forcepathstyle: true

      table_manager:
        retention_deletes_enabled: true
        retention_period: 168h

      schema_config:
        configs:
        - from: 2020-05-15
          store: boltdb-shipper
          object_store: aws
          schema: v11
          index:
            prefix: index_
            period: 24h
          chunks:
            prefix: chunk

      limits_config:
        retention_period: 48h
        retention_stream:
        - selector: '{namespace="argocd"}'
          priority: 1
          period: 24h
      ruler:
        storage:
          type: s3
          s3:
            s3: <my_mino_endpoint>
            s3forcepathstyle: true

  serviceMonitor:
    enabled: true
    interval: 1m
    scrapeTimeout: 30s

```

My new `loki` values.yaml
```yaml
loki:
  loki:
    storage:
      bucketNames:
        chunks: loki-chunks
        ruler: loki-ruler
        admin: loki-admin
      type: s3
      s3:
        accessKeyId: ${MINIO_USERNAME}
        secretAccessKey: ${MINIO_PASSWORD}
        endpoint: <minio_endpoint>
        s3ForcePathStyle: true
        insecure: true
    auth_enabled: false
    structuredConfig:
      table_manager:
        retention_deletes_enabled: true
        retention_period: 168h

      schema_config:
        configs:
        - from: 2023-01-01
          store: boltdb-shipper
          object_store: s3
          schema: v11
          index:
            prefix: index_
            period: 24h
          chunks:
            prefix: chunk

      limits_config:
        retention_period: 48h
        retention_stream:
        - selector: '{namespace="argocd"}'
          priority: 1
          period: 24h
    rulerConfig:
      alertmanager_url: https://mimir.mattgerega.net

  minio:
    enabled: false
  write:
    extraArgs:
      - -config.expand-env=true
    extraEnvFrom:
      - secretRef:
          name: minio-secret
    persistence:
      enabled: true
      storageClass: nfs-client
  read:
    extraArgs:
      - -config.expand-env=true
    extraEnvFrom:
      - secretRef:
          name: minio-secret
    persistence:
      enabled: true
      storageClass: nfs-client
  backend:
    extraArgs:
      - -config.expand-env=true
    extraEnvFrom:
      - secretRef:
          name: minio-secret
    persistence:
      enabled: true
      storageClass: nfs-client
  gateway:
    autoscaling:
      enabled: false
    ingress:
      enabled: true
      hosts:
        - host: "loki.mattgerega.net"
          paths:
            - path: /
              pathType: Prefix
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/service-upstream: "true"
      tls: []
  monitoring:
    selfMonitoring:
      enabled: false
      grafanaAgent:
        installOperator: false
    lokiCanary:
      enabled: false
    serviceMonitor:
      enabled: true
      interval: 1m
      scrapeTimeout: 30s
  test:
    enabled: false
```
