### DISCUSSION TITLE
How to provision dashboards from json or gnetId using the __inputs notation?

### DISCUSSION THREAD

**Discussion by Dunge** [grafana/grafana#67075] [Dashboards, Panels & Visualizations]
When using the UI, you click the import button, provide the json file or the gnetID and press import, it ask you to select your datasource and it works.

I managed to get my dashboard provisioned automatically from a Kubernetes helm deployment. Mine using the sidecar and a configmap, and others using gnetID in the values.yaml files like this:

```
  dashboardProviders:
    dashboardproviders.yaml:
     apiVersion: 1
     providers:
     - name: 'imported'
       orgId: 1
       folder: 'imported'
       type: file
       disableDeletion: true
       editable: true
       options:
         path: /var/lib/grafana/dashboards/standard

  dashboards:
    imported:
      NodeExporter:
        gnetId: 1860
      AspNet:
        gnetId: 10915
```

The dashboards appear in the application, but you get errors about DS_PROMETHEUS being undefined or what not. Some works, some don't. Error is always a bit different. In the case of the ASP Net one above, variable is ${DS_GRAFANACLOUD-SANDERSAARES-PROM}. For NodeExporter it's ${DS_LOCALHOST}, etc.

I see in the json files these variables are set under the `__inputs` section and seems to point to the prometheus data source, why isn't it handled?

I tried to add the variables under the `dashboards` section above for each. Does not seems to be working. I also tried adding simply "datasource" as I see in some examples, not working either.

**Comment by Dunge** [comment]
Thanks to @krapie in #10786 I managed to get it working. The solution is to use name/value pairs for the variables under datasource. Also specifying the revision is important otherwise it takes the oldest one, and not the latest.

```
      NodeExporter:
        gnetId: 1860
        revision: 31
        datasource:
         - name: DS_PROMETHEUS
           value: prometheus
```
