### DISCUSSION TITLE
How to disable grafana alerts creation for specific datasource?

### DISCUSSION THREAD

**Discussion by azhurbilo** [grafana/grafana#67281] [Alerting]
Usecase: I want reuse Prometheus + Alertmanager from kube-prometheus-stack helm and
in grafana UI visualise prometheus/alertmanager alerts as read only
but leave ability to create grafana alerts for other datasources (Google Cloud Monitoring for example)

I disabled "manageAlerts" for datasource
```
- name: Hot Metrics (Prometheus)
      type: prometheus
      url: http://****:9090/
      access: proxy
      jsonData:
        manageAlerts: false
```
<img width="1005" alt="gr-alerts-2" src="https://user-images.githubusercontent.com/6387460/234574968-0d986d9e-834f-4af0-be5f-5ef21fcc940b.png">

but I am still is able to create alerts from Grafana UI

<img width="942" alt="grafana-alerts-1" src="https://user-images.githubusercontent.com/6387460/234575050-02d801cc-1b05-48bd-b5b0-2faafd4bdb33.png">

expected result: "Hot Metrics (Prometheus)" is not available for alerts creation in Grafana Alerting view -> "New alert rule"

grafana version: v9.3.6
