### DISCUSSION TITLE
Private Datasource Connect (PDC) in Grafana

### DISCUSSION THREAD

**Discussion by leandro-deveikis** [grafana/grafana#69754] [General]
## Introduction:
The Private Datasource Connect feature enables customers to effortlessly connect to their own data sources. By utilizing a Socks connection over SSH, Grafana's lightweight PDC agent establishes a secure and encrypted connection to databases and other datasources, whether they are running in VPCs or on-premises. This connectivity enables users to easily create and visualize dashboards, run alerts, and leverage any other feature provided by Grafana Cloud.

## Purpose of this Discussion:
In line with our commitment to open-source software (OSS), we have initiated this Discussion to encourage feedback from the community. We value your input as it helps us continually enhance Grafana and deliver an exceptional user experience.

To learn more about the implementation of Private Datasource Connect, we invite you to explore the documentation, that provides a step-by-step tutorial on configuring PDC. Please refer to the following resource: [Configure Grafana private data source connect](https://grafana.com/docs/grafana-cloud/data-configuration/configure-private-datasource-connect/)

The documentation currently includes a list of supported datasources, but please note that this list is not definitive. We are actively working to expand the range of supported datasources.

**Comment by rminderhoud** [comment]
Thank you for this feature, I just implemented it and it works well. A much better solution than needing to allow Grafana Clouds 200+ IP addresses access to some managed services (e.g. hosted databases).

**Reply by leandro-deveikis** [reply]
Thanks for your feedback @rminderhoud :smile:

**Comment by tekicode** [comment]
We've been utilizing PDC in our Non-Production Thanos environment.

It appears that the agent can run for such a duration that some key internal to it expires. There's no error on the agent side, but Grafana Cloud reports an error connecting to the PDC Datasource. Each time this is remedied by restarting the agent.

Is there anything we should be configuring to make this a little more self-healing?
<details><summary>Here's the current YAML. - Click</summary>

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: grafana-pdc-agent
    name: grafana-pdc-agent
  name: grafana-pdc-agent
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: grafana-pdc-agent
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: grafana-pdc-agent
    spec:
      containers:
      - args:
        - -cluster
        - $(CLUSTER)
        - -token
        - $(TOKEN)
        - -gcloud-hosted-grafana-id
        - $(HOSTED_GRAFANA_ID)
        env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: grafana-pdc-agent
        - name: CLUSTER
          valueFrom:
            secretKeyRef:
              key: cluster
              name: grafana-pdc-agent
        - name: HOSTED_GRAFANA_ID
          valueFrom:
            secretKeyRef:
              key: hosted-grafana-id
              name: grafana-pdc-agent
        image: grafana/pdc-agent:latest
        imagePullPolicy: Always
        name: grafana-pdc-agent
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          privileged: false
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 30000
        runAsGroup: 30000
        runAsUser: 30000
      terminationGracePeriodSeconds: 30
```
</details>
