### ISSUE TITLE
plugin installation & 'get version' timeout (TLS Handshake Failure)

### ISSUE THREAD

**Issue by germebl** [grafana/grafana#100103]
### What happened?

This issue was unfortunately closed with giving up:
https://github.com/grafana/grafana/issues/13920

Grafana fails to fetch plugins or updates from https://grafana.com. The following errors appear in the logs:
```
logger=plugin.angulardetectorsprovider.dynamic t=2025-02-05T07:46:44.895827409Z level=error msg="Error while updating detectors" error="fetch: http do: Get \"https://grafana.com/api/plugins/angular_patterns\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
logger=plugin.backgroundinstaller t=2025-02-05T07:46:44.895855392Z level=error msg="Failed to install plugin" pluginId=grafana-pyroscope-app version= error="Get \"https://grafana.com/api/plugins/grafana-pyroscope-app/versions\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
logger=grafana.update.checker t=2025-02-05T07:46:44.956320289Z level=error msg="Update check failed" error="failed to get stable version from grafana.com: Get \"https://grafana.com/api/grafana/versions/stable\": net/http: TLS handshake timeout" duration=10.062517106s
```

**Running `grafana cli plugins list-remote` and `grafana cli plugins install grafana-pyroscope-app` inside the container works just fine. When using curl to determine if i can get a HEAD, its responding instantly fine.**

### What did you expect to happen?

Grafana should be able to connect to grafana.com to download plugins and get the stable version.

### Did this work before?

Nope, since 2018 - someone gave up:
https://github.com/grafana/grafana/issues/13920

### How do we reproduce it?

1. Just start a Grafana Container with Docker Compose
2. Check Logs

### Environment (with versions)?

Grafana: 11.5.1
OS: Docker version 27.5.1, build 9f9e405
Browser: Unrelated
Network: Bridge / Host (both tested)

### Grafana platform?

Docker

**Comment by tolzhabayev** [comment]
Can you provide an example docker compose file to reproduce this?

Here is one I am using and it works just fine

```
services:
  grafana:    
    container_name: grafana
    image: grafana/grafana:11.5.1
    pull_policy: always
    ports:
      - 3000:3000
```

log excerpt: 
```
grafana  | logger=plugin.angulardetectorsprovider.dynamic t=2025-02-05T10:57:34.716992505Z level=info msg="Patterns update finished" duration=59.788292ms
grafana  | logger=installer.fs t=2025-02-05T10:57:35.533617339Z level=info msg="Downloaded and extracted grafana-pyroscope-app v0.1.19 zip successfully to /var/lib/grafana/plugins/grafana-pyroscope-app"

```

**Comment by tolzhabayev** [comment]
It works for me the same way as our docker compose files are quite similar. 

> We are behind a company Firewall and Outbound is working (otherwise the curl and grafana cli commands wouldnt work).
As you might have guessed this is where I would see the issue coming from, I would try this workaround https://github.com/grafana/grafana/issues/13920#issuecomment-444487179

Basically:

```
services:
  grafana:
    image: grafana/grafana:11.5.1
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_DEFAULT_APP_MODE='production'
      - GF_DEFAULT_INSTANCE_NAME='grafana'
      - GF_SECURITY_ADMIN_USER='admin'
      - GF_SECURITY_ADMIN_PASSWORD='admin123'
      - GF_LOG_LEVEL='warn'
      - GODEBUG=netdns=cgo
```

**Comment by jseiser** [comment]
@germebl 

Any chance you are behind a suricata  firewall? Like the AWS Network Firewall?  because I believe go lang 1.23 breaks this.

https://github.com/grafana/grafana/issues/100217

If you tried 11.2 grafana, I wonder if it would work.

**Comment by germebl** [comment]
Hey,

so we are dont using a Suricata Firewall, its a OPNsense. Tried 11.2.0 and 11.2.6 - still the same problem. Also tried both GODEBUG, even if it is not a firewall that uses golang.

**Comment by tolzhabayev** [comment]
@germebl unfortunately then we don't really have an idea on how we can help - unless you can somehow reproduce it in docker composer outside of your network / firewall too.

**Comment by tolzhabayev** [comment]
@germebl this does indeed feel weird that UI installation works as well as the cli, the only thing I can think of is that for some reason there is no outbound connection for this container during grafana startup for some reason.

I can only suggest to try out non-grafana-code specific outbound connections during startup to see if that's the case.
For example try just running curl:

```
services:
  curl:
    image: curlimages/curl:latest
    container_name: curl
    ports:
      - "3000:3000"
    command: >-
      https://grafana.com/api/plugins/angular_patterns
```
