### ISSUE TITLE
Alerting: channel_not_found error on image upload to slack

### ISSUE THREAD

**Issue by agathalunac** [grafana/grafana#100283]
### What happened?

https://github.com/grafana/alerting/issues/255 this issue was resolved in version 11.5.0

but after the image update I'm getting this error:

```
logger=ngalert.notifier.slack notifierUID=xxx alert="test image[xxxx][active]" t=2025-02-07T14:38:40.501197973Z level=error msg="Failed to attach image to notification" error="failed to send request: channel_not_found"
logger=ngalert.notifier.slack notifierUID=xx t=2025-02-07T14:38:40.501300236Z level=error msg="Failed to upload image" err="failed to send request: channel_not_found"
```

The channel exists and I receive the alert on my channel, the only thing missing is the image

ps.: bot is a member of the channel

```
apiVersion: 1
contactPoints:
    - orgId: 1
      name: my-contact-point
      receivers:
        - uid: xxxxxxxx
          type: slack
          settings:
            recipient: my-channel-name
            token: my-slack-bot-token
            username: Grafana Alerts
          disableResolveMessage: false
```

My bot has the following permissions:

```
[chat:write]

[chat:write.customize]

[files:write]

[groups:read]

[incoming-webhook]

[usergroups:read]

[users:read]
```

### What did you expect to happen?

Receive the alert image in my slack channel

### Did this work before?

No, I'm trying to include grafana-image-renderer now

### How do we reproduce it?

1. grafana 11.5.0
2. grafana-image-renderer 3.11.6
3. Slack channel and bot created this year

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

Kubernetes
