### ISSUE TITLE
Config: Wrong subPath config result in endless loop

### ISSUE THREAD

**Issue by yincongcyincong** [grafana/grafana#100706]
### What happened?

```
# The full public facing url
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana

# Serve Grafana from subpath specified in `root_url` setting. By default it is set to `false` for compatibility reasons.
serve_from_sub_path = false
```
setting this config, the endless login will appear.

### What did you expect to happen?

no endless login 

### Did this work before?

i don't know

### How do we reproduce it?

1. use config i post
2. enter localhost:3000
3.

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 11.5.1
OS: macos
Browser: chrome

### Grafana platform?

None

**Comment by ChilledSlim** [comment]
See the same thing in a basic config (no changes made to config, out of box, first start) with traefik:

```
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - /srv/grafana/storage:/var/lib/grafana
    user: '0'
    environment:
      - GF_SERVER_ROOT_URL=https://host.domain.com/grafana/
      - GF_PLUGINS_PREINSTALL=grafana-clock-panel
    labels:
      - 'traefik.enable=true'
      - "traefik.http.routers.grafana.entryPoints=https"
      - 'traefik.http.routers.grafana.tls=true'
      - 'traefik.http.routers.grafana.rule=Host(`host.domain.com`) && PathPrefix(`/grafana`)'
      - "traefik.http.routers.grafana.middlewares=authelia@docker"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
```

Going to https://host.domain.com/grafana I get

_`https://host.domain.com/grafana/login?redirectTo=%2Flogin%3FredirectTo%3D%252Flogin%253FredirectTo%253D%25252Flogin%25253FredirectTo%25253D%2525252Flogin%2525253FredirectTo%2525253D%252525252Flogin%252525253FredirectTo%252525253D%25252525252Flogin%25252525253FredirectTo%25252525253D%2525252525252Flogin%2525252525253FredirectTo%2525252525253D%252525252525252Flogin%252525252525253FredirectTo%252525252525253D%25252525252525252Flogin%25252525252525253FredirectTo%25252525252525253D%2525252525252525252Flogin%2525252525252525253FredirectTo%2525252525252525253D%252525252525252525252Flogin%252525252525252525253FredirectTo%252525252525252525253D%25252525252525252525252Flogin%25252525252525252525253FredirectTo%25252525252525252525253D%2525252525252525252525252Flogin%2525252525252525252525253FredirectTo%2525252525252525252525253D%252525252525252525252525252Flogin%252525252525252525252525253FredirectTo%252525252525252525252525253D%25252525252525252525252525252Flogin%25252525252525252525252525253FredirectTo%25252525252525252525252525253D%2525252525252525252525252525252Flogin%2525252525252525252525252525253FredirectTo%2525252525252525252525252525253D%252525252525252525252525252525252Flogin%252525252525252525252525252525253FredirectTo%252525252525252525252525252525253D%25252525252525252525252525252525252Flogin%25252525252525252525252525252525253FredirectTo%25252525252525252525252525252525253D%2525252525252525252525252525252525252Flogin%2525252525252525252525252525252525253FredirectTo%2525252525252525252525252525252525253D%252525252525252525252525252525252525252Flogin%252525252525252525252525252525252525253FredirectTo%252525252525252525252525252525252525253D%25252525252525252525252525252525252525252Flogin%25252525252525252525252525252525252525253FredirectTo%25252525252525252525252525252525252525253D%2525252525252525252525252525252525252525252Flogin%2525252525252525252525252525252525252525253FredirectTo%2525252525252525252525252525252525252525253D%252525252525252525252525252525252525252525252Flogin%252525252525252525252525252525252525252525253FredirectTo%252525252525252525252525252525252525252525253D%25252525252525252525252525252525252525252525252Flogin%25252525252525252525252525252525252525252525253FredirectTo%25252525252525252525252525252525252525252525253D%2525252525252525252525252525252525252525252525252Flogin%2525252525252525252525252525252525252525252525253FredirectTo%2525252525252525252525252525252525252525252525253D%252525252525252525252525252525252525252525252525252Flogin%252525252525252525252525252525252525252525252525253FredirectTo%252525252525252525252525252525252525252525252525253D%25252525252525252525252525252525252525252525252525252Flogin%25252525252525252525252525252525252525252525252525253FredirectTo%25252525252525252525252525252525252525252525252525253D%2525252525252525252525252525252525252525252525252525252Flogin%2525252525252525252525252525252525252525252525252525253FredirectTo%2525252525252525252525252525252525252525252525252525253D%252525252525252525252525252525252525252525252525252525252Flogin`_

until it says that the "431 Request Header Fields Too Large"

**Comment by ChilledSlim** [comment]
Fixed with: adding a strip pathprefix (which adds the X-Forwarded-Prefix header) and adding it as a middleware, but ideally grafana should handle this from the headers
```
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - /srv/grafana/storage:/var/lib/grafana
    user: '0'
    environment:
      - GF_SERVER_ROOT_URL=https://host.domain.com/grafana/
      - GF_PLUGINS_PREINSTALL=grafana-clock-panel
    labels:
      - 'traefik.enable=true'
      - "traefik.http.middlewares.stripprefix.stripprefixregex.regex=\\/([^/])+"
      - "traefik.http.routers.grafana.entryPoints=https"
      - 'traefik.http.routers.grafana.tls=true'
      - 'traefik.http.routers.grafana.rule=Host(`host.domain.com`) && PathPrefix(`/grafana`)'
      - "traefik.http.routers.grafana.middlewares=authelia@docker,stripprefix"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
```
