### ISSUE TITLE
Alerting: Link to Panel is generated wrong (superflouis /d/d path segment)

### ISSUE THREAD

**Issue by senpro-ingwersenk** [grafana/grafana#101203]
### What happened?

When clicking the link to open the panel specified in the alert, the URL to reach the dashboard and panel ends up with an additional `/d` segment in the URL, breaking the forwarding.

In the alert view, the link is: `https://grafana.ourinstance.tld/d/f6e21d50-84c2-4c3e-80a6-5be1451bd5ab?orgId=20&viewPanel=49` which gets redirected to `https://grafana.ourinstance.tld/d/d/f6e21d50-84c2-4c3e-80a6-5be1451bd5ab?orgId=20&from=now-6h&to=now&timezone=browser`

Notice this bit:
```
tld/d/d/f6e2
   ^^^^
```

Manually removing the additional `/d` works.

Panel config (`jq ".panels[] | select(.id == "49")"`):
```json
{
  "datasource": {
    "type": "influxdb",
    "uid": "${datasource}"
  },
  "fieldConfig": {
    "defaults": {
      "color": {
        "mode": "palette-classic"
      },
      "custom": {
        "axisBorderShow": false,
        "axisCenteredZero": false,
        "axisColorMode": "text",
        "axisLabel": "",
        "axisPlacement": "auto",
        "barAlignment": 0,
        "barWidthFactor": 0.6,
        "drawStyle": "line",
        "fillOpacity": 0,
        "gradientMode": "opacity",
        "hideFrom": {
          "legend": false,
          "tooltip": false,
          "viz": false
        },
        "insertNulls": false,
        "lineInterpolation": "linear",
        "lineWidth": 1,
        "pointSize": 5,
        "scaleDistribution": {
          "type": "linear"
        },
        "showPoints": "never",
        "spanNulls": false,
        "stacking": {
          "group": "A",
          "mode": "none"
        },
        "thresholdsStyle": {
          "mode": "off"
        }
      },
      "displayName": "${__field.labels.host}",
      "links": [],
      "mappings": [],
      "max": 100,
      "min": 0,
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          },
          {
            "color": "red",
            "value": 80
          }
        ]
      },
      "unit": "percent"
    },
    "overrides": []
  },
  "gridPos": {
    "h": 9,
    "w": 8,
    "x": 8,
    "y": 25
  },
  "hideTimeOverride": false,
  "id": 49,
  "options": {
    "legend": {
      "calcs": [
        "mean",
        "lastNotNull",
        "max"
      ],
      "displayMode": "list",
      "placement": "right",
      "showLegend": false
    },
    "tooltip": {
      "mode": "multi",
      "sort": "none"
    }
  },
  "pluginVersion": "9.0.1",
  "targets": [
    {
      "datasource": {
        "type": "influxdb",
        "uid": "${datasource}"
      },
      "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wmi.Win32_OperatingSystem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"FreePhysicalMemory\" or r[\"_field\"] == \"TotalVisibleMemorySize\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"client\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with _value: (float(v: r.TotalVisibleMemorySize) - float(v: r.FreePhysicalMemory)) / float(v: r.TotalVisibleMemorySize) * 100.0}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
      "refId": "main"
    }
  ],
  "title": "Memory Usage (Client)",
  "type": "timeseries"
}
```

Alert config:
```yaml
- orgId: 20
      name: Windows (Clients)
      folder: Microsoft Corporation
      interval: 1m
      rules:
        - uid: wlzli-msWinCliMemWarn
          title: Memory Usage (Client) (Warning)
          condition: condition
          data:
            - refId: main
              relativeTimeRange:
                from: 3600
                to: 0
              datasourceUid: wlzli-microsoft
              model:
                datasource:
                    type: influxdb
                    uid: wlzli-microsoft
                intervalMs: 1000
                maxDataPoints: 43200
                query: "from(bucket: \"microsoft\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wmi.Win32_OperatingSystem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"FreePhysicalMemory\" or r[\"_field\"] == \"TotalVisibleMemorySize\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"client\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with _value: (float(v: r.TotalVisibleMemorySize) - float(v: r.FreePhysicalMemory)) / float(v: r.TotalVisibleMemorySize) * 100.0}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
                refId: main
            - refId: alert
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - A
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: main
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: alert
                type: reduce
            - refId: condition
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 90
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: alert
                intervalMs: 1000
                maxDataPoints: 43200
                refId: condition
                type: threshold
          dashboardUid: f6e21d50-84c2-4c3e-80a6-5be1451bd5ab
          panelId: 49
          noDataState: OK
          execErrState: Error
          for: 5m
          annotations:
            __dashboardUid__: f6e21d50-84c2-4c3e-80a6-5be1451bd5ab
            __panelId__: "49"
          labels:
            customer: wlzli
            severity: WARN
          isPaused: false
```

this alert is provisioned, and so is the dashboard.

Additionally:
```
> jq ".title, .uid, .annotations, .links"
"Windows (Clients)"
"f6e21d50-84c2-4c3e-80a6-5be1451bd5ab"
{
  "list": [
    {
      "builtIn": 1,
      "datasource": {
        "type": "datasource",
        "uid": "grafana"
      },
      "enable": false,
      "hide": true,
      "iconColor": "rgba(0, 211, 255, 1)",
      "name": "Annotations & Alerts",
      "target": {
        "limit": 100,
        "matchAny": false,
        "tags": [],
        "type": "tags"
      },
      "type": "dashboard"
    }
  ]
}
[
  {
    "asDropdown": false,
    "icon": "bolt",
    "includeVars": true,
    "keepTime": true,
    "tags": [],
    "targetBlank": true,
    "title": "Report",
    "tooltip": "",
    "type": "link",
    "url": "https://reporter.grafana.ourinstance.tld/render?"
  }
]
```

### What did you expect to happen?

We expected to click the link to visit the panel containing the data causing the alert.

### Did this work before?

Yes. This worked before I updated Grafana from 11.4.0 to 11.5.1.

### How do we reproduce it?

1. Install, enable and configure OnCall
2. Observe an alert and open it by clicking the list entry
3. Click the link "View associated panel"

### Is the bug inside a dashboard panel?

Kind of? Yes? But also no - this is just _linking to_ a panel...

### Environment (with versions)?

Grafana: 11.5.1
OS: NixOS 24.05
Browser: Brave (but also confirmed on Firefox and Chrome)

### Grafana platform?

Kubernetes

### Datasource(s)?

InfluxDB
