### ISSUE TITLE
Folder-level RBAC is enforced in non-Enterprise deployments

### ISSUE THREAD

**Issue by dobroliubov** [grafana/grafana#101308]
### What happened?

**What I have:**

- self-hosted non-licensed grafana deployed in Kubernetes via official helm chart (chart version 8.10.1, app version 11.5.2)
- dashboards sidecar enabled, and grafana successfully discovers and creates dashboards from ConfigMap resources
- there are users with Admin and Viewer rights using this Grafana instance

**What I do:**
- create ConfigMap with dashboard that has folder defined through annotation. This folder doesn't exist in grafana yet:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: dashboard
  namespace: namespace  
  labels:
    grafana_dashboard: 'true'
  annotations:
    grafana_folder: my-folder
data:
  dashboard.json: |
    <DASHBOARD_JSON>
```

**What I expect:**
- grafana creates new folder named "my-folder"
- dashboard is placed under created folder
- access rights on folder level are not enforced, and grafana users with Admin and Viewer rights both can use this folder and open dashboards stored in it

**What I see in fact:**
- folder is created
- only users with Admin rights can access dashboard
- Viewers can't open created dashboard

[This ticket](https://github.com/grafana/grafana/issues/99448) mentions that RBAC on folder level is an Enterpise-only feature. Official documentation says the same.

### What did you expect to happen?

My expectation: RBAC on folder level should not be enforced. 

### Did this work before?

Worked as expected in older grafana versions (11.0.x).

### How do we reproduce it?

1. Install grafana via helm chart with enabled dashboards sidecar.
2. Create ConfigMap with dashboard and unique folder definition.
3. Make sure that dashboard is created under new folder.
4. Check access rights for created folder. 

Default mapping says only Admin can access it.

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

helm chart version: 8.10.1
app version: 11.5.2

### Grafana platform?

Kubernetes
