### ISSUE TITLE
Multiple installations of the Grafana do not initialize empty postgres schemas on a shared logical database

### ISSUE THREAD

**Issue by dlydiard** [grafana/grafana#102160]
### What happened?

**Describe the bug**
We have multiple namespaces instantiating the `Grafana` CR (grafana operator). The first namespace, with its own schema in a shared Postgres database, installed correctly and created all tables from an empty schema. However, additional namespaces with separate Postgres schemas fail to create the necessary tables at startup.

**Version**
grafana-operator.v5.17.0

**To Reproduce**
```yaml
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  labels:
    dashboards: grafana
  name: grafana
  namespace: devlake
spec:
  config:
    auth:
      disable_login_form: 'false'
      login_cookie_name: grafana_session
    auth.anonymous:
      enabled: 'false'
    auth.basic:
      enabled: 'true'
    auth.ldap:
      config_file: /etc/grafana-ldap/ldap.toml
      enabled: 'true'
    log:
      level: info
      mode: console
    smtp:
      enabled: 'true'
      from_address: ...
      host: ...
      password: ...
      user: ...
  deployment:
    metadata: {}
    spec:
      replicas: 2
      template:
        metadata: {}
        spec:
          containers:
            - env:
                - name: GF_SECURITY_ADMIN_USER
                  valueFrom:
                    secretKeyRef:
                      key: user
                      name: root-password
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: token
                      name: root-password
                - name: GF_DATABASE_NAME
                  value: postgres
                - name: GF_DATABASE_TYPE
                  value: postgres
                - name: GF_DATABASE_HOST
                  valueFrom:
                    secretKeyRef:
                      key: host
                      name: postgres-static-credentials
                - name: GF_DATABASE_USER
                  valueFrom:
                    secretKeyRef:
                      key: username
                      name: postgres-static-credentials
                - name: GF_DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: postgres-static-credentials
                - name: GF_DATABASE_MAX_OPEN_CONN
                  value: '20'
                - name: GF_DATABASE_MAX_IDLE_CONN
                  value: '5'
              name: grafana
              resources:
                limits:
                  cpu: 250m
                  memory: 300Mi
                requests:
                  cpu: 100m
                  memory: 200Mi
              securityContext: {}
              volumeMounts:
                - mountPath: /etc/grafana-ldap
                  name: grafana-ldap
                  readOnly: true
          volumes:
            - name: grafana-ldap
              secret:
                secretName: ldap-config
  version: 'docker.io/grafana/grafana@sha256:a0f881232a6fb71a0554a47d0fe2203b6888fe77f4cefb7ea62bed7eb54e13c3'
status:
  adminUrl: 'http://grafana-service.devlake.svc:3000'
  datasources:
    - devlake/default-postgres/27e02ed2-f7d2-4dd2-b52b-d4ed33302826
  stage: complete
  stageStatus: success
  version: 11.3.0
```

Startup Logs:
```
logger=settings t=2025-02-26T15:55:01.839356419Z level=info msg="Starting Grafana" version=11.3.0 commit=d9455ff7db73b694db7d412e49a68bec767f2b5a branch=HEAD compiled=2025-02-26T15:55:01Z
logger=settings t=2025-02-26T15:55:01.839831058Z level=info msg="Config loaded from" file=/usr/share/grafana/conf/defaults.ini
logger=settings t=2025-02-26T15:55:01.839848293Z level=info msg="Config loaded from" file=/etc/grafana/grafana.ini
logger=settings t=2025-02-26T15:55:01.839855354Z level=info msg="Config overridden from command line" arg="default.paths.data=/var/lib/grafana"
logger=settings t=2025-02-26T15:55:01.839861678Z level=info msg="Config overridden from command line" arg="default.paths.logs=/var/log/grafana"
logger=settings t=2025-02-26T15:55:01.839867871Z level=info msg="Config overridden from command line" arg="default.paths.plugins=/var/lib/grafana/plugins"
logger=settings t=2025-02-26T15:55:01.839874703Z level=info msg="Config overridden from command line" arg="default.paths.provisioning=/etc/grafana/provisioning"
logger=settings t=2025-02-26T15:55:01.839881121Z level=info msg="Config overridden from command line" arg="default.log.mode=console"
logger=settings t=2025-02-26T15:55:01.839887628Z level=info msg="Config overridden from Environment variable" var="GF_PATHS_DATA=/var/lib/grafana"
logger=settings t=2025-02-26T15:55:01.839893795Z level=info msg="Config overridden from Environment variable" var="GF_PATHS_LOGS=/var/log/grafana"
logger=settings t=2025-02-26T15:55:01.839899897Z level=info msg="Config overridden from Environment variable" var="GF_PATHS_PLUGINS=/var/lib/grafana/plugins"
logger=settings t=2025-02-26T15:55:01.839905841Z level=info msg="Config overridden from Environment variable" var="GF_PATHS_PROVISIONING=/etc/grafana/provisioning"
logger=settings t=2025-02-26T15:55:01.839911577Z level=info msg="Config overridden from Environment variable" var="GF_DATABASE_TYPE=postgres"
logger=settings t=2025-02-26T15:55:01.839917414Z level=info msg="Config overridden from Environment variable" var="GF_DATABASE_HOST=aw-ue1-mt1-applications.cluster-cdm7r2qiijsl.us-east-1.rds.amazonaws.com"
logger=settings t=2025-02-26T15:55:01.839928957Z level=info msg="Config overridden from Environment variable" var="GF_DATABASE_NAME=postgres"
logger=settings t=2025-02-26T15:55:01.839934746Z level=info msg="Config overridden from Environment variable" var="GF_DATABASE_USER=devlake"
logger=settings t=2025-02-26T15:55:01.839941635Z level=info msg="Config overridden from Environment variable" var="GF_DATABASE_PASSWORD=*********"
logger=settings t=2025-02-26T15:55:01.839948398Z level=info msg="Config overridden from Environment variable" var="GF_DATABASE_MAX_IDLE_CONN=5"
logger=settings t=2025-02-26T15:55:01.839954552Z level=info msg="Config overridden from Environment variable" var="GF_DATABASE_MAX_OPEN_CONN=20"
logger=settings t=2025-02-26T15:55:01.839961146Z level=info msg="Config overridden from Environment variable" var="GF_SECURITY_ADMIN_USER=root"
logger=settings t=2025-02-26T15:55:01.839967491Z level=info msg="Config overridden from Environment variable" var="GF_SECURITY_ADMIN_PASSWORD=*********"
logger=settings t=2025-02-26T15:55:01.839974607Z level=info msg=Target target=[all]
logger=settings t=2025-02-26T15:55:01.839986477Z level=info msg="Path Home" path=/usr/share/grafana
logger=settings t=2025-02-26T15:55:01.839993084Z level=info msg="Path Data" path=/var/lib/grafana
logger=settings t=2025-02-26T15:55:01.839998514Z level=info msg="Path Logs" path=/var/log/grafana
logger=settings t=2025-02-26T15:55:01.840003723Z level=info msg="Path Plugins" path=/var/lib/grafana/plugins
logger=settings t=2025-02-26T15:55:01.840009558Z level=info msg="Path Provisioning" path=/etc/grafana/provisioning
logger=settings t=2025-02-26T15:55:01.840015278Z level=info msg="App mode production"
logger=featuremgmt t=2025-02-26T15:55:01.840628249Z level=info msg=FeatureToggles dashboardScene=true ssoSettingsApi=true topnav=true angularDeprecationUI=true influxdbBackendMigration=true alertingInsights=true kubernetesPlaylists=true recordedQueriesMulti=true panelMonitoring=true lokiStructuredMetadata=true promQLScope=true dashgpt=true prometheusConfigOverhaulAuth=true addFieldFromCalculationStatFunctions=true awsAsyncQueryCaching=true dashboardSceneForViewers=true prometheusAzureOverrideAudience=true recoveryThreshold=true groupToNestedTableTransformation=true openSearchBackendFlowEnabled=true lokiMetricDataplane=true correlations=true managedPluginsInstall=true dataplaneFrontendFallback=true alertingNoDataErrorExecution=true annotationPermissionUpdate=true prometheusMetricEncyclopedia=true logRowsPopoverMenu=true formatString=true transformationsVariableSupport=true accessControlOnCall=true lokiQuerySplitting=true autoMigrateXYChartPanel=true nestedFolders=true logsInfiniteScrolling=true cloudWatchCrossAccountQuerying=true exploreMetrics=true logsExploreTableVisualisation=true publicDashboardsScene=true pinNavItems=true dashboardSceneSolo=true lokiQueryHints=true tlsMemcached=true transformationsRedesign=true cloudWatchNewLabelParsing=true alertingSimplifiedRouting=true logsContextDatasourceUi=true publicDashboards=true notificationBanner=true cloudWatchRoundUpEndTime=true
logger=sqlstore t=2025-02-26T15:55:01.840724364Z level=info msg="Connecting to DB" dbtype=postgres
logger=migrator t=2025-02-26T15:55:01.858314533Z level=info msg="Locking database"
logger=migrator t=2025-02-26T15:55:01.861423849Z level=info msg="Starting DB migrations"
logger=migrator t=2025-02-26T15:55:01.879652392Z level=info msg="Unlocking database"
Error: ✗ pq: relation "migration_log" does not exist
```

To fix this issue i ran the following SQL, where `schema_name` is the target schema to initialize:
```
create sequence "schema_name".migration_log_id_seq as integer;
alter sequence "schema_name".migration_log_id_seq owner to "schema_name";

create table "schema_name".migration_log (
  id integer primary key not null default nextval('"schema_name".migration_log_id_seq'::regclass),
  migration_id character varying(255) not null,
  sql text not null,
  success boolean not null,
  error text not null,
  timestamp timestamp without time zone not null
);

alter table "schema_name".migration_log owner to "schema_name";

CREATE INDEX "UQE_user_login" ON schema_name.user (login);
CREATE INDEX "UQE_user_email" ON schema_name.user (email);
CREATE INDEX "IDX_temp_user_email" ON schema_name.temp_user (email);
CREATE INDEX "IDX_temp_user_org_id" ON schema_name.temp_user (org_id);
CREATE INDEX "IDX_temp_user_code" ON schema_name.temp_user (code);
CREATE INDEX "IDX_temp_user_status" ON schema_name.temp_user (status);
CREATE INDEX "UQE_api_key_key" ON schema_name.api_key (key);
CREATE INDEX "UQE_alert_rule_tag_alert_id_tag_id" ON schema_name.alert_rule_tag (alert_id, tag_id);
CREATE INDEX "UQE_annotation_tag_annotation_id_tag_id" ON schema_name.annotation_tag (annotation_id, tag_id);
CREATE INDEX "IDX_login_attempt_username" ON schema_name.login_attempt (username);
CREATE INDEX "UQE_alert_configuration_org_id" ON schema_name.alert_configuration (org_id);
CREATE INDEX "UQE_user_role_org_id_user_id_role_id" ON schema_name.user_role (org_id, user_id, role_id, created);
CREATE INDEX "IDX_correlation_uid" ON schema_name.correlation (uid);
CREATE INDEX "IDX_correlation_source_uid" ON schema_name.correlation (source_uid);
CREATE INDEX "UQE_seed_assignment_builtin_role_role_name" ON schema_name.seed_assignment (builtin_role, role_name) ;
```

In Postgres, each user sets their `search_path` to the target schema and has write access to it. After executing the SQL commands above, Grafana starts successfully, populates the `migration_log` table, and runs without issues.

**Runtime (please complete the following information):**

- OS: Linux
- Grafana Operator Version: 5.17.0
- Environment: OpenShift 4.15
- Deployment type: OpenShift OLM
- Postgres: 15.6 (RDS)

**Additional context**

### What did you expect to happen?

**Expected behavior**
Grafana should automatically create all tables during a fresh installation with an empty schema. This might be related to https://github.com/grafana/grafana/issues/27606

### Did this work before?

Only for the first instance of Grafana.

### How do we reproduce it?

1. Single postgres cluster with dedicated schemas per grafana installation.
2. Used Grafana Operator CRs to create new instances of Grafana in different namespace. Each instance of Grafana is configured to use a dedicated schema.
3. First instance of Grafana created all required tables. All subsequence instances fail to create initial tables. 
4. After manually creating the migration_log tables and indexes that the migration is trying to drop, Grafana started to work.

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

- OS: Linux
- Grafana Operator Version: 5.17.0
- Environment: OpenShift 4.15
- Deployment type: OpenShift OLM
- Postgres: 15.6 (RDS)

### Grafana platform?

Kubernetes
