### ISSUE TITLE
Datasources: Azure Monitor Datasource using workloadidentity helm configs do not auto complete fields

### ISSUE THREAD

**Issue by Swaps76** [grafana/grafana#102427]
### What happened?

Using the [docs](https://grafana.com/docs/grafana/latest/datasources/azure-monitor/) to create a helm template to configure azure monitor datasource using workload identity creates a datasource with authentication and default subscription fields in a semi or unfilled state;

![Image](https://github.com/user-attachments/assets/d28dcc85-e0fc-4bc4-a395-077a61044147)

When manually creating the same datasource in the UI, there is a requirement to first select 'Workload identity' or 'App Registration' in the authentication field, and to 'Load Subscriptions' so they may appear in the default subscription dropdown.  If the following json lines are added to the code, then the workloadidentity is properly filled in and we are able to click the buttons to load subscriptions.

```
          - name: azure-monitor-dashboard-dev
            type: grafana-azure-monitor-datasource
            access: proxy
            orgId: 1
            editable: true
            readOnly: false
            jsonData:
              azureAuthType: workloadidentity
              subscriptionId: "redacted"
            version: 1
```

This seems like a hack to be able to fill the fields outside of the code, by way of the lines;
```
            editable: true
            readOnly: false
```
Without these, the coded datasource does not preload auth/sub correctly, should it do so?

Thanks!

### What did you expect to happen?

The fields to be preloaded with Workload Identity and the subscriptions that the workload ID has access to.

### Did this work before?

It works when configured manually in the UI.

### How do we reproduce it?

1. Create all the necessary configuration for a workload id with access to a resource and respective annotations ont he service account and pod in the k8s cluster.
2. Create the azure monitor datasource via helm template as per docs.
3. In grafana check the datasource connection.

### Environment (with versions)?

Grafana: 11.4.1
OS: MAC OS 14.6.1
Browser: Chrome

### Grafana platform?

Kubernetes

### Datasource(s)?

Azure Monitor
