### ISSUE TITLE
Home Dashboard as config

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#10266]
Hi

As we have the new dashboard provisioning as file feature

it would be great to be able to set org level home dashboard from config file too.

**Comment by bergquist** [comment]
A little hesitant. I like the idea but right now I cant see how to add this in a simple way. 
grafana.ini does not work since it would not support orgs.
`conf/provisioning/sample.yaml` won't be so easy since it doesn't have a root level per org.
Adding it to the dashboard.json might work but that would seem very confusing. 

This might have to wait until we support creating orgs from configuration. If we ever decide to do that :)

**Comment by roidelapluie** [comment]
Here is my ansible code if someone needs this:

```
- uri:
    url: http://127.0.0.1:{{grafana_instance.port}}/api/dashboards/db/{{ grafana_instance.default_dashboard_slug }}
    headers:
      "X-WEBAUTH-USER": admin
    return_content: yes
  register: dashboard
  retries: 10
  delay: 1
  when: "grafana_instance.default_dashboard_slug is defined"
- uri:
    url: http://127.0.0.1:{{grafana_instance.port}}/api/org/preferences
    method: PUT
    body_format: json
    body: '{"homeDashboardId": {{dashboard.json.dashboard.id}} }'
    headers:
      Authorization: "{{grafana_instance.admin_token}}"
  when: "grafana_instance.default_dashboard_slug is defined"
```
