### ISSUE TITLE
Migration: initialization mysql database type failed with MariaDB

### ISSUE THREAD

**Issue by ThanatosDi** [grafana/grafana#102668]
### What happened?

I tried using Docker to create a docker-compose setup for Grafana and MariaDB, but I encountered an error during initialization. The following error message appeared:
```
logger=migrator t=2025-03-23T01:41:25.181901879+08:00 level=error msg="Executing migration failed" id="Rename table alert_rule_tag to alert_rule_tag_v1 - v1" error="Error 1025 (HY000): Error on rename of './grafana/alert_rule_tag' to './grafana/alert_rule_tag_v1' (errno: 194 \"Tablespace is missing for a table\")" duration=76.550338ms
logger=migrator t=2025-03-23T01:41:25.181958789+08:00 level=error msg="Exec failed" error="Error 1025 (HY000): Error on rename of './grafana/alert_rule_tag' to './grafana/alert_rule_tag_v1' (errno: 194 \"Tablespace is missing for a table\")" sql="ALTER TABLE `alert_rule_tag` RENAME TO `alert_rule_tag_v1`"
```

### What did you expect to happen?

finished the migration, let Grafana running.

### Did this work before?

No

### How do we reproduce it?

Here is my docker compose stack.
```yaml
networks:
  grafana-stack-network:
    name: grafana-stack-network
    driver: bridge
services:
  mariadb:
    image: mariadb:${MARIADB_VERSION:-11.7}
    container_name: mariadb
    volumes:
      - ${MARIADB_DATA}:/var/lib/mysql # 儲存 MariaDB 資料
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE:-grafana}
      - MARIADB_USER=${MARIADB_USER:-grafana}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    ports:
      - ${MARIADB_PORT:-3306}:3306
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - grafana-stack-network
  grafana:
    image: grafana/grafana-enterprise:${GRAFANA_VERSION:-latest}
    restart: unless-stopped
    depends_on:
      - mariadb
    volumes:
      - ${GRAFANA_DATA}:/var/lib/grafana
    environment:
      - GF_DATABASE_TYPE=mysql
      - GF_DATABASE_HOST=mariadb:3306
      - GF_DATABASE_NAME=${MARIADB_DATABASE:-grafana}
      - GF_DATABASE_USER=${MARIADB_USER:-grafana}
      - GF_DATABASE_PASSWORD=${MARIADB_PASSWORD}
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_FEATURE_TOGGLES_ENABLE=alertingSimplifiedRouting,alertingQueryAndExpressionsStepMode
      - TZ=${TIMEZONE}
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    ports:
      - "3000:3000"
    networks:
      - grafana-stack-network
```

### Environment (with versions)?

Grafana: 11.5.1
OS: Docker Desktop with windows 11
Browser: Chrome 134.0.6998.89 

### Grafana platform?

Docker
