### ISSUE TITLE
Grafana dashboards provisioner chooses wrong folder

### ISSUE THREAD

**Issue by justaskz** [grafana/grafana#102630]
### What happened?

I have this provisioner config:
```
---
apiVersion: 1
providers:
  - name: main
    orgId: 1
    type: file
    disableDeletion: false
    editable: false
    updateIntervalSeconds: 10
    options:
      path: /tmp/grafana/dashboards
      foldersFromFilesStructure: true
```

I put `dashboard.json` in `/tmp/grafana/dashboards/app/dashboard.json` folder. It provisions dashboard to `app` folder as expected.

However if I create `app` folder somewhere in Grafana file system like `dev/app`, it puts dashboard to that folder instead.

### What did you expect to happen?

If there is `dev/app` folder, it should still put dashboard in `app` folder.

### Did this work before?

Dont know

### How do we reproduce it?

I created simple docker compose project

https://github.com/justaskz/grafana-stack

### Environment (with versions)?

Grafana: 11.5.2
OS: Macos
Browser: Chrome

### Grafana platform?

Docker
