### ISSUE TITLE
Dashboards: The panel has moved out of place

### ISSUE THREAD

**Issue by DevOpsPop** [grafana/grafana#102672]
### What happened?

After update to 11.5.2 from 11.2.2 the panel has moved out of place. This is how it appears on all devices.
![Image](https://github.com/user-attachments/assets/34c89856-976e-4e97-90fc-645523ac788b)

For some reason this problem only appears in this dashboard, the others seem to work.
Attempts to move it back fail, because after pod restarting everything comes back. And when loading a dashboard from a provision file, a diff with the current changes is immediately displayed.
![Image](https://github.com/user-attachments/assets/5fd8ff4f-1c1d-4131-b6d1-6c8d6ea0469c)

### What did you expect to happen?

everything works fine, panel on right place

### Did this work before?

yes

### How do we reproduce it?

1.Load ELK dashboard from provider 
```
      - name: 'infrastructure'
        orgId: 1
        folder: 'Infrastructure'
        type: file
        disableDeletion: true
        editable: true
        options:
          path: /var/lib/grafana/dashboards/infrastructure
```
2. 

### Is the bug inside a dashboard panel?

[elasticsearch.json](https://github.com/user-attachments/files/19408430/elasticsearch_exporter_k8s.json)

### Environment (with versions)?

Grafana: 11.5.2
OS: Linux, MacOS, Windows.
Browser: Mozilla, Chrome, Safari

### Grafana platform?

Kubernetes
