### ISSUE TITLE
Dashboard privisioning does not create folder

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#10267]
Givent the following dashboard provisioning file

```
- name: 'abcdef'
  folder: 'ABC-DEF'
  type: file
  options:
   folder: /usr/share/grafana-dashboards/cinnic
```

The folder 'ABC-DEF' is not greated by Grafana; therefore dashboards are under the 'root' folder.
