### ISSUE TITLE
the configuration file passed through the YAML file does not take effect.

### ISSUE THREAD

**Issue by ixiaoyi93** [grafana/grafana#103167]
### What happened?

I defined the tracesToLogsV2 configuration in the datasources.yaml file, but when I viewed the data source configuration through grafana, it did not match what I defined.

My datasources.yaml content is as follows.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-data-source
  namespace: grafana-stack
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/version: "10.0.2"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      access: proxy
      basicAuth: false
      editable: false
      isDefault: true
      jsonData:
        httpMethod: GET
        httpHeaderName1: 'Authorization'
      secureJsonData:
        httpHeaderValue1: 'xxxxxxxx'
      orgId: 1
      type: prometheus
      uid: prometheus
      url: http://prometheus.url
      version: 1
    - name: Tempo
      access: proxy
      apiVersion: 1
      basicAuth: false
      editable: false
      isDefault: false
      orgId: 1
      type: tempo
      uid: tempo
      url: http://tempo-query-frontend:3100
      version: 1
      jsonData:
        httpMethod: GET
        serviceMap:
          datasourceUid: prometheus
        streamingEnabled:
          search: true
        nodeGraph:
          enabled: true
        traceQuery:
          timeShiftEnabled: true
          spanStartTimeShift: '-1h'
          spanEndTimeShift: '1h'
        spanBar:
          type: 'Tag'
          tag: 'http.path'
        tracesToLogsV2:
          datasourceUid: 'loki'
          spanStartTimeShift: '-1h'
          spanEndTimeShift: '1h'
          filterByTraceID: false
          filterBySpanID: false
          customQuery: true
          query: '{${__tags}} | trace_id="${__span.traceId}"'
```

The results seen from grafana datasource are as follows.

![Image](https://github.com/user-attachments/assets/6e15757d-af19-4beb-a930-93310e9dc57b)

### What did you expect to happen?

The configuration results viewed through grafana datasoure are consistent with what I defined.

### Did this work before?

I don't know.

### How do we reproduce it?

1. copy datasource.yaml
2.Mount the configuration into the grafana container directory as follows.
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: grafana-stack
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/version: "10.0.2"
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
      app.kubernetes.io/instance: grafana
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana
        app.kubernetes.io/instance: grafana
    spec:
      serviceAccountName: grafana
      automountServiceAccountToken: true
      securityContext:
        fsGroup: 472
        runAsGroup: 472
        runAsNonRoot: true
        runAsUser: 472
      hostAliases:
        - hostnames:
          - loki-gateway-test.alphalawyer.cn
          ip: 192.168.254.134
      initContainers:
        - name: init-chown-data
          image: "busybox:1.31.1"
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
              - CHOWN
            runAsNonRoot: false
            runAsUser: 0
            seccompProfile:
              type: RuntimeDefault
          command:
            - chown
            - -R
            - 472:472
            - /var/lib/grafana
          volumeMounts:
            - name: storage
              mountPath: "/var/lib/grafana"
      enableServiceLinks: true
      containers:
        - name: grafana
          image: "grafana:11.5.3-ubuntu"
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: config
              mountPath: "/etc/grafana/grafana.ini"
              subPath: grafana.ini
            - name: ldap
              mountPath: "/etc/grafana/ldap.toml"
              subPath: ldap.toml
            - name: storage
              mountPath: "/var/lib/grafana"
            - name: datasource
              mountPath: "/etc/grafana/provisioning/datasources/datasources.yaml"
              subPath: datasources.yaml
          ports:
            - name: grafana
              containerPort: 3000
              protocol: TCP
            - name: gossip-tcp
              containerPort: 9094
              protocol: TCP
            - name: gossip-udp
              containerPort: 9094
              protocol: UDP
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin-password
            - name: GF_FEATURE_TOGGLES_ENABLE
              value: traceqlEditor
            - name: GF_PATHS_DATA
              value: /var/lib/grafana/
            - name: GF_PATHS_LOGS
              value: /var/log/grafana
            - name: GF_PATHS_PLUGINS
              value: /var/lib/grafana/plugins
            - name: GF_PATHS_PROVISIONING
              value: /etc/grafana/provisioning
            - name: GF_INSTALL_PLUGINS
              value: "grafana-exploretraces-app-0.2.3.zip;grafana-lokiexplore-app-1.0.8.zip"
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 60
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
      volumes:
        - name: config
          configMap:
            name: grafana
        - name: ldap
          configMap:
            name: grafana-ldap-config
        - name: datasource
          configMap:
            name: grafana-data-source
        - name: storage
          persistentVolumeClaim:
            claimName: grafana-data
```
3.`kubectl apply -f deployment.yaml`

### Environment (with versions)?

Grafana: Grafana v11.5.3 (4b398c1311)
OS: ubuntu
Browser: edge

### Grafana platform?

Kubernetes

### Datasource(s)?

tempo 2.7.1
