### ISSUE TITLE
Workload identity: `failed to retrieve Azure access token` on first call

### ISSUE THREAD

**Issue by rickardp** [grafana/grafana#103637]
### What happened?

Note: Original issue created here: https://github.com/grafana/azure-data-explorer-datasource/issues/1250, but looking at the code a lot of the Grafana auth stuff seem to be happening in the Grafana core. Please advice where to place this issue.

**What happened**:
* (Data source is provisioned)
* Go to Explore tab, choose the Azure Data Explorer data source
* Observe the following error
* 

![Image](https://github.com/user-attachments/assets/0478c6f2-c53e-4d50-99c4-0cf7bf82bfe9)
* Go to the Data sources tab
* Press "Save & Test" (without any changes)
* Observe a successful response
* Go back to Explore
* Observe the data source is working

If the data source is provisioned as read only, pressing the "Test" button will *not* work

### What did you expect to happen?

The data source working the first time

### Did this work before?

Did not try

### How do we reproduce it?

The following is the provisioning of the data source:
```yaml
...
- name: Data Explorer
          type: grafana-azure-data-explorer-datasource
          uid: adx
          isDefault: false
          jsonData:
            authType: workloadidentity
            clusterUrl: "$__env{ADX_CLUSTER}"
            defaultDatabase: my-database
          access: proxy
```

### Environment (with versions)?

- Grafana version: Grafana v11.5.2 (598e0338d5)
- Plugin version: 5.1.1
- OS Grafana is installed on: Official Docker image
- User OS & Browser: macOS, Safari

### Grafana platform?

Kubernetes

### Datasource(s)?

azure-data-explorer-datasource
