### ISSUE TITLE
Alerting: double $$ when exporting alert rule with tags which contains go template

### ISSUE THREAD

**Issue by andrejshapal** [grafana/grafana#103737]
### What happened?

Hello, 

https://play.grafana.org/alerting/nJ8whrTVk/modify-export?returnTo=%2Falerting%2Flist
When setting such label:

![Image](https://github.com/user-attachments/assets/ae6a9fb8-3bdb-4bf9-8709-5d990df28a88)

When trying to export this alert, the following manifest is produced:
   ```
       annotations:
            description: We are getting a high number of request errors and are seeing a low number of users.
            summary: High Errors and Low Users
          labels:
            alertname: '{{$$labels.something}}'
          isPaused: false
          missing_series_evals_to_resolve: -1
```
Double $$ looks wrong here. 

### What did you expect to happen?

   ```
       annotations:
            description: We are getting a high number of request errors and are seeing a low number of users.
            summary: High Errors and Low Users
          labels:
            alertname: '{{$labels.something}}'
          isPaused: false
          missing_series_evals_to_resolve: -1
```

### Did this work before?

This was working without issues when we were on 11.0.0

### How do we reproduce it?

1. Create alert
2. Set tag with some go template which uses $
3. Try to export

### Environment (with versions)?

Grafana: Grafana v11.6.0 (d2fdff9ee4)
OS: MacOs
Browser: Windows

### Grafana platform?

Kubernetes
