### ISSUE TITLE
Provisioning of nested folders for Dashboards

### ISSUE THREAD

**Issue by svenBrumble** [grafana/grafana#103950]
**Why is this needed**:

Currently, Grafana has the ability to create nested folders for dashboards through the UI. However, it is not possible to do so via provisioning, e.g.:
```yaml
  - name: Database Error Logs
    folder: Services/My Service/Databases
    type: file
    options:
      path:
        /var/lib/grafana/dashboards/services/my_service/databases/database_error_logs.json
```
Grafana will create **one** folder "Services/My Service/Databases" on the base level and put the dashboard there:
```
root
└─Services/My Service/Databases
  └─Database Error Logs
```

This is not only leaving out a crucial feature from provisioning, it's also **inconsistent** with provisioning alert groups. The docs for the alert rules say that "/" shouldn't be used in the folder name because it will be interpreted to created folders. E.g.:
```yaml
apiVersion: 1
groups:
    - orgId: 1
      name: Every minute
      folder: Services/My Service/Databases
      interval: 1m
      rules:
        - uid: du8ojvx3upkfg6
          title: My Service Database Alert
       ....
```
This will create the complete structure and put the alert group there:
```
root
└─Services
  └─My Service
      └─Databases
          └─My Service Database Alert
```

So the logic to create sub folders is clearly already there, it's just not implemented for Dashboards.

**What would you like to be added**:

If the folder for a Dashboard in provisioning contains "/", it should result in the provisioning creating nested folders, just like it does for alert rules. Also `foldersFromFilesStructure` should create the entire folder structure just like the option suggests and not just one level of folders.

**Who is this feature for?**

Every user who deploys Grafana with provisioning und uses nested folders.
