### ISSUE TITLE
Datasource: Google cloud monitoring datasource cannot authenticate using direct WIF

### ISSUE THREAD

**Issue by mos1380** [grafana/grafana#104151]
### What happened?

Trying to use direct workload identity federation for a Grafana instance running on GKE to access google cloud monitoring. However it seems like the datasource tries to use the GCE default service account instead of the Grafana service account and authentication fails. The datasource is configured as such:

```yaml
      apiVersion: 1
      datasources:
        - name: GCP Monitoring
          uid: gcp-monitoring
          type: stackdriver
          access: proxy
          jsonData:
            authenticationType: gce
```

When trying to query the datasource the following error is shown in the frontend:
```
unexpectederrorGet"https://cloudresourcemanager.googleapis.com/v1/projects":failedtoretrievegoogleaccesstoken:metadata:GCEmetadata"instance/service-accounts/default/token?scopes=https://www.googleapis.com/auth/cloudplatformprojects.readonly"notdefined
```

### What did you expect to happen?

For the Grafana to be able to authenticate on google cloud platform as the grafana Kubernetes service user using direct workload identity federation.

### Did this work before?

No. But grafana is able to use the kubernetes service user to access cloud monitoring by impersonating a service account.

### How do we reproduce it?

1. Setup WIF for GKE service accounts
3. Give the grafana workload identity the relevant IAM permissions (roles/monitoring.viewer)
4. Configure the google cloud monitoring datasource with auth type set to gce

### Environment (with versions)?

Grafana: 11.6.0@d2fdff9ee4d75c74bfd3a97c18a0b8e4d029f06e
OS: macOS Sequoia Version 15.4 (24E248)
Browser: Chrome Version 135.0.7049.95

### Grafana platform?

Kubernetes

### Datasource(s)?

google cloud monitoring
