### ISSUE TITLE
5.0.0.pre1: Dashboards not loaded from directory on start

### ISSUE THREAD

**Issue by johnny** [grafana/grafana#10504]
With current master (f3a66ec), dashboards are not loaded when Grafana starts. Touching the file creates the dashboard, but navigating to it results in a 404.

Manually uploading the same json file works.

Please include this information:
- What Grafana version are you using?
5.0.0-pre1 commit=f3a66ec
- What OS are you running grafana on?
Doesn't work on both MacOs native and Kubernetes using Docker
- What did you do?
```
cat provisioning/dashboards/default.yaml 
- name: 'default'
  org_id: 1
  folder: 'test'
  type: file
  options:
    folder: /home/user/dashboards
```

```
cat /home/user/dashboards/dashboard.json
{
  "title": "Foo",
  ...
}
```

- What was the expected result?
Once Grafana starts, there is a dashboard named Foo in the folder test.

- What happened instead?
The folder test was created, but was empty. Executing `touch /home/user/dashboards/dashboard.json` resulted in the dashboard being in the list. Clicking on the dashboard resulted in a 404 error.

The actual dashboard file used can be found here: https://github.com/gatling/gatling/tree/master/src/sphinx/realtime_monitoring/code/gatling.json
