### ISSUE TITLE
Image rendering in docker-compose not working - no option in gui

### ISSUE THREAD

**Issue by stefanpejcic** [grafana/grafana#105247]
### What happened?

Installed grafana docker and renderer, followed docs [#1](https://grafana.com/docs/grafana/latest/setup-grafana/image-rendering/) [#2](https://grafana.com/grafana/plugins/grafana-image-renderer/)

this is the docker-compose.yml file:
```
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    network_mode: host
    volumes:
      - grafana-volume:/var/lib/grafana
    environment:
      GF_RENDERING_SERVER_URL: http://IP_HERE:8081/render
      GF_RENDERING_CALLBACK_URL: http://IP_HERE:3000/
      GF_LOG_FILTERS: rendering:debug
      GF_UNIFIED_ALERTING: true
      GF_UNIFIED_ALERTING_SCREENSHOTS_CAPTURE: true
      GF_PLUGIN_GRAFANA_IMAGE_RENDERER_RENDERING_IGNORE_HTTPS_ERRORS: true
      # temp
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
    depends_on:
      - renderer

  renderer:
    container_name: renderer
    image: grafana/grafana-image-renderer:latest
    network_mode: host

volumes:
  grafana-volume:

```

and on gui i see that plugin is active:

![Image](https://github.com/user-attachments/assets/3e83fab7-4df5-4660-a406-b6c353d1069f)

but in the alerts i dont see the option to enable image as I had before:
![Image](https://github.com/user-attachments/assets/7a4656a8-9967-4f9b-bf2a-211ee63d079f)

when i test from terminal, image generation is working:
```
curl -o panel.png   -H "Authorization: Bearer XXXXXXXXXXXXXXXXXXXXXXXXXX"   "http://IP_HERE:3000/render/d-solo/oyh2QbDmz/alerting-overview?panelId=2545&orgId=1&width=1000&height=500"
```

and i also see the images in volume created:
```
root@XXXXXx:/var/lib/docker/volumes/grafana_grafana-volume/_data/png# ll
total 328
drwx------ 2 472 root   4096 May 12 10:15 ./
drwxrwxrwx 6 472 root   4096 May 12 10:15 ../
-rw-r--r-- 1 472 root 163124 May 12 10:15 H1jugACEDUXc1ocxwm9b.png
-rw-r--r-- 1 472 root 162517 May 12 10:15 w8Q5LOaBMvijG2TOh7yV.png
```

but I dont have the iamges on alerts send by grafana, nor i have the option in gui to enmable them like i had on previous grafana installed as service:

![Image](https://github.com/user-attachments/assets/d3909302-e2c3-4a0a-936c-44528850e74f)

### What did you expect to happen?

I expect an option in the gui to enable images and for images to be generated

### Did this work before?

idk, im first time running it in docker - works fine on older grafana as service

### How do we reproduce it?

1. run the docker-compose i provided
2. create a dashboard with panel
3. add alert and opsgenie or slack channel
4. create api token and test with provided command
5. then lower treshold to let grafana trigger its own alert
6. check received notification on slack

### Is the bug inside a dashboard panel?

not sure

### Environment (with versions)?

Grafana: v12.0.0 (4c0e7045f9)
OS: Ubuntu 24.04 and Docker
Browser: firefox

### Grafana platform?

Docker
