### ISSUE TITLE
Correlations: Ability to add `external` correlations via provisioning

### ISSUE THREAD

**Issue by ross-paypay** [grafana/grafana#106520]
## **Why is this needed**:

Currently, external correlations can only be added via the Grafana UI.

According to the [correlation docs](https://grafana.com/docs/grafana/latest/administration/correlations/create-a-new-correlation/#create-a-correlation-with-provisioning):
> config.type
> Correlation type. “query” is the only supported type at the moment

Attempting add `config.type: external` results in the following error.
```
Error: ✗ Datasource provisioning error: invalid correlation config type: "external"
```

## **What would you like to be added**:

The ability specify `config.type: external` with a `config.target.url` that functions the same as if the correlation was created in the UI. 

## **Who is this feature for?**

Grafana users that manage datasources via provisioning

**Comment by gelicia** [comment]
@ross-paypay We absolutely need to update the docs, but we built support for external correlations into provisioning from the beginning https://github.com/grafana/grafana/pull/92442/files#diff-697d4c9c412bb234e6f2f3bf08a1c09ffde1410afd8fc691c2d40b46b8205c5aR35 

Looking at the error youre getting, I think the issue is you're on an older version before the change. We changed that error message as well in when we added the new type https://github.com/grafana/grafana/pull/92442/files#diff-697d4c9c412bb234e6f2f3bf08a1c09ffde1410afd8fc691c2d40b46b8205c5aL17

Support for external correlations was added in 11.3 - can you upgrade and try again?

**Comment by gelicia** [comment]
Closing as I believe this is solved - feel free to comment if you update to 11.3 or later and still cannot get it working!

**Comment by vainikkaj** [comment]
@gelicia Should following YAML work?

```
          - uid: "trace-to-log-dashboard"
            sourceUID: "tempo01"
            orgId: 1
            targetUID: null
            label: "Open AKS log dashboard 📜 (ContainerLogv2)"
            description: ""
            provisioned: true
            config:
              type: "external"
              field: "traceID"
              target:
                url: '/foo/bar?var-LabelKey=app.kubernetes.io%2Fname&var-LabelValue=$$${serviceName}'
```

Grafana gives `correlation contains non default value in config.type` error and does not start ☹️
