### ISSUE TITLE
Tempo datasource provisioning with streaming enablement doesn't seem to work

### ISSUE THREAD

**Issue by zalegrala** [grafana/grafana#106725]
### What happened?

With Grafana 12.0.1, and a very recent Tempo version, it doesn't appear that the provisioning of the Tempo datasource is enabling the streaming configuration.

![Image](https://github.com/user-attachments/assets/e73d77a3-8c46-4eb4-b4f5-8d7027114c10)

![Image](https://github.com/user-attachments/assets/2adb77e7-11a8-4877-9328-9fcefd161a82)

### What did you expect to happen?

I'm expecting that with the `jsonData` provided to the provisioned data source, that the streaming would be enabled.

### Did this work before?

I've only recently attempted this, so unsure if this ever worked.

### How do we reproduce it?

1. Create a tempo datasource using provisioning
2. Set the `jsonData` to include the streaming config set to enabled.
3. Check the resulting data source after provisioning is complete.

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 12.0.1
OS: Kubernetes (k3s) on archlinux
Browser: Zen

### Grafana platform?

Kubernetes

### Datasource(s)?

Tempo

**Comment by andresmgot** [comment]
Hi @zalegrala,

I am not able to reproduce the issue. I've used the following provisioning file:

```
apiVersion: 1
datasources:
  - name: TempoOps
    type: tempo
    basicAuth: false
    url: "https://tempo.grafana.net"
    jsonData:
      streamingEnabled:
        metrics: true
        search: true
```

And the datasource is properly provisioned:

![Image](https://github.com/user-attachments/assets/796fdc4e-0f6a-47fc-a3e8-4616519c01b5)

So maybe it's an indentation issue on your side?

**Comment by zalegrala** [comment]
I think its unlikely its an indentation issue, since I'm rendering the yaml from jsonnet.  Is it possible a combination of the values I have is conflicting with the streaming settings?

**Comment by andresmgot** [comment]
It shouldn't be the case but if you want I can try with your exact same provisioning file but please send it as text, I cannot get it from the image.

**Comment by zalegrala** [comment]
```yaml
apiVersion: 1
datasources:
    - access: proxy
      editable: false
      isDefault: false
      jsonData:
        httpHeaderName1: X-Scope-OrgID
        lokiSearch:
            datasourceUid: Loki
        nodeGraph:
            enabled: true
        search:
            hide: true
        serviceMap:
            datasourceUid: Mimir
        streamingEnabled:
            metrics: true
            search: true
        timeout: 500
        tracesToLogs:
            datasourceUid: Loki
            tags:
                - job
                - instance
                - cluster
                - namespace
                - pod
        tracesToMetrics:
            datasourceUid: Mimir
      name: TempoOps
      secureJsonData:
        httpHeaderValue1: ops
      type: tempo
      url: http://query-frontend.trace.svc.cluster.znet:3200
      version: 1
```
