### ISSUE TITLE
Datasource: AWS assume role not working from outside of AWS

### ISSUE THREAD

**Issue by odam06** [grafana/grafana#106937]
### What happened?

We are hosting Grafana on a GKE cluster, and we want to allow it to assume an AWS IAM Role using Web Identity Federation (OIDC) in order to securely access AWS services (e.g., CloudWatch).

Implementation Steps
1. Token Projection via Service Account
We configured the Grafana Helm chart to inject an OIDC token using Kubernetes' token projection mechanism:

``` yaml
extraVolumeMounts:
  - name: aws-token
    mountPath: /var/run/secrets/tokens
    readOnly: true

extraVolumes:
  - name: aws-token
    projected:
      sources:
        - serviceAccountToken:
            path: aws-token
            audience: sts.amazonaws.com
            expirationSeconds: 3600
```
We also set the corresponding environment variable in the Grafana container:

``` yaml
env:
  - name: AWS_WEB_IDENTITY_TOKEN_FILE
    value: "/var/run/secrets/tokens/aws-token"
```

Note: This uses a custom Helm chart because the official one didn’t allow us to configure projected extraVolumes easily (only extraVolumes have been modified for the test).

2. AWS OIDC Identity Provider Setup
We created a new OIDC provider in AWS, referencing the GKE cluster:

``` json
{
  "Url": "https://container.googleapis.com/v1/projects/<project_id>/locations/<location>/clusters/<cluster_name>",
  "ClientIDList": ["sts.amazonaws.com"],
  "ThumbprintList": ["08745487e891c19e3078c1f2a07e452950ef36f6"]
}
```

3. IAM Role and Trust Policy
An IAM Role was created with a trust policy that allows sts:AssumeRoleWithWebIdentity:

``` json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::<account_id>:oidc-provider/container.googleapis.com/v1/projects/<project_id>/locations/<location>/clusters/<cluster_name>"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "container.googleapis.com/v1/projects/<project_id>/locations/<location>/clusters/<cluster_name>:sub": "system:serviceaccount:<namespace>:grafana"
        }
      }
    }
  ]
}
```

Issue Encountered
Despite the setup, Grafana fails to authenticate when trying to access the AWS data source (e.g., CloudWatch). The SDK throws an error during credential resolution via Web Identity.
![Image](https://github.com/user-attachments/assets/d9e9cadf-9c70-490a-8e3c-e9a5afb05a48)

We confirmed that:

The token is correctly projected and accessible at the specified path.

The token works when tested in another pod using the same service account and token projection mechanism. Tested with a command like this:
``` bash
aws sts assume-role-with-web-identity \
  --role-arn "$AWS_ROLE_ARN" \
  --role-session-name test-session \
  --web-identity-token file://$AWS_WEB_IDENTITY_TOKEN_FILE
```

Can you take a look at this issue ?

### What did you expect to happen?

I expect the datasource to connect correctly to AWS cloudwatch from GKE via assume role

### Did this work before?

Never tried before

### How do we reproduce it?

1. Create an OIDC provider on aws side with gke url
2. Create a grafana role with trust relationship from gke cluster
3. Mount on grafana a volume with a sts.amazonaws.com audience in a projected service account token 
4. Give the path of the service account token to grafana with the `AWS_WEB_IDENTITY_TOKEN_FILE` env var
5. Create a new datasource with aws sdk auth and the role created previously in aws assume role.

### Environment (with versions)?

Grafana: 11.6.1
OS: MacOS Sequoia 15.5
Browser: Brave 1.79.123

### Grafana platform?

Kubernetes

### Datasource(s)?

CloudWatch data source - native plugin
