### ISSUE TITLE
[kubernetes] relative static files includes are broken on reload

### ISSUE THREAD

**Issue by Deshke** [grafana/grafana#10791]
Please include this information:
- What Grafana version are you using?
 docker  grafana/grafana:4.6.3

- What did you do?
  pressed F5 or strg+r

- What was the expected result?
  working webpage

- What happened instead?
  relative css/static files includes are not working

```
t=2018-02-06T10:14:20+0000 lvl=info msg="Starting Grafana" logger=server version=4.6.3 commit=7a06a47 compiled=2017-12-14T08:36:59+0000
t=2018-02-06T10:14:20+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2018-02-06T10:14:20+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2018-02-06T10:14:20+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2018-02-06T10:14:20+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2018-02-06T10:14:20+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2018-02-06T10:14:20+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.log.mode=console"
t=2018-02-06T10:14:20+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_SERVER_ROOT_URL=/grafana/"
t=2018-02-06T10:14:20+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_AUTH_ANONYMOUS_ENABLED=true"
t=2018-02-06T10:14:20+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_AUTH_ANONYMOUS_ORG_ROLE=Admin"
t=2018-02-06T10:14:20+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_AUTH_BASIC_ENABLED=false"
t=2018-02-06T10:14:20+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2018-02-06T10:14:20+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2018-02-06T10:14:20+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2018-02-06T10:14:20+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2018-02-06T10:14:20+0000 lvl=info msg="App mode production" logger=settings
t=2018-02-06T10:14:20+0000 lvl=info msg="Initializing DB" logger=sqlstore dbtype=sqlite3
t=2018-02-06T10:14:20+0000 lvl=info msg="Starting DB migration" logger=migrator
t=2018-02-06T10:14:20+0000 lvl=info msg="Executing migration" logger=migrator id="copy data account to org"
t=2018-02-06T10:14:20+0000 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account to org"
t=2018-02-06T10:14:20+0000 lvl=info msg="Executing migration" logger=migrator id="copy data account_user to org_user"
t=2018-02-06T10:14:20+0000 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account_user to org_user"
t=2018-02-06T10:14:20+0000 lvl=info msg="Starting plugin search" logger=plugins
t=2018-02-06T10:14:20+0000 lvl=info msg="Initializing CleanUpService" logger=cleanup
t=2018-02-06T10:14:20+0000 lvl=info msg="Initializing Alerting" logger=alerting.engine
t=2018-02-06T10:14:20+0000 lvl=info msg="Initializing Stream Manager"
t=2018-02-06T10:14:20+0000 lvl=info msg="Initializing HTTP Server" logger=http.server address=0.0.0.0:3000 protocol=http subUrl=/grafana socket=
```

kubernetes ingress 

```yaml
metadata:
  annotations:
    ingress.kubernetes.io/add-base-url: "true"
    ingress.kubernetes.io/configuration-snippet: |
      add_header Cache-Control  "public, must-revalidate, proxy-revalidate";
    ingress.kubernetes.io/rewrite-target: /
......
spec:
  rules:
  - host: sub.domain.tld
    http:
      paths:
      - backend:
          serviceName: monitoring-grafana
          servicePort: 3000
        path: /grafana
```

kubernetes deployment 

```yaml
      containers:
      - env:
        - name: INFLUXDB_HOST
          value: monitoring-influxdb
        - name: GF_AUTH_BASIC_ENABLED
          value: "false"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: Admin
        - name: GF_SERVER_ROOT_URL
          value: /grafana   # does not change with a https://domain.tld/grafana/
        image: grafana/grafana:4.6.3
        imagePullPolicy: IfNotPresent
        name: grafana
        ports:
        - containerPort: 3000
          protocol: TCP
```

![bildschirmfoto vom 2018-02-06 11-30-13](https://user-images.githubusercontent.com/1473225/35854634-25c9c7d2-0b31-11e8-98c9-a52dfa612777.png)

`/public` is attached after the dashboard url  e.g `https://foo.bar/grafana/dashboard/db/public/build/manifest.979c370f20ff0db1a23c.js` but the file is located at `grafana/public/build`  

any idea how to work around this?

**Comment by Deshke** [comment]
nvm found the issue, nginx.ingress in k8s  

```yaml
metadata:
  annotations:
    ingress.kubernetes.io/add-base-url: "false"
```

the `add-base-url` needs to be explicit set to `false`
