### ISSUE TITLE
Provisionning dashboards with folders do not allow for the same filename

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#10874]
With the following structure:

- /usr/share/grafana/dashboards/customer1/linux.json
- /usr/share/grafana/dashboards/customer1/jvm-app1.json
- /usr/share/grafana/dashboards/customer2/linux.json
- /usr/share/grafana/dashboards/customer2/jvm-app2.json

I configure the provisioning to create the folders customer1 and customer2.

The dashboard linux.json is only populated in one of the two folders even if they have different UID.
Renaming to linux1.json fixes it.

tested with latest nightly.

**Comment by torkelo** [comment]
you mean customer2/linux.json ?

**Comment by roidelapluie** [comment]
update description, sorry, created the ticket by accident :)

**Comment by torkelo** [comment]
@bergquist any ideas what is going on here ?

**Comment by bergquist** [comment]
not sure. We use the full pathname as identifier. Are you using symlinks?

**Comment by roidelapluie** [comment]
No and I could reproduce that with grafana-5.0.0-11575pre1 and 5.0.0-11709beta1

**Comment by bergquist** [comment]
Can't reproduce this. I've created two folders bot containing the same file and use a config like this

```yaml
 - name: 'team-a'
   org_id: 1
   folder: 'Team A'
   type: file
   options:
     path: /var/lib/grafana/dashboards/team1
 - name: 'team-b'
   org_id: 2
   folder: 'Team B'
   type: file
   options:
     path: /var/lib/grafana/dashboards/team2
```

But I found another bug that might have affected you. If you provisioing dashboards once and then change the org_id Grafana will get confused. The solution for that problem is to delete all the rows for the second provider in the `dashboard_provisoning` table. I'm creating a new issue for that bug.

Do you see any errors logs about the behavior?
