### ISSUE TITLE
anonymous will show login page

### ISSUE THREAD

**Issue by ntting** [grafana/grafana#11174]
Grafana version: 5.0.0_Beta1

When set conf/defaults.ini anonymous enabled is true, bug sometime the login page will show when we open a dashboard url, Especially in the open for the first time。 We play dashboards in warroom，this caused a lot of inconvenience

```ini
[auth.anonymous]
# enable anonymous access
enabled = true
```

 Looking forward to receive your reply

**Comment by bergquist** [comment]
@ntting on what OS are you running Grafana?

**Comment by ntting** [comment]
@bergquist  we run it in Cloudfoundry， in 4.6.0 is right。 when the login page appears, and then refresh several times can be normal again。

**Comment by bergquist** [comment]
Weird. I've been able to refresh a dashboard with anonymous login for 15min without going to the login page once. Do you any things in the logs that might help us?

**Comment by Deshke** [comment]
same here with a kubernetes deployment 


```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitoring-grafana
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:5.0.0
        ports:
        - containerPort: 3000
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: ca-certificates
          readOnly: true
        - mountPath: /var/lib/grafana
          name: grafana-storage
        - mountPath: /usr/share/ca-certificates
          name: os-certs
        env:
        - name: INFLUXDB_HOST
          value: monitoring-influxdb
        - name: GF_SERVER_HTTP_PORT
          value: "3000"
          # The following env variables are required to make Grafana accessible via
          # the kubernetes api-server proxy. On production clusters, we recommend
          # removing these env variables, setup auth for grafana, and expose the grafana
          # service using a LoadBalancer or a public IP.
        - name: GF_AUTH_BASIC_ENABLED
          value: "false"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: Admin
        - name: GF_SERVER_ROOT_URL
          # If you're only using the API Server proxy, set this value instead:
          # value: /api/v1/namespaces/kube-system/services/monitoring-grafana/proxy/
          value: /grafana/
      volumes:
      - name: ca-certificates
        hostPath:
          path: /etc/ssl/certs
      - name: os-certs
        hostPath:
          path: /usr/share/ca-certificates
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: grafana-pvc
```

returns me straight to the login page (this worked in 4.6.3)
