### ISSUE TITLE
Support "Name" field for auth.proxy

### ISSUE THREAD

**Issue by gdhgdhgdh** [grafana/grafana#11237]
I have auth.proxy reverse proxying working well - thank you for this feature. 

A useful cosmetic improvement would be to support an additional HTTP header so the upstream webserver could send the user's full "Firstname Lastname" in addition to their login name or email address.

**Comment by glennschmidt** [comment]
This sounds like what the `auth.proxy.headers` setting is meant to do

At least, that's my interpretation of the docs:

> **headers**
> Used to define additional headers for Name, Email and/or Login, for example if the user’s name is sent in the X-WEBAUTH-NAME header and their email address in the X-WEBAUTH-EMAIL header, set headers = Name:X-WEBAUTH-NAME Email:X-WEBAUTH-EMAIL.
http://docs.grafana.org/installation/configuration/#headers

However, I haven't been able to get this feature to work.

**Comment by Yanson** [comment]
The code for this appears to be here:
https://github.com/grafana/grafana/blob/b418e14bd975bca7d8afd8a236a909c8405a29f6/pkg/middleware/auth_proxy.go#L114

However, it does not appear to work for me.

```toml
[auth.proxy]
auto_sign_up = true
enabled = true
header_name = x-auth-request-user
header_property = username
headers = Email:x-auth-request-email
```

Using with https://github.com/bitly/oauth2_proxy
