### ISSUE TITLE
5.0.2 Unable to use users without email

### ISSUE THREAD

**Issue by thomasvargiu** [grafana/grafana#11272]
Creating users without emails will automatically fill email field with the username.
Trying to login an user registered with no email fails due to wrong credentials.

Expected:
Login with username shoud work even without an email.

I'm using grafana with docker:

```yml
  grafana:
    image: grafana/grafana:5.0.2
    restart: on-failure
    ports:
      - "3000:3000"
    networks:
      - front
      - back
    environment:
      GF_SERVER_ROOT_URL: http://grafana.myhost.it
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana:/var/lib/grafana
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
        order: stop-first
      restart_policy:
        condition: on-failure
```
