### ISSUE TITLE
404 with /dashboard as sub path behind nginx

### ISSUE THREAD

**Issue by brukau** [grafana/grafana#11335]
Creation of new dashboard/folder/import fails with 404 in case of running grafana behind nginx with */dashboard* sub_path. But it works if for example */grafana* is used as sub_path.

If */d* is used as sub path then when you click on '+' icon you are redirected to `http://localhost/d/ashboard/new?orgId=1` which also returns 404.
 

Version:  Grafana v5.0.3 (commit: 91162f3) 

docker-compose:
```
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
```
nginx.conf:    
```
...
server {
  listen 80;
  location /dashboard/ {
    proxy_pass http://grafana:3000/;
  }
}
...
```
grafana.ini:
`root_url = http://localhost/dashboard `
