### ISSUE TITLE
Postgres datasource provisioning problems

### ISSUE THREAD

**Issue by asthomasdk** [grafana/grafana#11407]
### What Grafana version are you using?
5.0.3
### What datasource are you using?
Postgres

### What OS are you running grafana on?
Docker container 

### What did you do?
Created a datasources.yml file with the following content: 

``` 
# list of datasources that should be deleted from the database
delete_datasources:

# list of datasources to insert/update depending
# whats available in the datbase
datasources:
- name: pg-dashboard
  type: postgres
  access: proxy
  url: postgres:5432
  password: "password"
  user: "grafanareader"
  database: "dashboard"
  basicAuth: false
  is_default: true
  editable: true
  json_data:
    ssl_mode: "disable"
```

The problem is the sslMode setting - which is not working. 

I have also tried this with : 
```
  json_data:
    ssl_mode: "disable"
``` 

and 

``` 
  jsonData:
    sslMode: "disable"
```  

None of which seem to work. 

What is the correct syntax? 

### What was the expected result?
Fully provisoned postgres datasource

### What happened instead?
ssl mode is set to `require`- which means I have to manually change the setting on a new system before things work.

**Comment by svenklemm** [comment]
i think the correct syntax should be ```sslmode```

**Comment by asthomasdk** [comment]
I think I have tried all possible combinations here and just cannot get it to work. May have to resort to posting json data for now.

**Comment by asthomasdk** [comment]
Hmm - I am seeing this error in the log file for the docker container: 

```
[Deprecated] the datasource provisioning config is outdated. please upgrade" logger=provisioning.datasources filename=/etc/grafana/provisioning/datasources/datasource.yml
```

So there must be something wrong with the provisioning file.

**Comment by marefr** [comment]
@asthomasdk questions should be asked on the [community site](https://community.grafana.com/). Github issues are for feature request and bug reports.

For now, please make sure use a provisioning configuration as described in latest [documentation](http://docs.grafana.org/administration/provisioning/#datasources).

**Comment by asthomasdk** [comment]
That is what I was trying to do. And since I had problems getting it to work - I thought it would make sense to log something here. 

FYI it looks like the following config works with almost everything : 

```
# # config file version
apiVersion: 1

# # list of datasources that should be deleted from the database
deleteDatasources:

# # list of datasources to insert/update depending
datasources:
- name: pg-dashboard
  type: postgres
  access: proxy
  url: postgres:5432
  password: password
  user: grafanareader
  database: dashboard
  basicAuth: false
  isDefault: true
  jsonData:
     sslmode: disable
  version: 1
  editable: true
``` 

I think it may have been the missing first line with the `apiVersion: 1`that has made a difference. 

The only thing that is not being set now is the password.

**Comment by marefr** [comment]
You need to provide the password using `secureJsonData` property:

```yaml
...
secureJsonData:
 password: "..."
```

Just by looking at the json data posted (chrome dev tools for example) when creating a new postgres datasource I see the following:

```json
{
  "name": "Test pg",
  "type": "postgres",
  "url": "localhost:5432",
  "access": "proxy",
  "jsonData": { "keepCookies": [], "sslmode": "disable" },
  "secureJsonFields": {},
  "database": "test",
  "user": "test",
  "secureJsonData": { "password": "test" }
}
```

Of course the provision configuration is yaml, but supports the same camelCase json properties.

Closing this since it's no bug.
