### ISSUE TITLE
Modifying provisioned dashboards that are marked as editable are imported as uneditable

### ISSUE THREAD

**Issue by furhouse** [grafana/grafana#11465]
### What Grafana version are you using?
5.0.4
### What datasource are you using?
CloudWatch
### What OS are you running grafana on?
Ubuntu 16.04
### What did you do?
Imported a dashboard using provisioning.
```yaml
apiVersion: 1

providers:
- name: 'dashboards'
  orgId: 1
  folder: ''
  type: file
  editable: true
  options:
    path: /usr/share/grafana/dashboards/restore
```
### What was the expected result?
The provisioned dashboard should be editable.
### What happened instead?
The provisioned dashboard is uneditable, and I have to press the green 'Make Editable' button to be able to change its properties.
