### ISSUE TITLE
viewers_can_edit doesn't work with provisioned dashboards

### ISSUE THREAD

**Issue by bechtoldt** [grafana/grafana#11470]
### What Grafana version are you using?
latest
### What datasource are you using?
Prometheus
### What did you do?
* Logged with external authenticated user (using generic oauth) with role "Viewer"
* tried to edit an existing dashboard, that is saved in an existing Grafana folder

Dashboard provision config:
```
      - name: 'monitoring'
        orgId: 1
        folder: 'Infrastructure'
        type: file
        disableDeletion: False
        editable: False
        options:
          path: /etc/grafana-dashboards/xyz/monitoring/
```

### What was the expected result?
It should be possible to manipulate the dashboard (and only the dasboard) and export the updated JSON object, even though editable is set to false in the dashboard provisioning config. users.viewers_can_edit is set to true in the Grafana settings.

### What happened instead?
Edit buttons are missing and it's not possible to open Dashboard settings (besides the "View JSON" tab).
