### ISSUE TITLE
root_url path is ignored in GitHub OAuth callback

### ISSUE THREAD

**Issue by manics** [grafana/grafana#11817]
### What Grafana version are you using?
5.1.0

### What datasource are you using?
Prometheus

### What OS are you running grafana on?
`grafana/grafana` Docker image using [official Helm chart stable/grafana 1.2.2](https://github.com/kubernetes/charts/tree/89d59a91d75cda0f9df655d9088cc12c1a9dc650/stable/grafana)

### What did you do?
Configured Grafana to run under a subpath `/grafana`.
Created a GitHub OAuth app with callback https://INTERNAL_DOMAIN.openmicroscopy.org/grafana/login/github

### What was the expected result?
GitHub OAuth login to Grafana should work

### What happened instead?
GitHub Oauth failed as the redirect_uri sent by Grafana was missing the root-url path (`/login/github` instead of `/grafana/login/github`):

```
t=2018-05-03T17:59:32+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/login/github status=302 remote_addr=192.168.8.15 time_ms=0 size=323 referer="https://INTERNAL_DOMAIN.openmicroscopy.org/grafana/login?redirect=%2F"
t=2018-05-03T17:59:32+0000 lvl=eror msg="failed to login " logger=oauth error=redirect_uri_mismatch errorDesc="The redirect_uri MUST match the registered callback URL for this application."
t=2018-05-03T17:59:32+0000 lvl=eror msg="Login provider denied login request" logger=context userId=0 orgId=1 uname= error=redirect_uri_mismatch errorDesc="The redirect_uri MUST match the registered callback URL for this application."
t=2018-05-03T17:59:32+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/login/github status=302 remote_addr=192.168.8.15 time_ms=0 size=37 referer="https://INTERNAL_DOMAIN.openmicroscopy.org/grafana/login?redirect=%2F"
```

Relevant Helm chart configuration:
```
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  path: /grafana
  hosts:
  - INTERNAL_DOMAIN.openmicroscopy.org
  tls:
  - hosts:
    - INTERNAL_DOMAIN.openmicroscopy.org

persistence:
  enabled: false

image:
  tag: 5.1.0

env:
  GF_AUTH_ANONYMOUS_ENABLED: "true"
  GF_AUTH_GITHUB_ENABLED: "true"
  GF_AUTH_GITHUB_ALLOW_SIGN_UP: "true"
  GF_AUTH_GITHUB_CLIENT_ID: SECRET
  GF_AUTH_GITHUB_CLIENT_SECRET: SECRET
  GF_AUTH_GITHUB_SCOPES: user:email,read:org
  GF_AUTH_GITHUB_AUTH_URL: https://github.com/login/oauth/authorize
  GF_AUTH_GITHUB_TOKEN_URL: https://github.com/login/oauth/access_token
  GF_AUTH_GITHUB_API_URL: https://api.github.com/user
  GF_AUTH_GITHUB_ALLOWED_ORGANISATIONS: openmicroscopy
  GF_SERVER_DOMAIN: INTERNAL_DOMAIN.openmicroscopy.org
  GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s:/grafana/"
  GF_LOG_LEVEL: debug
```
All other aspects of Grafana seem to work.
