### ISSUE TITLE
Keeps provisioning datasources

### ISSUE THREAD

**Issue by timothy6007** [grafana/grafana#11853]
Please include this information:
### What Grafana version are you using?
Version 5.1.0 (commit: 844bdc53a)
### What datasource are you using?
Prometheus,Graphite
### What OS are you running grafana on?
Debian
### What did you do?
I tried to provision Grafana with Datasources and Dashboards.
### What was the expected result?
Grafana to use these files to create dashboards and datasources and keep using them.
### What happened instead?
After a restart, the dashboards stay but the datasources get recreated. This causes the datasources to get a new id, which causes a mismatch between the alert datasourceID and the ID of the datasource itself.
### Related part of the log:
t=2018-05-07T12:43:05+0200 lvl=eror msg="Unable to load datasource meta data" logger=context userId=1 orgId=1 uname=admin error="Data source not found"
t=2018-05-07T12:43:05+0200 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/35/api/v1/query_range status=500 remote_addr=81.82.211.78 time_ms=1 size=49 referer="url_to_website"
(i removed the url because of safety measures)

### current workaround
if i move the dashboards provisioning folder after restart and move it back, it will readd the dashboards, which fixes the mismatch.

edit:
this is one of the datasource files that i'm using

```
apiVersion: 1
deleteDatasources:
   - name: Prometheus
     orgId: 1
datasources:
 - name: Prometheus
   type: prometheus
   access: proxy
   url: http://localhost:9090
   version: 1
   editable: true
```
