### ISSUE TITLE
Simplify dashboard provisioning & folders

### ISSUE THREAD

**Issue by xlson** [grafana/grafana#12016]
## How it works right now

To provision a dashboard you need this:
1. One or more provider configs in `<Grafana Home>/provisioning/dashboards` (default path)
2. Dashboard json files in a folder that is pointed out by the provider config

```
# <Grafana Home>/provisioning/dashboards/provider.yaml
apiVersion: 1

providers:
- name: 'default'
  orgId: 1
  folder: ''
  type: file
  disableDeletion: false
  options:
    path: /var/lib/grafana/dashboards
```
```
# /var/lib/grafana/dashboards/mydashboard.json
{ ... }
```

## What ends up happening

> As a beginner I expect to find a folder to drop a `dashboard.json` file in and then have the dashboard show up in Grafana. I'm probably going to try with `<Grafana Home>/provisioning/dashboards` as that seems to make sense and be confused when it doesnt work. I'll check logs but see no error message.

I've seen questions regarding dashboard provisioning pop up now and then, usually regarding how to get your first provisioned dashboard up and running in a clean Grafana install. The provider concept is something we need to support an advanced user but it gets in the way when learning about dashboard provisioning for the first time. 

## A possible solution

- provision dashboard json files (with a default provider config) in `<Grafana Home>/provisioning/dashboards` when no provider exist
- log an error message if both provider config and dashboard json files are found in the default folder (use the provider, don't provisiong the json files)

ping @bergquist

**Comment by bergquist** [comment]
I think this would be a good UX improvement for new/small users who don't work with multiple teams and folders. I'm a little bit worried it might come off as "messy" for our current user base but those who currently use our provisioning system for dashboards are most likely advanced users who have no problems catching up with this change.

**Comment by xlson** [comment]
What is it you think would come off as messy? Existing users of the dashboard provisioning feature should not be affected at all and not necessarily even have to learn about this feature.

**Comment by torkelo** [comment]
> One or more provider configs in <Grafana Home>/provisioning/dashboards (default path)

I thought provisioning providers was located in the config dig /etc/grafana/provisioning  no in grafana home dir (where content files are).

**Comment by xlson** [comment]
@torkelo You're right, for both packages and docker its in `/etc/grafana/provisioning`. Otherwise its below the home folder if you installed the tar-ball or are running in dev. 

Perhaps I shouldn't have mentioned the folder. The main idea here is that perhaps we don't need to require a provisioning config for the basic use-case. It would be really nice if the user could just drop some dashboards in a folder without setting up a provider themselves. But, I don't know if this is something we should solve or not, I haven't seen that many questions about provisioning recently (which could just be missing them, or it just isn't the issue I thought it was).

**Comment by bergquist** [comment]
I think this should be address with docs and comments in configuration. 
This is not a feature you stumble upon anyway.

**Comment by DanCech** [comment]
Not sure if this is the right place for this, but I'm facing a related problem trying to provision dashboards.  Right now I'm creating the entire dashboard folder tree hierarchy manually, but I would like to be able to use a configmap in kubernetes to define all the dashboards to be provisioned.  If each entry in dashboards.yml was able to define a list of files instead of a path that would make it possible to have all the dashboard files in the same directory (and thus a single configmap) even if they were being provisioned into multiple different folders or orgs in grafana.

**Comment by bergquist** [comment]
Sounds like something we might want to support.

I think it would be nice to allow overriding dashboard folder per `path` basis. Would also make sense to allow specifying files instead of directories as path. Something like 
```yaml
 providers:
  - name: 'gdev prov dev1'
    folder: 'prov dev1'
    type: file
    updateIntervalSeconds: 3
    options:
      paths: 
      - file: devenv/dev-dashboards-without-uid/dash1.json
        folder: 'prov dev2'
      - file: devenv/dev-dashboards-without-uid/dash2.json
      - file: devenv/dev-dashboards-without-uid/dash3.json
        folder: 'prov dev3'
```

Another idea would be to allow glob expressions. 
```yaml
 providers:
  - name: 'gdev prov dev1'
    folder: 'prov dev1'
    type: file
    updateIntervalSeconds: 3
    options:
      paths: 
      - file: devenv/dev-dashboards-without-uid/*.json
        folder: 'common'
      - file: devenv/dev-dashboards-without-uid/dash{2|3}.json
        folder: 'prov dev3'
```

this deserves is own issue since I'm not sure either solution makes dashboard provisioning easier :)

**Comment by xlson** [comment]
Still relevant I'd say.

**Comment by arnedc** [comment]
I would also like to see the same directory structure on the Grafana UI as in the folder that is configured in the dashboard yaml (see #21909):

**What would you like to be added**: When I provision dashboards for a path where the dashboards are organized under a directory structure, I would love to see that same structure in the Grafana UI.
Example:
dashboards.yml (under `/etc/grafana/provisioning/dashboards`)
```yaml
apiVersion: 1
providers:
 - name: 'dashboards'
   orgId: 1
   folder: ''
   type: file
   disableDeletion: false
   editable: true
   allowUiUpdates: false
   options:
     path: "/var/lib/grafana/dashboards/"
```
With the following structure under `/var/lib/grafana/dashboards`
```
$ tree /var/lib/grafana/dashboards
/var/lib/grafana/dashboards
└── Components
    ├── component1.json
    ├── component2.json
└── System
    ├── alerts.json
    ├── system.json
```
, we should be able to see in the Grafana UI, two folders (System & Components), under which the appropriate dashboards are listed 

**Why is this needed**: It makes provisioning a lot easier for set-ups with a lot of dashboards that need some structure. Now we have to create a separate provision yaml for each directory.
