### ISSUE TITLE
[provisionning] deleteDatasources nned to have at least one datasource to works

### ISSUE THREAD

**Issue by rockandska** [grafana/grafana#12512]
### What Grafana version are you using?
```
# grafana-server -v
Version 5.2.0 (commit: ad4d717)
```
### What datasource are you using?
- influxdb
### What OS are you running grafana on?
```
# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
### What did you do?
Configure datasources to be deleted inside /etc/grafana/provisioning/datasources/ansible.yaml

```
apiVersion: 1
deleteDatasources:
- name: test4
```
Restart grafana

### What was the expected result?

Having the "test4" datasource deleted

### What happened instead?

Nothing. The test4 datasource is still present
It seems than it is required to have some datasources configured in the same file to be functional , because even if i have a file with datasources to be created , and one file for datasources to be deleted, i hit the same behaviour.

Regards,

**Comment by marefr** [comment]
Think you forgot the orgId. Following works for me so closing this.

```yaml
apiVersion: 1

deleteDatasources:
  - name: Test4
    orgId: 1
```

**Comment by rockandska** [comment]
Why the orgId is required only if there is no datasources ?
Why the orgId is required when it is not the case with the API because the datasource name is unique for all orgId?

Since the orgId is not required with the API and it works normally when there is datasources present in the file, it looks like a bug for me. please reopen.

test4 datasource will be deleted:
```
apiVersion: 1
deleteDatasources:
- name: test4

datasources:
- access: proxy
  name: test5
  orgId: 1
  type: influxdb
  url: http://host:port
```
test4 datasource will be **not** deleted:
```
apiVersion: 1
deleteDatasources:
- name: test4
```
