### ISSUE TITLE
Dashboard Provisioning does not track symlink changes

### ISSUE THREAD

**Issue by kanga333** [grafana/grafana#12534]
Thank you for developing a wonderful product.

### What Grafana version are you using?

- 5.2.1

### What datasource are you using?

- prometheus

### What OS are you running grafana on?

- Using the official docker image on Fedora 27

### What did you do?

- Set dashboards.yml as follows

```yml
apiVersion: 1

providers:
- name: 'midleware'
  orgId: 1
  folder: 'midleware'
  type: file
  disableDeletion: false
  editable: true
  options:
    path: /git/grafana.git/provisioning/dashboards/midleware
```

- Set /git/grafana.git as a symlink of /git/rev-a
- Loading from /git/grafana.git/provisioning/dashboards/midleware will succeed
- Change /git/grafana.git to symlink of /git/rev-b and delete /git/ rev-a

### What was the expected result?

- Reload the configuration from /git/grafana.git/provisioning/dashboards/midleware
- At that time the actual path refers to /git/reb-b/provisioning/dashboards/midleware

### What happened instead?

- I got a message like the following

```
t=2018-07-09T06:11:50+0000 lvl=eror msg="failed to search for dashboards" logger=provisioning.dashboard type=file name=midleware error="stat /git/rev-a/provisioning/dashboards/midleware: no such file or directory"
```

I think that it is necessary to change the evaluation of symlink running in NewDashboardFileReader to startWalkingDisk. What do you think?
https://github.com/grafana/grafana/blob/7214ee90242e00dbb900a349373dd67a10659317/pkg/services/provisioning/dashboards/file_reader.go#L56

**Comment by torkelo** [comment]
I think if you change symlinks while grafana is running is not requiring a restart ok?

**Comment by xlson** [comment]
I think we might want to support this at some point. Using symbolic links for deployment is a fairly common use case so this could definitely bite more users.

**Comment by torkelo** [comment]
as I understand we already do support it? this was a case where the root provisioned folder symlink was hanged after starting Grafana. But I agree if it is a common action to change symlinks like this after starting Grafana then we should do something, but not sure if this is going to be a common problem.

**Comment by kanga333** [comment]
I will explain more specifically what I want to do.I want to do GitOps with [git-sync](https://github.com/kubernetes/git-sync). I manage under the provisioning directory as a git repository. git-sync will fetch changes as new revisions after making changes to the git repository. At that time the above symbolic link change will occur. 

Since I want to track changes, I want to manage dashbord settings with git. However, I do not want to deploy settings or replace containers every time I change the dashboard. I am glad that grafana will automatically reload the settings when rewriting the symbolic link with git-sync.

**Comment by kanga333** [comment]
I prepared the reproduction case by simplifying it. I use the following docker-compose.

```
version: "2"

services:
  grafana:
    image: grafana/grafana:5.2.1
    ports:
      - 3000:3000
    environment:
      - GF_PATHS_DATA=/var/lib/grafana/data
      - GF_PATHS_PROVISIONING=/git/grafana-provision-example.git/provisioning
    volumes:
      - grafana:/var/lib/grafana
      - git:/git:ro
  git-sync:
    image: kanga333/git-sync:latest
    environment:
      - GIT_SYNC_REPO=https://github.com/kanga333/grafana-provision-example.git
      - GIT_SYNC_BRANCH=master
      - GIT_SYNC_WAIT=10
      - GIT_SYNC_ROOT=/git
    volumes:
      - git:/git
volumes:
  grafana:
  git:
```

I manage the settings of the provision directory with [kanga333/grafana-provision-example](https://github.com/kanga333/grafana-provision-example.git) and synchronize with git-sync for use with grafana.

First start git-sync. (Since docker-compose does not have a function like the k8s init container, it is started manually first.)

```
docker-compose up git-sync
```

Next, start grafana.

```
docker-compose up grafana
```

The /git directory looks like this. (inside the grafana container)

```
grafana@22e08a43bd8d:/$ ls -l /git/
total 4
lrwxrwxrwx 1 root root   44 Jul 12 14:09 grafana-provision-example.git -> rev-f0f7a164ba1fdc2b792a443a04d63072408f81f8
drwxr-xr-x 3 root root 4096 Jul 12 14:09 rev-f0f7a164ba1fdc2b792a443a04d63072408f81f8
```

The /git/grafana-provision-example.git directory looks like this. It is the root directory of git.

```
grafana@22e08a43bd8d:/$ ls -l /git/grafana-provision-example.git/
total 8
-rw-r--r-- 1 root root   27 Jul 12 14:09 README.md
drwxr-xr-x 3 root root 4096 Jul 12 14:09 provisioning
```

Grafana reads the settings of kanga333/grafana-provision-example and creates a dashboard. In that state make changes to kanga333/grafana-provision-example. This is to change the contents of the dashboard. Git-sync will resynchronize after the change but rewriting the symbolic link will occur.

The /git directory after rewriting is as follows.

```
grafana@22e08a43bd8d:/$ ls -l /git/
total 4
lrwxrwxrwx 1 root root   44 Jul 12 14:17 grafana-provision-example.git -> rev-5045d02f3e12bc9319ffb84e248475d9c3593853
drwxr-xr-x 3 root root 4096 Jul 12 14:17 rev-5045d02f3e12bc9319ffb84e248475d9c3593853
```

Since the symbolic link has been switched, the following error will be displayed.

```
t=2018-07-12T14:20:07+0000 lvl=eror msg="failed to search for dashboards" logger=provisioning.dashboard type=file name=midleware error="stat /git/rev-f0f7a164ba1fdc2b792a443a04d63072408f81f8/provisioning: no such file or directory"
```

I think that git-sync is a side-car container and syncing the configuration file with git is a common approach such as k8s. The essence of what I want to do is not to rewrite the symlink, but to synchronize the configuration using git-sync. Since git-sync has rewritten the symlink to realize atomic change, I have encountered this problem.
