### ISSUE TITLE
LDAP Attributes are set to empty string on user creation

### ISSUE THREAD

**Issue by nlowe** [grafana/grafana#12564]
Please include this information:
### What Grafana version are you using?
5.2.0 (Also reproduced in 5.1.4)

### What datasource are you using?
N/A (Haven't gotten that far)

### What OS are you running grafana on?
kubernetes on ubuntu 16.04

### What did you do?
Configure LDAP to connect to active directory and map one of my groups as admin and `*` as viewer.

### What was the expected result?
Grafana logs me in correctly, creating my user with the appropriate attributes and permissions.

### What happened instead?
Grafana appears to create a user for me with empty attributes. Groups are ignored, and no other users can login because they have the same empty attributes, violating unique constraints.

<details>

<summary>grafana.ini (Rendered by helm)</summary>

```ini
[analytics]
check_for_updates = true
[auth.ldap]
config_file = /etc/grafana/ldap.toml
enabled = true
[grafana_net]
url = https://grafana.net
[log]
filters = ldap:debug
mode = console
[paths]
data = /var/lib/grafana/data
logs = /var/log/grafana
plugins = /var/lib/grafana/plugins
provisioning = /etc/grafana/provisioning
```

</details>

<details>

<summary>ldap.toml (Rendered by helm)</summary>

```toml
verbose_logging = true

[[servers]]
host = "ad.mydomain.net"
port = 636
use_ssl = true
start_tls = false
ssl_skip_verify = true
bind_dn = "MYDOMAIN\\%s"
search_filter = "(sAMAccountName=%s)"
search_base_dns = ["dc=mydomain,dc=net"]

[servers.attributers]
name = "givenName"
surname = "sn"
username = "sAMAccountName"
member_of = "memberOf"
email = "mail"

[[servers.group_mappings]]
group_dn = "CN=SEC - Cloud DevOps Support,OU=Security Groups,DC=MyDomain,DC=net"
org_role = "Admin"

[[servers.group_mappings]]
group_dn = "*"
org_role = "Viewer"
```

</details>

Relevant server logs:

```text
t=2018-07-10T18:26:13+0000 lvl=dbug msg="Ldap User found" logger=ldap info="(*login.LdapUserInfo)(0xc420355ce0)({\n DN: (string) (len=80) \"CN=Nathan Lowe,OU=Users,OU=Quality Assurance,OU=CTO,OU=Westlake,DC=MyDomain,DC=net\",\n FirstName: (string) \"\",\n LastName: (string) \"\",\n Username: (string) \"\",\n Email: (string) \"\",\n MemberOf: ([]string) {\n }\n})\n"
t=2018-07-10T18:26:13+0000 lvl=dbug msg="Updating last user_seen_at" logger=context userId=2 orgId=1 uname= user_id=2
```

Did I miss a step? I made [a small go program](https://gist.github.com/nlowe/a745947416f3917a22ef8144ec0fbf4f) that replicates pretty closely what grafana is doing https://github.com/grafana/grafana/blob/55780972109190b57b3b1fd48a899ec35466e92e/pkg/login/ldap.go#L91-L117 

As you can see, it correctly parses the attributes.
