### ISSUE TITLE
[Feature Request] Please add an option to specify Scrape interval in the prometheus datasource provisioning file

### ISSUE THREAD

**Issue by arno01** [grafana/grafana#12656]
Please add an option to specify ``Scrape interval`` in the prometheus datasource provisioning file.

Maybe also ``Query timeout`` and ``HTTP Method`` as well.

### What Grafana version are you using?
5.2.1

### What datasource are you using?
Prometheus

### What OS are you running grafana on?
Ubuntu Linux 4.15

### What did you do?
Created a prometheus datasource provisioning configuration.

- ``/etc/grafana/provisioning/datasources/prometheus.yaml``

```
apiVersion: 1

datasources:
- name: Prometheus
  version: 1
  editable: false
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prom:9090
```

### What was the expected result?
I wanted to see there is scrape interval setting but there is none according to the ``pkg/services/provisioning/datasources/types.go`` file from v5.2.1 branch.

### What happened instead?
N/A

### If related to metric query / data viz:
N/A

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
N/A

**Comment by torkelo** [comment]
Add this

jsonData:
     timeInterval: "15s"

**Comment by dt-rush** [comment]
@torkelo, This doesn't seem to be working anymore... using `Grafana v5.3.2 (0d821d0)`.

My `provisioning/datasources/all.yml`:

```
datasources:
- name: 'prometheus'
  type: 'prometheus'
  access: 'proxy'
  org_id: 1
  url: 'https://prometheus.xxxxxxxxxx.io'
  is_default: true
  version: 1
  editable: true
  jsonData:
    timeInterval: '5m'
```

**Comment by marefr** [comment]
@dt-rush you'll need to restart Grafana for the datasource provisioning changes to take effect. Make sure that you use `apiVersion: 1` and use camelCase properties, like this:

```yaml
apiVersion: 1

datasources:
  - name: gdev-prometheus
    type: prometheus
    access: proxy
    isDefault: true
    url: http://localhost:9090
    jsonData:
      timeInterval: '5m'
```

Please refer to [documentation](http://docs.grafana.org/administration/provisioning/#datasources) for further information.
