### ISSUE TITLE
Alerts refer to datastore with ID whereas graphs don't

### ISSUE THREAD

**Issue by Crocmagnon** [grafana/grafana#12867]
### What Grafana version are you using?
- 5.2.1

### What datasource are you using?
- Prometheus

### What OS are you running grafana on?
- https://github.com/grafana/grafana-docker, hosted on Ubuntu 18.04

### What did you do?
I redeployed my service with this config :
```yaml
apiVersion: 1

deleteDatasources:
  - name: Prometheus

datasources:
  - name: Prometheus
    type: prometheus
```

Everytime, the ID of the datasource changed which is normal.

### What was the expected result?
Expecting both graphs and alerts to continue working, or both to break.

### What happened instead?
Though graphs had no issue, alerts were broken after a redeploy. I worked around this by removing the `deleteDatasources` as I don't need it since the `datasources` creates or updates the source.
