### ISSUE TITLE
Add more detailed logging for sending emails (EOF notification email)

### ISSUE THREAD

**Issue by weeco** [grafana/grafana#13041]
### What Grafana version are you using?
5.2.2
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
Docker image -> FROM grafana/grafana:5.2.2
### What did you do?
I wanted to add the possibility to send alert notifications via Email. To achieve this I have adapted the grafana.ini to:

```ini
[smtp]
enabled = true
host = smtp.gmail.com:465
;user =
# If the password contains # or ; you have to wrap it with trippel quotes. Ex """#password;"""
;password =
;cert_file =
;key_file =
;skip_verify = false
;from_address =
from_name = Grafana
```

The username and password variables are set using environment variables:

```yml
    - name: GF_SMTP_USER
      valueFrom:
        secretKeyRef:
          key: username
          name: mailing-credentials
    - name: GF_SMTP_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: mailing-credentials
    - name: GF_SMTP_FROM_ADDRESS
      valueFrom:
        secretKeyRef:
          key: username
          name: mailing-credentials
```

**Additional information:**
- We are running grafana in a kubernetes cluster
- We have two other services in the same kubernetes cluster which successfully send emails using the exact same email credentials. Additionally I have ensured there is no 2FA authentication or similiar gmail settings preventing grafana from sending emails.
- The password doesn't contain any double quotes or hashtags
- The SMTP settings show up in the grafana dashboard under admin -> settings
- Under /usr/share/grafana/public/emails there is a `alert_notification_example.html` file which has read permissions and contains a couple HTML lines:
- I have tried various configurations (smtp-relay.gmail.com), each host with different port (25, 465, 587), skip_verify true/false, none of them were successful
- I disabled system wide IPv6 resolving by creating an own dockerfile with `COPY ./gai.conf /etc/gai.conf` where gai.conf contains nothing but `precedence ::ffff:0:0/96  100`
```
-rw-r--r--  1 root root 27653 Jul 25 11:21 alert_notification_example.html
```

### What was the expected result?
To test the email feature I used the "Send test email" button. I expected it to send a mail to the account I entered in the below "Email addresses" text box.

### What happened instead?
A red alert modal slided in saying "Failed to send alert notifications".

**Container logs**
```
=2018-08-27T14:13:04+0000 lvl=dbug msg="Sending notification" logger=alerting.notifier type=email id=0 isDefault=false
t=2018-08-27T14:13:04+0000 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=[redacted]
t=2018-08-27T14:13:04+0000 lvl=eror msg="Failed to send alert notification email" logger=alerting.notifier.email error=EOF
t=2018-08-27T14:13:04+0000 lvl=eror msg="Failed to send alert notifications" logger=context userId=6 orgId=5 uname=redacted error=EOF
t=2018-08-27T14:13:04+0000 lvl=eror msg="Request Completed" logger=context userId=6 orgId=5 uname=redacted method=POST path=/api/alert-notifications/test status=500 remote_addr=redacted time_ms=208 size=48 referer=https://grafana.service.ops.redacted.com/
t=2018-08-27T14:13:07+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=13
```

### My request

Even though we have enabled Debug logging we haven't got any helpful logs to resolve that issue. It would be very helpful to get more logs to inspect what exactly is happening there and what the gmail api returns.
