### ISSUE TITLE
Split dashboard json file into json panels’ files

### ISSUE THREAD

**Issue by nlevchuk** [grafana/grafana#13080]
Hey guys!

I asked a question [here](https://community.grafana.com/t/split-dashboard-json-file-into-json-panels-files/9912) but no one reply me.

### What Grafana version are you using?
v5.2.2

### What datasource are you using?
Influxdb

### What OS are you running grafana on?

CentOS 7 (x86_64)

### What did you do?

I set up grafana's dashboard config file in /etc/grafana/provisioning/dashboards:

```
apiVersion: 1

providers:
 - name: 'Staging'
   orgId: 1
   folder: ''
   type: file
   options:
     path: /var/lib/grafana/dashboards/staging.json

 - name: 'Production'
   orgId: 1
   folder: ''
   type: file
   options:
     path: /var/lib/grafana/dashboards/production.json
{% endfor %}
```

And than i put customised dashboard and panels inside it in one json file for /var/lib/grafana/dashboards/staging.json and /var/lib/grafana/dashboards/production.json. But since i use Ansible i have one sample.json template file for both staging and production. 

And now i need to add extra panel to Production dashboard only.

I put in /etc directory updated yml file
```
apiVersion: 1

providers:
 - name: 'Staging'
   orgId: 1
   folder: ''
   type: file
   options:
     path: /var/lib/grafana/dashboards/staging/

 - name: 'Production'
   orgId: 1
   folder: ''
   type: file
   options:
     path: /var/lib/grafana/dashboards/production/
```

and create new directory and file structure in /var/lib 
```
- /var/lib/grafana/dashboards/production/all.json
- /var/lib/grafana/dashboards/production/http_response.json

- /var/lib/grafana/dashboards/staging/all.json
```

### What was the expected result?

Grafana will use all json files from /var/lib/grafana/dashboards/production/ to prepare one dashboard and i can see it on my grafana site.

### What happened instead?

Grafana created empty dashboard called HTTP_RESPONSE

Thanks for help!
