### ISSUE TITLE
Incomplete dashboards provisioning documentation

### ISSUE THREAD

**Issue by walterdolce** [grafana/grafana#13225]
The [Grafana dashboard provisioning documentation](http://docs.grafana.org/v5.0/administration/provisioning/#dashboards) says:

> Each config file can contain a list of `dashboards providers` that will load dashboards into Grafana from the local filesystem.

What are those "providers"? What can they be?

Then, in the example snippet you see the following:
```
apiVersion: 1

providers:
- name: 'default'
  orgId: 1
  folder: ''
  type: file
  disableDeletion: false
  editable: false
  options:
    path: /var/lib/grafana/dashboards
```

What is or is not supported in this file?

For example, what are the possible values for `type`? What are the possible values that can go underneath `options`?

As a user I would expect to have all possible configuration parameters to be documented but it seems that's not currently the case. 

Thank you.

### What Grafana version are you using?
5.2.3

### What datasource are you using?
N/A

### What OS are you running grafana on?
Off the official's Docker Grafana image
