### ISSUE TITLE
root_url value in /etc/grafana/grafana.ini is not being used for redirect_uri

### ISSUE THREAD

**Issue by wadadli** [grafana/grafana#14006]
Please include this information:
### What Grafana version are you using?
5.3.2 - using the Helm chart
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
Ubuntu (GKE)
### What did you do?
```
grafana.ini:
  paths:
    data: /var/lib/grafana/data
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  analytics:
    check_for_updates: true
  log:
    mode: console¬
  grafana_net:¬
    url: https://grafana.net
  sever:
    protocol: https
    domain: example.com
    root_url: https://example.com/
    enforce_domain: true # I have tried without this as well
  auth.github:
    enabled: true
    allow_sign_up: true
    client_id:saf768saf76890asg986a
    client_secret: 435678987654356789765435678
    scopes: user:email,read:org
    auth_url: https://github.com/login/oauth/authorize
    token_url: https://github.com/login/oauth/access_token
    api_url: https://api.github.com/user
    allowed_organizations: foo
```
### What was the expected result?
I expected github login to work.
### What happened instead?
git hub login err `redirect_uri_mismatch`
the request param has `redirect_uri: http://localhost:3000/login/github`

Snooping around in the container `/usr/share/grafana/conf/default.ini` seems to be over ruling `/etc/grafana/grafana.ini` for `root_url`
