### ISSUE TITLE
Support changes on dashboard provisioner configuration file

### ISSUE THREAD

**Issue by dominikhahn** [grafana/grafana#14188]
### What Grafana version are you using?
Grafana v5.3.4 (commit: 69630b9)
### What datasource are you using?
Prometheus v2.4.3 (commit: 167a4b4)
### What OS are you running grafana on?
Docker Image using tag 5.3.4 (Debian GNU/Linux 9) using persistent volume
### What did you do?
Change Dashboard Provisioner configuration file
### What was the expected result?
Changes gets recognized by the provisioning service upon restart
### What happened instead?
Grafana doesn't apply the latest configuration changes and relies on the old configuration

**Comment by dominikhahn** [comment]
@xlson sure!
grafana is running on a kubernetes cluster using persistent volume. clean setup, no specific configuration files.

1. run api calls to create organizations and store their ids.
2. create one dashboard provider file which contains all ids from above using a generic file path for all orgs
3. restart grafana container/pod with the new dashboard provider configuration
4. the change doesn't get recognized

**Comment by rstrazza** [comment]
We have a similar case and posted a [question](https://community.grafana.com/t/updating-provisioning-configmaps-on-the-fly-without-downtime-or-a-redeploy/12490) in the community forum. Our use case is about organizing dashboards in folders. New folders and dashboards will be added over time.

Grafana is also running on kubernetes and the `dp.yml` (dahboard providers) file is defined in a ConfigMap that mounts to a volume.

During first time deployment, the `dp.yml` file may look like this and everything works well. Please note folder `folder1`:

```
apiVersion: 1

providers:
- name: "folder1"
  orgId: 1
  folder: "folder1"
  type: file
  disableDeletion: false
  updateIntervalSeconds: 3
  options:
    path: "/data/dashboards/folder1"
```

After adding a few dahsboards in a new folder `folder2`, the ConfigMap is updated and reflected in the filesystem, however, Grafana does not create the new folder nor load the new dashboards. This is how the updated file looks like:

```
apiVersion: 1

providers:
- name: "folder1"
  orgId: 1
  folder: "folder1"
  type: file
  disableDeletion: false
  updateIntervalSeconds: 3
  options:
    path: "/data/dashboards/folder1"
- name: "folder2"
  orgId: 1
  folder: "folder2"
  type: file
  disableDeletion: false
  updateIntervalSeconds: 3
  options:
    path: "/data/dashboards/folder2"
```

Having support for reloading changes in the dashboard provider in this case would be very helpful.

Happy to provide more details if needed. Thanks!

**Comment by zhughes3** [comment]
@dominikhahn did you remove the grafana storage volume before you restarted your container with the new configuration files?

**Comment by dominikhahn** [comment]
@zhughes3 no i didn't. just updated the dashboard providers configuration file and restarted the container.
but funny thing beside: if i do, the new file gets recognized, but the organization doesn't exists anymore ;-)

**Comment by zhughes3** [comment]
@dominikhahn Yeah, that's a shame. I would expect that though since you make a bunch of HTTP calls to create those orgs.

**Comment by torkelo** [comment]
think there is an issue to support live reloading: https://github.com/grafana/grafana/issues/12878

**Comment by xlson** [comment]
@zhughes3 as @torkelo mentioned, Grafana does not support live-reloading the provisioner config.

**Comment by xlson** [comment]
@dominikhahn It sounds like you aren't using a persistent database (either external or as a persistent volume for your sqlite db) with Grafana, this would mean that you the organisations you created before restarting Grafana won't exist after the restart and would cause provisioning to those organisations to fail.

**Comment by dominikhahn** [comment]
> @dominikhahn It sounds like you aren't using a persistent database (either external or as a persistent volume for your sqlite db) with Grafana, this would mean that you the organisations you created before restarting Grafana won't exist after the restart and would cause provisioning to those organisations to fail.

The Grafana instance is using a persistent volume. should i provide some more infos/configs/logfiles?

**Comment by dominikhahn** [comment]
@xlson the path where the persistent volume is mounted:
`/var/lib/grafana`

grafana.ini:
```
[server]
domain = grafana.example.com
[alerting]
enabled = false
[analytics]
check_for_updates = false
reporting_enabled = false
[auth.basic]
enabled = true
[auth.ldap]
allow_sign_up = true
config_file = /etc/grafana/ldap.toml
enabled = true
verbose_logging = true
[dashboards]
versions_to_keep = 5
[grafana_net]
url = https://grafana.net
[log]
filters = ldap:debug,provisioning.datasources:debug,provisioning.dashboard:debug
mode = console
[paths]
data = /var/lib/grafana/data
logs = /var/log/grafana
plugins = /var/lib/grafana/plugins
provisioning = /etc/grafana/provisioning
[security]
disable_gravatar = true
login_remember_days = 1
[snapshots]
external_enabled = false
[users]
allow_org_create = false
allow_sign_up = false
auto_assign_org = true
login_hint = username
```
pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: grafana-353-rfr92
  namespace: monitoring
spec:
  containers:
    - env:
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              key: admin-user
              name: grafana
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: admin-password
              name: grafana
      image: 'grafana/grafana:5.4.2'
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 10
        httpGet:
          path: /api/health
          port: 3000
          scheme: HTTP
        initialDelaySeconds: 60
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 30
      name: grafana
      ports:
        - containerPort: 80
          name: service
          protocol: TCP
        - containerPort: 3000
          name: grafana
          protocol: TCP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /api/health
          port: 3000
          scheme: HTTP
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 64Mi
      volumeMounts:
        - mountPath: /etc/grafana/grafana.ini
          name: config
          subPath: grafana.ini
        - mountPath: /etc/grafana/ldap.toml
          name: grafana-ldap-sync
          subPath: ldap.toml
        - mountPath: /var/lib/grafana/dashboards/builtin
          name: dashboards-builtin
        - mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
          name: config
          subPath: datasources.yaml
        - mountPath: /etc/grafana/provisioning/dashboards/dashboardproviders.yaml
          name: dashboard-providers
          subPath: dashboardproviders.yaml
        - mountPath: /var/lib/grafana
          name: storage
  volumes:
    - configMap:
        defaultMode: 420
        name: grafana-dashboard-providers
      name: dashboard-providers
    - configMap:
        defaultMode: 420
        name: grafana
      name: config
    - configMap:
        defaultMode: 420
        name: grafana-dashboards-builtin
      name: dashboards-builtin
    - name: grafana-ldap-sync
      secret:
        defaultMode: 420
        items:
          - key: ldap-toml
            path: ldap.toml
        secretName: grafana-ldap-sync
    - name: storage
      persistentVolumeClaim:
        claimName: grafana
```
persistent volume claim:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: grafana
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  phase: Bound
```
