### ISSUE TITLE
Grafana creating multiple alerts

### ISSUE THREAD

**Issue by benny1611** [grafana/grafana#14526]
### What Grafana version are you using?
Grafana v5.4.2 (commit: d812109)
### What datasource are you using?
Prometheus & InfluxDB
### What OS are you running grafana on?
Debian GNU/Linux 9 (stretch)
### What did you do?
I added some graphs and alert rules for the graphs (graphs are provisioned and some alerts are added via a script that I made)
### What was the expected result?
Only ONE alert rule per graph
### What happened instead?
Grafana first created only one alert rule per graph, but then after some time they were doubled, then tripled. In the end I've got 8 alerting rules per graph all working and alerting, that means: every time the service went down I've got 8 same alerts on my notification channel.
It worked fine when I've started to make my dashboards and script (about a month ago), but then all of a sudden it went nuts and started to multiply my alerting rules. I've posted an image below with the alerting rules (a little censored). For example the affected rules are: Bitbucket uptime alert (both are curently duplicated), Wiki uptime alert, Mattermost uptime akert, Manager uptime alert, DEV uptime alert and Sonar 6.

PS: I've also checked the JSON files of the dashboards and they are fine.

![alert](https://user-images.githubusercontent.com/32867903/50076238-6c6f1780-01e1-11e9-8613-73e15322d592.png)

**Comment by torkelo** [comment]
How are you creating your dashboards? Looks like your creating new dashboards (which creates duplicate alert rules)

**Comment by benny1611** [comment]
I've created my dashboards manually (using the UI), then I provisioned them (following this tutorial  [https://56k.cloud/blog/provisioning-grafana-datasources-and-dashboards-automagically/](here))

**Comment by Ijin08** [comment]
Is it only the alerts that are duplicated or are the graph panels also duplicated? So if you check the alerts in panel edit mode are there more than one alert there?

Is it possible to show the script that you are using?

**Comment by benny1611** [comment]
Only alerts are duplicated, the panels and the dashboards are not. I can't show you my script, but I can tell you what it does:
- It calculates the next pannel ID (it takes the biggest pannel ID, then adds 2)
- Calculates the position where the next pannel should be (just loooks for biggest y then adds the predefined height on top of the value)
- Adds the new pannel on the specified dashboard (it takes 3 parameters: name of the service, URL and dashboard to be added to)

The script just changes the JSON files of the dashboards (adding/removing pannels and of course adding alerts on the new pannels). I use it to add pannels because a lot of them are the same and I don't want to insert all the pannels manually.

I must mention though: I changed my dashboard.yml from this:
```
apiVersion: 1

providers:
- name: 'standardDashboard' # name of this dashboard configuration
  orgId: 1
  folder: ''
  type: 'file'
  updateIntervalSeconds: 60
  disableDeletion: false
  options:
    path: /var/lib/grafana/dashboards
- name: 'graphs'
  folder: ''
  type: 'file'
  updateIntervalSeconds: 60
  disableDeletion: false
  options:
    path: /var/lib/grafana/dashboards
- name: 'jenkins'
  folder: ''
  type: 'file'
  updateIntervalSeconds: 60
  disableDeletion: false
  options:
    path: /var/lib/grafana/dashboards
```

To this:

```
apiVersion: 1

providers:
- name: 'standardDashboard' # name of this dashboard configuration
  orgId: 1
  folder: ''
  type: 'file'
  updateIntervalSeconds: 60
  disableDeletion: false
  options:
    path: /var/lib/grafana/dashboards/standardDashboard.json
- name: 'graphs'
  folder: ''
  type: 'file'
  updateIntervalSeconds: 60
  disableDeletion: false
  options:
    path: /var/lib/grafana/dashboards/graphs.json
- name: 'jenkins'
  folder: ''
  type: 'file'
  updateIntervalSeconds: 60
  disableDeletion: false
  options:
    path: /var/lib/grafana/dashboards/jenkins.json

```

And it worked, I'm not having this problem anymore (I don't know if I fixed it though but for now I'm not having this problem anymore. Even after a few restarts I'm still having just one alert per graph)
