### ISSUE TITLE
[Provisioning dashboard] - new folder empty if config change

### ISSUE THREAD

**Issue by ahurtaud** [grafana/grafana#14932]
### What Grafana version are you using?
v5.4.3
### What OS are you running grafana on?
docker
### What did you do?
Change the grafana folder on the dashboard provisioning config file.
```yaml
    - name: 'system'
      orgId: 1
      folder: 'System'
      type: file
      disableDeletion: false
      updateIntervalSeconds: 30 #how often Grafana will scan for changed dashboards
      options:
        path: /var/lib/grafana/provisioning/dashboards/System/
```
to
```yaml
    - name: 'system'
      orgId: 1
      folder: 'NEW System'
      type: file
      disableDeletion: false
      updateIntervalSeconds: 30 #how often Grafana will scan for changed dashboards
      options:
        path: /var/lib/grafana/provisioning/dashboards/System/
```
### What was the expected result?
Provisioned dashboards should be within the new grafana folder.
### What happened instead?
The new grafana folder was created empty, and provisioned dashboards stayed in the old folder.
![screen](https://user-images.githubusercontent.com/25080995/51321430-06391700-1a63-11e9-907c-63f404777615.png)

### More info:
When a provisioned dashboard is deleted from the old folder, the provisioning add it to the new folder.
![screen](https://user-images.githubusercontent.com/25080995/51321500-3a143c80-1a63-11e9-8943-65c810bc643e.png)
