### ISSUE TITLE
Alert rules being lost (or misconfigured) after each docker-compose down && up

### ISSUE THREAD

**Issue by pkaramol** [grafana/grafana#14970]
Please include this information:
### What Grafana version are you using?
 Grafana v5.4.3 (commit: 6539180)
### What datasource are you using?
`prometheus:latest` docker image
### What OS are you running grafana on?
dockerized on `Ubuntu 18.04`
### What did you do?
Created a prometheus - grafana stack.
After configuring via grafana ui some alerts, these seem to produce the following error after each stack restart

```
grafana_1        | t=2019-01-21T13:15:20+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=3 name="Memory Usage (%) alert" error="Could not find datasource Data source not found" changing state to=alerting
```
The error seems to go away after I delete and recreate the alert from scratch;

### What was the expected result?
Keep the alert rules working (as they were initially)

Here is the `grafana` service definition in my `docker-compose.yml`

```

volumes:
    grafana_data: {}


    grafana:
        image: grafana/grafana
        depends_on:
            - prometheus
        ports:
            - 3000:3000
        volumes:
            - grafana_data:/var/lib/grafana
            - ./grafana/provisioning/:/etc/grafana/provisioning/
        env_file:
            - ./grafana/config.monitoring
        restart: always

```
