### ISSUE TITLE
Custom headers for http datasources are not used for alerting queries

### ISSUE THREAD

**Issue by stewartshea** [grafana/grafana#15381]
### What Grafana version are you using?
5.4.3 ( and tested 6.0.0-beta)

### What datasource are you using?
Elasticsearch via Red Hat OpenShift with Oauth 2

### What OS are you running grafana on?
Official docker image running on RHEL 7.6

### What did you do?
- Configured elasticsearch datasource with bearer token (OpenShift auth)
- Tested an alert

### What was the expected result?
- Alert to fire

### What happened instead?
- Alert errored

```
tsdb.HandleRequest() error invalid character 'A' looking for beginning of value
```

 ### Additional Details
If the datasource is configured with TLS client auth, the alert fires without issue: 
```
firing:true
state:"pending"
conditionEvals:"true = true"
timeMs:"208.616ms"
  matches:Array[1]
    0:Object
      metric:"Count"
    value:1.4956695536309128
logs:Array[2]
  0:Object
    message:"Condition[0]: Query Result"
      data:Array[1]
  1:Object
    message:"Condition[0]: Eval: true, Metric: Count, Value: 1.496"
    data:null
```

**Comment by marefr** [comment]
@stewartshea can you please include information about how you have configured bearer token (OpenShift auth), through provisioning?

**Comment by stewartshea** [comment]
@marefr 

Using the dynamic datasource provisioning, the data is passed via the headers under the secureJsonData configuration field. This appears to function properly to actually run the queries, but the alert doesn't seem to fire appropriately. 

```
# # config file version
apiVersion: 1


# # list of datasources to insert/update depending
# # on what's available in the datbase
datasources:
   # <string, required> name of the datasource. Required
 - name: efk-logging
   # <string, required> datasource type. Required
   type: elasticsearch
   # <string, required> access mode. direct or proxy. Required
   access: proxy
   # <int> org id. will default to orgId 1 if not specified
   orgId: 1
   # <string> url
   url: "https://es-logging.lab.pathfinder.gov.bc.ca/" 
   basicAuth: false
   isDefault: true
   # <map> fields that will be converted to json and stored in json_data
   jsonData:
      tlsSkipVerify: true
      httpHeaderName1: "Authorization"
      httpHeaderName2: "X-Remote-User"
      httpHeaderName3: "X-Forwarded-For"
   # <string> json object of data that will be encrypted.
   secureJsonData:
     httpHeaderValue1: "Bearer [bearer-token]"
     httpHeaderValue2: "[username]"
     httpHeaderVaule3: "127.0.0.1"
   version: 1
#   # <bool> allow users to edit datasources from the UI.
   editable: true
```
