### ISSUE TITLE
cannot configure a provisioning path to include the home directory shortcut (~) (tilde expansion)

### ISSUE THREAD

**Issue by bburke4** [grafana/grafana#15543]
### What Grafana version are you using?
5.4.3
### What datasource are you using?
postgres
### What OS are you running grafana on?
macOS Mojave 10.14.2
### What did you do?
Configured the provisioning directory to include my home directory. I tried each of the following to try to workaround the issue:
```ini
[paths]
# folder that contains provisioning config files that grafana will apply on startup and while running.
provisioning = ~/dev/grafana/dev/provisioning/
; provisioning = $HOME/dev/grafana/dev/provisioning/
; provisioning = /../$HOME/dev/grafana/dev/provisioning/
; provisioning = /../~/dev/grafana/dev/provisioning/
```
### What was the expected result?
Grafana would find the provisioning files in my home directory.
### What happened instead?
Grafana logged an error:
```

t=2019-02-19T16:34:21-0500 lvl=info msg="Initializing ProvisioningService" logger=server
t=2019-02-19T16:34:21-0500 lvl=eror msg="can't read datasource provisioning files from directory" logger=provisioning.datasources path=/usr/local/opt/grafana/share/grafana/~/dev/grafana/dev/provisioning/datasources
```

**Comment by bburke4** [comment]
This also applies for dashboard-provider configurations. For example, with this config:
```
providers:
- name: 'someName'
  folder: 'someName'
  type: file
  disableDeletion: false
  updateIntervalSeconds: 600 #how often Grafana will scan for changed dashboards
  options:
    path: ~/dev/grafana/dashboards/someDashboards
```

I see this error logged: 
```
t=2019-02-20T09:16:45-0500 lvl=eror msg="Cannot read directory" logger=provisioning.dashboard type=file name=someDashboards error="stat ~/dev/grafana/dashboards/someDashboards: no such file or directory"
```
