### ISSUE TITLE
Improve the grafana/ui select multi-value support style

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#15954]
The select component in grafana UI supports `isMulti={true}` but the style gets funky:
![image](https://user-images.githubusercontent.com/705951/54223824-8d2fcc00-44b5-11e9-90e6-d5d31c21add1.png)

While looking at the styles, also consider the `no options` style:
![image](https://user-images.githubusercontent.com/705951/54223891-b2243f00-44b5-11e9-8533-f9848d47e5cc.png)

FYI, this has a storybook example in #15938

**Comment by dehrax** [comment]
Something is setting
```css
.gf-form-select-box__value-container > div {
    display: inline-block;
}
```
But I can't seem to find it. Is it Emotion somewhere? I'd like to use this selector for `vertical-align: middle`, to center the input field vertically.
