### ISSUE TITLE
Extra settings for the Prometheus datasource when used for Thanos or other LTS solutions

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#16665]
Thanos offers extra settings that can be very useful when looking at long term data such as `downsampling`, `timeout`, `partial_response`, `dedup`

Instead of building a new datasource plugin for Thanos which would be a lot of code duplication, we should add a setting to the Prometheus datasource where LTS storage alternatives can be configured. Query editors and other parts of Grafana can then show those when it makes sense instead of duplicating all other aspects of the Prometheus datasource.

**Comment by povilasv** [comment]
I'll try to implement something to what we discussed in https://github.com/grafana/grafana/pull/16574 .
So you can assign this to me. Also I'll let thanos community know aboiut this.

Could you help me on the UX bits?

```
  jsonData:
    # enable Thanos
    long_term_storage: thanos
    deduplication: true
    timeout: 2m
    downsampling: false
    partial_response: false
```

Maybe we should prefix flags? instead of `deduplication` `thanos_deduplication: true` or do nested structs?
