### ISSUE TITLE
Datasource basic auth requires user to be present in Grafana

### ISSUE THREAD

**Issue by viralkamdar** [grafana/grafana#16868]
**What happened**: Basic auth doesn't work for data source if the user is not present in Grafana or has different password

**What you expected to happen**: Basic auth credentials required for a data source need not be present in Grafana

**How to reproduce it (as minimally and precisely as possible)**: Create a Prometheus data source which requires basic authentication. The user for the basic authentication should not be present in Grafana. Click on test data source. The test fails with the error `EROR[05-03|11:57:33] Invalid username or password             logger=context error="Invalid Username or Password"`. Then create the required user in Grafana with the correct credentials and click on test data source again. The test passes now.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v6.1.6 (cf9cb45)
- Data source type & version: Prometheus 2.8.1
- OS Grafana is installed on: Linus/MacOS
- User OS & Browser: MacOS, Firefox/Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
What did you specify in your data source settings? (Basic Auth Username / password) ?

**Comment by torkelo** [comment]
How are you authenticating against Grafana itself?

**Comment by viralkamdar** [comment]
Grafana has a different basic auth username and password.
Datasources.yaml file is like below
```
apiVersion: 1
datasources:
- name: Prometheus
  type: prometheus
  orgId: 1
  access: proxy
  url: https://prometheus.example.com
  isDefault: true
  basicAuth: true
  basicAuthUser: exampleuser
  basicAuthPassword: examplepassword
```
