### ISSUE TITLE
Frequency and send_reminders fields are ignored during notifier provisioning

### ISSUE THREAD

**Issue by kanuahs** [grafana/grafana#17196]
**What happened**:
Grafana ignores the `frequency` and `send_reminders` in notifiers.yaml during provisioning.
![actual](https://user-images.githubusercontent.com/6103603/58092012-b1600580-7be8-11e9-88d1-a78e459aefb6.png)

**What you expected to happen**:

`send_reminder` and `frequency` should be set according to the values defined in notifiers.yaml
![expected](https://user-images.githubusercontent.com/6103603/58092025-b91faa00-7be8-11e9-98d6-85a0493a18b1.png)

**How to reproduce it (as minimally and precisely as possible)**:
1.) Write a notifiers.yaml provisioning file. eg.
notifiers.yaml
```yaml
notifiers:
  - name: GrafanaAlert
    type: slack
    uid: notifier1
    orgId: 1
    is_default: true
    send_reminders: true
    frequency: 1h
    settings:
      recipient: "#cluster-alerts"
      token: ""
      uploadImage: true
      url: SLACK_URL_HERE
      username: grafana
```

2.) Mount the folder containing the file as a volume when running grafana.
```bash
docker run -it --rm --name=grafana -p 3000:3000 -v /path/to/folder/containing/notifiers:/etc/grafana/provisioning/notifiers/ grafana/grafana:6.1.4
```

**Anything else we need to know?**:

The HTTP API to create notifiers does not have this bug.

**Environment**:
- Grafana version: 6.1.4
- Data source type & version: N/A
- OS Grafana is installed on: N/A
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others: N/A
