### ISSUE TITLE
Grafana resolved alert notifications to Alertmanager being sent not in a proper way

### ISSUE THREAD

**Issue by viberan** [grafana/grafana#17432]
Seems there is an issue in how Grafana sends resolved alert notification to Alertmanager

**What happened**:

there is a Grafana alert setup to send notification to Alertmanager on 15% change in prometheus metric value over last 10 minutes:

![image](https://user-images.githubusercontent.com/45915382/58881186-5519dd00-86e2-11e9-8d73-90ca0bed71d6.png)

Alertmanager groups the alerts by 'alertname' and sends notification to slack channel:

```
global:
  resolve_timeout: 5m

route:
  receiver: 'slack_eugene'   #Fallback
  group_by: ['alertname']
  group_wait: 0s
  group_interval: 5m
  repeat_interval: 2h
  continue: false
  routes:
   - match:
      alertname: "Coverage Drop Detected"
    group_wait: 0s
    receiver: 'slack_eugene_from_grafana'
  - match:
      alertname: "CoverageDropPrometheus"
    group_wait: 0s
    receiver: 'slack_eugene_from_grafana'
```

The snippet above contains two matching rules, one for  "Coverage Drop Detected" which is the alert name being sent from Grafana and the second rule for "CoverageDropPrometheus" which is the alert sent directly from Prometheus with exactly the same alerting conditions as in the Grafana alert. I set it up via Prometheus alert rules as a reference point in order to debug the issue. 

The following templates are used to format messages  in slack:

```
{{- define "slack.condition.coverage_drop_alert" -}}
   {{ if eq .GroupLabels.alertname "Coverage Drop Detected" -}}
      {{- range .Alerts }}
      *AlertName:* {{ .Labels.alertname }}
      *Status*: {{ .Status }}
      *reportId:* {{ .Labels.reportId }}
      {{- end }}
  {{- end }}
{{- end }}

{{- define "slack.condition.coverage_drop_prometheus_alert" -}}
   {{ if eq .GroupLabels.alertname "CoverageDropPrometheus" -}}
      {{- range .Alerts }}
      *AlertName:* {{ .Labels.alertname }}
      *Status*: {{ .Status }}
      *reportId:* {{ .Labels.reportId }}
      {{- end }}
  {{- end }}
{{- end }}
```

So, I've got notification like these:

![image](https://user-images.githubusercontent.com/45915382/58883200-9ad8a480-86e6-11e9-9d82-8c721a4d31a6.png)

![image](https://user-images.githubusercontent.com/45915382/58883232-a926c080-86e6-11e9-9f3e-f94d5930b27c.png)

The problem arise when a notification is being resolved. Grafana seems to send a resolved notification with labels having empty values. This leads to a confusing message content where there is some resolved notification without a label value (empty reportId field) and all the previous alerts are still firing.

![image](https://user-images.githubusercontent.com/45915382/58883410-0c185780-86e7-11e9-840f-73baa573f735.png)

While the resolved message sent directly from Prometheus cleanly reports all alerts in the resolved state:

![image](https://user-images.githubusercontent.com/45915382/58884098-62d26100-86e8-11e9-9794-a3a27c44f57b.png)

**What you expected to happen**:

The resolved notifications in Grafana per individual alert with resolved state and the original content of label values. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.2.1 (the same problem with 6.1.x)
- Data source type & version: Prometheus 2.10.0 (same for Prometheus 2.8.x) - probably not relevant for the case
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Chrome
- Grafana plugins:
- Others:
