### ISSUE TITLE
TLS handshake error for Grafana running with SSL certs in kubernetes cluster

### ISSUE THREAD

**Issue by anarwal** [grafana/grafana#17758]
**What happened**:
I am running Grafana in kube cluster in SSL mode. I have specified following settings in default.ini file:
```
[server]
# Protocol (http or https)
## value comes from kubernetes env variables
protocol = ${PROTOCOL}

# The http port  to use
http_port = 3000

# The public facing domain name used to access grafana from a browser
## value comes from kubernetes env variables
domain = ${DOMAIN}

# Redirect to correct domain if host header does not match domain
# Prevents DNS rebinding attacks
enforce_domain = false

# The full public facing url
root_url = %(protocol)s://%(domain)s:%(http_port)s/

# Log web requests
router_logging = false

# the path relative working path
static_root_path = public

# enable gzip
enable_gzip = true

# https certs & key file
cert_file = ${SSL_CERT_FILE}
cert_key = ${SSL_KEY_FILE}
```

In kube yaml, I have following setup for ports:
Under service resource:
```
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 3000
```
Under Pods:
```
ports:
  - containerPort: 3000
     protocol: TCP
```
The logs of the grafana pods continuously throw:
`2019/06/24 19:12:55 http: TLS handshake error from {IP}:11782: EOF`
Where Port keeps changing and I keep getting TLS handshake error. 

**What you expected to happen**:
Actual application logs from grafana server 

**How to reproduce it (as minimally and precisely as possible)**:
- Deploy Grafana in kubernetes cluster with SSL certs. 
- Grafana server needs to run with HTTPS protocol
- Port needs to be forwarded to 443 for kubernetes cluster 

**Anything else we need to know?**:
- As per my understanding from error thrown in logs, grafana tries to connect server over: `http`, whereas I am running it over `https` and maybe due to that TLS handshake error is thrown. 
- I have already tested cert, key used for grafana server

**Environment**:
- Grafana version: `6.2.4`
- OS Grafana is installed on:  `alpine:3.9`

**Comment by marefr** [comment]
Environment variables in defaults.ini is not supported.

**Comment by anarwal** [comment]
@marefr So I should be using https://grafana.com/docs/installation/configuration/#using-environment-variables? 
Would it work in combination with `defaults.ini`?

**Comment by ericmacfa** [comment]
@marefr
Given that environment variables are not supported in defaults.ini, could you please provide some insight into why the [documentation](https://grafana.com/docs/installation/configuration/#instance-name) illustrates using environment variables?

**Comment by marefr** [comment]
Seems like at least ${HOSTNAME} is supported, but not sure any other environment variables referenced i defaults.ini are. Then you should use the `GF_<section>_<config parameter name>` to override default settings in defaults.ini instead. Does this makes sense?

**Comment by anarwal** [comment]
It does, I thought `${HOSTNAME}` is supported than others should be supported too. Anyway, I will try  `GF_<section>_<config parameter name>`

**Comment by marefr** [comment]
As a general rule of thumb you should never make changes to the defaults.ini since that may be overwritten next time you upgrade Grafana. Instead either add an additional custom.ini or either use environment variables and add any overrides in those.

**Comment by ericmacfa** [comment]
Is it safe to assume that environment variables are supported in `custom.ini`, or are they handled in the same manner as `defaults.ini`?

**Comment by marefr** [comment]
Same manner as defaults.ini

**Comment by ericmacfa** [comment]
Understood. Would it be possible to add a disclaimer to the documentation that indicates:
> environment variables are not supported in defaults.ini

**Comment by marefr** [comment]
Had to double check this since I never used environment variables in .ini files. Apparantly using `${ ENV_VAR}` syntax in .ini files should work. Sorry for the confusion.

So question regarding issue description, how do you provide your environment variables to grafana pod?

**Comment by torkelo** [comment]
can you go to server admin / settings view and verify your settings? 

Can you show the startup logs?

**Comment by anarwal** [comment]
@maref ENV Variables are read either directly from kube.yaml or from secrets. Please see the example below:
```
  env:
        - name: PROTOCOL
          value: "https"
        - name: DOMAIN
          value: {{ dns_address }} //this value is updated by CI job
        - name: ADMIN_USER
          value: "admin"
        - name: ADMIN_PASSWORD
          value: "admin"
        - name: SSL_CERT_FILE
          value: /var/run/secrets/kubernetes.io/server.crt 
        - name: SSL_KEY_FILE
          value: /var/run/secrets/kubernetes.io/server.key
```
