### ISSUE TITLE
Password works only in UI not in Provisioning

### ISSUE THREAD

**Issue by Grey2k** [grafana/grafana#17833]
**What happened**:

Im using same config

```yml
# # config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: mysql_grafana

# list of datasources to insert/update depending
# on what's available in the database
datasources:
  # <string, required> name of the datasource. Required
  - name: mysql_grafana
    # <string, required> datasource type. Required
    type: mysql
    # <string, required> access mode. direct or proxy. Required
    access: direct
    # <string> url
    url: mysql
    # <bool> mark as default datasource. Max one per org
    isDefault: false
    # <bool> allow users to edit datasources from the UI.
    editable: true
    database: "grafana"
    user: "grafana"
    secureJsonData:
      password: "p!@8sword"
```

After start - data source available but password is incorrect, after i copy and paste it in UI - its start work.  What i doing wrong - i checked 5 times - its the same password

**What you expected to happen**:

Data source will be correct

**How to reproduce it (as minimally and precisely as possible)**:

Use this config on 6.2.5 version Grafana.

Also a see that encrypted password in DB changes after i enter it through UI.
May be issue related with secure_key?

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.2.5
- Data source type & version: mysql percona 8.0.13-4.1.el7
- OS Grafana is installed on: docker
- User OS & Browser:
- Grafana plugins:
- Others:
