### ISSUE TITLE
grafana login by oauth login.OAuthLogin(missing saved state)

### ISSUE THREAD

**Issue by xiaoxi1989** [grafana/grafana#17925]
**What happened**:
grafana auth by keycloak and session store in mysql.
first login get error: login.OAuthLogin(missing saved state),
![image](https://user-images.githubusercontent.com/23303904/60657611-3430dd00-9e84-11e9-8c79-929aeb92d1f6.png)

but relogin by **(sign in with oauth)** is fine(no input user and password).
![image](https://user-images.githubusercontent.com/23303904/60657658-427ef900-9e84-11e9-99f4-31ac6847fe27.png)

**What you expected to happen**:
login success

**Environment**:
- Grafana version:
grafana 6.25

- Data source type & version:
mysql5.7

- OS Grafana is installed on:
docker

- User OS & Browser:
macos 1.13.6 
chrome

**Comment by torkelo** [comment]
That is strange, we have no similar reports. Do you always get this on the first login?

**Comment by xiaoxi1989** [comment]
@torkelo  Thank you for your reply. yes, every first login get this error.
my configuration is 
```
[auth.generic_oauth]
enabled = true
name = OAuth
allow_sign_up = true
client_id = grafana
client_secret = 6886cf64-ab2f-42a6-8ef9-c43380d94230
scopes = user:email
auth_url = http://xxxx:18081/auth/realms/grafana/protocol/openid-connect/auth
token_url = http://xxxx:18081/auth/realms/grafana/protocol/openid-connect/token
api_url = http://xxxx:18081/auth/realms/grafana/protocol/openid-connect/userinfo

[database]
# You can configure the database connection by specifying type, host, name, user and password
# as separate properties or as on string using the url properties.
# Either "mysql", "postgres" or "sqlite3", it's your choice
type = mysql
host = xxxxx:3306
name = grafana
user = root
# If the password contains # or ; you have to wrap it with triple quotes. Ex """#password;"""
password = xxxxx


```

**Comment by xiaoxi1989** [comment]
request info
![image](https://user-images.githubusercontent.com/23303904/60704227-6864d600-9f36-11e9-8e2b-79713a2f4a4e.png)

**Comment by xiaoxi1989** [comment]
chrome info 
curl 'http://localhost:3000/login/generic_oauth?state=k8oYTIDNn14diTQ6tz0vQvrcYslEhf7c4cVlD3pSNK4%3D&session_state=2e079150-5234-47ef-9f3f-71da807edfdd&code=8f996c18-4420-4fde-86fd-446a65f65be1.2e079150-5234-47ef-9f3f-71da807edfdd.a37ecfc6-07eb-46ed-bd25-ae8d519cb43e' -H 'Connection: keep-alive' -H 'Cache-Control: max-age=0' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3' -H 'Referer: http://10.13.83.10:18081/auth/realms/grafana/protocol/openid-connect/auth?access_type=online&client_id=grafana&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Flogin%2Fgeneric_oauth&response_type=code&scope=user%3Aemail&state=k8oYTIDNn14diTQ6tz0vQvrcYslEhf7c4cVlD3pSNK4%3D' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: zh-CN,zh;q=0.9' -H 'Cookie: oauth_state=ea46359a58f6951d7091c8e7def416f0e067ea272e4e66c416bb93192946f2af' --compressed

Response Cookies
oauth_state is empty

**Comment by xiaoxi1989** [comment]
this is my fault

i changed grafana.ini to solve the problem.
```
domain = 0.0.0.0
# Redirect to correct domain if host header does not match domain
# Prevents DNS rebinding attacks
enforce_domain = true
# The full public facing url you use in browser, used for redirects and emails
# If you use reverse proxy and sub path specify full url (with sub path)
root_url = http://0.0.0.0:3000
```

**Comment by haf** [comment]
I get the same error; but I'm reluctant to change to `domain = 0.0.0.0` since it's not a domain. Config:

```ini
instance_name = grafana.example.com

[server]
root_url = https://grafana.example.com
domain = grafana.example.com
enforce_domain = false
enable_gzip = true

[security]
admin_password = snip
cookie_secure = true
cookie_samesite = strict
auto_assign_org = true
auto_assign_org_id = 1
auto_assign_org_role = Viewer
viewers_can_edit = false
editors_can_admin = true # default false
login_remember_days = 30

[auth.github]
enabled = true
allow_sign_up = true
client_id = snip
client_secret = snip
scopes = user:email,read:org
auth_url = https://github.com/login/oauth/authorize
token_url = https://github.com/login/oauth/access_token
api_url = https://api.github.com/user

[analytics]
reporting_enabled = false
```

using k8s config:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
    component: grafana
    tier: resources
  name: grafana
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: grafana
      tier: resources
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "3000"
        prometheus.io/scrape: "true"
      labels:
        app: grafana
        tier: resources
    spec:
      containers:
      - image: grafana/grafana:6.3.2
        name: grafana
        ports:
        - containerPort: 3000
          name: http
        resources:
          limits:
            cpu: 500m
            memory: 2500Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: data
        - mountPath: /etc/grafana/grafana.ini
          name: conf
          subPath: grafana.ini
      initContainers:
      - command:
        - chown
        - -R
        - 472:472
        - /var/lib/grafana
        image: busybox:1.30
        name: chown
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: data
      securityContext:
        fsGroup: 472
        runAsUser: 472
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: grafana
      - configMap:
          name: grafana
        name: conf
```

With a HTTPS-terminating nginx proxy in front.
