### ISSUE TITLE
Provisioned values containing $ character is replaced with empty string

### ISSUE THREAD

**Issue by compelx** [grafana/grafana#17986]
**What happened**:
We upgraded from `Grafana v5.4.4 (commit: e86baa5)` to `Grafana v6.2.5 (commit: 6082d19)` and provisioned Microsoft SQL Server datasources using Windows auth appears to have broke. Testing the datasource throws `InitialBytes InitializeSecurityContext failed 8009030c`. It's acting like the creds are wrong. Eventually, clicking test enough time actually locks the account in Active Directory.

I've confirmed the password is correct and that the same .yml datasource file when used in the conf for a Grafana instance of v5.4.4 works. I can test and use it to build dashboards just fine.

Interestingly, if I create the datasource via the UI in Grafana 6.2.5 it works. I can test successfully.

**What you expected to happen**:

I expected that when I click test on that provisioned datasource it is successful like in v5 of Grafana

**How to reproduce it (as minimally and precisely as possible)**:

Since it works fine if I create the datasource via UI, I checked out what `/api/datasources` returned and compared the two datasources. Here is what I'm getting:

    {
    "id": 31,
    "orgId": 1,
    "name": "Created via UI",
    "type": "mssql",
    "typeLogoUrl": "public/app/plugins/datasource/mssql/img/sql_server_logo.svg",
    "access": "proxy",
    "url": "mysqlserver.infra.corp.local",
    "password": "",
    "user": "infra\\svc_mywindowsaccount",
    "database": "mydatabase",
    "basicAuth": false,
    "isDefault": false,
    "jsonData": {
    "encrypt": "false"
    },
    "readOnly": false
    }

vs

    {
    "id": 30,
    "orgId": 1,
    "name": "Created via provisioner",
    "type": "mssql",
    "typeLogoUrl": "public/app/plugins/datasource/mssql/img/sql_server_logo.svg",
    "access": "",
    "url": "mysqlserver.infra.corp.local",
    "password": "",
    "user": "infra\\svc_mywindowsaccount",
    "database": "mydatabase",
    "basicAuth": false,
    "isDefault": false,
    "jsonData": {
    "connMaxLifetime": 14400,
    "maxIdleConns": 2,
    "maxOpenConns": 0
    },
    "readOnly": true
    }

Here is what the datasource yml looks like:
```
apiVersion: 1

datasources:
  - name: 'Created via provisioner'
    type: mssql
    url: mysqlserver.infra.corp.local
    database: mydatabase
    user: infra\svc_mywindowsaccount
    jsonData:
      maxOpenConns: 0         # Grafana v5.4+
      maxIdleConns: 2         # Grafana v5.4+
      connMaxLifetime: 14400  # Grafana v5.4+
    secureJsonData:
      password: "???"

```

**Anything else we need to know?**:
I spun up a vanilla, brand-new instance of Grafana 6.2.5 and tested with the provisioned datasource and got the same results. If I go back to v5 Grafana or even stand up a vanilla, brand-new instance of Grafana 5.4.4 (just tried this) the provisioned datasource works. I can click test and it's successful.

**Environment**:
- Grafana version: We upgraded from `Grafana v5.4.4 (commit: e86baa5)` to `Grafana v6.2.5 (commit: 6082d19)`
- Data source type & version: Microsoft SQL Server
- OS Grafana is installed on: Windows Server 2016
- User OS & Browser: Windows 10 and Chrome 75.0.3770.100
- Grafana plugins: 
- Others:
