### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS when grafana redirects to /login (behind nginx reverse proxy)

### ISSUE THREAD

**Issue by romenrg** [grafana/grafana#18299]
**What happened**:

I am trying to access Grafana at `localhost:5000/grafana` and I am getting a ERR_TOO_MANY_REDIRECTS error in my browser, being automatically redirected to `localhost:5000/grafana/login`.

**What you expected to happen**:

I expected to see the Grafana UI working normally, not the redirection loop.

**How to reproduce it (as minimally and precisely as possible)**:

I have the following **nginx congif**:
```
set $grafana_upstream_endpoint http://grafana:5000/;

location /grafana/ {
  proxy_pass	     $grafana_upstream_endpoint;
  proxy_set_header   Host $host;
}
```

And I have the following **grafana.ini** config:
```
[server]
domain = localhost
http_port = 5000
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: latest (using docker)
- User OS & Browser: MacOs and Chrome

**Comment by aocenas** [comment]
Hey @romenrg can you check this older issue https://github.com/grafana/grafana/issues/2578 ? There are some suggestions that may help. Please let me know if any of them helped or not.

**Comment by romenrg** [comment]
Hi @aocenas, thanks for replying :)

I have just managed to get it working. Posting here what I ended up doing in case someone else faces a similar issue.

- First, I stopped using the config file and changed the "grafana" service configuration in my docker-compose file to the following:

```
  grafana:
    container_name: grafana
    image: "grafana/grafana:latest"
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
      - **GF_SERVER_ROOT_URL=http://${EXTERNAL_DOMAIN}:${EXTERNAL_PORT}/grafana**
    healthcheck:
      test: curl --user admin:admin -sS http://localhost:3000/ | grep "grafana" || exit 1
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 60s
```

Then, I modified the corresponding nginx config for grafana to:

```
set $grafana_upstream_endpoint http://grafana:3000;

location /grafana/ {
  proxy_pass	$grafana_upstream_endpoint;
  rewrite       ^/grafana/?(.*) /$1 break;
  include       /etc/nginx/proxy.conf;
}
```

Just for full context, here is my `proxy.conf` file:

```
proxy_set_header    Host                $host:$server_port;
proxy_set_header    X-Real-IP           $remote_addr;
proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
proxy_set_header    X-Forwarded-Host    $host;
proxy_set_header    X-Forwarded-Port    $server_port;
proxy_set_header    X-Forwarded-Server  $host:$server_port;
proxy_set_header    X-Forwarded-Proto   $scheme;

proxy_max_temp_file_size 0;

client_max_body_size       100m;
client_body_buffer_size    128k;

proxy_connect_timeout      90;
proxy_send_timeout         90;
proxy_read_timeout         90;

proxy_buffer_size          4k;
proxy_buffers              4 32k;
proxy_busy_buffers_size    64k;
proxy_temp_file_write_size 64k;
```
