### ISSUE TITLE
First attempt of creating an organization fails with PostgreSQL database

### ISSUE THREAD

**Issue by lucassousaf** [grafana/grafana#18628]
**What happened**:
First attempt of creating an organization fails with PostgreSQL database. Once it fails, the next requests succeed. This Bug happens in both GUI and HTTP API.
**What you expected to happen**:
Create an organization on first attempt.
**How to reproduce it (as minimally and precisely as possible)**:
* Run `docker-compose up` with the following configuration:
```yml
version: "2.1"

services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=grafana
      - POSTGRES_PASSWORD=grafana
      - POSTGRES_DB=grafana
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U grafana"]
      interval: 10s
      timeout: 5s
      retries: 5
  grafana:
    image: grafana/grafana:6.3.3
    environment:
      - GF_SERVER_HTTP_PORT=4000
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=postgres
      - GF_DATABASE_USER=grafana
      - GF_DATABASE_PASSWORD=grafana
      - GF_DATABASE_NAME=grafana
      - GF_DATABASE_SSL_MODE=disable
    ports:
      - 4000:4000
    depends_on:
      postgres:
        condition: service_healthy
```
* Try to create a new organization: 
  * First attempt will fail but the second will succeed
  * GUI: http://localhost:4000/org/new
  * HTTP API: 
    ```sh
    curl --user admin:admin -X POST -v -H "Content-Type: application/json" -H "Accept: application/json" -d '{"name": "test-org"}' http://localhost:3000/api/orgs
    ```

**Anything else we need to know?**:
Without database or using MySQL works as expected.
**Environment**: 
- Grafana version: 6.3.3
- Data source type & version: PostgreSQL 9.6, 12
- OS Grafana is installed on: [Docker container](https://hub.docker.com/r/grafana/grafana/)
- User OS & Browser:Ubuntu 18.04, Firefox 68.0.2
- Grafana plugins: No
- Others: No
