### ISSUE TITLE
provisioned and displayed dashboard is not reloaded

### ISSUE THREAD

**Issue by aklemp** [grafana/grafana#18647]
**What happened**:

I am provisioning dashboards to Grafana in OpenShift. I.e. the dashboards are provided via ConfigMaps and mounted into the Grafana container where they are picked up, can be selected and displayed. The dashboards have an auto-refresh configured (1m) and `updateIntervalSeconds: 30` in the provisioning configuration. UIDs are used that do not change and only the version and of course content is changed. However, if a dashboard is being displayed, it is not updated to show the changes. This is especially a problem in kiosk mode without user interaction.

**What you expected to happen**:

The shown dashboard is reloaded if there is a newer version for that UID.

**How to reproduce it (as minimally and precisely as possible)**:

* /etc/grafana/provisioning/dashboards/all.yaml
  ```
  apiVersion: 1
  providers:
    - name: default
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: false
      updateIntervalSeconds: 30
      options:
        path: /var/lib/grafana/dashboards
  ```
* Any valid dashboard `/var/lib/grafana/dashboards/mydashboard.json` with auto refresh.
* Open the dashboard in Grafana.
* Change the file `/var/lib/grafana/dashboards/mydashboard.json` by increasing the version field and a panel title for example.
* Wait for the panel title to be refreshed automatically.

**Anything else we need to know?**:

Closing and reopening the dashboard or pressing F5 in the browser reloads the dashboard to reflect the changes.

**Environment**:
- Grafana version: v6.2.2 (07540df)
- Data source type & version: Prometheus
- OS Grafana is installed on: Docker: grafana:6.2.2
- User OS & Browser: Debian & Chrome
- Grafana plugins:
- Others:
