### ISSUE TITLE
Azure Monitor datasource provisioning using YML needs to know the datasource id before its creation

### ISSUE THREAD

**Issue by stncrn** [grafana/grafana#18849]
Hello

On my Grafana 2.6.5 installation, I created all dashboards and datasources using YML provisioning.

This feature is very lightly documented for the Azure Monitor datasource. But I managed to make it work using this old discussion : [https://github.com/grafana/azure-monitor-datasource/issues/65#issuecomment-429840138](https://github.com/grafana/azure-monitor-datasource/issues/65#issuecomment-429840138)

However, this had to be done in 2 times, and is quite hard to totally automate:

1 - Provision the datasource with a random id in the url parameter:
```yaml
apiVersion: 1

datasources:
- name: Azure Monitor
  type: grafana-azure-monitor-datasource
  access: proxy
  orgId: 1
  url: /api/datasources/proxy/2
  isDefault: true
  jsonData:
    cloudName: azuremonitor
    subscriptionId: xxxx
    tenantId: xxxx
    clientId: xxxx
    logAnalyticsDefaultWorkspace: xxxx
    azureLogAnalyticsSameAs: true
    keepCookies: []
    appInsightsAppId: xxxx
  secureJsonData:
    clientSecret: xxxx
    appInsightsApiKey: xxxx
  editable: true
```

2 - Get the datasaource id that has been assigned, by querying /api/datasources.
```json
[
  { "..." : "..."} ,
  {
    "id": 4,
    "orgId": 1,
    "name": "Azure Monitor",
    "type": "grafana-azure-monitor-datasource",
    "..." : "...",
    "access": "proxy",
    "url": "/api/datasources/proxy/2",
    "..." : "..."
  },
  { "..." : "..."}
]
```
Then modify the YML file, to update the url field:
```yaml
apiVersion: 1

datasources:
- name: Azure Monitor
  ...
  url: /api/datasources/proxy/4
  ...
```

I would have expected that the url field populates automatically, using the id assigned at the datasource creation.
