### ISSUE TITLE
unable to delete datasource when added through config file

### ISSUE THREAD

**Issue by martinrw** [grafana/grafana#18848]
**What happened**:
I am using puppet to manage my datasources, all this does is add a file into /etc/grafana/provisioning/datasources/ called puppetprovisioned.yaml

This file contains each of my datasources like this:
```
datasources:
- name: datasourcename
  grafana_url: http://localhost:8080
  grafana_user: admin
  grafana_password: adminpass
  type: influxdb
  url: https://influx.com:8086
  user: grafana
  password: influxgrafanapass
  database: databasename
  access: proxy
```
Adding a new datasource works fine but if I remove that datasource from the config file and restart grafana-server the datasource still remains in the web UI

If I attempt to delete it from the API I get this:

> {"message":"Cannot delete read-only data source"}

and in the web UI I see this message:

> This datasource was added by config and cannot be modified using the UI. Please contact your server admin to update this datasource.

and the delete button is greyed out

**What you expected to happen**:
When the datasource is removed from the config file and the service is restarted the datsource should disappear completely from grafana

**How to reproduce it (as minimally and precisely as possible)**:
Add a datasource by writing to a config file in /etc/grafana/provisioning/datasources/
restart the service - you will see the datasource appear
now remove that datasource config file
restart the service - the datasource still seems to exist in grafana

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.3.3-1.x86_64
- Data source type & version: tried both elasticsearch and influxdb
- OS Grafana is installed on: CentOS 7.6
- User OS & Browser: Fredora 30 + firefox 68
- Grafana plugins: grafana-piechart-panel, grafana-clock-panel, natel-influx-admin-panel
- Others:

**Comment by torkelo** [comment]
related to this: https://github.com/grafana/grafana/issues/12875

**Comment by ibanmarco** [comment]
You need to disable `read-only` and enable `editable` feature for each datasource you want to add:

datasources:
- name: datasourcename
  grafana_url: http://localhost:8080
  grafana_user: admin
  grafana_password: adminpass
  type: influxdb
  url: https://influx.com:8086
  user: grafana
  password: influxgrafanapass
  database: databasename
  access: proxy
  **readOnly: false
  editable: true**

**Comment by lazypower** [comment]
Lovely fix, it seems that these fields are missing from the schema of the provisioner

https://grafana.com/docs/grafana/latest/administration/provisioning/

**Comment by valentinbud** [comment]
Hello @ibanmarco,

I have tried your suggestion, adding `readOnly: false` and `editable: true` to the
datasources configuration but the delete button is still greyed out and the message 
`This datasource was added by config and cannot be modified using the UI. Please contact your server admin to update this datasource.` appears.

Grafana is deployed using the `kube-prometheus-stack` helm chart. Grafana version is `Grafana v7.5.5 (b5190ee547)`

The configmap with `datasources.yaml` is the following

```
apiVersion: v1
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://kube-prometheus-stack-prometheus:9090/
      access: proxy
      isDefault: true
      jsonData:
        timeInterval: 30s
    - access: proxy
      basicAuth: true
      basicAuthPassword: *****
      basicAuthUser: grafana
      editable: false
      jsonData:
        tlsSkipVerify: false
      name: prometheus-testing-cluster
      orgId: 1
      type: prometheus
      url: https://prometheus-ds.testing.123formbuilder.com
      version: 1
    - access: proxy
      basicAuth: true
      basicAuthPassword: ******
      basicAuthUser: grafana
      editable: true
      jsonData:
        tlsSkipVerify: false
      name: prometheus-testing
      orgId: 1
      readOnly: false
      type: prometheus
      url: https://prometheus-ds.testing.123formbuilder.com
      version: 1
    - access: proxy
      basicAuth: true
      basicAuthPassword: ******
      basicAuthUser: grafana
      editable: true
      jsonData:
        tlsSkipVerify: false
      name: Prometheus Testing
      orgId: 1
      readOnly: false
      type: prometheus
      url: https://prometheus-ds.testing.123formbuilder.com
      version: 1
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: kube-prometheus-stack
    meta.helm.sh/release-namespace: monitoring
  labels:
    app: kube-prometheus-stack-grafana
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 15.4.4
    chart: kube-prometheus-stack-15.4.4
    grafana_datasource: "1"
    heritage: Helm
    release: kube-prometheus-stack
  name: kube-prometheus-stack-grafana-datasource
  namespace: monitoring
```

I want to delete the `Prometheus Testing` and `prometheus-testing` datasources. Am I doing something wrong?

Thank you.

**Comment by valentinbud** [comment]
For anyone stumbling across this the answer lies in https://community.grafana.com/t/removing-provisioned-datasources/17096.

I have manually edited the configmap and added `deleteDatasources`. Afterwards the datasources disappeared from
Grafana. 

Thank you for such a wonderful tool.

**Comment by gtirloni** [comment]
For anyone confused about how this interacts with Helm charts, I've added a comment [here](https://github.com/grafana/helm-charts/issues/1125#issuecomment-1711367462) that hopefully clarifies this situation. This was the first issue I found while searching how to properly remove a datasource added through a config file (which was created by a Helm chart).

**Comment by younsl** [comment]
If you are using the kube-prometheus-stack chart, this is the solution I used.

---

## Overview

This is the procedure to delete a datasource in Grafana deployed with kube-prometheus-stack.

## Environment

- EKS v1.30
- kube-prometheus-stack `v58.2.2` (Chart version)
- Datsource to delete: Loki

```console
helm list -n monitoring
NAME                 	NAMESPACE 	REVISION	UPDATED                             	STATUS  	CHART                       APP VERSION
kube-prometheus-stack	monitoring	33      	2024-05-23 17:20:51.137351 +0900 KST	deployed	kube-prometheus-stack-58.2.2v0.73.2
```

## Deletion Procedure

The existing additionalDatasources configuration used in the grafana subchart of the `kube-prometheus-stack` is as follows:

```yaml
# kube-prometheus-stack/values.yaml
grafana:
  deleteDatasources: {}
  # - name: example-datasource
  #   orgId: 1

  additionalDataSources:
    - name: Loki
      uid: loki
      type: loki
      access: proxy
      basicAuth: false
      editable: false
      orgId: 1
      url: http://loki-distributed-gateway.loki
      version: 1
```

Add the datasource you want to delete to grafana.deleteDatasources.

In this scenario, we are going to delete the Loki provisioned datasource.

![image](https://github.com/user-attachments/assets/7b416893-d133-47fa-b239-94e918dea35a)

The result after applying the changes to the Helm chart is as follows:

```yaml
# kube-prometheus-stack/values.yaml
grafana:
  deleteDatasources:
    - name: Loki
      orgId: 1
  # - name: example-datasource
  #   orgId: 1

  ## Configure additional grafana datasources (passed through tpl)
  ## ref: http://docs.grafana.org/administration/provisioning/#datasources
  additionalDataSources: {}
    # - name: Loki
    #   uid: loki
    #   type: loki
    #   access: proxy
    #   basicAuth: false
    #   editable: true
    #   orgId: 1
    #   url: http://loki-distributed-gateway.loki
    #   version: 1
```

Apply the changes to Grafana using the `helm upgrade` command.

Verify that the Loki datasource has been deleted from the datasources data in the ConfigMap.

```yaml
$ kubectl get configmap -n monitoring kube-prometheus-stack-grafana-datasource -o yaml
...
data:
  datasource.yaml: |-
    apiVersion: 1
    deleteDatasources:
      - name: Loki
        orgId: 1
    datasources:
    - name: Prometheus
      type: prometheus
      uid: prometheus
      url: http://kube-prometheus-stack-prometheus.monitoring:9090/
      access: proxy
      isDefault: true
      jsonData:
        httpMethod: POST
        timeInterval: 30s
    - name: Alertmanager
      type: alertmanager
      uid: alertmanager
      url: http://kube-prometheus-stack-alertmanager.monitoring:9093/
      access: proxy
      jsonData:
        handleGrafanaManagedAlerts: false
        implementation: prometheus
```

When you access Grafana's web interface, you should see that the datasource has been deleted.

**Comment by younsl** [comment]
If you installed grafana using the kube-prometheus-stack chart, this solution will help you.

---

## Overview

This is the procedure to delete a datasource in Grafana deployed with [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack).

## Environment

- EKS v1.30
- kube-prometheus-stack `v58.2.2` (Chart version)
- Datsource to delete: Loki

```console
$ helm list -n monitoring
NAME                 	NAMESPACE 	REVISION	UPDATED                             	STATUS  	CHART                       APP VERSION
kube-prometheus-stack	monitoring	33      	2024-05-23 17:20:51.137351 +0900 KST	deployed	kube-prometheus-stack-58.2.2v0.73.2
```

## Deletion Procedure

The existing additionalDatasources configuration used in the grafana subchart of the `kube-prometheus-stack` is as follows:

```yaml
# kube-prometheus-stack/values.yaml
grafana:
  deleteDatasources: {}
  # - name: example-datasource
  #   orgId: 1

  additionalDataSources:
    - name: Loki
      uid: loki
      type: loki
      access: proxy
      basicAuth: false
      editable: false
      orgId: 1
      url: http://loki-distributed-gateway.loki
      version: 1
```

Add the datasource you want to delete to grafana.deleteDatasources.

In this scenario, we are going to delete the Loki provisioned datasource.

![image](https://github.com/user-attachments/assets/7b416893-d133-47fa-b239-94e918dea35a)

The result after applying the changes to the Helm chart is as follows:

```yaml
# kube-prometheus-stack/values.yaml
grafana:
  deleteDatasources:
    - name: Loki
      orgId: 1
  # - name: example-datasource
  #   orgId: 1

  ## Configure additional grafana datasources (passed through tpl)
  ## ref: http://docs.grafana.org/administration/provisioning/#datasources
  additionalDataSources: {}
    # - name: Loki
    #   uid: loki
    #   type: loki
    #   access: proxy
    #   basicAuth: false
    #   editable: false
    #   orgId: 1
    #   url: http://loki-distributed-gateway.loki
    #   version: 1
```

Apply the changes to Grafana using the `helm upgrade` command.

Verify that the Loki datasource has been deleted from the datasources data in the ConfigMap.

> [!WARNING]
> The name and namespace of the `configMap` resource may vary depending on each cluster environment.

```yaml
$ kubectl get configmap -n monitoring kube-prometheus-stack-grafana-datasource -o yaml
...
data:
  datasource.yaml: |-
    apiVersion: 1
    deleteDatasources:
      - name: Loki
        orgId: 1
    datasources:
    - name: Prometheus
      type: prometheus
      uid: prometheus
      url: http://kube-prometheus-stack-prometheus.monitoring:9090/
      access: proxy
      isDefault: true
      jsonData:
        httpMethod: POST
        timeInterval: 30s
    - name: Alertmanager
      type: alertmanager
      uid: alertmanager
      url: http://kube-prometheus-stack-alertmanager.monitoring:9093/
      access: proxy
      jsonData:
        handleGrafanaManagedAlerts: false
        implementation: prometheus
```

When you access Grafana's web interface, you should see that the datasource has been deleted.

## Reference

[Removing provisioned datasources](https://community.grafana.com/t/removing-provisioned-datasources/17096)
