### ISSUE TITLE
Error 'e.text is undefined' on Firefox when testing data source

### ISSUE THREAD

**Issue by xelite** [grafana/grafana#18891]
**What happened**:

Error 'e.text is undefined' when testing provisioned data source on Firefox broweser. When using eg. Vivaldi everything is fine.

**What you expected to happen**:
Tested and added data source .

**How to reproduce it (as minimally and precisely as possible)**:

```
apiVersion: 1

deleteDatasource:
  - name: 'influx-telegraf@chuj'
    orgId: 20

datasources:
  - name: 'influx-telegraf@chuj'
    orgId: 20
    type: influxdb
    access: proxy
    url: 'http://172.7.5.11:8086'
    database: 'telegraf'
    user: grafana_user
    password: Nie-powiem
    basicAuth: false
    version: 1
    editable: true
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.3.25
- Data source type & version: Influxdb
- OS Grafana is installed on: Debian 9
- User OS & Browser: Firefox 69.0b4
- Grafana plugins: -
- Others: -
