### ISSUE TITLE
Provisioning PostgreSQL datasource validation failed

### ISSUE THREAD

**Issue by cdalexndr** [grafana/grafana#18904]
Using grafana docker image `grafana/grafana:latest` (Grafana v6.3.3) with the following `datasource.yaml`:
```
datasources:
  - name: PostgreSQL
    type: postgres
    url: db:5432
    user: postgres
    secureJsonData:
      password: "postgres"
    jsonData:
      sslmode: "disable"
      postgresVersion: 1000 #10.00
    database: postgres
    version: 1
    editable: true
```
After starting grafana, the datasource is created, but when I try to test it by pressing "Save & Test" button, a pop-up appears in top right corner saying "Validation failed". Changing any of the values, including setting an invalid host results in the same message.

If I create a new datasource with the same configuration, everything works correctly.
