### ISSUE TITLE
Alert rule results to state alerting due to "Could not find datasource Data source not found"

### ISSUE THREAD

**Issue by xnike** [grafana/grafana#19163]
**What happened**:

Using auto provisioning of data sources and dashboards via `conf/provisioning` directory with data source template like this (forcing recreation by deleteDatasources)

```
# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: ${dataSourceName}
    orgId: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
  # <string, required> name of the datasource. Required
  - name: ${dataSourceName}
...
```

could result after Grafana restart to correctly changed data source ids and correctly shown metrics on dashboards, but **at the same time** broken alerts

```
=2019-09-17T12:45:45+0300 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=10 name="SMP Availability alert" error="Could not find datasource Data source not found" changing state to=alerting
```

due to hard coded datasourceId into settings column of alert DB table.

```
{
  "conditions": [
    {
      "evaluator": {
        "params": [
          1
        ],
        "type": "lt"
      },
      "operator": {
        "type": "or"
      },
      "query": {
        "datasourceId": 1,
...
}
```

**What you expected to happen**:

The same behavior for metrics graphs and alerts: using data source name not id.

**Environment**:
- Grafana version: 6.3.5
