### ISSUE TITLE
Cloudwatch datasource with arn authentication not working properly

### ISSUE THREAD

**Issue by giom-l** [grafana/grafana#19173]
**What happened**:
I configured a datasource that I give to Grafana at startup.
```datasources:
  - name: Cloudwatch
    type: cloudwatch
    isDefault: true
    jsonData:
      authType: arn
      assumeRoleArn: arn:aws:iam::<account>:role/<rolename>
      defaultRegion: eu-west-1
```
My instance has assumeRole properly set up.
To be sure, I get this role arn with the following during startup of the instance (user_data) : 
```
# get instance Role ARN 
role_name=$(curl http://169.254.169.254/latest/meta-data/iam/security-credentials)
role_arn=$(aws iam get-role --role-name=$role_name | jq .Role.Arn -r)

# sed delimiters are deliberately changed to "#" as the role arn value contains "/"
sed \
    -e "s#<role_arn>#$role_arn#g" \
    /etc/grafana/provisioning/datasources/datasources.yml.src > /etc/grafana/provisioning/datasources/datasources.yml
```
The result is as expected like the conf given above.

When I go to the configuration page : 
- Auth provider and Default region are filled correctly
- ARN is not filled with the value I provided (it is empty)

Test the datasource end up with 
![image](https://user-images.githubusercontent.com/29728596/58717360-5938b880-83cb-11e9-986b-c7a274611932.png)

This issue seems to have been referenced [here](https://github.com/grafana/grafana/issues/16725) but closed with a workaround only (yes, with credentials instead of arn, it works, but that is not the point)

**What you expected to happen**:
When Grafana is started, ARN should be filled with the value provided and testing datasource should be OK

**How to reproduce it (as minimally and precisely as possible)**:
You should have a Grafana set up on AWS, with correct permissions to Cloudwatch (as stated [here] (
(https://grafana.com/docs/features/datasources/cloudwatch/)

**Anything else we need to know?**:
Reopening of issue https://github.com/grafana/grafana/issues/17396
Identified workaround : 
```
Figured out a workaround when saving through the UI
    Set actual role (not assume role) on UI and save, and same on ec2
    Switch the "Auth Provider" in UI to Credentials file (leave value blank)
    Save and Enjoy!

```
But it only works when the datasource has been created through the UI ! 

**Environment**:
- Grafana version: Grafana v6.2.1 (commit: 9e40b07)
- Data source type & version: Cloudwatch
- OS Grafana is installed on: AWS amazon ami
- User OS & Browser: Ubuntu, both Chrome/Firefox
- Grafana plugins: None
- Others:

**Comment by gbmelki** [comment]
I am facing this same issue as well, any updates on this?

**Comment by alexjkay** [comment]
Also having the same issue as above.

**Comment by devdavidkarlsson** [comment]
Works on my machine:

```
cat >>  /etc/grafana/provisioning/datasources/initial_config.yaml <<-'EOM'
apiVersion: 1
datasources:
  - name: dev-cw
    type: 'cloudwatch'
    access: 'proxy'
    editable: true
    jsonData:
      authType: 'arn'
      assumeRoleArn: '${grafana_read_role_arn_dev}'
      defaultRegion: 'us-east-1'
  - name: prod-cw
    type: 'cloudwatch'
    access: 'proxy'
    editable: true
    jsonData:
      authType: 'arn'
      assumeRoleArn: '${grafana_read_role_arn_prod}'
      defaultRegion: 'us-east-1'
EOM
```
