### ISSUE TITLE
jsonData and secureJsonData are ignored when provisioning Elasticsearch datasource from file

### ISSUE THREAD

**Issue by treksler** [grafana/grafana#19684]
**What happened**: when provisioning elasticsearch datasearch from a file, jsonData and secure JsonData keys are ignored. As a result, provisioning BasicAuth and TLS auth settings is impossible. (Use ODFE with security enabled to test) Settings need to be edited in browser, and are periodically lost and have to be re-entered in the browser

**What you expected to happen**:
settings form jsonData and secure JsonData would be applied

**How to reproduce it (as minimally and precisely as possible)**:
Using sample config https://grafana.com/docs/features/datasources/elasticsearch/#configure-the-datasource-with-provisioning es version is not set to 7 as expected.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.4.1
- Data source type & version: elasticsearch
- OS Grafana is installed on: Docker
- User OS & Browser: Mac OS, Chrome and Safari
- Grafana plugins: none
- Others:

**Comment by treksler** [comment]
looks like you have to specify apiversion, or it will ignore jsonfile

this appears to not work
```
datasources:
  - name: elasticsearch-v7-filebeat
    type: elasticsearch
    access: proxy
    database: "[filebeat-]YYYY.MM.DD"
    url: http://localhost:9200
    jsonData:
      interval: Daily
      timeField: "@timestamp"
      esVersion: 70
      logMessageField: message
      logLevelField: fields.level
```


```
apiVersion: 1

datasources:
  - name: elasticsearch-v7-filebeat
    type: elasticsearch
    access: proxy
    database: "[filebeat-]YYYY.MM.DD"
    url: http://localhost:9200
    jsonData:
      interval: Daily
      timeField: "@timestamp"
      esVersion: 70
      logMessageField: message
      logLevelField: fields.level
```
