### ISSUE TITLE
Provisioning: Support integer env variables in yaml files 

### ISSUE THREAD

**Issue by darkleaf** [grafana/grafana#20347]
**What happened**:
I can't set up **integer (not string)** values in my datasource via environment variables. 

**What you expected to happen**:

It is possible to set up integer values via environment variables.

**How to reproduce it (as minimally and precisely as possible)**:

```
# provisioning/datasources/postgres.yaml
apiVersion: 1

deleteDatasources:
- name: PostgreSQL

datasources:
- name: PostgreSQL
  type: postgres
  # ...
  jsonData:
    maxOpenConns: $GRAFANA_DATASOURCE_MAX_OPEN_CONNS
    maxIdleConns: $GRAFANA_DATASOURCE_MAX_IDLE_CONNS
    connMaxLifetime: $GRAFANA_DATASOURCE_CONN_MAX_LIFETIME
```

```
# app.env
GRAFANA_DATASOURCE_MAX_OPEN_CONNS=4
GRAFANA_DATASOURCE_MAX_IDLE_CONNS=2
GRAFANA_DATASOURCE_CONN_MAX_LIFETIME=14400
```

**Anything else we need to know?**:

String values are set up correctly.

**Environment**:
- Grafana version: 6.4.4
- Data source type & version: postgres 11
- OS Grafana is installed on: docker image
- User OS & Browser: -
- Grafana plugins: grafana-piechart-panel, michaeldmoore-multistat-panel, natel-plotly-panel
- Others:

**Comment by magaton** [comment]
I am not able to set up datasource urls using env vars.
```
MacBook-Pro-2:grafana agaton$ brew services stop grafana
Stopping `grafana`... (might take a while)
==> Successfully stopped `grafana` (label: homebrew.mxcl.grafana)
MacBook-Pro-2:grafana agaton$ rm -rf grafana.db png/
MacBook-Pro-2:grafana agaton$ export DS_ELASTICSEARCH=http://localhost:9200
MacBook-Pro-2:grafana agaton$ echo $DS_ELASTICSEARCH
http://localhost:9200
MacBook-Pro-2:grafana agaton$ brew services start grafana
==> Successfully started `grafana` (label: homebrew.mxcl.grafana)
```    

My datasource.yml:
```
datasources:
  - id: 1
    orgId: 1
    name: "documents"
    type: "elasticsearch"
    typeLogoUrl: "public/app/plugins/datasource/elasticsearch/img/elasticsearch.svg"
    access: "proxy"
    url: $DS_ELASTICSEARCH
    password: ""
    user: ""
    database: "documents"
    basicAuth: false
    isDefault: true
    jsonData:
      esVersion: 60
      keepCookies: []
      maxConcurrentShardRequests: 256
      timeField: "timestamp"
    readOnly: false
    editable: true
```

When I start grafana I see that url in datasource is empty (not substituted).


```

**Comment by darkleaf** [comment]
@magaton, you start grafana via `brew services start grafana`. May be brew don't respect local environment.
Although my question is about integer rather then string values in environment.

**Comment by magaton** [comment]
Thanks @darkleaf 
This was indeed the case.  One needs to set env var HOMEBREW_ENV_FILTERING=1 in order to instruct Homebrew to accept ENV vars. This is working now, but it seems there is no way to specify fallback defaults like:
```
- id: 1
    orgId: 1
    name: "documents"
    type: "elasticsearch"
    typeLogoUrl: "public/app/plugins/datasource/elasticsearch/img/elasticsearch.svg"
    access: "proxy"
    url: ${DS_ELASTICSEARCH:"http://localhost:9092"}
```
in case DS_ELASTICSEARCH env var is not set.

**Comment by dpajin** [comment]
Hi @darkleaf, @magaton, 

I have the similar problem that my env variables are not substituted, but I am using Ubuntu 18.04 as host OS and Grafana Version 6.6.1 (21bf8b71bc). 
I am trying to supply datasource username and password. 

According to github issue https://github.com/grafana/grafana/pull/16499 1 this should be supported.

Here is the output in the container.
```
bash-5.0$ more /etc/grafana/provisioning/datasources/datasources.yaml
datasources:

# JTI raw databases
- name: juniper_1
  type: influxdb
  access: proxy
  orgId: 1
  url: http://db_1:8086
  password: $INFLUXDB_PASS
  user: $INFLUXDB_USER
  database: juniper
  basicAuth: false
  isDefault: false
  editable: false

bash-5.0$ env | grep INFLUX 
INFLUXDB_USER=test
INFLUXDB_PASS=test
```
In Grafana Web UI I see datasource is created and the username is set to "$INFLUXDB_USER" and password is blank.
If I further go to the dashboard page, it tries to load data from the database for each panel, and then it prompts me to enter username and password with the following description:

> The server is asking for your username and password. The server reports that it is from InfluxDB.

Any ideas how to try to resolve this?

**Comment by Zipfer** [comment]
```  access: 'direct'
  database: 'metrics'
  user: $INFLUX_USER```
```bash-5.0$ env |grep INFLUX
INFLUX_USER=test```
<img width="478" alt="image" src="https://user-images.githubusercontent.com/1160859/82077441-4bd81500-9694-11ea-9b89-e58019a18931.png">

**Comment by jackielii** [comment]
Got similar problem setting up a Clickhouse datasource via provisioning:

```
  - name: Clickhouse
    # <string, required> Sets the data source type.
    type: grafana-clickhouse-datasource
    access: proxy
    uid: clickhouse-local
    jsonData:
      username: $CLICKHOUSE_USERNAME
      server: $CLICKHOUSE_SERVER
      port: $CLICKHOUSE_PORT
    secureJsonData:
      password: $CLICKHOUSE_PASSWORD
```

And my env is set:
```
CLICKHOUSE_PORT=9000
CLICKHOUSE_USERNAME=default
CLICKHOUSE_PASSWORD=
CLICKHOUSE_SERVER=host.docker.internal
```

However when I test the datasource it says:
```
json: cannot unmarshal string into Go struct field Settings.port of type int64: could not parse json
```
