### ISSUE TITLE
Exploring Loki - incosistent results

### ISSUE THREAD

**Issue by shaikatz** [grafana/grafana#20511]
**What happened**:
When searching Loki logs in the explore window, adjusting the time window results in different results for the same time frames.

**What you expected to happen**:
Specific time should always return the same rows despite the time window. 

**How to reproduce it (as minimally and precisely as possible)**:
* Create a new deployment that write logs once an hour.
* Open the explore window and put your time window around the log time +- 10 minutes.
You'll see X number of logs at the time the deployment wrote the logs.

* Click few times on the zoom out button.
You'll see X+- number of logs at the same time above.

**Environment**:
- Grafana version: 6.5.1-beta / 6.3.3
- Data source type & version: Loki 0.4.0
- OS Grafana is installed on: Linux
- User OS & Browser: MAC & Chrome
- Grafana plugins: None

**Comment by hugohaggmark** [comment]
Thanks for reporting this @shaikatz

**Comment by pstibrany** [comment]
I cannot reproduce this problem. Here is what I did:

- Started Loki: `docker run -d -p 3100:3100 --name=loki grafana/loki:v1.0.0`
- Started Grafana: `docker run -d -p 3001:3000 --name=grafana-beta grafana/grafana:6.5.0-beta1`
- Used promtail with this config file:

```
clients:
  - url: http://localhost:3100/loki/api/v1/push

positions:
  filename: /tmp/20511-positions.yml

scrape_configs:
  - job_name: testing

    static_configs:
      - targets:
          - localhost

        labels:
          __path__: /tmp/random.log

    pipeline_stages:
      - json:
          expressions:
            message:
            timestamp:

      - timestamp:
          source: timestamp
          format: 2006-01-02T15:04:05.000000Z

      - output:
          source: message
```

Here is my Log file ("/tmp/random.log" from promtail config):

```{ "timestamp": "2019-11-21T02:15:00.123456Z", "message": "DEBUG message"}
{ "timestamp": "2019-11-21T03:15:00.123456Z", "message": "WARNING message"}
{ "timestamp": "2019-11-21T04:15:00.123456Z", "message": "ERROR message"}```

Each line is one hour after the first one. After adding Loki to Grafana, I can see all three log lines. When I set time window to 'now-4h –– now-3h', I see only latest line. When I zoom out, I get another one, and after another zoom out, yet another line.

<img width="1586" alt="Screenshot 2019-11-21 at 08 33 22" src="https://user-images.githubusercontent.com/895919/69316792-df76de80-0c39-11ea-85c7-67fed7ff22d6.png">

<img width="1586" alt="Screenshot 2019-11-21 at 08 33 30" src="https://user-images.githubusercontent.com/895919/69316837-f0275480-0c39-11ea-9877-0d86274ae652.png">

<img width="1586" alt="Screenshot 2019-11-21 at 08 33 34" src="https://user-images.githubusercontent.com/895919/69316857-f6b5cc00-0c39-11ea-80a1-bd2a8b398812.png">

@shaikatz can you please share your log files (if possible), details about how you run Loki (config), and screenshots to highlight the problem? Thanks!
