### ISSUE TITLE
Add Max concurrent Shard Requests to Elasticsearch Datasource provisioning

### ISSUE THREAD

**Issue by DrMxxxxx** [grafana/grafana#20554]
**What would you like to be added**:
For provisioning Elasticsearch Datasources it should be possible to configure the parameter "Max concurrent Shard Requests" in the Datasource configuration file.

**Why is this needed**:
It should be possible to overwrite the default Max concurrent Shard Requests of 5 with a custom value. I can configure it on the Website manually, but it would be a nice add to have this done via the provisioning.

**Comment by marefr** [comment]
That should already be supported. Please show your config file and what you've tried.

**Comment by DrMxxxxx** [comment]
Hi, 
thanks for the fast answer. 

When I look at the Website (https://grafana.com/docs/administration/provisioning/) I cannot see, where I have to put the value for this "Max shard ...."

So my config looks like this:
```
- name: THENAME
  type: elasticsearch
  access: proxy
  orgId: 1
  url: http://elasticsearch1:9200
  user:
  database: "indices*"
  basicAuth: true
  basicAuthUser: "theuser"
  withCredentials: false
  isDefault: false
  jsonData:
    esVersion: 70
    timeField: "@timestamp"
    interval: ""
  secureJsonData:
    tlsCACert: "..."
    tlsClientCert: "..."
    tlsClientKey: "..."    
    password:
    basicAuthPassword: "supersecurepassword"
  version: 1
  editable: true
```

Just to be sure we are talking about the same. I mean this value:
![image](https://user-images.githubusercontent.com/41616347/69335144-8c625300-0c5c-11ea-81f2-977a83981ffe.png)

Thanks!
