### ISSUE TITLE
Grafana fails to start when having a basic auth password with more than 255 characters

### ISSUE THREAD

**Issue by rndmh3ro** [grafana/grafana#20639]
**What happened**:
Grafana is provisioned in an Openshift cluster with the following Prometheus datasource:
```
    prometheus.yaml: |-
      apiVersion: 1
      datasources:
      - name: Infrastructure-Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        basicAuth: true
        basicAuthPassword: ${INFRA_PROM_HTPASS_PW}
        basicAuthUser: internal
        url: https://prometheus-k8s.openshift-monitoring.svc:9091
        jsonData:
          tlsSkipVerify: true
        isDefault: false
        version: 2
        editable: true
```
Grafana fails to start when having a basic auth password (`INFRA_PROM_HTPASS_PW`) with more than 255 characters:
```
t=2019-11-25T15:08:10+0000 lvl=eror msg="Server shutdown" logger=server reason="Service init failed: Datasource provisioning error: pq: value too long for type character varying(255)"
```

However when entering the long password in the GUI it is successfully saved and working.

**What you expected to happen**:

Grafana starts with the long password

**How to reproduce it (as minimally and precisely as possible)**:

Provision grafana with the aforementioned prometheus datasource.

**Environment**:
- Grafana version:  Grafana v5.2.1 (2040f61) 
- Data source type & version: Prometheus
- OS Grafana is installed on: CentOS
