### ISSUE TITLE
Docker-Compose with Grafana stops when Postgres has not finished starting

### ISSUE THREAD

**Issue by Ydiren** [grafana/grafana#20743]
We're hitting the same issue as reported in the following issue:
[https://github.com/grafana/grafana-docker/issues/92](https://github.com/grafana/grafana-docker/issues/92)

This was closed stating that some improvement could be made to the resilience of Grafana. 

The work around listed in the other issue works, but it goes against the solution recommended by the Docker docs:
 [https://docs.docker.com/compose/startup-order/](https://docs.docker.com/compose/startup-order/)

Unfortunately due to the repository now being archived we're no longer able to add follow up comments to this issue, so I'm raising this to find out if this startup dependency issue has been addressed?

Versions:
We're not pinning any particular versions so are using latest, which at the time of writing are:

Postgres: [https://hub.docker.com/layers/postgres/library/postgres/latest/images/sha256-4b08dd6db8813fd2ee7f15ced1b72f52b8a8726cbeb91e4ff3285332539e257d](https://hub.docker.com/layers/postgres/library/postgres/latest/images/sha256-4b08dd6db8813fd2ee7f15ced1b72f52b8a8726cbeb91e4ff3285332539e257d)

Grafana: [https://hub.docker.com/layers/grafana/grafana/latest/images/sha256-98352c51c952d749e74899302eaffea749423ee379548a4d3fb829a74291783d](https://hub.docker.com/layers/grafana/grafana/latest/images/sha256-98352c51c952d749e74899302eaffea749423ee379548a4d3fb829a74291783d)

**Comment by xlson** [comment]
This issue is still unresolved. Thanks for (re-)reporting it, this is something we should fix and I will bring it up for discussion internally. Historically, we have made it so that any failure during startup will make Grafana fail completely, but I think this is an incorrect behaviour for "ephemeral" problems like access to the Database.

**Comment by paulspencerwilliams** [comment]
@xlson cheers for the response. Do you have any workarounds in the meantime?

**Comment by papagian** [comment]
@paulspencerwilliams 
As a workaround if you are using docker-compose >= 2.1 you can use the `healthcheck` and `depends_on` instructions.

For example:
```
version: "2.1"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DATABASE: grafana
      POSTGRES_USER: grafana
      POSTGRES_PASSWORD: password
    ports:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d grafana -U grafana"]
      timeout: 10s
      retries: 10

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=db:5432
      - GF_DATABASE_USER=grafana
      - GF_DATABASE_PASSWORD=password
      - GF_DATABASE_SSL_MODE=disable
    ports:
      - 3000
    depends_on:
      db:
        condition: service_healthy
```
