### ISSUE TITLE
can't import dashboard

### ISSUE THREAD

**Issue by Hokwang** [grafana/grafana#21159]
Hello.

I am behind the corporate proxy env.
I installed grafana using helm chart on the kubernetes.

My values.yaml file is below.
```
image:
  tag: 6.5.2

testFramework:
  enabled: false

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  path: /grafana-dev
  hosts:
    - <my address>
  tls:
    - secretName: ingress-tls
      hosts:
        - <my address>

persistence:
  enabled: false

env:
  http_proxy: "http://<proxyhost>:<proxyport>"
  https_proxy: "http://<proxyhost>:<proxyport>"
  no_proxy: "localhost,127.0.0.1,<my address>"

plugins:
  - grafana-piechart-panel

grafana.ini:
  server:
    domain: <my address>
    root_url: https://<my address>/grafana-dev/
    serve_from_sub_path: true
  analytics:
    reporting_enabled: false
```

After login, move import dashboard page
and click input area.
the error shows 
` {"data":"","status":502,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"api/gnet/dashboards/undefined","retry":0,"headers":{"X-Grafana-Org-Id":1,"Accept":"application/json, text/plain, */*"}},"statusText":"","xhrStatus":"complete","isHandled":true}`

I don't know why this url is starting from api without grafana.com

log shows'
```
2019/12/18 06:00:18 http: proxy error: x509: certificate signed by unknown authority
t=2019-12-18T06:00:18+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=grafanaadmin method=GET path=/api/gnet/dashboards/undefined status=502 remote_addr=127.0.0.1 time_ms=375 size=0 referer=https://nwse.sec.samsung.net/grafana-dev/dashboard/import
```

Also I don't know why remote_addr=127.0.0.1 not grafana.com

**What happened**:
I can't import dashboard.

I think I need proxy config like http_proxy or add cert file.
but already proxy config is exist and in case of cert file, I don't know
grafana use which command and where's the location of cert file.

**Environment**:
- Grafana version: 6.5.2
- Data source type & version: -
- OS Grafana is installed on: container
- User OS & Browser: Windows 10 & Chrome
- Grafana plugins: -
- Others: -

Thanks,
