### ISSUE TITLE
Datasource provisioning uses "Browser" as default access mode when not specified

### ISSUE THREAD

**Issue by qlyoung** [grafana/grafana#21398]
**What happened**:

Provisioned an InfluxDB datasource and neglected to specify the `access:` field in the `.yaml` file. Datasource access mode behavior defaulted to the equivalent of the web UI's `Browser`.

**What you expected to happen**:

I expect an omitted `access` field to default to `proxy` (named `Server` in the web interface), which is the default when configuring a new datasource from the web interface.

**How to reproduce it (as minimally and precisely as possible)**:

Use the following config to configure a datasource:
```
apiVersion: 1    
    
datasources:    
- name: InfluxDB    
  type: influxdb    
  isDefault: true    
  database: mydb    
  url: http://bepis:8086    
  jsonData:    
    httpMode: GET
```
Note the missing `access` field. Start Grafana, navigate to this provisioned InfluxDB datasource in the web UI, and observe that the dropdown says `Server`. Open your network requests debugger in your browser devtools, then click "Test datasource". Observe a request from the browser to `http://bepis:8086`. If the `Server` access method were actually in effect, this request should have been proxied to the Grafana server.

**Anything else we need to know?**:

Love your product!

**Environment**:

- Grafana version: 5.0
- Data source type & version: InfluxDB
- OS Grafana is installed on: Official Grafana Docker image
- User OS & Browser: Firefox 71.0, Ubuntu 18.04
- Grafana plugins: None
