### ISSUE TITLE
"Server Error" when adding InfluxDB as a datasource

### ISSUE THREAD

**Issue by ttys42** [grafana/grafana#21611]
**What happened**:
After fresh install it is not possible to add an InfluxDB source

**What you expected to happen**:
InfluxDB can be added as data source

**How to reproduce it (as minimally and precisely as possible)**:
-Clean install CentOS 8
-add influx repo as described here https://docs.influxdata.com/influxdb/v1.7/introduction/installation/#installing-influxdb-oss
-install & start influxdb
-add grafana repo as described here https://grafana.com/docs/grafana/latest/installation/rpm/#install-from-yum-repository
-install & start grafana
-add influxdb as a data source
-Now there is an "InfluxDB Error: Server Error" in Grafana
-This is in the grafana log
`t=2020-01-20T11:35:02+0100 lvl=eror msg="Request error" logger=context userId=1 orgId=1 uname=admin error="runtime error: invalid memory address or nil pointer dereference" stack="/usr/local/go/src/runtime/panic.go:199 (0x4502db)\n/usr/local/go/src/runtime/signal_unix.go:394 (0x450118)\n/go/src/github.com/grafana/grafana/pkg/api/pluginproxy/ds_proxy.go:216 (0xf9470d)\n/go/src/github.com/grafana/grafana/pkg/api/pluginproxy/ds_proxy.go:68 (0xf93a12)\n/go/src/github.com/grafana/grafana/pkg/api/dataproxy.go:35 (0x12ff338)\n/usr/local/go/src/reflect/value.go:460 (0x49b5f5)\n/usr/local/go/src/reflect/value.go:321 (0x49adb3)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x82a9d9)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x82a389)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x82b978)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0xc5efd5)\n/go/src/github.com/grafana/grafana/pkg/middleware/request_tracing.go:25 (0xc5efc8)\n/usr/local/go/src/reflect/value.go:460 (0x49b5f5)\n/usr/local/go/src/reflect/value.go:321 (0x49adb3)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x82a9d9)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x82a389)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x82b978)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0xc5e7cc)\n/go/src/github.com/grafana/grafana/pkg/middleware/request_metrics.go:17 (0xc5e7b7)\n/usr/local/go/src/reflect/value.go:460 (0x49b5f5)\n/usr/local/go/src/reflect/value.go:321 (0x49adb3)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x82a9d9)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x82a389)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x82b978)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0xc5e6df)\n/go/src/github.com/grafana/grafana/pkg/middleware/recovery.go:147 (0xc5e6cd)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:79 (0x82b820)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:157 (0x82a6e9)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:135 (0x82a478)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x82b978)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0xc5bf2b)\n/go/src/github.com/grafana/grafana/pkg/middleware/logger.go:34 (0xc5bf16)\n/usr/local/go/src/reflect/value.go:460 (0x49b5f5)\n/usr/local/go/src/reflect/value.go:321 (0x49adb3)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x82a9d9)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x82a389)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x82b978)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:187 (0x83cad6)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:303 (0x8373a5)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/macaron.go:220 (0x83086a)\n/usr/local/go/src/net/http/server.go:2802 (0x70a533)\n/usr/local/go/src/net/http/server.go:1890 (0x705ed4)\n/usr/local/go/src/runtime/asm_amd64.s:1357 (0x46a9f0)\n"
`

**Environment**:
- Grafana version: 6.5.3
- Data source type & version: influxdb 1.7.9
- OS Grafana is installed on: CentOS 8

**Comment by 5aint2ero** [comment]
I have the same Problem

**Comment by laundmo** [comment]
same problem here! im using docker with this docker-compose config:
```
version: "3"
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    volumes:
      - /srv/docker/influxdb/data:/var/lib/influxdb
      - /srv/docker/influxdb/config/:/etc/influxdb/
    ports:
      - "127.0.0.1:8086:8086"
      - "127.0.0.1:8082:8082"
      - "127.0.0.1:8089:8089/udp"
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=
    command:
      - influxd
    restart: always
    
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "10.0.0.2:3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource
    volumes:
      - /srv/docker/grafana/data:/var/lib/grafana
    network_mode: "host"
    restart: always
```
