### ISSUE TITLE
Use same directory structure in grafana dashboard folders as in provisioning path

### ISSUE THREAD

**Issue by arnedc** [grafana/grafana#21909]
**What would you like to be added**: When I provision dashboards for a path where the dashboards are organized under a directory structure, I would love to see that same structure in the Grafana UI.
Example:
dashboards.yml (under `/etc/grafana/provisioning/dashboards`)
```
apiVersion: 1
providers:
 - name: 'ActiveScale components dashboards'
   orgId: 1
   folder: 'ActiveScale Components'
   type: file
   disableDeletion: false
   editable: true
   allowUiUpdates: false
   options:
     path: "/var/lib/grafana/dashboards/"
```
With the following structure under `/var/lib/grafana/dashboards`
```
$ tree /var/lib/grafana/dashboards
/var/lib/grafana/dashboards
└── Components
    ├── component1.json
    ├── component2.json
└── General
    ├── alerts.json
    ├── system.json
```
, we should be able to see in the Grafana UI, two folders (General & Components), under which the appropriate dashboards are listed 

**Why is this needed**: It makes provisioning a lot easier for set-ups with a lot of dashboards that need some structure. Now we have to create a separate provision yaml for each directory.
