### ISSUE TITLE
Explore: "Add data source" should use root_url

### ISSUE THREAD

**Issue by stalks** [grafana/grafana#22027]
**What happened**:
Setup grafana in docker behind nginx reverse proxy.
Click Explore >> Add data source redirects me to /datasources/new, resulting in 404

**What you expected to happen**:
Should redirect to /grafana/datasources/new

**Environment**:
- Grafana version: 6.6.1 (docker/alpine)
- Data source type & version: mysql, mariadb 10.4
- OS Grafana is installed on: alpine docker in a debian10 docker host
- User OS & Browser: Win10 Chrome
- Grafana plugins: alexanderzobnin-zabbix-app
- Configs

*nginx.conf:*
```
location /grafana/ {
        proxy_pass  http://grafana:3000/;
    }
```
*grafana.ini:*
```
root_url = %(protocol)s://%(domain)s/grafana/
```
*docker-compose.yml:*
```yaml
version: '3.1'

services:
    grafana:
        image: grafana/grafana:6.6.1
        container_name: grafana
        volumes:
            - etc:/etc/grafana
        environment:
            - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
        networks:
            - net
            - proxy
    sql:
        image: mariadb:10.4
        container_name: grafana-sql
        environment:
            - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/root-dbpasswd
            - MYSQL_DATABASE=grafana
            - MYSQL_USER=grafana
            - MYSQL_PASSWORD_FILE=/run/secrets/grafana-dbpasswd
        volumes:
            - sql:/var/lib/mysql
        networks:
            - net
            - pma
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-u", "healthcheck"]
            timeout: 20s
            retries: 10
        secrets:
            - root-dbpasswd
            - grafana-dbpasswd

secrets:
    root-dbpasswd:
        file: ./secrets/root-dbpasswd.secret
    grafana-dbpasswd:
        file: ./secrets/grafana-dbpasswd.secret


volumes:
    etc:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /data/docker/volumes/grafana-etc
    sql:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /data/docker/volumes/grafana-sql

networks:
    net:
        driver: bridge
    proxy:
        external:
            name: shared-proxy
    pma:
        external:
            name: shared-pma
```
