### ISSUE TITLE
Alerts sent to all notification channels and to specified uid

### ISSUE THREAD

**Issue by VMabille** [grafana/grafana#22312]
**What happened**:
I have multiple notification channels defined in an alerts.yaml file., present along with my dashboard in a provisioning folder. Each notification channel has a dedicated uid.
In my dashboards json files, I am using these uid to select the mailing list to send the alerts to. 
However for each alert defined, the notification list consist of all the notification channels defined in my alerts.yaml file. 

Examples below of my alert.yaml code, my alert definition in a dashboard json file and what I see in the alert panel.

**What you expected to happen**:
Notification list for the alert only consists of the channels defined by their uid. 

**How to reproduce it (as minimally and precisely as possible)**:
Inside a provisioning/ folder: 
- alerts.yaml with 2 notifiers, with different uids
- an alert defined in a dashboard.json panel. using one of these uid in the "notifications" list.
After starting the server, verify in the alert panel the notification list for this alert.

**Anything else we need to know?**:

**Environment**:
- Grafana version:  6.6.0 (5c11bbdfb4)  
- Data source type & version: prometheus
- OS Grafana is installed on: Ubuntu 18.04.3 LTS
- User OS & Browser:  Windows 10 / Google Chrome
- Grafana plugins:  Default plugins

alert.yaml: 
```
notifiers:
    - name: alerts_channel_1
      type: email
      uid: alerts_1
      org_id: 1
      is_default: true
      send_reminder: false
      frequency: 30m
      disable_resolve_message: false
      settings:
        addresses: "mail1@gmail.com"
    - name: alerts_channel_2
      type: email
      uid: alerts_2
      org_id: 1
      is_default: true
      send_reminder: false
      frequency: 30m
      disable_resolve_message: false
      settings:
        addresses: "mail2@gmail.com"
```

alert in dashboard.json:
```
"alert": {
               ...
                "name": "Alert 1",
                "notifications": [
                  {
                    "uid": "alerts_1"
                  }
                ]
            },
```

Alert as seen on GUI attached.
![alert](https://user-images.githubusercontent.com/22357981/74841194-8e55b400-5328-11ea-9f74-446e13793e89.png)
