### ISSUE TITLE
Git dashboard provider

### ISSUE THREAD

**Issue by Hipska** [grafana/grafana#22397]
**What would you like to be added**:

A new dashboard provider type that pulls git repositories

```yaml
providers:
  # <string> an unique provider name
- name: 'a unique provider name'
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string, required> name of the dashboard folder. Required
  folder: ''
  # <string> folder UID. will be automatically generated if not specified
  folderUid: ''
  # <string, required> provider type. Required
  type: git
  options:
    # <string, required> address of the git repository. Required
   repo: 'https://foosball.example.org/path/to/repo.git'
   # <string> tag or branch name, defaults to 'HEAD'
   version: develop
   # <string> path to use if dashboards are not in main directory
   path: dashboards/output
```

**Why is this needed**:

To be able to manage dashboards easier into a repository.
