### ISSUE TITLE
Database locked, sleeping then retrying

### ISSUE THREAD

**Issue by gerardo8a** [grafana/grafana#22555]
**What happened**:

t=2020-03-03T22:39:33+0000 lvl=info msg="Database locked, sleeping then retrying" logger=sqlstore error="database is locked" retry=0

I start getting this error without even doing anything. Using provision dashbaords.

```apiVersion: 1

providers:
  # <string> an unique provider name
  - name: 'Omega'
    # <int> org id. will default to orgId 1 if not specified
    orgId: 1
    # <string, required> name of the dashboard folder. Required
    folder: 'Federation'
    # <string> folder UID. will be automatically generated if not specified
    folderUid: 'federation'
    # <string, required> provider type. Required
    type: file
    # <bool> disable dashboard deletion
    disableDeletion: false
    # <bool> enable dashboard editing
    editable: true
    # <int> how often Grafana will scan for changed dashboards
    updateIntervalSeconds: 10
    # <bool> allow updating provisioned dashboards from the UI
    allowUiUpdates: false
    options:
      # <string, required> path to dashboard files on disk. Required
      path: /var/lib/grafana/dashboards/federation
```

```
apiVersion: 1

providers:
  # <string> an unique provider name
  - name: 'Omega'
    # <int> org id. will default to orgId 1 if not specified
    orgId: 1
    # <string, required> name of the dashboard folder. Required
    folder: 'Individual'
    # <string> folder UID. will be automatically generated if not specified
    folderUid: 'individual'
    # <string, required> provider type. Required
    type: file
    # <bool> disable dashboard deletion
    disableDeletion: false
    # <bool> enable dashboard editing
    editable: true
    # <int> how often Grafana will scan for changed dashboards
    updateIntervalSeconds: 10
    # <bool> allow updating provisioned dashboards from the UI
    allowUiUpdates: false
    options:
      # <string, required> path to dashboard files on disk. Required
      path: /var/lib/grafana/dashboards/individual
```

**What you expected to happen**:
no lock

**How to reproduce it (as minimally and precisely as possible)**:
Using grafana docker; grafana/grafana:6.6.2

**Anything else we need to know?**:
Using folders
Mutliple datasources

**Environment**:
- Grafana version: 66.2
- Data source type & version: prometheus
- OS Grafana is installed on: desktop
- User OS & Browser: MacOS 10.15.3  and Chrome Version 80.0.3987.122 (Official Build) (64-bit)
- Grafana plugins: pie chart
- Others:
