### ISSUE TITLE
Grafana UID keeps randomly changing without grafana being restarted

### ISSUE THREAD

**Issue by gerardo8a** [grafana/grafana#22556]
**What happened**:
Using docker version of grafana and adding my dashboards in separate directories. 
Also each directory uses a different prometheus source

* Datasource 
```
apiVersion: 1

datasources:
  - name: prometheus-federation
    type: prometheus
    access: proxy
    url: https://prometheus-federation.......
```

```
apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: https://prometheus......
```

* Providers
```
apiVersion: 1

providers:
  # <string> an unique provider name
  - name: 'Omega'
    # <int> org id. will default to orgId 1 if not specified
    orgId: 1
    # <string, required> name of the dashboard folder. Required
    folder: 'Federation'
    # <string> folder UID. will be automatically generated if not specified
    folderUid: 'federation'
    # <string, required> provider type. Required
    type: file
    # <bool> disable dashboard deletion
    disableDeletion: false
    # <bool> enable dashboard editing
    editable: true
    # <int> how often Grafana will scan for changed dashboards
    updateIntervalSeconds: 10
    # <bool> allow updating provisioned dashboards from the UI
    allowUiUpdates: false
    options:
      # <string, required> path to dashboard files on disk. Required
      path: /var/lib/grafana/dashboards/federation
```

```
apiVersion: 1

providers:
  # <string> an unique provider name
  - name: 'Omega'
    # <int> org id. will default to orgId 1 if not specified
    orgId: 1
    # <string, required> name of the dashboard folder. Required
    folder: 'Individual'
    # <string> folder UID. will be automatically generated if not specified
    folderUid: 'individual'
    # <string, required> provider type. Required
    type: file
    # <bool> disable dashboard deletion
    disableDeletion: false
    # <bool> enable dashboard editing
    editable: true
    # <int> how often Grafana will scan for changed dashboards
    updateIntervalSeconds: 10
    # <bool> allow updating provisioned dashboards from the UI
    allowUiUpdates: false
    options:
      # <string, required> path to dashboard files on disk. Required
      path: /var/lib/grafana/dashboards/individual
```

Dockerfile

```
FROM <MY BASE IMAGE>

RUN curl -L -f -o grafana-pie-chart.zip https://github.com/grafana/piechart-panel/releases/download/v1.4.0/grafana-piechart-panel-1.4.0.zip
RUN mkdir -p /plugins
RUN unzip -o grafana-pie-chart.zip -d /plugins

FROM grafana/grafana:6.6.2
COPY --from=tools /plugins /var/lib/grafana/plugins
# dasboards/
#     federation/
#     individual/
COPY dashboards /var/lib/grafana/dashboards

# providers contains the two files descirbed above
COPY providers /etc/grafana/provisioning/dashboards

# providers defined above
COPY datasource /etc/grafana/provisioning/datasources



**What you expected to happen**:
Run grafana and load dashboards from folders, but when I start grafana the directories in grafana are there "federation" and "individual" but I have to click several times to see the dashboards inside, seems that something prevents the dashboards from loading.

Even whena dashboard loads I can see the data but after a few refresh (two or three) the dashboard is gone!  with the error
`Dashboard not found`

Logs show

```
2020-03-03T22:51:27+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/dashboards/uid/B9AQzf_Zk status=404 remote_addr=172.17.0.1 time_ms=0 size=33 referer="http://localhost:3000/d/B9AQzf_Zk/cluster-utilization?orgId=1"
```

Seems that the uid changes all the time because I go back and try to find again the same dashboard via the folder and when It finally shows up in the folder when I click the url UID is different.

**How to reproduce it (as minimally and precisely as possible)**:
Build the container
```
docker build . -t grafana && docker run -p 3000:3000 grafana:latest
```


**Anything else we need to know?**:



**Environment**:
- Grafana version: 66.2
- Data source type & version: prometheus
- OS Grafana is installed on: desktop
- User OS & Browser: MacOS 10.15.3 and Chrome Version 80.0.3987.122 (Official Build) (64-bit)
- Grafana plugins: pie chart
- Others:
