### ISSUE TITLE
Template list broken with query 

### ISSUE THREAD

**Issue by garrettheel** [grafana/grafana#22973]
**What happened**:

The select boxes described by `templating.list` in the dashboard JSON are acting strangely, to the point that they're unusable.

From what I can tell, an object is being used in place of a string. This is also evidenced by the fact that I can see requests to my datasource with the literal `request=[object Object]`.

The dashboard config looks like:

```yaml
templating:
  list:
    - name: foo
      type: query
      query: my_query_goes_here
      datasource: mydatasource
      current:
        text: default1
        value: default1
    - name: bar
      type: query
      query: my_query_goes_here
      datasource: mydatasource
      current:
        text: default1
        value: default1
```

It's worth noting that the `bar` query does reference the variable set by `foo`, but I also see the same issue if I delete `bar` and just have `foo`.

**What you expected to happen**:

I expect the default value to appear and the dropdown box to populate with results from the query. Instead, the dropdown is initially "None" and does not populate with the query results.

**How to reproduce it (as minimally and precisely as possible)**:

Use the above dashboard config and load a dashboard. Interact with the select box.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8d5c605
- Data source type & version: Custom
- OS Grafana is installed on: Linux 5.5.8-100.fc30.x86_64
- Old (working) version: bcac76f
- User OS & Browser: OSX 10.14 / Chrome 80.0.3987.149
- Grafana plugins:
- Others:
