### ISSUE TITLE
Make file the default dashboard provider type

### ISSUE THREAD

**Issue by marcusolsson** [grafana/grafana#23111]
**What would you like to be added**:

I'd like for the default dashboard provider type to be "file", as this is the only valid value.

**Why is this needed**:

Today, `type` is a required property when defining a dashboard provider, even though there's only [one valid option](https://github.com/grafana/grafana/blob/69c5efcf005cc44e5777aea654800d7a298b94c6/pkg/services/provisioning/dashboards/dashboard.go#L100): `file`:

```
apiVersion: 1

providers:
  - name: Default
    type: file # Should be the default value
    options:
      path: /var/lib/grafana/dashboards
```

Every required property places cognitive load on the person learning something new. We should strive to simplify the number of things they need to know to get started.
