### ISSUE TITLE
oAuth overwrites Organization assignment

### ISSUE THREAD

**Issue by DaspawnW** [grafana/grafana#23204]
**What happened**:
User who is federated from keycloak via generic oauth gets added to an Organization by an administrator (he is also an admin). During the assignment he is logged in and performs a refresh then he can see the assignment and perform a switch to the other Organization.
If the user performs a logout and login again the assignment is gone.
Same if the user is not logged in during the assignment, after he performs login the assignment to an organization is gone.
I haven't configured allowed_organization.

**What you expected to happen**:
The user gets assigned to an Organization as soon as the user performs login he sees the Organization and can switch into it.

**How to reproduce it (as minimally and precisely as possible)**:

Helm Chart deployment with following grafana["grafana.ini"] file.

```
  grafana.ini:
    server:
      root_url: https://this value is overwritten
    database:
      url: "postgres://${PGUSERNAME}:${PGPASSWORD}@grafana:5432/grafana"
    users:
      allow_sign_up: false
    auth.generic_oauth:
      name: DIMS
      enabled: true
      client_id: ${OIDC_CLIENT_ID}
      client_secret: ${OIDC_CLIENT_SECRET}
      scopes: "openid email"
      auth_url: ${OIDC_URL}/auth/realms/dims/protocol/openid-connect/auth
      token_url: ${OIDC_URL}/auth/realms/dims/protocol/openid-connect/token
      api_url: ${OIDC_URL}/auth/realms/dims/protocol/openid-connect/userinfo
      allow_sign_up: true
      role_attribute_path: contains(roles[*], 'admin') && 'Admin' || contains(roles[*], 'editor') && 'Editor' ||'Viewer'
      ;allowed_organizations: ""
```

outcome is the following:

```
[analytics]
check_for_updates = true

[auth.generic_oauth]
;allowed_organizations =
allow_sign_up = true
api_url = ${OIDC_URL}/auth/realms/dims/protocol/openid-connect/userinfo
auth_url = ${OIDC_URL}/auth/realms/dims/protocol/openid-connect/auth
client_id = ${OIDC_CLIENT_ID}
client_secret = ${OIDC_CLIENT_SECRET}
enabled = true
name = DIMS
role_attribute_path = contains(roles[*], 'admin') && 'Admin' || contains(roles[*], 'editor') && 'Editor' ||'Viewer'
scopes = openid email
token_url = ${OIDC_URL}/auth/realms/dims/protocol/openid-connect/token

[database]
url = postgres://${PGUSERNAME}:${PGPASSWORD}@grafana:5432/grafana

[grafana_net]
url = https://grafana.net

[log]
mode = console

[paths]
data = /var/lib/grafana/data
logs = /var/log/grafana
plugins = /var/lib/grafana/plugins
provisioning = /etc/grafana/provisioning

[server]
root_url = https://this value is overwritten

[users]
allow_sign_up = false
```

**Anything else we need to know?**:

I used helm chart in version 5.0.9

**Environment**:
- Grafana version: Grafana v6.7.1 (ca6d08d5cb)
- Data source type & version:
- OS Grafana is installed on: Docker / Linux
- User OS & Browser: Mac OSX / Firefox
- Grafana plugins:-
- Others:-
