### ISSUE TITLE
Still unable to send emails that do not require TLS connections

### ISSUE THREAD

**Issue by thameezb** [grafana/grafana#24563]
As per Ref https://github.com/grafana/grafana/issues/7189

It should be possible to send emails to an SMTP server that doesn't require TLS connections.

This is still an issue and experienced by 3 other users in the previously closed issue. 

Grafana Version v6.7.1

Config (helm chart):
```
  smtp:
    enabled: true
    host: "10.10.120.18:25"
    skip_verify: true
    from_address: "grafana@grafana.co.za"
    from_name: "Grafana"
    ehlo_identity: "server.grafana.local"
```
```
Log Error:
t=2020-03-24T14:02:29+0000 lvl=eror msg="failed to send notification" logger=alerting.notifier uid= error="Failed to send notification to email address: <EMAILADD>: 454 4.7.0 TLS not available due to local problem"
```
