### ISSUE TITLE
Provisioning: Datasource without access field is provisioned but then test in config page does not work

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#24591]
1. Provision the devenv datasources
2. Configure the gdev-cloudwatch datasource with access/secret key. 
3. Test and Save returns 'Validation failed' 

Adding a new Clouwatch Datasource works as expected. 

git commit: 846142eebdb5a2a94c01bdd1cbeeb5261ee1c9e2

**Comment by aocenas** [comment]
So I get this only if I do not specify `access` key:
```
- name: test-cloudwatch
    type: cloudwatch
    editable: true
    access: proxy <-- is required even though it's not in the UI
    jsonData:
      authType: keys
      defaultRegion: eu-west-2
...

```
