### ISSUE TITLE
Docker permission issues

### ISSUE THREAD

**Issue by modem7** [grafana/grafana#24595]
**What happened**:
Fresh build of Grafana docker, permission issues with persistent volume

**What you expected to happen**:
No permission issues

**How to reproduce it (as minimally and precisely as possible)**:
```
  grafana:
    hostname: Grafana
    container_name: Grafana
    image: grafana/grafana
    networks:
      pihole:
        ipv4_address: '172.22.0.111'
    ports:
      - "3001:3000"
    volumes: 
      - Grafana:/config
    environment:
      - GF_PATHS_DATA=/config/data
      - GF_PATHS_LOGS=/config/logs
      - GF_PATHS_PLUGINS=/config/plugins
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel
    depends_on:
      - varkendb
      - varken
      - telegraf
    restart: unless-stopped
```

**Anything else we need to know?**:
```
GF_PATHS_DATA='/config/data' is not writable.
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later
mkdir: can't create directory '/config/plugins': Permission denied
```
I understand that I can do a directory permissions change following the instructions at https://grafana.com/docs/grafana/latest/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later - but why isn't this working as standard in a persistent volume as per your recommendations in https://grafana.com/docs/grafana/latest/installation/configure-docker/

Forgive me if I'm being a muppet here!

**Environment**:
- Grafana version: Docker latest
- Data source type & version: InfluxDB latest
- OS Grafana is installed on: Fedora/Docker
- User OS & Browser: Waterfox latest
- Grafana plugins: grafana-piechart-panel,grafana-worldmap-panel
- Others:
