### ISSUE TITLE
Import API returns empty message when behind reverse proxy

### ISSUE THREAD

**Issue by jamesthegiantpeach** [grafana/grafana#24756]
**What happened**:
I have setup grafana server behind an istio gateway. I have adjusted grafana.ini to the appropriate reverse proxy settings

```
[server]
domain = monitoring.[REDACTED].local
root_url = %(protocol)s://%(domain)s/istio/grafana/
serve_from_sub_path = true
```

I am able to access the UI and navigate around just fine, but when I try to import a dashboard with the UI, I get an error. The server logs show 

```
"Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/gnet/dashboards/undefined status=404 remote_addr=10.1.27.1 time_ms=296 size=60 referer=http://monitoring.[REDACTED].local/istio/grafana/dashboard/import
t=2020-05-15T19:49:24+0000 lvl=eror msg="Dashboard not found" logger=context userId=0 orgId=1 uname= error="Dashboard not found"
```
When using the browser debugger, I find the call is to ` http://monitoring.[REDACTED].local/istio/grafana/api/dashboards/import`, and it returns a 404. 

When I remove all of the reverse proxy settings and do a standard install, I am able to get the dashboards to import. If I use the reverse proxy with the standard root path I also get the same error. So it's not the non-standard path. 

**What you expected to happen**:
I expected the dashboard to import.

**How to reproduce it (as minimally and precisely as possible)**:
- Install microk8s for k8s 1.18. 
- microk8s.enable rbac dns storage registry metallb
- Grab the [manifest](https://github.com/kubeflow/manifests/blob/master/istio/istio-install/base/istio-noauth.yaml) and add an overlay patch 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: grafana
          volumeMounts:
            - name: config
              mountPath: "/etc/grafana/grafana.ini"
              subPath: grafana.ini
```

with 

```
configMapGenerator:
  - name: istio-grafana
    behavior: merge
    files:
      - grafana.ini
```
in your kustomization.yaml file. 

- Create istio gateway resources

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: monitoring-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "monitoring.[REDACTED].local"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana-vs
spec:
  hosts:
    - "monitoring.[REDACTED].local"
  gateways:
    - "monitoring-gateway"
  http:
    - match:
        - uri:
            prefix: "/istio/grafana/"
          method:
            exact: "GET"
      rewrite:
        uri: "/istio/grafana/"  (I have also tried this with rewrite to /)
      route:
        - destination:
            host: "grafana.istio-system.svc.cluster.local"
            port:
              number: 3000
```
- `microk8s.kubectl get svc -n istio-system` and get the public IP for the istio-ingressgateway
- Create an entry for monitoring.[REDACTED].local and the gateway ip in /etc/hosts. 
- Navigate to http://monitoring.[REDACTED].local/istio/grafana/
- Navigate to import dashboard and try to import any dashboard (e.g. node exporter dash with id 11074) 

**Environment**:
- Grafana version: 6.4.2
- Data source type & version: Prometheus v2.3.1
- OS Grafana is installed on: It is running in the standard grafana/grafana:6.4.2 container. I have it deployed on microk8s on an ubuntu 18.04 box. 
- User OS & Browser: Ubuntu 18.04 / Chrome
