### ISSUE TITLE
Grafana don't start - new installation

### ISSUE THREAD

**Issue by Syntax3rror404** [grafana/grafana#25040]
**What happened**: I use docker for runnig grafana in my environment. I make everything from the doc to install it. I changed the permission for the volumes and then i start grafana via docker-compose.

I get this error:

```
[root@dockersrv01 dockersrv01]# docker-compose -f compose/monitoring/docker-compose.yml logs
Attaching to monitoring_grafana_1
grafana_1  | /run.sh: line 80: exec: grafana-server: not found
```

The container restarts every time because of the error and the restart allways. I try to remove the volumes and try again, but i get this error every time.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

Simply make a docker-compose up. 

**Anything else we need to know?**:

Yes, this is my docker-compose file:

```
version: "3.7"

services:
  grafana:
    image: grafana/grafana:7.0.0
    restart: always
    ports:
      - 3000:3000
    user: "472"
    volumes:
      - ../../volumes/grafana/grafana_conf:/etc/grafana
      - ../../volumes/grafana/grafana_lib:/var/lib/grafana
      - ../../volumes/grafana/grafana_home:/usr/share/grafana

```
**Environment**:
- Grafana version: grafana/grafana: 7.0.0
- Data source type & version: na
- OS Grafana is installed on: docker on CentOS 8
- User OS & Browser: Windows 10 - Chrome
- Grafana plugins: na
- Others: na
