### ISSUE TITLE
Provisioning plugins using config files 

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#25526]
It should be possible to provision Grafana with plugins using config files. On startup, Grafana should make sure that the specified plugins are installed and configured correctly. If the plugins are missing Grafana should fetch them using the same code as the CLI. If the plugins are not set up as configured, Grafana should update the settings for that plugin (Only app plugins can be configured currently)

The config files should allow the operator to specify which plugin that should be installed and at what version. The initial version should support specific versions or `latest`. Specifying what versions that accepted new patches (ex ^1.2.0) etc is out of scope for the initial implementation. 

Plugins can only be installed once per instance but can have app settings per org. So I suggest that each plugin can have a settings array of how that plugin should be configured in Grafana database. Ex

```yaml
apiVersion: 1

plugins:
  - name: grafana-piechart-panel
    version: 1.2.3
  - name: grafana-alerting-ui-app
    version: latest
    settings: 
    - orgId: 1	
      enabled: true
      pinned: true
      jsonData: 
        url: https://some.cloudy.service
      secureJsonData:
        token: <foo-bar-baz>
    - orgId: 2	
      enabled: true
      jsonData: 
        url: https://some.cloudy.service
      secureJsonData:
        token: <foo-bar-baz>
```
