### ISSUE TITLE
remote_cache is not working in grafana in kubernetes

### ISSUE THREAD

**Issue by rjshrjndrn** [grafana/grafana#25735]
**What happened**:
Configured [remote_cache]
```
      - env:
        - name: GF_REMOTE_CACHE_TYPE
          value: redis
        - name: GF_REMOTE_CACHE_CONNSTR
          value: addr=172.19.0.2:6379

```
**What you expected to happen**:
I have 2 grafana instances with same above config.
If I login to first cluster,  then next cluster shouldn't ask for login info

**How to reproduce it (as minimally and precisely as possible)**:
```
helm install prometheus-operator
kubectl edit deployment prometheus-operator-grafana 
```
Add the snippet in 
```
      - env:
        - name: GF_REMOTE_CACHE_TYPE
          value: redis
        - name: GF_REMOTE_CACHE_CONNSTR
          value: addr=172.19.0.2:6379

```

**Anything else we need to know?**:

**Environment**: 
- Grafana version:
```
 bash-5.0$ grafana-server -v
Version 7.0.3
```
- Data source type & version:
- OS Grafana is installed on: 
```
❮ kubectl version --short
Client Version: v1.16.0
Server Version: v1.16.3-k3s.2

kubernetes
Prometheus-operator version: prometheus-operator-8.5.8
```
