### ISSUE TITLE
jsonData "tlsSkipVerify" is not submitted when provisioning InfluxDB datasource 

### ISSUE THREAD

**Issue by josteinHellerud** [grafana/grafana#25828]
Hi! 

Thanks for making Grafana. I'm having some trouble with provisioning InfluxDB with `tlsSkipVerify: true`. Any help would be very much appreciated. Thanks in advance. 

**What happened**: 
I'm trying to provision a datasource for Grafana 7.0.3-ubuntu running in Docker locally. Everything works well, except that I cannot set `tlsSkipVerify: true`. From what I can understand it seems to be an issue with either my datasource provisioning file, or a bug where the jsonData is not submitted for some reason. This is the datasource provisioning file I'm using `all.yml`:

```
datasources:
  - name: 'InfluxDB'
    type: 'influxdb'
    access: 'proxy'
    org_id: 1
    url: 'https://host.docker.internal:21108'
    is_default: true
    editable: true
    database: 'skogul'
    user: 'foo'
    password: 'bar'
    withCredentials: false
    jsonData:
      tlsSkipVerify: true
    version: 1
```

Using the API to verify what was submitted gives me: 

```
{
    "id": 1,
    "orgId": 1,
    "name": "InfluxDB",
    "type": "influxdb",
    "typeLogoUrl": "",
    "access": "proxy",
    "url": "https://host.docker.internal:21108",
    "password": "bar",
    "user": "foo",
    "database": "skogul",
    "basicAuth": false,
    "basicAuthUser": "",
    "basicAuthPassword": "",
    "withCredentials": false,
    "isDefault": true,
    "jsonData": {},
    "secureJsonFields": {},
    "version": 1,
    "readOnly": false
}
```

As you can see jsonData is empty. 

**What you expected to happen**:
I expected the jsonData field to contain `tlsSkipVerify: true`. I used the GUI to set this value manually and checked with the API again. This produced this result: 

```
{
    "id": 1,
    "orgId": 1,
    "name": "InfluxDB",
    "type": "influxdb",
    "typeLogoUrl": "",
    "access": "proxy",
    "url": "https://host.docker.internal:21108",
    "password": "bar",
    "user": "foo",
    "database": "skogul",
    "basicAuth": false,
    "basicAuthUser": "",
    "basicAuthPassword": "",
    "withCredentials": false,
    "isDefault": true,
    "jsonData": {
        "tlsSkipVerify": true
    },
    "secureJsonFields": {},
    "version": 2,
    "readOnly": false
}
```
This is what I expected to be returned after provisioning the first time. 

**How to reproduce it (as minimally and precisely as possible)**:
Run dockerized Grafana and add the file `all.yml` (pasted on the top here) to the folder `/etc/grafana/provisioning`.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana 7.0.3-ubuntu
- Data source type & version: InfluxDB 
- OS Grafana is installed on: MacOS Catalina 10.15.5 running Docker version 19.03.8
- User OS & Browser: MacOS Catalina 10.15.5 & Chrome Version 83.0.4103.106
- Grafana plugins:
- Others:
