### ISSUE TITLE
Data source provisioning access value error not caught by validator

### ISSUE THREAD

**Issue by protohuf** [grafana/grafana#25866]
**What happened**:
Using a data source provisioning yaml with a certain incorrect value for the "access" key will still add the data source. The data source however, is not usable.

Example to incorrect data source provisioning yaml:
```
    apiVersion: 1
    datasources:
        - access: proxy,
          editable: true
          name: prometheus
          isDefault: true
          orgId: 1
          type: prometheus
          url: localhost:9090
          version: 1
```

Note the error on the "access" key property: "proxy," (a comma at the end). Grafana will parse this data source and add it without any warnings or errors. When trying to create a dashboard using data from the data source a hard-to-parse UI error will occur: "Failed to fetch"

**What you expected to happen**:
Receive an error of incorrect value on key "access".

**How to reproduce it (as minimally and precisely as possible)**:

- Create a data source provisioning file using the example given above, eg: /etc/grafana/provisioning/datasources/prom.yaml
- Start Grafana (note no error message of incorrect syntax)
- Try to add a panel in a new dashboard with any data from the data source (eg; PromQL: prometheus_build_info)
- Note the exclamation point in the corner of the panel, hovering over the exclamation point shows the error: "Failed to fetch"

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.4
- Data source type & version: Prometheus
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Ubuntu 18.04
- Grafana plugins: None
- Others: N/A
