### ISSUE TITLE
Made "Explore" Tool Available to the Users With "Viewer" Role

### ISSUE THREAD

**Issue by k8s42** [grafana/grafana#25914]
**What would you like to be added**:
To have the "Explore" tool available to the users with the "Viewer" role.

**Why is this needed**:
Our team finds Explore to be a very powerful tool to view logs and metrics using Loki and Prometheus, respectively. This allows us to look at raw data for root-cause analysis purposes without the need to write new dashboards or work with existing ones. The Ops team members with "Viewer" roles would benefit from it greatly as they won't have to rely on someone to write dashboards for them. This would help them in quick analysis of issues occurring in the cluster, cluster resources app, containers, etc. using Prometheus and Loki as data sources.

**Comment by torkelo** [comment]
Just enable this setting: https://grafana.com/docs/grafana/latest/administration/configuration/#viewers-can-edit

**Comment by Mike7518** [comment]
Link to the current version of the documentation : https://grafana.com/docs/grafana/v10.1/setup-grafana/configure-grafana/#viewers_can_edit
> `viewers_can_edit`
>Viewers can access and use [Explore](https://grafana.com/docs/grafana/v10.1/explore/) and perform temporary edits on panels in dashboards they have access to. They cannot save their changes. Default is false.

**Comment by younsl** [comment]
You can add the `viewers_can_edit` setting to the ConfigMap resource that Grafana pod uses. This was tested on Grafana version 11.5.2 installed using the helm chart.

```yaml
data:
  grafana.ini: |
    [users]
    viewers_can_edit = true
```

The above configuration is part of the ConfigMap that the Grafana pod references. After adding this setting, viewer users can access the Explore tab in Grafana.

```toml
[users]  
# Viewers can edit and inspect dashboards in the browser but cannot save them.  
viewers_can_edit = true 
```

**Comment by younsl** [comment]
You can add the [viewers_can_edit](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#viewers_can_edit) setting to the ConfigMap resource that the Grafana pod uses. This was tested on Grafana version 11.5.2 installed using the official Helm chart.

```toml
[users]  
# Viewers can edit and inspect dashboards in the browser but cannot save them.  
viewers_can_edit = true
```

You can add the following to the ConfigMap that the Grafana pod references. The absolute path to the config file in the Grafana pod is `/etc/grafana/grafana.ini`.

```yaml
data:
  grafana.ini: |
    [users]
    viewers_can_edit = true
```

The above configuration is part of the ConfigMap that the Grafana pod references. After adding this setting, viewer users can access the Explore tab in Grafana.

![Image](https://github.com/user-attachments/assets/54fc6f8f-1521-4529-a3ad-f5c15891b3b3)

![Image](https://github.com/user-attachments/assets/a3f3be53-a76b-49c8-bd05-55eb2bfda638)
