### ISSUE TITLE
Graafna ignores the esVersion field in datasources

### ISSUE THREAD

**Issue by jakubgs** [grafana/grafana#26078]
I'm running the `grafana/grafana:7.0.4` Docker container and I'm provisioning an ElasticSearch proxy using this config:
```yaml
apiVersion: 1

deleteDatasources:
  - id: 1

datasources:
- name: ElasticSearch
  type: elasticsearch
  orgId: 1
  esVersion: 70
  database: '[logstash-]YYYY.MM.DD'
  interval: 'Daily'
  timeField: '@timestamp'
  logMessageField: 'message'
  logLevelField: 'severity_name'
  access: proxy
  url: http://elasticsearch:9200
  withCredentials: false
  isDefault: false
  jsonData:
     tlsAuth: false
     tlsAuthWithCACert: false
  version: 1
  editable: true
```
According to documentation the value of `70` is valid:

>`esVersion` - number - Elasticsearch version as a number (2/5/56/60/70)
>https://grafana.com/docs/grafana/latest/administration/provisioning/#data-sources

But whenever I restart Grafana it reverts to version `5.0` of ElasticSearch, which breaks all graphs:
![grafana_es_settings](https://user-images.githubusercontent.com/2212681/86571827-616e0a80-bf72-11ea-86de-e1c0c04b9abe.png)
It also appears to be ignoring the `interval`, `logMessageField`, and `logLevelField` settings.
Removing the config file from `provisioning/datasources` stop these fields from being reset on restart.
