### ISSUE TITLE
Loki - derived field configuration

### ISSUE THREAD

**Issue by zemacnica** [grafana/grafana#26087]
https://github.com/grafana/grafana/pull/23585

**What happened**: 
I have configuration with multiple datasources. I configured Loki with derived field, but only option how to link Jaeger internally is to fill datasourceUid. But I can't define Jaeger uid or use other identificator (like name). And datasource created by config can't be edited.
Also to find datasource uid is little bit tricky (I have to inspect requests, maybe there is better way)

configuration:

  ```
   - name: Jaeger
      type: jaeger
      url: http://jaeger-tracing-query.observability.svc.cluster.local:16686/loyalty/jaeger
      access: server
    - name: Loki
      type: loki
      url: http://loki:3100
      access: proxy
      jsonData:
        maxLines: 1000
        derivedFields:
          # Field with internal link pointing to data source in Grafana.
          # Right now, Grafana supports only Jaeger and Zipkin data sources as link targets.
          - datasourceUid: Jaeger
            matcherRegex: "traceID=(\\w+)"
            name: TraceID
            # url will be interpreted as query for the datasource
            url: "$${__value.raw}"
  
          # Field with external link.
          # - matcherRegex: "traceID=(\\w+)"
          #   name: TraceID
          #   url: "http://localhost:16686/trace/$${__value.raw}"
```

**What you expected to happen**:
- to have posibility to configure Jager uid or use Jaeger name in Loki configuration

**How to reproduce it (as minimally and precisely as possible)**:
Configure both datasources -  Jaeger and Loki with derived field with internal link

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.1.0-beta2
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by aocenas** [comment]
> But I can't define Jaeger uid or use other identificator (like name)

What does this mean exactly? Do you get an error if you add it? The way this should work is that you can have:
```
- name: Jaeger
    uid: my-jaeger-datasource
    type: jaeger
    url: http://jaeger-tracing-query.observability.svc.cluster.local:16686/loyalty/jaeger
    access: server
```

And then reference `my-jaeger-datasource` in the Loki definition.

**Comment by zemacnica** [comment]
I tried also define uid in Jaeger datasource, just as experiment  ( it is not mentioned in documentation ), but it did't work either. Or values should be "my-jaeger-datasource" ?

**Comment by zemacnica** [comment]
![image](https://user-images.githubusercontent.com/47662214/86782298-2e557500-c05f-11ea-8407-eb44ff890c41.png)
```yaml
   - name: Jaeger
      type: jaeger
      url: http://jaeger-tracing-query.observability.svc.cluster.local:16686/loyalty/jaeger
      access: server
      uid: jaeger123
   - name: Loki
      type: loki
      url: http://loki:3100
      access: proxy
      jsonData:
        maxLines: 1000
        derivedFields:
          # Field with internal link pointing to data source in Grafana.
          # Right now, Grafana supports only Jaeger and Zipkin data sources as link targets.
          - datasourceUid: jaeger123 # not a uid, bug
            matcherRegex: "traceID=(\\w+)"
            name: TraceID
            # url will be interpreted as query for the datasource
            url: "$${__value.raw}"
```
Ok, it works after second attempt! Interesting. Thank you.

![image](https://user-images.githubusercontent.com/47662214/86783891-272f6680-c061-11ea-85e5-c4f759dbf96f.png)

**Comment by aocenas** [comment]
The `uid` value can be anything, it should just be unique across all defined datasource uids. If it is not defined in the provisioning file then it is created as a random unique string. That is specifically to allow the linking and referencing between datasources. So in this case:
```
- name: Jaeger
    uid: my-jaeger
    type: jaeger
    url: http://jaeger-tracing-query.observability.svc.cluster.local:16686/loyalty/jaeger
    access: server
  - name: Loki
    type: loki
    url: http://loki:3100
    access: proxy
    jsonData:
      maxLines: 1000
      derivedFields:
        # Field with internal link pointing to data source in Grafana.
        # Right now, Grafana supports only Jaeger and Zipkin data sources as link targets.
        - datasourceUid: my-jaeger
          matcherRegex: "traceID=(\\w+)"
          name: TraceID
          # url will be interpreted as query for the datasource
          url: "$${__value.raw}"

        # Field with external link.
        # - matcherRegex: "traceID=(\\w+)"
        #   name: TraceID
        #   url: "http://localhost:16686/trace/$${__value.raw}"
```
should work.

**Comment by aocenas** [comment]
If you have trouble with this in the future in some cases just reopen this but going to close this now.

**Comment by GNSunny** [comment]
Hi, In the newer version of grafana-9.30, for the additional data sources when adding the Loki-data source in the derived fields the url is not getting updated in the query filed in the UI
my config for additionalDatasource is 

```
  additionalDataSources:
    - name: Loki
      type: loki
      url: 'http://loki:3100'
      access: proxy
      isDefault: false
      editable: true
      jsonData:
        timeout: "300"
        derivedFields:
          - datasourceUid: tempo-datasource
            matcherRegex: "traceId=(\\w+)"
            url: '$${__value.raw}'     <<<<<------------------
            name: traceId
    - name: Tempo
      type: tempo
      uid: tempo-datasource
      url: 'http://tempo:3100'
      isDefault: false
      editable: true
```
![image](https://user-images.githubusercontent.com/2715756/220948039-f60b99ce-8acb-42bf-b3fc-1aa4c8e80926.png)

The above query field is not getting updated I have tried replacing `url: '$${__value.raw}` field with `query: '$${__value.raw}` and tried different bits but the query field from the above snapshot never gets updated. 

much appreciated, If anyone help/support with this issue, please?

dfd
