### ISSUE TITLE
Colors for Loki log, and inconsistency due to 'level' label

### ISSUE THREAD

**Issue by remithomasn7** [grafana/grafana#26488]
I am currently using Grafana v7.0.6, and I am still facing this issue (https://github.com/grafana/grafana/issues/21112#issue-538288193). To be more precise, when I have no label for my log level, or a label which is not 'level' but 'lvl'. Grafana is (almost) able to set a level and a color to my log:

![Screenshot 2020-07-21 at 15 22 59](https://user-images.githubusercontent.com/45794704/88060173-253bcc00-cb66-11ea-834c-e9881611e62f.png)

I said almost, cause as you can see on the screenshot above, for one of my log line, the lvl=INF is set to unknown. That's a first issue but not the major one.

When I use a label named 'level', Grafana is facing more trouble to identify my log level (and to set a proper color):
![Screenshot 2020-07-21 at 15 27 33](https://user-images.githubusercontent.com/45794704/88060602-c0cd3c80-cb66-11ea-8dce-72f02d03d51d.png)

This time, only the log line with 'lvl=ERR' was well identified. As this issue is closed I am wondering if I am missing something, or if this issue is still there.

_Originally posted by @remithomasn7 in https://github.com/grafana/grafana/issues/21112#issuecomment-661862166_

**Comment by ivanahuckova** [comment]
Hello @remithomasn7! This definitely might seem like inconsistent behaviour that we should fix, but let me first explain why this happens:
>when I have no label for my log level, or a label which is not ‘level’ but ‘lvl’. Grafana is (almost) able to set a level and a color to my log:

Yes, this is because in a case, where you don’t have log level label, we are parsing log message. And in your log message, you have log levels that are consistent with our[ LogLevel enum](https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/types/logs.ts#L9-L27) (Error, Fatal, Info, Warn). That’s why it wasn’t able to identify info and set that log level to unknown - because the word "info" was missing in that log message.

>When I use a label named ‘level’, Grafana is facing more trouble to identify my log level (and to set a proper color):

This is because in this case, we are only looking at level label and in this case, log levels aren’t consistent with our LogLevel enum (WRN, INF, FTL). 

So to fix this, we need to introduce more LogLevels including FTL, INF, WRN. Or if you would like to fix this faster, you can just update labels/logs with levels that are in LogLevel enum.

**Comment by remithomasn7** [comment]
Thanks Ivana for your answer. I'll change my log level to match with the hardcoded logLevel Enum.
Great job by the way !

**Comment by remithomasn7** [comment]
Okay, just a last comment to suggest a better (from my point of view) way to deal with it.

I changed my Promtail yaml config do the following:
```
  pipeline_stages:
  - match:
      selector: '{job="promtail"}'
      stages:
        - json:
            expressions:
                time: time
                level: level
                message: message
                props: props
        - template:
            source: level
            template: '{{ Replace .level "INF" "Info" 1 }}'
        - labels:
            level:
        - timestamp:
            format: RFC3339Nano
            source: time
        - template:
            source: readable_log
            template: 'level={{ .level }} message="{{ .message }}" {{ .props }}'
        - output:
            source: readable_log
```

This allows me to match with the expected logEnum without modifying my log go module !
