### ISSUE TITLE
Display regression at Grafana 7.1.0 on iOS/iPhone

### ISSUE THREAD

**Issue by Paraphraser** [grafana/grafana#26572]
**What happened**:

Please see attached image. Two rows:

* Upper row = Grafana 7.0.6
* Lower row = Grafana 7.1.0

Two columns:

* LHS = iPad screen shot
* RHS = iPhone screen shots (showing effect of scrolling down)

The weather dashboard is built to display as shown on the iPad (two rows, the upper row with three panels, the lower row with 5 panels).

Up to and including Grafana 7.0.6, the iPhone display stacked these as a single column of 8 panels.

As of Grafana 7.1.0, only the first three panels (one iPad row) appear. The master screen view has clearly been sized to accommodate all 8 panels but, after the first three, all the rest of the vertical space is black. 

**What you expected to happen**:

No change in behaviour from 7.0.6 to 7.1.0. I see the behavioural change as a regression.

**How to reproduce it (as minimally and precisely as possible)**:

I am running Grafana as part of [IOTstack/docker](https://github.com/SensorsIot/IOTstack). Changing the relevant "image" line in my `docker-compose.yml`:

```
  grafana:
    container_name: grafana
#    image: "grafana/grafana:7.0.6"
    image: "grafana/grafana:latest"
    restart: unless-stopped
    user: "0"
    ports:
      - "3000:3000"
    env_file:
      - ./services/grafana/grafana.env
    volumes:
      - ./volumes/grafana/data:/var/lib/grafana
      - ./volumes/grafana/log:/var/log/grafana
```

and restarting the stack is sufficient to reproduce this problem. Running 7.0.6, the problem is not present. Running "latest" (7.1.0), the problem is present. Nothing else changes on either the IOTstack/Docker side or the iPhone side.

**Anything else we need to know?**:

It is possible this is related to issue #26439.

**Environment**:

- Grafana version: 7.0.6 vs 7.1.0
- Data source type & version: Influx 1.8.1
- OS Grafana is installed on: Raspbian 10 (Buster) running on 4GB RPi4B.

	```
	$ uname -a
	Linux sec-dev 5.4.51-v7l+ #1326 SMP Fri Jul 17 10:51:18 BST 2020 armv7l GNU/Linux
	```
- User OS & Browser: iOS 13.6 (both iPad and iPhone). Safari.
- Grafana plugins: (whatever comes with IOTstack installation)
- Others: The screen captures are all in kiosk mode but the same thing happens in other modes. It also does not matter whether I use Safari to view the Grafana display or via an "add to Home Screen" link to open the dashboard in its own window.

![evidence](https://user-images.githubusercontent.com/34226495/88366845-8ca78500-cdcd-11ea-9bda-d1486866c6a8.png)
