### ISSUE TITLE
provisioned dashboard can be modify by API

### ISSUE THREAD

**Issue by ktibi** [grafana/grafana#26620]
**What happened**:

A dashboard provisionned by file can be update with API. The configuration of dashboard : 
```
  - name: Services
    folder: 'Services'
    type: file
    disableDeletion: false
    allowUiUpdates: false
    updateIntervalSeconds: 10
    options:
      path: /etc/grafana/provisioning/dashboards/services
```

**What you expected to happen**:

Dashboard provisionned by file can't be modify. Maybe need to add an option like : 
`allowApiUpdates`

**How to reproduce it (as minimally and precisely as possible)**:
Provisionne dashboard with file and modify by API. (in my case, with ansible plugin annotation)

**Anything else we need to know?**:

![image](https://user-images.githubusercontent.com/2437140/88541402-f9f92700-d014-11ea-9b0c-e1ded5219586.png)

**Environment**:
- Grafana version: 7.1.1
- Data source type & version: Multiples
- OS Grafana is installed on: Docker Ubuntu official image
