### ISSUE TITLE
Provisioned datasources do not take effect automatically

### ISSUE THREAD

**Issue by GGOUSSEAUD** [grafana/grafana#26925]
**Describe the bug**
When provisioning a datasource, I need to press save & test on one of my datasources for them to be effective. Shouldn't it be enough just to provision them?

**To Reproduce**
1. Start grafana with provisionned datasource (prometheus & Loki in my case)
2. Check explore or dashboard
3. See that for both it says datasource does not exists
4. Press "Save & test" on one of them.
5. All datasources now work

**Expected behavior**
Provisioned datasources should be effective automatically.

**Environment:**
- Docker version 19.03.6, build 369ce74a3c
- docker-compose version 1.24.0, build 0aa59064

<details>
  <summary>datasource.yml (Click to expand)</summary>

```yaml
apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  timeInterval: 15s
  password:
  user:
  database:
  withCredentials:
  secureJsonData:
    tlsCACert: "..."
    tlsClientCert: "..."
    tlsClientKey: "..."
  version: 1
  editable: true
- name: Loki
  type: loki
  access: proxy
  orgId: 1
  url: http://loki:3100
  version: 1
  editable: true
```
</details>

**Screenshots, Promtail config, or terminal output**

**Before Save & test**
![Ds](https://user-images.githubusercontent.com/25582593/89885373-4161e480-dbcb-11ea-8dde-90e8200a3b57.png)
![Provisioned ds](https://user-images.githubusercontent.com/25582593/89884695-2d69b300-dbca-11ea-8272-906f31d5c909.png)
![Explore state](https://user-images.githubusercontent.com/25582593/89884742-3e1a2900-dbca-11ea-8e9f-b7f0e13f1859.png)
![Back state](https://user-images.githubusercontent.com/25582593/89884940-8df8f000-dbca-11ea-9a14-12af28367c21.png)
**After Save & test**
![image](https://user-images.githubusercontent.com/25582593/89885473-67878480-dbcb-11ea-9a4f-e80e1de8dfaa.png)
![image](https://user-images.githubusercontent.com/25582593/89885648-aae1f300-dbcb-11ea-951a-619a7e1ff626.png)
