### ISSUE TITLE
Token does not work for provisioned Flux data source

### ISSUE THREAD

**Issue by kchervonets** [grafana/grafana#27011]
**What happened**:

The data source appeared in Grafana but the test connection does not work. I manually changed the token and it started to work.

**What you expected to happen**:

To provision a data source with all data including the token.

**How to reproduce it (as minimally and precisely as possible)**:
```
  - name: InfluxDB
    type: "influxdb"
    access: "proxy"
    url: "http://localhost:9999/api/v2"
    basicAuth: true
    editable: true
    jsonData:
      defaultBucket: "mybucket"
      httpMode: "POST"
      organization: "myorg"
      version: "Flux"
    secureJsonData:
      token: "mytoken" (I used a normal generated token)
    secureJsonFields:
      token: true
```
**Anything else we need to know?**:

**Environment**:

Grafana version: 7.1.1
Data source type & version: InfluxDB (quay.io/influxdb/influxdb:2.0.0-beta)
OS Grafana is installed on: macOS
User OS & Browser: Chrome and Safari
Grafana plugins: grafana-piechart-panel
Others:
