### ISSUE TITLE
Unable to connect to Prometheus metrics from inside Docker

### ISSUE THREAD

**Issue by garrypas** [grafana/grafana#27023]
Setup two containers in a docker network locally. One running my DotNET Core app (with Prometheus), the other running Grafana.

I see the Prometheus metrics in my browser at http://localhost:5000/metrics

I installed curl in the grafana container and was able to curl the http://mcs/metrics endpoint (the mcs container is a webapp running on port 80, mapped to 5000 on the host, so port 80 inside docker).

I added the http://mcs/metrics to the URL field and expected the grafana server to be able to reach the mcs container.

![image](https://user-images.githubusercontent.com/5046018/90346382-4b973f00-e020-11ea-8c02-67f68d0260f3.png)

But instead I see this:

![image](https://user-images.githubusercontent.com/5046018/90346419-b34d8a00-e020-11ea-8c3a-39137203f8e6.png)

The metrics endpoint has no authorization requirements, just running it locally atm.

Running latest version of Docker on Mac.

Other things I tried:
- Removing the /metrics part of the URL.
- Toggled Skip TLS Verify.

docker-compose.yml below:

```
version: "3.5"
services:
  mcs:
    container_name: mcs
    build: ./
    ports:
      - "5000:80"
    expose:
      - "80"
    networks:
      - gf_net
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "2345:3000"
    networks:
      - gf_net    

networks:
  gf_net:
    external: false
    name: gf_net

```

**Comment by sakjur** [comment]
Hi Garry,

This is a bit confusing, but Grafana cannot scrape Prometheus-style metrics straight away but needs a Prometheus server in between.
I tend to think of Prometheus as three semi-separate things:

- A way of describing metrics (this is what you have for your **mcs** application, it's also sometimes called OpenMetrics)
- A querying language (PromQL, this is how Grafana asks the Prometheus server for a representation of a time series).
- A Prometheus server which reads your metrics endpoints, stores them in a Prometheus database, and responds to PromQL questions.

Grafana only knows about PromQL and you only have to know about the OpenMetrics format, all the advanced data science-y stuff happens in the Prometheus server which you'll have to spin up as a separate container. Refer to the [Installation | Prometheus](https://prometheus.io/docs/prometheus/latest/installation/) page in Prometheus' documentation for information on how you'd do that. My colleague Ivana has also written a blog post describing the process ["How to Explore Prometheus with Easy 'Hello World' Projects" on the Grafana blog](https://grafana.com/blog/2019/12/04/how-to-explore-prometheus-with-easy-hello-world-projects/).

Feel free to reach out to the Grafana community for support with getting your configuration set up at [community.grafana.com](https://community.grafana.com)

p.s. If you haven't used PromQL before I've written a guide ["Introduction to PromQL, the Prometheus Query Language" on the Grafana blog](https://grafana.com/blog/2020/02/04/introduction-to-promql-the-prometheus-query-language/) that might come in handy.

**Comment by garrypas** [comment]
Thanks for your reply.

This was me being a noob. I added this to my docker-compose.yml

```
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
    - mcs
    networks:
      - gf_net
```

i.e. 3 containers: mcs (my app) ==> prometheus ==> grafana

...and this prometheus.yml file:

```
scrape_configs:
- job_name: mcs_metrics
  scrape_interval: 5s
  static_configs:
  - targets: [ 'mcs:80' ]
```

...and now I see my metrics in Grafana :-)

Thank you for pointing me in the right direction.
