### ISSUE TITLE
GF_SECURITY_ADMIN_PASSWORD_FILE do not work

### ISSUE THREAD

**Issue by z-dmitri** [grafana/grafana#27285]
```
version: '3.8'
secrets:
  some_pwd:
    file: ./some.pwd
services:
  grafana:
    environment:
      - GF_SECURITY_ADMIN_PASSWORD_FILE=/run/secrets/some_pwd
    secrets:
      - some_pwd
```

- set password as 'admin' instead take password from file

+ https://grafana.com/docs/grafana/latest/installation/configure-docker/
mention "GF_SECURITY_ADMIN_PASSWORD__FILE" setting with double '__' - it behave correctly that makes some confusing
Reproduced on latest and 5.2.0 Grafana docker containers

Reproduced on Linux container with Docker for Windows, however secrets works fine for other services

Thanks in advance

**Comment by hugohaggmark** [comment]
Hi @z-dmitri , I've tried with the following without issues:

```yaml
version: '3.8'
secrets:
  some_pwd:
    file: ./some.pwd
services:
  grafana:
    image: grafana/grafana:7.1.5
    ports:
      - "3003:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/some_pwd
    secrets:
      - some_pwd
```

In your exemple the `GF_SECURITY_ADMIN_PASSWORD_FILE` is missing a `_` and should be `GF_SECURITY_ADMIN_PASSWORD__FILE`, can you try that?
