### ISSUE TITLE
Cloudwatch datasource provision silently fails, while doing the same via GUI works fine 

### ISSUE THREAD

**Issue by larsrnielsen** [grafana/grafana#27321]
**What happened**:
Grafana 7.1.5 installed via Prometheus operator chart. Sidecar enabled for datasource and dashboards. For debug purposes I have created a CM and Secret for a Cloudwatch data source (see below). Grafana is configured to use IAM for Serviceaccounts. I am able to use the GUI to get access to CloudWatch data without any issues - I only set the default region to eu-central-1.

I see the following in the log:

```
[2020-09-02 05:55:02] Working on secret: monitoring/grafana-datasources-cloudwatch2
[2020-09-02 05:55:02] Working on configmap: monitoring/grafana-datasources-cloudwatch3
```

```
apiVersion: v1
data:
  datasource.yaml: |-
    apiVersion: 1
    deleteDatasources:
    - name: CloudWatch3
      orgId: 1
    datasources:
    - name: CloudWatch3
      type: cloudwatch
      access: proxy
      orgId: 1
      jsonData:
        authType: credentials
        defaultRegion: "eu-central-1"
      version: 1
      editable: false
kind: ConfigMap
metadata:
  labels:
    grafana_datasource: "1"
  name: grafana-datasources-cloudwatch3
  namespace: monitoring
```

```
apiVersion: v1
stringData:
  datasource.yaml: |-
    apiVersion: 1
    deleteDatasources:
    - name: CloudWatch2
      orgId: 1
    datasources:
    - name: CloudWatch2
      type: cloudwatch
      access: proxy
      orgId: 1
      jsonData:
        authType: credentials
        defaultRegion: "eu-central-1"
        customMetricsNamespaces: 'CWAgent,CustomNameSpace'
      version: 1
      editable: false
kind: Secret
metadata:
  labels:
    grafana_datasource: "1"
  name: grafana-datasources-cloudwatch2
  namespace: monitoring

```

**What you expected to happen**:
I would expect to see at least one configured CloudWatch data source in the GUI, but I only see Prometheus.

**How to reproduce it (as minimally and precisely as possible)**:
A Helm installed Grafana server using sidecars for datasources.
