### ISSUE TITLE
Provisioning of an InfluxDB datasource using Flux query language fails

### ISSUE THREAD

**Issue by cykl** [grafana/grafana#27389]
**What happened**:

When an InfluxDB data source configured to use the Flux query language is provisioned, it exist but supplied configuration wasn't applied.

**What you expected to happen**:

Data source must exist, use Flux query language and token, bucket etc. be set.

**How to reproduce it (as minimally and precisely as possible)**:

I followed data source documentation:
 - https://grafana.com/docs/grafana/latest/features/datasources/influxdb/#influxdb-2x-example
 - https://github.com/influxdata/influxdb-client-go/#influxdb-18-api-compatibility

Data source is provisioned by this configuration file:
 
```yaml
datasources:
  - name: Flux_micrometer
    type: "influxdb"
    access: "proxy"
    url: "http://influx:8086"
    editable: true
    secureJsonData:
      token: "test:test"
    jsonData:
      version: Flux
      organization: ""
      defaultBucket: micrometer
      tlsSkipVerify: true
      timeInterval: "1m"                        
```

Open this data source configuration in Grafana:

![Screenshot_2020-09-04 Flux_micrometer Settings - Grafana](https://user-images.githubusercontent.com/1764725/92244666-7b20c500-eec3-11ea-8e93-2e4c71bb928a.png)

Note that query language is set to InfluxQL rather than Flux. If I manually switch the query language to Flux, all fields are empty

**Anything else we need to know?**:

I am able to configure the data source using form the UI.

![Screenshot from 2020-09-04 15-23-22](https://user-images.githubusercontent.com/1764725/92244883-d652b780-eec3-11ea-987d-f94d20ffb123.png)

Thus, I expect that documentation is erroneous or something is wrong in provisioning. 

I am also able to provision an InfluxQL based data source.

**Environment**:
- Grafana version: 7.1.5
- Data source type & version: InfluxDB (1.8) / Flux
- OS Grafana is installed on: Docker image

**Comment by cykl** [comment]
#27011 reported another issue with Flux data source provisioning.  Since it only complains about the token I expect that other fields are properly configured which is not what I observe. I tried to replicate #27011 using provided configuration and 7.1.1 and observed exactly the same behaviour that I reported in this issue.

**Comment by bckeene** [comment]
Experiencing a similar issue when setting up a fresh Flux data source (InfluxDB Cloud) from the Grafana UI:

<img width="715" alt="Screen Shot 2020-09-11 at 2 47 06 PM" src="https://user-images.githubusercontent.com/3768387/92975963-4ae6a280-f43e-11ea-81cd-2c5859d75975.png">

Confirmed Org, Token, and URL are correct.

**Comment by marefr** [comment]
I just tried your provided configuration at it works as expected for me on 7.2. Make sure that you include the `apiVersion: 1` - did you?

```yaml
apiVersion: 1

datasources:
  - name: Flux_micrometer
    type: "influxdb"
    access: "proxy"
    url: "http://influx:8086"
    editable: true
    secureJsonData:
      token: "test:test"
    jsonData:
      version: Flux
      organization: ""
      defaultBucket: micrometer
      tlsSkipVerify: true
      timeInterval: "1m"
```

**Comment by marefr** [comment]
Closing this due to lack of response. We'll consider reopen the issue if you provide more information.

**Comment by cykl** [comment]
@marefr Sorry for this late response. Adding `apiVersion: 1` indeed fixes the issue.

**Comment by caleb15** [comment]
Where do I get the proper token value? I'm presuming it's not literally `"test:test"`?

**Comment by caleb15** [comment]
Nevermind, I think the token value is `username:password`. It works now, thanks :+1:

**Comment by Lewiscowles1986** [comment]
So I too transposed the `/api/datasources/:id` and `/api/datasources` (which return json, not yaml... wat?)

```
apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    typeName: InfluxDB
    access: proxy
    url: http://influxdb:8086
    basicAuth: true
    basicAuthUser: my-user
    isDefault: true
    editable: true
    user: ""
    database": ""
    secureJsonData:
      basicAuthPassword: my-password
      token: my-super-secret-auth-token
    secureJsonFields:
      basicAuthPassword: true
      token: true
    jsonData:
      httpMode: POST
      version: InfluxQL
      defaultBucket: k6
      organization: my-org
      version": Flux

```

sort of works. I login and change the type and then save and test and it works.

It's very annoying
