### ISSUE TITLE
Redirecting to /login/generic_oauth/login after OAuth 2.0 leads to a 404 page.

### ISSUE THREAD

**Issue by Macrame** [grafana/grafana#27465]
**What happened**:
Grafana shows a 404 page after OAuth 2.0 successfully.

**What you expected to happen**:
Lead me to the home page with authenticated.

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy the KeyCloak server.
2. Create a realm and a client for grafana, and create a user obviously.
**Anything else we need to know?**:
Grafana is running behind many proxies: **Public Load Balancer** -> **HAProxy** -> **metallb** -> **Istio ingress gateway** working on Layer 4 except the last one.
The redirecting flow(assume my domain is `abc.com` and my realm is `abcdef`):
```
Request: https://grafana-dashboard.abc.com/login/generic_oauth
**Referer: https://grafana-dashboard.abc.com/login
**cookie**: redirect_to=%2Flogin%2Fgeneric_oauth%2Flogin
Response: 302-> https://oidc.abc.com/auth/realms/abcdef/protocol/openid-connect/auth?access_type=online&client_id=grafana&redirect_uri=https%3A%2F%2Fgrafana-dashboard.abc.com%2Flogin%2Fgeneric_oauth&response_type=code&scope=openid&state=NKBuKzcQ5hqXKeUta7xYGTzzNJIttLULh9nYUq7eQPE%3D
```
---
```
Request: https://oidc.abc.com/auth/realms/abcdef/protocol/openid-connect/auth?access_type=online&client_id=grafana&redirect_uri=https%3A%2F%2Fgrafana-dashboard.abc.com%2Flogin%2Fgeneric_oauth&response_type=code&scope=openid&state=NKBuKzcQ5hqXKeUta7xYGTzzNJIttLULh9nYUq7eQPE%3D
Referer: https://grafana-dashboard.abc.com/login
Response: 302-> https://grafana-dashboard.abc.com/login/generic_oauth?state=NKBuKzcQ5hqXKeUta7xYGTzzNJIttLULh9nYUq7eQPE%3D&session_state=a2696b80-6b10-4fce-a052-c91fec500240&code=4c4c1959-694b-4e2a-8051-0d4e7ec47f08.a2696b80-6b10-4fce-a052-c91fec500240.ad0ffffb-de11-401d-b827-abb73ece03a4
```
---
```
Request: https://grafana-dashboard.abc.com/login/generic_oauth?state=NKBuKzcQ5hqXKeUta7xYGTzzNJIttLULh9nYUq7eQPE%3D&session_state=a2696b80-6b10-4fce-a052-c91fec500240&code=4c4c1959-694b-4e2a-8051-0d4e7ec47f08.a2696b80-6b10-4fce-a052-c91fec500240.ad0ffffb-de11-401d-b827-abb73ece03a4
Referer: https://grafana-dashboard.abc.com/login
cookie: redirect_to=%2Flogin%2Fgeneric_oauth%2Flogin; oauth_state=602acf72a11d61e5c24216239da64a1f9a53f9503096d4b0d126f8220f2677f8
Response: 302-> /login/generic_oauth/login

```
---
```
Request: https://grafana-dashboard.abc.com/login/generic_oauth/login
Response: 200 (But in fact this is a page with the 404 hit.
```
## Notice  the **Referer** and **cookie** which indicate the browser to redirect to `/login/generic_oauth/login`.

![image](https://user-images.githubusercontent.com/10723556/92545660-314d2b80-f283-11ea-80be-4f70fc9f8a81.png)

**Environment**:
- Grafana version: V7.1.1
- Data source type & version: Prometheus
- OS Grafana is installed on: Kubernetes v1.18.4 with docker 19.03.9 on CentOS 8.0
- User OS & Browser: Chrome 84.0.447 on Windows 10 (version 2004 build 19041.450)
- Grafana plugins: No
- Others:
I tried to clean cache and hard reloaded. It still showed the 404 page.

**Comment by Macrame** [comment]
It's right to direct to the page `/login` before authenticated. But after authenticating successfully it should NOT redirect to `/login/generic_oauth/login` instead of `/`.

**Comment by Macrame** [comment]
Supply logs:

Grafana log:
```
t=2020-09-09T02:30:44+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/generic_oauth status=302 remote_addr=10.1.68.128 time_ms=0 size=328 referer=https://grafana-dashboard.abc.com/login
t=2020-09-09T02:30:47+0000 lvl=info msg="state check" logger=oauth queryState=602acf72a11d61e5c24216239da64a1f9a53f9503096d4b0d126f8220f2677f8 cookieState=602acf72a11d61e5c24216239da64a1f9a53f9503096d4b0d126f8220f2677f8
t=2020-09-09T02:30:47+0000 lvl=info msg="Successful Login" logger=http.server User=ayden.franklin@abc.com
t=2020-09-09T02:30:47+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/generic_oauth status=302 remote_addr=10.1.68.128 time_ms=98 size=49 referer=

```

**Comment by marefr** [comment]
@Macrame please include your [server settings](https://grafana.com/docs/grafana/latest/administration/configuration/#server). Are you using any reverse proxy in front of Grafana?

**Comment by Macrame** [comment]
It runs in a docker container on Kubernetes cluster. There is the server section in configuration:
```
[server]
# Protocol (http, https, h2, socket)
;protocol = http

# The ip address to bind to, empty will bind to all interfaces
;http_addr =

# The http port  to use
;http_port = 3000

# The public facing domain name used to access grafana from a browser
;domain = localhost

# Redirect to correct domain if host header does not match domain
# Prevents DNS rebinding attacks
;enforce_domain = false

# The full public facing url you use in browser, used for redirects and emails
# If you use reverse proxy and sub path specify full url (with sub path)
;root_url = %(protocol)s://%(domain)s:%(http_port)s/

# Serve Grafana from subpath specified in `root_url` setting. By default it is set to `false` for compatibility reasons.
;serve_from_sub_path = false

# Log web requests
;router_logging = false

# the path relative working path
;static_root_path = public

# enable gzip
;enable_gzip = false

# https certs & key file
;cert_file =
;cert_key =

# Unix socket path                                                              
;socket =
```
Grafana is running behind many proxies: Public Load Balancer -> HAProxy -> metallb -> Istio ingress gateway, working on Layer 4 except the last one.

**Comment by Macrame** [comment]
Could you show me the `Referer` and `cookie` for your testing about this issue? I want to confirm it is not ` /login/generic_oauth/login`

**Comment by marefr** [comment]
@Macrame you should configure `root_url` to your public facing url. I think that will resolve your problem.

**Comment by Macrame** [comment]
Thanks for your help.

Actually, I had configured the `root_url` in my deployment yaml file:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
 ...
        env:
        - name: GF_AUTH_GENERIC_OAUTH_ENABLED
          value: "true"
        - name: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
          value: grafana
        - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
          value: "bxxxxxxxxxxxxxxxxxxxxxxxxxx7"
        - name: GF_AUTH_GENERIC_OAUTH_SCOPES
          value: openid
        - name: GF_SERVER_ROOT_URL
          value: https://grafana-dashboard.abc.com/
        - name: GF_AUTH_GENERIC_OAUTH_AUTH_URL
          value: https://oidc.abc.com/auth/realms/abcdef/protocol/openid-connect/auth
        - name: GF_AUTH_GENERIC_OAUTH_TOKEN_URL
          value: https://oidc.abc.com/auth/realms/abcdef/protocol/openid-connect/token
        - name: GF_AUTH_GENERIC_OAUTH_API_URL
          value: https://oidc.abc.com/auth/realms/abcdef/protocol/openid-connect/userinfo
```

Although it took effect (the `oauth_url` and `token_url` etc worked well) I could not find the configuration in the running container. The server section in configuration, which I provided in the above comment, was the default one. I am very Confused for the configuration in a RUNNING Pod(Container).
