### ISSUE TITLE
Better database connection defaults

### ISSUE THREAD

**Issue by deas** [grafana/grafana#27647]
**What would you like to be added**:

We upgraded from grafana 6.something to 7.1.3 and we found a regression which was logging out people. We are running multiple pods on Kubernetes and the session is backed by Postgres 11. Postgres has a default connection limit of 100 and grafanas default is unlimited. We don't have detailed metrics, but production load is surely "moderate" at best.

However, once every few hours we have been encountering connection errors [wiping the session cookie](https://github.com/grafana/grafana/blob/v7.1.3/pkg/middleware/middleware.go#L217) returning 500 and logging out users:

```
t=2020-09-13T16:39:10+0200 lvl=eror msg="Failed to look up user based on cookie" logger=context error="pq: sorry, too many clients already"
t=2020-09-13T16:39:10+0200 lvl=info msg="New token" logger=context unhashed token=
```

We can reproduce the issue easily putting very high and unrealistic load on the system but please note that we also see it once every few hours with very moderate load. Appears, there is a situation causing inefficient usage of connections. We "solved" the issue using a simple limit on `max_open_conn`. There may be other factors coming into play, but just setting a default value might be an improvement already.

Below, you'll see two unrealistic executions of `ab`. The first one is with a limit of 20 connections, the second one is without a limit (default). The first one performs way better and also does not expose any errors.

## 20 connections
```
ab -n 20000 -c 500 -C grafana_session=068ddbe97f28b1841a9c2dfa566aa042 http://localhost:32785/api/org/users
This is ApacheBench, Version 2.3 <$Revision: 1843412 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 2000 requests
Completed 4000 requests
Completed 6000 requests
Completed 8000 requests
Completed 10000 requests
Completed 12000 requests
Completed 14000 requests
Completed 16000 requests
Completed 18000 requests
Completed 20000 requests
Finished 20000 requests


Server Software:        
Server Hostname:        localhost
Server Port:            32785

Document Path:          /api/org/users
Document Length:        203 bytes

Concurrency Level:      500
Time taken for tests:   11.197 seconds
Complete requests:      20000
Failed requests:        0
Total transferred:      9140000 bytes
HTML transferred:       4060000 bytes
Requests per second:    1786.14 [#/sec] (mean)
Time per request:       279.933 [ms] (mean)
Time per request:       0.560 [ms] (mean, across all concurrent requests)
Transfer rate:          797.14 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   2.7      0      36
Processing:    12  276 382.6    164    5035
Waiting:        9  276 382.6    164    5035
Total:         13  277 382.6    165    5035

Percentage of the requests served within a certain time (ms)
  50%    165
  66%    233
  75%    292
  80%    339
  90%    528
  95%    911
  98%   1600
  99%   2094
 100%   5035 (longest request)
```

## no connection limit
```
ab -n 20000 -c 500 -C grafana_session=e3af1d67e41ce96f576742e6b886c95e http://localhost:32787/api/org/users
This is ApacheBench, Version 2.3 <$Revision: 1843412 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 2000 requests
Completed 4000 requests
Completed 6000 requests
Completed 8000 requests
Completed 10000 requests
Completed 12000 requests
Completed 14000 requests
Completed 16000 requests
Completed 18000 requests
Completed 20000 requests
Finished 20000 requests


Server Software:        
Server Hostname:        localhost
Server Port:            32787

Document Path:          /api/org/users
Document Length:        210 bytes

Concurrency Level:      500
Time taken for tests:   34.793 seconds
Complete requests:      20000
Failed requests:        10608
   (Connect: 0, Receive: 0, Length: 10608, Exceptions: 0)
Non-2xx responses:      75
Total transferred:      9198822 bytes
HTML transferred:       4112725 bytes
Requests per second:    574.82 [#/sec] (mean)
Time per request:       869.837 [ms] (mean)
Time per request:       1.740 [ms] (mean, across all concurrent requests)
Transfer rate:          258.19 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    1   3.6      0      44
Processing:     2  681 1119.5    468   16522
Waiting:        2  681 1119.5    468   16522
Total:          3  682 1119.9    469   16522

Percentage of the requests served within a certain time (ms)
  50%    469
  66%    540
  75%    654
  80%   1001
  90%   1692
  95%   2442
  98%   3718
  99%   5004
 100%  16522 (longest request)
```

We used the following `docker-compose.yaml` to set up the system.

```yaml
version: "2.1"

services:
  db:
    image: postgres:11
    environment:
      POSTGRES_DATABASE: grafana
      POSTGRES_USER: grafana
      POSTGRES_PASSWORD: password
    ports:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d grafana -U grafana"]
      timeout: 10s
      retries: 10

  grafana:
    image: grafana/grafana:7.1.3
    #volumes:
    #  - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - VIRTUAL_HOST=grafana.loc
      - GF_SERVER_ROOT_URL=http://grafana.loc
      - GF_DATABASE_MAX_OPEN_CONN=20
      - GF_DATABASE_NAME=grafana
      - GF_DATABASE_USER=grafana
      - GF_DATABASE_PASSWORD=password
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=db:5432
      - GF_DATABASE_SSL_MODE=disable
      - GF_SESSION_PROVIDER=postgres
      - GF_SESSION_PROVIDER_CONFIG=user=grafana password=password host=db port=5432 dbname=grafana sslmode=disable
      - GF_SERVER_ROUTER_LOGGING=true
      - GF_LOG_CONSOLE_FORMAT=json
      - GF_LOG_FILTERS=alerting.notifier:debug,alerting.notifier.slack:debug,auth:debug
      - GF_AUTH_TOKEN_ROTATION_INTERVAL_MINUTES=2
    ports:
      - 3000
    depends_on:
      db:
        condition: service_healthy
```

**Why is this needed**:

Default experience may improve
