### ISSUE TITLE
Service init failed: Alert notification provisioning error: Alert notification name *** aleready exist

### ISSUE THREAD

**Issue by yuklia** [grafana/grafana#27903]
```
notifiers:
    - name: devops
      type: email
      uid: devops
      org_id: 2
      org_name: DevOps team
      is_default: false
      send_reminder: true
      frequency: 1h
      disable_resolve_message: false
      settings:
        addresses: ****

delete_notifiers:
    - name: devops
      uid: devops
      org_id: 2
```

**What happened**:
```
t=2020-09-29T15:59:58+0000 lvl=info msg="Deleting alert notification" logger=provisioning.notifiers name=devops uid=devops
Service init failed: Alert notification provisioning error: Alert notification name devops alerady exists
```

**What you expected to happen**:
**update** provisioned config

**Environment**:
- Grafana version: 7.1.5
- Data source type & version: Prometheus
- OS Grafana is installed on: ubuntu 18
