### ISSUE TITLE
Provisional datasource not respecting Basic Auth settings

### ISSUE THREAD

**Issue by Nkmol** [grafana/grafana#27961]
**What happened**:
When adding a provisional Datasource the "Test & Save" functionality fails with a 401 Unauthorized, because an "Authorization" header is sent.

**What you expected to happen**:
When the "basicAuth" is "false" and not enabled in the UI,  I would expect no "Authorization" header to be sent. I would even expect when "basicAuth" is not set it should default to "false".

**How to reproduce it (as minimally and precisely as possible)**:
Add the following `docker-compose`:

```
version: '3.7'

services:

  grafana:
    image: grafana/grafana:7.2.0
    environment: 
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - INFLUXDB_URL=<redacted>
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_DATABASE=test
    volumes:
      - ./datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    ports:
      - 3000:3000
```

The mounted YAML data source:

```
# config file version
apiVersion: 1

# list of data sources to insert/update depending
# what's available in the database
data sources:
  # <string, required> name of the datasource. Required
  - name: InfluxDB
    # <string, required> access mode. proxy or direct (Server or Browser in the UI). Required
    access: proxy
    # <string, required> datasource type. Required
    type: influxdb
    # <string> url
    url: ${INFLUXDB_URL}
    # <bool> enable/disable basic auth
    basicAuth: false
    # <string> database user, if used
    user: ${INFLUXDB_ADMIN_USER}
    # <string> json object of data that will be encrypted.
    secureJsonData: 
      # <string> database password, if used
      password: ${INFLUXDB_ADMIN_PASSWORD}
    # <string> database name, if used
    database: ${INFLUXDB_DATABASE}
    # <bool> enable/disable basic auth
    isDefault: true
    version: 1
    # <bool> allow users to edit datasources from the UI.
    editable: true
```

**Anything else we need to know?**:
Note that this same setup does seem to work when manually adding the same datasource. From the UI there is no difference, so I expect the YAML translation part goes wrong.

**This did work in 6.5.2**

**Environment**:
- Grafana version: 7.2
- Data source type & version: influxdb
- OS Grafana is installed on: Docker `image: grafana/grafana:7.2.0`
- User OS & Browser: Firefox MacOs

----

As a side note, the input of the BasicAuth is also not correctly used. When placing "test:test" in the BasicAuth input, I actually get a base64 result of the InfluxDB user/password. I am not sure if this is by design and is related, but a completely different issue.
