### ISSUE TITLE
Elasticsearch provisioning ignores esVersion and pattern/interval.

### ISSUE THREAD

**Issue by andrew-pickin-epi** [grafana/grafana#28063]
```
appVersion: 1

datasources:
- id: 3
  orgId: 1
  name: Elasticsearch
  type: elasticsearch
  typeLogoUrl: "public/app/plugins/datasource/elasticsearch/img/elasticsearch.svg"
  access: proxy
  url: "http://elasticsearch:9200"
  password: ""
  user: ""
  database: "[fluentd-]YYYYMMDD"
  basicAuth: false
  isDefault: false
  jsonData: 
    esVersion: "7.0+"
    interval: "Daily"
    logLevelField: ""
    logMessageField: ""
    maxConcurrentShardRequests: 5
    timeField: "@timestamp"
  readOnly: false
```

Both esVersion and interval are ignored.
