### ISSUE TITLE
Unable to set Elastic Search esVersion and pattern using Provisioning

### ISSUE THREAD

**Issue by andrew-pickin-epi** [grafana/grafana#28062]
```
appVersion: 1

datasources:
- id: 3
  orgId: 1
  name: Elasticsearch
  type: elasticsearch
  typeLogoUrl: "public/app/plugins/datasource/elasticsearch/img/elasticsearch.svg"
  access: proxy
  url: "http://elasticsearch:9200"
  password: ""
  user: ""
  database: "[fluentd-]YYYYMMDD"
  basicAuth: false
  isDefault: false
  jsonData: 
    esVersion: "7.0+"
    interval: "Daily"
    logLevelField: ""
    logMessageField: ""
    maxConcurrentShardRequests: 5
    timeField: "@timestamp"
  readOnly: false
```

Both eaVersion and Pattern are ignored.

**Comment by aocenas** [comment]
Seems like the version needs to be a string see https://github.com/grafana/grafana/issues/11126 for details.

Not sure about the pattern we will have to look at that.

**Comment by aocenas** [comment]
We may need to make the docs about how the version should be specified more clear.

**Comment by andrew-pickin-epi** [comment]
both string or integer are ignored, as is the interval

**Comment by Elfo404** [comment]
@andrew-pickin-epi I'm not able to reproduce the issue, I tried with the following configuration 

```yaml
apiVersion: 1

datasources:
  - name: Elasticsearch Provisioned
    type: elasticsearch
    access: proxy
    database: '[metrics-]YYYY.MM.DD'
    url: http://localhost:12200
    jsonData:
      interval: Hourly
      timeField: '@timestamp'
      esVersion: 70
      timeInterval: 11s
      logMessageField: logmessagefield
      logLevelField: logLevelField
      maxConcurrentShardRequests: 123
```
and everything works as expected. I'm closing this issue for now. Feel free to comment again if it is still an issue for you (including which version of Grafana you are running and in which OS).
