### ISSUE TITLE
OAuth token from auth.proxy does not forward to datasource

### ISSUE THREAD

**Issue by pantaoran** [grafana/grafana#28404]
**What happened**:
I'm deploying a Grafana instance on OpenShift with an OAuth sidecar container. That handles authentication and then forwards to Grafana. In Grafana I configured `auth.proxy` for this.
When I configure a Prometheus datasource and switch on the `Forward OAuth identity` I see the following error in the log:
`lvl=eror msg="Failed to find oauth provider with given name" logger=data-proxy-log provider=authproxy`
I do not get authenticated at the datasource.

**What you expected to happen**:
I expect that the OAuth identity which is passed to Grafana in an HTTP header is forwarded to the Prometheus datasource to authenticate me.

**How to reproduce it (as minimally and precisely as possible)**:
I'm using the following authentication settings in my Grafana:
```
    auth:
      disable_login_form: True
      disable_signout_menu: True
      oauth_auto_login: True
    auth.basic:
      enabled: False
    auth.anonymous:
      enabled: True
    auth.proxy:
      enabled: True
      header_name: X-Forwarded-User
      headers: 'Name:X-Forwarded-User Email:X-Forwarded-Email Token:X-Forwarded-Access-Token'
```

**Anything else we need to know?**:
Forwarding the OAuth identity was apparently implemented in https://github.com/grafana/grafana/pull/15205 by @seanlaff 
I was hoping that he could tell me if I misunderstand something or if this is a bug. Could it be that `auth.proxy` is not considered as a valid OAuth provider? Unfortunately I don't know anything about Go and find it too hard to understand the source code to figure it out.

**Environment**:
- Grafana version: 6.5.1
- Data source type & version: Prometheus
- OS Grafana is installed on: Alpine Linux 3.8 in a docker container provided by https://github.com/integr8ly/grafana-operator
- User OS & Browser: Windows 10 Enterprise 1809, Chrome 85.0.4183.121
- Grafana plugins: none that I know of
- Others:
