### ISSUE TITLE
trust auth proxy: allow claims consumption without doing client lookup

### ISSUE THREAD

**Issue by Morriz** [grafana/grafana#28566]
**What would you like to be added**:

The option to disable client authentication in case `auth.generic_oauth` is chosen.
This would result in no client lookup, but could still be doing a JWT validation when the shared secret is provided.

I see these options:
```yaml
auth:
  generic_oauth: true
  auth_delegated: true
  oidc:
    verify_secret: '' # if provided assume verification of the payload
```

**Why is this needed**:
Allows grafana to consume a provided trusted JWT so it can just use it's payload to map claims in `role_attribute_path`, without doing ANY oauth lookup/flows up front.

This scenario is implemented by us (and imo will become very common):

----- public boundary
1. auth-proxy (normalizing incoming JWT to have predictable claims) <--> IDP
----- service mesh
2. istio handling authn/authz targeting workloads (imo good place to deal with this to abstract away from services)
----- cluster services
3. services (like grafana) getting passthrough header `Authorization: bearer xxx` from istio to use claims
