### ISSUE TITLE
Datasource provisioning documentation for Prometheus incorrectly specifies httpMode

### ISSUE THREAD

**Issue by salekseev** [grafana/grafana#28876]
**What happened**:

Documentation at https://github.com/grafana/grafana/blob/master/docs/sources/administration/provisioning.md#json-data specifies `httpMode` is used for both InfluxDB and Prometheus but in fact it should be `httpMethod` per
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/prometheus/datasource.ts#L75.

**What you expected to happen**:

Docs need to be updated to include `httpMethod` for Prometheus

**How to reproduce it (as minimally and precisely as possible)**:

Creating a datasource according to the docs does not switch method:

```
---
apiVersion: 1
datasources:
  - access: proxy
    name: "default-kubecost"
    isDefault: false
    type: prometheus
    jsonData:
      httpMode: POST
    url: http://kubecost-prometheus-server.kubecost
```

**Environment**:
- Grafana version: v7.1.1 (3039f9c3bd)
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux
- User OS & Browser: MacOS / Chrome
- Grafana plugins: Prometheus
- Others: N/A
