### ISSUE TITLE
Unable to use Provisioning of Dashboards and Data Sources after 7.2

### ISSUE THREAD

**Issue by SuperAvarice** [grafana/grafana#28877]
**What happened**:
Provisioning of Data Sources other than orgId: 0 fails on startup.
I believe it is due to this: Provisioning: Add validation for missing organisations in datasource, dashboard, and notifier configurations. #26601
The problem is that there is no way to provision organizations before startup. I have to use the API to add the orgs, but the instance will not start.
Maybe I am doing it wrong, please suggest a better way.
I also have to add the admin user configs through the API...
As of now I am bound to v7.1.5

**What you expected to happen**:
A way provision the docker image
Possible solutions: 
 -- Revert change #26601
 -- Implement: Organisations provisioning #12119
 -- Make all the provisioning run time through the API <-- Yuck.

**How to reproduce it (as minimally and precisely as possible)**:
Provision Data Sources and/or Dashboards with organisations that do not exist before startup.

**Anything else we need to know?**:

Dockerfile:
```
ARG BASE_IMAGE
FROM $BASE_IMAGE

# Remove sample data
RUN rm -rf /etc/grafana/provisioning/datasources/sample.yaml
RUN rm -rf /etc/grafana/provisioning/dashboards/sample.yaml

# Install plugins
RUN grafana-cli plugins install grafana-piechart-panel

# Configure grafana provisioned data sources
ADD provisioning/datasources/*.yaml /etc/grafana/provisioning/datasources/

# Configure grafana pre-defined dashboards
ADD provisioning/dashboards/*.yaml /etc/grafana/provisioning/dashboards/

# Copy dashboards
ADD provisioning/dashboards/main/*.json /etc/grafana/provisioning/dashboards/main/
ADD provisioning/dashboards/admin/*.json /etc/grafana/provisioning/dashboards/admin/

```
grafana compose:
```
    grafana:
        image: "{{ grafana_name }}"
        restart: "always"
        environment:
            GF_SERVER_ROOT_URL: "{{ grafana_root_url }}"
            GF_DATABASE_TYPE: "mysql"
            GF_DATABASE_HOST: "mariadb:3306"
            GF_DATABASE_USER: "grafana"
            GF_DATABASE_PASSWORD: "{{ grafana_db_password }}"
            GF_DATABASE_MAX_IDLE_CONN: "1000"
            GF_ANALYTICS_REPORTING_ENABLED: "false"
            GF_ANALYTICS_CHECK_FOR_UPDATES: "false"
            GF_SECURITY_ADMIN_USER: "admin"
            GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_admin_password }}"
            GF_SECURITY_COOKIE_SECURE: "true"
            GF_SECURITY_COOKIE_SAMESITE: "none"
            GF_SECURITY_ALLOW_EMBEDDING: "true"
            GF_SECURITY_X_CONTENT_TYPE_OPTIONS: "false"
            GF_SECURITY_X_XSS_PROTECTION: "false"
            GF_SNAPSHOTS_EXTERNAL_ENABLED: "false"
            GF_USERS_ALLOW_SIGN_UP: "false"
            GF_AUTH_DISABLE_SIGNOUT_MENU: "true"
            GF_AUTH_OAUTH_AUTO_LOGIN: "true"
            GF_AUTH_DISABLE_LOGIN_FORM: "true"
            GF_AUTH_PROXY_ENABLED: "true"
            GF_LOG_MODE: "file"
            GF_LOG_LEVEL: "warn"
            GF_LOG_FILE_LOG_ROTATE: "true"
            GF_LOG_FILE_DAILY_ROTATE: "true"
            GF_LOG_FILE_MAX_DAYS: "10"
            GF_ALERTING_CONCURRENT_RENDER_LIMIT: "10"
            GF_RENDERING_SERVER_URL: "http://renderer:8081/render"
            GF_RENDERING_CALLBACK_URL: "http://grafana:3000/"
````

**Environment**:
- Grafana version: 7.2+
- Data source type & version: InfluxDB
- OS Grafana is installed on: Docker
- User OS & Browser: ALL
