### ISSUE TITLE
LDAP unconditionally applies an OR filter

### ISSUE THREAD

**Issue by the-maldridge** [grafana/grafana#28920]
**What happened**:
Configuring the ldap auth backend failed because my backing LDAP server does not support filter expressions of the 'or' type.

**What you expected to happen**:
I expected the filter expression I added in the config file to be used verbatim.  I did not expect an undocumented change to be made to my filter expression.

**How to reproduce it (as minimally and precisely as possible)**:
Configure ldap auth, note that the filter expression sent to the server and the filter expression in the config file do not match.

**Anything else we need to know?**:
In my environment we are not running a "real" ldap server but instead a proxy which speaks a subset of the features a real server would.  While we'll probably hack in support for this, it was confusing and took a while to figure out why grafana was not sending the exact expression from the config file.  This also limits the flexibility a little by constraining to a "match any" type of filter instead of a "match all" which would be desirable in one of my environments.

**Environment**:
- Grafana version: 7.2.2 Docker (alpine)
- Data source type & version: N/A
- OS Grafana is installed on: N/A
- User OS & Browser: N/A
- Grafana plugins: None
- Others: LDAP is configured as shown below.

```toml
[[servers]]
host = "127.0.0.1"
port = 10389
use_ssl = false
bind_dn = "uid=%s,ou=entities,dc=netauth,dc=netauth,dc=org"

search_filter = "(uid=%s)"

search_base_dns = ["ou=entities,dc=netauth,dc=netauth,dc=org"]
                                                                 
[servers.attributes]
name = "givenName"
surname = "sn"
username = "cn"
member_of = "memberOf"
email =  "email"
```

The line that causes the problem is: https://github.com/grafana/grafana/blob/master/pkg/services/ldap/ldap.go#L375

Since this appears to be related to supporting logging in with anything that matched it doesn't seem like something that can be easily changed (though this is a security posture I don't agree with), so ultimately I think the resolution to this is probably documentation, but I'd like to know what others think.
