### ISSUE TITLE
Cloudwatch plugin: "HTTP Error Internal Server Error"

### ISSUE THREAD

**Issue by krafty1010** [grafana/grafana#28989]
- Grafana v6.2.5 (6082d19)
- Running on RHEL 7.9 EC2 instance (in account 1234567890)
- IAM role assigned to the EC2 instance. From this it is possible assume role arn:aws:iam::1234567890:role/xxx_grafana_role. This role can access Cloudwatch metrics. This has been tested using the aws cli on the EC2 instance; it is possible from the instance role to assume xxx_grafana_role and query cloudwatch
- HTTP proxy access required to access AWS endpoints

Cloudwatch plugin provisioned using;

```
# config file version
apiVersion: 1

#cloudwatch local
  - name: CloudWatch-tst
    type: cloudwatch
    jsonData:
      authType: arn
      assumeRoleArn: arn:aws:iam::1234567890:assumed-role/xxx_grafana_role
      defaultRegion: eu-west-1
```

After an instance reboot the plugin fails;

![image](https://user-images.githubusercontent.com/24271977/98686071-0a34d800-2360-11eb-901d-6a37a1a699cb.png)

log entries;

```
t=2020-11-10T14:02:47+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=0.0.0.0:5401 protocol=http subUrl= socket=
t=2020-11-10T14:05:42+0000 lvl=eror msg="Metric request error" logger=context userId=10 orgId=1 uname=0000000 error="Failed to call ec2:getAwsConfig, NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"
t=2020-11-10T14:05:42+0000 lvl=eror msg="Request Completed" logger=context userId=10 orgId=1 uname=0000000 method=POST path=/api/tsdb/query status=500 remote_addr=10.x.x.x time_ms=95 size=34 referer=https://dashboard.cloud.dev.net/datasources/edit/37/
t=2020-11-10T14:05:52+0000 lvl=eror msg="Metric request error" logger=context userId=10 orgId=1 uname=0000000 error="NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"
t=2020-11-10T14:05:52+0000 lvl=eror msg="Request Completed" logger=context userId=10 orgId=1 uname=0000000 method=POST path=/api/tsdb/query status=500 remote_addr=10.x.x.x time_ms=42 size=34 referer=https://dashboard.cloud.dev.net/datasources/edit/37/
```

At a loss here. The error points to credential issues but as mentioned I have been able to test the ARN access using aws cli. Thanks!
