### ISSUE TITLE
Provisioning: application is not pinned to the sidebar

### ISSUE THREAD

**Issue by alexanderzobnin** [grafana/grafana#29058]
**What happened**:
When using provisioning with an application that has already being installed, but was disabled manually, it's going to be enabled, but not pinned to the sidebar.

**What you expected to happen**:
Application is enabled and pinned to the sidebar.

**How to reproduce it (as minimally and precisely as possible)**:
1. Install application.
1. Go to the app config page in Grafana.
1. Enable it. App should be pinned to the sidebar (if it's a feature of the app).
1. Disable app. 
1. Add app provisioning config, like:
    ```yaml
    apps:
      - type: grafana-synthetic-monitoring-app
        disabled: false
    ```
1. Restart grafana server.
1. Reload app config page. App is enabled, but not pinned to the sidebar.

**Anything else we need to know?**:
This happens because of this line:
https://github.com/grafana/grafana/blob/a1e80af800f04d70d28deb9793d73ce55796b7f8/pkg/services/provisioning/plugins/plugin_provisioner.go#L50
If plugin config found in Grafana DB, then `Pinned` property will be always given from that config. But if app is disabled, then `Pinned` is usually `false` (I can say it's false in 99% cases, since if we disable app, then we want to remove it from the sidebar as well, so we set `pinned` to `false` in the query).

I think there're 2 possible solutions:
1. Set `Pinned` to `true` if we enable app via provisioning (`disabled: false`).
1. Add `pinned` option to the provisioning conf (probably, with default set to `false` or using `disabled` style - name it `unpinned`):
    ```yaml
    apps:
      - type: grafana-synthetic-monitoring-app
        disabled: false
        pinned: true
    ```

**Environment**:
- Grafana version: latest master (7.4.0-pre)
- Data source type & version: Synthetic Monitoring app (or any other app that appears on the sidebar)
- OS Grafana is installed on: 
- User OS & Browser:
- Grafana plugins:
- Others:
