### ISSUE TITLE
Grafana container unable to use mysql as backend database

### ISSUE THREAD

**Issue by rlenferink** [grafana/grafana#29127]
**What happened**:
I am trying to start grafana as container with mysql as database type. I created a docker-compose.yml file for setting up grafana and mysql. See the following:

```yaml
[root@monitoring-vm1 ~]# cat docker-compose/grafana/docker-compose.yml
version: "3"

networks:
  grafana:

services:
  grafana:
    image: grafana/grafana:7.3.2
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      GF_SECURITY_ADMIN_USER: <snip>
      GF_SECURITY_ADMIN_PASSWORD__FILE: /etc/grafana/admin_password
      GF_DATABASE_TYPE: mysql
      GF_DATABASE_HOST: db:3306
      GF_DATABASE_NAME: grafana_db
      GF_DATABASE_USER: grafana_db_user
      GF_DATABASE_PASSWORD: <snip>
    volumes:
      - ./admin_password:/etc/grafana/admin_password
      - /data/grafana/data:/var/lib/grafana
    networks:
      grafana:

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: <snip>
      MYSQL_USER: grafana_db_user
      MYSQL_PASSWORD: <snip>
      MYSQL_DATABASE: grafana_db
    expose:
      - "3306"
    volumes:
      - /data/mysql/data:/var/lib/mysql
    networks:
      grafana:
```

Using docker logs it unfortunately says the following:

```bash
EROR[11-15|13:09:15] Server shutdown                          logger=server reason="Service init failed: migration failed: failed to check table existence: dial tcp 172.30.0.2:3306: connect: no route to host"
Service init failed: migration failed: failed to check table existence: dial tcp 172.30.0.2:3306: connect: no route to host
```

**What you expected to happen**:
I expected that Grafana would start using the mysql database.

**How to reproduce it (as minimally and precisely as possible)**:

Use the following docker-compose configuration and call `docker-compose up -d` (note that the entrypoint is overridden)

```yaml
version: "3"

networks:
  grafana:

services:
  grafana:
    image: grafana/grafana:7.3.2
    command: /bin/sh -c "while true; do sleep 2; done"
    entrypoint: /bin/sh -c "while true; do sleep 2; done"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      GF_SECURITY_ADMIN_USER: admin_user
      GF_SECURITY_ADMIN_PASSWORD: admin_password
      GF_DATABASE_TYPE: mysql
      GF_DATABASE_HOST: db:3306
      GF_DATABASE_NAME: grafana_db
      GF_DATABASE_USER: grafana_db_user
      GF_DATABASE_PASSWORD: grafana_password
    networks:
      grafana:

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: grafana_password
      MYSQL_USER: grafana_db_user
      MYSQL_PASSWORD: grafana_password
      MYSQL_DATABASE: grafana_db
    expose:
      - "3306"
    networks:
      grafana:
```

After that the containers are started. Use `docker-compose exec -u 0 grafana /bin/bash` to get a shell in the container.

Executing grafana results in an error now. I used ping to verify that `db` resolves from within the container:

```bash
[root@monitoring-vm1 grafana]# docker-compose exec -u 0 grafana /bin/bash
bash-5.0# ./bin/grafana-server
INFO[11-15|13:18:09] Starting Grafana                         logger=server version=7.3.2 commit=b8ad4eaab3 branch=HEAD compiled=2020-11-11T13:20:01+0000
INFO[11-15|13:18:09] Config loaded from                       logger=settings file=/usr/share/grafana/conf/defaults.ini
INFO[11-15|13:18:09] Config overridden from Environment variable logger=settings var="GF_PATHS_DATA=/var/lib/grafana"
INFO[11-15|13:18:09] Config overridden from Environment variable logger=settings var="GF_PATHS_LOGS=/var/log/grafana"
INFO[11-15|13:18:09] Config overridden from Environment variable logger=settings var="GF_PATHS_PLUGINS=/var/lib/grafana/plugins"
INFO[11-15|13:18:09] Config overridden from Environment variable logger=settings var="GF_PATHS_PROVISIONING=/etc/grafana/provisioning"
INFO[11-15|13:18:09] Config overridden from Environment variable logger=settings var="GF_DATABASE_TYPE=mysql"
INFO[11-15|13:18:09] Config overridden from Environment variable logger=settings var="GF_DATABASE_HOST=db:3306"
INFO[11-15|13:18:09] Config overridden from Environment variable logger=settings var="GF_DATABASE_NAME=grafana_db"
INFO[11-15|13:18:09] Config overridden from Environment variable logger=settings var="GF_DATABASE_USER=grafana_db_user"
INFO[11-15|13:18:09] Config overridden from Environment variable logger=settings var="GF_DATABASE_PASSWORD=*********"
INFO[11-15|13:18:09] Config overridden from Environment variable logger=settings var="GF_SECURITY_ADMIN_USER=admin_user"
INFO[11-15|13:18:09] Path Home                                logger=settings path=/usr/share/grafana
INFO[11-15|13:18:09] Path Data                                logger=settings path=/var/lib/grafana
INFO[11-15|13:18:09] Path Logs                                logger=settings path=/var/log/grafana
INFO[11-15|13:18:09] Path Plugins                             logger=settings path=/var/lib/grafana/plugins
INFO[11-15|13:18:09] Path Provisioning                        logger=settings path=/etc/grafana/provisioning
INFO[11-15|13:18:09] App mode production                      logger=settings
INFO[11-15|13:18:09] Connecting to DB                         logger=sqlstore dbtype=mysql
INFO[11-15|13:18:09] Starting DB migrations                   logger=migrator
EROR[11-15|13:18:10] Server shutdown                          logger=server reason="Service init failed: migration failed: failed to check table existence: dial tcp 172.30.0.2:3306: connect: no route to host"
Service init failed: migration failed: failed to check table existence: dial tcp 172.30.0.2:3306: connect: no route to host
bash-5.0# ping db
PING db (172.30.0.2): 56 data bytes
64 bytes from 172.30.0.2: seq=0 ttl=64 time=0.120 ms
64 bytes from 172.30.0.2: seq=1 ttl=64 time=0.112 ms
64 bytes from 172.30.0.2: seq=2 ttl=64 time=0.101 ms
64 bytes from 172.30.0.2: seq=3 ttl=64 time=0.106 ms
^C
--- db ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max = 0.101/0.109/0.120 ms
bash-5.0#
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: grafana/grafana:7.3.2
- Data source type & version: mysql:5.7
- OS Grafana is installed on: CentOS 8
- User OS & Browser: Windows 10 with Firefox
- Grafana plugins: Don't know => the default that ships with the container image
- Others:

**Comment by aknuds1** [comment]
I think something must be going wrong in your Docker Compose setup (if Grafana can't reach the database server, as in your error, it should also be an issue on the Docker level, not within Grafana). I adjusted your second docker-compose.yml to start Grafana, and it works for me without any issues:

```
version: "3"

networks:
  grafana:

services:
  grafana:
    image: grafana/grafana:7.3.2
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      GF_SECURITY_ADMIN_USER: admin_user
      GF_SECURITY_ADMIN_PASSWORD: admin_password
      GF_DATABASE_TYPE: mysql
      GF_DATABASE_HOST: db:3306
      GF_DATABASE_NAME: grafana_db
      GF_DATABASE_USER: grafana_db_user
      GF_DATABASE_PASSWORD: grafana_password
    networks:
      grafana:

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: grafana_password
      MYSQL_USER: grafana_db_user
      MYSQL_PASSWORD: grafana_password
      MYSQL_DATABASE: grafana_db
    expose:
      - "3306"
    networks:
      grafana:
```

My `docker-compose up` output looks as follows: 

```
✗ docker-compose up
Starting grafana_db_1 ... done
Starting grafana_grafana_1 ... done
Attaching to grafana_db_1, grafana_grafana_1
db_1       | 2020-11-15 13:52:00+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.32-1debian10 started.
db_1       | 2020-11-15 13:52:00+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
db_1       | 2020-11-15 13:52:00+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.32-1debian10 started.
db_1       | 2020-11-15T13:52:00.961008Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
db_1       | 2020-11-15T13:52:00.961676Z 0 [Note] mysqld (mysqld 5.7.32) starting as process 1 ...
db_1       | 2020-11-15T13:52:00.963055Z 0 [Note] InnoDB: PUNCH HOLE support available
db_1       | 2020-11-15T13:52:00.963063Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1       | 2020-11-15T13:52:00.963065Z 0 [Note] InnoDB: Uses event mutexes
db_1       | 2020-11-15T13:52:00.963066Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
db_1       | 2020-11-15T13:52:00.963068Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
db_1       | 2020-11-15T13:52:00.963069Z 0 [Note] InnoDB: Using Linux native AIO
db_1       | 2020-11-15T13:52:00.963178Z 0 [Note] InnoDB: Number of pools: 1
db_1       | 2020-11-15T13:52:00.963223Z 0 [Note] InnoDB: Using CPU crc32 instructions
db_1       | 2020-11-15T13:52:00.963958Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
db_1       | 2020-11-15T13:52:00.968007Z 0 [Note] InnoDB: Completed initialization of buffer pool
db_1       | 2020-11-15T13:52:00.968909Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
db_1       | 2020-11-15T13:52:00.979800Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
db_1       | 2020-11-15T13:52:00.990273Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1       | 2020-11-15T13:52:00.990300Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1       | 2020-11-15T13:52:01.006001Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1       | 2020-11-15T13:52:01.006361Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
db_1       | 2020-11-15T13:52:01.006365Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
db_1       | 2020-11-15T13:52:01.006584Z 0 [Note] InnoDB: Waiting for purge to start
db_1       | 2020-11-15T13:52:01.056701Z 0 [Note] InnoDB: 5.7.32 started; log sequence number 14921711
db_1       | 2020-11-15T13:52:01.056863Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1       | 2020-11-15T13:52:01.057018Z 0 [Note] Plugin 'FEDERATED' is disabled.
db_1       | 2020-11-15T13:52:01.059005Z 0 [Note] InnoDB: Buffer pool(s) load completed at 201115 13:52:01
db_1       | 2020-11-15T13:52:01.061876Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
db_1       | 2020-11-15T13:52:01.061889Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
db_1       | 2020-11-15T13:52:01.062413Z 0 [Warning] CA certificate ca.pem is self signed.
db_1       | 2020-11-15T13:52:01.062436Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
db_1       | 2020-11-15T13:52:01.062811Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
db_1       | 2020-11-15T13:52:01.062838Z 0 [Note] IPv6 is available.
db_1       | 2020-11-15T13:52:01.062848Z 0 [Note]   - '::' resolves to '::';
db_1       | 2020-11-15T13:52:01.062860Z 0 [Note] Server socket created on IP: '::'.
db_1       | 2020-11-15T13:52:01.065934Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
db_1       | 2020-11-15T13:52:01.073999Z 0 [Note] Event Scheduler: Loaded 0 events
db_1       | 2020-11-15T13:52:01.074188Z 0 [Note] mysqld: ready for connections.
db_1       | Version: '5.7.32'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
grafana_1  | t=2020-11-15T13:52:01+0000 lvl=info msg="Starting Grafana" logger=server version=7.3.2 commit=b8ad4eaab3 branch=HEAD compiled=2020-11-11T13:20:01+0000
grafana_1  | t=2020-11-15T13:52:01+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
grafana_1  | t=2020-11-15T13:52:01+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
grafana_1  | t=2020-11-15T13:52:01+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
grafana_1  | t=2020-11-15T13:52:01+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
grafana_1  | t=2020-11-15T13:52:01+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
grafana_1  | t=2020-11-15T13:52:01+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"
grafana_1  | t=2020-11-15T13:52:01+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.log.mode=console"
grafana_1  | t=2020-11-15T13:52:01+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_DATA=/var/lib/grafana"
grafana_1  | t=2020-11-15T13:52:01+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_LOGS=/var/log/grafana"
grafana_1  | t=2020-11-15T13:52:01+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_PLUGINS=/var/lib/grafana/plugins"
grafana_1  | t=2020-11-15T13:52:01+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_PROVISIONING=/etc/grafana/provisioning"
grafana_1  | t=2020-11-15T13:52:01+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_DATABASE_TYPE=mysql"
grafana_1  | t=2020-11-15T13:52:01+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_DATABASE_HOST=db:3306"
grafana_1  | t=2020-11-15T13:52:01+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_DATABASE_NAME=grafana_db"
grafana_1  | t=2020-11-15T13:52:01+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_DATABASE_USER=grafana_db_user"
grafana_1  | t=2020-11-15T13:52:01+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_DATABASE_PASSWORD=*********"
grafana_1  | t=2020-11-15T13:52:01+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_SECURITY_ADMIN_USER=admin_user"
grafana_1  | t=2020-11-15T13:52:01+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_SECURITY_ADMIN_PASSWORD=*********"
grafana_1  | t=2020-11-15T13:52:01+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
grafana_1  | t=2020-11-15T13:52:01+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
grafana_1  | t=2020-11-15T13:52:01+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
grafana_1  | t=2020-11-15T13:52:01+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
grafana_1  | t=2020-11-15T13:52:01+0000 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning
grafana_1  | t=2020-11-15T13:52:01+0000 lvl=info msg="App mode production" logger=settings
grafana_1  | t=2020-11-15T13:52:01+0000 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=mysql
grafana_1  | t=2020-11-15T13:52:01+0000 lvl=info msg="Starting DB migrations" logger=migrator
grafana_1  | t=2020-11-15T13:52:01+0000 lvl=info msg="Starting plugin search" logger=plugins
grafana_1  | t=2020-11-15T13:52:01+0000 lvl=info msg="Registering plugin" logger=plugins id=input
grafana_1  | t=2020-11-15T13:52:01+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=
grafana_1  | t=2020-11-15T13:52:21+0000 lvl=eror msg="Failed to look up user based on cookie" logger=context error="user token not found"
grafana_1  | t=2020-11-15T13:52:21+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=172.20.0.1 time_ms=0 size=29 referer=
```

Closing this issue since it doesn't appear to be a Grafana bug. If you need further support, I would recommend you use our community [forums](http://community.grafana.com) or [Slack](http://slack.raintank.io) since we use GitHub for bug reports and feature requests.
