### ISSUE TITLE
can't start Grafana v7.3.0 on Synology

### ISSUE THREAD

**Issue by schel4ok** [grafana/grafana#29170]
**Given Docker compose file**
```
version: '3.5'
services:

  grafana:
    container_name: grafana
    image: grafana/grafana
    environment:
      TZ: "Europe/Moscow"
    volumes:
      - /volume3/Documents/server/smarthome/grafana:/var/lib/grafana
      - /usr/syno/etc/certificate/_archive/aTWviv:/var/ssl 
    ports:
      - "3000:3000"
    user: "472:472"
    restart: always
    networks:
      - smarthome

networks:
  smarthome:
    name: smarthome
    driver: bridge
```
Setup permissions for grafana folder and run docker compose:
```
chown -R 472:472 /volume3/Documents/server/smarthome/grafana
docker-compose up -d
```

**What happened**:
```
GF_PATHS_DATA='/var/lib/grafana' is not writable.,
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later,
mkdir: can't create directory '/var/lib/grafana/plugins': Permission denied,
```
Here https://community.grafana.com/t/new-docker-install-with-persistent-storage-permission-problem/10896 everybody solved issue with chown 472:472 command, but it doesn't help me.

**How to reproduce it (as minimally and precisely as possible)**:
Just run above docker compose file on Synology

**Environment**:
- Grafana version: latest (I suppose v7.3.0)
- Data source type & version: https://registry.hub.docker.com/r/grafana/grafana/
- OS Grafana is installed on: DSM 6.2.3-25426 update 2
