### ISSUE TITLE
DNS names not resolved when using the Docker version with docker-compose

### ISSUE THREAD

**Issue by BlueskyFR** [grafana/grafana#29192]
**What happened**:

Here is my docker-compose file:
```yml
version: "3.8"

services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana-storage:/var/lib/grafana
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel, grafana-piechart-panel"
    user: "${USER_ID}"
    depends_on:
      - prometheus
    restart: unless-stopped
  
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    user: "${USER_ID}"
    restart: unless-stopped
```

So it is a pretty simple/basic compose file. Docker-compose automatically creates an internal network BUT, when specifying `http://prometheus:9090` as the data source, I get an **HTTP Error not found** error in Grafana:
![image](https://user-images.githubusercontent.com/25421460/99512983-687a4000-298a-11eb-8798-8c6397d3320b.png)

This obviously shouldn't happen as the request is made by the Grafana server. If I replace the url by my host's public one it works, but the DNS name should be handled and resolved anyway.
The ports are opened, everything is up and running: the only problem is the name resolution.
I am using the Alpine version of the Grafana Docker image.

**What you expected to happen**:

`http://prometheus:9090` to be resolved as it should.

**How to reproduce it (as minimally and precisely as possible)**:

Just create a `docker-compose.yml` and run `docker-compose up -d`, then create a new prometheus data source, specify `http://prometheus:9090` as the url and it should fail.

**Environment**:
- Grafana version: latest
- Data source type & version: latest
- OS Grafana is installed on: Docker (Alpine)
- User OS & Browser: Manjaro/Vivaldi

**Comment by papagian** [comment]
I'm unable to reproduce it in my environment (host OS mac OS X). I suspect that this related to [this](https://github.com/docker/compose/issues/7638) docker-compose issue when running in Manjaro.

**Comment by BlueskyFR** [comment]
> I'm unable to reproduce it in my environment (host OS mac OS X). I suspect that this related to [this](https://github.com/docker/compose/issues/7638) docker-compose issue when running in Manjaro.

The container is running on a distant Ubuntu server

**Comment by BlueskyFR** [comment]
@papagian can you please re-open?

**Comment by papagian** [comment]
> The container is running on a distant Ubuntu server

do you mean that the docker container host is different from where the browser is running?

**Comment by BlueskyFR** [comment]
> > The container is running on a distant Ubuntu server
> 
> do you mean that the docker container host is different from where the browser is running?

Yes that was dumb from me to put my OS's specs since I do everything remotely (ssh) on a distant Ubuntu server.
Please ignore the Manjaro/Vivaldi specs, the server is running Ubuntu 20.04.

**Comment by papagian** [comment]
What is the datasource [access](https://grafana.com/docs/grafana/latest/datasources/prometheus/#prometheus-settings) type (Server or Browser)?

**Comment by BlueskyFR** [comment]
> What is the datasource [access](https://grafana.com/docs/grafana/latest/datasources/prometheus/#prometheus-settings) type (Server or Browser)?

Server

**Comment by mindon** [comment]
```yaml
version: '3.9'
services:
    a:
        entrypoint: ["ping", "a-service"]
        image: library/busybox
        container_name: a-service
        hostname: a-service
        networks:
             - share-net
        depends_on:
             b:
                 condition: service_started
        #links:
        #    - b:b-service
    b:
        entrypoint: ["ping", "b-service"]
        image: library/busybox
        container_name: b-service
        hostname: b-service
        networks:
             - share-net

networks:
     share-net:
          external: true
```

`docker exec a-service ping b-service `
got "ping: bad address 'b-service'"

`docker exec a-service ping  172.18.0.5`
it's ok (networks no problem):
PING 172.18.0.5 (172.18.0.5): 56 data bytes
64 bytes from 172.18.0.5: seq=0 ttl=64 time=0.140 ms

`docker exec a-service nslookup b-service `
got "nslookup: write to '127.0.0.11': Connection refused"

`docker exec a-service more /etc/hosts`
found 172.18.0.6      a-service, but no entry for b-service

the internal container service names resolve failed:
**dsn not working, no hosts entry appended**

it doesn't work either with links.

docker-compose version 1.28.0
Docker version 19.03.6
