### ISSUE TITLE
LogQL metric query [Interval] returns no data when it is expected to do so

### ISSUE THREAD

**Issue by pcbl** [grafana/grafana#29210]
**Describe the bug**
I am using Loki 1.6.1 and am having an unexpected behavior. We are building some Grafana Dashboards with Loki data, and one of the Dashboard elements is a chart that shows log entries over time , grouped by level.

To achieve that, I have a very simple query:

`sum(count_over_time({ServiceName=~"DataService"}[$__interval])) by(Level)`

The $__interval is calculated by Grafana by dividing the "Max data points" by the "time range".

I defined a Range which certainly has few Long entries, given my criteria.

What I noticed is that depending of the $__interval calculated value, loki does not return data:

- **100ms**: No data is returned
- **1s**: Data is returned

As far as I can understand, when I have a query like this:
`sum(count_over_time({ServiceName=~"DataService"}[100ms])) by(Level)`
I should get a sum of log entries grouped by level, every 100ms, given my Time range.

`sum(count_over_time({ServiceName=~"DataService"}[1s])) by(Level)`
I should get a sum of log entries grouped by level, every 1s, given my Time range.

On Both cases, I am using exactly the same Time Range, but when I have 1s I get data from loki, but on 100ms I get no data.

**Expected behavior**
On Both cases I expect that some data is returned, as I am sure there is data on Loki that matches the criteria.

Could you guys share some light? I believe that I might have some setting wrongly configured?

My Loki settings:
```yaml
auth_enabled: false

server:
  http_listen_port: 22222
  log_level: 'debug'

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

schema_config:
  configs:
  - from: 2018-04-15
    store: boltdb
    object_store: filesystem
    schema: v11
    index:
      prefix: index_
      period: 168h      
    
storage_config:
  boltdb:
    directory: C:\LokiBackup\Loki_Bkp_2020.08.19__10_11_55\index
  filesystem:
    directory: C:\LokiBackup\Loki_Bkp_2020.08.19__10_11_55\chunks

limits_config:
  enforce_metric_name: false
```

Thanks in advance!
