### ISSUE TITLE
SigV4 Elasticsearch external datasource not reachable and not properly initialized

### ISSUE THREAD

**Issue by clementlesne** [grafana/grafana#29439]
**What happened**: I am using a yaml datasource for Elasticsearch hosted on AWS with SigV4. Each time Grafana starts, my datasource is ingested. But I cannot use it or fetch any data through it. In the options panel, the parameter "SigV4 auth" is disabled.

Like this: https://ibb.co/n7S2c4t

**What you expected to happen**: I except the auth option "SigV4 auth" to be enabled when SigV4 credentials are defined.

What I expect is: https://ibb.co/7R3v8dG

**How to reproduce it (as minimally and precisely as possible)**:

1. Create an AWS Elasticsearch

2. In AWS, create an IAM user and associated role

3. Create an external datasource file with this configuration and complete with your AWS creds:

```yaml
apiVersion: 1

deleteDatasources:
  - name: ELK (eu-central-1)
    orgId: 1

datasources:
- name: ELK (eu-central-1)
  type: elasticsearch
  access: proxy
  database: "[logs.default.]YYYY.MM.DD"
  url: https://vpc-xxx.eu-central-1.es.amazonaws.com
  jsonData:
    esVersion: 70
    timeField: "@timestamp"
    interval: Daily
    logMessageField: message
    logLevelField: fields.level
    sigV4AuthType: keys
    sigV4AssumeRoleArn: arn:aws:iam::xxx:role/xxx-grafana
    sigV4Region: eu-central-1
  secureJsonData:
    sigV4AccessKey: xxx
    sigV4SecretKey: xxx
  orgId: 1
  editable: false
```

4. Start Grafana and see the datasource configuration, the option "SigV4 auth" is disabled

**Other things we need to know:**

- I use an Amazon Elasticsearch behind a private VPC endpoint

**Environment**:
- Grafana version:v7.3.3 (2489dc4d3a)
- Data source type & version: Elasticsearch bundled with Grafana
- OS Grafana is installed on: RedHat UBI 8.2
- User OS & Browser: Firefox, MacOS
- Grafana plugins: petrslavotinek-carpetplot-panel v0.1.1, grafana-clock-panel v1.1.1, jdbranham-diagram-panel v1.7.1, grafana-piechart-panel v1.6.1, natel-plotly-panel v0.0.6, vonage-status-panel v1.0.10, flant-statusmap-panel v0.3.4, 
- Others: Elasticsearch 7.8, grafana-worldmap-panel v0.3.2
