### ISSUE TITLE
Provisioning templated dashboard with variables doesn't work

### ISSUE THREAD

**Issue by dpostolovski** [grafana/grafana#29636]
**What happened**:
I am provisioning data sources and dashboards through file providers. Data-sources are provisioned fine (PostgreSQL, grafana-simple-json-datasource), but dashboards that include variables that depend on a provisioned data source does not work.
When loading the dashboard in browser, an error appears: 

```
Templating [id]
Error updating options: Datasource named ${DS_POSTGRESQL} was not found
```
The error only appears for the variable data-source. Panel data-sources work fine. Another data-source has been tried, and it doesn't work, although it can be successfully used in the panels. 

**What you expected to happen**:

Dashboard is initialized successfully without an error.

**How to reproduce it (as minimally and precisely as possible)**:

data source provider (tsdb.yaml):
```
# config file version
apiVersion: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:
  # <string, required> name of the datasource. Required
  - name: TSDB
    # <string, required> datasource type. Required
    type: postgres
    # <string, required> access mode. proxy or direct (Server or Browser in the UI). Required
    access: proxy
    # <int> org id. will default to orgId 1 if not specified
    orgId: 1
    # <string> custom UID which can be used to reference this datasource in other parts of the configuration, if not specified will be generated automatically
    uid: tsdb_solardata
    # <string> url
    url: ${TSDB_HOST}:5432
    # <string> Deprecated, use secureJsonData.password
    password:
    # <string> database user, if used
    user: ${TSDB_USER}
    # <string> database name, if used
    database: ${TSDB_DATABASE}
    # <bool> enable/disable basic auth
    basicAuth: false
    # <string> basic auth username
    basicAuthUser: false
    # <string> Deprecated, use secureJsonData.basicAuthPassword
    basicAuthPassword: false
    # <bool> enable/disable with credentials headers
    withCredentials: false
    # <bool> mark as default datasource. Max one per org
    isDefault: true
    # <map> fields that will be converted to json and stored in jsonData
    jsonData:
      postgresVersion: 1000
      sslmode: "disable"
      timescaledb: true
    # <string> json object of data that will be encrypted.
    secureJsonData:
      # <string> database password, if used
      password: ${TSDB_PASSWORD}
    version: 2
    # <bool> allow users to edit datasources from the UI.
    editable: false

```

Dashboard YAML:

```
{
  "__inputs": [
    {
      "name": "DS_POSTGRESQL",
      "label": "PostgreSQL",
      "description": "",
      "type": "datasource",
      "pluginId": "postgres",
      "pluginName": "PostgreSQL"
    }
  ],
  "__requires": [
    {
      "type": "panel",
      "id": "gauge",
      "name": "Gauge",
      "version": ""
    },
    {
      "type": "grafana",
      "id": "grafana",
      "name": "Grafana",
      "version": "7.3.4"
    },
    {
      "type": "datasource",
      "id": "postgres",
      "name": "PostgreSQL",
      "version": "1.0.0"
    }
  ],
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": null,
  "iteration": 1607201148960,
  "links": [],
  "panels": [
    {
      "cacheTimeout": null,
      "datasource": "${DS_POSTGRESQL}",
      "fieldConfig": {
        "defaults": {
          "custom": {},
          "mappings": [
            {
              "id": 0,
              "op": "=",
              "text": "N/A",
              "type": 1,
              "value": "null"
            }
          ],
          "nullValueMode": "connected",
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          },
          "unit": "watth"
        },
        "overrides": []
      },
      "gridPos": {
        "h": 5,
        "w": 4,
        "x": 0,
        "y": 0
      },
      "id": 13,
      "links": [],
      "options": {
        "orientation": "horizontal",
        "reduceOptions": {
          "calcs": [
            "sum"
          ],
          "fields": "",
          "values": false
        },
        "showThresholdLabels": false,
        "showThresholdMarkers": true
      },
      "pluginVersion": "7.3.4",
      "targets": [
        {
          "format": "time_series",
          "group": [],
          "metricColumn": "none",
          "rawQuery": false,
          "rawSql": "SELECT\n  datetime AS \"time\",\n  \"FromGenToGrid\"\nFROM tsdb_energy\nWHERE\n  $__timeFilter(datetime) AND\n  id = $id\nORDER BY 1",
          "refId": "A",
          "select": [
            [
              {
                "params": [
                  "\"FromGenToGrid\""
                ],
                "type": "column"
              }
            ]
          ],
          "table": "tsdb_energy",
          "timeColumn": "datetime",
          "timeColumnType": "timestamp",
          "where": [
            {
              "name": "$__timeFilter",
              "params": [],
              "type": "macro"
            },
            {
              "datatype": "int4",
              "name": "",
              "params": [
                "id",
                "=",
                "$id"
              ],
              "type": "expression"
            }
          ]
        }
      ],
      "timeFrom": null,
      "timeShift": null,
      "title": "From PV To Grid",
      "type": "gauge"
    }
  ],
  "refresh": false,
  "schemaVersion": 26,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": [
      {
        "allValue": null,
        "current": {},
        "datasource": "${DS_POSTGRESQL}",
        "definition": "SELECT distinct(id) from tsdb_energy;",
        "error": null,
        "hide": 0,
        "includeAll": false,
        "label": "System",
        "multi": false,
        "name": "id",
        "options": [],
        "query": "SELECT distinct(id) from tsdb_energy;",
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "sort": 1,
        "tagValuesQuery": "",
        "tags": [],
        "tagsQuery": "",
        "type": "query",
        "useTags": false
      }
    ]
  },
  "time": {
    "from": "now-8d",
    "to": "now-2d"
  },
  "timepicker": {
    "nowDelay": "24h",
    "refresh_intervals": [
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ]
  },
  "timezone": "utc",
  "title": "System Metrics Copy",
  "uid": "aJrEiCAMz",
  "version": 3
}
```

docker-compose.yml 

```
grafana:
    image: grafana/grafana:7.3.4
    restart: always
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=petrslavotinek-carpetplot-panel,grafana-simple-json-datasource
      - TSDB_HOST=${TSDB_HOST}
      - TSDB_USER=${TSDB_USER}
      - TSDB_PASSWORD=${TSDB_PASSWORD}
      - TSDB_DATABASE=${TSDB_DATABASE}
      - DS_POSTGRESQL=TSDB
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.4
- Data source type & version: PostgreSQL, but tried with another data-source with same results.
- OS Grafana is installed on: Grafana docker image.
- User OS & Browser: Windows 10, Firefox 83.0 (64-bit) and Chrome Version 87.0.4280.88
- Grafana plugins: petrslavotinek-carpetplot-panel,grafana-simple-json-datasource
- Others: Postgres with TimescaleDB, but irrelevant for this bug.

**Comment by dpostolovski** [comment]
After more careful observation, although the other panels do not throw up an error in the form of a notification, the data source can not be configured correctly to display the data:
![Capture](https://user-images.githubusercontent.com/43391137/101412963-bfb56580-38e3-11eb-82a0-2c520abd2454.PNG)

Maybe I am doing something wrong?

**Comment by hugohaggmark** [comment]
Sorry for the late response @dpostolovski but have you tried to use `"datasource": "TSDB"` instead of `"datasource": "${DS_POSTGRESQL}"`?

**Comment by dpostolovski** [comment]
@hugohaggmark Yes, that works. But it isn't ideal thing for templating.

**Comment by dprokop** [comment]
@dpostolovski question- are you expecting your env variables to be used by the privisioned dashboard json? I've just noticed this in the issue description:

```
grafana:
    image: grafana/grafana:7.3.4
    restart: always
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=petrslavotinek-carpetplot-panel,grafana-simple-json-datasource
      - TSDB_HOST=${TSDB_HOST}
      - TSDB_USER=${TSDB_USER}
      - TSDB_PASSWORD=${TSDB_PASSWORD}
      - TSDB_DATABASE=${TSDB_DATABASE}
      - DS_POSTGRESQL=TSDB
```

If so, then it will not work. Please take a look at the documentation here https://grafana.com/docs/grafana/latest/administration/provisioning/#using-environment-variables. You can use env variables in the YML files, but you are trying to do that in the provisioned dashboard json file.

For an example of a provisioned dashboard you can have a look here: https://github.com/grafana/grafana/blob/master/devenv/dev-dashboards/datasource-elasticsearch/elasticsearch_v7.json
