### ISSUE TITLE
Can't enable skip tls verify using datasource.yml in docker-compose

### ISSUE THREAD

**Issue by ThomasGeor** [grafana/grafana#29785]
https://github.com/grafana/grafana/blob/2c7adccf12c8620d37dd4e9cef7d31b2d0de175d/pkg/models/datasource_cache.go#L50

**What happened**:
I am running grafana - influxdb and telegraf using docker-compose. I want to create  an influxdb datasource on startup for grafana. 
To do that, i am mounting a grafana provisioning folder copied from /etc/grafana/provisioning.
![image](https://user-images.githubusercontent.com/26853955/101947266-1ffc1e00-3be8-11eb-9113-d70f2a298e9b.png)

Running the docker-compose, influxdb-grafana and telegraf run ok.
Navigating to grafana on firefox using localhost:3000 i am logging in grafana with admin credentials. I navigate to datasources and i see my influxdb datasource mounted. I navigate to my influxdb datasource and Skip TLS Verify option is turned off. This should not happen since i enable it from the dashboard file i am using.

datasource.yml :
```
# config file version
apiVersion: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
  # <string, required> name of the datasource. Required
- name: edgeX-influxd
  # <string, required> datasource type. Required
  type: influxdb
  # <string, required> access mode. direct or proxy. Required
  access: proxy
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string> url
  url: https://influxdb:8086
  # <bool> enable editing of datasource from ui
  isDefault: true
  # <bool> allow updating provisioned datasource from the UI
  editable: true
  # <string> database name, if used
  database: database_influx
  # <bool> skil tls verification
  **tls_skip_verify_insecure : true**
```
and the output was this :
![image](https://user-images.githubusercontent.com/26853955/101947157-e88d7180-3be7-11eb-9df1-725fb3ad368c.png)

**What you expected to happen**:
![image](https://user-images.githubusercontent.com/26853955/101947191-f5aa6080-3be7-11eb-89d0-1830f01a4869.png)

**Anything else we need to know?**:
**Environment**: Ubuntu 20.04
- Grafana version: 7.3.1
- Data source type & version: influxdb 1.8.3
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Ubuntu 20.4 & Firefox
- Grafana plugins:
