### ISSUE TITLE
AWS Cognito Auth BUG

### ISSUE THREAD

**Issue by apolegoshko** [grafana/grafana#29914]
**What happened**:

Authentication using AWS Cognito is not working when I'm passing env variables from Kubernetes secret. While if I'm passing values directly in deployment.yaml file of Grafana - it works.

**What you expected to happen**:

I'm expecting that I should authenticate in Grafana using AWS Cognito when I'm passing variables from Kubernetes secret.

**How to reproduce it (as minimally and precisely as possible)**:

Create a kuberenetes secret. 

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: grafana-oauth-secrets
data:
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: <base64>
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: <base64>
```

Reference this in deployment file of grafana. 

```yaml
...
          envFrom:
            - secretRef:
                name: grafana-oauth-secrets
...
```
Try to Authenticate in Grafana using AWS Cognito.

**Anything else we need to know?**:

**Environment**: Kubernetes
- Grafana version: 7.3.6
- Data source type & version: -
- OS Grafana is installed on: Kubernetes 1.18, Docker
- User OS & Browser: Chrome Google
- Grafana plugins: -
- Others: -
