### ISSUE TITLE
gettingstarted panel is messing up custom home dashboard on initial setup

### ISSUE THREAD

**Issue by Mario-Hofstaetter** [grafana/grafana#29934]
**What happened**:

Since provisioning does not support setting the Home Dashboard of an installation,
I used [`default_home_dashboard_path` in config](https://grafana.com/docs/grafana/latest/administration/configuration/#default_home_dashboard_path) to set my custom home dashboard (by using an ENV variable).

When doing so, the default panel of `"type": "gettingstarted"` **is injected in my dashboard and is messing up the layout**.
If the raw json of the dashboard is inspected, it does contain this panel while the original file does not.

- This seems to be happening only once during first login
- Clicking "**Remove this panel**" does seem to remove it permanently for this user at least
  - Tested different browsers, clearing browser cache, and using different users to login, the panel does not seem to reappear.
- EDIT: Tested and got feedback from colleages connecting with different users from different clients.
They DO get the banner once after logging in. So not quite sure where/how it is saved, can't be a cookie otherwise browser cache clear would get it back.

It is a very minor issue but it is annoying when doing a presentation of the grafana setup in front of staff / management though since grafana is otherwise so shiny and cool ❤️ 

**What you expected to happen**:

The configured dashboard being display without getting modified.

**How to reproduce it (as minimally and precisely as possible)**:

[MyHomeDashboard.json](https://github.com/grafana/grafana/files/5719852/MyHomeDashboard.json.txt)

- Use attached `MyHomeDashboard.json` and put into `./dashboards/`
  - Please rename from `.txt` since github does not support attaching json files
- Alternatively create and use any dashboard yourself
- Use the following `docker-compose.yml` and put into `./`
- `docker-compose up -d` -> Open http://localhost:3000 in browser

```yaml
version: "2"

services:
  grafana:
    environment:
      - "GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/dashboards/MyHomeDashboard.json"
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./dashboards:/etc/grafana/dashboards:ro
```

Original `MyHomeDashboard.json`:
![grafik](https://user-images.githubusercontent.com/33002073/102694917-6672fd80-4224-11eb-8e9f-ee5c80ad14f0.png)

As Home Dashboard:
![grafik](https://user-images.githubusercontent.com/33002073/102694949-9de1aa00-4224-11eb-8f00-f737a8378fe6.png)

**Environment**:
- Grafana version: `Grafana v7.3.6 (ea06633c34)`
- OS Grafana is installed on: docker image
- User OS & Browser: Windows 10, Firefox and Chrome
