### ISSUE TITLE
Not being able to provision azure-monitor with YML Grafana v7.0.3

### ISSUE THREAD

**Issue by JavierHernandezMontes** [grafana/grafana#29947]
Hello,

I am trying to automate the data source configuration for azure-monitor using Azure pipelines in devops.

The configuration made is the following:

```
grafana:
  additionalDataSources:
    - name: azure-monitor
      type: grafana-azure-monitor-datasource
      orgId: 1
      typeLogoUrl: public/plugins/grafana-azure-monitor-datasource/img/logo.jpg
      access: proxy
      url: /api/datasources/proxy/2
      isDefault: false
      jsonData:
        cloudName: azuremonitor
        subscriptionId: xxx
        tenantId: xxx
        clientId: xxx
        logAnalyticsDefaultWorkspace: xxx
        azureLogAnalyticsSameAs: true
        keepCookies: []
      secureJsonData:
        clientSecret: xxx
      editable: false
```
I see that the values established are in grafana:

And I get the error:
"1. Successfully queried the Azure Monitor service. 2. Azure Log Analytics: Unauthorized: AuthorizationRequiredError. Valid authentication was not provided":

![image](https://user-images.githubusercontent.com/25748527/102778996-d48a0280-4393-11eb-969b-85b837fdb1eb.png)

If I update manually in the data source the "Client Secret" works.

It also works using version of Grafana v6.4.2 with the same code and same configuration without the need of changing the “Client Secret” manually.
