### ISSUE TITLE
Grafana alert duplicated but UI did not list out

### ISSUE THREAD

**Issue by renchili** [grafana/grafana#30210]
**What happened**:
![image](https://user-images.githubusercontent.com/33677006/104268714-8918cf00-54cf-11eb-838d-111ed9b1afd8.png)

**What you expected to happen**:
the above 2 alerts should list under the pannel, but we got :
![image](https://user-images.githubusercontent.com/33677006/104268756-a483da00-54cf-11eb-93d4-edb239e3957f.png)

**How to reproduce it (as minimally and precisely as possible)**:
cannot reproduce, I do not know what triggered this
**Anything else we need to know?**:
we running 2 grafana servers shared the same MySQL DB
**Environment**:
- Grafana version: 7.2.1
- Data source type & version: Prometheus
- OS Grafana is installed on: ubuntu
- User OS & Browser: alerting rule not related to the user browser
- Grafana plugins: NA
- Others:
in DB alert table really got 2 alerts with different expression, but when open the correspond pannel only 1 alert show in alert tab 
and one of the alert in db is with a wrong (not same) expression as the pannel

**Comment by marefr** [comment]
Weird. But guess that could happen in some special case when updating dashboards. Is the MySQL DB using a high availability setup, like master/master, replication etc?

When looking in database table does it have the same dashboard_id, panel_id and org_id? Maybe you can include the output of the two rows (strip any sensitive data). 

Sure you haven't created a copy of the dashboard?

**Comment by renchili** [comment]
hi let me provide more information:
```
mysql> select * from alert  where `name`='Server Alert- update API p99 latency alert'\G
*************************** 1. row ***************************
             id: 29413
        version: 0
   dashboard_id: 1391
       panel_id: 30
         org_id: 2
           name: Server Alert- update API p99 latency alert
        message: item write api has large latency
          state: ok
       settings: {"alertRuleTags":{},"conditions":[{"evaluator":{"params":[15000],"type":"gt"},"operator":{"type":"and"},"query":{"datasourceId":202,"model":{"expr":"histogram_quantile(0.99, sum(job:rpc_server_latency_bucket:rate1m{cmd=~\"item.+\", cmd!~\"item.+get.+|item.item_info.add_item_with_basic_info|item.item_info.delete_model_list|item.tag.create_item_tag|item.tag.update_item_tag|item.storage.+|item.item_info.add_item_with_basic_info_check_only|item.item_info.update_item_basic_info_check_only|item.attribute.+|item.mtsku.+|item.price_stock_snapshot.+\", cmd !~ \"item.price_stock_snapshot.+|item.ips_proxy.+\", 
cmd!=\"item.price_stock_snapshot.add_stock_snapshot\"})by (le,cmd))","format":"time_series","hide":false,"interval":"","intervalFactor":1,"legendFormat":"p99-{{cmd}}","refId":"A"},"params":["A","5m","now"]},"reducer":{"params":[],"type":"avg"},"type":"query"}],"executionErrorState":"keep_state","for":"5m","frequency":"1m","handler":1,"message":"item write api has large latency","name":"Server Alert- update API p99 latency alert","noDataState":"ok","notifications":[{"uid":"QTKoL-AMz"}]}
      frequency: 60
        handler: 1
       severity:
       silenced: 0
execution_error:
      eval_data: NULL
      eval_date: NULL
 new_state_date: 2021-01-08 14:38:17
  state_changes: 398
        created: 2020-12-02 13:22:39
        updated: 2021-01-09 19:31:29
            for: 300000000000
*************************** 2. row ***************************
             id: 29414
        version: 0
   dashboard_id: 1391
       panel_id: 30
         org_id: 2
           name: Server Alert- update API p99 latency alert
        message: @here item write api has large latency
          state: paused
       settings: {"alertRuleTags":{},"conditions":[{"evaluator":{"params":[1500],"type":"gt"},"operator":{"type":"and"},"query":{"datasourceId":202,"model":{"expr":"histogram_quantile(0.99, sum(job:rpc_server_latency_bucket:rate1m{cmd !~ \"item.+get.+|item.item_info.add_item_with_basic_info|item.ips_proxy.add_item_selling_price_batch|item.ips_proxy.update_item_selling_and_normal_price_batch|item.ips_proxy.delete_item_selling_price_batch|item.item_info.delete_model_list|item.tag.create_item_tag|item.tag.update_item_tag|item.storage.kv_storage.insert|item.item_info.add_item_with_basic_info_check_only|item.item_info.update_item_basic_info_check_only|item.attribute.create_attr|item.attribute.create_attr_value|item.attribute.create_category_attr_mapping|item.attribute.create_category_attr_value_mapping|item.mtsku.create_and_link_mtsku_by_mpsku_item|item.mtsku.create_single_mtsku_and_mpsku_item|item.mtsku.update_single_mtsku_and_mpsku_item|item.mtsku.create_mpsku_item\", cmd=~\"item.+\"})by (le,cmd))","format":"time_series","hide":false,"interval":"","intervalFactor":1,"legendFormat":"p99-{{cmd}}","refId":"D"},"params":["D","5m","now"]},"reducer":{"params":[],"type":"avg"},"type":"query"}],"executionErrorState":"keep_state","for":"5m","frequency":"1m","handler":1,"message":"@here item write api has large latency","name":"Server Alert- update API p99 latency alert","noDataState":"ok","notifications":[{"uid":"QTKoL-AMz"}]}
      frequency: 60
        handler: 1
       severity:
       silenced: 0
execution_error:
      eval_data: {"evalMatches":[{"value":2830.3025767507825,"metric":"p99-item.price_stock_snapshot.add_price_snapshot","tags":{"cmd":"item.price_stock_snapshot.add_price_snapshot"}}]}
      eval_date: NULL
 new_state_date: 2021-01-12 02:52:30
  state_changes: 756
        created: 2020-12-02 13:22:41
        updated: 2020-12-02 13:22:41
            for: 300000000000            
```
