### ISSUE TITLE
Grafana configuration gets reset when changing environment variable passed via docker-compose.yml

### ISSUE THREAD

**Issue by tukotech** [grafana/grafana#30693]
**What happened**:
When I change an environment variable passed via docker-compose yml file, Grafana's configuration gets reset. I have tried this 5 times.

**What you expected to happen**:
When then environment variable is changed it should not reset Graphana's configuration. Reset here means I have to start re-configuring Grafana from scratch.

**How to reproduce it (as minimally and precisely as possible)**:

1. Start from https://github.com/grafana/tutorial-environment
2. Once it is up and running change docker-compose.yml

From
```
  grafana:
    image: grafana/grafana:7.3.6
    ports:
      - 3000:3000
    networks:
      - grafana
```
To (as an example)
```
  grafana:
    image: grafana/grafana:7.3.7
    ports:
      - 3000:3000
    networks:
      - grafana
    environment:
      - GF_SERVER_DOMAIN=example.org
      - GF_SMTP_ENABLED=true
      - GF_SMTP_SKIP_VERITY=true
      - GF_SMTP_HOST=some.smtp.server.com:25
      - GF_SMTP_FROM_ADDRESS=admin@grafana.localhost
```

Then restart like:
```
docker-compose stop
docker-compose up -d
```
Re-connecting to Grafana should show that the configuration is reset to default
Note: I was running docker-compose on Debian 10.7 64-bit

**Anything else we need to know?**:

**Environment**:
- Grafana version:7.3.7
- Data source type & version: Not important
- OS Grafana is installed on: Debian 10.7 runs the docker-compose
- User OS & Browser: Windows 10 & Chrome
- Grafana plugins: None
- Others: None

**Comment by papagian** [comment]
@tukotech
what do you mean "Re-connecting to Grafana should show that the configuration is reset to default"?
Can you share the log when you first starting grafana and when restarting?

**Comment by tukotech** [comment]
@papagian 
RE: what do you mean "Re-connecting to Grafana should show that the configuration is reset to default"?
Imagine following the tutorial from https://github.com/grafana/tutorial-environment, the first login to local grafana, that is it. 

RE: Can you share the log when you first starting grafana and when restarting?
Where can I find this? Note that this is in docker environment and I would need guidance how to get it.

**Comment by papagian** [comment]
> Where can I find this? Note that this is in docker environment and I would need guidance how to get it.
you can check the container logs using:
`docker-compose logs grafana`

When you run `docker-compose up -d` the second time a new container and a new (sqlite) database will be created.
The password is kept in the database not in the configuration. So for persisting the password the second container should point to the same database file created before. For doing so you can create an empty database:
`sqlite3 grafana.db "VACUUM;"`

Then, use the following `docker-compose.yml` for starting grafana for first time:
```
  grafana:
    image: grafana/grafana:7.3.6
    ports:
      - 3000:3000
    volumes:
      - ./grafana.db:/var/lib/grafana/grafana.db
    networks:
      - grafana
```

Start the container and create the password.
Then change the `docker-compose.yml` to:
```
  grafana:
    image: grafana/grafana:7.3.7
    ports:
      - 3000:3000
    networks:
      - grafana
    volumes:
      - ./grafana.db:/var/lib/grafana/grafana.db
    environment:
      - GF_SERVER_DOMAIN=example.org
      - GF_SMTP_ENABLED=true
      - GF_SMTP_SKIP_VERITY=true
      - GF_SMTP_HOST=some.smtp.server.com:25
      - GF_SMTP_FROM_ADDRESS=admin@grafana.localhost
```

Stop and start the container again and now you should be able with the password you have created before.
