### ISSUE TITLE
Default docker group is root(0) contrary to documents

### ISSUE THREAD

**Issue by mvadu** [grafana/grafana#30953]
**Documentation**:
https://grafana.com/docs/grafana/latest/installation/docker/#migrate-to-v51-or-later
"The Grafana Docker image runs with the root group (id 1) instead of the grafana group (id 472), for better compatibility with OpenShift. "

**What happened**:
Running fresh docker container on ubuntu 20  with 
```
version: '3.3'

services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: unless-stopped
    ports:
    - "3000:3000"
```
Checking the user running the grafana process shows the uid to be 472 and gid as 0.

```
bash-5.0$ uname -a
Linux 7a3db0a0ed2e 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 Linux
bash-5.0$ id
uid=472(grafana) gid=0(root) groups=0(root)
bash-5.0$ grafana-server -v
Version 7.4.0 (commit: c2203b9859, branch: HEAD)
```

**What you expected to happen**:
uid=0(root) gid=0(root) groups=0(root)

**How to reproduce it (as minimally and precisely as possible)**:
See the docker compose above

**Anything else we need to know?**:
The documentation might need to be updated to clarify the default user is still 472, and the root group is 0 and not one. Since the source code is setting it to 0 [here](https://github.com/grafana/grafana/blob/ee405ef0693def6e8c227bbe5b99e062fc072212/Dockerfile#L40)
