### ISSUE TITLE
Missing an info about building packages

### ISSUE THREAD

**Issue by hasso** [grafana/grafana#30963]
**What would you like to be added**:

An info about building binary packages.

**Why is this needed**:

After removing grunt `go run build.go build package` doesn't work any more and an info about developers/users can build their own packages is missing.

**Comment by oddlittlebird** [comment]
Are you referring to plugins documentation or frontend API documentation?

**Comment by hasso** [comment]
It probably should be in developer documentation (https://github.com/grafana/grafana/blob/master/contribute/developer-guide.md). Ie I mean there is no info how to create a custom grafana server packages - rpm, deb, tar.gz.

**Comment by oddlittlebird** [comment]
@marcusolsson, can you take a look at this?

**Comment by pielambr** [comment]
This is how I did it 

1) `gpg --gen-key` to generate a new GPG key with password
2) Export private key with `gpg --output private.pgp --armor --export-secret-key <gpg email address>`
3) Export public key with `gpg --output factry.gpg --armor --export <gpg email address>`
4) Download the grabpl tool from here: https://grafana-downloads.storage.googleapis.com/grafana-build-pipeline/v0.5.38/grabpl
4) Set the environment variables `GPG_KEY_PASSWORD`, `GPG_PRIV_KEY` and `GPG_PUB_KEY`. For the last two, they have to be base64 encoded, so you can do something like `export GPG_PRIV_KEY=$(cat private.gpg | base64)`
5) Build frontend and server for Grafana:
  - `./grabpl build-frontend --jobs 8 --no-install-deps --edition oss --no-pull-enterprise`
  - `./grabpl build-backend --jobs 8 --edition oss --variants linux-x64 --no-pull-enterprise`
  Change above commands as needed
6) Run `mkdir plugins-bundled/dist/ dist/`, these should exist before packaging
7) Package with `./grabpl package --jobs 8 --edition oss --no-pull-enterprise --variants linux-x64`

**Comment by hasso** [comment]
But something is still missing, seems.
```
$ ./grabpl build-backend --jobs 8 --edition oss --variants linux-x64 --no-pull-enterprise
* Detecting the version mode based on the version being built
* Building Grafana back-end, version "7.4.1", OSS edition, version mode Release, variants linux-x64
* Creating worker pool with 8 workers
* Installing compilers...
panic: Can't find "/tmp/x86_64-centos6-linux-gnu.tar.xz"
```

**Comment by marcusolsson** [comment]
I'm not sure how common it is for users to create their own rpm/deb packages of Grafana, so can't say whether it's something worth maintaining docs for. If something that used to work is broken, I think we should consider fixing it. 

Maybe @aknuds1 might be able to help out here?

**Comment by hasso** [comment]
I've been building several custom packages for users – grafana/grafana#448 alone is a good reason to do it, but there is others (custom sorting, units that don't make sense in wider context etc).

**Comment by pielambr** [comment]
Right, about the missing `/tmp/x86_64-centos6-linux-gnu.tar.xz`, I solved this by using the Docker container
`grafana/build-container:1.3.2`
since this holds all the other dependencies as well :shrug:

**Comment by cbonte** [comment]
> I've been building several custom packages for users – #448 alone is a good reason to do it, but there is others (custom sorting, units that don't make sense in wider context etc).

I also have to maintain custom packages to include some fixes that were never accepted.
For example : https://github.com/grafana/grafana/issues/12963

**Comment by sigkosr** [comment]
Hello everyone, is anyone got any workaround? My colleague is working on this problem and cant find the solution.
why grunt got removed? I am totally noob here, From #29461 torkelo mention that it replaces with alternative but what is this alternative or I am misunderstand/misread?
and what happen to "build from source" document page, hopefully new instruction is work in process.
thanks for reading

**Comment by digrich** [comment]
Hello Grafana Team - Not able to build grafana from source after 7.4 release. Can you please update if the steps to build grafana are changed in 7.4?

**Comment by sealgrubble** [comment]
Here is a workaround that we have done for the case of not cross compiling e.g. (i.e. build=target or build=host).  
Our workaround is for building deb and rpm packages for x64 machines. 
Thanks @pielambr for providing the hints.
The steps are:
1. Build grafana frontend as usual via yarn i.e. yarn install --pure-lock-file and yarn start commands
2. Build grafana backend as usual via go i.e. go run build.go build
3. Now packaging time, follow  steps 1 2 3 4 5 and 7 from @pielambr and you would get .deb .rpm and tar.gz in the ./dist folder. Note: a. --jobs N is to define number of workers
           b. There might be some complaining about signing rpm but that rpm should work

PS. We have tried cross compiling too but we ended up with errors associated with openssl in building grafana backend step...

**Comment by achatterjee-grafana** [comment]
@aknuds1 and @marcusolsson, there are new comments on this issue. Can you check how it should be resolved. Thanks for your help!

**Comment by aknuds1** [comment]
We don't currently have any strategy for supporting 3rd parties in building their own Grafana packages (archives, Deb/RPM packages etc.). We have a complex CI setup, and providing support for 3rd parties to do the same would require significant effort. I'm labeling it as a feature request, since if we were to provide support for it, it would need a lot of deliberation.

**Comment by achatterjee-grafana** [comment]
@aknuds1 thank you for looking into this and commenting.

**Comment by gavol** [comment]
May I ask why such a nice and important feature has been removed?

Additionally, an RPM for the official versions can be easily downloaded from the Grafana download page, so that is something definitely possible. Why custom builds are now excluded form the possibility to build such packages? And that was working pretty well in previous versions.

I have to admin that I am a little bit disappointed from this kind of actions.

**Comment by hasso** [comment]
Please reconsider. Although Grafana is a complicated project and I understand a desire to carefully design everything, building packages shouldn't be a rocket science and can be just possible, not a designed experience. Remember for example, it took 5 years for Grafana to support any date format except the US one. All this time I and I'm sure that many others built custom packages for this reason alone.

I also made a pull request to fix another big annoyance for anyone working with network. I have to build custom packages for this reason alone. But now what? I have no idea what should I do to get it merged – https://github.com/grafana/grafana/pull/31512 

I don't have problems hacking my packages together, but it shouldn't be an experience it is now – icecaps melting resource hungry and secret recipe.

**Comment by niclash** [comment]
Is https://grafana-downloads.storage.googleapis.com/grafana-build-pipeline/v0.5.38/grabpl still the latest/greatest ?

**Comment by hasso** [comment]
No. See the beginning of the scripts/lib.star file for grabpl and build container versions needed to build a specific version/branch.

**Comment by flynn1973** [comment]
i made up a build script which uses nfpm from goreleaser,  works ok here, no need for a complicated ci stack or other crap. sufficient for building local packages. feel free to adapt, adopt whatever...released under the "i dont care" license.

build script:

````
#!/usr/bin/bash
export GRAFANA_VERSION="v8.0.5"
export GOPATH=/scratch/go/dev
export PATH=${GOPATH}/bin:${PATH}
cd ${GOPATH}/src/github.com/grafana
rm -rf grafana
git clone https://github.com/grafana/grafana
cd grafana
git checkout -f $GRAFANA_VERSION
BUILD_VERSION=$(git describe --tags)
if [[ "$BUILD_VERSION" != "$GRAFANA_VERSION" ]]; then
        echo "Version missmatch, look after git tag"
        exit 1
else
yarn install --pure-lockfile
yarn build
go run build.go setup
go run build.go build
# Todo rpm build with nfpm
${GOPATH}/bin/nfpm pkg --packager rpm --config /scratch/go/BUILDSCRIPTS_CTREMEL/conf/grafana_nfpm.yaml --target /scratch/go/BUILDSCRIPTS_CTREMEL/dist
fi
````

nfpm config:

````
name: "grafana"
arch: "ppc64le"
platform: "linux"
version: "${GRAFANA_VERSION}"
section: "default"
priority: "extra"
replaces:
- grafana
provides:
- grafana-server
- grafana-cli
depends:
- coreutils
- shadow-utils
maintainer: "<contact@grafana.com>"
description: |
  Grafana
vendor: "Grafana"
homepage: "https://grafana.com"
license: "Apache 2"
contents:
        - src: ./bin/linux-ppc64le/grafana-server
          dst: /usr/sbin/grafana-server
        - src: ./bin/linux-ppc64le/grafana-cli
          dst: /usr/sbin/grafana-cli
        - src: ./packaging/rpm/init.d/grafana-server
          dst: /etc/init.d/grafana-server
        - src: ./packaging/rpm/sysconfig/grafana-server
          dst: /etc/sysconfig/grafana-server
          type: config|noreplace
        - src: ./packaging/rpm/systemd/grafana-server.service
          dst: /usr/lib/systemd/system/grafana-server.service
        - src: ./public/
          dst: /usr/share/grafana/public
        - src: ./conf/
          dst: /usr/share/grafana/conf

empty_folders:
  - /etc/grafana

scripts:
    postinstall: ./packaging/rpm/control/postinst

rpm:
    scripts:
        posttrans: ./packaging/rpm/control/posttrans

````
