### ISSUE TITLE
Data Source Provisioning error after upgrade to 7.4.0

### ISSUE THREAD

**Issue by EnnFour** [grafana/grafana#30999]
**What happened**:
On upgrade to 7.4.0, my datasource provisioning broke with the following error: `service init failed: Datasource provisioning error: unique identifier and org id are needed to be able to get or delete a datasource`
This is unexpected, as the my datasource-conf.yaml is the following:

    apiVersion: 1
    datasources:
      - name: Prometheus
      - type: prometheus
      - access: proxy
      - url: prometheus:9090
      - orgId: 1
      - uid: "1230"
    version: 1
    editable: false

**What you expected to happen**:
I expected there to be no issues with how I previously had the data source configured (which specified neither orgId nor uid)

**How to reproduce it (as minimally and precisely as possible)**:
Pull the grafana/grafana:latest image from docker hub. Set up a prometheus server on port 9090. Create the above config file.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4.0
- Data source type & version: Prometheus -- pulled from dockerhub prom/prometheus
- OS Grafana is installed on: Comes from docker image
- User OS & Browser: Using a GitPod environment in Google Chrome
- Grafana plugins: None
- Others:

**Comment by wbrowne** [comment]
@EnnFour This is happening due to incorrect YAML format. The structure above is actually treating each child of `datasources` to be its own provisioned datasource. The first with only the name provided, the second with the type provided, and so on. Which is why it complains about a lack of unique identifier. What I believe you want is:

```yaml
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: prometheus:9090
    orgId: 1
    uid: "1230"
    version: 1
    editable: false
```
