### ISSUE TITLE
Flux Datasource Can't Connect to Influx DB 1.8.3 (Internal Server Error)

### ISSUE THREAD

**Issue by sirockin** [grafana/grafana#31963]
**What happened**:

When I tried to connect to influxdb instance using flux datasource I received "Error reading InfluxDB". Browser console showed POST request returning internal server error.

**What you expected to happen**:

The datasource to connect

**How to reproduce it (as minimally and precisely as possible)**:

Running from docker-compose extract:
```
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - "./grafana.ini/:/etc/grafana/grafana.ini"
      # Grafana config persistence
   ....
  influxdb:
    image: influxdb:1.8.3
    restart: always
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DATA_ENGINE=tsm1
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_HTTP_FLUX_ENABLED=true
    volumes:
    ...
```

![image](https://user-images.githubusercontent.com/7776773/111038400-f0e48b00-8428-11eb-8ffc-ce3df596540b.png)

![image](https://user-images.githubusercontent.com/7776773/111038639-6dc43480-842a-11eb-81c7-0b2db2dd38fa.png)

**Anything else we need to know?**:

I can connect fine using the standard InfluxQL data source and the same URL

I can run flux queries from an instance of Chronograf running in the same docker-compose setup, again using the same URL.

I get an identical error if I cahnge the "Access" field to "Browser" and edit the URL to point directly to the machine.

**Environment**:
- Grafana version:
Grafana latest maps to version 7.4.3

- Data source type & version:
Flux (InfluxDB 1.8.3)

- OS Grafana is installed on:

Officical docker image running on Ubuntu Server 20.04

- User OS & Browser:
Windows 10
Firefox 86.0
