### ISSUE TITLE
Using Environment Variables in provisioning datasources jsonData

### ISSUE THREAD

**Issue by vshivkov** [grafana/grafana#32061]
**What happened**:
when using environment variables, a value with the string type is substituted in the provisioning datasource

provisioning/datasources/datasource.yaml:
 ```
apiVersion: 1
 metadata:
  name: datasources 
 datasources:    
  - name: "MyBackendDatasource"
    type: my-backend-datasource
    access: proxy
    jsonData:
      tlsAuthWithCACert: ${GRAF_DATASOURCE_AuthWithCACert}
    secureJsonData:
      tlsCACert: ${GRAF_DATASOURCE_tlsCACert}
    isDefault: false
    version: 1
    editable: true
```

Datasource Settings error:
`json: cannot unmarshal string into Go struct field DataSourceOptions.tlsAuthWithCACert of type bool`

console.log(options.jsonData):
`jsonData: {tlsAuthWithCACert: "true"}`

**What you expected to happen**:
It is substituted for an environment variable with the boolean type
`jsonData: {tlsAuthWithCACert: true}`

**How to reproduce it (as minimally and precisely as possible)**:
mentioned above

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4.1
- Data source type & version: My backend plugin
- OS Grafana is installed on: rhel7
- User OS & Browser: windows 10, yandex browser
