### ISSUE TITLE
EKS IRSA sts:AssumeRoleWithWebIdentity broken in 7.4.0

### ISSUE THREAD

**Issue by guitarrapc** [grafana/grafana#32531]
**What happened**:

On AWS EKS 1.19, Grafana 7.5.1, deployed with the latest helm chart 6.7.0, cannot perform sts:AssumeRoleWithWebIdentity authentication anymore using IRSA. Query fails with this error:

```
WebIdentityErr: failed to retrieve credentials caused by: SerializationError: failed to unmarshal error message status code: 403, request id: XG4TCCYJ3YJJDQBCCXEEVGDXVU caused by: UnmarshalError: failed to unmarshal error message 00000000 3c 4d 69 73 73 69 6e 67 41 75 74 68 65 6e 74 69 |<MissingAuthenti| 00000010 63 61 74 69 6f 6e 54 6f 6b 65 6e 45 78 63 65 70 |cationTokenExcep| 00000020 74 69 6f 6e 3e 0a 20 20 3c 4d 65 73 73 61 67 65 |tion>. <Message| 00000030 3e 4d 69 73 73 69 6e 67 20 41 75 74 68 65 6e 74 |>Missing Authent| 00000040 69 63 61 74 69 6f 6e 20 54 6f 6b 65 6e 3c 2f 4d |ication Token</M| 00000050 65 73 73 61 67 65 3e 0a 3c 2f 4d 69 73 73 69 6e |essage>.</Missin| 00000060 67 41 75 74 68 65 6e 74 69 63 61 74 69 6f 6e 54 |gAuthenticationT| 00000070 6f 6b 65 6e 45 78 63 65 70 74 69 6f 6e 3e 0a |okenException>.| caused by: unknown error response tag, {{ MissingAuthenticationTokenException} []}
```

Amazon Timestream datasource provider is set to "AWS SDK Default", endpoint is set to "query-cell1.timestream.us-west-2.amazonaws.com" and default region is set to "us-west-2".

![image](https://user-images.githubusercontent.com/3856350/113091681-6de47280-9227-11eb-9d26-b706831ceee2.png)

**What you expected to happen**:

Authenticate succesfully to AWS using IRSA token.

**How to reproduce it (as minimally and precisely as possible)**:

On a EKS 1.19 cluster:

* Create Amazon Timestream database at us-west-2 (oregon).
* Create IAM role along with policy that give it access to cloudwatch.
* Deploy Grafana helm chart and set the serviceAccount annotation "eks.amazonaws.com/role-arn" to the IAM role ARN, add grafana timestream plugin `grafana-timestream-datasource`.
* Create a Timestream datasource and test.

**Anything else we need to know?**:

**Environment**:
- Grafana version:
   - 7.2.2: OK
   - 7.3.0-beta2: OK
   - 7.3.5: OK (helm chart 6.2.2 using this version)
   - 7.3.7: OK
   - 7.4.0: NG (degrade start)
   - 7.4.5: NG (helm chart 6.6.4 using this version)
   - 7.4.8: NG
   - 7.5.1: NG (latest helm chart 6.7.0 using this version)
- Data source type & version:
- OS Grafana is installed on: Docker `grafana/grafana`
- User OS & Browser: Windows/Chrome
- Grafana plugins: grafana-timestream-datasource
- Others: aws cli with same serviceaccount works fine. This is grafana sts:AssumeRoleWithWebIdentity issue.
- Related: 
  * https://github.com/grafana/grafana/issues/20473 result is IRSA working from `7.3.0-beta2`.
  * https://github.com/grafana/grafana/issues/29017 result is IRSA not working from `7.3.x`.
  * [Latest Helm chart 6.7.0](https://artifacthub.io/packages/helm/grafana/grafana/6.7.0) using grafana 7.5.1 and this issue happens.

**Comment by wbrowne** [comment]
Thanks for the detailed info @guitarrapc. I don't see anything immediately obvious that could cause this problem from v7.4.0. Did you try what was mentioned [here](https://github.com/grafana/grafana/issues/29017#issuecomment-762725349)?

**Comment by guitarrapc** [comment]
Thank you for the check. OK. I'll check on my docker again with v7.4.0.

**Comment by guitarrapc** [comment]
> Did you try what was mentioned here?

Yes, IAM Role Assume to `system:serviceaccount:*:grafana`, and serviceaccount is `grafana` as Helm created default.

I tried again and reproduce in following values.yaml and helm command.

```shell
helm repo add grafana https://grafana.github.io/helm-charts
helm repo update
helm upgrade --install grafana grafana/grafana --version 6.6.4 --namespace grafana -f ./grafana/helm/values.yaml
```

```yaml
serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::xxxxx:role/eks-pod-grafana-role

image:
  tag: 7.4.0
adminPassword: strongpassword

plugins:
  - grafana-timestream-datasource

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Timestream
        type: grafana-timestream-datasource
        isDefault: true
        jsonData:
          authType: default
          endpoint: query-cell1.timestream.us-west-2.amazonaws.com
          defaultRegion: us-west-2

sidecar:
  dashboards:
    enabled: true
```


and not happen with following 7.3.7.

```yaml
serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::xxxxx:role/eks-pod-grafana-role

image:
  tag: 7.3.7
adminPassword: strongpassword

plugins:
  - grafana-timestream-datasource

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Timestream
        type: grafana-timestream-datasource
        isDefault: true
        jsonData:
          authType: default
          endpoint: query-cell1.timestream.us-west-2.amazonaws.com
          defaultRegion: us-west-2

sidecar:
  dashboards:
    enabled: true
```

![image](https://user-images.githubusercontent.com/3856350/114339939-6743ec80-9b91-11eb-8a0e-909cd437e776.png)


What was your values.yaml?
