### ISSUE TITLE
version check in settings page is wrong/ wrong plugin version in use?

### ISSUE THREAD

**Issue by JanHBade** [grafana/grafana#32841]
Hello,

I am runnig a grafana (v7.5.3) docker container an a rasperry pi 4, everything works fine.

When I restart the container the downloads the needed plugins:

```
installing grafana-piechart-panel @ 1.6.1
from: https://grafana.com/api/plugins/grafana-piechart-panel/versions/1.6.1/download
into: /var/lib/grafana/plugins

✔ Installed grafana-piechart-panel successfully 
```

but when i look in the settings page

![grafik](https://user-images.githubusercontent.com/3524802/114180839-0de57e80-9941-11eb-9b38-cb91ed4aff41.png)

so I think the website not checked that there is a new plugin or is ist using the old one?

Docker Compose
```
grafana:
    container_name: grafana
    image: grafana/grafana
    depends_on:
      - influxdb
    volumes:
      - ./../grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - grafana_data:/var/lib/grafana
    networks:
      - gateway
    environment:
     - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana
     - GF_INSTALL_PLUGINS=grafana-clock-panel,fetzerch-sunandmoon-datasource,natel-discrete-panel,grafana-piechart-panel
     - GF_RENDERING_SERVER_URL=http://grafana-renderer:8081/render
     - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
 ```
