### ISSUE TITLE
${__org.name} and ${__user.login} don't work with grafana-image-renderer

### ISSUE THREAD

**Issue by lnicot01** [grafana/grafana#33016]
**What happened**:
When rendering a dashboard or a panel (Share | Direct link rendered image), ${__org.name} and ${__user.login} are rendered empty.

**What you expected to happen**:
The organisation name and user name must appear. 

**How to reproduce it (as minimally and precisely as possible)**:
Create a text panel and add in markdown content :
org : ${__org}  
org id : ${__org.id}  
org name : ${__org.name}  

user : ${__user}  
user id : ${__user.id}  
user login : ${__user.login}  

dashboard : ${__dashboard}  
dashboard uid : ${__dashboard.uid}  
dashboard name : ${__dashboard.name}  

Save the dashboard.
Use share menu on the panel and click 'Direct link rendered image' link to renderer panel
All variables are correctly displayed except ${__org.name} and ${__user.login}

**Anything else we need to know?**:
Works fine with Grafana 6.5.3

**Environment**:
- Grafana version: 7.3.5 and 7.5.1
- Data source type & version: None
- OS Grafana is installed on: docker
- User OS & Browser: Windows 10 / Chrome
- Grafana plugins: Image Renderer 2.0.1 and 1.0.9
- Others:

**Comment by hugohaggmark** [comment]
Reproduced with the following docker compose:
```yml

services:
  grafana:
    image: grafana/grafana:7.5.1
    ports:
      - 3001:3000
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
  renderer:
    image: grafana/grafana-image-renderer:2.0.1
    ports:
      - 8081
    environment:
      ENABLE_METRICS: 'true'
```

and the following dashboard json
```json
{
  "__inputs": [],
  "__requires": [
    {
      "type": "grafana",
      "id": "grafana",
      "name": "Grafana",
      "version": "7.5.1"
    },
    {
      "type": "panel",
      "id": "text",
      "name": "Text",
      "version": ""
    }
  ],
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": null,
  "links": [],
  "panels": [
    {
      "datasource": null,
      "description": "",
      "fieldConfig": {
        "defaults": {},
        "overrides": []
      },
      "gridPos": {
        "h": 12,
        "w": 13,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "content": "org : ${__org}\n\norg id : ${__org.id}\n\norg name : ${__org.name}\n\nuser : ${__user}\n\nuser id : ${__user.id}\n\nuser login : ${__user.login}\n\ndashboard : ${__dashboard}\n\ndashboard uid : ${__dashboard.uid}\n\ndashboard name : ${__dashboard.name}",
        "mode": "markdown"
      },
      "pluginVersion": "7.5.1",
      "targets": [
        {
          "queryType": "randomWalk",
          "refId": "A"
        }
      ],
      "timeFrom": null,
      "timeShift": null,
      "title": "Panel Title",
      "type": "text"
    }
  ],
  "schemaVersion": 27,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "New dashboard Copy",
  "uid": "YE4sxwXMz",
  "version": 2
}
```
