### ISSUE TITLE
Docs: Add Data links example to ElasticSearch provisioning documentation

### ISSUE THREAD

**Issue by morsik** [grafana/grafana#33086]
**What would you like to be added**:

Currently Grafana has ability to provision Data Sources, Dashboards and other stuff. But unfortunately, it's not possible (or I haven't found?!) how to provision Data Links for ElasticSearch data source. I mean this part which I'm trying to migrate to provisioned setup and I just can't.

![Screenshot from 2021-04-17 01-51-56](https://user-images.githubusercontent.com/783794/115094912-99ea3e00-9f1f-11eb-9c61-e136cd6faae0.png)

I checked those pages, and I haven't found any information about this setting:
- https://grafana.com/docs/grafana/latest/administration/provisioning/
- https://grafana.com/tutorials/provision-dashboards-and-data-sources/
- https://grafana.com/docs/grafana/latest/datasources/elasticsearch/#configure-the-data-source-with-provisioning

**Why is this needed**:

Well… to provision :)

**Comment by hugohaggmark** [comment]
Passing this to @grafana/observability-squad

**Comment by sandhose** [comment]
This seems to be actually doable. When trying out the datasources API, I noticed the `dataLinks` live under `jsonData`:

```http
GET /api/datasources
```

```json
[
  {
    "name": "ElasticSearch",
    "type": "elasticsearch",
    "more fields": "omitted",
    "jsonData": {
      "dataLinks": [
        {
          "datasourceUid": "jaeger",
          "field": "trace.id",
          "url": "${__value.raw}"
        }
      ],
      "esVersion": 70,
      "logLevelField": "log.level",
      "logMessageField": "message",
      "timeField": "@timestamp"
    }
  }
]
```

Which means something like this works:

```yaml
apiVersion: 1

datasources:
  - name: Jaeger
    uid: jaeger # Fixed UID set here
    type: jaeger
    access: proxy
    url: http://jaeger:16686

  - name: ElasticSearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: filebeat
    jsonData:
      esVersion: 70
      timeField: '@timestamp'
      logMessageField: message
      logLevelField: log.level
      dataLinks:
        - datasourceUid: jaeger # Target UID needs to be known
          field: "trace.id"
          url: "$${__value.raw}" # Careful about the double "$$" because of env var expansion
```

**Comment by ivanahuckova** [comment]
Yes it is possible. It is actually [documented in Loki](https://grafana.com/docs/grafana/latest/datasources/loki/#configure-the-data-source-with-provisioning), but we are missing documentation for Elasticsearch. 
If it is okay with you, I would change the title of this issue to **Docs: Add documentation for Elasticsearch provisioning with derived field** and pass it to @grafana/docs-squad team.

**Comment by oddlittlebird** [comment]
Heya @Elfo404, is this something you would be willing to tackle after the release?

**Comment by Elfo404** [comment]
@oddlittlebird yeah, i actually looked at this last week and forgot to assign myself, will add docs asap and ping you

**Comment by oddlittlebird** [comment]
@Elfo404, please involve @achatterjee-grafana. She is the main writer for the Grafana OSS docs.

**Comment by ivanahuckova** [comment]
To fix this, we just need to add this content right bellow ` logLevelField: fields.level` on line (currently) 248 in https://github.com/grafana/grafana/blob/main/docs/sources/datasources/elasticsearch.md: 

```
      dataLinks:
        - datasourceUid: jaeger # Target UID needs to be known
          field: "trace.id"
          url: "$${__value.raw}" # Careful about the double "$$" because of env var expansion
```

So it is going to be:

```
datasources:
  - name: elasticsearch-v7-filebeat
    type: elasticsearch
    access: proxy
    database: "[filebeat-]YYYY.MM.DD"
    url: http://localhost:9200
    jsonData:
      interval: Daily
      timeField: "@timestamp"
      esVersion: "7.0.0"
      logMessageField: message
      logLevelField: fields.level
      dataLinks:
        - datasourceUid: jaeger # Target UID needs to be known
          field: "trace.id"
          url: "$${__value.raw}" # Careful about the double "$$" because of env var expansion
```
