### ISSUE TITLE
7.5.0-Master: Unauthorized error when switching themes in the Anonymous mode

### ISSUE THREAD

**Issue by mikhailredis** [grafana/grafana#33089]
**What happened**:

It's such a cool feature! Getting Unauthorized error in the Anonymous mode when switching theme:

![Screen Shot 2021-04-17 at 11 09 28 AM](https://user-images.githubusercontent.com/47795110/115117615-8239a680-9f6d-11eb-97cb-340a689ad837.png)

![Screen Shot 2021-04-17 at 11 10 10 AM](https://user-images.githubusercontent.com/47795110/115117622-8960b480-9f6d-11eb-8ab8-c488ef4f6489.png)

**What you expected to happen**:

No Errors.

**How to reproduce it (as minimally and precisely as possible)**:

Start docker in the Anonymous mode:

```
grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_ENABLE_GZIP=true
      - GF_USERS_DEFAULT_THEME=light
```

Try to switch themes using `t t`.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.5.0-17862pre (c46f992bfb)
- Data source type & version:
- OS Grafana is installed on: Docker
- User OS & Browser:
- Grafana plugins:
- Others:
