### ISSUE TITLE
x509: failed to load system roots and no roots provided" webhook=Telegram

### ISSUE THREAD

**Issue by agn-7** [grafana/grafana#33080]
I'm using the Telegram alert notifier for alarms in Grafana but I'm dealing with the following error when an error happens or I test the Notification Chanel:

```
t=2021-04-16T17:05:41+0000 lvl=info msg="New state change" logger=alerting.resultHandler alertId=1 newState=ok prev state=alerting
t=2021-04-16T17:05:42+0000 lvl=info msg="Sending telegram notification" logger=alerting.notifier.telegram chat_id=65165282 bot_token=1757791099:AAFGifQqxDdm-dHrcxMNwtw3c5iTdjxhJNY apiAction=sendMessage
t=2021-04-16T17:05:43+0000 lvl=eror msg="Failed to send webhook" logger=alerting.notifier.telegram error="Post https://api.telegram.org/bot1757791099:AAFGifQqxDdm-dHrcxMNwtw3c5iTdjxhJNY/sendMessage: x509: failed to load system roots and no roots provided" webhook=Telegram
```

Actually, I checked this path (`/etc/ssl/certs/ca-certificates.crt`) in the Grafana container but it does not exist and when I want to create `certs` folder and copy `ca-certificates.crt` manually I encounter with the following error:

```
docker exec -it -u 0 ivms_grafana bash

# cd /etc/ssl
# mkdir certs
```

Out:

```
mkdir: cannot create directory 'certs': Read-only file system
```

Also, in order to check the Telegram API I used `curl` as follows:

```
curl https://api.telegram.org/bot1757791990:AAFGifQqxDdm-dHrcxMNwtwc35iTdjxhJNY/sendMessage\?chat_id\=65165282\&text\=Hi
```

Out:

```
curl: (77) error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
```

Also to certain that the API doesn't have any problem, I added `insecure` word to `~/.curlc` and the message was sent using `curl` successfully:

```
echo insecure >> ~/.curlc
```

---

Here's the grafana container configuration on docker-compose:

```
ivms_grafana:
  image: grafana/grafana:5.1.3
  container_name: ivms_grafana
  environment:
    - VIRTUAL_PROTO=http
    - GF_SERVER_PROTOCOL=http
    - VIRTUAL_PORT=3000
    - GF_SERVER_CERT_FILE=/etc/ssl/certificate.crt
    - GF_SERVER_CERT_KEY=/etc/ssl/nginx-selfsigned.key
 ```

**Comment by hugohaggmark** [comment]
Passing this to @grafana/backend-platform

**Comment by dsotirakis** [comment]
Hello @agn-7, I can't reproduce - meaning that I can see an actual `certs` folder inside the container and can successfully send a telegram notification. Sure you need these variables there?
```
GF_SERVER_CERT_FILE=/etc/ssl/certificate.crt
GF_SERVER_CERT_KEY=/etc/ssl/nginx-selfsigned.key
```

Maybe some overrides are happening?

**Comment by agn-7** [comment]
Hello @dsotirakis 
Do you mean I should remove those variables? If so, I tried it and I still get the same error.

in fact, there isn't this address (`/etc/ssl/certs/ca-certificates.crt`) in the grafana container.

**Comment by dsotirakis** [comment]
@agn-7 , the following happens when I run it with bash inside the Grafana container `5.1.3`

```
$~bash ls -al /etc/ssl/certs | grep ca-certificates.crt

-rw-r--r-- 1 root root 261407 May 16  2018 ca-certificates.crt
```

can't seem to find the `nginx-selfsigned.key` though.

**Comment by agn-7** [comment]
@dsotirakis 
Thank you. I rewrite a new `docker-compose` with your mentioning points as well as the `renderer` container, and the problem has been solved.

Also, here's the whole `docker-compose`:

```
version: '3.4'

services:
  nobitex_influxdb:
    image: influxdb:1.7.6
    container_name: nobitex_influxdb
    restart: unless-stopped
    ports:
      - "8087:8086"
    volumes:
      - $PWD/influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  nobitex_grafana:
    image: grafana/grafana:7.0.6
    container_name: nobitex_grafana
    restart: unless-stopped
    user: "$UID:$GID"
    environment:
      - HTTP_USER="admin"
      - HTTP_PASS="admin"
      - INFLUXDB_HOST=nobitex_influxdb
      - INFLUXDB_PORT=8087
      - INFLUXDB_NAME="nobitex"
      - INFLUXDB_USER="root"
      - INFLUXDB_PASS="root"
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_RENDERING_SERVER_URL="http://renderer:8081/render"
      - GF_RENDERING_CALLBACK_URL=http://nobitex_grafana:3003/
      - GF_LOG_FILTERS=rendering:debug
    volumes:
      - ./grafana:/var/lib/grafana
#      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - "3003:3000"
    depends_on:
      - nobitex_influxdb
      - renderer
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  renderer:
    image: grafana/grafana-image-renderer:latest
    container_name: renderer
    ports:
      - 8081
```
