### ISSUE TITLE
tencentcloud-monitor-app plugin's datasource not available in Grafana < 7.3

### ISSUE THREAD

**Issue by jamesxwang** [grafana/grafana#33116]
**What happened**: Datasource not installed for `tencentcloud-monitor-app` plugin in Grafana version 7.0 & 7.1 & 7.2.

**What you expected to happen**: Support the `tencentcloud-monitor-app` plugin in Grafana version >= 7.0.

**How to reproduce it (as minimally and precisely as possible)**:
1. Use the compose file below:
```yaml
---
version: '3'

services:
  grafana-730:
    image: grafana/grafana:7.3.0
    ports:
      - '3000:3000'
    environment:
      - GF_INSTALL_PLUGINS=tencentcloud-monitor-app
  grafana-715:
    image: grafana/grafana:7.1.5
    ports:
      - '3001:3000'
    environment:
      - GF_INSTALL_PLUGINS=tencentcloud-monitor-app
```
2. docker-compose up
3. Enable the plugin 
![image](https://user-images.githubusercontent.com/36892657/115212255-e22d7a00-a132-11eb-9975-2f441aae9542.png)
4. Search datasource `tencent`
![image](https://user-images.githubusercontent.com/36892657/115212315-f3768680-a132-11eb-9763-720b1f54e2ae.png)

In http://localhost:3000/, Datasource is available while in http://localhost:3001/ is not.

**Anything else we need to know?**: N/A

**Environment**:
- Grafana version: 7.1.x
- Data source type & version: plugin built-in datasource
- OS Grafana is installed on: MacOS (irrelevant)
- User OS & Browser: MacOS & Chrome (irrelevant)
- Grafana plugins: tencentcloud-monitor-app
- Others: N/A
