### ISSUE TITLE
Docs feedback: /getting-started/labels.md

### ISSUE THREAD

**Issue by Ruppsn** [grafana/grafana#33203]
Hello,
I believe the following is not right:

```
scrape_configs:
 - job_name: system
   pipeline_stages:
   static_configs:
   - targets:
      - localhost
     labels:
      job: syslog
      __path__: /var/log/syslog
 - job_name: system
   pipeline_stages:
   static_configs:
   - targets:
      - localhost
     labels:
      job: apache
      __path__: /var/log/apache.log
```

If i run these both with the same job_name, only the last one with the same name will be active. 
If i change it to something like this:

```
scrape_configs:
 - job_name: system
   pipeline_stages:
   static_configs:
   - targets:
      - localhost
     labels:
      job: syslog
      __path__: /var/log/syslog
 - job_name: system1
   pipeline_stages:
   static_configs:
   - targets:
      - localhost
     labels:
      job: apache
      __path__: /var/log/apache.log
```

Both rules are working.

Can someone confirm this? 

I am using promtail 2.2.1
