### ISSUE TITLE
Examplars are not working for imported prometheus data source with exemplarTraceIdDestinations configured

### ISSUE THREAD

**Issue by betorvs** [grafana/grafana#33312]
**What happened**:

Examplars are not showing Tempo Link and when I tried to access a datasource in Configurations>Data Sources (imported using grafana chart k8s-sidecar), it throws an error:
```
An unexpected error happened
TypeError: t.map is not a function
qt@http://grafana.example.local/public/build/prometheusPlugin.7d3798b26be143575eb4.js:1:62697
Ut@http://grafana.example.local/public/build/prometheusPlugin.7d3798b26be143575eb4.js:1:64091
EaOu/zt<@http://grafana.example.local/public/build/prometheusPlugin.7d3798b26be143575eb4.js:1:67639
div
t@http://grafana.example.local/public/build/DataSourceSettingsPage.7d3798b26be143575eb4.js:1:4239
form
div
div
ZGyg/m.Contents@http://grafana.example.local/public/build/app.7d3798b26be143575eb4.js:2:1728166
div
div
div
t@http://grafana.example.local/public/build/vendors~app.7d3798b26be143575eb4.js:2:1037093
m@http://grafana.example.local/public/build/app.7d3798b26be143575eb4.js:2:3052340
div
m@http://grafana.example.local/public/build/app.7d3798b26be143575eb4.js:2:1727666
t@http://grafana.example.local/public/build/DataSourceSettingsPage.7d3798b26be143575eb4.js:1:8964
O@http://grafana.example.local/public/build/vendors~app.7d3798b26be143575eb4.js:2:90047
l@http://grafana.example.local/public/build/DataSourceSettingsPage.7d3798b26be143575eb4.js:1:14478
n@http://grafana.example.local/public/build/vendors~app.7d3798b26be143575eb4.js:2:663494
t@http://grafana.example.local/public/build/app.7d3798b26be143575eb4.js:2:1800871
t/ct/h<@http://grafana.example.local/public/build/app.7d3798b26be143575eb4.js:2:2976031
t@http://grafana.example.local/public/build/app.7d3798b26be143575eb4.js:2:1962644
t@http://grafana.example.local/public/build/app.7d3798b26be143575eb4.js:2:1963174
l@http://grafana.example.local/public/build/vendors~app.7d3798b26be143575eb4.js:2:87652
```

**What you expected to happen**:

I can see the datasouce. And when I try to search using examplars enabled I can see Tempo Link. This is not working too.
I was trying to see examplars links in grafana explore view as describe here: https://github.com/betorvs/mini-observability-stack#metrics---traces---logs

**How to reproduce it (as minimally and precisely as possible)**:

I created an mini-observability-stack repository https://github.com/betorvs/mini-observability-stack

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5.4
- Data source type & version:  https://github.com/betorvs/mini-observability-stack/blob/main/deploy/grafana-manifests.yaml#L181
```
    - access: proxy
      basicAuth: false
      editable: false
      isDefault: true
      jsonData:
        disableMetricsLookup: false
        httpMethod: POST
        exemplarTraceIdDestinations:
          name: traceID
          datasourceUid: tempo
      name: prometheus
      uid: prometheus
      type: prometheus
      url: http://prometheus-k8s.monitoring.svc.cluster.local:9090/
      version: 1
 ```
- OS Grafana is installed on: grafana docker image
- User OS & Browser: Tested on Google Chrome 89 and Firefox 85
- Grafana plugins: Prometheus and Tempo datasource
- Others: 
  - grafana chart version: 6.7.1

**Comment by hugohaggmark** [comment]
Passing this over to @grafana/observability-squad

**Comment by betorvs** [comment]
hi @hugohaggmark thanks for replying it.
I received some help in grafana.slask.com and now its working:
```
- access: proxy
      basicAuth: false
      editable: false
      isDefault: true
      jsonData:
        disableMetricsLookup: false
        httpMethod: POST
        exemplarTraceIdDestinations:
          - name: traceID
            datasourceUid: tempo
      name: prometheus
      uid: prometheus
      type: prometheus
      url: http://prometheus-k8s.monitoring.svc.cluster.local:9090/
      version: 1
 ```
 I miss a "-" dash in front of name after exemplarTraceIdDestinations. 
 I will close this issue.
