### ISSUE TITLE
Data Source Error when adding "https://" on Mac | Possible Cause of CORS Error

### ISSUE THREAD

**Issue by brudnak** [grafana/grafana#33956]
**What happened**:

Having an problem with running Grafana locally when including "https://" on the URL in the datasources.yaml file

1. If the datasource.yaml file looks like this

```yaml
  # -------------------------------------------------
  # -------------------------------------------------
  # <string, required> name of the datasource. Required
- name: TEST_DATA_SOURCE
  # <string, required> datasource type. Required
  type: elasticsearch
  # <string, required> access mode. proxy or direct (Server or Browser in the UI). Required
  access: proxy
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string> url
  url: https://test-url.com/testing
  # <bool> mark as default datasource. Max one per org
  isDefault: False
  # <map> fields that will be converted to json and stored in jsonData
  database: the-test-db
  jsonData:
    httpHeaderName1: 'SOMEToken'
    timeInterval: "1m"
    esVersion: 60
    timeField: "incident.resolve.resolvedDate"
  secureJsonData:
    httpHeaderValue1: '42RandomString42'
  version: 1
  # <bool> allow users to edit datasources from the UI.
  editable: True
  # -------------------------------------------------
```

2. With this datasource.yaml file if I run

```sh
brew services restart grafana
```

3. then go to localhost:3000 and Grafana won't even load at all

![screen-shot](https://i.imgur.com/W56JmMD.png)

4. If I remove the "https://" from the yaml file like this

```yaml
  # -------------------------------------------------
  # -------------------------------------------------
  # <string, required> name of the datasource. Required
- name: TEST_DATA_SOURCE
  # <string, required> datasource type. Required
  type: elasticsearch
  # <string, required> access mode. proxy or direct (Server or Browser in the UI). Required
  access: proxy
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string> url
  url: https://test-url.com/testing
  # <bool> mark as default datasource. Max one per org
  isDefault: False
  # <map> fields that will be converted to json and stored in jsonData
  database: the-test-db
  jsonData:
    httpHeaderName1: 'SOMEToken'
    timeInterval: "1m"
    esVersion: 60
    timeField: "incident.resolve.resolvedDate"
  secureJsonData:
    httpHeaderValue1: '42RandomString42'
  version: 1
  # <bool> allow users to edit datasources from the UI.
  editable: True
  # -------------------------------------------------
```

![screen shot](https://i.imgur.com/eYDJ7qz.png)

5. Then Grafana loads and works mostly as expected [CORS ERROR]. This same issue occurs for other teammates using mac, however, the issue does not occur for teammates running windows machines.

6. This seems like it also might be causing a CORS error for teammates using mac opposed to teammates running windows that do not get a CORS error when accessing the same data source. This appears to be the only variable when accessing the same data source besides mac VS windows. With Mac devices hitting a CORS error and windows machines not getting a CORS error for the exact same data source and local setup.

**What you expected to happen**:

Be able to include ```https://``` in the URL when using localhost on a mac. This seems to be causing a CORS error for mac users.

**How to reproduce it (as minimally and precisely as possible)**:

1. Run Grafana locally on a mac using ```brew services start grafana```
2. In the data source yaml file for the URL don't include ```https://```
3. Grafana wont load at all
4. Remove the ```https://``` from the datasource.yaml file

**Anything else we need to know?**:

N/A

**Environment**:

Environment: LOCAL

- Grafana version: Latest ( 7.5.5)
- Data source type & version: Elasticsearch 6+ version
- OS Grafana is installed on: local
- User OS & Browser: macOS Big Sur Version 11.3 / Google Chrome (latest)
- Grafana plugins: N/A
- Others: N/A
