### ISSUE TITLE
Cloudwatch log queries not working after upgrading to Grafana 8.0

### ISSUE THREAD

**Issue by awsiv** [grafana/grafana#35448]
**What happened**:

Cloudwatch logs queries stopped working after upgrade to Grafana 8.0

Haven't tested in a new installation though

**What you expected to happen**:
Nothing mentioned in the changelogs about it.. so I expected it to work OOTB

**How to reproduce it (as minimally and precisely as possible)**:
1. Configure Cloudwatch datasource with "AWS SDK Default"
2. Go to Explore and do a simple CW log query on a log group (with data)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0
- Data source type & version: Cloudwatch 
- OS Grafana is installed on: Docker "grafana:latest" on fargate
- User OS & Browser: Windows/Brave
- Grafana plugins: Cloudwatch
- Others:

**Comment by csgergorubint** [comment]
Experiencing the same issue, Metrics queries are working just fine, running any log query will POST to /query, and return with 200, with the following response data:

```
{
  "results": {
    "A": {
      "frames": [
        {
          "schema": {
            "name": "A",
            "refId": "A",
            "meta": {
              "custom": {
                "channelName": "<uuid removed>"
              }
            },
            "fields": []
          },
          "data": {
            "values": []
          }
        }
      ]
    }
  }
}
``` 

**Environment:**

- [grafana helm chart](https://github.com/grafana/helm-charts/tree/main/charts/grafana) 6.12.1
- values.yaml excerpt:
```
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "<arn of the role>"

env:
  AWS_REGION: "eu-central-1"
  AWS_ROLE_ARN: "<arn of the role>"
  AWS_WEB_IDENTITY_TOKEN_FILE: "/var/run/secrets/eks.amazonaws.com/serviceaccount/token"
  

datasources:
 datasources.yaml:
   - name: CloudWatch
     type: cloudwatch
     access: proxy
     jsonData:
       authType: "default"
       defaultRegion: "default"
```
- IAM policy attached to the role
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "tag:GetResources",
                "logs:StopQuery",
                "logs:StartQuery",
                "logs:GetQueryResults",
                "logs:GetLogGroupFields",
                "logs:GetLogEvents",
                "logs:DescribeLogGroups",
                "ec2:DescribeTags",
                "ec2:DescribeRegions",
                "ec2:DescribeInstances",
                "cloudwatch:ListMetrics",
                "cloudwatch:GetMetricStatistics",
                "cloudwatch:GetMetricData",
                "cloudwatch:DescribeAlarmsForMetric",
                "cloudwatch:DescribeAlarms",
                "cloudwatch:DescribeAlarmHistory"
            ],
            "Resource": "*"
        }
    ]
}
```
