### ISSUE TITLE
Grafana pods not come up after enabling existingClaim in Grafana v8.0.0

### ISSUE THREAD

**Issue by skokkira** [grafana/grafana#35473]
Below is the info enabled in grafana chart:

apiVersion: v2
name: grafana
version: 6.12.0
appVersion: 8.0.0
kubeVersion: '^1.8.0-0'

persistence:
  type: pvc
  enabled: true
  existingClaim: grafana-pvc**

output:
[<id>@<hostname> grafana]$ kubectl get all -n <namespace>
NAME              TYPE       CLUSTER-IP    EXTERNAL-IP   PORT(S)        AGE
service/grafana   NodePort   10.96.42.44   <none>        80:xxxx/TCP   9s

NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/grafana   0/1     0            0           9s

NAME                                 DESIRED   CURRENT   READY   AGE
replicaset.apps/grafana-5474db49fd   1         0         0       9s
[id@hostname grafana]$

**Comment by grafanabot** [comment]
Thanks for creating this issue! We think it's missing some basic information. 

Follow the issue template and add additional information that will help us replicate the problem. 
For data visualization issues: 
- Query results from the inspect drawer (data tab & query inspector)
- Panel settings can be extracted in the panel inspect drawer JSON tab

For dashboard related issues: 
- Dashboard JSON can be found in the dashboard settings JSON model view

For authentication, provisioning and alerting issues, Grafana server logs are useful. 

Happy graphing!

**Comment by grafanabot** [comment]
Thanks for creating this issue! We think it's missing some basic information. 

Follow the issue template and add additional information that will help us replicate the problem. 
For data visualization issues: 
- Query results from the inspect drawer (data tab & query inspector)
- Panel settings can be extracted in the panel inspect drawer JSON tab

For dashboard related issues: 
- Dashboard JSON can be found in the dashboard settings JSON model view

For authentication, provisioning and alerting issues, Grafana server logs are useful. 

Happy graphing!

**Comment by zuchka** [comment]
Hi @skokkira,

I was not able to reproduce this. I followed these instructions and I was able to deploy the same Grafana chart version with an existingClaim and the pods didn't hang.

Can you please share your full values.yaml? Was your setup working before on an earlier version?

If you use `kubectl describe deployment` do you see any interesting information?

**Comment by zuchka** [comment]
grafana-pv.yaml

```
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-prom-grafana-0
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  storageClassName: grafana
```

grafana-pvc.yaml

```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

values.yaml

```
---
apiVersion: v1
grafana:
  enabled: true

  persistence:
    type: pvc
    enabled: true
    # annotations: {}
    finalizers:
      - kubernetes.io/pvc-protection
    existingClaim: prom-grafana
```
