### ISSUE TITLE
Prometheus provisioning:  setting the httpMethod has no effect

### ISSUE THREAD

**Issue by tensorchen** [grafana/grafana#35621]
![image](https://user-images.githubusercontent.com/16510475/121874775-46874700-cd3a-11eb-8731-aa7b744da962.png)

![image](https://user-images.githubusercontent.com/16510475/121874865-5c950780-cd3a-11eb-8502-e2e0d9f9c529.png)

**Environment**:
- Grafana version: 8.0.1

**Comment by torkelo** [comment]
it should be under jsonData

example: 

```yaml
  - name: gdev-prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    jsonData:
      httpMethod: GET
```
