### ISSUE TITLE
[CloudWatch Datasource] Can't access AWS resources with service account auth (OIDC) in EKS

### ISSUE THREAD

**Issue by yongzhang** [grafana/grafana#35974]
**What happened**:
Can't access AWS metrics and cloudwatch logs (AWS China), see below errors in grafana:
```
"t=2021-06-21T01:56:42+0000 lvl=eror msg=\"Metric request error\" logger=context userId=4 orgId=1 uname=whatever error=\"failed to query data: WebIdentityErr: failed to retrieve credentials\\ncaused by: InvalidIdentityToken: OpenIDConnect provider's HTTPS certificate doesn't match configured thumbprint\\n\\tstatus code: 400, request id: c83ca487-9b6a-4d3a-a9a4-fe75f4ce036f\" remote_addr=10.10.10.10\n"
```
It works in grafana version 7.x, but broken in 8.x

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Add cloudwatch datasource:

![image](https://user-images.githubusercontent.com/15604715/122707528-c2c6e080-d28c-11eb-9dd3-84bcd6ac34d0.png)

service account in EKS:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws-cn:iam::my_aws_account:role/grafana-dev
  name: grafana
  namespace: dev
```

Import dashboard RDS and go to the page:

![image](https://user-images.githubusercontent.com/15604715/122726162-535eea00-d2a8-11eb-8e65-02f677bde8a4.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: CloudWatch
- OS Grafana is installed on: Container in AWS EKS (grafana:grafana:8.0.3)
- User OS & Browser: Chrome
- Grafana plugins: CloudWatch
- Others:
