### ISSUE TITLE
404 not found when creating cortex alerting rule in Grafana UI

### ISSUE THREAD

**Issue by kevinschoonover** [grafana/grafana#35977]
**What happened**:
Hello! I am not sure if this is due to my configuration or not, but whenever I try to create a Cortex managed rule in the grafana 8.0.3 UI, I get the following error:
![image](https://user-images.githubusercontent.com/17842707/122718040-49de6f00-d221-11eb-9010-b2ce4357b32d.png)

I see in the cortex logs that it is making a request to `prometheus/rules/*` instead of `api/v1/rules/*`
![image](https://user-images.githubusercontent.com/17842707/122718088-59f64e80-d221-11eb-8518-7cbb3bcd98bd.png)

Looking at the [cortex HTTP API docs](https://cortexmetrics.io/docs/api/#get-rule-group), this does seem to be expected behavior for the /api/prom prefix; however, if I change the datasource from 

```yml
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://cortex.service.dc1.consul:9009/prometheus
    jsonData:
      exemplarTraceIdDestinations:
      - name: traceID
        datasourceUid: tempo
```

to

```yml
apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://cortex.service.dc1.consul:9009/api/prom
    jsonData:
      exemplarTraceIdDestinations:
      - name: traceID
        datasourceUid: tempo
```

I can no longer use it as a data source for creating alerts
![image](https://user-images.githubusercontent.com/17842707/122718472-d721c380-d221-11eb-8f43-52dd07f47b71.png)

Is this a configuration issue on my side or is there any other information I can provide to help diagnose?

**How to reproduce it (as minimally and precisely as possible)**:

grafana datasource file:
```yml
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://cortex.service.dc1.consul:9009/prometheus
    jsonData:
      exemplarTraceIdDestinations:
      - name: traceID
        datasourceUid: tempo
```

cortex configuration:
```yml
auth_enabled: false

server:
  http_listen_port: 9009

  # Configure the server to allow messages up to 100MB.
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  grpc_server_max_concurrent_streams: 1000

...

ruler:
  enable_api: true
  enable_sharding: false
  storage:
    type: local
    local:
      directory: /data/rules
```
