### ISSUE TITLE
[ngalert] validation error after converting old Telegram settings to ngalert

### ISSUE THREAD

**Issue by waterdrop01** [grafana/grafana#36079]
I upgraded to Grafana V8 and enabled ngalert feature.

My previous Telegram settings have been automatically converted to a "contact point":
![Screenshot from 2021-06-23 16-47-32](https://user-images.githubusercontent.com/47316824/123118223-bb493800-d442-11eb-9048-d45035b20cb8.png)

But I can't delete it, edit it, or create a new contact point (be it a Telegram one, or any other type like email).

Here is the message I receive each time I do one of the above actions (ie click on blue button "Save contact point"):

![Screenshot from 2021-06-23 16-07-27](https://user-images.githubusercontent.com/47316824/123111381-28f26580-d43d-11eb-8d77-95b817d49acf.png)

```
t=2021-06-27T13:08:26+0000 lvl=eror msg="unable to sync configuration" logger=alertmanager err="unable to reload configuration: alert validation error: Could not find Bot Token in settings"
```

I suppose it's because of this [code](https://github.com/grafana/grafana/blob/main/pkg/services/alerting/notifiers/telegram.go).

Any idea on how to fix this? (manually is fine).

Thanks!

**Comment by gotjosh** [comment]
> Any idea on how to fix this? (manually is fine).

If you have access to the database, you can truncate the alertmanger configuration table and we'll apply the default config upon restarting.

**Comment by waterdrop01** [comment]
@gotjosh thanks for your feedback. 

Yes I have access to the server. Could you give some more guidance regarding the operation?

- Is the database an sqlite file, and if yes where is the .sqlite located?
- What kind of SQL statement should I run to "truncate" the alertmanager part of the database?

Thanks a lot for your help!

**Comment by waterdrop01** [comment]
For info, I exec into the kubernetes grafana running container.

Found the `grafana.db` file (under `/var/lib/grafana`)

However, as we can see in the [Dockerfile](https://github.com/grafana/grafana/blob/v8.0.3/Dockerfile), Alpine is used, and sqlite3 is not installed.

I can't login as the **root** user...and so can't run `apk add sqlite3`.

Any idea how to fix the alertmanager bug?

Thanks

**Comment by waterdrop01** [comment]
Finally manually fixed it:

my grafana is using local sqlite3 db `/var/lib/grafana/grafana.db`. But as it's not possible to `exec` as root in the grafana running container, here is what I did:

I deployed the below ubuntu pod and attached it to grafana pvc:
```
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  volumes:
    - name: ubuntu-pv-claim
      persistentVolumeClaim:
        claimName: grafana
  containers:
    - name: ubuntu
      image: ubuntu
      command: ["/bin/sleep", "3650d"]
      volumeMounts:
        - mountPath: "/var/lib/grafana"
          name: ubuntu-pv-claim
```
and then, as sqlite3 doesn't support `TRUNCATE`, I ran `DELETE FROM alert_configuration;`

Finally, my alerts are back!!!
