### ISSUE TITLE
[Grafana v8] Errors loading rules Failed to load rules state from Loki: 404 page not found 

### ISSUE THREAD

**Issue by waterdrop01** [grafana/grafana#36091]
I upgraded an existing Grafana installation to v8 and enabled `ngalert`.

When navigating to `/alerting/list`, I see this message:

![Screenshot from 2021-06-23 19-19-59](https://user-images.githubusercontent.com/47316824/123140902-1e919500-d458-11eb-9271-d2b406ff0c09.png)

Loki is one of my datasources. However I don't know why Grafana is complaining? I never used Loki alert rules so far (through cortex).

I guess it's a bug...?

**Comment by zuchka** [comment]
Hi @waterdrop01,

Thank you for reporting this. 

For the internal squads, I'm seeing similar errors:

[here](https://admin-dev-us-central-0.grafana.net/grafana/alerting/list)
and 
[here](https://g80-beta.grafana.net/alerting/list)

If you have admin privileges, you can also recreate it on play.grafana.org:

* add a Loki datasource. The configuration test can fail.
* navigate to `alerting/list`. the page throws an error
* remove the Loki datasource and the error disappears

also reproducible on a fresh instance with properly configure Loki datasource. Here's a docker-compose that will throw same error:

```
version: "3"

networks:
  grafana:

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
    networks:
      - grafana

  loki:
    image: grafana/loki:latest
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - grafana

  promtail:
    image: grafana/promtail:latest
    networks:
      - grafana

  grafana:
    image: grafana/grafana:main
    ports:
      - 3000:3000
    networks:
      - grafana
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=ngalert

  node:
    image: prom/node-exporter:latest
    ports:
      - 9100:9100
    networks:
      - grafana
```

* build containers
* check `alerting/list` : loads fine; no errors
* add Loki datasource
* set `http://loki:3100` for `URL`
* test and save (connection should succeed)
* check `alerting/list`; throws error
