### ISSUE TITLE
Alerting: Provisioning of notifiers/contact points not working on Grafana 8

### ISSUE THREAD

**Issue by dpasqualin** [grafana/grafana#36153]
Hi, first of all good job on Grafana 8, the new alerting system is very promising.

I found what seems to be a bug in the provisioning of notifiers. I use this file below on Grafana 7.x and it successfully adds a notifier as specified. However, using the same file in the same directory with Grafana 8 it doesn't add a notifier (which I believe now is called a contact point?). I don't see any errors in the log, it is like the file is not being read.

I'm installing grafana from the debian repository, version 8.0.4, copying the file to `/usr/share/grafana/conf/provisioning/notifiers/` and restarting the server.

```
notifiers:
  - name: AlertManager
    type: prometheus-alertmanager
    uid: notifier1
    org_id: 1
    is_default: true
    send_reminder: true
    frequency: 1h
    disable_resolve_message: false
    settings:
      url: <url to our alertmanager>
```

**Environment**:
- Grafana version: 8.0.4
- OS Grafana is installed on: debian stretch

Thank you for your time.

**Comment by davidmparrott** [comment]
@zuchka currently, provisioning is not supported for Grafana 8 alerts. We made a choice to not include this in the feature preview.

**Comment by AverageMarcus** [comment]
@davidmparrott Is provisioning planned for ngalerts in the future? I've tried to find a relevant issue but can't seem to see anything other than this one that relates to it. Would love to be able to track progress / contribute where I can.

**Comment by Fockaert** [comment]
@davidmparrott Could you please share when we can expect the final version of the new Grafana 8 alerts (assuming provisioning is supported)?

**Comment by kylebrandt** [comment]
@Fockaert The current plan is that new Grafana 8 alerting will become the default before we have resolved provisioning (8.2/8.3). When this happens, legacy alerting will still be available but the default system will be switched (flag will be needed for legacy, instead of currently flag is needed of 8/NG alerting). To get to that default we need Multi-instance Grafana (HA) alerting, and org isolation working. However, provisioning is the next major priority after those things are accomplished - so perhaps 8.4/8.5 is a reasonable estimate at this time.

I think @armandgrillet can verify if I am off on any of what I am saying there.

**Comment by Fockaert** [comment]
Thx @kylebrandt , more clear on my end already

**Comment by grafanabot** [comment]
This issue was removed from the 8.5.0-beta1 milestone because 8.5.0-beta1 is currently being released.

**Comment by bensoille** [comment]
FYI the following issue provides with a solution : https://github.com/grafana/grafana/issues/50632

**Comment by visit1985** [comment]
@bensoille thanks, for the workaround – I wouldn't call it solution. :wink:

**Comment by stevenr-ookla** [comment]
Made an AlertRule PR for this https://github.com/grafana/grafana-api-golang-client/pull/91

**Comment by grafanabot** [comment]
This issue was removed from the 9.1.0 milestone because 9.1.0 is currently being released.

**Comment by armandgrillet** [comment]
A blog post regarding this has been published: https://grafana.com/blog/2022/08/25/new-in-grafana-alerting-file-provisioning/

**Comment by Slach** [comment]
@armandgrillet @JohnnyQQQQ 
 https://grafana.com/blog/2022/08/25/new-in-grafana-alerting-file-provisioning/
looks useless
where is the real example with real queries and real data sources for yaml files for alerting provisioning?

```
provisioning.yaml: |
    templates:
    - name: my_first_template
      template: the content for my template 
```

this is not a real example    

moreover, https://github.com/grafana/grafana/tree/main/pkg/services/provisioning/alerting/testdata/alert_rules  
still not contains any real queries and query types

Could you provide any real queries for any real data sources for example?

**Comment by streetstorm** [comment]
@Slach 
Doc: https://grafana.com/docs/grafana/latest/administration/provisioning/#alerting
Here is my example, it works:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alerting
data:
  provisioning.yaml: |
    templates:
    - name: send_message
      template: |
        {{ define "send_message" }}
          {{- if gt (len .Alerts.Firing) 0 }}
            {{- len .Alerts.Firing }} firing:
            {{- range .Alerts.Firing }} {{ template "mymessage" .}} {{ end }}
          {{- end }}
          {{- if gt (len .Alerts.Resolved) 0 }}
            {{- len .Alerts.Resolved }} resolved:
            {{- range .Alerts.Resolved }} {{ template "mymessage" .}} {{ end }}
          {{- end }}
        {{- end }}
    - name: mymessage
      template: |
        {{ define "mymessage" }}
          [{{.Status}}] {{ .Labels.alertname }}
          {{- if gt (len .Annotations) 0 }}
          Annotations:
          {{- range .Annotations.SortedPairs }}
            {{ .Name }}: {{ .Value }}
          {{- end }}
          {{- end }}

          {{- if gt (len .DashboardURL ) 0 }}
          Go to dashboard: {{ .DashboardURL }}
          {{- end }}
          {{- if gt (len .PanelURL ) 0 }}
          Go to panel: {{ .PanelURL }}
          {{- end }}
          {{- if gt (len .SilenceURL ) 0 }}
          Silence alert: {{ .SilenceURL }}
          {{- end }}
        {{- end }}
    contactPoints:
      - name: slack_monitoring
        receivers:
          - uid: slack_uid_1
            type: slack
            settings:
              recipient: ""
              token: ""
              username: ""
              icon_emoji: ""
              icon_url: ""
              mentionUsers: ""
              mentionGroups: ""
              mentionChannel: here
              url: https://hooks.slack.com/
              endpointUrl: ""
              title: |
                [{{ len .Alerts.Firing }} FIRING], [{{ len .Alerts.Resolved }} RESOLVED]
              text: |
                {{ template "send_message" . }}
    policies:
      - receiver: slack_monitoring
        matchers:
          - alertchannel = slack
          - severity =~ "warning|critical"
        group_wait: 30s
        group_internval: 5m
        repeat_interval: 4h
        routes:
          - receiver: slack_monitoring
            matchers:
              - alertchannel = slack
              - severity =~ "warning|critical"
```

**Comment by Slach** [comment]
opps sorry, I miss something
I search documentation about how to provision ALERTS, not alerts message templates and notification channels
and https://github.com/grafana/grafana/tree/main/pkg/services/provisioning/alerting/testdata/alert_rules doesn't help

**Comment by streetstorm** [comment]
@Slach 
API /api/v1/provisioning/alert-rules/{rule_id} helps to prepare this ALERT RULE
```
    groups:
      - name: Microservices
        folder: Microservices
        interval: 60s
        rules:
          - uid: micro_svc_1
            title: "Deployment status replicas available"
            condition: condition
            data:
              - refId: query
                relativeTimeRange:
                  from: 900
                  to: 0
                datasourceUid: '00000000002'
                model:
                  expr: "kube_deployment_status_replicas_available"
                  intervalMs: 15000
                  legendFormat: "{{ deployment }} - {{ namespace }}"
                  maxDataPoints: 43200
                  refId: query
              - refId: reduced
                datasourceUid: '-100'
                model:
                  expression: query
                  intervalMs: 1000
                  maxDataPoints: 43200
                  reducer: last
                  refId: reduced
                  type: reduce
              - refId: condition
                datasourceUid: '-100'
                model:
                  expression: "$$reduced < 1"
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: condition
                  type: math
            dashboardUid: UID
            panelId: ID
            noDataState: Alerting
            for: 5m
            annotations:
              Message: ""
            labels:
              alertchannel: slack
              severity: critical
```
