### ISSUE TITLE
"Not allowing oauth_github login", but I added auth.github in the config

### ISSUE THREAD

**Issue by waterdrop01** [grafana/grafana#36195]
Hello,

I have grafana v8.0.3 installed using its official helm chart (v6.13.5).

I used to have github oauth login working well, after adding below code to the `grafana-values.yml` file:
```
grafana.ini:
  auth.github:
    enabled: true
    allow_sign_up: false
    scopes: user:email,read:org
    auth_url: https://github.com/login/oauth/authorize
    token_url: https://github.com/login/oauth/access_token
    api_url: https://api.github.com/user
    team_ids: 
    allowed_organizations: my-org
    client_id: my_id
    client_secret: my_secret
```
Here is the error message logged by grafana container when a github user of `my-org` clicks on the "login with github" button:

```
t=2021-06-26T21:42:49+0000 lvl=warn msg="Not allowing oauth_github login, user not found in internal user database and allow signup = false"
t=2021-06-26T21:42:49+0000 lvl=eror msg="invalid username or password" logger=context userId=0 orgId=0 uname=
t=2021-06-26T21:42:49+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/github status=302 remote_addr=100.64.2.233 time_ms=868 size=29 referer=https://grafana.my.fqdn/
```
Clearly the "Not allowing oauth_github login" part of the error is wrong (conflicting with the actual configuration).

I can still login with the existing user (as it's already in base I guess) but any new user (belonging to the my-org organization) can't.

Anyone also experiencing this issue? 

Thank you

**Environment**:
- Grafana version: 8.0.3
- OS Grafana is installed on: Kubernetes
- User OS & Browser: Firefox
- Grafana plugins: No plugins
