### ISSUE TITLE
Data source provisioning breaks alerts

### ISSUE THREAD

**Issue by FireEmerald** [grafana/grafana#36328]
**What happened**:
Using the provisioning like explained [here](https://grafana.com/docs/grafana/latest/administration/provisioning/#example-data-source-config-file) in the documentation to load data sources like this:
``` yaml
# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Db1
    orgId: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:
  - name: Db1
    type: postgres
    orgId: 1
    uid: db-01
(...)
```
Works as intended **until** you create a panel using the datasource and add a alert to it. If you now restart the grafana container you will get the following error (repeating):
``` log
t=2021-07-01T06:42:51+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=1 name="My alert" error="could not find datasource: data source not found" changing state to=alerting
t=2021-07-01T06:43:01+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=1 name="My alert" error="could not find datasource: data source not found" changing state to=alerting
```

**What you expected to happen**:
I expected that the example from the documentation page works well, especially using `deleteDatasources` in combination with `datasources`.

**How to reproduce it (as minimally and precisely as possible)**:
1. Startup grafana as container with a datasource deployed using provisioning.
2. Create a dashboard with a panel using the provisioned data source and create a alert.
3. Save dashboard, restart grafana container and see the error in the logs of the container.

**Anything else we need to know?**:
I think the issue is that the `data_source.id` is increased on startup, due to the deletion of the existing data source and re-creation.

The grafana database table `data_source` contains the column `id` which is `1` on the first startup and `2` on the second. 
Normally this is fine, but in the `alert` table in column `settings` we store the old id `1` which does not exist anymore:

alert.id | alert.name | alert.settings
--|--|--
1 | My alert | {"alertRuleTags":{},"conditions":[{ (...) "query":{"datasourceId":1,"model": (...)

References: #10843, #13004

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: postgres
- OS Grafana is installed on: linux, docker
- User OS & Browser: windows, chrome
