### ISSUE TITLE
Error loading Cortex alertmanager rules via Grafana UI (404 page not found)

### ISSUE THREAD

**Issue by aarepuu** [grafana/grafana#36337]
**What happened**:
Hi. I'm trying to use Grafana 8 to manage Cortex alerts (running in local k8s cluster), but getting 404 when trying to connect to my `ruler`. I'm not sure if that's a configuration issue or am I missing something. Seen similar issues reported in #35977 and #36074.

<img width="1914" alt="Screenshot 2021-07-01 at 08 25 50" src="https://user-images.githubusercontent.com/1277660/124086478-ff42cb00-da48-11eb-9904-1f343462a7b6.png">

Grafana logs show that the url that it's trying to hit is `/api/prometheus/1/api/v1/rules`:

![Screenshot 2021-07-01 at 08 54 00](https://user-images.githubusercontent.com/1277660/124087707-28179000-da4a-11eb-8115-d5e1dbffc4ea.png)

I can see the Cortex datasource in the dropdown when creating a new alert, but getting 404 when adding alerts:

<img width="961" alt="Screenshot 2021-07-01 at 08 51 09" src="https://user-images.githubusercontent.com/1277660/124087873-56956b00-da4a-11eb-9161-b67c7de873da.png">

When I logged into Grafana pod and tried to connect to ruler api direct it seems to get a response:
```bash
> rules=$(wget -O - http://ruler/prometheus/api/v1/rules --header 'X-Scope-OrgID: local-test'); echo $rules
{"status":"success","data":{"groups":[]},"errorType":"","error":""}
````
Is there an issue with my configuration and is there any ways I can diagnose it better?

**How to reproduce it (as minimally and precisely as possible)**:

`grafana` config (using helm chart):
```yml
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: local-test
        type: prometheus
        url: http://query-frontend/api/prom
        access: proxy
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "local-test"
grafana.ini:
  feature_toggles:
    enable: ngalert
```

`ruler` config:
```yml
ruler:
  alertmanager_url: http://alertmanager/api/prom/alertmanager/
  enable_api: true
  enable_alertmanager_v2: true
  storage:
    configdb:
      configs_api_url: http://configs:80
ruler_storage:
  backend: configdb
  configdb:
    configs_api_url: http://configs:80
```

**Anything else we need to know?**:

**Environment**:
- Grafana version:  8.0.3
- Data source type & version: Cortex v1.9.0
- OS Grafana is installed on: docker-desktop k8s using Grafana [helm-charts](https://github.com/grafana/helm-charts)
- User OS & Browser: MacOS 10.14 and Chrome 91.0.4472.114
