### ISSUE TITLE
how to skip TLS verification for plugins installation via docker ?

### ISSUE THREAD

**Issue by xmlking** [grafana/grafana#36492]
I have my `docker-compose` https://github.com/xmlking/micro-apps/blob/develop/infra/redis.yml  to install  plugins via GF_INSTALL_PLUGINS
it works fine from the home network. but getting `x509: certificate signed by unknown authority` error when running same from behind corp proxy. 
**is there a  way to configure skip `TLS` verification for plugins ?**

```yml
  grafana:
    image: grafana/grafana:8.0.4
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_ENABLE_GZIP=true
      - GF_USERS_DEFAULT_THEME=dark
      - GF_INSTALL_PLUGINS=redis-datasource,redis-app
      # defend following secrets in .env and don't commit `.env` file to git.
      - REDIS_CLOUD_HOST
      - REDIS_CLOUD_PASSWORD
    volumes:
      - ./grafana/provisioning/datasources/:/etc/grafana/provisioning/datasources/
      - ./grafana/provisioning/dashboards/:/etc/grafana/provisioning/dashboards/
      - grafana:/var/lib/grafana
    links:
      - redis
    depends_on:
      - redis
```

```
grafana_1  | Error: ✗ Failed to send request: Get "https://grafana.com/api/plugins/repo/redis-datasource": x509: certificate signed by unknown authority
grafana_1 exited with code 1
insight_1  | error uploading: HTTPSConnectionPool(host='api.segment.io', port=443): Max retries exceeded with url: /v1/batch (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))
```
