### ISSUE TITLE
grafana-cli does not install plugin into directory specified by GF_PATHS_PLUGINS

### ISSUE THREAD

**Issue by jkager** [grafana/grafana#36502]
**What happened**:
When running Grafana in Docker with the environment variable `GF_PATHS_PLUGINS` set to a non-standard path, the command `grafana-cli plugins install` will not install plugins into the directory indicated by the environment variable, but to the default path (`/var/lib/grafana/plugins`). As a result, the installed plugin won't be available in the user interface.

**What you expected to happen**:
`grafana-cli` should use the path indicated by the environment variable and install plugins into that directory.

**How to reproduce it (as minimally and precisely as possible)**:
Create `docker-compose.yml`:

````
version: "3"

services:
  grafana:
    image: grafana/grafana:8.0.4
    environment:
      - GF_PATHS_PLUGINS=/opt/plugins
    volumes:
      - ./plugins:/opt/plugins
    ports:
      - "3000:3000"
````

````
mkdir plugins
docker-compose up -d
docker-compose exec grafana grafana-cli plugins install marcusolsson-json-datasource
docker-compose exec grafana ls -l plugins
docker-compose exec grafana ls -l /var/lib/grafana/plugins
````

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.4
- Data source type & version: marcusolsson-json-datasource 1.2.1
- OS Grafana is installed on: Ubuntu 21.04 / Docker
- User OS & Browser: Ubuntu 21.04
- Grafana plugins: marcusolsson-json-datasource 1.2.1
- Others:
