### ISSUE TITLE
admin credentials set in env by secret doesn't work

### ISSUE THREAD

**Issue by EHP4321** [grafana/grafana#37234]
Sorry If Im just doing it wrong. But it seems like this should work, since the env variables get set correctly also when its a secret, and changing login works when its not a secret.

**What happened**:
I followed this guide https://grafana.com/docs/grafana/latest/installation/kubernetes/
And everything worked as it should, I could log into grafana with the default admin user and password
Then I change default admin user and password in grafana.yaml by inserting this:
```
          env:
          - name: GF_SECURITY_ADMIN_USER
            value: ...
          - name: GF_SECURITY_ADMIN_PASSWORD
            value: ...
```
on a new line below `imagePullPolicy: IfNotPresent`
Again everything works as expected, I can log into grafana with my chosen admin user and password
I can change it as many times as I want, as long as I delete the deployment and pvc before applying, I can login to grafana with the changed user and password as expected.
The problem happens when I try to use a secret.
I add this secret:
```
apiVersion: v1
kind: Secret
metadata:
  name: grafana-login-secret
data:
  username: ...
  password: ...
```
Where user and password is in base64.
And I replace the first change in grafana.yaml with this:
```
          env:
          - name: GF_SECURITY_ADMIN_USER
            valueFrom:
              secretKeyRef:
                key: username
                name: grafana-login-secret
          - name: GF_SECURITY_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: grafana-login-secret
```
This time env variables in the pod gets set correctly, but I cannot login to grafana. Not with the login I have set, and not with the default (admin, admin) login.
I have deleted pvc. I do exactly the same as when I changed the plaintext password, which works.

**What you expected to happen**:
I expected the default admin password to be set to the env variable GF_SECURITY_ADMIN_PASSWORD, also when that variable was set to a value that comes from a secret.

**How to reproduce it (as minimally and precisely as possible)**:
Take the grafana.yaml from here https://grafana.com/docs/grafana/latest/installation/kubernetes/
And add env variables for setting admin user and password to it, set their value to come from a secret.
Or just use mine below.

**Anything else we need to know?**:
This is my full grafana.yaml
```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
        - 0    
      containers:
        - name: grafana
          image: grafana/grafana:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: GF_SECURITY_ADMIN_USER
            valueFrom:
              secretKeyRef:
                key: username
                name: grafana-login-secret
          - name: GF_SECURITY_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: grafana-login-secret
          ports:
            - containerPort: 3000
              name: http-grafana
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1            
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-pv

      volumes:
        - name: grafana-pv
          persistentVolumeClaim:
            claimName: grafana-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http-grafana
  selector:
    app: grafana
  sessionAffinity: None
  type: LoadBalancer

```

**Environment**:
- Grafana version: I have tried 7.5.2, 8.0.6 and 8.1.0-beta2 with same result
- OS Grafana is installed on: its the grafana/grafana docker deployed in microk8s
- User OS & Browser: Ubuntu 20, Brave web browser

**Comment by zuchka** [comment]
Hi @EHP4321 

Thanks for making this issue. I just ran the following yaml file on Minikube and it worked as expected. After applying this and then port forwarding the Grafana server, I was able to log in with username: `test` and password : `1f2d1e2e67df`:

```
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-login-secret
data:
  username: dGVzdA==
  password: MWYyZDFlMmU2N2Rm
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
        - 0    
      containers:
        - name: grafana
          image: grafana/grafana:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: GF_SECURITY_ADMIN_USER
            valueFrom:
              secretKeyRef:
                key: username
                name: grafana-login-secret
          - name: GF_SECURITY_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: grafana-login-secret
          ports:
            - containerPort: 3000
              name: http-grafana
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1            
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-pv

      volumes:
        - name: grafana-pv
          persistentVolumeClaim:
            claimName: grafana-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http-grafana
  selector:
    app: grafana
  sessionAffinity: None
  type: LoadBalancer
```

maybe you are applying your secrets a different way? Do you get the same response if you test on minikube?
