### ISSUE TITLE
provisioned dashboard can be modified by UI

### ISSUE THREAD

**Issue by clux** [grafana/grafana#37679]
**What happened**:
Dashboard loaded through a provider can be updated through its json model tab despite `allowUiUpdates: false`.

**What you expected to happen**:
That we cannot save the dashboard through the interface when setting `allowUiUpdates: false`.

**How to reproduce it (as minimally and precisely as possible)**:
- Edit a provisioned dashboard
- Click save, and on the popup for [cannot save provisioned dashboard](https://grafana.com/static/img/docs/v51/provisioning_cannot_save_dashboard.png), copy the json
- Go to the dashboard's JSON Model
- Paste the JSON
- Click Save Changes

We can now verify that a new version exists under Versions
![Screenshot from 2021-08-09 10-08-11](https://user-images.githubusercontent.com/134092/128683390-b8b3d588-6ed3-4dcf-90b5-16a123f7920a.png)

**Anything else we need to know?**:

Probably a consequence of https://github.com/grafana/grafana/issues/26620

**Environment**:
- Grafana version: 8.0.5
- Data source type & version:

```
  provider.yaml: |-
    apiVersion: 1
    providers:
    - name: 'sidecarProvider'
      orgId: 1
      type: file
      disableDeletion: false
      allowUiUpdates: false
      updateIntervalSeconds: 30
      options:
        foldersFromFilesStructure: true
        path: /tmp/dashboards
```

- OS Grafana is installed on:

`grafana/grafana:8.0.5` through `kube-prometheus-stack`

- User OS & Browser:

Linux + Chrome.
