### ISSUE TITLE
InfluxDb certificate error when upgrade from 8.0.2 to 8.1.0

### ISSUE THREAD

**Issue by Oscar-Young** [grafana/grafana#37683]
**What happened:**
Upgrade from 8.0.2 to 8.1.0, And Alert chart using influxdb  to report the `certificate signed by unknown authority`
When I rolled back to version 8.0.2, everything was fine.

**What you expected to happen:**
I want to understand what happened.

**How to reproduce it (as minimally and precisely as possible):**

- Alarm chart using influxdb.
- Influxdb : use certificates or expired certificates ( or other ? )

**Environment:**

docker-compose.yaml:

```YAML
version: "3"
services:
  grafana:
    container_name: grafana
    image: grafana/grafana:8.0.2
    user: "0"
    ports:
      - "5001:5001"
    volumes:
      - ./grafana:/var/lib/grafana
      - ./etc/grafana:/etc/grafana
```
