### ISSUE TITLE
[Bug] "user not a member of one of the required groups"/"login.OAuthLogin(get info from azuread)"  from Azure AD

### ISSUE THREAD

**Issue by yashwanth-l** [grafana/grafana#37693]
@m4c3 @salihzett @pihai - Can you please check why on doing on the 2 tasks I still see the issue of `user not a member of one of the required groups` in the trace logs while in UI it is `login.OAuthLogin(get info from azuread)`

1. App Manifest has `appRoles` ==> ` Viewer` and `Admin` config
2. App Manifest has `"groupMembershipClaims": "ApplicationGroup, SecurityGroup"`
3. Adding the Group Claim in Token Config of the Azure App.

What am I still missing here?

grafana.ini file is as follows:

```
auth.azuread:
      name: "Azure AD"
      enabled: true
      allow_sign_up: false
      client_id: "${aad_client_id}"
      client_secret: "${aad_client_secret}"
      scopes: "openid email profile"
      auth_url:  https://login.microsoftonline.com/${tenant_id}/oauth2/v2.0/authorize
      token_url: https://login.microsoftonline.com/${tenant_id}/oauth2/v2.0/token
      signout_redirect_url: https://login.microsoftonline.com/${tenant_id}/oauth2/logout?post_logout_redirect_uri=https://${grafana_fqdn}
      allowed_domains: ${tenant_domain}
      allowed_groups: "${aad_groups}"
```
