### ISSUE TITLE
Dashboard URL by title does not seem work as expected

### ISSUE THREAD

**Issue by datamattsson** [grafana/grafana#37813]
I'm trying to produce two separate dashboards that should be importable into any Grafana instance and I should be able to link between them regardless of `uid`.

**What happened**:
Entered `dashboard/db/test` in the URL to my "test" dashboard.

**What you expected to happen**:
My "test" dashboard to display.

**How to reproduce it (as minimally and precisely as possible)**:
Enter `dashboard/db/< your dashboard title>` as [described here](https://community.grafana.com/t/dashboard-urls/13682).

**Anything else we need to know?**:
Not sure.

**Environment**:
- Grafana version: Grafana v8.0.5 (cbb2aa5001)
- Data source type & version: Prometheus (irrelevant)
- OS Grafana is installed on: Linux
- User OS & Browser: MacOS/Firefox
- Grafana plugins: none
- Others: Installed via Helm using this configuration:
```
grafana.ini:
  server:
    domain: "grafana.<my domain>"
    root_url: "%(protocol)s://%(domain)s/grafana"
    serve_from_sub_path: true
persistence:
  enabled: true
ingress:
  enabled: true
  hosts:
    - "grafana.<my domain>"
```
