### ISSUE TITLE
/var/lib/grafana/sessions have thousands of files

### ISSUE THREAD

**Issue by oazabir** [grafana/grafana#3824]
How do I keep this tidy?

**Comment by torkelo** [comment]
Trying to replicate/fix this issue, 

Do you have files there or just empty directories?

**Comment by trinitronx** [comment]
Also seeing this on Grafana running in Kubernetes running from Docker Hub image: [`grafana/grafana:2.6.0`][1].  This is running with `/var/lib/grafana` mounted via NFS into the pods.  The thought was instead of using postgres or another shared session store for running multiple grafana pods, we could just use a shared NFS mount instead and avoid more complexity.

Seems like a ***ton*** of leftover session files exist under the sessions directory.  Lots of files, not as many dirs:

```
# find  /ifs/kub/grafana/var-lib/sessions -type f | wc -l
  121657
# find  /ifs/kub/grafana/var-lib/sessions -type d | wc -l
     273
```

Presumably a lot of the leftover ones are from cluster activity, starting / terminating pods over time.. but I'm not sure how Grafana internally removes these, and I have *not* verified that it's due to non-graceful shutdown.

The reason I noticed this issue was due to a very slow startup sequence for the pod.  [This line in the `./run.sh` script was hanging for a very long time.][2]  I've verified with `strace` that it's just processing all these leftover files.

[1]: https://hub.docker.com/r/grafana/grafana/
[2]: https://github.com/grafana/grafana-docker/blob/master/run.sh#L7

**Comment by torkelo** [comment]
There is session clean up, I tried to troubleshoot this but could not find any issue, the code should only leave some empty dirs but all session files should be cleaned up.

If anyone has a tip for how to replicate this

**Comment by petemyron** [comment]
Are they safe to delete? What do they store? All of mine (I looked at a small handful of 51,869) have these exact characters: `ˇÅˇÇˇÇ`. I'm running `monitoringartist/grafana-xxl` 3.0 in docker. It looks like they are old, though, with the last modified date of 2016.5.20 (when we were using an older version of grafana or grafana-xxl).

**Comment by trinitronx** [comment]
Not exactly sure what causes this, so I'm not sure how to reproduce other than trying to run it the way we are:

 - On Kubernetes
 - Pods share NFS mounts (where sessions get written)
 - NFS mount is across VPN tunnel in another datacenter.  So I/O latency may be an issue.

We started out running multiple pods with the shared NFS mount, however due to running into an issue with many users getting logged out while editing dashboards (was very frequent with num pods > 1), we scaled down to a single running pod in hopes that a single instance accessing the NFS mount wouldn't confuse it too much.

It does appear that there is an issue with the session garbage collection routine somewhere with our configuration, as I can see some lines in our [Grafana logs (anonymized)][2] saying so:

    2016/06/22 00:30:24 error garbage collecting session files: lstat /var/lib/grafana/sessions/5/3/53bf4a9039d5a1cf: no such file or directory

The garbage collection errors appear to be coming from [go-macaron/session/file.go:255][1].  Our logs also have a lot of `500` errors (unknown what this is from or whether it's related or not).

The Kubernetes `ReplicationController` and `Pod` template we are using is like this (also anonymized):

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: www-example-grafana
  namespace: default
  labels:
    team: example
    component: grafana
spec:
  replicas: 1
  selector:
    team: example
    component: grafana
  template:
    metadata:
      name: www-example-grafana
      labels:
        team: example
        component: grafana
    spec:
      containers:
        -
          env:
            -
              name: GRAFANA_DEFAULT_DASHBOARD
              value: /dashboard/file/kubernetes.json
          image: grafana/grafana:2.6.0
          name: grafana
          ports:
            -
              containerPort: 3000
              name: http-grafana
              protocol: TCP
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - mountPath: /etc/grafana
              name: etc-grafana
            - mountPath: /var/lib/grafana
              name: var-lib-grafana
              readOnly: false
      restartPolicy: Always
      volumes:
        - name: etc-grafana
          nfs:
            server: nfs.example.com
            path: /data/kub/example/grafana-aws/etc
        - name: var-lib-grafana
          nfs:
            server: nfs.example.com
            path: /data/kub/example/grafana-aws/var-lib
```

We run a `NodePort` type Kubernetes `Service`.  The yaml manifest we use is like this:

```
apiVersion: v1
kind: Service
metadata:
  name: www-example-grafana
  namespace: default
  labels:
    team: example
    component: grafana
spec:
  type: NodePort
  ports:
  - nodePort: 30002
    port: 3000
    targetPort: http-grafana
  selector:
    team: example
    component: grafana
```

We're on Kubernetes `v1.2.3`.

Hope this helps track it down!

[1]: https://github.com/go-macaron/session/blob/master/file.go#L255
[2]: http://pastebin.com/c3Nk08A2
