### ISSUE TITLE
All AWS Elasticsearch based alerts return "No Data" since 8.1  (AWS/SigV4)

### ISSUE THREAD

**Issue by cykl** [grafana/grafana#38440]
**What happened**:

Upgraded from 8.0.x to 8.1.(0|1|2),  all elasticsearch based alerts switched to NO DATA state. ES datasource is still working, it only impacts alerts.

**What you expected to happen**:

Alerts should have continued to work as before.

**How to reproduce it (as minimally and precisely as possible)**:

Provision an elasticsearch data source using 8.1.x

```
    - name: es-test
      type: 'elasticsearch'
      access: proxy
      database: '[redacted-]YYYYMMDD'
      url: 'https://[redacted].eu-west-3.es.amazonaws.com/'
      user: grafana
      jsonData:
        interval: Daily
        timeField: '@timestamp'
        esVersion: '7.10.0'
        sigV4Auth: true
        sigV4AuthType: keys
        sigV4Region: 'eu-west-3'
      secureJsonData:
        sigV4AccessKey: [redacted]
        sigV4SecretKey: [redacted]
```
        
Create a dashboard and a panel with the simplest possible query 

![image](https://user-images.githubusercontent.com/1764725/130436071-ceefaac4-a0a5-49e0-8744-5572a9569f9d.png)

Save the dashboard. Go back to the panel, add an alert
 
![image](https://user-images.githubusercontent.com/1764725/130436199-0a2772ec-01cc-4c2c-b961-774d218c0e2b.png)

Click on "test rule" and observe that no data is returned.

![image](https://user-images.githubusercontent.com/1764725/130436378-bc73f5c6-786d-4808-ae90-c223462cb76a.png)

Logs don't tell me much:

```
 t=2021-08-23T11:06:35+0000 lvl=info msg="Creating new client" logger=tsdb.elasticsearch.client version=7.7.0 timeField=@timestamp indices=[redacted]-20210823
t=2021-08-23T11:06:36+0000 lvl=info msg="Alert Rule returned no data" logger=alerting.evalContext ruleId=0 name="Panel Title alert" changing state to=no_data
```

**Anything else we need to know?**:

Rolling back to 8.0.6 fixes the issue. 

**Environment**:

- Grafana version: 8.1.[012]
- Data source type & version: Elasticsearch
- This is an AWS Elastisearch cluster using sigV4 auth. I have not tried to deploy a non AWS ES cluster.
