### ISSUE TITLE
Discord notification channel provisioner: message content field is not set

### ISSUE THREAD

**Issue by bramceulemans** [grafana/grafana#38494]
**What happened**: 

We are using a provisioner to create a Discord notification channel. However the `settings.message` field is not being applied.

Example:

```
notifiers:
  - name: Discord
    type: discord
    uid: discord-alerts
    org_id: 1
    is_default: true
    send_reminder: false
    frequency: 1h
    disable_resolve_message: false
    # Discord specific settings
    settings:
      url: $DISCORD_ALERT_WEBHOOK_URL
      message: $DISCORD_ALERT_MESSAGE
```

The `$DISCORD_ALERT_MESSAGE` environment variable is set to `"Example message"`.

**What you expected to happen**:

The "message content" field is set. This is currently not happening.

![image](https://user-images.githubusercontent.com/13304739/130602394-30738b4e-1e7c-49d7-9182-570d0cadad25.png)

**How to reproduce it (as minimally and precisely as possible)**:

See the example above.

**Anything else we need to know?**:

Nothing, really.

**Environment**:
- Grafana version: 8.1.2
- Data source type & version: N.A.
- OS Grafana is installed on: Docker on Ubuntu 20.04
- User OS & Browser: Google Chrome
- Grafana plugins: N.A.
- Others: N.A.
