### ISSUE TITLE
Tempo Search via Loki Fails, However Loki -> Tempo Works. 

### ISSUE THREAD

**Issue by rrichardson** [grafana/grafana#39147]
**What happened**:  
I configured Grafana datasources for Loki and Tempo for derived fields in Loki, and Trace to Logs in Tempo, as per the docs. 
Upon clicking search in the Tempo UI,  I am greeted with this error: 

```
No Loki datasource configured for search. Set up Derived Fields for traces in a Loki datasource settings and link it to this Tempo datasource.
```

**What you expected to happen**:  
I expected to get a list of search results for the service_name in which I was searching. 

**How to reproduce it (as minimally and precisely as possible)**:  
Configure Loki and Tempo datasources via `grafana-datasources` yaml configuration when deploying.  Configs below: 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.1.2
- Data source type & version:  Loki and Tempo (Grafana 8.1.2?) 
- OS Grafana is installed on: Official Grafana Docker container 8.1.2 in Kubernetes 1.18
- User OS & Browser:   Fedora Silverblue - Latest Firefox Stable
- Grafana plugins:
- Others:

** Configs ** 

```yaml
loki.yaml: |
    datasources:
      - access: proxy
        editable: false
        isDefault: false
        name: loki
        type: loki
        url: http://query-frontend.loki.svc.cluster.local:3100
        version: 1
        jsonData:
          httpMethod: GET
          derivedFields:
            - datasourceUid: Tempo
              matcherRegex: 'traceId":"(\w+)"'
              name: TraceID
              # url will be interpreted as query for the datasource
              url: '$${__value.raw}'
  prometheus.yml: |
    apiVersion: 1
    datasources:
      - access: proxy
        editable: false
        isDefault: true
        jsonData:
            httpMethod: GET
        name: prometheus
        type: prometheus
        url: http://prometheus.grafana.svc.cluster.local/prometheus/
        version: 1
  tempo.yml: |
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        url: http://tempo:3200
        jsonData:
          tracesToLogs:
            datasourceUid: loki
            tags:
              - pod
              - svc_name

**Comment by rrichardson** [comment]
![image](https://user-images.githubusercontent.com/124171/133118647-713b9e2b-8777-4f83-85a2-bd66f8c7207b.png)

--- 

![image](https://user-images.githubusercontent.com/124171/133118674-49d1cdef-2494-4b52-b749-81645514ca1f.png)

**Comment by rrichardson** [comment]
I see this warning in the grafana logs at startup: 

```
t=2021-09-13T16:30:30+0000 lvl=warn msg="[Deprecated] the datasource provisioning config is outdated. please upgrade" logger=provisioning.datasources filename=/etc/grafana/provisioning/datasources/loki.yml
``` 

What is the new preferred form of auto-provisioning datasources?

**Comment by rrichardson** [comment]
Nevermind the last comment.  I failed to include the apiVersion: 1 in the Loki config when I was testing some changes in the datasource

**Comment by connorlindsey** [comment]
You need to set the `uid` property for each datasource (See the [docs here](https://grafana.com/docs/grafana/latest/administration/provisioning/#example-data-source-config-file)) via the config, then reference that.

Here's what I changed the config to to get it working (the uid could be anything)
<details>
  <summary>loki.yaml</summary>

<p>

```yaml
apiVersion: 1

datasources:
  - access: proxy
    editable: true
    isDefault: false
    name: loki-test
    type: loki
    uid: loki-custom-uid
    url: http://query-frontend.loki.svc.cluster.local:3100
    version: 1
    jsonData:
      httpMethod: GET
      derivedFields:
        - datasourceUid: tempo-custom-uid
          matcherRegex: 'traceId":"(\w+)"'
          name: TraceID
          # url will be interpreted as query for the datasource
          url: '$${__value.raw}'
```
</p>
</details>

<details>
  <summary>tempo.yml</summary>

<p>

```yaml
apiVersion: 1
datasources:
  - name: Tempo-test
    type: tempo
    url: http://tempo:3200
    editable: true
    uid: tempo-custom-uid
    jsonData:
      tracesToLogs:
        datasourceUid: loki-custom-uid
        tags:
          - pod
          - svc_name
```

</p>
</details>
