### ISSUE TITLE
Grafana's Loki-Tempo integration broken

### ISSUE THREAD

**Issue by gabrieloandco** [grafana/grafana#39562]
**What happened**:
![Selection_047](https://user-images.githubusercontent.com/22502671/134480062-6f573336-4bbf-4ff8-a3b2-3be9a9247ec4.png)
Query error
No Loki datasource configured for search. Set up Derived Fields for traces in a Loki datasource settings and link it to this Tempo datasource.

**What you expected to happen**:
See the traces on the Loki logs in Tempo

**How to reproduce it (as minimally and precisely as possible)**:
Tempo and Loki are correctly integraded on the Datasource configuration:
![image](https://user-images.githubusercontent.com/22502671/134480424-b2ecd953-c5f8-4628-9b80-743c74732f6a.png)
![image](https://user-images.githubusercontent.com/22502671/134480476-d94df7e8-59df-45c8-9567-49dec9d31b1b.png)

Just doing a query with the Loki tab on Tempo explorer will reproduce the error. 

**Environment**:
- Grafana version: 8.1.5 
- Data source type & version: Loki, Tempo
- OS Grafana is installed on: Kubernetes Helm Chart 
- Chart version: 6.16.9

Helm Specific: 
Grafana: https://github.com/grafana/helm-charts/tree/main/charts/grafana == 6.16.9
Tempo: https://github.com/grafana/helm-charts/tree/main/charts/tempo == 0.7.7
Loki: https://github.com/grafana/helm-charts/tree/main/charts/loki == 2.6.0

Grafana Values:
additionalDataSources:
  - access: proxy
    jsonData:
      derivedFields:
      - datasourceUid: Tempo
        matcherRegex: '"trace_id":\s?"(\w+)'
        name: TraceID
        url: ${__value.raw}
    name: Loki
    type: loki
    url: http://loki.loki.svc.cluster.local:3101
  - access: proxy
    jsonData:
      tracesToLogs:
        datasourceUid: Loki
    name: Tempo
    type: tempo
    url: http://tempo.tempo.svc.cluster.local:3100

**Comment by zuchka** [comment]
Hi @gabrieloandco

Thanks for making this issue. I'm sorry you're blocked. This is a rather complex issue to try and reproduce. Can you please include for details on your configurations? What about server logs? Maybe set [the log level for Grafana server](https://grafana.com/docs/grafana/latest/administration/configuration/#log) to `debug`?

**Comment by grafanabot** [comment]
Thanks for creating this issue! We think it's missing some basic information. 

Follow the issue template and add additional information that will help us replicate the problem. 
For data visualization issues: 
- Query results from the inspect drawer (data tab & query inspector)
- Panel settings can be extracted in the panel inspect drawer JSON tab

For dashboard related issues: 
- Dashboard JSON can be found in the dashboard settings JSON model view

For authentication, provisioning and alerting issues, Grafana server logs are useful. 

Happy graphing!

**Comment by gabrieloandco** [comment]
> Hi @gabrieloandco
> 
> Thanks for making this issue. I'm sorry you're blocked. This is a rather complex issue to try and reproduce. Can you please include more details on your configurations? What about server logs? Maybe set [the log level for Grafana server](https://grafana.com/docs/grafana/latest/administration/configuration/#log) to `debug`?
> 
> Also have you tried fiddling with that regex?

There's no need to fiddle with that regex, because as you can see in the first screenshot Loki finds the traceid and redirects to Tempo. The problem is that Tempo is not able to use the Loki Datasource even if it is properly configured as you can see in the last two screenshots. There's nothing outputted to the debug log when I run that query. And I don't think it should be that complex to reproduce because the three tools (Loki, Tempo and Grafana) are mantained by Grafana Labs.

**Comment by zuchka** [comment]
@gabrieloandco I apologize. I suppose that for me, Grafana + Loki + Tempo + Helm + K8s = a lot of configurations for the engineers to guess at here. 

Could you please include more details? For instance, we maintain numerous helm charts. Which chart are you using? Your `values.yaml`? If the issue is not that complex to reproduce, would it be possible for you to include more detailed reproduction steps? 

I know this is frustrating, but the more information that you provide, the better the chance that the team can either spot the configuration issue or track down the bug. Thank you for your support! 🙏

**Comment by gabrieloandco** [comment]
Just updated the Issue with the required information:
Helm Specific:
Grafana: https://github.com/grafana/helm-charts/tree/main/charts/grafana == 6.16.9
Tempo: https://github.com/grafana/helm-charts/tree/main/charts/tempo == 0.7.7
Loki: https://github.com/grafana/helm-charts/tree/main/charts/loki == 2.6.0

Grafana Values:
additionalDataSources:
access: proxy
jsonData:
derivedFields:
datasourceUid: Tempo
matcherRegex: '"trace_id":\s?"(\w+)'
name: TraceID
url: ${__value.raw}
name: Loki
type: loki
url: http://loki.loki.svc.cluster.local:3101
access: proxy
jsonData:
tracesToLogs:
datasourceUid: Loki
name: Tempo
type: tempo
url: http://tempo.tempo.svc.cluster.local:3100

To reproduce just install Tempo, Loki and Grafana in the same cluster and configure the Data Sources as shown above.

**Comment by aocenas** [comment]
Trying the same configuration and it work fine for me. One thing though is that from the screenshot you sent of the Tempo config, it looks differently in 8.1.5 which is the version you mention you are using. This is how that section looks in 8.1.5 for me:
![Screenshot from 2021-10-04 15-07-33](https://user-images.githubusercontent.com/1014802/135856799-4714ff29-a3d2-4626-997d-c6db71f94514.png)

Could this be just mismatched Grafana instance or something like that? If not can you send the data source provisioned config in a way that is not formatted in markdown so I can make sure there is not some mistake I am not seeing right now.

**Comment by gabrieloandco** [comment]
Hi, for some reason the chart installed 8.0.5 instead of 8.1.5. However I still get the same error message, here is the requested data source: 
```
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus:9090/
      access: proxy
      isDefault: true
      jsonData:
        timeInterval: 30s
    - access: proxy
      jsonData:
        derivedFields:
        - datasourceUid: Tempo
          matcherRegex: '"trace_id":\s?"(\w+)'
          name: TraceID
          url: ${__value.raw}
      name: Loki
      type: loki
      url: http://loki.loki.svc.cluster.local:3101
    - access: proxy
      jsonData:
        tracesToLogs:
          datasourceUid: Loki
      name: Tempo
      type: tempo
      url: http://tempo.tempo.svc.cluster.local:3100
```

**Comment by aocenas** [comment]
Seems like you are missing the uid property on the data sources. When you have linking like this:
```
tracesToLogs:
  datasourceUid: Loki
```
it refers to uid of the data source not it's name (as that does not have to be unique as far as I know) so you have to set some uid to the Loki data source like this:
```
- access: proxy
      jsonData:
        derivedFields:
        - datasourceUid: Tempo
          matcherRegex: '"trace_id":\s?"(\w+)'
          name: TraceID
          url: ${__value.raw}
      name: Loki
      type: loki
      uid: Loki
      url: http://loki.loki.svc.cluster.local:3101
```
Same goes for Tempo as you reference it from the derivedFields config.

Another issue is the `url: ${__value.raw}`, it needs to be `url: $${__value.raw}`. The double `$$` is escaped $ because otherwise in yaml files single $ is used to reference external variables when yaml file is interpreted.
