### ISSUE TITLE
Provisioning: Discord Notification's URL secure setting is in fact a regular setting

### ISSUE THREAD

**Issue by Angelin01** [grafana/grafana#40148]
**What happened**:

When provisioning Grafana, [the documentation here](https://grafana.com/docs/grafana/latest/administration/provisioning/) states that Discord's `url` parameter is a "Secure Setting", however if you provide it as a secure setting:
```yaml
notifiers:
  notifiers.yaml:
    notifiers:
      - name: "Discord Alert"
        type: discord
        uid: discord-alert
        org_id: 1
        is_default: false
        send_reminder: true
        frequency: 24h
        disable_resolve_message: false
        settings:
          avatar_url: "SOME_URL"
          content: "<@SOME_ID>"
        secure_settings:
          url: "$DISCORD_URL"
 ```
 it fails with the error `service init failed: Alert notification provisioning error: alert validation error: Could not find webhook url property in settings`
 
However, if provided as a regular setting:
```yaml
settings:
  avatar_url: "SOME_URL"
  content: "<@SOME_ID>"
  url: "$DISCORD_URL"
```
everything works.

Looking at the [Discord Alert code here](https://github.com/grafana/grafana/blob/da813877fb8b6e2796d3305927ee4017351e998b/pkg/services/alerting/notifiers/discord.go#L57), and comparing it with the Slack equivalent, it seems it is indeed just a regular setting and not a secure setting.

**What you expected to happen**:

Discord's notification setting should be a Secure Setting.
