### ISSUE TITLE
[provisioning] [helm] datasource defaultRegion not set in Grafana chart

### ISSUE THREAD

**Issue by Mar8x** [grafana/grafana#40453]
**What happened**:
I provisioned a prometheus datasource through the helm chart. In Grafana, the named datasource was present but testing the source turned into a "Server Error". 

![Screenshot 2021-10-14 at 12 14 49](https://user-images.githubusercontent.com/45066148/137298387-e0360516-4a67-45ad-8107-9eb02e9fb8a4.png)
4

I could see from the datasource panel that the `defaultRegion` was missing, albeit it was in the templated & provisioned file. `bash-5.1$ cat /etc/grafana/provisioning/datasources/datasources.yaml`:
```yaml
apiVersion: 1
datasources:
- access: proxy
  isDefault: true
  jsonData:
    authType: default
    defaultRegion: eu-west-1
    sigV4Auth: true
  name: prom1
  type: prometheus
  url: https://aps-workspaces.eu-west-1.amazonaws.com/workspaces/ws-XXXX-...
```
To prove the source is working with all given configuration, I manually added a new source which contained the value for `defaultRegion`. With the only difference off adding `defaultRegion` the test to connect to the source was successful.

**What you expected to happen**:
Configuration in Grafana instance is as to the datasource definition in the provisioning-file.

**How to reproduce it (as minimally and precisely as possible)**:
Create a provisioning file for the data source as to the above example.

**Anything else we need to know?**:
```ini
grafana.ini:
  paths:
    data: /var/lib/grafana/
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  analytics:
    check_for_updates: true
  log:
    mode: console
  grafana_net:
    url: https://grafana.net
  server:
    domain: xxxx
    root_url: "%(protocol)s://%(domain)s/grafana"
    serve_from_sub_path: true
  auth:
    sigv4_auth_enabled: true
```

**Environment**:
- Grafana version: v8.2.1 (88622d7f09)
- Data source type & version: prometheus, AMP (Amazon Managed Prometheus Service)
- OS Grafana is installed on: EKS:: 1.21, with AMI instance versions: 1.21.2-20210914
- User OS & Browser: 
- Grafana plugins: default (no additional ones)
- Others: Helm Chart:: grafana-6.16.14
