### ISSUE TITLE
Datasource proxy returning "too many outstanding requests"

### ISSUE THREAD

**Issue by applike-ss** [grafana/grafana#41194]
**What happened**:
We were trying out loki and the integration into grafana. When adding a dashboard with not only logs but also time series visualization, we encountered "too many outstanding requests" (HTTP 429) responses from grafana in the network monitor.
The exclamation mark symbol was shown in the panels on the top left side with the same text "too many outstanding requests".
However a quick google search for exactly that term in combination with loki OR grafana reveiled nothing that seemed to be the same issue.

**What you expected to happen**:
I would expect to be able to configure how many requests can be processed simultaneously and also to find possible response codes in the documentation. There should be a possibility to troubleshoot the issue without diving into the code.

**How to reproduce it (as minimally and precisely as possible)**:
* Setup Prometheus stack with grafana
* Setup Loki distributed
* Ingest lots of events for ~24h
* Add a dashboard with logs and time series visualization
* Set timeframe to 24h or more

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.1.5
- Data source type & version: loki 2.3.0
- OS Grafana is installed on: docker image grafana/grafana:8.1.5 on k8s
- User OS & Browser: Linux / Chrome
- Grafana plugins: Just core plugins
- Others: -

**Comment by dsotirakis** [comment]
Hello @applike-ss, thanks for raising the issue!
Can you please try increasing `max_idle_connections` constant to see if it fixes your issue?

More details here https://grafana.com/docs/grafana/latest/administration/configuration/#max_idle_connections.

**Comment by applike-ss** [comment]
Thanks for the hint. I tried it and at first it looked like it works, but after the next 5-10 requests (changed the filter condition for use a different log stream) the same behaviour came back. Just from watching the behaviour it looks like some resource is not being freed. It only seems to effect the time series graph. Not sure now if it is actually grafana or if it is loki. Do you know if grafana can cause this error message at all?

**Comment by cyriltovena** [comment]
👋 @applike-ss Can you share you Loki configuration ? I think you're hitting a default limit somewhere.

**Comment by applike-ss** [comment]
Here's my current config:
```
auth_enabled: true

server:
  http_listen_port: 3100

distributor:
  ring:
    kvstore:
      store: memberlist

memberlist:
  join_members:
    - loki-loki-distributed-memberlist

ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1
  chunk_encoding: snappy
  chunk_idle_period: 15m
  chunk_block_size: 2621440
  chunk_retain_period: 1m
  max_chunk_age: 1h
  max_transfer_retries: 0

limits_config:
  enforce_metric_name: false
  max_cache_freshness_per_query: 10m
  max_query_length: 12000h
  max_query_parallelism: 256
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 30

schema_config:
  configs:
    - from: 2020-05-15
      store: aws
      object_store: s3
      schema: v11
      index:
        prefix: my-{{ .Values.environment }}-loki_
        period: 720h
        tags:
          Project: foo-project
          Environment: {{ .Values.environment }}
          Component: loki

storage_config:
  aws:
    s3: s3://eu-central-1/my-loki-bucket
    dynamodb:
      dynamodb_url: dynamodb://eu-central-1

chunk_store_config:
  # store for 1 year
  max_look_back_period: 8760h

table_manager:
  index_tables_provisioning:
    enable_ondemand_throughput_mode: true
    enable_inactive_throughput_on_demand_mode: true
  chunk_tables_provisioning:
    enable_ondemand_throughput_mode: true
    enable_inactive_throughput_on_demand_mode: true
  retention_deletes_enabled: true
  retention_period: 8640h

query_range:
  align_queries_with_step: true
  parallelise_shardable_queries: false
  max_retries: 5
  split_queries_by_interval: 15m
  cache_results: true
  results_cache:
    cache:
      enable_fifocache: true
      fifocache:
        max_size_items: 1024
        validity: 24h

frontend_worker:
  frontend_address: loki-loki-distributed-query-frontend:9095
  parallelism: 2

frontend:
  log_queries_longer_than: 5s
  compress_responses: true
  tail_proxy_url: http://loki-loki-distributed-querier:3100

compactor:
  shared_store: s3

ruler:
  storage:
    type: s3
    s3:
      s3: s3://eu-central-1/my-loki-bucket
  ring:
    kvstore:
      store: memberlist
  rule_path: /tmp/loki/scratch
  alertmanager_url: https://alertmanager.xx
  external_url: https://alertmanager.xx
```
