### ISSUE TITLE
Error Checking Server Process Execution Privilege when Running Grafana Docker Container

### ISSUE THREAD

**Issue by norsemanGrey** [grafana/grafana#41217]
**What happened**:

Getting the following error when building and running the Grafana docker container with docker-compose. 

`Error checking server process execution privilege. error: could not get current OS user to detect process privileges`

The container starts and I am able to access the GUI.

**What you expected to happen**:

Not getting the error. Not sure what it impacts as I cannot find any references to the specific error.

**How to reproduce it (as minimally and precisely as possible)**:

Building and running Grafana with the following docker-compose service config.

```
  metrics-viewer:
    image: grafana/grafana:latest
    container_name: metrics-viewer
    hostname: grafana
    security_opt:
      - no-new-privileges:true
    user: "1000"
    networks:
      monitoring-net:
        ipv4_address: ${IP_MONITORING_BASE}.${ID_METRICS_VIEWER}
    environment:
    ports:
      - target: 3000
        published: ${PORT_EXTERNAL_BASE}${ID_METRICS_VIEWER}
    volumes:
      - type: bind
        source: ${DIR_DOCKER}/grafana/config
        target: /var/lib/grafana
    restart: unless-stopped
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2.2
- OS Grafana is installed on: Ubuntu Server / Docker Container
