### ISSUE TITLE
Alerting: Continuous 500 errors from ruler API on alerting list view for Prometheus datasource

### ISSUE THREAD

**Issue by fabsrc** [grafana/grafana#41483]
**What happened**:

When visiting and staying on the unified alerting list view (/alerting/list), Grafana returns a 500 error response every 15s with the following content:

```json
{"message":"unexpected content type from upstream. expected YAML, got text/html; charset=utf-8"}
```

**What you expected to happen**:

No 500 error response is returned or it is at least not returned continuously (i.e. Grafana does not make any further request to the ruler API if the datasource does not support it).

**How to reproduce it (as minimally and precisely as possible)**:

1. Start Grafana and Prometheus with `docker-compose up` with unified alerting enabled:

```yaml
version: "3"

services:
  prometheus:
    image: prom/prometheus:v2.31.1

  grafana:
    image: grafana/grafana:8.2.3
    ports:
      - 127.0.0.1:3000:3000
    environment:
      GF_UNIFIED_ALERTING_ENABLED: "true"
      GF_ALERTING_ENABLED: "false"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
```

2. Create Prometheus datasource

```sh
curl -X POST http://localhost:3000/api/datasources \
-H 'Content-Type: application/json; charset=utf-8' \
--data-binary @- << EOF
{
  "name":"prometheus",
  "type":"prometheus",
  "url":"http://prometheus:9090",
  "access":"proxy"
}
EOF
```

3.  Go to alert list view: http://localhost:3000/alerting/list and check the dev tools network tab. A 500 error response should appear every 15s.

**Anything else we need to know?**:

I guess the 500 error is expected in the FE: https://github.com/grafana/grafana/blob/6862c7baf8a6f50d1ed571bbdb835b565bf2082c/public/app/features/alerting/unified/api/ruler.ts#L108 However, if the first response already returned a 500 error, indicating that ruler is not supported for this datasource, I think there is no need to make any additional calls to the endpoint.

**Environment**: 
- Grafana version: 8.2.3
- Data source type & version: Prometheus (v2.31.1)
- OS Grafana is installed on: K8s, Docker
- User OS & Browser: MacOS; Mozilla Firefox & Google Chrome
- Grafana plugins: -
- Others: -
