### ISSUE TITLE
Docs: improve provisioning documentation for Elasticsearch

### ISSUE THREAD

**Issue by Elfo404** [grafana/grafana#41485]
starting from Grafana 8.0, `esVersion` should be a semver-valid string (ie. `"7.10.0"`).

```yaml
  - name: es-prov
    type: elasticsearch
    access: proxy
    database: "[metrics-]YYYY.MM.DD"
    url: http://localhost:12200
    jsonData:
      interval: Daily
      timeField: "@timestamp"
      esVersion: 7.10.0
      timeInterval: "10s"
```

using this configuration correctly generates this:
![Screenshot 2021-11-09 at 15 39 04](https://user-images.githubusercontent.com/1170767/140955431-6e1e392d-849c-45d2-96e4-b32ff532249f.png)

we should probably better describe how to provision an ES datasource and what format is expected in https://grafana.com/docs/grafana/latest/features/datasources/elasticsearch/#configure-the-data-source-with-provisioning, I'll create an issue and update docs.

_Originally posted by @Elfo404 in https://github.com/grafana/grafana/issues/11126#issuecomment-964274500_
