### ISSUE TITLE
TablePanel: Handle column overflow and horizontal scrolling in table panel

### ISSUE THREAD

**Issue by jerryxguo** [grafana/grafana#4157]
if there are many columns, the table headers run out of the table. when scroll to right, the table cells move left and won't match up with their headers.

![image](https://cloud.githubusercontent.com/assets/10950337/13340309/7573f2a0-dc83-11e5-8398-b3e7a56209dc.png)

it can be fixed by removing " position absolute " from .table-panel-table-header-inner css  but the header won't be fixed when scroll down

**Comment by vitorboschi** [comment]
Could this jQuery feature be used to solve the problem? -> http://mkoryak.github.io/floatThead/

**Comment by waqark3389** [comment]
+1

**Comment by bbczeuz** [comment]
Still open. With 4.4.1, one cell overflow is handled correctly, but headers a) don't scroll b) overflow

**Comment by phouverneyuff** [comment]
Use datatable panel instead
https://github.com/briangann/grafana-datatable-panel

**Comment by jlming6** [comment]
Hi @torkelo is there a timeline for this issue?

**Comment by deepakmahakale** [comment]
Any plans for fixing this issue?

**Comment by Gnommer** [comment]
@torkelo please coordinate to solve this issue of sticky headers and scrolable column features. i have one company critical application which depends on this panel. The Datatable Panel is not helping out for reasons there are no value mappings and color thresholding is not working for that. my only shot is with the table plugin if this one issue with the column headers can be fixed

**Comment by tomisaacson** [comment]
@Gnommer I used @phouverneyuff's suggestion of using https://github.com/briangann/grafana-datatable-panel instead, worked fine for me.

**Comment by Gnommer** [comment]
> @Gnommer I used @phouverneyuff's suggestion of using https://github.com/briangann/grafana-datatable-panel instead, worked fine for me.

i am searching for a version which supports grafana version 6.1.6. 
The Datatable panel does not have value mappings
and thresholding doesnt work for this version

The column overflow issue persists in the table plugin.
Can any one write a small fix for this issue. much appreciated.

**Comment by tejaram15** [comment]
@torkelo I am interested in working on this feature. Planning on creating a Pull request real soon.

**Comment by pushpinder098** [comment]
Hello @torkelo,

any update on this issue? I am using "v6.0.1" and facing "Horizontal scrolling in table panel doesn't move table header". It would be appreciable if you let me know on it.

**Comment by merlin-zaraza** [comment]
Would be great to fix this

**Comment by Drasius2** [comment]
Still issue in Grafana v6.2.5 (6082d19)

**Comment by pete00067** [comment]
Bug still exsisted, any updates on the fix?

**Comment by wernerdaehn** [comment]
I Concur. Don't understand why such a basic thing is still not fixed.

**Comment by Phrlog** [comment]
Hello @tejaram15,
do you still working on this feature?

**Comment by subbaray** [comment]
+1, Can we have this feature soon?

**Comment by tejaram15** [comment]
Hi. Stopped Working on this feature.

Sent from Mail for Windows 10

**Comment by karln-star** [comment]
+1
Would be really helpful in inspecting logs.

**Comment by mukuls9971** [comment]
+1 
Can we have this feature soon?
I am ready to help to improve table panel

**Comment by naturalbeau** [comment]
any update on this issue? It still exits in v6.4.3.

**Comment by xfirehawk123** [comment]
Hello Grafana Team,

thanks for all the great work! But it would be great, if we could have a fix for that issue.

Thanks

**Comment by piotr-d** [comment]
v6.5.1 still has this issue

**Comment by AIXruth** [comment]
+1
v6.5.2 still has this issue

**Comment by rmunoz10** [comment]
+1 v6.6.0 still as this issue

**Comment by vmanju123** [comment]
any update on this issue ? is there a fix available ?

**Comment by syco** [comment]
Hi, would be great to see this fixed, in the meantime following @jerryxguo advice I edited the css, as I'm ok with the headers scrolling vertically and not being fixed at the top here's my final solution for the dark theme:

```css
.table-panel-container {
  padding-top: 0px !important;
}
.table-panel-header-bg {
  display: none !important;
}
.table-panel-table thead tr {
  background: linear-gradient(135deg,#2f2f32,#262628) !important;
  border-bottom: 2px solid #161719 !important;
  border-top: 2px solid #161719 !important;
}
.table-panel-table-header-inner {
  padding: .3em 1.1em .45em 1.1em !important;
  position: inherit !important;
  white-space: nowrap !important;
}
```
