### ISSUE TITLE
Declarative Config - notifiers.yaml - Microsoft Teams, unable to set Upload Image

### ISSUE THREAD

**Issue by szymon3** [grafana/grafana#41681]
**What happened**:
I've configured Microsoft Teams notifier from notifiers.yaml. I've set `upload_image: true` field, however it seems like this field is being ignored. I'm able to check "Include Image" setting from Grafan UI under _Notification channels_ settings.

**What you expected to happen**:
I expect that _Include Image_ field will be activated in UI after I set `upload_image: true` in notifiers.yaml.

**How to reproduce it (as minimally and precisely as possible)**:
Put following configuration in `notifiers.yaml` provisioning file.
```yaml
notifiers:
  - name: teams_devops
    type: teams
    org_id: 1
    uid: teams_devops
    is_default: true
    upload_image: true
    settings:
      url: xxxxxxx
```

![Notification settings](https://i.imgur.com/4Pqu8Oj.png)

**Environment**:
- Grafana version: v8.2.1
- OS Grafana is installed on: Kube Prometheus Stack Helm Chart, K8s
