### ISSUE TITLE
Stuck at Loading labels with prometheus but I can load data

### ISSUE THREAD

**Issue by qiujiangkun** [grafana/grafana#42019]
**What happened**:
I'm trying out grafana and prometheus. When I click on Metrics Browser, it stuck at Loading labels... But I can draw graph if I manually type the query.
![image](https://user-images.githubusercontent.com/33482468/142711720-81659b70-2b07-4093-a62e-65cfe3bcb4ee.png)

**What you expected to happen**:
It loads metrics labels.

**How to reproduce it (as minimally and precisely as possible)**:
Set up prometheus as default data source, create a dashboard, click on Metrics Browser and you'll see it

**Environment**:
- Grafana version: v8.2.5 (b57a137acd)
- Data source type & version: Prometheus 2.3.0
- OS Grafana is installed on: Docker for Mac
- User OS & Browser: MacOS
- Grafana plugins: default

```yaml
version: '3.7'

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  front-tier:
  back-tier:

services:

  prometheus:
    image: prom/prometheus:v2.3.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
#    links:
#      - cadvisor:cadvisor
#      - alertmanager:alertmanager
    #      - pushgateway:pushgateway
#    depends_on:
#      - cadvisor
    #      - pushgateway
    networks:
      - back-tier
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
#    deploy:
#      placement:
#        constraints:
#          - node.hostname == ${HOSTNAME}

#  node-exporter:
#    image: prom/node-exporter
#    volumes:
#      - /proc:/host/proc:ro
#      - /sys:/host/sys:ro
#      - /:/rootfs:ro
#    command:
#      - '--path.procfs=/host/proc'
#      - '--path.sysfs=/host/sys'
#      - --collector.filesystem.ignored-mount-points
#      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
#    ports:
#      - 9100:9100
#    networks:
#      - back-tier
#    restart: always
#    deploy:
#      mode: global

#  alertmanager:
#    image: prom/alertmanager
#    ports:
#      - 9093:9093
#    volumes:
#      - ./alertmanager/:/etc/alertmanager/
#    networks:
#      - back-tier
#    restart: always
#    command:
#      - '--config.file=/etc/alertmanager/config.yml'
#      - '--storage.path=/alertmanager'
  #    deploy:
  #      placement:
  #        constraints:
  #          - node.hostname == ${HOSTNAME}
#  cadvisor:
#    image: gcr.io/cadvisor/cadvisor
#    volumes:
#      - /:/rootfs:ro
#      - /var/run:/var/run:rw
#      - /sys:/sys:ro
#      - /var/lib/docker/:/var/lib/docker:ro
#    ports:
#      - 8080:8080
#    networks:
#      - back-tier
#    restart: always
#    deploy:
#      mode: global

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
#    env_file:
#      - ./grafana/config.monitoring
    networks:
      - back-tier
      - front-tier
    restart: always

#  pushgateway:
#    image: prom/pushgateway
#    restart: always
#    expose:
#      - 9091
#    ports:
#      - "9091:9091"
#    networks:
#      - back-tier
```
