### ISSUE TITLE
After updating from 8.2.5 to 8.3.0 our Prometheus datasource does not work anymore: bad_response: readObjectStart: expect { or n, but found B, error found in #1 byte of

### ISSUE THREAD

**Issue by dbluxo** [grafana/grafana#42672]
**What happened**:

After updating Grafana from 8.2.5 to 8.3.0 our Prometheus datasource does not work anymore.
All queries have the same error message and even a test in the datasource now fails:

<img width="1401" alt="Bildschirmfoto 2021-12-02 um 17 00 51" src="https://user-images.githubusercontent.com/20679842/144457785-50e7e399-1223-47fa-8514-bd5a4f5de760.png">

As of the Grafana logs:

```
t=2021-12-02T16:11:27+0000 lvl=eror msg="Instant query failed" logger=tsdb.prometheus query=1+1 err="bad_response: readObjectStart: expect { or n, but found B, error found in #1 byte of ...|Bad Request|..., bigger context ...|Bad Request. The request or configuration is malfor|..."
t=2021-12-02T16:11:27+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=POST path=/api/ds/query status=400 remote_addr="<redacted>, <redacted>" time_ms=39 size=214 referer=https://grafana-<redacted>/datasources/edit/Billing-observability-labor
```

**What you expected to happen**:

Working Prometheus datasource.

**Anything else we need to know?**:

Query inspector for 8.3.0 (not working):

```
{
  "request": {
    "url": "api/ds/query",
    "method": "POST",
    "data": {
      "queries": [
        {
          "refId": "A",
          "key": "Q-56985939-91f4-4627-805e-8784b5e4634e-0",
          "instant": true,
          "range": true,
          "exemplar": false,
          "expr": "billing_loki_used_charge_euros",
          "datasource": {
            "uid": "Billing-observability-labor",
            "type": "prometheus"
          },
          "queryType": "timeSeriesQuery",
          "requestId": "Q-56985939-91f4-4627-805e-8784b5e4634e-0A",
          "utcOffsetSec": 3600,
          "legendFormat": "",
          "datasourceId": 2,
          "intervalMs": 15000,
          "maxDataPoints": 1632
        }
      ],
      "range": {
        "from": "2021-12-02T14:30:00.532Z",
        "to": "2021-12-02T15:30:00.532Z",
        "raw": {
          "from": "now-1h",
          "to": "now"
        }
      },
      "from": "1638455400532",
      "to": "1638459000532"
    },
    "hideFromInspector": false
  },
  "response": {
    "results": {
      "A": {
        "error": "bad_response: readObjectStart: expect { or n, but found B, error found in #1 byte of ...|Bad Request|..., bigger context ...|Bad Request. The request or configuration is malfor|...",
        "refId": "A"
      }
    }
  }
}
```

Query inspector for 8.2.5 (working):

```
{
  "request": {
    "url": "api/datasources/proxy/2/api/v1/query?query=billing_loki_used_charge_euros&time=1638458848&namespace=observability-labor",
    "method": "GET",
    "hideFromInspector": false
  },
  "response": {
    "status": "success",
    "data": {
      "resultType": "vector",
      "result": [
        {
          "metric": {
            "__name__": "billing_loki_used_charge_euros",
            "namespace": "observability-labor"
          },
          "value": [
            1638458848,
            "0.00000026388014602060943"
          ]
        }
      ]
    }
  }
}
```

Datasource configuration:

```
- orgId: 1
  version: 1
  name: Billing-observability-labor
  type: prometheus
  access: proxy
  url: https://amp-user-proxy.billing.svc.cluster.local:8443
  jsonData:
    customQueryParameters: namespace=observability-labor
    disableMetricsLookup: true
    httpHeaderName1: Authorization
    httpMethod: GET
    tlsSkipVerify: false
  secureJsonData:
    httpHeaderValue1: $BILLING_OBSERVABILITY_LABOR_HTTPHEADERVALUE_1
```

What I still notice is that although we have configured `GET` as http method, a `POST` is executed.

**Environment**:
- Grafana version: 8.3.0
- Data source type & version: Prometheus
- OS Grafana is installed on: Docker, Kubernetes
- User OS & Browser: Firefox, Safari, Chrome
