### ISSUE TITLE
Variable substitution for `Min step` doesn't work in 8.3.0

### ISSUE THREAD

**Issue by Vasniktel** [grafana/grafana#42688]
**What happened**:
Unable to substitute a dashboard interval variable into a `Min step` field after updating to 8.3.0. Predefined variables also behave strangely (e.g. `$__interval` and `$__rate_interval` seem to work while `$__range` doesn't). 

**What you expected to happen**:
Previously substitution worked fine.

**How to reproduce it (as minimally and precisely as possible)**:
- Use this docker-compose file:
```yml
version: "3.8"
services:
  prometheus:
    image: prom/prometheus:v2.29.2
    ports:
      - 9090:9090
  grafana-830:
    image: grafana/grafana:8.3.0
    ports:
      - 3830:3000
  grafana-826:
    image: grafana/grafana:8.2.6
    ports:
      - 3826:3000
```
- Set up Prometheus data source.
- Create a dashboard with an interval variable.
- Try creating a panel. Your variable should work OK if you put it anywhere in the query. It will not work if you use it in the `Min step` field. With 8.2.6 everything works fine.

**Anything else we need to know**:

![Recording](https://user-images.githubusercontent.com/23561899/144502291-ae37aebd-8643-44c1-a54e-b998d4de9b35.gif)

Logs:
```
grafana-830_1  | t=2021-12-02T20:55:21+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="failed to query data: time: invalid duration \"$query0\"" remote_addr=172.20.0.1
grafana-830_1  | t=2021-12-02T20:55:21+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/ds/query status=500 remote_addr=172.20.0.1 time_ms=1 size=34 referer="http://localhost:3830/dashboard/new?orgId=1&editPanel=2"
```

**Environment**:
- Grafana version: 8.3.0
- Data source type & version: Prometheus 2.29.2
- OS Grafana is installed on: Used from the docker image
- User OS & Browser: Ubuntu 20.04, Chrome 95.0.4638.69
- Grafana plugins: none
