### ISSUE TITLE
Azure Log Analytics based alerts failing in 8.3.0

### ISSUE THREAD

**Issue by cheekp** [grafana/grafana#42747]
**What happened**:
Errors observed in unified alert system on grafana managed alerts using the Azure Log Analytics datasource following upgrade from 8.2.5 to 8.3.0.

All alerts based on Log Analytics show a health state of 'ERROR'  after upgrade.

![Screenshot 2021-12-03 at 14 25 27](https://user-images.githubusercontent.com/39499749/144623921-f6aa97d8-1cdd-4790-99b8-58cc8b710265.png)

Editing any of the alerts based on this data source appears to be problematic.
The Workspace dropdown in blank. The existing Kusto query is not displayed.
![Screenshot 2021-12-03 at 14 33 26](https://user-images.githubusercontent.com/39499749/144625004-507acbaa-e4d5-45af-b26e-7846270bf694.png)

Browser dev tools shows a new 404. The path '/proxy/1/sameasloganalyticsazure', looks different to 8.2.5.

![Screenshot 2021-12-03 at 14 39 38](https://user-images.githubusercontent.com/39499749/144621590-67bc97a5-537c-4322-8db7-0404bd826488.png)

Selecting the workspace warns of the following error:

**Failed to evaluate queries and expressions: failed to execute conditions: plugin unavailable**

Browser dev tools shows the following 400.
![Screenshot 2021-12-03 at 14 44 03](https://user-images.githubusercontent.com/39499749/144621621-2ce045bb-f39e-44bd-bfda-4516960b5588.png)

**What you expected to happen**:
Azure - Azure Log Analytics based alerts to be in a OK health state and usable in 8.3.

**How to reproduce it (as minimally and precisely as possible)**:
Ubuntu stock docker image grafana/grafana:8.3.0
Inbuilt Azure datasource should do it.

**Anything else we need to know?**:
My data source is provisioned via yaml file.

```
apiVersion: 1

datasources:
  - name: Azure
    type: grafana-azure-monitor-datasource
    uid: XXXXXXXX
    orgId: 1
    typeLogoUrl: public/plugins/grafana-azure-monitor-datasource/img/logo.jpg
    access: proxy
    url: /api/datasources/proxy/2
    isDefault: true
    jsonData:
      cloudName: azuremonitor
      subscriptionId: #subscriptionId#
      tenantId: #tenantId#
      clientId: #clientId#
      logAnalyticsDefaultWorkspace: #logAnalyticsDefaultWorkspace#
      azureLogAnalyticsSameAs: true
      keepCookies: []
    secureJsonData:
      clientSecret: '#clientSecret#'
    editable: true
```

*Environment**:
- Grafana version: 
8.3.0
- Data source type & version: 
Builtin Azure data source. Azure Monitor API details configured. Azure Log Analytics API using 'same details as Azure Monitor API'.
- OS Grafana is installed on: 
Ubuntu stock docker image grafana/grafana:8.3.0
- User OS & Browser: 
Edge
- Grafana plugins:
N/A
- Others:
- N/A
