### ISSUE TITLE
Loki datasource timeout at 30s

### ISSUE THREAD

**Issue by demandbase-gmavadiya** [grafana/grafana#42801]
**What happened**:
Same logql query works with logcli but consistently fails when using Grafana Loki datasource. `query_range` call fails in `~30s` when using Grafana

**What you expected to happen**:
Grafana should have returned the results and not failed with data source error

**How to reproduce it (as minimally and precisely as possible)**:
1. Upload up to 10d and TB+ worth of logs to s3
2. Configure Loki data source using either external LB or direct k8s svc
3. Query something similar to `{namespace="foo",container="bar"} |= "foo_" |~ "(?i)bar"` over a large window like `168h`
4. Observe that `query_range` fails in `~30s` and Grafana throws Data source error
5. Now port-forward the svc (`loki-distributed-query-frontend` or `loki-distributed-gateway`) locally and run the same query via `logcli`.
6. Observe that logcli returns the results fine

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2.5
- Data source type & version: Loki
- User OS & Browser: OSX
- Loki v2.3.0
![Screen Shot 2021-12-06 at 2 47 16 PM](https://user-images.githubusercontent.com/89478062/144936704-7db70c87-0393-4717-9a6b-fee33a7665d6.png)

**Comment by Flokami** [comment]
Hello, I may have something similar.

I'm using : 
```
label_values({}, host)
```
To get all of my host, but this lead me to a bad gateway.

Loki is responding on Grafana "Explore" panel.
I get this error in log : 
```
lvl=eror msg="Data proxy error" logger=data-proxy-log userId=1 orgId=1 uname=xxx path=/api/datasources/proxy/3/loki/api/v1/series remote_addr=xx.xx.xx.xx referer="xx://xxxx/d/51yRW577k/logs?orgId=1&editview=templating" error="http: proxy error: net/http: timeout awaiting response headers"
```

And no error in Loki log that seem to send the data.

Environment:
- Grafana 8.3.1
- Loki 2.4.1

**Comment by saytik** [comment]
have the same problem upfteer upgrading grafana to 8.3.2 and loki 2.4.1 
Datasource Loki timeout is set to 120

**Comment by saytik** [comment]
Increased read and write timeouts  in loki config... It helped me.
```
server:
  http_listen_port: 3100
  http_server_read_timeout: 600s
  http_server_write_timeout: 600s

frontend:
    address: 127.0.0.1
```

my current config works without timeouts, but very slow long queries:

```
auth_enabled: false

server:
  http_listen_port: 3100
  http_server_read_timeout: 600s
  http_server_write_timeout: 600s
  log_level: debug
  grpc_server_max_recv_msg_size: 20388078
  grpc_server_max_send_msg_size: 20388078

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  wal:
    enabled: true
    dir: /loki/wal
  chunk_idle_period: 1h       # Any chunk not receiving new logs in this time will be flushed
  max_chunk_age: 1h           # All chunks will be flushed when they hit this age, default is 1h
  chunk_target_size: 1048576  # Loki will attempt to build chunks up to 1.5MB, flushing first if chunk_idle_period or max_chunk_age is reached first
  chunk_retain_period: 20m    # Must be greater than index read cache TTL if using an index cache (Default index read cache TTL is 5m)
  max_transfer_retries: 0     # Chunk transfers disabled

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
      chunks:
        prefix: chunk_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 720h         # Can be increased for faster performance over longer query periods, uses more disk space
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

compactor:
  working_directory: /loki/boltdb-shipper-compactor
  shared_store: filesystem
  retention_enabled: true

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_query_parallelism: 64
  max_streams_per_user: 500000
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 24
  max_concurrent_tail_requests: 20
  retention_period: 31d
  per_stream_rate_limit: 16MB
  per_stream_rate_limit_burst: 64MB

chunk_store_config:
  max_look_back_period: 720h
  cache_lookups_older_than: 24h
  chunk_cache_config:
    enable_fifocache: true
    fifocache:
      max_size_bytes: 2048000000

table_manager:
  index_tables_provisioning:
    enable_ondemand_throughput_mode: true
    enable_inactive_throughput_on_demand_mode: true
  retention_deletes_enabled: true
  retention_period: 720h

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules-temp
  alertmanager_url: http://localhost:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true

querier:
  max_concurrent: 25
  query_timeout: 5m
  extra_query_delay: 30s
  engine:
    timeout: 5m
    max_look_back_period: 2m
  query_ingesters_within: 3h

query_range:
  split_queries_by_interval: 5m
  max_retries: 5
  cache_results: true
  parallelise_shardable_queries: true

  results_cache:
    cache:
      enable_fifocache: true
      fifocache:
        max_size_items: 2048000000
        validity: 48h

frontend:
    address: 127.0.0.1
    log_queries_longer_than: 5s
    compress_responses: true
 
```
