### ISSUE TITLE
Tempo datasource is not documented

### ISSUE THREAD

**Issue by rgl** [grafana/grafana#43013]
**What happened**:

The Tempo datasource is not documented at https://grafana.com/docs/grafana/latest/administration/provisioning/

**What you expected to happen**:

To have the Tempo datasource documented so I can properly define it in a datasources.yml configuration file.

**PS** For reference, the current datasources can be obtained from the [data source api](https://grafana.com/docs/grafana/latest/http_api/data_source/) at http://localhost:3000/api/datasources.

This is somewhat related to https://github.com/grafana/grafana/issues/11495.

**Comment by Elfo404** [comment]
@connorlindsey could you take a look please?

**Comment by connorlindsey** [comment]
Thanks for bringing this up. We'll get that added here: https://grafana.com/docs/grafana/latest/datasources/tempo/

**Comment by dellnoantechnp** [comment]
Now i see the source code, find this options for Temp datasource provisioning config.
code here: [https://github.com/grafana/grafana/blob/6184bf21e28e67b25f50b31e19f1e327efa78a92/public/app/plugins/datasource/tempo/datasource.ts#L586](https://github.com/grafana/grafana/blob/6184bf21e28e67b25f50b31e19f1e327efa78a92/public/app/plugins/datasource/tempo/datasource.ts#L586)

```yaml
            - name: Tempo
              type: tempo
              url: http://tempo-gateway.tempo.svc.cluster.local
              uid: tempo-datasource-uid
              access: proxy
              isDefault: false
              editable: true
              jsonData:
                tracesToLogsV2:
                  datasourceUid: loki-datasource-uid
                  spanStartTimeShift: 10m
                  spanEndTimeShift: -1h
                  tags: [{key: 'service.name', value: 'app'}]        # "service.name" trace atribute loki label "app" on Loki
                  filterByTraceID: true                                # default false, if set "true", then will be LogQL likes "{app="xxxx"} |=085ab2f3b0a0983af31d988844da9cca" in Loki
                nodeGraph:
                  enabled: true
                serviceMap:
                  datasourceUid: prometheus-mimir            # it will use some trace_* metrics from prometheus, looks like export from "grafana agent" probeboly.
                lokiSearch:
                  datasourceUid: loki-datasource-uid
                search:
                  hide: false
                  filters: [{id: "service-name", scope: "resource", tag: "service.name", operator: "="}]        # Grafana document doesn't have any docs for this, there are "filters"  fields options like GUI config under the image.
```

Tempo search config:
![image](https://github.com/grafana/grafana/assets/11703403/e904bcdf-1fff-43fe-85fb-c43fa3327426)

In the Explore:
![image](https://github.com/grafana/grafana/assets/11703403/ad8b06f1-3e9b-4a49-bf1b-430db73b8e3a)

---
This is my Tempo datasource Provisioning config to share, hope to help someone.  😊
