### ISSUE TITLE
Defaulting stack-driver data source to GCE does not work (jwt is always the default)

### ISSUE THREAD

**Issue by webzakimbo** [grafana/grafana#43077]
**What happened**:

I created a data source for grafana as follows:

```
    datasources:
    - name: Google Cloud monitoring
      type: stackdriver
      editable: true
      orgId: 1
      readOnly: false
      version: 1
      access: proxy
      jsonData:
        authenticationType: gce
```

When I access my Grafana instance, the system has picked up the datasource configuration and a Google Cloud Monitoring source is visible in the data source section, however it is defaulted to 'jwt' rather than 'gce'.

An Admin has to then manually change the datasource from jwt to gce so that the stackdriver/google cloud monitoring dashboards work.

The data source otherwise works - when I manually select 'gce' a test works (and my stackdriver graphs pull data).

As the default of gce is not correctly set this means that I cannot fully deploy my grafana instances automatically - manual intervention is required.

**What you expected to happen**:

When I access the datasource configuration as an admin and select "Google Cloud Monitoring", my data source should have defaulted to 'gce' and my dashboards should work without manual intervention as an admin.

**How to reproduce it (as minimally and precisely as possible)**:

Use the minimal data source configuration from the documentation as follows:

```
datasources:
  - name: Google Cloud Monitoring
    type: stackdriver
    access: proxy
    jsonData:
      authenticationType: gce
```

Then access Grafana (as an admin) -> datasources -> select google cloud monitoring.  It will have defaulted to 'jwt' rather than 'gce'.

**Anything else we need to know?**:

**Environment**:
- Grafana version:

Grafana v8.3.0 (914fcedb72) also just tried today's latest build Grafana v8.3.2 (afb9e8e5f3)

- Data source type & version:

google cloud monitoring

- OS Grafana is installed on:

Ubuntu

- User OS & Browser:

Mac OS & Chrome (also firefox, safari etc etc)

- Grafana plugins:

https://grafana.com/docs/grafana/latest/datasources/google-cloud-monitoring/

**Comment by Elfo404** [comment]
Hello @webzakimbo thanks for reporting this.

I just tried to reproduce this but unfortunately I couldn't.

it works as expected for me with 

```
  - name: Google Cloud Monitoring
    type: stackdriver
    access: proxy
    jsonData:
      authenticationType: gce
```

![Screenshot 2021-12-14 at 11 06 02](https://user-images.githubusercontent.com/1170767/145987697-b7854141-8e57-46bf-93bd-d8f1b5c4182b.png)

can you think of anything else in your setup that might affect this? are you sure there are no typos in your actual configuration? are you restarting grafana after applying the changes? (just trying to rule out some options)

**Comment by webzakimbo** [comment]
Hi @Elfo404 

Thanks for the quick response.

I'm not restarting grafana no - this is part of a kubernetes deployment, where the configuration gets mapped in prior to the service starting.

My full configuration looks as follows - 

```
datasources:
- name: prometheus
  type: prometheus
  access: proxy
  org_id: 1
  url: http://prometheus-server
  is_default: true
  version: 1
  editable: false
- name: Google Cloud monitoring
  type: stackdriver
  editable: true
  orgId: 1
  readOnly: false
  version: 1
  access: proxy
  jsonData:
    authenticationType: gce
```
I know that my datasources configuration is being applied because:

* on the /datasources page I see the prometheus datasource defined above (and this works)
* on the /datasources page I see the stackdriver datasource, and removing this from the configuration above removes it from hostname/datasource - so is is being added from the configuration

It's just that this:

``
  jsonData:
    authenticationType: gce
```

Is ignored.
