### ISSUE TITLE
 dashboards provisioning provider has no database write permissions because of duplicates

### ISSUE THREAD

**Issue by double-yaya** [grafana/grafana#43530]
**What happened**:
I provisioned a grafana instance in k8s with prometheus. Datasources work, and stock dashboards work fine, but when I add an additional dashboard provider/provisioner (Beast below) to a new Dashboard folder, json dashboard files are not read/recognised (although the folder itself is, thus showing only an empty dashboard folder).

```

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      allowUiUpdates: true
      editable: true
      updateIntervalSeconds: 10
      options:
        path: /var/lib/grafana/dashboards
```

[log]
`mode = console
`
logs:
```
t=2021-12-26T07:19:49+0000 lvl=warn msg="dashboards provisioning provider has no database write permissions because of duplicates" logger=provisioning.dashboard provider=default
t=2021-12-26T07:19:49+0000 lvl=warn msg="Not saving new dashboard due to restricted database access" logger=provisioning.dashboard type=file name=default provisioner=default file=/var/lib/grafana/dashboards/en/kubelet-dashboard.json folderId=1
t=2021-12-26T07:19:49+0000 lvl=warn msg="Not saving new dashboard due to restricted database access" logger=provisioning.dashboard type=file name=default provisioner=default file=/var/lib/grafana/dashboards/cluster/kube-pod-dashboard.json folderId=5
t=2021-12-26T07:19:59+0000 lvl=warn msg="Not saving new dashboard due to restricted database access" logger=provisioning.dashboard type=file name=default provisioner=default file=/var/lib/grafana/dashboards/cluster/kube-pod-dashboard.json folderId=5
t=2021-12-26T07:19:59+0000 lvl=warn msg="Not saving new dashboard due to restricted database access" logger=provisioning.dashboard type=file name=default provisioner=default file=/var/lib/grafana/dashboards/en/kubelet-dashboard.json folderId=1
```

**What you expected to happen**:
auto reload dashboard to grafana ui

Anything else we need to know?:
restart grafana or use api reload (http://ip/grafana/api/admin/provisioning/dashboards/reload) works 

**Environment**:
- Grafana version:8.3.3
- Data source type & version:sqllite3
- OS Grafana is installed on:linux
- User OS & Browser:Linux + Chrome
- Grafana plugins:
- Others:

**Comment by zuchka** [comment]
Thanks for creating this issue, @double-yaya 

> has no database write permissions because of duplicates

can you please try to clarify this statement? Ty!

**Comment by manfred-ackermann** [comment]
Hey @double-yaya 

Check the contents of /var/lib/grafana/dashboards/ for non-unique existence of dashboard uids in the grafana container, e.g.

```
cd /var/lib/grafana/dashboards/
for i in $(find ./ -type f); do tail $i; done|grep '"uid": '|cut -f2 -d':'|sort|uniq -c|grep -v ' 1 '
```
If something comes up, the above command tell you the un-unique uids used.

**Comment by ctsanjuan** [comment]
Hey @double-yaya,
Not only unique uid, title of dashboards stored in the same folder must be unique too. Logs provided are not complete. In the case of duplicated title something similar must appear:
`{"folderID":<number>,"logger":"provisioning.dashboard","lvl":"warn","msg":"dashboard title is not unique in folder","providers":["sidecarProvider"],"t":"2022-01-20T10:55:51.49810515Z","times":2,"title":"dashboard_title"}`

**Comment by adeverteuil** [comment]
I ran into this error since I have two dashboard provisioning providers pointing to the same path. I want to provision the same set of dashboards in two different orgs.

My dashboards provisioning config file:
```
apiVersion: 1

providers:
 - name: 'Org one'
   orgId: 1
   folder: ''
   folderUid: ''
   type: file
   options:
     path: /var/lib/grafana/dashboards
 - name: 'Org three'
   orgId: 3
   folder: ''
   folderUid: ''
   type: file
   options:
     path: /var/lib/grafana/dashboards
```

**Comment by grafanabot** [comment]
Thanks for creating this issue! We think it's missing some basic information. 

Follow the issue template and add additional information that will help us replicate the problem. 
For data visualization issues: 
- Query results from the inspect drawer (data tab & query inspector)
- Panel settings can be extracted in the panel inspect drawer JSON tab

For dashboard related issues: 
- Dashboard JSON can be found in the dashboard settings JSON model view

For authentication, provisioning and alerting issues, Grafana server logs are useful. 

Happy graphing!

**Comment by shashank-omre-cldcvr** [comment]
```
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'first'
        orgId: 1
        type: file
        folder: 'first'
        allowUiUpdates: true
        disableDeletion: false
        updateIntervalSeconds: 10
        editable: true
        options:
          path: /tmp/dashboards/first
      - name: 'test'
        orgId: 1
        type: file
        folder: ''
        allowUiUpdates: true
        disableDeletion: false
        updateIntervalSeconds: 10
        editable: true
        options:
          path: /tmp/dashboards/test
```
I'm also facing the same issue
any solution.

```
  annotations:
    k8s-sidecar-target-directory: "/tmp/dashboards/test"
```
**Error msg**

`t=2022-02-11T08:29:57+0000 lvl=warn msg="Not saving new dashboard due to restricted database access" logger=provisioning.dashboard type=file name=sidecarProvider provisioner=sidecarProvider file=/tmp/dashboards/test/test-overview.json folderId=0`

**Comment by wbrowne** [comment]
As mentioned by @manfred-ackermann and @ctsanjuan, this "restricted database access" is a mechanism to prevent overwriting due to duplicate data. There should be therefore some dashboard provisioning data found that's causing this to occur.

Some notes as per [the provisioning documentation](https://grafana.com/docs/grafana/latest/administration/provisioning/):

>Note: Provisioning allows you to overwrite existing dashboards which leads to problems if you re-use settings that are supposed to be unique. Be careful not to re-use the same title multiple times within a folder or uid within the same installation as this will cause weird behaviors.

@adeverteuil that issue fixed as for `8.4.0-beta1` - https://github.com/grafana/grafana/pull/44151

@shashank-omre-cldcvr are there any more logs prior to _"Not saving new dashboard due to restricted database access"_ that you can share? Furthermore, are you sure there isn't duplicate data shared between `/tmp/dashboards/first` and `/tmp/dashboards/test`? If not, would you mind sharing the `JSON` in order to help reproduce this issue?

**Comment by siavashs** [comment]
We've also noticed that some dashboards disappear from our Grafana instances randomly, this started late last year.
We run 3 replicas of grafana pods on our K8s cluster, each pod has it's on sidecar and I wonder if this is contributing to the issue in any way.
We also see the above error in our Grafana logs which disappears after restarting the pods, we are not sure yet what triggers it, it could be the dashboard deployments by the applications.

**Comment by wbrowne** [comment]
Do you also see issues with database locking (from the logs or elsewhere) @siavashs?

**Comment by clux** [comment]
we run an entirely gitops provisioned set of dashboards and sometimes users made edits in the repo that also triggered this behaviour. it's not bad that this is an error, but it is kind of unintuitive that the entire dashboard loading shuts down if there is a single duplicate. it would be better if the duplicate uid/title dashboards were excluded instead - so one bad actor cannot screw it up for everyone.

anyway, we have a primitive check pre-merge that helps catch it in the dashboard monorepo case (harder to check this if they are all over the place). dropping it here in case people run into this:

```sh
  # cheap check for uniqueness of dashboard titles (also halts grafana dashboard provider)
  echo "cheap checking dashboard titles for uniqueness:"
  echo "(if any dashboard titles are listed below, they have a title used elsewhere)"
  diff <(grep "^      \"title\"" -rin dashboards/ | cut -d':' -f4 | sort) \
    <(grep "^      \"title\"" -rin dashboards/ | cut -d':' -f4 | sort | uniq)
```

(this assumes dashboard json in configmaps are indented at 4 characters + normal `jq` indents after)

**Comment by totoroot** [comment]
> ```
> cd /var/lib/grafana/dashboards/
> for i in $(find ./ -type f); do tail $i; done|grep '"uid": '|cut -f2 -d':'|sort|uniq -c|grep -v ' 1 '
> ```
> 
> If something comes up, the above command tell you the un-unique uids used.

Just wanted to add, that in addition to @manfred-ackermann's suggestion the following can be used to find and list filenames and uids of all dashboards in a top-level directory recursively in a table:

```sh
for i in $(find ./**/*.json -type f); do echo "$(yq '.uid' $i) $i"; done | sort | column -t
```

Prerequisite is to have [`yq`](https://github.com/mikefarah/yq) installed but it can be achieved with `grep` just as well.

**Comment by andrejshapal** [comment]
Hello, 
I think I know how to reproduce this issue:

1. Create dashboard config with uID a for folder /tmp/dashboard/a and push into grafana.
2. Change config uID a folder to /tmp/dasboard/b and push into grafana. 
There will be an error for duplicates in uID because due to some circumstances, the dashboard from folder a is not getting deleted. 

To fix this works:
1. Create copy of config a with uID b for folder /tmp/dashboard/a and another name, push to grafana.
In this case the first dashboard will be changed for the new one with another uID and conflict will be avoided. 
2. Delete configmap with uID b. 
And here this dashboard will disappear from grafana. 

Have no idea why in case when folder is changed the dashboard not getting deleted and conflict occurs. Probably bug in logic.

**Comment by ying-jeanne** [comment]
@andrejshapal hey, could you share in your example what is your provision configuration path. https://github.com/grafana/grafana/blob/main/pkg/services/provisioning/provisioning.go#L189, look at the code. for reload, every time we re-walkthrough the file system, without deleting the existing provisioned dashboard, just append the new ones.

**Comment by ying-jeanne** [comment]
@andrejshapal is that possible you trigger one of those reload API to test, for example after finish step 2 Change config uID a folder to /tmp/dasboard/b and push into grafana, use the API here to force reload the dashboard configuration and see what happens https://grafana.com/docs/grafana/latest/http_api/admin/#reload-provisioning-configurations

**Comment by commixon** [comment]
I think this is relevant: https://github.com/grafana/grafana/issues/39467

**Comment by siavashs** [comment]
> Do you also see issues with database contention/locking (from the logs or elsewhere) @siavashs?

@wbrowne not so far but I'll dig deeper the next time issue happens.

**Comment by andrejshapal** [comment]
> @andrejshapal is that possible you trigger one of those reload API to test, for example after finish step 2 Change config uID a folder to /tmp/dasboard/b and push into grafana, use the API here to force reload the dashboard configuration and see what happens https://grafana.com/docs/grafana/latest/http_api/admin/#reload-provisioning-configurations

Hello, 
We have checked and (http://ip/grafana/api/admin/provisioning/dashboards/reload) works in order to fix the problem without restarting grafana.

**Comment by jollyekb** [comment]
Grafana 9.4.3 samr problem. 
Not saving new dashboard due to restricted database access
uid of dashboards is uniq

**Comment by manfred-ackermann** [comment]
Hey jollyekb

> uid of dashboards is uniq
Does it still fit into the uid restrictions (length)?

IIRC it's a 40 char database field.

Am Di., 28. März 2023 um 10:04 Uhr schrieb jollyekb <
***@***.***>:

**Comment by double-yaya** [comment]
fix it ,thanks all

**Comment by Dunge** [comment]
I'm having a similar issue with dashboards provisioned via the helm chart and gnetId. They show up correctly the first time, but then cannot be modified. Even if I delete them manually and restart the grafana pod, the error remains.

config:
```
  dashboardProviders:
    dashboardproviders.yaml:
     apiVersion: 1
     providers:
     - name: 'imported'
       orgId: 1
       folder: 'imported'
       type: file
       disableDeletion: true
       editable: true
       options:
         path: /var/lib/grafana/dashboards/standard

  dashboards:
    imported:
      AspNet:
        gnetId: 10915
```

log:
```
logger=provisioning.dashboard t=2023-04-24T17:33:35.391897122Z level=warn msg="dashboards provisioning provider has no database write permissions because of duplicates" provider=imported orgId=1
logger=provisioning.dashboard type=file name=imported t=2023-04-24T17:33:35.424479555Z level=warn msg="Not saving new dashboard due to restricted database access" provisioner=imported file=/var/lib/grafana/dashboards/standard/ASPNET.json folderId=412
```

**Comment by grahamprimm** [comment]
I'm having the same issue with multiple dashboards, a restart usually fixes the issue but not always

**Comment by stepanselyuk** [comment]
I see there are three ways to put some dashboards in different folders (I will explain on an example of kube prometheus stack):

1) Just set:
```
grafana.sidecar.dashboards.provider.foldersFromFilesStructure: true
```
and use annotation in configmap of a dashboard:
```
  annotations:
    k8s-sidecar-target-directory: My Dashboards
```
this way dashboards will be physically located at `${grafana.sidecar.dashboards.folder}/My Dashboards` or if specified additionally `grafana.sidecar.dashboards.defaultFolderName: default`, dashboards will be placed in `${grafana.sidecar.dashboards.folder}/${grafana.sidecar.dashboards.defaultFolderName}/My Dashboards`. The default of former for KPS is `/tmp/dashboards`

2) More harder way:
```
spec.values.grafana.sidecar.dashboards.extraMounts:
            - name: sc-user-dashboards-volume
              mountPath: /tmp/user-dashboards
            - name: sc-mimir-dashboards-volume
              mountPath: /tmp/mimir-dashboards

spec.values.grafana.dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
            - name: 'userDashboards'
              orgId: 1
              folder: 'User Dashboards'
              type: file
              disableDeletion: true
              allowUiUpdates: false
              options:
                foldersFromFilesStructure: false
                path: /tmp/user-dashboards
            - name: 'mimirDashboards'
              orgId: 1
              folder: 'Mimir Dashboards'
              type: file
              disableDeletion: true
              allowUiUpdates: false
              options:
                foldersFromFilesStructure: false
                path: /tmp/mimir-dashboards

# this will create volumes definition as well
spec.values.grafana.extraEmptyDirMounts:
       - name: sc-user-dashboards-volume
         mountPath: /tmp/user-dashboards
       - name: sc-mimir-dashboards-volume
         mountPath: /tmp/mimir-dashboards
```
and specify in dashboards' configmaps:
```
  annotations:
    k8s-sidecar-target-directory: /tmp/mimir-dashboards
    
  annotations:
    k8s-sidecar-target-directory: /tmp/user-dashboards
```
so files will be physically placed outside of the default path.

3) Probably `grafana.sidecar.dashboards.defaultFolderName` can be used with placing other folders also just under /tmp/dashboards, without extra mounts. But I did not test it.
