### ISSUE TITLE
Streaming data source doesn't work in grafana 8

### ISSUE THREAD

**Issue by RafalEsp** [grafana/grafana#43612]
**What happened**: Simple streaming data source that I have created doesn't work on Grafana 8. The plugin doesn't appear on the available data sources list when I want to add it manually.

**What you expected to happen**: Streaming data source is recognized in the same way in Grafana 8 as in Grafana 7

**How to reproduce it (as minimally and precisely as possible)**: In docker-compose, mount a volume of the custom streaming data source plugin that works in Grafana 7 to Grafana 8 docker container.

```
grafana8:
    image: grafana/grafana:latest
    volumes:
      - ./provisioning/providers:/etc/grafana/provisioning
      - ./provisioning/dashboards:/var/lib/grafana/dashboards
      - ./dist/:/var/lib/grafana/plugins/enreach-stream
 ```

**Environment**:
- Grafana version: 7.5.9 and the latest 8
- Data source type & version: custom, basic streaming data source
- OS Grafana is installed on: official grafana docker image
- User OS & Browser: MacOs + Chrome
- Grafana plugins: -
- Others: -

**Grafana 7**
<img width="1150" alt="Screenshot 2022-01-03 at 11 51 42" src="https://user-images.githubusercontent.com/6512351/147922574-5d2f556f-01ec-4dd2-9b30-50c02e811843.png">

**Grafana 8**
<img width="2058" alt="Screenshot 2022-01-03 at 11 33 07" src="https://user-images.githubusercontent.com/6512351/147922661-8e511694-da0a-461d-956e-8960c3b99b5c.png">
