### ISSUE TITLE
error in expanding template <$values.B>: map has no entry for key \"B\""

### ISSUE THREAD

**Issue by waterdrop01** [grafana/grafana#44499]
**What happened**:
I upgraded Grafana from **v8.3.0** to **v8.3.4**, and Loki/promtail from **v2.4.1** to **v2.4.2** using helm chart.

Following the upgrade, the grafana frontend shows "404 page not found", and grafana logs shows "error in expanding template":

```
lvl=eror msg="error in expanding template" logger=ngalert name=errorvalue value="{{ $values.B }}" err="error executing template __alert_TEST qt-js log errors: template: __alert_TEST qt-js log errors:1:86: executing \"__alert_TEST qt-js log errors\" at <$values.B>: map has no entry for key \"B\""
t=2022-01-26T21:14:37+0000 lvl=eror msg="error in expanding template" logger=ngalert name=object value="Service: {{ $values.B.Labels.app }}" err="error executing template __alert_TEST qt-js log errors: template: __alert_TEST qt-js log errors:1:95: executing \"__alert_TEST qt-js log errors\" at <$values.B.Labels.app>: map has no entry for key \"B\""
lvl=warn msg="ignoring unexpected file while scanning local working directory" logger=ngalert.multiorg.alertmanager filename=/var/lib/grafana/alerting/alert
lvl=warn msg="ignoring unexpected file while scanning local working directory" logger=ngalert.multiorg.alertmanager filename=/var/lib/grafana/alerting/body
lvl=warn msg="ignoring unexpected file while scanning local working directory" logger=ngalert.multiorg.alertmanager filename=/var/lib/grafana/alerting/title
```

**What you expected to happen**:
I expect Grafana to start without any error.

**How to reproduce it (as minimally and precisely as possible)**:
```
helm repo add grafana https://grafana.github.io/helm-charts
helm repo update
helm upgrade grafana grafana/grafana --namespace=monitoring --values helm-values.yml
```
And here is my `helm-values.yml` file:

```yml
image:
  repository: grafana/grafana
  tag: 8.3.0
  pullPolicy: IfNotPresent

persistence:
  type: pvc
  enabled: true
  storageClassName:
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  annotations: {}
  finalizers:
    - kubernetes.io/pvc-protection
```

Note: I'm using the new alerting system

Any feedback would be much appreciated! Many thanks...
