### ISSUE TITLE
MSSQL Datasource username empty after container restart

### ISSUE THREAD

**Issue by ZealousMacwan** [grafana/grafana#44736]
**What happened**:
Created MSSQL Datasource provisioned using YML file and added database username from UI. After the container restarts, the username was removed from UI and the data panel was throwing an error on login failed for user ". Volume was mounted to persist data.

**What you expected to happen**:
MSSQL Datasource field "username" should be persisted even after a container restart

**How to reproduce it (as minimally and precisely as possible)**:

Spin up MSSQL Docker container using the below link or have your own MSSQL connection
[MSSQL Docker](https://github.com/ZealousMacwan/mssql-docker)

1. Create a below datasources.yml file under C:\datasources.yml
```
# config file version
apiVersion: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:
  # <string, required> name of the datasource. Required
- name: Prometheus
  # <string, required> datasource type. Required
  type: prometheus
  # <string, required> access mode. proxy or direct (Server or Browser in the UI). Required
  access: direct
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string> url
  url:
  isDefault: false
  version: 1
  # <bool> allow users to edit datasources from the UI.
  editable: true
- name: MSSQL
  # <string, required> datasource type. Required
  type: mssql
  # <string, required> access mode. proxy or direct (Server or Browser in the UI). Required
  access: proxy
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string> url
  url:
  database:
  user: 
  password :
  isDefault: false
  version: 1
  # <bool> allow users to edit datasources from the UI.
  editable: true
  
```

2. Run Grafana 8.3.4 container
```
docker run -d -p 3000:3000 --name=grafana4 --mount type=bind,source=C:/datasources.yml,target=/etc/grafana/provisioning/datasources/datasources.yml -v grafana-storage4:/var/lib/grafana grafana/grafana:8.3.4
```
3. Open localhost:3000 in a browser
4. Go to data sources and fill MSSQL data source details (attention on username it will be empty next time after restart)
5. Test and Save data source
6. Stop container
```
docker stop grafana4
```
7. Start container
```
docker start grafana4
```
8. Check username field in MSSQL data source which is empty now
9. 
![image](https://user-images.githubusercontent.com/22982363/152032447-57903e3f-ce4d-4955-a5e5-f839a107ad5b.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.4, 8.3.3
- Data source type & version: MSSQL 
- OS Grafana is installed on: Docker desktop on MS Windows 10 Pro 
- User OS & Browser: MS Windows 10 & Google Chrome
- Grafana plugins: MSSQL
- Others:
