### ISSUE TITLE
ha_advertise_address does not work when using Grafana in Docker

### ISSUE THREAD

**Issue by erkexzcx** [grafana/grafana#45060]
Here is my HA configuration that I am using and works "fine" (I hope)
```toml
[server]
root_url = http://grafana.company.com/

[database]
type = mysql
host = mariadb.company.com:3306
name = grafana
user = asdfasdf
password = asdfasdf

[auth]
login_maximum_inactive_lifetime_duration = 365d
login_maximum_lifetime_duration = 365d

[auth.ldap]
enabled = true

[unified_alerting]
enabled = true
ha_listen_address = "0.0.0.0:3001"
ha_advertise_address = "0.0.0.0:3001"
ha_peers = "docker0.company.com:3001,docker1.company.com:3001"

[metrics]
enabled = false
```

When I try to change below configuration:
```toml
ha_advertise_address = "0.0.0.0:3001"
```

to this:
```toml
ha_advertise_address = "docker0.company.com:3001"
```

I get this error and Grafana in Docker container does not start:
```
t=2022-02-08T12:14:19+0000 lvl=info msg="component=cluster level=warn err=\"couldn't deduce an advertise address: failed to parse advertise addr 'docker0.company.com'\"" logger=ngalert.multiorg.alertmanager Failed to start grafana. error: unable to initialize gossip mesh: create memberlist: Failed to get final advertise address: Failed to parse advertise address "docker0.company.com" unable to initialize gossip mesh: create memberlist: Failed to get final advertise address: Failed to parse advertise address "docker0.company.com"
```

If I leave `0.0.0.0:3001` it starts, but I am seeling loads of these in logs:
```
t=2022-02-08T12:23:31+0000 lvl=info msg="component=cluster level=debug memberlist=\"2022/02/08 12:23:31 [ERR] memberlist: Failed to send ping: write udp [::]:3001->0.0.0.0:3001: sendto: cannot assign requested address\\n\"" logger=ngalert.multiorg.alertmanager
t=2022-02-08T12:23:32+0000 lvl=info msg="component=cluster level=debug memberlist=\"2022/02/08 12:23:32 [ERR] memberlist: Failed to send ping: write udp [::]:3001->0.0.0.0:3001: sendto: cannot assign requested address\\n\"" logger=ngalert.multiorg.alertmanager
```

Could you please clarify what am I doing wrong? [The documentation](https://grafana.com/docs/grafana/latest/administration/configuration/#unified_alerting) is clear to me:
> **ha_advertise_address**
> Explicit address/hostname and port to advertise other Grafana instances. The port is used for both TCP and UDP.

Which means I am doing the right thing - letting other Grafana instances know that if they want to reach me, they should reach me by docker host address? But then why Grafana fails to start?

**Environment**:
- Grafana version: Grafana v8.3.4 (a551d74b11)
- Data source type & version: N/A
- OS Grafana is installed on: Docker, `grafana-oss:8.3.4`
- User OS & Browser: N/A
- Grafana plugins: alexanderzobnin-zabbix-app,goshposh-metaqueries-datasource,grafana-azure-monitor-datasource,grafana-clock-panel,grafana-piechart-panel,grafana-polystat-panel,grafana-simple-json-datasource,grafana-worldmap-panel,jdbranham-diagram-panel,natel-discrete-panel,vonage-status-panel,xginn8-pagerduty-datasource
- Others: N/A

**Comment by erkexzcx** [comment]
Maybe Grafana is unable to parse address? It's actually more complex than `docker0.company.com`:
```
something-docker5.az9.company.com:3001
```

**Comment by erkexzcx** [comment]
I've been playing a bit with a docker on my machine :)

This seems to be **not** working:
```
[unified_alerting]
enabled = true
ha_listen_address = "0.0.0.0:3001"
ha_advertise_address = "0.0.0.0:3001"
ha_peers = "grafana0:3001,grafana1:3001"
```

And this seems to be working:
```
[unified_alerting]
enabled = true
ha_listen_address = ":3001"
ha_advertise_address = ":3001"
ha_peers = "grafana0:3001,grafana1:3001"
```

**Comment by erkexzcx** [comment]
> .# Listen address/hostname and port to receive unified alerting messages for other Grafana instances. The port is used for both TCP and UDP. It is assumed other Grafana instances are also running on the same port. The default value is `0.0.0.0:9094`.
> ;ha_listen_address = "0.0.0.0:9094"
> 
> .# Listen address/hostname and port to receive unified alerting messages for other Grafana instances. The port is used for both TCP and UDP. It is assumed other Grafana instances are also running on the same port. The default value is `0.0.0.0:9094`.
;ha_advertise_address = ""

Basically `0.0.0.0:9094` breaks things and `:9094` do not. Please fix this behaviour. It should be identical.

Using `0.0.0.0:3001` does not even start the Grafana. It crashes on startup.

**Comment by erkexzcx** [comment]
Also, can you clarify the purpose of `ha_advertise_address` field in general? Aren't this field used to specify external "host:port" which will be advertised to other Grafana's alertmanager instances of the cluster?

I understand this as like this:
- `ha_listen_address` used for binding alertmanager port.
- `ha_advertise_address` used for letting other Grafana's alertmanager instances know how to access this instance (aka external "host:port"). In my case it's suppossed to be docker host ip/host and port.
- `ha_peers` is initial list of Grafana's alert manager nodes, known as bootstrap servers. These will be used to retrieve full list of hosts within the Grafana's alertmanager cluster.

Am I right? If so, `ha_advertise_address` field is completely broken and unusable.

**Comment by erkexzcx** [comment]
Related: https://github.com/grafana/grafana/pull/41503

**Comment by erkexzcx** [comment]
Looks to be working this way:
```toml
[unified_alerting]
enabled = true
ha_listen_address = ":3001"
ha_advertise_address = "123.123.123.123:3001"
ha_peers = "server1:3001,server2:3001"
```

In `ha_advertise_address` one must use IP rather than host (which resolves to IP). In `ha_peers` I am not sure, but using host seem to be working.

Would be great if Grafana fixes logic behind `ha_advertise_address` so one could provide hostname instead of IP...

And also comments, which are copy/paste.
