### ISSUE TITLE
Creation of a container does not set up timescaledb as data source

### ISSUE THREAD

**Issue by flixman** [grafana/grafana#45209]
**What happened**:
I am able to create a data source programmatically by performing a post against grafana with the following payload:
```python
    data = dict(
      name="PostgreSQL",
      type="postgres",
      url="db:5432",
      access="proxy",
      isDefault=True,
      basicAuth=False,
      database=os.getenv("GF_DATABASE_NAME"),
      user=os.getenv("GF_DATABASE_USER"),
      secureJsonData=dict(password=os.getenv("GF_DATABASE_PASSWORD")),
      jsonData=dict(
          postgresVersion=1200,
          sslmode="disable",
          timescaledb=True,
          tlsAuth=False
      )
    )
```
However, the following configuration in docker-compose does not provide the same result (no data source gets created):
```yaml
grafana:
    hostname: grafana
    image: grafana/grafana-oss:latest
    env_file:
      - .env.grafana
    environment:
      - GF_DATABASE_USER=energyreader
      - GF_DATABASE_PASSWORD=@9F7a&dL6C_3Exh
      - GF_DATABASE_HOST=db:5432
      - GF_DATABASE_NAME=energyhub
      - GF_SESSION_PROVIDER_CONFIG=user=energyreader password=@9F7a&dL6C_3Exh host=db port=5432 dbname=energyhub sslmode=disable timescaledb=True default=True postgresVersion=1200
```
With the contents of .env.grafana being
```
GF_DATABASE_TYPE=postgres
GF_SESSION_PROVIDER=postgres
GF_DATABASE_SSL_MODE=disable
GF_USERS_ALLOW_SIGN_UP=false
GF_SECURITY_ADMIN_USER=admin
GF_SECURITY_ADMIN_PASSWORD=<password>
```

**What you expected to happen**:
I'd expect the datasource to be created at container creation time.

**How to reproduce it (as minimally and precisely as possible)**:
Run the following docker-compose
```yaml
grafana:
    hostname: grafana
    image: grafana/grafana-oss:latest
    environment:
      - GF_DATABASE_TYPE=postgres
      - GF_SESSION_PROVIDER=postgres
      - GF_DATABASE_SSL_MODE=disable
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=<password>
      - GF_DATABASE_USER=energyreader
      - GF_DATABASE_PASSWORD=<password>
      - GF_DATABASE_HOST=db:5432
      - GF_DATABASE_NAME=energyhub
      - GF_SESSION_PROVIDER_CONFIG=user=energyreader password=<password> host=db port=5432 dbname=energyhub sslmode=disable timescaledb=True default=True postgresVersion=1200
```

**Anything else we need to know?**:
Not, as far as I can tell.

**Environment**:
- Grafana version: grafana/grafana-oss:latest
- Data source type & version: postgresql with timescaledb plugin, 14
- OS Grafana is installed on: n/a
- User OS & Browser: Arch linux, Firefox
- Grafana plugins: none
- Others:
