### ISSUE TITLE
[8.3.4] Alerting: "manageAlerts: false" option doesn't disable "Manage alerts via Alerting UI"

### ISSUE THREAD

**Issue by andy812** [grafana/grafana#45298]
My datasource config:
```
datasources:
    - access: proxy
      manageAlerts: false
      name: Prometheus
      type: prometheus
      url: http://prom-prometheus:9090
```
But `manageAlerts: false` doesn't really disable "Manage alerts via Alerting UI".
<img width="478" alt="изображение" src="https://user-images.githubusercontent.com/29895539/153597906-32518faf-3d05-4ac0-813b-b0c4e7441bba.png">

Expectation: `manageAlerts: false` option should disable alerts management via Alerting UI.

**Environment**:
- Grafana version: 8.3.4

**Comment by zoltanbedi** [comment]
manageAlerts option should be under jsonData see https://grafana.com/docs/grafana/latest/administration/provisioning/

```yaml
  - name: gdev-prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    jsonData:
      manageAlerts: false
```
