### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'displayMode')

### ISSUE THREAD

**Issue by jicki** [grafana/grafana#45648]
**What happened**:

A Grafana v8.3.6 to B Grafana v8.3.6

Panel JSON

Error

TypeError: Cannot read properties of undefined (reading 'displayMode')

** JSON **

```yaml
{
  "id": 63,
  "gridPos": {
    "h": 12,
    "w": 24,
    "x": 0,
    "y": 1
  },
  "type": "table",
  "title": "域名状态明细",
  "transformations": [
    {
      "id": "merge",
      "options": {}
    },
    {
      "id": "organize",
      "options": {
        "excludeByName": {
          "Time": true,
          "Value #B": true,
          "__name__": true,
          "cluster": true,
          "job": true,
          "prometheus": true
        },
        "indexByName": {
          "Time": 0,
          "Value #A": 5,
          "Value #B": 14,
          "Value #C": 6,
          "Value #D": 12,
          "Value #E": 11,
          "Value #F": 7,
          "Value #G": 8,
          "Value #H": 9,
          "__name__": 13,
          "cluster": 1,
          "instance": 2,
          "job": 3,
          "prometheus": 4,
          "version": 10
        },
        "renameByName": {
          "Value #A": "连通性",
          "Value #C": "状态",
          "Value #D": "证书(天)",
          "Value #E": "Http 版本",
          "Value #F": "耗时",
          "Value #G": "1H 可用%",
          "Value #H": "DNS",
          "instance": "URL",
          "job": "类型",
          "prometheus": "",
          "version": "TLS版本"
        }
      }
    }
  ],
  "datasource": {
    "type": "prometheus",
    "uid": "${cluster}"
  },
  "pluginVersion": "8.3.6",
  "fieldConfig": {
    "defaults": {
      "custom": {
        "align": "center",
        "displayMode": "auto"
      },
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          },
          {
            "color": "red",
            "value": 80
          }
        ]
      },
      "mappings": [],
      "color": {
        "mode": "thresholds"
      },
      "noValue": "无",
      "unit": "short"
    },
    "overrides": [
      {
        "matcher": {
          "id": "byName",
          "options": "URL"
        },
        "properties": [
          {
            "id": "custom.width",
            "value": 602
          },
          {
            "id": "custom.displayMode",
            "value": "json-view"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "连通性"
        },
        "properties": [
          {
            "id": "mappings",
            "value": [
              {
                "options": {
                  "0": {
                    "color": "red",
                    "index": 0,
                    "text": "离线"
                  },
                  "1": {
                    "color": "green",
                    "index": 1,
                    "text": "在线"
                  }
                },
                "type": "value"
              }
            ]
          },
          {
            "id": "custom.displayMode",
            "value": "color-background"
          },
          {
            "id": "custom.width",
            "value": 114
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "状态"
        },
        "properties": [
          {
            "id": "decimals",
            "value": 0
          },
          {
            "id": "thresholds",
            "value": {
              "mode": "absolute",
              "steps": [
                {
                  "color": "green",
                  "value": null
                },
                {
                  "color": "semi-dark-orange",
                  "value": 400
                },
                {
                  "color": "semi-dark-red",
                  "value": 500
                }
              ]
            }
          },
          {
            "id": "custom.displayMode",
            "value": "color-background"
          },
          {
            "id": "mappings",
            "value": [
              {
                "options": {
                  "null": {
                    "color": "semi-dark-red",
                    "index": 0,
                    "text": "无"
                  }
                },
                "type": "value"
              }
            ]
          },
          {
            "id": "custom.width",
            "value": 96
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "耗时"
        },
        "properties": [
          {
            "id": "unit",
            "value": "s"
          },
          {
            "id": "custom.displayMode",
            "value": "gradient-gauge"
          },
          {
            "id": "decimals",
            "value": 1
          },
          {
            "id": "max",
            "value": 0.5
          },
          {
            "id": "color",
            "value": {
              "mode": "continuous-GrYlRd"
            }
          },
          {
            "id": "custom.width"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "1H 可用%"
        },
        "properties": [
          {
            "id": "unit",
            "value": "percentunit"
          },
          {
            "id": "decimals"
          },
          {
            "id": "thresholds",
            "value": {
              "mode": "absolute",
              "steps": [
                {
                  "color": "semi-dark-red",
                  "value": null
                },
                {
                  "color": "light-yellow",
                  "value": 0.9
                },
                {
                  "color": "light-green",
                  "value": 0.99
                }
              ]
            }
          },
          {
            "id": "custom.displayMode",
            "value": "gradient-gauge"
          },
          {
            "id": "max",
            "value": 1
          },
          {
            "id": "color"
          },
          {
            "id": "custom.width",
            "value": 288
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "DNS"
        },
        "properties": [
          {
            "id": "unit",
            "value": "s"
          },
          {
            "id": "custom.displayMode",
            "value": "color-background"
          },
          {
            "id": "decimals"
          },
          {
            "id": "thresholds",
            "value": {
              "mode": "absolute",
              "steps": [
                {
                  "color": "green",
                  "value": null
                },
                {
                  "color": "orange",
                  "value": 0.01
                },
                {
                  "color": "red",
                  "value": 0.02
                }
              ]
            }
          },
          {
            "id": "custom.width",
            "value": 128
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "TLS版本"
        },
        "properties": [
          {
            "id": "mappings",
            "value": [
              {
                "options": {
                  "TLS 1.0": {
                    "color": "semi-dark-red",
                    "index": 0,
                    "text": "1.0"
                  },
                  "TLS 1.1": {
                    "color": "semi-dark-yellow",
                    "index": 1,
                    "text": "1.1"
                  },
                  "TLS 1.2": {
                    "color": "green",
                    "index": 2,
                    "text": "1.2"
                  },
                  "TLS 1.3": {
                    "color": "green",
                    "index": 3,
                    "text": "1.3"
                  }
                },
                "type": "value"
              }
            ]
          },
          {
            "id": "custom.displayMode",
            "value": "color-background"
          },
          {
            "id": "thresholds",
            "value": {
              "mode": "absolute",
              "steps": [
                {
                  "color": "semi-dark-red",
                  "value": null
                }
              ]
            }
          },
          {
            "id": "custom.width",
            "value": 102
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "Http 版本"
        },
        "properties": [
          {
            "id": "custom.displayMode",
            "value": "color-background"
          },
          {
            "id": "decimals",
            "value": 1
          },
          {
            "id": "thresholds",
            "value": {
              "mode": "absolute",
              "steps": [
                {
                  "color": "semi-dark-red",
                  "value": null
                },
                {
                  "color": "orange",
                  "value": 1.1
                },
                {
                  "color": "green",
                  "value": 2
                }
              ]
            }
          },
          {
            "id": "custom.width",
            "value": 109
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "证书(天)"
        },
        "properties": [
          {
            "id": "unit",
            "value": "none"
          },
          {
            "id": "thresholds",
            "value": {
              "mode": "absolute",
              "steps": [
                {
                  "color": "red",
                  "value": null
                },
                {
                  "color": "orange",
                  "value": 15
                },
                {
                  "color": "green",
                  "value": 30
                }
              ]
            }
          },
          {
            "id": "custom.displayMode",
            "value": "color-background"
          },
          {
            "id": "decimals",
            "value": 0
          },
          {
            "id": "custom.width",
            "value": 102
          }
        ]
      }
    ]
  },
  "options": {
    "showHeader": true,
    "footer": {
      "show": false,
      "reducer": [
        "sum"
      ],
      "fields": ""
    },
    "sortBy": [
      {
        "desc": true,
        "displayName": "耗时"
      }
    ]
  },
  "targets": [
    {
      "datasource": {
        "type": "prometheus",
        "uid": "${cluster}"
      },
      "exemplar": false,
      "expr": "probe_success{job=\"service_status\"} - 0",
      "format": "table",
      "instant": true,
      "interval": "",
      "legendFormat": "",
      "refId": "A"
    },
    {
      "datasource": {
        "type": "prometheus",
        "uid": "${cluster}"
      },
      "exemplar": false,
      "expr": "probe_tls_version_info{job=\"service_status\"}",
      "format": "table",
      "hide": false,
      "instant": true,
      "interval": "",
      "legendFormat": "",
      "refId": "B"
    },
    {
      "datasource": {
        "type": "prometheus",
        "uid": "${cluster}"
      },
      "exemplar": false,
      "expr": "probe_http_status_code{job=\"service_status\"} - 0",
      "format": "table",
      "hide": false,
      "instant": true,
      "interval": "",
      "legendFormat": "",
      "refId": "C"
    },
    {
      "datasource": {
        "type": "prometheus",
        "uid": "${cluster}"
      },
      "exemplar": false,
      "expr": "(probe_ssl_earliest_cert_expiry{job=\"service_status\"}-time())/3600/24",
      "format": "table",
      "hide": false,
      "instant": true,
      "interval": "",
      "legendFormat": "",
      "refId": "D"
    },
    {
      "datasource": {
        "type": "prometheus",
        "uid": "${cluster}"
      },
      "exemplar": false,
      "expr": "probe_http_version{job=\"service_status\"} - 0",
      "format": "table",
      "hide": false,
      "instant": true,
      "interval": "",
      "legendFormat": "",
      "refId": "E"
    },
    {
      "datasource": {
        "type": "prometheus",
        "uid": "${cluster}"
      },
      "exemplar": false,
      "expr": "probe_duration_seconds{job=\"service_status\"} - 0",
      "format": "table",
      "hide": false,
      "instant": true,
      "interval": "",
      "legendFormat": "",
      "refId": "F"
    },
    {
      "datasource": {
        "type": "prometheus",
        "uid": "${cluster}"
      },
      "exemplar": false,
      "expr": "sum_over_time(probe_success{job=\"service_status\"}[60m])/count_over_time(probe_success{job=\"service_status\"}[60m])",
      "format": "table",
      "hide": false,
      "instant": true,
      "interval": "",
      "legendFormat": "",
      "refId": "G"
    },
    {
      "datasource": {
        "type": "prometheus",
        "uid": "${cluster}"
      },
      "exemplar": false,
      "expr": "probe_dns_lookup_time_seconds{job=\"service_status\"}-0",
      "format": "table",
      "hide": false,
      "instant": true,
      "interval": "",
      "legendFormat": "",
      "refId": "H"
    }
  ]
}
```
