### ISSUE TITLE
Internal alertmanager does not alert upon prometheus defined rules

### ISSUE THREAD

**Issue by dvidben** [grafana/grafana#45698]
**What happened**:
Grafana's internal alertmanager does not alert upon firing rules defined in kube-prometheus-stack.
While Prometheus' Alertmanager does trigger notifications for any of the predefined Prometheus rules, Grafana's internal alertmanager only alerts upon Grafana's managed alerts.

The user experience becomes also more confusing since Grafana does list all the recording and firing alerts defined in Prometheus:
![image](https://user-images.githubusercontent.com/8014577/155015995-fd81ef8d-87ac-4354-98c9-837e2931b21d.png)

**What you expected to happen**:
Grafana's alertmanager to alert upon managed alerts and *also* Prometheus-defined rules.

**How to reproduce it (as minimally and precisely as possible)**:
1. Prepare a values.yaml for kube-prometheus-operator including a default receiver for testing (if using a custom webhook, provide the proper url):
```
alertmanager:
  enabled: true
  config:
    global:
      resolve_timeout: 5m
    route:
      receiver: webhook
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
    receivers:
    - name: webhook
      webhook_configs:
      - url: http://<url>
```
2. Install kube-prometheus-operator in your k8s cluster using above values.yaml.
3. Navigate to Grafana UI and configure a testing **contact point** (use your preferred notification channel, i.e: email, slack, etc)
4. Using Grafana UI, configure the contact point you created as the root default notification policy in "Notification policies" tab.
5. Using Grafana UI, configure the root Notification policy timing option "Repeat interval" to 20s so it triggers soon during testing. Save your changes
5. Wait for new notifications. You'll receive notifications from Prometheus Alertmanager, but not from Grafana.
6. Using Grafana UI, create a new managed alert that always triggers, for example CPU system seconds greater than 0 using expression: 
`container_cpu_system_seconds_total{container="kube-prometheus-stack"}` 
7. Grafana will start sending notifications for the newly created alert, but not for any of the default rules defined in Prometheus.

**Anything else we need to know?**:

**Environment**:
- Grafana version: OSS v8.3.5
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux distro.
- User OS & Browser: Windows 10, Chrome 98.0.4758.102
- Grafana plugins: None
- Others:
kube-prometheus-stack-32.2.1
