### ISSUE TITLE
[Postgresql][Provisioning] Defined password in provisioned datasources are not being loaded

### ISSUE THREAD

**Issue by ralequi** [grafana/grafana#45798]
**What happened**: 
I have defined a PSQL datasource like:

```yml
apiVersion: 1
deleteDatasources: []
datasources:
- access: proxy
  name: DEMOPSQL
  type: postgres
  user: demouser
  password: demopassword
  database: demodb
  basicAuth: false
  orgId: 1
  jsonData:
    postgresVersion: 1200
    sslmode: disable
    timeInterval: 1s
    timescaledb: true
    tlsAuth: false
    tlsAuthWithCACert: false
    tlsConfigurationMethod: file-path
    tlsSkipVerify: true

```

However I get a connection error, in grafana and in Postgresql:
```
2022-02-23 16:10:52.089 CET [3153285] demouser@demodb FATAL:  password authentication failed for user "demouser"
2022-02-23 16:10:52.089 CET [3153285] demouser@demodb DETAIL:  Password does not match for user "demouser".
        Connection matched pg_hba.conf line 96: "host    all             all             127.0.0.1/32            md5"
```

I've tested the connection properties with psql, and everything worked.
Without recompiled grafana, I've attached a GDB to the production (no debugsym) release of grafana `8.4.1` and found (with some hardcore work) that function generateConnectionString ( see https://github.com/grafana/grafana/blob/main/pkg/tsdb/postgres/postgres.go#L118 ) is returning the following string:

`user='demouser' password='' host='' dbname='demodb' sslmode='disable'`

So, after investigating for a while, I'm confident there is something blocling the field "password" from being loaded on datasource provisioning.

This kind of datasources worked at grafana 8.0.x and I think in 8.1.x too but stop working at 8.2.x 

**What you expected to happen**:
The password is correctly loaded and the datasource become usable widely 

**How to reproduce it (as minimally and precisely as possible)**:
Just copy the provisioning yml and create the corresponding psql DB/user/passwd.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.4.1
- Data source type & version: Postgresql / Provisioned datasource
- OS Grafana is installed on: Ubuntu 20
- User OS & Browser: Fedora & google chrome
- Grafana plugins: standard
- Others: Please, request if you need something more

Thank for your time and attention

**Comment by zuchka** [comment]
Thanks for creating this issue, @ralequi 

I believe you need to use `secureJsonData` as per the documentation:

see the table [at the bottom of this page](https://grafana.com/docs/grafana/latest/administration/provisioning/#using-environment-variables)

I also tested this, and the provisioning worked on my local instance:

```
  - name: Postgres
    type: postgres
    url: localhost:5432
    database: grafanadb
    user: grafana
    secureJsonData:
      password: "grafana"
    jsonData:
      sslmode: "disable" # disable/require/verify-ca/verify-full
      maxOpenConns: 0         # Grafana v5.4+
      maxIdleConns: 2         # Grafana v5.4+
      connMaxLifetime: 14400  # Grafana v5.4+
      postgresVersion: 903 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: false
```
