### ISSUE TITLE
Loki: If label value includes backslash it is not escaped and query is invalid

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#45809]
**What happened**:
In log browser, we are not escaping backslash, but it seems like we do it for Prometheus. We should probably do the same here and also look at autocomplete.

**What you expected to happen**:

When I choose value from autocomplete or label browser, backslash it should be correctly escaped.

**How to reproduce it (as minimally and precisely as possible)**:
1. You have to have logs with label values that include backslash
2. Open log browser and pick label + value with backslash
3. backslash should be escaped and query should produce result without error

**Comment by wrightsonm** [comment]
I have the same issue with Grafana Explore Tab & Loki.
Grafana 8.4.3
Loki 2.4.2
Chrome Version 98.0.4758.102 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/6232774/156434186-eb92f6a1-360f-40bb-8580-868a962fb7f5.png)

Resulting in this error:
```
Query error
Error: parse error at line 1, col 11: invalid char escape. Make sure that all special characters are escaped with \. For more information on escaping of special characters visit LogQL documentation at https://grafana.com/docs/loki/latest/logql/.
```

![image](https://user-images.githubusercontent.com/6232774/156434329-4ae616a0-e6f5-4197-bb05-e5ec5b301741.png)

When I attempt to add escaping backslashes, I also get an unexpected error:

![image](https://user-images.githubusercontent.com/6232774/156434568-30588ea4-b635-41ea-86aa-c4f78dc5a759.png)

If I enter the following query and press control enter:
`{filename="C:",job="apache"}`
I get 0 results as expected


![image](https://user-images.githubusercontent.com/6232774/156434906-367c7534-8c93-4f8f-9a97-dbe0f84d8d6a.png)

If I then attempt to edit the query, as I add the first \ of the file path I get an error message:
`{filename="C:\",job="apache"}`

![image](https://user-images.githubusercontent.com/6232774/156435046-8cf6fea8-f1fe-4091-9b04-7bd9674cd6b9.png)

**Comment by wrightsonm** [comment]
Screen capture gif to demonstrate the UI 'crashing' issue
![Animation](https://user-images.githubusercontent.com/6232774/157889719-dbe1584e-1bed-404a-852e-af3a36f0396c.gif)

I have identified a couple of workarounds to this situation for the time being with help from @ivanahuckova 

1. Ensure filenames do not have \\ using promtail pipeline stages:

```
scrape_configs:
  - job_name: apache
    
    pipeline_stages:
    - replace:
        expression: '(\\)'
        source: "filename"
        replace: "/"
    - labels:
        filename: 
    static_configs:
    - targets:
        - localhost
      labels:
        job: apache
        __path__: C:\Apache24\logs\testaccess.log
```

2. Modify the autogenerated query in grafana explore from:
{filename="C:\Apache24\logs\testaccess.log",job="apache"}
to:
{filename=`C:\Apache24\logs\testaccess.log`,job="apache"}
