### ISSUE TITLE
grafana cant provision any dashboard from file configuration

### ISSUE THREAD

**Issue by nohant** [grafana/grafana#45899]
**What happened**: grafana can't read dashboard folder

**What you expected to happen**: grafana should be able to read the dashboard folder as provisioned

**How to reproduce it (as minimally and precisely as possible)**:

have X number of dashboard in a folder, mount it under /tmp/dashboards 

```
dashboards
├── argo-sync.json
├── argocd.json
├── breezer.json
```

```
apiVersion: 1

providers:
  - name: 'dashboards'
    orgId: 1
    type: 'file'
    updateIntervalSeconds: 60
    disableDeletion: false
    allowUiUpdates: true
    options:
      path: /tmp/dashboards
```
`grafana-6cf85fd9c8-zsgmx grafana {"error":"data source not found","logger":"provisioning.dashboard","lvl":"eror","msg":"failed to save dashboard","name":"dashboards","t":"2022-02-25T09:55:57.13+0000","type":"file"}
`
**Anything else we need to know?**:

There's a typo in the error message <3.

**Environment**:
- Grafana version: 8.4
- Data source type & version: apiVersion: 1, dashboard provisioning
- OS Grafana is installed on: docker :V image is grafana/grafana:8.4.0
- User OS & Browser: every user has the problem
- Grafana plugins: no plugins.
- Others:

edit: attached folder structure

**Comment by nohant** [comment]
adding debug log level for context.
```
grafana-848f7b6dcc-48kk2 grafana {"logger":"provisioning.dashboard","lvl":"dbug","msg":"Start walking disk","name":"dashboards","path":"/tmp/dashboards/","t":"2022-02-25T11:15:42.36+0000","type":"file"}
grafana-848f7b6dcc-48kk2 grafana {"file":"/tmp/dashboards/coresystem-dashboard.json","folderId":0,"logger":"provisioning.dashboard","lvl":"dbug","msg":"saving new dashboard","name":"dashboards","provisioner":"dashboards","t":"2022-02-25T11:15:42.43+0000","type":"file"}
grafana-848f7b6dcc-48kk2 grafana {"key":"last_sent","logger":"infra.kvstore.sql","lvl":"dbug","msg":"kvstore value not found","namespace":"infra.usagestats","orgId":0,"t":"2022-02-25T11:15:42.43+0000"}
grafana-848f7b6dcc-48kk2 grafana {"error":"data source not found","logger":"provisioning.dashboard","lvl":"eror","msg":"failed to save dashboard","name":"dashboards","t":"2022-02-25T11:15:42.45+0000","type":"file"}
```

**Comment by nohant** [comment]
i tried also to remove manually a single dashboard from postgres, under `dashboard` and `dashboard_provisioning ` table.
That single dashboard hasn't come back after restarting the deployment.

```
FROM grafana/grafana:8.4.2

ARG GF_GID="0"
ENV GF_DATAPROXY_TIMEOUT="120"

USER grafana
RUN mkdir -p /tmp/dashboards
COPY dashboards /tmp/dashboards/
```

**Comment by zuchka** [comment]
This structure works for me. Try using [this repo](https://github.com/zuchka/grafana-compose/tree/main/netsage-sankey-panel) as a template and see if that gets you unblocked

```
.
├── README.md
├── docker-compose.yaml
└── provisioning
    ├── dashboards
    │   ├── .gitkeep
    │   ├── dashboards
    │   │   ├── .gitkeep
    │   │   ├── dashboard.json
    │   │   ├── disableDeletion-false.json
    │   │   └── disableDeletion-true.json
    │   └── providers.yaml
    ├── datasources
    │   ├── .gitkeep
    │   └── datasources.yml
    ├── notifiers
    │   └── .gitkeep
    └── plugins
        └── .gitkeep
```

**Comment by nohant** [comment]
1.  @zuchka  you linked a private repository
2. sorry but i don't think mine as question but more of a problem

That's my yaml file on Kubernetes and as you can see the end result is basically the same as you explained.
```

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 472
        fsGroup: 472
      containers:
      - name: grafana
        image: grafana
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 10
          periodSeconds: 3
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 10
          periodSeconds: 3
          timeoutSeconds: 3
        envFrom:
          - configMapRef:
              name: grafana-variables
          - secretRef:
              name: grafana-github-infra-managed
          - secretRef:
              name: grafana-smtp-infra-managed
          - secretRef:
              name: grafana-slack-infra-managed
          - secretRef:
              name: grafana-secretenv-infra-managed
        ports:
          - containerPort: 3000
            name: http
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 20m
            memory: 256Mi
        volumeMounts:
          - mountPath: /etc/grafana/provisioning/notifiers
            name: notifiers
          - mountPath: /etc/grafana/provisioning/datasources
            name: datasource
          - mountPath: /etc/grafana/provisioning/dashboards
            name: dashboards
      volumes:
        - name: notifiers
          configMap:
            name:  grafana-notifiers
        - name: datasource
          configMap:
            name:  grafana-datasources
        - name: dashboards
          configMap:
            name:  grafana-dashboards

```
so no, i think i'm facing a problem somewhere.
