### ISSUE TITLE
Provisioning: Plugin provisioning doesn't store secureJsonData

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#46116]
**What happened**:
Provisioning a plugin using the following yaml everything seems to work as expected, but checking the `plugin_setting` table shows that `secure_json_data` column value is `null`.
```yaml
apps:
- type: plugin
    jsonData:
      key: value
    secureJsonData:
      secureKey: secureValue
    org_id: 1
    disabled: false
```

**What you expected to happen**:
`SecureJsonData` to be properly stored in the database. This currently causes issues for multiple users so would be good to fix asap.

**Anything else we need to know?**:
Seems to have been introduced via #44989. Think providing `sqlstore.SQLStore` [here](https://github.com/grafana/grafana/blob/cd3fb8e8321259c41d566b7fda394dd4b8c61398/pkg/services/provisioning/provisioning.go#L167) is wrong - it should be `pluginsettings.Service` to properly encrypt the `secureJsonData`.

**Environment**:
- Grafana version: main branch (cd3fb8e8321259c41d566b7fda394dd4b8c61398)
