### ISSUE TITLE
Error reading Prometheus: Post "http://localhost:9090/api/v1/query": dial tcp 127.0.0.1:9090: connect: connection refused

### ISSUE THREAD

**Issue by Geek-Joey** [grafana/grafana#46434]
1.when i use grafana to configure the prometheus,
 the prometheus service is normal, i can visit the ui from `http://localhost:9090`,all the targets is up.

- the error info is :
```shell
 Error reading Prometheus: Post "http://localhost:9090/api/v1/query": dial tcp 127.0.0.1:9090: connect: connection refused
```

- the `prometheus.yml` is: 
```yml
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
# Push Gateway
  - job_name: "pushgateway"
    static_configs:
      - targets: ["localhost:9091"]
        labels:
          instance: pushgateway

  # Node Exporter
  - job_name: "node exporter"
    static_configs:
      - targets: ["localhost:9100"]

# Kafka Exporter
  - job_name: "kafka exporter"
    static_configs:
      - targets: ["localhost:9308"]
```

- the granfan service which is docker deploymed is normal , i remain the default configuration (/etc/grafana/grafana.ini).

2. i configured granfan use another prometheus address ,it worked success.

3. environment info : 
- Grafana version: v8.4.3 
- Prometheus version: 2.33.5
- OS : Mac M1 

can you give me some advice，I will be very grateful。
