### ISSUE TITLE
Prometheus datasource doesn't work after upgrading to grafana version 8.3+

### ISSUE THREAD

**Issue by ljuaneda** [grafana/grafana#46682]
**What happened**:
Prometheus datasource doesn't work anymore after upgrading from 8.2.7 to 8.3+
I've got an error in UI when testing the datasource and every dashboards failed.
In the logs : err="client_error: client error: 403"

Switching backs to docker image version 8.2.7, it's working as before.

**What you expected to happen**:
It should work as with version 8.2
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
```
/usr/share/grafana $ cat /etc/grafana/provisioning/datasources/thanos-querier.yaml
apiVersion: 1
datasources:
- access: proxy
  basicAuth: true
  basicAuthPassword: ######
  basicAuthUser: internal
  isDefault: true
  jsonData:
    httpHeaderName1: Authorization
    httpMethod: POST
    timeInterval: 30s
    tlsSkipVerify: true
    tracesToLogs: {}
  name: Prometheus
  secureJsonData: {}
  type: prometheus
  url: https://thanos-querier.openshift-monitoring.svc:9091
```

**Environment**:
- Grafana version:  current is 8.2.7, I've tried every version from 8.3.0-beta1 to 8.4+
- Data source type & version: thanos-querier v0.17.2 (prometheus 2.23.0)
- OS Grafana is installed on: Openshift v4.7.30 with grafana-operator (https://github.com/grafana-operator/grafana-operator)
- User OS & Browser: Windows 10 & Chrome
- Grafana plugins: default
- Others: n/a
