### ISSUE TITLE
foldersFromFilesStructure provisioned dashboards have non-deterministic folder ids

### ISSUE THREAD

**Issue by clux** [grafana/grafana#46782]
**What happened**:
When running grafana as a HA `Statefulset`, provisioned configmaps with `foldersFromFilesStructure` enabled end up with different folder `uids` depending on which grafana pod you end up with.

**What you expected to happen**:
`foldersFromFilesStructure` should use a deterministic system for generatic uids based on the folder names.

**How to reproduce it (as minimally and precisely as possible)**:

enable `grafana-sc-dashboard` via the [official chart](https://github.com/grafana/helm-charts/blob/dc39d0eb823cd7ca239064b7a87823b5cd1643cf/charts/grafana/values.yaml#L622-L690):

```yaml
  sidecar:
    dashboards:
      resource: configmap
      folderAnnotation: grafana_folder
      provider:
        name: sidecarProvider
        foldersFromFilesStructure: true
```

and provision some dashboard with a folder:

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitoring
  name: grafana-dashboard-analytics-status-api
  labels:
    grafana_dashboard: "1"
    app.kubernetes.io/name: grafana
  annotations:
    grafana_folder: "./analytics"
data:
  status-api.json: ....
```

then browse to the `analytics` folder here (say) and you'll find the folder url two distinct folder urls:

- `$GRAFANA_BASE_URL/dashboards/f/bw-5XUE7z/analytics`
- `$GRAFANA_BASE_URL/dashboards/f/hhYtX8E7z/analytics`

depending on what pod you get routed to.

**Anything else we need to know?**:

**Environment**:
kubernetes, with official helm chart.

- Grafana version: 8.3 (EDIT: also happens on 8.4.2)
- OS Grafana is installed on: kubernetes 1.22 EKS
