### ISSUE TITLE
Previews: removing the `fixed:datasources:reader` fixed role assignment breaks authorization model of the crawler process

### ISSUE THREAD

**Issue by ArturWierzbicki** [grafana/grafana#46968]
To reproduce:

1. Create a dashboard using at least one non-grafana data source. 
2. Remove the `fixed:datasources:reader` fixed role assignment
   - Example provisioning file:
```
# config file version
apiVersion: 1

# list of default built-in role assignments that should be removed
removeDefaultAssignments:
  - builtInRole: "Admin"
    fixedRole: "fixed:datasources:reader"
```

3. Run the crawler 
4. Previews of dashboards with non-grafana data sources will be blank
