### ISSUE TITLE
Legacy alerts on provisioned dashboards reporting nodata

### ISSUE THREAD

**Issue by rzylim** [grafana/grafana#47605]
**What happened**:
I'm trying to set up a provisioned dashboard a legacy alert, via grafonnet.

The grafana instance successfully boots and loads the provisioned dashboard, and data retrieval is successful and the appropriate graphs are shown as exepcted.

![grafana_issue_alert_nodata_target](https://user-images.githubusercontent.com/19969292/162890596-3bcd1718-ea49-4189-9e33-5dd3b3c8f37b.png)

However, the no data annotation appeared shortly after, indicating that the alert was not successful in retrieving the data necessary for the processing of its rules.

Inspection of the panel shows that the alert is present, and it was possible to use the "Test Rule" function which returned the following result:

![grafana_issue_alert_nodata_alert](https://user-images.githubusercontent.com/19969292/162890672-e7f1c178-b06d-433a-a01b-4b6ca17f176a.png)

```
{
  "firing": false,
  "state": "ok",
  "conditionEvals": "false = false",
  "timeMs": "1.453ms",
  "logs": [
    {
      "message": "Condition[0]: Query",
      "data": {
        "from": 1649736909453,
        "queries": [
          {
            "refId": "A",
            "model": {
              "datasource": {
                "type": "postgres"
              },
              "format": "time_series",
              "group": [],
              "hide": false,
              "metricColumn": "CONCAT('upper')",
              "rawQuery": false,
              "rawSql": "SELECT\n  \"time\" AS \"time\",\n  CONCAT('upper') AS metric,\n  value\nFROM c_239\nWHERE\n  $__timeFilter(\"time\") AND\n  meta_id = 5\nORDER BY 1,2",
              "refId": "E",
              "select": [
                [
                  {
                    "params": [
                      "value"
                    ],
                    "type": "column"
                  }
                ]
              ],
              "table": "c_239",
              "timeColumn": "\"time\"",
              "timeColumnType": "timestamp",
              "where": [
                {
                  "name": "$__timeFilter",
                  "params": [],
                  "type": "macro"
                },
                {
                  "datatype": "int4",
                  "name": "",
                  "params": [
                    "meta_id",
                    "=",
                    5
                  ],
                  "type": "expression"
                }
              ]
            },
            "datasource": {
              "id": 1,
              "name": "iot-database"
            },
            "maxDataPoints": 0,
            "intervalMs": 0
          }
        ],
        "to": 1649737209453
      }
    },
    {
      "message": "Condition[0]: Query Result",
      "data": {
        "meta": {
          "executedQueryString": "SELECT\n  \"time\" AS \"time\",\n  CONCAT('upper') AS metric,\n  value\nFROM c_239\nWHERE\n  \"time\" BETWEEN '2022-04-12T04:15:09.453450624Z' AND '2022-04-12T04:20:09.453450624Z' AND\n  meta_id = 5\nORDER BY 1,2",
          "rowCount": 0
        },
        "series": [
          {
            "name": "upper",
            "points": [
              [
                4.29,
                1649736920460
              ],
              [
                5.59,
                1649737000889.9998
              ]
            ]
          }
        ]
      }
    },
    {
      "message": "Condition[0]: Eval: false, Metric: upper, Value: 4.940",
      "data": null
    }
  ]
}
```

Resulting JSON model for the alert:
```
"alert": {
  "alertRuleTags": { },
  "conditions": [
      {
        "evaluator": {
            "params": [
              20
            ],
            "type": "gt"
        },
        "operator": {
            "type": "and"
        },
        "query": {
            "params": [
              "E",
              "5m",
              "now"
            ]
        },
        "reducer": {
            "params": [ ],
            "type": "avg"
        },
        "type": "query"
      }
  ],
  "executionErrorState": "alerting",
  "for": "5m",
  "frequency": "60s",
  "handler": 1,
  "message": "Alert message",
  "name": "Panel 1 Alert",
  "noDataState": "nodata",
  "notifications": [
      {
        "uid": "xxxxx"
      }
  ]
}
```

Resulting JSON model for the target:
```
{
    "datasource": {
      "type": "postgres"
    },
    "format": "time_series",
    "group": [ ],
    "hide": false,
    "metricColumn": "CONCAT('upper')",
    "rawQuery": false,
    "refId": "E",
    "select": [
      [
          {
            "params": [
                "value"
            ],
            "type": "column"
          }
      ]
    ],
    "table": "c_239",
    "timeColumn": "time",
    "where": [
      {
          "name": "$__timeFilter",
          "params": [ ],
          "type": "macro"
      },
      {
          "datatype": "int4",
          "name": "",
          "params": [
            "meta_id",
            "=",
            5
          ],
          "type": "expression"
      }
    ]
}
```

Grafana alert configuration:
```
GF_ALERTING_ENABLED__FILE: 'true'
GF_UNIFIED_ALERTING_ENABLED__FILE: 'false'
```

**What you expected to happen**:
Provisioned legacy alerts should retrieve data and be evaluated successfully.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create datasource provisioning yaml file, according to https://grafana.com/docs/grafana/latest/datasources/postgres/ and https://grafana.com/docs/grafana/latest/administration/provisioning/.
```
apiVersion: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:
  # <string, required> name of the datasource. Required
  - name: iot-database
    # <string, required> datasource type. Required
    type: postgres
    url: url:5432
    database: database
    user: $USER
    secureJsonData:
      password: $PASSWORD
    # only fields common to all datasources are fields.
    # the rest should be stored as a json blob in the jsonData field.
    jsonData:
      sslmode: 'disable' # disable/require/verify-ca/verify-full
      # maxOpenConns: 0 # Grafana v5.4+
      # maxIdleConns: 2 # Grafana v5.4+
      # connMaxLifetime: 14400 # Grafana v5.4+
      postgresVersion: 1200 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: true
      timeInterval: 1m
    # <bool> mark as default datasource. Max one per org
    isDefault: true
    # <int> org id. will default to orgId 1 if not specified
    orgId: 1
    # <string> custom UID which can be used to reference this datasource in other parts of the configuration, if not specified will be generated automatically
    uid: uid
    version: 1
    # <bool> allow users to edit datasources from the UI.
    editable: false

```
2. Create dashboard provisioning yaml file, according to https://grafana.com/docs/grafana/latest/administration/provisioning/.
```
apiVersion: 1

providers:
  # <string> an unique provider name. Required
  - name: 'dashboards'
    # <int> Org id. Default to 1
    orgId: 1
    # <string> name of the dashboard folder.
    folder: ''
    # <string> folder UID. will be automatically generated if not specified
    folderUid: ''
    # <string> provider type. Default to 'file'
    type: file
    # <bool> disable dashboard deletion
    disableDeletion: false
    # <int> how often Grafana will scan for changed dashboards
    # updateIntervalSeconds: 10
    # <bool> allow updating provisioned dashboards from the UI
    allowUiUpdates: false
    options:
      # <string, required> path to dashboard files on disk. Required when using the 'file' type
      # path: /var/lib/grafana/dashboards
      path: /etc/grafana/provisioning/dashboards
      # <bool> use folder names from filesystem to create folders in Grafana
      foldersFromFilesStructure: true
```
3. Use Jsonnet and Grafonnet to generate a panel using legacy alerts.
```
dashboard.new(title='title').addPanels(
  [graphPanel.new(
    title='title'
  ).addAlert(
    panel.alert.name,
    executionErrorState=panel.alert.executionErrorState,
    forDuration=panel.alert.forDuration,
    frequency=panel.alert.frequency,
    handler=panel.alert.handler,
    message=panel.alert.message,
    noDataState=panel.alert.noDataState,
    alertRuleTags=panel.alert.alertRuleTags,
    notifications=panel.alert.notifications
  ).addConditions(
    [
      alertCondition.new(
        evaluatorParams=[20],
        evaluatorType='gt',
        operatorType='and',
        queryRefId='E',
        queryTimeEnd='now',
        queryTimeStart='5m',
        reducerParams=[],
        reducerType='avg',
      )
    ]
  ) + {
    targets+: [
      {
          datasource: {
            type: 'postgres',
          },
          format: 'time_series',
          group: [],
          hide: false,
          metricColumn: 'desc',
          rawQuery: false,
          refId: 'E',
          select: [
            [
              {
                type: 'column',
                params: [
                  'value',
                ],
              },
            ],
          ],
          table: 'c_239',
          timeColumn: 'time',
          where: [
            { name: '$__timeFilter', params: [], type: 'macro' },
            {
              type: 'expression',
              datatype: 'int4',
              name: '',
              params: [
                'meta_id',
                '=',
                5,
              ],
            },
          ],
        }
    ]
  }]
)
```
2. 

**Anything else we need to know?**:
No.

**Environment**:
- Grafana version: grafana/grafana:7.5.15 (from docker hub)
- Data source type & version: timescaledb 2.5.1-pg14 (from docker hub)
- OS Grafana is installed on: Alpine
- User OS & Browser: Windows 10/ Ubuntu 20.04, Chrome
- Grafana plugins: Nil
- Others: Grafonnet (3626fc4)
