### ISSUE TITLE
Cannot login with Azure AD, got Cannot remove last organization admin

### ISSUE THREAD

**Issue by jlandercy** [grafana/grafana#47687]
Might be a bug, might be a documentation update request.

**What happened**:

I want to allow Grafana to use Azure AD as primary authentication service with OAuth2 flow.
In order to acheive it I have read those documentations:
 - https://grafana.com/docs/grafana/latest/auth/azuread/#create-the-azure-ad-application
 - https://grafana.com/docs/grafana/latest/auth/azuread/#enable-azure-ad-oauth-in-grafana

I have created the necessary resources in Azure Active Directory.
I have created the adhoc configuration in the docker compose hosting Grafana:

```yaml
services:
  grafana:
    environment:
      - "GF_AUTH_AZUREAD_NAME=Azure AD"
      - "GF_AUTH_AZUREAD_ENABLED=true"
      - "GF_AUTH_AZUREAD_ALLOW_SIGN_UP=false"
      - "GF_AUTH_AZUREAD_SCOPES=openid email profile"
      - "GF_AUTH_AZUREAD_AUTH_URL=https://login.microsoftonline.com/secret/oauth2/v2.0/authorize"
      - "GF_AUTH_AZUREAD_TOKEN_URL=https://login.microsoftonline.com/secret/oauth2/v2.0/token"
      - "GF_AUTH_AZUREAD_ALLOWED_DOMAINS=example.com"
      - "GF_AUTH_AZUREAD_CLIENT_ID=secret"
      - "GF_AUTH_AZUREAD_CLIENT_SECRET=secret"
```

When I restart the service, the OAuth flow is present and works as expected at least at the MicroSoft AD side.
I do login and I am redirected to the Grafana callback, but then Grafana synchornization process fails without leaving enough information to understand why can be done to solve this issue.

On the Grafana Web Interface I got an error message saying:

```
Login failed: cannot remove last organization admin
```

Reading Grafana logs in debug mode:

```
logger=oauth t=2022-04-13T09:47:52.34+0000 lvl=info msg="state check" queryState=token cookieState=cookie
logger=oauth t=2022-04-13T09:47:52.52+0000 lvl=dbug msg="OAuthLogin Got token" token="unsupported value type"
logger=social t=2022-04-13T09:47:52.52+0000 lvl=dbug msg="AzureAD OAuth: extracted role" email=dummy@example.com role=Viewer
logger=social t=2022-04-13T09:47:52.52+0000 lvl=dbug msg="AzureAD OAuth: extracted groups" email=dummy@example.com groups="unsupported value type"
logger=oauth t=2022-04-13T09:47:52.52+0000 lvl=dbug msg="OAuthLogin got user info" userInfo="unsupported value type"
logger=oauth t=2022-04-13T09:47:52.52+0000 lvl=dbug msg="Building external user info from OAuth user info"
logger=api t=2022-04-13T09:47:52.52+0000 lvl=dbug msg="The user has a role assignment and organization membership is auto-assigned" role=Viewer orgId=1
logger=oauth t=2022-04-13T09:47:52.52+0000 lvl=dbug msg="Syncing Grafana user with corresponding OAuth profile"
logger=login.ext_user t=2022-04-13T09:47:52.55+0000 lvl=dbug msg="Updating user_auth info" user_id=1
logger=login.authinfo t=2022-04-13T09:47:52.58+0000 lvl=dbug msg="Updated user_auth" user_id=1 auth_module=oauth_azuread rows=1
logger=login.ext_user t=2022-04-13T09:47:52.59+0000 lvl=dbug msg="Syncing organization roles" id=1 extOrgRoles="unsupported value type"
logger=context t=2022-04-13T09:47:52.59+0000 lvl=eror msg="cannot remove last organization admin"
logger=context t=2022-04-13T09:47:52.6+0000 lvl=info msg="Request Completed" method=GET path=/login/azuread status=302 remote_addr=x.y.z.w time_ms=260 size=61 referer=https://login.microsoftonline.com/
```

When I loggin with classic auth, I do see that my user has the AzureAD badge and checking at the AD side I can confirm login succeeded to the MicroSoft AD perspective.

Reading a bit more on the internet it seems that when connecting through this mechanism Grafana will syncronize information it gets from the AD to manage Organizations, Users and Roles.

Eg.: Same issue with LDAP #2940.

I have tried to change the unique organization I have to someting meaninful in this context, I have tried
 - Tenant name: Example
 - AD name: Example
 - Email domain name: example.com 

I have restarted a fresh instance with a new database, the problem performs equally as per with an existing instance.

Nothing works! So it prevents us to connect Grafana to our AD. Very frustrating so far.
My problem is that there is not enough information to solve this issue and finalize debugging.

Perhaps this error is intended and then some documentation update would be great for the community.
Or it could be a real bug, and then extra developments are needed.
I cannot decide for now.

**What you expected to happen**:

I would expect the flow to finalize and get access to the Grafana instance as I do when I create a flow for GitHub or GitLab.
I can understand that there is extra mechanism when dealing with the AD.
I would expect more information from logs and documentation in order to solve this problem.

At the very end, if my analysis is correct I just need to understand how to rename my organization, but unfortunelty I do not have enough information.

**How to reproduce it (as minimally and precisely as possible)**:

Follow your documentation to create a connection with an AD instance and confirm there is a problem with Organization synchornization.

**Anything else we need to know?**:

I do extensively use Grafana for years and I think it is a great product which has a bright future ahead of it.
I'll be happy to solve this problem and leave to the community a better documentation to succeed in such a configuration.

**Environment**:
- Grafana version: 8.4.4
- Data source type & version: PostgreSQL 13
- OS Grafana is installed on: Ubuntu LTS 20.04
- User OS & Browser: Windows 10 & Firefox 99
- Grafana plugins: default
