### ISSUE TITLE
Datasource proxy headers broken since version 8.3

### ISSUE THREAD

**Issue by ThisIsQasim** [grafana/grafana#47734]
**What happened**:
HTTP Headers are not being passed to the datasource since version 8.3.0

**What you expected to happen**:
HTTP Headers to be passed to the datasource

**How to reproduce it (as minimally and precisely as possible)**:
Setup grafana 8.3.0 or higher behind a reverse proxy that injects some headers (or set dataproxy.send_user_header = true in config). Add a datasource and dump headers. Observe missing headers. Downgrade to 8.2.7 and headers appear again.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.0 =<
- Data source type & version: Prometheus 2.32.1
- OS Grafana is installed on: Docker
- User OS & Browser: macOS & Safari
- Grafana plugins: none

https://github.com/grafana/grafana/issues/47734#tasklist-block-efb3e408-f8db-4b00-bd97-4e26bb10a91d

**Comment by zuchka** [comment]
Thanks for creating this issue, @ThisIsQasim
Are you using a nginx? If so, how we handle headers changed in 8.3. Here is thread with the fix and the link to the changelog:

https://github.com/grafana/grafana/issues/45117#issuecomment-1033842787

**Comment by ThisIsQasim** [comment]
My setup is behind `ingress-nginx` so the host header is correctly set and everything in Grafana itself works as expected but the headers aren't being forwarded to the data source when grafana proxies to it.

**Comment by ThisIsQasim** [comment]
Your linked issue appears to be different. I haven't come across "origin not allowed" error and it's not related to 8.3.5 rather 8.3.0 and above.

**Comment by zuchka** [comment]
can you please provide more detailed steps for reproduction? Thank you!

**Comment by ThisIsQasim** [comment]
**How to reproduce it (less minimal and precise)**:
- Setup grafana 8.3.0 or higher behind a reverse proxy that injects some headers. Example for ingress-nginx
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  labels:
    app: grafana
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
    - hosts:
        - monitor.example.com
      secretName: grafana-tls
  rules:
    - host: monitor.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port: 
                  number: 3000
```
-  Alternatively you can set dataproxy.send_user_header = true in grafana config
```
# grafana.ini
[dataproxy]
logging = true
send_user_header = true
```
- Add a datasource e.g. prometheus and dump incoming headers from the datasource. You can add any ip with an http server running as a datasource and observe the headers with `tcpdump -i any -vvv -nnSS ip host <grafana_ip> and port <port specified in datasource>`
- Query the added datasource from grafana. You'll notice that the requests coming from grafana are missing headers that grafana itself is receiving
- Downgrade grafana to 8.2.7 and headers appear again.
