### ISSUE TITLE
[Bug] Security config is not affected by ENV variables in Docker container

### ISSUE THREAD

**Issue by satyrius** [grafana/grafana#4825]
Trying to run Grafana in Docker, but cannot configure security (admin name and password) with environment variables, its still *admin:admin*. The interesting fact is that disallowing users sing up works fine. Here is docker-compose.yml

```yaml
grafana:
  image: grafana/grafana:3.0.0-beta5
  container_name: grafana
  restart: always
  environment:
    GF_SECURITY_ADMIN_NAME: "root"
    GF_SECURITY_ADMIN_PASSWORD: "secret"
    GF_USERS_ALLOW_SIGN_UP: "false"
  ports:
    - "80:3000"
```

Versions:
```
Grafana version: 3.0.0-beta5, commit: v3.0-beta4+15-g2e8ed97, build date: 2016-04-15 16:13:06
```
