### ISSUE TITLE
Grafana on restarts or reloads move all dashboards to General folder

### ISSUE THREAD

**Issue by lovelinuxalot** [grafana/grafana#48569]
**Problem**:

Dashboards that are put in separate folders using provisioners, are moved to General folder when Grafana is restarted or Grafana API to reload dashboards is called.

I have some dashboards which are created with provisioning. My dashboards.yml config looks like this:
```
apiVersion: 1
providers:
- disableDeletion: false
  editable: false
  folder: OSS
  folderUid: 956   # <--- Tried with and without this parameter and no luck
  name: oss
  options:
    path: /var/lib/grafana/dashboards/oss
  orgId: 1
  type: file
      updateIntervalSeconds: 10
```

My Sidecar config for dashboards is this:

```
sidecar:
    dashboards:
        enabled: true
        label: grafana_dashboard
        annotations: {}
        folder: /var/lib/grafana/dashboards
        folderAnnotation: k8s-cms
        searchNamespace: ALL
        multicluster: false
```

I create dashboards from configMap, and I add the annotation to store the dashboard in the folder
```
apiVersion: v1
kind: ConfigMap
metadata:
    annotations:
        k8s-cms: /var/lib/grafana/dashboards/oss
    labels:
        grafana_dashboard: "1"
    name: oss-dummy-provisioner
    namespace: oss-dev
```

When I apply the configMap, I could see that the dashboard is being created inside the folder OSS in UI. I check the grafana.db entry and see a random folderUid has been provided and it was `768`. This value was same when I tested for both with/without `folderUid` parameter. 

The interesting stuff is when I restart Grafana or reload the Grafana dashboard configuration. In both cases the `folderUid` for the dashboards are changed to `0` and the dashboards are no longer `OSS` folder and they are under `General` folder.

If I manually create a folder and manually upload dashboards to this folder, then this is persisted after restarts.

**Expected Result**:

Dashboards should stay in their own folders, after restart or reload.

**How to reproduce it (as minimally and precisely as possible)**:

- Create Grafana dashboards using providers
- Ensure the dashboards are in proper folders in UI
- Restart or reload grafana
- Check UI, the dashboards will be in General folder

**Anything else we need to know?**:

- IF the folder is created manually through UI and the dashboards are uploaded to it via UI, they stay as it is even after restarts. Problem is only for dashboards that are created via provisioners
- This is issue is similar to #24369

**Environment**:

- Grafana Version: 8.3.1
- Running environment: AKS, deployed via Grafana Helm chart
