### ISSUE TITLE
InfluxDB provisioning problem

### ISSUE THREAD

**Issue by IgorKha** [grafana/grafana#49248]
**What happened**: faced the problem of provisioning grafana dashboards with influx2 datasource
the essence of the problem is that I make a dashboard in grafana, I specify influx data source, everything works. save-export with Export for sharing externally
then I throw the board and the datasource config into the grafana provisioning folder and run
everything starts, the datasource test passes, but nothing is displayed in the dashboard until I click the same datasource again in the panel settings....

if you try to export the dashboard right after the import, the file is saved with the name `undefined-1652961347524.json` and the content

```json
{
   error: {
     "message": "Datasource ${DS_INFLUXDB} was not found"
   }
}
```

```mc
[4.0K]  ./grafana
└── [4.0K]  provisioning
    ├── [4.0K]  dashboards
    │   ├── [ 25K]  CL-213-E.json
    │   └── [ 185]  dashboard.yml
    └── [4.0K]  datasources
        └── [ 393]  datasource.yml
3 directories, 3 files
```

### docker-compose file

```yml
........
  grafana:
    image: grafana/grafana:8.5.2
    container_name: mon_grafana
    restart: always
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    networks:
      - iot
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=123123123
      - GF_USERS_ALLOW_SIGN_UP=false
........
```
### datasource.yml

```yml
apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    orgId: 1
    url: http://mon_influxdb2:8086
    isDefault: true
    secureJsonData:
      token: *****token
    jsonData:
      version: Flux
      organization: org
      defaultBucket: bucket1
      tlsSkipVerify: true
```

### dashboard.yml

```yml
apiVersion: 1

providers:
- name: 'InfluxDB'
  orgId: 1
  folder: ''
  type: file
  disableDeletion: false
  editable: true
  options:
    path: /etc/grafana/provisioning/dashboards
```

### CL-213-E.json

```json
{
  "__inputs": [
    {
      "name": "DS_INFLUXDB",
      "label": "InfluxDB",
      "description": "",
      "type": "datasource",
      "pluginId": "influxdb",
      "pluginName": "InfluxDB"
    }
  ],
...........
```

![Peek 2022-05-19 14-40](https://user-images.githubusercontent.com/2268209/169316141-91dcebe2-c454-47f2-8bd1-bff0793ab618.gif)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**: Connect influx, create a dashboard with a query to this database, export the dashboard.
perform provisioning with file configuration as I did above

**Anything else we need to know?**: If you set up datasource and then import the dashboard manually, then everything works

**Environment**:
- Grafana version: tested 8.4.7 & 8.5.2
- Data source type & version: InfluxDB2 Flux
- OS Grafana is installed on: docker-compose
- User OS & Browser: Linux & Chrome 101.0.4951.64 (Official Build) (64-bit)
- Grafana plugins:
- Others:

**Comment by Vollbrecht** [comment]
in the datasource.yaml you need to set `httpMode: "POST`. It should look like this -> 


```
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    orgId: 1
    url: http://mon_influxdb2:8086
    isDefault: true
    secureJsonData:
      token: *****token
    jsonData:
      version: Flux
      httpMode: "POST"
      organization: org
      defaultBucket: bucket1
```
this was already discussed in the forums.
https://community.grafana.com/t/setting-http-method-for-a-provisioned-influx-data-type/34891

**Comment by IgorKha** [comment]
`httpMode: "POST"` unfortunately does not solve my problem

![Peek 2022-05-19 22-39](https://user-images.githubusercontent.com/2268209/169389727-b7e1aa43-b7fd-47b5-9877-6016e6c6bc8d.gif)

```log
mon_grafana    | logger=sqlstore t=2022-05-19T19:37:10.77+0000 lvl=info msg="Created default admin" user=admin
mon_grafana    | logger=sqlstore t=2022-05-19T19:37:10.77+0000 lvl=info msg="Created default organization"
mon_grafana    | logger=plugin.manager t=2022-05-19T19:37:10.85+0000 lvl=info msg="Plugin registered" pluginId=input
mon_grafana    | logger=query_data t=2022-05-19T19:37:10.85+0000 lvl=info msg="Query Service initialization"
mon_grafana    | logger=live.push_http t=2022-05-19T19:37:10.86+0000 lvl=info msg="Live Push Gateway initialization"
mon_grafana    | logger=provisioning.datasources t=2022-05-19T19:37:10.96+0000 lvl=info msg="inserting datasource from configuration " name=InfluxDB-nnz uid=P39F8580EFE73AB7B
mon_grafana    | logger=ngalert t=2022-05-19T19:37:10.98+0000 lvl=info msg="warming cache for startup"
mon_grafana    | logger=ngalert.multiorg.alertmanager t=2022-05-19T19:37:10.98+0000 lvl=info msg="starting MultiOrg Alertmanager"
mon_grafana    | logger=grafanaStorageLogger t=2022-05-19T19:37:10.98+0000 lvl=info msg="storage starting"
mon_grafana    | logger=http.server t=2022-05-19T19:37:10.98+0000 lvl=info msg="HTTP Server Listen" address=[::]:3000 protocol=http subUrl= socket=
mon_grafana    | logger=context traceID=00000000000000000000000000000000 t=2022-05-19T19:37:21.23+0000 lvl=eror msg="Failed to look up user based on cookie" error="user token not found"
mon_grafana    | logger=context traceID=00000000000000000000000000000000 userId=0 orgId=0 uname= t=2022-05-19T19:37:21.23+0000 lvl=info msg="Request Completed" method=GET path=/ status=302 remote_addr=192.168.48.1 time_ms=0 duration=693.086µs size=29 referer= traceID=00000000000000000000000000000000
mon_grafana    | logger=context traceID=00000000000000000000000000000000 t=2022-05-19T19:37:21.24+0000 lvl=eror msg="Failed to look up user based on cookie" error="user token not found"
mon_grafana    | logger=context traceID=00000000000000000000000000000000 t=2022-05-19T19:37:25.83+0000 lvl=eror msg="Failed to look up user based on cookie" error="user token not found"
mon_grafana    | logger=http.server t=2022-05-19T19:37:25.86+0000 lvl=info msg="Successful Login" User=admin@localhost
mon_grafana    | logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-05-19T19:37:26.27+0000 lvl=info msg="Request Completed" method=GET path=/api/live/ws status=0 remote_addr=192.168.48.1 time_ms=1 duration=1.076825ms size=0 referer= traceID=00000000000000000000000000000000
mon_grafana    | logger=live t=2022-05-19T19:37:40.12+0000 lvl=info msg="Initialized channel handler" channel=grafana/dashboard/uid/1sWR2ounz address=grafana/dashboard/uid/1sWR2ounz
mon_grafana    | logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-05-19T19:38:37.11+0000 lvl=eror msg="Dashboard not found" error="Dashboard not found" remote_addr=192.168.48.1 traceID=00000000000000000000000000000000
mon_grafana    | logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-05-19T19:38:37.11+0000 lvl=info msg="Request Completed" method=GET path=/api/dashboards/uid/1sWR2ounz1 status=404 remote_addr=192.168.48.1 time_ms=2 duration=2.533807ms size=78 referer=http://localhost:3000/dashboard/import traceID=00000000000000000000000000000000
mon_grafana    | logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-05-19T19:38:37.67+0000 lvl=eror msg="Dashboard not found" error="Dashboard not found" remote_addr=192.168.48.1 traceID=00000000000000000000000000000000
mon_grafana    | logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-05-19T19:38:37.67+0000 lvl=info msg="Request Completed" method=GET path=/api/dashboards/uid/1sWR2ounz13 status=404 remote_addr=192.168.48.1 time_ms=0 duration=774.644µs size=78 referer=http://localhost:3000/dashboard/import traceID=00000000000000000000000000000000
mon_grafana    | logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-05-19T19:38:41.59+0000 lvl=eror msg="Dashboard not found" error="Dashboard not found" remote_addr=192.168.48.1 traceID=00000000000000000000000000000000
mon_grafana    | logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-05-19T19:38:41.59+0000 lvl=info msg="Request Completed" method=GET path=/api/dashboards/uid/1sWR2ounz13 status=404 remote_addr=192.168.48.1 time_ms=0 duration=436.414µs size=78 referer=http://localhost:3000/dashboard/import traceID=00000000000000000000000000000000
mon_grafana    | logger=live t=2022-05-19T19:38:41.78+0000 lvl=info msg="Initialized channel handler" channel=grafana/dashboard/uid/1sWR2ounz13 address=grafana/dashboard/uid/1sWR2ounz13
^CGracefully stopping... (press Ctrl+C again to force)
```

**Comment by zuchka** [comment]
here is a docker compose template that works for me w provisioning:

https://github.com/zuchka/grafana-compose/tree/main/netsage-sankey-panel

**Comment by Vollbrecht** [comment]
> here is a docker compose template that works for me w provisioning:
> 
> https://github.com/zuchka/grafana-compose/tree/main/netsage-sankey-panel

hmm i am not sure that the provided example without a InfluxV2 will help him here, but thank you. 


@IgorKha  how did you initial created your dashboard(before provisioning)? I had a look at my setup and looked in particular into the json file of my dashboards. Two things i noted here:
1. My dashboards don't use an `__inputs:..` section, but rather specify an datasource per panel.
2. The `"uid: "some_uid""` is my datasource blocks inside the dasboards are not the Datasource name rather an alphanumerical combination. 

If you look in Configuration -> Data Sources and hover over the InfluxDB Source the browser shows you a link like `https://</your-server>/datasources/edit/<datasource_id>` . Can you ceck if that <datasource_id> is the same as in the uid blocks in your dashboard?

**Comment by IgorKha** [comment]
Yes indeed, @zuchka answer doesn't solve my problem at all
@Vollbrecht 
Initially, I created the dashboard in grafana, which also worked in docker, after deploying it on my server, the scheme is quite simple, I already used such provisioning only as a database was Prometheus
https://github.com/IgorKha/Grafana-Mikrotik
Regarding `__inputs` this section appears if we use external export as described here https://grafana.com/docs/grafana/latest/dashboards/export-import/#exporting-a-dashboard
`uid` does not match initially, because it is defined as a variable because of the external export. If you specify it explicitly in the form of uid datasource, then it works, but this behavior is not normal. For example, how can I transfer such a dashboard to another person, it will not work for him, because. `uid` will be from my db.
There is an idea to solve this problem for me personally, you can explicitly specify the `uid` when starting in a file

### datasource.yml

```yml
apiVersion: 1

datasources:
  - name: InfluxDB-nnz
    type: influxdb
    access: proxy
    orgId: 1
    uid: P39F8580EFE73AB7B
    url: http://mon_influxdb2:8086
......
```
and explicitly setting `uid` in the dashboard json

but again, this is abnormal behavior
