### ISSUE TITLE
Cannot use contact points created via API or during provisioning

### ISSUE THREAD

**Issue by bensoille** [grafana/grafana#50632]
**What happened**:

> **When trying to create full setup programmatically, I cannot make use of the created _contact points_, they show up ONLY in API responses. NOT in UI**

    

## 1. tried with _alert-notifications_ API endpoint 
  ```shell
curl -k -X POST -H "Authorization: Bearer xxx" \     
    -H "Content-type: application/json" \     
    -d '{"name": "test-via-api","type":"slack","is_default":true,"org_id":1,"settings":{"recipient":"#dest-channel","url":"https://slack.com/api/chat.postMessage","token":"xoxb-zzzzz","uploadImage":true},"secure_settings":{"url":"https://slack.com/api/chat.postMessage","token":"xoxb-zzzzz"}}' \
    http://localhost:3000/api/alert-notifications
  ```
 :arrow_right:  contact point gets created and shown in same endoint GET response, but _contact points_ list in UI did NOT change

## 2. tried with provisioning
Saved file to `/etc/grafana/provisioning/notifiers/slack.yaml` :
```yaml
apiVersion: 1

notifiers:
  - name: test-via-api
    type: slack
    org_id: 1
    is_default: true
    uid: notifier1
    settings:
      recipient: "#dest-channel"
      uploadImage: true
    secure_settings:
      token: "xoxb-zzzzz"
      url: "https://slack.com/api/chat.postMessage"
  - name: default-email
    type: email
    org_id: 1
    uid: notifier2
    is_default: false
    settings:
      addresses: example11111@example.com
delete_notifiers:
  - name: grafana-default-email
    org_id: 1
    uid: notifier1
```
Then restarted grafana service ; I could witness in grafana logs : 
```
logger=provisioning.notifiers t=2022-06-10T16:07:54.77+0000 lvl=dbug msg="Looking for alert notification provisioning files" path=/etc/grafana/provisioning/notifiers
logger=provisioning.notifiers t=2022-06-10T16:07:54.77+0000 lvl=dbug msg="Parsing alert notifications provisioning file" path=/etc/grafana/provisioning/notifiers file.Name=sample.yaml
logger=provisioning.notifiers t=2022-06-10T16:07:54.77+0000 lvl=dbug msg="Parsing alert notifications provisioning file" path=/etc/grafana/provisioning/notifiers file.Name=slack.yaml
logger=provisioning.notifiers t=2022-06-10T16:07:54.77+0000 lvl=dbug msg="Validating alert notifications"
logger=provisioning.notifiers t=2022-06-10T16:07:54.79+0000 lvl=info msg="Deleting alert notification" name=grafana-default-email uid=notifier1
logger=provisioning.notifiers t=2022-06-10T16:07:54.8+0000 lvl=dbug msg="inserting alert notification from configuration" name=test-via-api uid=notifier1
logger=provisioning.notifiers t=2022-06-10T16:07:54.84+0000 lvl=dbug msg="updating alert notification from configuration" name=default-email
```
 :arrow_right:  contact point gets created and shown in same endoint GET response, but _contact points_ list in UI did NOT change

## 3. tried with `/api/provisioning/contact-points` endpoint : 
:arrow_right: Error 404, seems NOT to be implemented in `8.5.5`

## In all cases : 
- I can list my created resources with GET request : 
```shell
curl -k -H "Authorization: Bearer xxxxx" http://localhost:3000/api/alert-notifications | jq
```
Which gives correct response : 
```json
[
  {
    "id": 4,
    "uid": "notifier2",
    "name": "default-email",
    "type": "email",
    "isDefault": false,
    "sendReminder": false,
    "disableResolveMessage": false,
    "frequency": "",
    "created": "2022-06-10T14:41:09Z",
    "updated": "2022-06-10T16:07:54Z",
    "settings": {
      "addresses": "example11111@example.com"
    },
    "secureFields": {}
  },
  {
    "id": 6,
    "uid": "notifier1",
    "name": "test-via-api",
    "type": "slack",
    "isDefault": true,
    "sendReminder": false,
    "disableResolveMessage": false,
    "frequency": "",
    "created": "2022-06-10T16:07:54Z",
    "updated": "2022-06-10T16:07:54Z",
    "settings": {
      "recipient": "#dest-channel",
      "uploadImage": true
    },
    "secureFields": {
      "token": true,
      "url": true
    }
  }
]
```

- However, these resources don't appear in grafana web UI

**What you expected to happen**:
I expected _contact points_ to show up in UI, and get used for alerting

**How to reproduce it (as minimally and precisely as possible)**:
Just do the same as described above.

**Anything else we need to know?**:
All remaining resources get correctly created and show up in grafana web UI : 
- folder
- dashboards
- alerts

**Environment**:
- Grafana version: 8.5.5
- Data source type & version: prometheus 2.28.1
- OS Grafana is installed on: Linux 5.13.0-1025-aws 20.04.1-Ubuntu
- User OS & Browser: Linux 5.14.0-1042-oem Ubuntu
- Grafana plugins: Alert list, Alertmanager, Annotations list, Azure Monitor, Bar chart, Bar gauge, Candlestick, CloudWatch, Dashboard list, Elasticsearch, Gauge, Geomap, Getting Started, Google Cloud Monitoring, Grafana Image Renderer, Graph (old), Graphite, Heatmap, Histogram, InfluxDB, Jaeger, Logs, Loki, Microsoft SQL Server, MySQL, News, Node Graph, OpenTSDB, Pie chart, Plugin list, PostgreSQL, Prometheus, Stat, State timeline, Status history, Table, Table (old), Tempo, TestData DB, Text, Time series, Welcome, Zipkin
- Others:
