### ISSUE TITLE
Grafana 9.0.0: Unexpected error while loading a Prometheus datasource in Explore view

### ISSUE THREAD

**Issue by dbluxo** [grafana/grafana#50870]
**What happened**: Updated from Grafana 8.5.1 to 9.0.0 (without changing any of the Grafana config)

When we open the Explore view for the datasource listed below, we see an "Unexpected error".

Grafana 9.0.0:

<img width="1626" alt="Bildschirmfoto 2022-06-15 um 13 18 32" src="https://user-images.githubusercontent.com/20679842/173817701-285ab312-1400-499d-9311-87c5a7dbf18b.png">
<img width="1124" alt="Bildschirmfoto 2022-06-15 um 13 17 18" src="https://user-images.githubusercontent.com/20679842/173817709-15332505-51f8-4814-9993-6950d1378c2d.png">

Grafana 8.5.1:

<img width="1622" alt="Bildschirmfoto 2022-06-15 um 13 25 43" src="https://user-images.githubusercontent.com/20679842/173817798-d8299ae7-37c6-4e3f-92b5-07e184603a38.png">
<img width="1107" alt="Bildschirmfoto 2022-06-15 um 13 31 21" src="https://user-images.githubusercontent.com/20679842/173817793-980cd707-5073-418f-9e5b-9ff70654bc43.png">

What I see as differences:

1. With Grafana 9.0 there is an unexpected error when opening the Explore view. 
2. The message "Labels and metrics lookup was disabled in data source settings." is not shown anymore.
3. Furthermore, I see that the `rules` and `query_examplars` requests end in a 401.
4. And 403s are logged continuously:

logger=live t=2022-06-15T11:35:06.776238617Z level=warn msg="Request Origin is not authorized" origin=https://grafana-observability-lab.<redacted-domain> host=grafana:80 appUrl=http://localhost:3000/ allowedOrigins=
logger=context traceID=00000000000000000000000000000000 userId=0 orgId=1 uname= t=2022-06-15T11:35:06.776303276Z level=info msg="Request Completed" method=GET path=/api/live/ws status=403 remote_addr=x.x.x.x time_ms=1 duration=1.502536ms size=10 referer= traceID=00000000000000000000000000000000

Datasource configuration:

```yaml
apiVersion: 1
datasources:
- orgId: 1
  version: 1
  name: Billing-observability-lab
  type: prometheus
  access: proxy
  url: https://amp-user-proxy.observability-lab.svc.cluster.local:8443
  jsonData:
    customQueryParameters: namespace=observability-lab
    disableMetricsLookup: true
    httpHeaderName1: Authorization
    httpMethod: GET
    manageAlerts: false
    tlsSkipVerify: false
  secureJsonData:
    httpHeaderValue1: $BILLING_OBSERVABILITY_LAB_HTTPHEADERVALUE_1
```

**What you expected to happen**: Opening the Explore view without errors. 

**Anything else we need to know?**: However, dashboards based on this datasource appear at first glance to be able to retrieve metrics and work.

**Environment**: 
- Grafana version: 9.0.0
- Data source type & version: Prometheus
- OS Grafana is installed on: Docker, Kubernetes
- User OS & Browser: Firefox, Safari, Chrome
