### ISSUE TITLE
Candlestick support with Flux

### ISSUE THREAD

**Issue by hasboeuf** [grafana/grafana#51081]
**What happened**:

I have this docker-compose
```
version: "3"
services:
  grafana:
    image: grafana/grafana:9.0.0
    container_name: grafana
    user: "${UID_GID}"
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana/var/lib/grafana:/var/lib/grafana
    environment:
      - GRAFANA_USERNAME=moni
      - GRAFANA_PASSWORD=moni
  influxdb:
    image: influxdb:2.2.0
    container_name: influxdb
    user: "${UID_GID}"
    restart: always
    ports:
      - 8086:8086
    volumes:
      - ./data/influxdb/persist:/var/lib/influxdb2
      - ./data/influxdb/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=user
      - DOCKER_INFLUXDB_INIT_PASSWORD=passsword
      - DOCKER_INFLUXDB_INIT_ORG=orga
      - DOCKER_INFLUXDB_INIT_BUCKET=chart
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=user-token
networks:
  default:
    name: test-network

```

I added the influx datasource successfully (using Flux language).

I added a candlestick chart and I use the following Flux query:

```
from(bucket: "chart")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "eth_ticker")
  |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
  |> group(columns: [])
  |> drop(columns:["_start", "_stop", "source", "_measurement"])
```

But `Data is missing a number field` is the error I get. Nevertheless the table view looks correct.

<img width="1718" alt="Capture d’écran 2022-06-20 à 00 18 23" src="https://user-images.githubusercontent.com/3967565/174502400-01de1015-891f-49fc-aef2-881719e25775.png">

**What you expected to happen**:

As my query returns columns open, high, low, close, I expect the Candlestick graph to work.

**How to reproduce it (as minimally and precisely as possible)**:

* Launch the docker compose attached
* Fill bucket with data
* Add datasource in Grafana
* Create a candlestick graph

**Anything else we need to know?**:

I would be glad if you need to know something.

Thank you for your time :)
