### ISSUE TITLE
Glue Correlations: DeleteCorrelation API endpoint

### ISSUE THREAD

**Issue by Elfo404** [grafana/grafana#51632]
As part of [#51323](https://github.com/grafana/grafana/issues/51323) we need an API to add correlations to existing datasources.

**Path**: `/datasources/uid/{uid}/correlations`
**Method**: `POST`
**Req. Body**:

```json
{
  "targetUid": "UID of the target datasource, required",
  "label": "arbitrary string, optional",
  "description": "arbitrary string, optional",
}
```` 

data should live in a new table `correlation`, for which we also to create the required db migration.

The endpoint should return the following errors (omitting auth-related errors for brevity):

| Code | Description |
|------|-------|
| 200 | Correlation created successfully. The newly created correlation is returned in the response. |
| 400 | Bad or incomplete data in the request body (ie. missing `targetUid` |
| 401 | Use does not have the required permission to edit the source datasource |
| 403 | Source datasource is read-only (identified by the `uid` param in path |
| 404 | either source DS (identified by `uid` in path) or target DS (identified by `targetUid` in req.body could not be found (or they belong to a different org.) |

When a correlation is successfully created, the following response should be returned:
```json
{
  "result": {
    "targetUid": "XXX", // UID of the target DS, required
    "label": "string", // optional, if provided in the req. body
    "description": "string", // optional, if provided in the req. body
    "uid": "string" // uid of the newly created correlation
  }
}
```

Provisioning should also work by having the same structure in datasources, and should support env interpolations (same as datasources) ie:
```yaml
  - name: gdev-loki
    type: loki
    access: proxy
    url: http://localhost:3100
    correlations:
      - targetUid: gdev-jaeger
        label: "Jaeger traces"
        description: "Related traces stored in Jaeger"
      - targetUid: gdev-zipkin
        label: "Zipkin traces"
        description: "Related traces stored in Zipkin"
```
