### ISSUE TITLE
Panel not hiding a datasource

### ISSUE THREAD

**Issue by raphaelquati** [grafana/grafana#51772]
**What happened**:
I have a panel, showing some Azure Storage metrics. But one data source is a math expression, to compute a % value of another data source (disabled)

In v8.5.4, it was working fine.
After an upgrade to v9.0.2, it stops working.
I've tried to recreate the panel, with no success.

**What you expected to happen**:
Hide data source 

**How to reproduce it (as minimally and precisely as possible)**:
Datasource: Azure Monitor
Add a metric. Click on "eye" (to hide/disable)
Add an expression 
Graph type: Gauge

![image](https://user-images.githubusercontent.com/815086/177457020-968a5c44-f8b0-493f-900b-62377b001bde.png)

**Environment**:
- Grafana version: v9.0.2 (0641b5d0cd)
- Data source type & version: Azure Monitor
- OS Grafana is installed on: Docker (k8s)
- User OS & Browser: Windows 11 -  Edge 103.0.1264.44 / FireFox 102.0
- Grafana plugins: Azure Monitor
- Others:

**Comment by joshhunt** [comment]
I'm not able to reproduce this using either the TestDB Datasource, or Azure Monitor. Are you able to supply the Panel JSON (Query Inspector > JSON > Panel JSON) to help reproduce. Be mindful to redact any sensitive information in the JSON.

Does this setup look similar to what causes the issue for you? https://play.grafana.org/d/l8cuf567z/51772-hiding-query-with-expressions?orgId=1&editPanel=2

**Comment by raphaelquati** [comment]
I've created a new dashboard. Same behavior:
You can notice (screen recorder) that with the presence of an expression data source, Azure Monitor keeps showing.
But after removing the expression, it works (hide)

Other data sources (like Cortex) are working like expected.

![GraphanaAzureMonitor](https://user-images.githubusercontent.com/815086/177686557-ff24d4b4-1ae1-4ce6-8cea-99a040ab5278.gif)


```
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "grafana-azure-monitor-datasource",
        "uid": "yqkdIL87k"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "orientation": "auto",
        "reduceOptions": {
          "calcs": [
            "lastNotNull"
          ],
          "fields": "",
          "values": false
        },
        "showThresholdLabels": false,
        "showThresholdMarkers": true
      },
      "pluginVersion": "9.0.2",
      "targets": [
        {
          "azureMonitor": {
            "aggregation": "Average",
            "allowedTimeGrainsMs": [
              3600000
            ],
            "dimensionFilters": [],
            "metricName": "FileShareCapacityQuota",
            "metricNamespace": "Microsoft.Storage/storageAccounts/fileServices",
            "resourceUri": "/subscriptions/{subscription}/resourceGroups/{resourceGroup}/providers/Microsoft.Storage/storageAccounts/{storageAccount}/fileServices/default",
            "timeGrain": "auto"
          },
          "datasource": {
            "type": "grafana-azure-monitor-datasource",
            "uid": "yqkdIL87k"
          },
          "hide": true,
          "queryType": "Azure Monitor",
          "refId": "A"
        },
        {
          "azureMonitor": {
            "aggregation": "Average",
            "allowedTimeGrainsMs": [
              3600000
            ],
            "dimensionFilters": [],
            "metricName": "FileCapacity",
            "metricNamespace": "Microsoft.Storage/storageAccounts/fileServices",
            "resourceUri": "/subscriptions/{subscription}/resourceGroups/{resourceGroup}/providers/Microsoft.Storage/storageAccounts/{storageAccount}/fileServices/default",
            "timeGrain": "auto"
          },
          "datasource": {
            "type": "grafana-azure-monitor-datasource",
            "uid": "yqkdIL87k"
          },
          "hide": true,
          "queryType": "Azure Monitor",
          "refId": "B"
        },
        {
          "datasource": {
            "name": "Expression",
            "type": "__expr__",
            "uid": "__expr__"
          },
          "expression": "$A / $B",
          "hide": false,
          "refId": "C",
          "type": "math"
        }
      ],
      "title": "Panel Title",
      "type": "gauge"
    }
  ],
  "refresh": "",
  "schemaVersion": 36,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "New dashboard",
  "version": 0,
  "weekStart": ""
}
```

**Comment by andresmgot** [comment]
hi @raphaelquati,

I am not sure what's going on but I am not able to reproduce it using your panel JSON and Grafana 9.0.2:

![Peek 2022-07-08 12-32](https://user-images.githubusercontent.com/4025665/177976123-3a8bdabf-fb6b-4d39-9a73-525ff943136f.gif)

If you open the query inspector, can you see if there is data for the hidden query? For example, here I am hiding the data for `A` so there are results for `B` and `C`:

![Screenshot from 2022-07-08 12-36-15](https://user-images.githubusercontent.com/4025665/177976932-ec9317d0-5c61-49d1-b549-69ea44debdc4.png)

**Comment by raphaelquati** [comment]
Investiganting a little......
After click on hide button, with the browser inspector opened, I realized, at query request, in azure monitor datasource, the "hide" attribute is missing. 

![image](https://user-images.githubusercontent.com/815086/178065887-f958d0f2-cb41-4288-88b6-7590fccf19ee.png)

On the response, the data ource is still present 
![image](https://user-images.githubusercontent.com/815086/178066064-2267b1b6-4065-4abb-9fef-73520ea0599b.png)

**Comment by raphaelquati** [comment]
And checking again the Panel Json Model.  The hide attribute is present

![image](https://user-images.githubusercontent.com/815086/178066619-644635e6-ddb1-4484-94de-54f6aaa4b017.png)

**Comment by raphaelquati** [comment]
Hi @aangelisc, Yes, I still have this issue.
Yes, the data is displayed in query Inspector:

![image](https://user-images.githubusercontent.com/815086/179012062-2b0213bf-ad8b-4503-9fc5-1b584e720eb9.png)

I don't know if it is related, but I'll create a new instance of Grafana 9.0.2, and I'll repeat the test.

Maybe It's related to migration ( v8.5.4 -> v9.0.2 ) (upgrade via Helm upgrade).

**Comment by aangelisc** [comment]
Hi @raphaelquati, that's great! Please let me know the outcome of that test 😊

**Comment by yaelleC** [comment]
Hello @raphaelquati did you get any luck by creating the panel from scratch in v9.0.2 (that would suggest the migration is the issue here)?

**Comment by JustinTArthur** [comment]
I am able to reproduce this with CloudWatch data source in v9.0.5:
1. Create a metric search query using query builder, assign it a query `Id` like "m1".
2. Create a metric search query using code view, give it the expression `RATE(m1)`.
3. Disable the first query using the eye icon.

The first query successfully gets `"hide": true` in the data model, but remains visible in both editing preview and the final viewed dashboard.

**Comment by andresmgot** [comment]
I am able to reproduce this as @JustinTArthur mentions for Grafana 9.0.5 only for Cloudwatch, but it seems to be fixed in 9.1.x (not reproducible there). @grafana/aws-plugins moving this to your board, proceed as you see fit!

**Comment by fridgepoet** [comment]
This was fixed in Grafana 9.0.6
https://github.com/grafana/grafana/issues/52360

**Comment by raphaelquati** [comment]
@fridgepoet, Please, can you reopen?

My problem is related to Azure Monitor only.

I've tested locally (k8s) with Graphana version 9.0.5.
In my test, I tried to replicate our case: Graphana is deployed using Terraform, with MySQL backend (via Helm)
I've tested the same result with MySQL and without MySQL (SQLite).
It doesn't work.

Grafana Helm values used:
```
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/large_client_header_buffers: "4 16k"
    nginx.ingress.kubernetes.io/proxy-body-size: 30m
  path: /
  hosts:
    - grafana.<IP>.nip.io


headlessService: false

autoscaling:
  enabled: false

nodeSelector:
  kubernetes.io/os: linux

deploymentStrategy:
  type: RollingUpdate

persistence:
  enabled: true

imageRenderer:
  enabled: true
  nodeSelector:
    kubernetes.io/os: linux

grafana.ini:
  smtp:
    enabled: true
    host: smtp.sendgrid.net:587
    user: apikey
    password: "<pass>"
    from_address: infra@<domain>
    from_name: Infra
  paths:
    data: /var/lib/grafana/data
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  analytics:
    check_for_updates: true
  log:
    mode: console
    level: debug
  grafana_net:
    url: https://grafana.net
  rendering:
    server_url: http://grafana-image-renderer:8081
  imageRenderer:
    enabled: true
    env:
      ENABLE_METRICS: 'true'
  unified_alerting:
    enabled: true
    execute_alerts: true
  alerting:
    enabled: false
  plugins:
    enable_alpha: true
  feature_toggles:
    enable: tempoSearch
```
