### ISSUE TITLE
Mkdir: can’t create directory ‘/var/lib/grafana/plugins’: Permission denied

### ISSUE THREAD

**Issue by coding-to-music** [grafana/grafana#51931]
I am attempting this tutorial: https://github.com/questdb/questdb-slack-grafana-alerts 

My repo is here: https://github.com/coding-to-music/questdb-slack-grafana-alerts

Community forum post: https://community.grafana.com/t/mkdir-cant-create-directory-var-lib-grafana-plugins-permission-denied/68342

When I run `docker-compose up` I get these messages:

## Errors and Messages

```
Attaching to grafana_alerts, questdb_alerts
grafana_alerts | mkdir: can't create directory '/var/lib/grafana/plugins': Permission denied
grafana_alerts | GF_PATHS_DATA='/var/lib/grafana' is not writable.
grafana_alerts | You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migrate-to-v51-or-later
```

## Steps attempted to fix

When I run this

```
id -u
1000
```

I see that I am user 1000, so I tried that in addition to user 472

Per the recommendation of this page: http://docs.grafana.org/installation/docker/#migrate-to-v51-or-later

I have added this line to the docker-compose.yml 

```
user: "472"
```

I have attempted to remove the directory /var/lib/grafana and also change it's ownership

I have tried changing the target directory ownership

and run `docker-compose up` as that user specified in the grafana-->user string 

```
sudo chown 472:472 /var/lib/grafana 
sudo chown 472:472 /var/lib/grafana/plugins 

sudo chown 1000:1000 /var/lib/grafana 
sudo chown 1000:1000 /var/lib/grafana/plugins 
```

## Similar problem reports:

https://community.grafana.com/t/gf-paths-data-var-lib-grafana-is-not-writable/31369

https://github.com/cfbarbero/tick-grafana-docker/issues/1

Any assistance is appreciated

**Comment by coding-to-music** [comment]
## docker-compose.yml
```
version: "3"

services:
  questdb:
    image: questdb/questdb
    container_name: questdb_alerts
    restart: always
    ports:
      - "8812:8812"
      - "9000:9000"
    networks:
      - "questdb"
    volumes:
      - ./data/db:/root/.questdb/db

  grafana:
    image: grafana/grafana
    container_name: grafana_alerts
    restart: always
    ports:
      - 3000:3000
    networks:
      - questdb
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./data/grafana:/var/lib/grafana/
    user: "472"

networks:
  questdb:
```

**Comment by usmangt** [comment]
Hi @coding-to-music 

Thanks for providing the details.

I was also able to reproduce this case based on the links you provide.

I found out a similar issue reported at ;

https://community.grafana.com/t/new-docker-install-with-persistent-storage-permission-problem/10896/

There are some suggestions to tackle this issue. So for e.g. I added this line when defining the grafana server i.e.

    user: "$UID:$GID"

and then it seems to not give this permission denied error.

Please check as I think, you will find a solution as well.

**Comment by grafanabot** [comment]
Please ask your question on [community.grafana.com/](https://community.grafana.com/). To avoid having your issue closed in the future, please read our [CONTRIBUTING](https://github.com/grafana/grafana/blob/main/CONTRIBUTING.md) guidelines.

Happy graphing!

**Comment by coding-to-music** [comment]
Thousands of unanswered questions on the Community forums, including mine, from 6 days ago, I tried adding content to bring it up and see if people could respond but nobody replied 

Community forum post: https://community.grafana.com/t/mkdir-cant-create-directory-var-lib-grafana-plugins-permission-denied/68342

**Comment by braindotai** [comment]
Same issue here, found no solution

**Comment by miege2k** [comment]
I have the same issue. Go to the Doc https://grafana.com/docs/grafana/latest/setup-grafana/configure-docker/#run-grafana-container-with-persistent-storage-recommended and try to you "Run Grafana container using bind mounts" and you will see the issue.

**Comment by usmangt** [comment]
Hi @miege2k,

> I have the same issue. Go to the Doc https://grafana.com/docs/grafana/latest/setup-grafana/configure-docker/#run-grafana-container-with-persistent-storage-recommended and try to you "Run Grafana container using bind mounts" and you will see the issue.

Please check the community forum link https://community.grafana.com/t/mkdir-cant-create-directory-var-lib-grafana-plugins-permission-denied/68342

as it provides the solution as how to resolve i.t

I will again close this GitHub issue.

**Comment by BuongiornoTexas** [comment]
I've run into the same or a related issue with grafana. See https://github.com/jasonacox/Powerwall-Dashboard/issues/22#issuecomment-1253076441 for a step by step approach to setting up file permissions on the **host** system so that the grafana container can write without problems. 

Posting here, as this was one of the issues that gave me a good pointer to a workaround, and because I haven't seen much other documentation on rootless docker solutions for this problem.

**Comment by TimChaubet-I4U** [comment]
How is this a closed issue, while this is still occuring on various docker-ce environments?
Running the container as root, as a workaround (as suggested in every topic) is a massive security flaw, imho.

**Comment by jjscaria** [comment]
I resolved this issue by adding an init container to change the permission:

```
services:
  init_grafana:
    image: grafana/grafana:latest
    user: root
    entrypoint:
      - /bin/sh
      - -c
      - |
        chown -R 65534:65534 /var/lib/grafana
    volumes:
      - /data/grafana:/var/lib/grafana
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    networks:
      - default
    ports:
      - "3000:3000"
    user: "65534"
    volumes:
      - /data/grafana:/var/lib/grafana
    depends_on:
      - init_grafana
```
