### ISSUE TITLE
Elasticsearch provisioned authentication failed

### ISSUE THREAD

**Issue by jasperjonker** [grafana/grafana#52158]
**What happened**:
When I provision the elasticsearch datasource using basic authentication, I get:
`Elasticsearch error: Authentication to data source failed`

My provision datasources.yaml:
```yaml
.
.
- name: Elasticsearch
    type: elasticsearch
    access: proxy
    isDefault: false
    basicAuth: true
    basicAuthUser: "username"
    basicAuthPassword: "password"
    database: ""
    url: https://elastic.example.com
    jsonData:
      esVersion: "8.0.0"
      includeFrozen: false
      timeField: "@timestamp"
      logMessageField: "message"
      logLevelField: "fields.level"
      maxConcurrentShardRequests: 5
      xpack: true
    readOnly: false
```
However, when I create the datasource inside grafana using exactly the same parameters (not provisioning), it connects fine.
Similarly, if I use the basic authorization header it works fine as well.:

```yaml
.
.
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    isDefault: false
    basicAuth: false
    database: ""
    url: https://elastic.example:443
    jsonData:
      esVersion: "8.0.0"
      includeFrozen: false
      logLevelField: "fields.level"
      logMessageField: "message"
      maxConcurrentShardRequests: 5
      timeField: "@timestamp"
      xpack: true
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'Basic base64_endocded_username:password'
```

**What you expected to happen**:
That I can provision the elasticsearch database using basic-auth without any authentication error

**How to reproduce it (as minimally and precisely as possible)**:
Use as provisioning `datasource.yaml`:
```yaml
apiVersion: 1
datasources:
- name: Elasticsearch
    type: elasticsearch
    access: proxy
    isDefault: false
    basicAuth: true
    basicAuthUser: "username"
    basicAuthPassword: "password"
    database: ""
    url: https://elastic.example.com
    jsonData:
      esVersion: "8.0.0"
      includeFrozen: false
      timeField: "@timestamp"
      logMessageField: "message"
      logLevelField: "fields.level"
      maxConcurrentShardRequests: 5
      xpack: true
    readOnly: false
```
**Anything else we need to know?**:

**Environment**: kubernetes
- Grafana version: v9.0.2
- Data source type & version: Elasticsearch from the bitnami chart, version 19.0.1 (based on Elasticsearch image version 8.3.2)
- OS Grafana is installed on: GKE (Google kubernetes) - Container-Optimized OS from Google, using official docker image `grafana/grafana:9.0.2`
- User OS & Browser: Fedora Linux & Firefox
- Grafana plugins: grafana-clock-panel, grafana-googlesheets-datasource, marcusolsson-csv-datasource, andig-darksky-datasource, grafana-github-datasource, doitintl-bigquery-datasource, yesoreyeram-infinity-datasource, frser-sqlite-datasource, doitintl-bigquery-datasource  grafana-piechart-panel  cloudflare-app
- Others:
