### ISSUE TITLE
Alertmanager Datasource: fails health check

### ISSUE THREAD

**Issue by driprado** [grafana/grafana#52506]
**What happened**:
Alertmanager Datasource Health check failed.

**What you expected to happen**:
Alertmanager is available to grafana as a datasource.

![Kapture 2022-07-20 at 16 22 13](https://user-images.githubusercontent.com/9782265/179911437-b8edd5d1-ffc6-4655-8709-9f2e77e9e40e.gif)

**How to reproduce it (as minimally and precisely as possible)**:
docker-compose:
```
version: '3.2'
services:
  alertmanager:
    image: prom/alertmanager:${ALERTMANAGER_TAG}
    ports:
    - 9093:9093
    command:
    - --config.file=/etc/alertmanager/alertmanager.yml
    - --storage.path=/alertmanager
    volumes:
    - ./alertmanager:/etc/alertmanager
    deploy:
      mode: global
    restart: always
  prometheus:
    image: prom/prometheus:${PROMETHEUS_TAG}
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus:/etc/prometheus
  grafana:
    depends_on: [prometheus]
    ports:
      - "3000:3000"
    image: grafana/grafana:8.3.0
    volumes:
      - ./grafana:/etc/grafana:rw
      
```

grafana.ini file:
```
app_mode = development

[auth.anonymous]
enabled = true
org_role = Editor

[log]
level = debug

[plugins]
enable_alpha = true

[feature_toggles]
enable = ngalert

```

grafana/provisioning/datasources/datasource.yml file:
```
apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: direct
  orgId: 1
  url: http://localhost:9090
  password:
  user:
  database:
  basicAuth: false
  basicAuthUser:
  basicAuthPassword:
  withCredentials:
  isDefault: true
  jsonData:
     graphiteVersion: "1.1"
     tlsAuth: false
     tlsAuthWithCACert: false
  secureJsonData:
    tlsCACert: "..."
    tlsClientCert: "..."
    tlsClientKey: "..."
  version: 1
  editable: true

- name: Alertmanager
  type: alertmanager
  access: direct
  url: http://localhost:9093
  jsonData:
  basicAuth: false
  basicAuthUser:
  basicAuthPassword:
```

**Environment**:
- Grafana version: grafana:8.3.0
- Data source type & version: Alertmanager v0.15.3
- OS Grafana is installed on:
- User OS & Browser: MacOs Monterey Version 12.3
- Grafana plugins: enable_alpha = true
- Others: No errors can be seing in debug logs.

**Comment by ashharrison90** [comment]
hi @driprado 👋 

are you able to check with later versions of grafana/alertmanager? 

i've just tried with grafana 9 + alertmanager 0.24.0 and everything is working as expected 🤔

**Comment by june-tyro** [comment]
Hi @ashharrison90 , I’ve been working with Adria on this issue, and we could resolve it through the following steps:

1. Create a separate user-defined bridge network _dockernet_ by running this command:
    `docker network create -d bridge dockernet`

2. Attach all the services to _dockernet_ by configuring _networks_ in `docker-compose.yaml` as below, and also newer version of Alertmanager should be used here:
    ```
    version: "3.8"
    services:
      alertmanager:
        image: prom/alertmanager:v0.23.0
        ports:
          - 9093:9093
        command:
          - '--config.file=/etc/alertmanager/alertmanager.yml'
          - '--storage.path=/alertmanager'
        volumes:
          - ./alertmanager:/etc/alertmanager
        deploy:
          mode: global
        restart: always
        networks:
          - dockernet 
      prometheus:
        image: prom/prometheus:v2.32.1
        ports:
          - "9090:9090"
        command:
          - '--config.file=/etc/prometheus/prometheus.yml'
        volumes:
          - ./prometheus:/etc/prometheus
        networks:
          - dockernet
      grafana:
          depends_on: [prometheus]
          ports:
            - "3000:3000"
          image: grafana/grafana:8.3.0
          volumes:
            - ./grafana:/etc/grafana
          networks:
          - dockernet
    networks:
      dockernet:
        external: true
    ```

3. Modify datasource configs in `grafana/provisioning/datasources/datasource.yml` with:
• changing `access` config from _direct_ to _proxy_
• using _service name_ instead of _localhost_ in `url` 
• specifying the `implementation` of Alertmanager as _prometheus_ 

    ```
    apiVersion: 1
    
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus:9090
      password:
      user:
      database:
      basicAuth: false
      basicAuthUser:
      basicAuthPassword:
      withCredentials:
      isDefault: true
      jsonData:
         graphiteVersion: "1.1"
         tlsAuth: false
         tlsAuthWithCACert: false
      secureJsonData:
        tlsCACert: "..."
        tlsClientCert: "..."
        tlsClientKey: "..."
      version: 1
      editable: true
    
    - name: Alertmanager
      type: alertmanager
      access: proxy
      url: http://alertmanager:9093
      jsonData:
        implementation: 'prometheus'
      basicAuth: false
      basicAuthUser: 
      basicAuthPassword: 
    ```
This approach not only resolves the _**health check fail**_ issue, but also prevents _**bad gateway**_ errors you might encounter when fetching prometheus or alertmanager from both grafana alerting and dashboard UI.

Hope this can be help for anyone who might run into similar issues, thank you :slightly_smiling_face:
