### ISSUE TITLE
auth.proxy does not work with oauth2_proxy

### ISSUE THREAD

**Issue by marian-gheorghe** [grafana/grafana#52681]
**What happened**:
I am trying to set up the following configuration locally
`[nginx] <-> [oauth2_proxy] <-> [grafana]`

* `nginx` listens on `80`
* `oauth2_proxy` listens on `4180`
* `grafana` listens on `3000`

Although successfully authenticating through the proxy (from proxy and identity provider perspective - here google) the authenticated user is not carried over to grafana, instead is redirected to the login screen.

While we could use the `auth.generic_oauth` for authenticating users through third party `OAuth2` provider (see [here](https://github.com/grafana/grafana/issues/52669)), the reason I have chosen this approach is to enable multiple applications to be configured with the common authentication backend.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

```
# docker-compose.yml
version: '3'
services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: always
    user: '104'
    volumes:
      - $PWD/data/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
        # [server]
      - GF_SERVER_PROTOCOL=http
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_ROOT_URL=http://localhost:80/
      
        # [users]
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_AUTO_ASSIGN_ORG=true
      - GF_USERS_AUTO_ASSIGN_ORG_ROLE=Admin

      
      # [auth.basic]
      - GF_AUTH_BASIC_ENABLED=false
      
      # [auth]
      - GF_AUTH_DISABLE_LOGIN_FORM=true

      # [auth.proxy]
      - GF_AUTH_PROXY_ENABLED=true
      - GF_AUTH_PROXY_HEADER_NAME=X-Forwarded-Email 
      - GF_AUTH_PROXY_HEADER_PROPERTY=email 
      - GF_AUTH_PROXY_HEADERS=Name:X-Forwarded-Email Email:X-Forwarded-Email
      - GF_AUTH_PROXY_AUTO_SIGN_UP=true
      - GF_AUTH_PROXY_ENABLE_LOGIN_TOKEN=false

  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    restart: always
    ports:
      - 4180:4180
    volumes:
      - $PWD/data/oauth2:/var/lib/oauth2_proxy
    environment:
      - OAUTH2_PROXY_PROVIDER=oidc
      - OAUTH2_PROXY_CLIENT_ID=<google_client_id>
      - OAUTH2_PROXY_CLIENT_SECRET=<google_client_secret>
      - OAUTH2_PROXY_OIDC_ISSUER_URL=https://accounts.google.com
      - OAUTH2_PROXY_COOKIE_SECRET=abcdefgh
      - OAUTH2_PROXY_COOKIE_DOMAIN=http://localhost:80
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_COOKIE_SECURE=false
      - OAUTH2_PROXY_UPSTREAMS=http://localhost:80
      - OAUTH2_PROXY_HTTP_ADDRESS=http://:4180
      - OAUTH2_PROXY_REDIRECT_URL=http://localhost:80/oauth2/callback
      - OAUTH2_PROXY_SET_XAUTHREQUEST=true
      
      - OAUTH2_PROXY_ERRORS_TO_INFO_LOG=true
      - OAUTH2_PROXY_AUTH_LOGGING=true
      - OAUTH2_PROXY_SHOW_DEBUG_ON_ERROR=true
      - OAUTH2_PROXY_SET_AUTHORIZATION_HEADER=true
      - OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER=true    
      - OAUTH2_PROXY_PASS_USER_HEADERS=true
      - OAUTH2_PROXY_PASS_HOST_HEADER=true
      - OAUTH2_PROXY_REVERSE_PROXY=true
      
      - OAUTH2_PROXY_PREFER_EMAIL_TO_USER=true
            
      - OAUTH2_PROXY_SSL_UPSTREAM_INSECURE_SKIP_VERIFY=true
      - OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY=true
  
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - $PWD/data/nginx/:/etc/nginx/conf.d/
```

```
# nginx.conf
server {
  listen 80;
  server_name localhost;

  location /oauth2/ {
    proxy_pass       http://oauth2-proxy:4180;
    proxy_set_header Host                    $host;
    proxy_set_header X-Real-IP               $remote_addr;
    proxy_set_header X-Scheme                $scheme;
    proxy_set_header X-Auth-Request-Redirect $request_uri;
  }
  location = /oauth2/auth {
    proxy_pass       http://oauth2-proxy:4180;
    proxy_set_header Host             $host;
    proxy_set_header X-Real-IP        $remote_addr;
    proxy_set_header X-Scheme         $scheme;
    proxy_set_header Content-Length   "";
    proxy_pass_request_body           off;
  }

  location / {
    auth_request /oauth2/auth;
    error_page 401 = /oauth2/sign_in;

    auth_request_set $user   $upstream_http_x_auth_request_user;
    auth_request_set $email  $upstream_http_x_auth_request_email;
    proxy_set_header X-User  $user;
    proxy_set_header X-Email $email;
    
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Server $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    
    auth_request_set $auth_cookie $upstream_http_set_cookie;
    add_header Set-Cookie $auth_cookie;

    proxy_pass http://grafana:3000;
  }
}
```

Run
`docker-compose up -d --build`

Then in browser navigate to `http://localhost/`=> User redirected to `oauth2_proxy` => google login succesful => back to `grafana` login screen.

It just so seems that I am missing some settings for carrying over the auth headers or something. Could anyone point me in the right direction?

There was a similar issue opened a while ago [here
](https://github.com/grafana/grafana/issues/27251), but it didn't work for me. I already have have `GF_AUTH_BASIC_ENABLED=false`

**Anything else we need to know?**:
All 3 actors: `grafana`, `nginx`, `oauth2_proxy` have clean logs, no warnings or errors.

**Environment**: `local`
- Grafana version: `grafana:latest`
- Data source type & version:
- OS Grafana is installed on: `MacOS`
- User OS & Browser: `Chrome`
- Grafana plugins:
- Others: `nginx`, `oauth2_proxy`

**Comment by marian-gheorghe** [comment]
I have replaced in Grafana config
```
- GF_AUTH_PROXY_HEADER_NAME=X-Forwarded-Email 
- GF_AUTH_PROXY_HEADER_PROPERTY=email 
- GF_AUTH_PROXY_HEADERS=Name:X-Forwarded-Email,Email:X-Forwarded-Email
```

And updated nginx.conf
```
proxy_set_header Forwarded $proxy_add_forwarded;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```

And the issue still persists

**Comment by marian-gheorghe** [comment]
I have tested the same nginx and oauth2_proxy configuration with `prometheus` and it works. 
For grafana, it just seems to be a matter of passing the right headers or this functionality is broken. 
Could someone have a look at the grafana config and advice on what could be tried out to make some progress on this ?
Thanks

**Comment by Jeinhaus** [comment]
In my case just starting Grafana with the above configuration and then passing the `X-Forwarded-Email` header does not work.
The configuration I used is

```yaml
# docker-compose.yml
version: '3'
services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: always
    user: '104'
    volumes:
      - $PWD/data/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
        # [server]
      - GF_SERVER_PROTOCOL=http
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_ROOT_URL=http://localhost:80/
      
        # [users]
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_AUTO_ASSIGN_ORG=true
      - GF_USERS_AUTO_ASSIGN_ORG_ROLE=Admin

      
      # [auth.basic]
      - GF_AUTH_BASIC_ENABLED=false
      
      # [auth]
      - GF_AUTH_DISABLE_LOGIN_FORM=true

      # [auth.proxy]
      - GF_AUTH_PROXY_ENABLED=true
      - GF_AUTH_PROXY_HEADER_NAME=X-Forwarded-Email 
      - GF_AUTH_PROXY_HEADER_PROPERTY=email 
      - GF_AUTH_PROXY_HEADERS=Name:X-Forwarded-Email Email:X-Forwarded-Email
      - GF_AUTH_PROXY_AUTO_SIGN_UP=true
      - GF_AUTH_PROXY_ENABLE_LOGIN_TOKEN=false
```

and then I use curl to query the API using 

```bash
curl -H "X-Forwarded-Email: foo@example.com" http://localhost:3000/api/users
```

which results in

```bash
{"accessErrorId":"ACE6203339251","message":"You'll need additional permissions to perform this action. Permissions needed: users:read","title":"Access denied"}
```

Shouldn't this be working according to the [docs](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/auth-proxy/#interacting-with-grafanas-authproxy-via-curl)?

**Comment by gwvandesteeg** [comment]
Check your headers, you have nginx looking for the `X-Email` headers, and grafana for `X-Forwarded-Email`.

**Comment by Jguer** [comment]
Hey, I'd advise using auth.jwt with oauth proxy for improved security (and better information handling).

You can check https://github.com/grafana/grafana/tree/main/devenv/docker/blocks/auth/jwt_proxy for inspiration.

Closing due to staleness

**Comment by air3ijai** [comment]
A working solution - [Grafana Oauth Proxy still displaying native login form](https://stackoverflow.com/questions/62559654/grafana-oauth-proxy-still-displaying-native-login-form)

**Comment by davgia** [comment]
> A working solution - [Grafana Oauth Proxy still displaying native login form](https://stackoverflow.com/questions/62559654/grafana-oauth-proxy-still-displaying-native-login-form)

It was working for me. But I've just updated to a newer Grafana version (10.1.5), through kube-prometheus-stack chart (51.8.1), and stopped working. Grafana just shows the login page while auth2_proxy completed the authentication successfully. Did you experience the same problem?

**Comment by air3ijai** [comment]
> Did you experience the same problem?

Just did an upgrade
```
resource "helm_release" "grafana" {
  name       = "grafana"
  repository = "https://grafana.github.io/helm-charts"
  chart      = "grafana"
  version    = "6.61.0"
```

`Grafana v10.1.5 (849c612fcb)` with `Oauth2 Proxy 7.5.1` and all works as expected.

**Comment by davgia** [comment]
> > Did you experience the same problem?
> 
> Just did an upgrade
> 
> ```
> resource "helm_release" "grafana" {
>   name       = "grafana"
>   repository = "https://grafana.github.io/helm-charts"
>   chart      = "grafana"
>   version    = "6.61.0"
> ```
> 
> `Grafana v10.1.5 (849c612fcb)` with `Oauth2 Proxy 7.5.1` and all works as expected.

could you please give me the complete configuration? grafana values, oauth2_proxy values etc..

**Comment by air3ijai** [comment]
> could you please give me the complete configuration? grafana values, oauth2_proxy values etc..
<details>
<summary>grafana.yaml</summary>

```yaml
# Values - https://github.com/grafana/helm-charts/tree/main/charts/grafana

# Ingress
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set  $user   $upstream_http_x_auth_request_user;
      auth_request_set  $email  $upstream_http_x_auth_request_email;
      proxy_set_header  X-Auth-Request-User   $user;
      proxy_set_header  X-Auth-Request-Email  $email;

  path: /
  hosts:
    - grafana.domain.tld
  tls:
    - hosts:
        - grafana.domain.tld
      secretName: grafana-tls

# Resources
resources:
  requests:
    memory: "200Mi"
    cpu: "200m"
  limits:
    memory: "1024Mi"
    cpu: "1024m"

# Persistance
persistence:
  enabled: true
  type: pvc
  size: 10Gi

# grafana.ini
grafana.ini:
  users:
    allow_sign_up: false
    auto_assign_org: true
    auto_assign_org_role: Editor
  auth:
    disable_login_form: false
    signout_redirect_url: https://grafana.domain.tld/oauth2/sign_out
  auth.proxy:
    enabled: true
    header_name: X-Auth-Request-User
    header_property: username
    headers: "Name:X-Auth-Request-User Email:X-Auth-Request-Email"
    auto_sign_up: true
    sync_ttl: 60
    enable_login_token: false

# Datasources
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Elasticsearch
      type: elasticsearch
      access: proxy
      url: http://elasticsearch:9200
      isDefault: true
      jsonData:
        index: '[kubernetes-]YYYY.MM.DD'
        interval: Daily
        timeField: '@timestamp'
      readonly: false
```
</details>


<details>
<summary>oauth2-proxy-grafana-ingress.yaml</summary>

```yaml
resources:
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: grafana-oauth2
      namespace: monitoring
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
    spec:
      ingressClassName: nginx
      rules:
      - host: grafana.domain.tld
        http:
          paths:
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: oauth2-proxy-grafana
                port:
                  number: 80
      tls:
      - hosts:
        - grafana.domain.tld
        secretName: grafana-tls
```
</details>

<details>
<summary>oauth2-proxy-grafana.yaml</summary>

```yaml
# Values - https://github.com/oauth2-proxy/manifests/tree/main/helm/oauth2-proxy

# App
image:
  tag: "v7.5.1"

# Config
config:
  configFile: |
    upstreams = [ "file:///dev/null" ]
    provider = "github"
    email_domains = [ "*" ]
    custom_sign_in_logo = "https://github.com/fluidicon.png"
    scope = "user:email read:org"
    github_org = "my-org"
    set_xauthrequest = true

  existingSecret: oauth2-proxy-grafana

# Metrics
metrics:
  enabled: true
```
</details>

**Comment by davgia** [comment]
Thank you, but it turns out that the problem was the latest version of ingress-nginx chart that disallows snippent annotations by default

**Comment by air3ijai** [comment]
Just did an update
```diff
-  version          = "4.7.2"
+  version          = "4.8.2"
```

And to have it here - [kubernetes/ingress-nginx/charts/ingress-nginx/values.yaml#L87](https://github.com/kubernetes/ingress-nginx/blob/15021952e10c263a5bf50cee09fa735a1dea6ce7/charts/ingress-nginx/values.yaml#L87)
```yaml
  allowSnippetAnnotations: true
```

PR: [Disable user snippets per default #10393](https://github.com/kubernetes/ingress-nginx/pull/10393)
Docs: [Configuration snippet](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#configuration-snippet)

**Comment by wackazong** [comment]
You should probably add this to values.yaml for grafana.ini:

```yaml
grafana.ini:
  security:
    disable_initial_admin_creation: true
```

https://github.com/helm/charts/issues/20697#issuecomment-674593231

**Comment by air3ijai** [comment]
I left the default Admin as a fail-back user in case if Oauth2 will fail and login form is enabled as well, and we can use it via port-forwarding.

But I have a question about that.

Users are auto-created and we assign them `Editor` role
```yaml
grafana.ini:
  users:
    auto_assign_org: true
    auto_assign_org_role: Editor
  auth:
    disable_login_form: false
  auth.proxy:
    auto_sign_up: true
```
Is there a way to add Admin permissions to some Oauth "auto-created at login accounts" without using a default Admin user for that?

**Comment by air3ijai** [comment]
One more issue, when updated top the latest ingress version - [1.12.2](https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v1.12.2).

Found a fix in [Admission Controller Error with allowSnippetAnnotations: true #12648](https://github.com/kubernetes/ingress-nginx/issues/12648#issuecomment-2581094073)

> The default annotation risk level has been lowered to `High` in v1.12. Snippet annotations have an annotation risk level of `Critical`.

So, since [ controller-v1.12.0](https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v1.12.0) it is required to update [`annotations-risk-level`](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#annotations-risk-level)
```yaml
controller:
  name: controller
  config:
    annotations-risk-level: Critical
```
