### ISSUE TITLE
Env variables is unsupport in new alerting provisioning 

### ISSUE THREAD

**Issue by vanchaxy** [grafana/grafana#53315]
**What happened**:
Trying to pass URL to contact point (rel #36153 ) as env var. Grafana ignores it.

**What you expected to happen**:
Grafana should use env var.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create the next yaml in alerting folder.
```
apiVersion: 1

contactPoints:
  - name: slack-default
    receivers:
    - uid: slack_default
      type: slack
      settings:
        url: $SLACK_DEFAULT_WEBHOOK
```
2. Set SLACK_DEFAULT_WEBHOOK env.
3. Try to use it. Grafana will try to make the request using the env name as url.

**Environment**:
- Grafana version: 9.1.0-beta1
