### ISSUE TITLE
Explore throws 404 error on /api/v1/rules with Mimir as Source

### ISSUE THREAD

**Issue by m-wack** [grafana/grafana#53451]
I have setup Mimir in Kubernetes using the following config:

alertmanager:
enable_api: false
ruler:
enable_api: false

I am using Mimir 2.2.0 and Grafana 9.0.1.

I am using Mimir as a Prometheus Datasource in Grafana with
manageAlerts: false

However, when going into Explore in Grafana and selecting the Mimir source, Grafana does a Request to:
/api/datasources/4/resources/api/v1/rules

This results in a 404 Not Found Banner shown in Grafana. Everything is working though, I can do queries, I see stuff. It's just that this error pops up everytime. 

I am also using Loki as a Datasource, also with the Ruler disabled and manageAlerts set to false in Grafana, and it does not throw this error. 
The Mimir Team told me this seems to be a Grafana Issue.

Any idea why this happens?

Regards

**Comment by mellieA** [comment]
@m-wack was there a previous issue/discussion with the mimir team you can reference here for context? 

To help me route this to the right squad, are you only seeing the error in explore or is it showing up in other places when you reference your mimir datasource?

I tried this using the docker tutorial environment at https://grafana.com/tutorials/play-with-grafana-mimir/ and edited the mimir configuration to set `enable_api: false` for alertmanager and ruler settings: 

```
alertmanager:
    data_dir: /data/alertmanager
    enable_api: false
    external_url: http://localhost:9009/alertmanager
. . . 
ruler:
    alertmanager_url: http://127.0.0.1:8080/alertmanager
    enable_api: false
```

I added a new mimir datasource and disabled managing alerts: 

![Screen Shot 2022-08-15 at 1 22 41 PM](https://user-images.githubusercontent.com/18175287/184702789-38ce65e6-687a-4da2-b877-1dd571717712.png)

The tutorial is using mimir 2.2.0 and Grafana 9.0.7
