### ISSUE TITLE
Duplicate notifications in the new alerting system

### ISSUE THREAD

**Issue by legolego621** [grafana/grafana#53990]
**What happened**:
I use grafana in kubernetes cluster in the amount of 2 replicas. They use one database data source.
I use new grafana alerts.

my env:
```
  - name: GF_ALERTING_ENABLED
    value: "false"
  - name: GF_UNIFIED_ALERTING_ENABLED
    value: "true"
```

I also use sending notifications in telegram.
When an alert is triggered, a notification is triggered from each running replica of grafana.

**What you expected to happen**:
Since graphana replicas actually use one database, notifications must be sent once, regardless of the number of replicas

**How to reproduce it (as minimally and precisely as possible)**:
1. Use grafana in k8s with more than 1 replicas, use one database data per replica.
2. Use the new alert system.
```
  - name: GF_ALERTING_ENABLED
    value: "false"
  - name: GF_UNIFIED_ALERTING_ENABLED
    value: "true"
```
3. Create a test alert, for example, in Telegram.
4. Get the number of alerts to the source equal to the number of replicas.

**Environment**:
- Grafana version: 9.1.0
- Data source type & version: grafana/grafana-enterprise:9.1.0
- OS Grafana is installed on: k8s v1.23.7

**Comment by armandgrillet** [comment]
Please follow https://grafana.com/docs/grafana/latest/alerting/high-availability/enable-alerting-ha/#enable-alerting-high-availability and let us know if you are still having issues.

**Comment by jasperjonker** [comment]
I had the same issue and the documentation for me wasn't all that clear. I got it working by doing the following:

- Add the port 9094 to the grafana deployment:
   ```yaml
  ports:
    - containerPort: 3000
      name: http-grafana
      protocol: TCP
    - containerPort: 9094
      name: grafana-alert
      protocol: TCP
  ```
- And the environmental variables to the grafana deployment as well:

  ```yaml
  env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
  ```

- Create a headless service, which is actually returning the pod IP instead of the service IP, which is exactly what `ha_peers` in `grafana.ini` needs:

  ```yaml
  apiVersion: v1
  kind: Service
  metadata:
    name: grafana-alerting
    namespace: grafana
    labels:
      app.kubernetes.io/name: grafana-alerting
      app.kubernetes.io/part-of: grafana
  spec:
    type: ClusterIP
    clusterIP: "None"
    ports:
      - port: 9094
    selector:
      app: grafana
  ```
Make sure your grafana deployment has the label `app:grafana`.

- Now add in the `grafana.ini`:
  ```ini
  [unified_alerting]
  enabled = true
  ha_listen_address = "${POD_IP}:9094"
  ha_peers = "grafana-alerting.grafana:9094"
  ha_advertise_address = "${POD_IP}:9094"
  ```
