### ISSUE TITLE
Provisioning: ContactPoints: disableResolveMessage NOT supported via YAML

### ISSUE THREAD

**Issue by mmusenbr** [grafana/grafana#54121]
**What happened**: I tried to provision contact points for the new alerting via the yaml-provisioning.

```yaml
      - name: TEST
        orgId: 1
        receivers: 
        - name: test
          uid: 123
          type: email
          disableResolveMessage: true
          settings:
            singleEmail: true
            addresses: some@address.com
``` 

After the provisiong the contact point exists, but the 'Disable resolved message' is not checked.

![image](https://user-images.githubusercontent.com/522783/186275190-80cecbac-b26c-4e2f-8041-116941e02eb0.png)

**What you expected to happen**:
After the provisiong the contact point via YAML and having disableResolveMessage set to true, the option is also checked.

**How to reproduce it (as minimally and precisely as possible)**:
See snippet above.

**Anything else we need to know?**:

Possible fix, imho:

```diff
diff --git a/pkg/services/provisioning/alerting/contact_point_types.go b/pkg/services/provisioning/alerting/contact_point_types.go
index 82803bb316..1f80570c71 100644
--- a/pkg/services/provisioning/alerting/contact_point_types.go
+++ b/pkg/services/provisioning/alerting/contact_point_types.go
@@ -68,7 +68,7 @@ type ReceiverV1 struct {
        UID                   values.StringValue `json:"uid" yaml:"uid"`
        Type                  values.StringValue `json:"type" yaml:"type"`
        Settings              values.JSONValue   `json:"settings" yaml:"settings"`
-       DisableResolveMessage values.BoolValue   `json:"disableResolveMessage"`
+       DisableResolveMessage values.BoolValue   `json:"disableResolveMessage" yaml:"disableResolveMessage"`
 }
 
 func (config *ReceiverV1) mapToModel(name string) (definitions.EmbeddedContactPoint, error) {

```

**Environment**:
- Grafana version: 9.1.1
- Data source type & version: not-applicable
- OS Grafana is installed on: not-applicable
- User OS & Browser: not-applicable
- Grafana plugins: not-applicable
