### ISSUE TITLE
Alert rule provision using Math returns error

### ISSUE THREAD

**Issue by sarm333** [grafana/grafana#54532]
Apologies in advance if there was an oversight on how I provision the alert rule, but have really been stuck on this for a while.

**What happened**:

Cannot provision an alert rule with a basic math expression like "$A > 2", but can create an alert rule with the same expression through the UI. The following error is thrown when trying to provision the alert rule:

```
Failed to evaluate queries and expressions: failed to execute conditions: invalid math command type in 'B': expr: unexpected ">" in input: F()
```

**What you expected to happen**:

The alert to be successfully provisioned.

**How to reproduce it (as minimally and precisely as possible)**:

- Manually create an alert using a default prometheus datasource and use a math expression on it. This should work
- Make a copy of the json of the newly created alert rule via the grafana API or through Chrome Dev tools once the above has been created
- Delete the alert rule to ensure no clashing
- Create a json/yaml for the provisioned alert using the data given. This will throw the math error

**Anything else we need to know?**:

This is what is given back from chrome dev tools (api/ruler/grafana/api/v1/rules?subtype=cortex) once manually created:

```
{
    "expr": "",
    "for": "5m",
    "grafana_alert": {
        "id": 13,
        "orgId": 1,
        "title": "test_rule",
        "condition": "B",
        "data": [
            {
                "refId": "A",
                "queryType": "",
                "relativeTimeRange": {
                    "from": 600,
                    "to": 0
                },
                "datasourceUid": "<prometheus_datasource_id>",
                "model": {
                    "editorMode": "builder",
                    "expr": "http_requests_total",
                    "hide": false,
                    "intervalMs": 1000,
                    "legendFormat": "__auto",
                    "maxDataPoints": 43200,
                    "range": true,
                    "refId": "A"
                }
            },
            {
                "refId": "B",
                "queryType": "",
                "relativeTimeRange": {
                    "from": 0,
                    "to": 0
                },
                "datasourceUid": "-100",
                "model": {
                    "conditions": [
                        {
                            "evaluator": {
                                "params": [
                                    3
                                ],
                                "type": "gt"
                            },
                            "operator": {
                                "type": "and"
                            },
                            "query": {
                                "params": [
                                    "A"
                                ]
                            },
                            "reducer": {
                                "params": [],
                                "type": "last"
                            },
                            "type": "query"
                        }
                    ],
                    "datasource": {
                        "type": "__expr__",
                        "uid": "-100"
                    },
                    "expression": "$A \u003e 2",
                    "hide": false,
                    "intervalMs": 1000,
                    "maxDataPoints": 43200,
                    "refId": "B",
                    "type": "math"
                }
            }
        ],
        "updated": "2022-08-31T13:47:59Z",
        "intervalSeconds": 60,
        "version": 1,
        "uid": "<some_uid>",
        "namespace_uid": "p7ovkHZVz",
        "namespace_id": 1,
        "rule_group": "new_test_group",
        "no_data_state": "NoData",
        "exec_err_state": "Alerting"
    }
}
```

The above was used and modified for the provisioning which I ended up with:

```
{
    "expr": "",
    "for": "5m",
    "id": 13,
    "orgId": 1,
    "title": "test_rule",
    "condition": "B",
    "data": [
        {
            "refId": "A",
            "queryType": "",
            "relativeTimeRange": {
                "from": 600,
                "to": 0
            },
            "datasourceUid": "<prometheus_datasource_id>",
            "model": {
                "editorMode": "builder",
                "expr": "http_requests_total",
                "hide": false,
                "intervalMs": 1000,
                "legendFormat": "__auto",
                "maxDataPoints": 43200,
                "range": true,
                "refId": "A"
            }
        },
        {
            "refId": "B",
            "queryType": "",
            "relativeTimeRange": {
                "from": 0,
                "to": 0
            },
            "datasourceUid": "-100",
            "model": {
                "conditions": [
                    {
                        "evaluator": {
                            "params": [
                                3
                            ],
                            "type": "gt"
                        },
                        "operator": {
                            "type": "and"
                        },
                        "query": {
                            "params": [
                                "A"
                            ]
                        },
                        "reducer": {
                            "params": [],
                            "type": "last"
                        },
                        "type": "query"
                    }
                ],
                "datasource": {
                    "type": "__expr__",
                    "uid": "-100"
                },
                "expression": "$A \u003e 2",
                "hide": false,
                "intervalMs": 1000,
                "maxDataPoints": 43200,
                "refId": "B",
                "type": "math"
            }
        }
    ],
    "intervalSeconds": 60,
    "uid": "YzJR_9ZVf",
    "rule_group": "new_test_group",
    "no_data_state": "NoData",
    "exec_err_state": "Alerting"
}
```

Have also tried using the unicode equivalent of ">" (\U+003E) but the same outcome

**Environment**:
- Grafana version: 9.1.1
- OS Grafana is installed on: Docker image: grafana/grafana:9.1.1
- User OS & Browser: Mac OS - Chrome

**Comment by sarm333** [comment]
Just to add, seems like it throws this error when using variables in the expression. Simply have something like "2 > 1" as the expression seems to work. Its when you combine something like "$A" within the expression

**Comment by mellieA** [comment]
@sarm333 another user had an issue with alerting interpreting the SQL statement that included ` $__timeEpoch(date_time)` in this issue https://github.com/grafana/grafana/issues/54369.

 Forwarding both to our alerting devs to get some insight about how to handle these use cases.

**Comment by aaronstutzer** [comment]
i have the same issue and cant even delete the alerts i already created :(

**Comment by mellieA** [comment]
@sarm333 this issue should be resolved with https://github.com/grafana/grafana/pull/54293

Please reopen if this isn't fixed with 9.1.2

**Comment by sarm333** [comment]
thank you for this. Will be updating to test

**Comment by salacr** [comment]
I think that this is actually not fixed I'm trying to provision an alert like this (the data source is VictoriaLogs)
```
apiVersion: 1
# List of rule groups to import or update
groups:
  # <int> organization ID, default = 1
  - orgId: 1
    # <string, required> name of the rule group
    name: Provisioned
    # <string, required> name of the folder the rule group will be stored in
    folder: general-provisioned
    # <duration, required> interval that the rule group should evaluated at
    interval: 180s
    # <list, required> list of rules that are part of the rule group
    rules:
      # <string, required> unique identifier for the rule
      - uid: f1877f66-e665-48f8-bdad-874ef46a14e1
        title: Alert:Error in logs
        condition: C
        data:
        - refId: A
          queryType: instant
          relativeTimeRange:
            from: 600
            to: 0
          datasourceUid: MMqDDPsVz
          model:
            editorMode: code
            expr: log_level:in("ERROR", "CRITICAL") | stats by (_time:10m, _msg, module_name, context_exception_file, message_hash) count() as log_count
            hide: false
            intervalMs: 1000
            legendFormat: ''
            maxDataPoints: 43200
            queryType: instant
            refId: A
        - refId: B
          type: expr
          datasourceUid: __expr__
          model:
            expression: A
            type: reduce
            reducer: last
            settings:
              mode: dropNN
            refId: B
        - refId: C
          datasourceUid: __expr__
          model:
            conditions:
                - evaluator:
                    params:
                        - B
                        - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    params: []
                  reducer:
                    params: []
                    type: avg
                  type: query
            datasource:
                name: Expression
                type: __expr__
                uid: __expr__
            expression: "$B > 0"
            intervalMs: 1000
            maxDataPoints: 43200
            refId: C
            type: math
        updated: '2023-06-15T08:35:15+02:00'
        noDataState: OK
        execErrState: Error
        for: 5m
        labels:
          type: logs
        isPaused: false
        annotations:
          __dashboardUid__: bU9TKEy4z
          __panelId__: '2'
```

But the result is like this:

<img width="1763" height="1127" alt="Image" src="https://github.com/user-attachments/assets/af144012-f33a-4e11-afa0-01b48885b782" />
