### ISSUE TITLE
Unable to get a unified alerting screenshot in Slack

### ISSUE THREAD

**Issue by wiardvanrij** [grafana/grafana#54742]
**What happened**:
Configured Grafana to create a screenshot for an alert via a Slack notification channel. I see however, no indication of this happening.

**What you expected to happen**:
The Slack Alert, contains an image via an URL of my Grafana public http folder

**How to reproduce it (as minimally and precisely as possible)**:
- configure Grafana to use image renderer and confirm that it is working. In my case, I've confirmed this by creating a report
- configure Grafana to make screenshots:

```
grafana.ini:
  external_image_storage:
    provider: local
  unified_alerting:
    enabled: true
    screenshots:
      capture: true
      max_concurrent_screenshots: 10
      upload_external_image_storage: true
  paths:
    data: /tmp-grafana-data
    temp_data_lifetime: 12h
```

- create an alert via a panel (which is a required) as per https://grafana.com/docs/grafana/latest/alerting/images-in-notifications/

**Anything else we need to know?**:
- I've enabled logs on debug mode and I have no indication of any errors or whatsoever. 
- I've tried to use ` {{.ImageURL}}` in the notification text body and that results in an empty string

**Environment**:
- Grafana version: v9.1.2 enterprise
- Others: image-renderer:latest
- On K8s
