### ISSUE TITLE
Log volume not showing any color 

### ISSUE THREAD

**Issue by Matthias64** [grafana/grafana#54863]
Hello,

Using Grafana v9.0.5, log Volume histogram is not reflecting the colors of the logs I have filtered : 

![image](https://user-images.githubusercontent.com/25939090/188928792-372d3d73-2226-4d9a-9504-baf37f6dddc0.png)

I expected to see info/warning/debug levels on the histogram as in older version.
The level is well detected in `Detected fields` 

![image](https://user-images.githubusercontent.com/25939090/188929473-c68ee15e-20ef-4dce-adf3-d744cdbf8c46.png)

Thank you !

Tested with Loki 2.2.0 and Loki 2.6.1

**Comment by ivanahuckova** [comment]
Hello @Matthias64, this doesn't seem like an issue, but rather that your logs don't have level label, and they have level information in content. Please review https://grafana.com/blog/2022/03/02/new-in-grafana-8.4-how-to-use-full-range-log-volume-histograms-with-grafana-loki/, specifically **How to see log volume with levels**.

**Comment by mentlak0** [comment]
@Matthias64  Did you attempt these? Mine still not working - tried all various methods to see colored logs

**Comment by Matthias64** [comment]
@mentlak0 I have tested but did not succeed to make it work at the moment. I think that I may need to tweak my promtail configuration. I will let you know if I figure out how to fix it.

**Comment by Matthias64** [comment]
Hello @mentlak0 and to help anyone facing this issue when upgrading Grafana,

I resolved that on my side by extracting directly the log level using promtail.
I used the following config that matches my specific type of logs 

```
config:
    logLevel: info # debug
    lokiAddress: http://loki.grafana-loki.svc.cluster.local:3100/loki/api/v1/push
    #scrapeConfigs: |
    snippets:
        pipelineStages: 
            - regex:
                 expression: '^.*?,\\\"level\\\":\\\"(?P<log_level>\w+)\\\".*?$'
            - labels:
                  level: log_level
```
Please note that if you want it to be detected automatically by Grafana you need to name the label as `level`

Once I added that, the level was appearing as an actual label in Grafana and the histogram is now colorful again. 
Please let me know if you find a simpler solution.

Have a good weekend :)
