### ISSUE TITLE
Alerting provisioning not working in Kubernetes

### ISSUE THREAD

**Issue by bygui86** [grafana/grafana#55069]
**What happened**:
I want to provision rules, contact points and notification policies mounting yaml files (coming from K8s ConfigMaps or Secrets) into Grafana running on K8s.
Unfortunately Grafana is not able to start, keeping crashing and restarting with following error logs:
```json
{"level":"info","logger":"query_data","msg":"Query Service initialization","t":"2022-09-13T09:33:22.423284432Z"}
{"level":"info","logger":"live.push_http","msg":"Live Push Gateway initialization","t":"2022-09-13T09:33:22.428724234Z"}
{"first_tick":"2022-09-13T09:33:30Z","level":"info","logger":"ticker","msg":"starting","t":"2022-09-13T09:33:22.457649796Z"}
{"level":"info","logger":"infra.usagestats.collector","msg":"registering usage stat providers","t":"2022-09-13T09:33:22.559032391Z","usageStatsProvidersLen":2}
{"error":"open /etc/grafana/provisioning/plugins: no such file or directory","level":"error","logger":"provisioning.plugins","msg":"Failed to read plugin provisioning files from directory","path":"/etc/grafana/provisioning/plugins","t":"2022-09-13T09:33:22.682713713Z"}
{"error":"open /etc/grafana/provisioning/notifiers: no such file or directory","level":"error","logger":"provisioning.notifiers","msg":"Can't read alert notification provisioning files from directory","path":"/etc/grafana/provisioning/notifiers","t":"2022-09-13T09:33:22.682826738Z"}
Failed to start grafana. error: file has invalid suffix '..2022_09_13_09_33_19.978766587' (.yaml,.yml,.json accepted)
file has invalid suffix '..2022_09_13_09_33_19.978766587' (.yaml,.yml,.json accepted)
```

I tried to ssh into Grafana pod to see the content of `/etc/grafana/provisioning/alerting` and here the outcome:
```bash
$ ls -lah /etc/grafana/provisioning/alerting
total 12K
drwxrwsrwx    3 root     nobody      4.0K Sep 12 15:18 .
drwxr-xr-x    3 root     root        4.0K Sep 12 15:18 ..
drwxr-sr-x    2 root     nobody      4.0K Sep 12 15:18 ..2022_09_12_15_18_07.095620097
lrwxrwxrwx    1 root     nobody        31 Sep 12 15:18 ..data -> ..2022_09_12_15_18_07.095620097
lrwxrwxrwx    1 root     nobody        20 Sep 12 15:18 alerting.yaml -> ..data/alerting.yaml
```
And the content of `alerting.yaml` is exactly the same as in the K8s ConfigMap reported below.

I mounted alerting yaml files same as I provisioned datasources.
Here the piece of Grafana Deployment manifest:
```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  # ...
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      # ...
      containers:
        - name: grafana
          image: grafana/grafana:9.1.4
          # ...
          volumeMounts:
            # storage
            - mountPath: /var/lib/grafana
              name: data-grafana
            - mountPath: /tmp
              name: tmp-grafana
            # configurations
            - mountPath: /etc/grafana
              name: grafana-ini
            # provisioning
            - mountPath: /etc/grafana/provisioning/datasources
              name: grafana-datasources
            - mountPath: /etc/grafana/provisioning/alerting
              name: grafana-alerting
      # ...
      volumes:
        # storage
        - name: data-grafana
          persistentVolumeClaim:
            claimName: data-grafana
        - name: tmp-grafana
          emptyDir: {}
        # configurations
        - name: grafana-ini
          secret:
            secretName: grafana-ini
        # provisioning
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
        - name: grafana-alerting
          configMap:
            name: grafana-alerting
```
Here alerting ConfigMap manifest:
```yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alerting
data:
  alerting.yaml: |-
    apiVersion: 1
    contactPoints:
      - orgId: 1
        name: email-test
        receivers:
          - uid: email-test
            type: email
            settings:
              addresses: "test@me.net"
    policies:
      - orgId: 1
        receiver: email-test
        group_by: [ domain ]
        matchers:
          - domain =~ "prototype|investigation"
        group_wait: 60s
        group_interval: 5m
        repeat_interval: 4h
    groups:
      - orgId: 1
        name: my_rule_group
        folder: my_first_folder
        interval: 60s
        rules:
          - uid: my_id_1
            title: my_first_rule
            condition: A
            data:
              - refId: A
                datasourceUid: '-100'
                model:
                  conditions:
                    - evaluator:
                        params:
                          - 3
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                          - A
                      reducer:
                        type: last
                      type: query
                  datasource:
                    type: __expr__
                    uid: '-100'
                  expression: 1==0
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: A
                  type: math
            noDataState: Alerting
            for: 60s
            annotations:
              some_key: some_value
            labels:
              team: sre_team_1
              domain: prototype
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
      - name: prometheus
        type: prometheus
        uid: 1
        orgId: 1
        url: $PROMETHEUS_URL
        access: proxy
        isDefault: true
        editable: true
        version: 1
```

**What you expected to happen**:
Alerting provisioning works same as datasources provisioning, mounted in the exact same way.

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy Grafana yaml manifests (Deployment and ConfigMap) on K8s
2. Looking at Grafana logs

**Anything else we need to know?**:
Not at the moment.

**Environment**:
- Grafana version:   v9.1.4
- Data source type & version:   N/A
- OS Grafana is installed on:   Google COS (container optimised system)
- User OS & Browser:   MacOS + Google Chrome
- Grafana plugins:   N/A
- Others:   K8s v1.21.14-gke.700
