### ISSUE TITLE
Notification policies (alerting) provisioning not working as described in documentation

### ISSUE THREAD

**Issue by bygui86** [grafana/grafana#55073]
**What happened**:
Still struggling with issue #55069, I found a sort of workaround, but now I have a couple of issues provisioning notification policies.
Here the loaded yaml file:
```yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alerting
data:
  alerting.yaml: |-
    apiVersion: 1
    contactPoints:
      - orgId: 1
        name: email-test
        receivers:
          - uid: email-test
            type: email
            settings:
              addresses: "test@me.net"
      - orgId: 1
        name: slack-test
        receivers:
          - uid: slack-test
            type: slack
            settings:
              recipient: ***
              token: ***
              icon_emoji: broken_heart
              title: |
                {{ template "slack.default.title" . }}
              text: |
                {{ template "slack.default.text" . }}
    policies:
      - orgId: 1
        receiver: email-test
        group_wait: 60s
        group_interval: 5m
        repeat_interval: 24h
      - orgId: 1
        receiver: slack-test
        group_by: [ domain ]
        matchers:
          - domain =~ "prototype|investigation"
        group_wait: 60s
        group_interval: 5m
        repeat_interval: 4h
    groups:
      # ...
```
Once Grafana starts, I see the following situation:
- Rules are properly loaded
  ![Screenshot 2022-09-13 at 11 13 03](https://user-images.githubusercontent.com/22518997/189872007-44fff191-aba6-451a-9596-06d966c35cc5.png)
- Contact points are properly loaded
  ![Screenshot 2022-09-13 at 10 58 09](https://user-images.githubusercontent.com/22518997/189872107-968f849d-23ac-4f22-bb1c-b2f612a4759d.png)
- Notification policies are NOT properly loaded, I don't see all notification policies specified in the yaml manifest and I'm not able to create further policies in the UI!
  ![Screenshot 2022-09-13 at 10 57 56](https://user-images.githubusercontent.com/22518997/189872204-4ca6c431-e3b7-4ff7-aecb-589deccc3cbb.png)

**What you expected to happen**:
1. All notifications policies listed in the yaml file are loaded.
2. Grafana

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy Grafana on K8s (see issue #55069 for Deployment manifest and above for ConfigMap)
2. Access alerting section in UI

**Anything else we need to know?**:
Not at the moment.

**Environment**:
- Grafana version: v9.1.4
- Data source type & version: N/A
- OS Grafana is installed on: Google COS (container optimised system)
- User OS & Browser: MacOS + Google Chrome
- Grafana plugins: N/A
- Others: K8s v1.21.14-gke.700

**Comment by bygui86** [comment]
I was able to reach a working configuration for Notification Policies mixing info from [documentation](https://grafana.com/docs/grafana/latest/administration/provisioning/#notification-policies) and [OpenAPI](https://editor.swagger.io/?url=https://raw.githubusercontent.com/grafana/grafana/main/pkg/services/ngalert/api/tooling/post.json).

But the documentation is absolutely incomplete and misleading, it must be improved because it took really a lot of time to come up with a working configuration.

Here below the working configuration I built:
```yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-notification-policies
data:
  notification-policies.yaml: |-
    apiVersion: 1
    policies:
      - orgId: 1
        receiver: email
        provenance: kubernetes-configmap
        group_wait: 60s
        group_interval: 5m
        repeat_interval: 24h
        routes:
          - receiver: slack-channel-1
            group_wait: 60s
            group_interval: 5m
            group_by:
              - namespace
            matchers:
              - namespace =~ a|b|c|d
            repeat_interval: 5m
            continue: false
          - receiver: slack-channel-2
            group_wait: 60s
            group_interval: 5m
            group_by:
              - app
            matchers:
              - app =~ grafana|prometheus|loki
            repeat_interval: 3h
            continue: false
          - receiver: slack-channel-3
            group_wait: 60s
            group_interval: 5m
            group_by:
              - kafka-topic
            matchers:
              - namespace = kafka
              - kafka-topic =~ ^my-topic
            repeat_interval: 6h
            continue: false
```

**Comment by brendamuir** [comment]
@JohnnyQQQQ can you help me by taking a look at this? is this covered by the doc updates we did?

**Comment by austin-millan** [comment]
I noticed OP is missing the `routes` field in the `policies` map... That seems to be required at least with my approach of piggybacking on a root contact point then doing sub-routing from there.

Here's a working configuration (with routes):

```
contactPoints:
  # <int> organization ID, default = 1
  - orgId: 1
    # <string, required> name of the contact point
    name: default
    receivers:
      - name: default
        uid: abc123
        type: email
        disableResolveMessage: true
        settings:
          singleEmail: true
          addresses: abc@default.com
  # <int> organization ID, default = 1
  - orgId: 1
    # <string, required> name of the contact point
    name: contact-point-sub1
    receivers:
      - name: contact-point-sub1
        uid: twLu0PI4zz
        type: email
        disableResolveMessage: true
        settings:
          singleEmail: true
          addresses: abc@sub1.com
  - orgId: 1
    # <string, required> name of the contact point
    name: contact-point-sub2
    receivers:
      - name: contact-point-sub2
        uid: pQLu0EI4zm
        type: email
        disableResolveMessage: true
        settings:
          singleEmail: true
          addresses: abc@sub2.com

policies:
  - orgId: 1
    receiver: default
    group_by: ['...']
    # provenance: file
    group_wait: 60s
    group_interval: 5m
    repeat_interval: 24h
    matchers:
      - domain =~ sub1|sub2
    routes:
      - receiver: contact-point-sub1
        group_wait: 60s
        group_interval: 5m
        repeat_interval: 4h
        matchers:
          - domain = sub1
        continue: false
      - receiver: contact-point-sub2
        group_wait: 60s
        group_interval: 5m
        repeat_interval: 4h
        matchers:
          - domain = sub2
        continue: false
```
Results in:
![notification-policies](https://user-images.githubusercontent.com/14066723/196786590-2841aefb-f7a3-42bc-bec2-f09fd3f5e139.png)


Now the same configuration with no routes:
![notification-policy2](https://user-images.githubusercontent.com/14066723/196786872-bf4f76b7-0643-4dab-963b-abdc29d365d3.png)

**Comment by bygui86** [comment]
@brendamuir I read again the doc here https://grafana.com/docs/grafana/latest/administration/provisioning/#contact-points and it looks still incomplete :(

Fields and description of `routes` is completely missing.

Here what is presented in the doc:
```yaml
# config file version
apiVersion: 1

# List of notification policies
policies:
  # <int> organization ID, default = 1
  - orgId: 1

    # [...]

    # routes:
    # FIELDS AND DESCRIPTION MISSING HERE
```
