### ISSUE TITLE
Grafana ES datasource issue when upgrading from v8 to v9.1.5

### ISSUE THREAD

**Issue by pjamenaja** [grafana/grafana#55353]
**What happened**:
I'm using this snippet to configure Grafana (NOT configure via UI) to connect ES, it is able to connect to ES without any issue in v8.3.5 but when I upgraded Grafana to v9.1.5 with the same snippet, it then unable to connect to ES, with this error "Elasticsearch error: Authentication to data source failed"
```
      - name: ES-SOC
        type: elasticsearch
        access: Server
        url: https://es-soc-es-http.es-soc.svc.cluster.local:9200
        basicAuth: true
        basicAuthUser: ${username}
        basicAuthPassword: ${password}
        database: ".ds-metrics-rtarf-events-soc-*"
        jsonData:
          interval: null
          timeField: '@timestamp'
          esVersion: '8.0.0'
          tlsSkipVerify: true
          tlsAuthWithCACert: false
```
![image](https://user-images.githubusercontent.com/28744323/190962707-7b3b10e1-a59b-45fd-b590-8b795fb0b826.png)

**What you expected to happen**:
Able to connect to ES as it was in v8.3.5

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: v9.1.5
- Data source type & version: Elasticsearch
- OS Grafana is installed on: Docker
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by mc-em** [comment]
Hi @pjamenaja,

It could be because of envelope encryption is enabled by default (starting from v9.0)
[https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-database-encryption/](url)

try to add new ES datasource with same details again or try adding below lines in grafana configuration file then restart grafana service.

[feature_toggles]
enable = disableEnvelopeEncryption

**Comment by pjamenaja** [comment]
Hi @mc-em,

Still not work, below are the configuration copied from `/etc/grafana/grafana.ini`. Yes, I did try adding the ES data source manually and it works. Unfortunately, we need to go with the `as code` way, no need for human to do any kind of manual configuration.

```
[analytics]
check_for_updates = true
[auth.generic_oauth]
api_url = https://keycloak.rtarf-nonprod.xxxxxx.com/auth/realms/rtaf-soc/protocol/openid-connect/userinfo
auth_url = https://keycloak.rtarf-nonprod.xxxxxx.com/auth/realms/rtaf-soc/protocol/openid-connect/auth
client_id = $__file{/etc/secrets/auth_generic_oauth/client_id}
client_secret = $__file{/etc/secrets/auth_generic_oauth/client_secret}
enabled = true
name = Keycloak
role_attribute_path = contains(roles[*], 'admin') && 'Admin' || contains(roles[*], 'editor') && 'Editor' || 'Viewer'
scopes = profile email
signout_redirect_url = https://keycloak.rtarf-nonprod.xxxxxx.com/auth/realms/rtaf-soc/protocol/openid-connect/logout?client_id=gra
tls_skip_verify_insecure = true
token_url = https://keycloak.rtarf-nonprod.xxxxxx.com/auth/realms/rtaf-soc/protocol/openid-connect/token
[auth.ldap]
enabled = true

[feature_toggles]
enable = disableEnvelopeEncryption

[grafana_net]
url = https://grafana.net
[log]
level = debug
mode = console
[paths]
data = /var/lib/grafana/
logs = /var/log/grafana
plugins = /var/lib/grafana/plugins
provisioning = /etc/grafana/provisioning
[server]
domain = grafana-soc.rtarf-nonprod.xxxxxx.com
root_url = https://grafana-soc.rtarf-nonprod.xxxxxx.com
```

**Comment by ivanahuckova** [comment]
@pjamenaja Can you please try to update your provisioning file following this example: https://grafana.com/docs/grafana/latest/administration/provisioning/#example-data-source-config-file . For example `basicAuthPassword` should be under `secureJsonData `.

**Comment by pjamenaja** [comment]
Hi @ivanahuckova 

The code block below solved my issue. Thank you very much.

```
      - name: ES-SOC
        type: elasticsearch
        access: Server
        url: https://es-soc-es-http.es-soc.svc.cluster.local:9200
        basicAuth: true
        basicAuthUser: ${username}
        database: "rtarf-events-soc-*"
        jsonData:
          interval: null
          timeField: '@timestamp'
          esVersion: '8.0.0'
          tlsSkipVerify: true
          tlsAuthWithCACert: false
        secureJsonData:
          basicAuthPassword: ${password}
```
