### ISSUE TITLE
Error: Minified React error #185 deploy in Azure kubernetes Service

### ISSUE THREAD

**Issue by wenbya** [grafana/grafana#55653]
**Steps to reproduce**:
grafana.yaml
```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: grafana
          image: grafana/grafana:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http-grafana
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-pv
      volumes:
        - name: grafana-pv
          persistentVolumeClaim:
            claimName: grafana-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http-grafana
  selector:
    app: grafana
  sessionAffinity: None
  type: LoadBalancer
```
`kubectl apply -f grafana.yml`

**Actual Result**:
```
$ kubectl get all
NAME                           READY   STATUS    RESTARTS   AGE
pod/grafana-6fcb59c4bf-cxcsb   1/1     Running   0          5m8s

NAME                 TYPE           CLUSTER-IP    EXTERNAL-IP     PORT(S)          AGE
service/grafana      LoadBalancer   10.0.24.146   20.75.xxx.121   3000:32535/TCP   5m8s
service/kubernetes   ClusterIP      10.0.0.1      <none>          443/TCP          8d

NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/grafana   1/1     1            1           5m10s

NAME                                 DESIRED   CURRENT   READY   AGE
replicaset.apps/grafana-6fcb59c4bf   1         1         1       5m11s
```

**Expected Result**
```
An unexpected error happened
DetailsError: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

    at rl (http://20.75.XXX.121:3000/public/build/6151.7d1ac5707e3d0fa69758.js:8234:1633)
    at li
    at ll (http://20.75.XXX.121:3000/public/build/6151.7d1ac5707e3d0fa69758.js:8234:5291)
    at ul
    at div
    at div
    at div
    at t (http://20.75.XXX.121:3000/public/build/2449.76aaaac2ca3dc7699615.js:2:713045)
```
but the same yaml file works well in minikube.

**Relevant WCAG Criteria:** [#.#.# WCAG Criterion](link to https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)

**Environment**:
- Grafana version: latest
- Data source type & version: null
- User OS & Browser: chrome Version 105.0.5195.127
- Others: AKS version 1.23.8
