### ISSUE TITLE
Anonymous user can not silence an alert, previously could pause it.

### ISSUE THREAD

**Issue by caviliar** [grafana/grafana#55783]
**What happened**: Have updated from 8.3.x to 9.1.5 and enabled unified alerting. The anonymous user can not `silence` an alert. Previously the user would have been able to `pause` an alert.

**What you expected to happen**: That an anonymous user can create a silence for an alert.

ini file:
```
    grafana.ini:
      auth.anonymous:
        enabled: 'true'
        org_name: 'foo'
        org_role: 'Editor'
      unified_alerting:
        enabled: true
      alerting:
        enabled: false
      ...
```
![Screenshot from 2022-09-27 17-06-09](https://user-images.githubusercontent.com/3527599/192429646-a5ac172b-22c3-4176-8849-0b8b18ac690d.png)
