### ISSUE TITLE
Grafana can't handle time_intervals on root level Alertmanager data source config

### ISSUE THREAD

**Issue by splitt3r** [grafana/grafana#55842]
**What happened**:

I'm using an external Alertmanager in Grafana. After configuring the Mute / Active times via `time_intervals` on the root level Grafana shows an error message in the Unified Alerting.

See https://prometheus.io/docs/alerting/latest/configuration/:
```yaml
# DEPRECATED: use time_intervals below.
# A list of mute time intervals for muting routes.
mute_time_intervals:
  [ - <mute_time_interval> ... ]

# A list of time intervals for muting/activating routes.
time_intervals:
  [ - [<time_interval>](https://prometheus.io/docs/alerting/latest/configuration/#time_interval) ... ]
```

![image](https://user-images.githubusercontent.com/1869584/192558735-2da167a5-0fa3-4f87-9268-45609cd7e318.png)

My Alertmanager config:

```yaml
...

route:
  receiver: "mails"
  group_by: ["alertname", "job", "instance"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 24h
  routes:
    - receiver: "jira1"
      matchers:
        - ...
      mute_time_intervals:
        - maintenance
    - receiver: "jira2"
      matchers:
        - ...
      mute_time_intervals:
        - maintenance
      active_time_intervals:
        - sandbox
    - receiver: "mails"
      mute_time_intervals:
        - maintenance

...

time_intervals:
  - name: maintenance
    time_intervals:
      - weekdays: ["friday"]
        times:
          - start_time: "14:00"
            end_time: "16:00"
  - name: sandbox
    time_intervals:
      - weekdays: ["monday:friday"]
        times:
          - start_time: "08:00"
            end_time: "19:00"
```

**What you expected to happen**:

Grafana should be able to parse the valid Alertmanager configuration.

**How to reproduce it (as minimally and precisely as possible)**:

External Alertmanager wich defines root level `time_intervals` in its configuration.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.1.3
- Data source type & version: Alertmanager
- OS Grafana is installed on: Docker
- User OS & Browser: Windows
- Grafana plugins: default
- Others: -
