### ISSUE TITLE
Grafana does not respect GF_SECURITY_ADMIN variables

### ISSUE THREAD

**Issue by thameezb** [grafana/grafana#55887]
**What happened**:
Grafana does not respect the values of the `GF_SECURITY_ADMIN_USER` and `GF_SECURITY_ADMIN_PASSWORD`. And therefore does not correctly set the admin username or password 

**What you expected to happen**:
Variables are respected and admin username and password are set the values of the variables passed in

**How to reproduce it (as minimally and precisely as possible)**:
Deploy a secret into the k8s namespace (`kubectl apply -f secret.yml -n grafana`) containing base64 encoded values for keys `admin-user` and `admin-password`
secret.yml
```
apiVersion: v1
data:
  admin-password: cGFzc3dvcmQK
  admin-user: cGFzc3dvcmQK
kind: Secret
metadata:
  name: grafana-creds
type: Opaque
```

Deploy the Grafana Helm chart (`helm install grafana grafana/grafana -n grafana -f values.yml`) with values file containing 

values.yml
```
admin:
  existingSecret: "grafana-creds"
    userKey: admin-user
    passwordKey: admin-password
```

Browse to Grafana URL and attempt to login with credentials found above (`password` and `password`). Login fails 

**Anything else we need to know?**:
The reason why I bring this issue here and not as a chart level is that if I exec onto the pod, I can see that `GF_SECURITY_ADMIN_USER` and `GF_SECURITY_ADMIN_PASSWORD` is set to the correct values.

**Environment**:
- Grafana version:  v9.1.6 (92461d8d1e)
- Helm chart version: 6.36.2
- User OS & Browser: MacOS and Chrome
