### ISSUE TITLE
Error from access control system resolver not found, user token not found

### ISSUE THREAD

**Issue by yaztriumph** [grafana/grafana#56087]
Stack is `EKS`, `Route53` , `Azure AD SSO`, `Istio VirtualService`, `grafana helm chart 6.38.6`, terraform, Client VPN
Can login through Azure Ad SSO, but can't do anything else. Getting Unauthorized error, and kicking out user. 

```
service.portName = service
service.targetPort = 3000 
service.port = 3000
service.type = ClusterIP

hosts = grafana-istio.${var.aws_region}.${var.environment}.abc.int
```

Grafana config: 
```
dashboardproviders.yaml
apiVersion: 1
providers:
- disableDeletion: false
  folder: istio
  name: istio
  options:
    path: /var/lib/grafana/dashboards/istio
  orgId: 1
  type: file
- disableDeletion: false
  folder: istio
  name: istio-services
  options:
    path: /var/lib/grafana/dashboards/istio-services
  orgId: 1
  type: file

datasources.yaml
apiVersion: 1
datasources:
- access: proxy
  editable: true
  isDefault: true
  jsonData:
    timeInterval: 5s
  name: Prometheus
  orgId: 1
  type: prometheus
  url: http://prometheus-istio-server.istio-system.svc.cluster.local

download_dashboards.sh
#!/usr/bin/env sh
set -euf
mkdir -p /var/lib/grafana/dashboards/istio
mkdir -p /var/lib/grafana/dashboards/istio-services

grafana.ini
auth.cookie_samesite = strict
auth.login_cookie_name = grafana_session
auth.login_maximum_inactive_lifetime_days = 7
auth.login_maximum_lifetime_days = 30
[analytics]
check_for_updates = true
[auth.azuread]
allow_sign_up = true
allowed_groups = redacted
auth_url = https://login.microsoftonline.com/redacted/oauth2/v2.0/authorize
client_id = redacted
client_secret = redacted
enabled = true
name = Azure AD
scopes = openid email profile
token_url = https://login.microsoftonline.com/redacted/oauth2/v2.0/token
[grafana_net]
url = https://grafana.net
[log]
mode = console
[paths]
data = /var/lib/grafana/
logs = /var/log/grafana
plugins = /var/lib/grafana/plugins
provisioning = /etc/grafana/provisioning
[server]
domain = grafana-istio.us-west-2.dev.abc.int
enforce_domain = false
root_url = https://grafana-istio.us-west-2.dev.abc.int


```

grafana pod logs: 
```
msg="Failed to look up user based on cookie" error="user token not found"
level=error msg="Error from access control system" error="no resolver found"
```

```
Browser Network
Search:

Request URL: https://grafana-istio.us-west-2.dev.equipifi.int/api/search 
Request Method: GET
Status Code: 401 
Remote Address: 10.6.7.181:443
Referrer Policy: strict-origin-when-cross-origin
Home:

Request URL: https://grafana-istio.us-west-2.dev.abc.int/api/dashboards/home
Request Method: GET
Status Code: 401 
Remote Address: 10.6.7.181:443
Referrer Policy: strict-origin-when-cross-origin
Frontend-metrics:

Request URL: https://grafana-istio.us-west-2.dev.abc.int/api/frontend-metrics
Request Method: POST
Status Code: 401 
Remote Address: 10.6.7.181:443
Referrer Policy: strict-origin-when-cross-origin
```

Grafana VS
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: grafana-vs
  namespace: istio-system
spec:
  gateways:
  - gateway-gtw
  hosts:
  - grafana-istio.us-west-2.dev.abc.int
  http:
  - route:
    - destination:
        host: grafana-istio.istio-system.svc.cluster.local
        port:
          number: 3000
  ```

**Comment by BeyondEvil** [comment]
I'm seeing the same errors, but not being kicked out.

Any ideas so far?

**Comment by mgyongyosi** [comment]
Hey @yaztriumph,

`level=error msg="Error from access control system" error="no resolver found"` - it doesn't have anything to do with this error and it has been fixed already

Could you please provide more info about the problem? Grafana version number, [HAR recording](https://toolbox.googleapps.com/apps/har_analyzer/)

Could you please try changing the `cookie_samesite` setting to `none` (and `cookie_secure` to `true`) to check whether the problem is because of the cookie handling?

**Comment by Rohlik** [comment]
I also have a lots of `these errors in our `grafana.log`:
```
logger=context traceID=00000000000000000000000000000000 userId=248 orgId=1 uname=redacted@corp.com t=2022-10-11T12:38:48.77782716+02:00 level=error msg="Error from access control system" error="no resolver found"
```
Grafana 9.1.5 on Linux and Okta auth configured.

**Comment by GreenRover** [comment]
Updated now from 9.1.5 to 9.2.1 but dont see improvements

**Comment by vsile** [comment]
The same error with 9.1.6 and Keycloak.

```
27.10.2022, 09:13:30	
logger=context traceID=00000000000000000000000000000000 userId=0 orgId=0 uname= t=2022-10-27T06:13:30.143717366Z level=info msg="Request Completed" method=GET path=/login/generic_oauth status=302 remote_addr=172.31.0.12 time_ms=1 duration=1.380327ms size=324 referer= traceID=00000000000000000000000000000000 handler=/login/:name
	
27.10.2022, 09:13:30	
logger=context traceID=00000000000000000000000000000000 userId=0 orgId=0 uname= t=2022-10-27T06:13:30.127307585Z level=info msg="Request Completed" method=GET path=/login status=307 remote_addr=172.31.0.12 time_ms=7 duration=7.176252ms size=67 referer= traceID=00000000000000000000000000000000 handler=/login
	
27.10.2022, 09:13:30	
logger=context traceID=00000000000000000000000000000000 userId=0 orgId=0 uname= t=2022-10-27T06:13:30.127266022Z level=info msg="OAuth auto login enabled. Redirecting to /dashboards/login/generic_oauth"
	
27.10.2022, 09:13:30	
logger=context traceID=00000000000000000000000000000000 userId=0 orgId=0 uname= t=2022-10-27T06:13:30.126050317Z level=error msg="Error from access control system" error="no resolver found"
	
27.10.2022, 09:13:30	
logger=infra.kvstore.sql t=2022-10-27T06:13:30.125463503Z level=debug msg="kvstore value not found" orgId=0 namespace=serviceaccounts key=hideApiKeys
	
27.10.2022, 09:13:30	
logger=context traceID=00000000000000000000000000000000 userId=0 orgId=0 uname= t=2022-10-27T06:13:30.12481053Z level=error msg="Error from access control system" error="no resolver found"
	
27.10.2022, 09:13:30	
logger=context traceID=00000000000000000000000000000000 userId=0 orgId=0 uname= t=2022-10-27T06:13:30.017801619Z level=info msg="Request Completed" method=GET path=/ status=302 remote_addr=172.31.0.12 time_ms=1 duration=1.707831ms size=40 referer= traceID=00000000000000000000000000000000 handler=/
```

**Comment by cwyl02** [comment]
I saw the same error and it caused my grafana pod crash, when viewing one of my dashboard that looks at loki log datasource.

- Grafana 9.1.5 (deployed by grafana chart 6.38.1)
- grafana exposed via a traefik Ingress
   - auth managed by `traefik-forward-auth` middleware
   - TLS enabled
- datasource: Loki (`access: proxy`)

My `values.yaml` of the deployed grafana chart
```
 datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          url: "http://grafana-loki-loki-distributed-gateway"
          access: proxy
          isDefault: false
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: kommander-traefik
        ingress.kubernetes.io/auth-response-headers: X-Forwarded-User
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.middlewares: "myns-stripprefixes@kubernetescrd,myns-forwardauth@kubernetescrd"
      hosts: [""]
      path: /logging/grafana
      pathType: ImplementationSpecific
    sidecar:
      dashboards:
        enabled: true
        label: grafana_logging_dashboard
        searchNamespace: ALL
    grafana.ini:
      log:
        level: warn
      server:
        protocol: http
        enable_gzip: true
        root_url: "%(protocol)s://%(domain)s:%(http_port)s/logging/grafana"
        serve_from_sub_path: true
      auth.proxy:
        enabled: true
        header_name: X-Forwarded-User
        auto-sign-up: true
      auth.basic:
        enabled: false
      users:
        auto_assign_org_role: Admin
      plugins:
        allow_loading_unsigned_plugins: "grafana-piechart-panel"
    service:
      type: ClusterIP
      port: 3000
    resources:
      # keep request = limit to keep this container in guaranteed class
      limits:
        cpu: 300m
        memory: 100Mi
      requests:
        cpu: 200m
        memory: 100Mi
    readinessProbe:
      httpGet:
        path: /api/health
        port: 3000
        scheme: HTTP
    livenessProbe:
      httpGet:
        path: /api/health
        port: 3000
        scheme: HTTP
      initialDelaySeconds: 60
      timeoutSeconds: 30
      failureThreshold: 10
    rbac:
      pspUseAppArmor: false
      pspEnabled: false
    # to avoid needing to download any plugins at runtime, use a container and a shared volume
    # do not enable the plugins here, instead rebuild the mesosphere/grafana-plugins image with the new plugins
    plugins: []
    #  - grafana-piechart-panel
    extraEmptyDirMounts:
      - name: plugins
        mountPath: /var/lib/grafana/plugins/
    extraInitContainers:
      - name: grafana-plugins-install
        image: mesosphere/grafana-plugins:v0.0.1
        command: ["/bin/sh", "-c", "cp -a /var/lib/grafana/plugins/. /var/lib/grafana/shared-plugins/"]
        volumeMounts:
        - name: plugins
          mountPath: /var/lib/grafana/shared-plugins/
```
