### ISSUE TITLE
Grafana Query Ui Input Issue - Input moves around and queries do not work correclty!

### ISSUE THREAD

**Issue by rufreakde** [grafana/grafana#56738]
**What happened**:
We use `Image:       grafana/grafana:8.3.5`
On Input in any query field the input gets all jumbled up and moves around. It is very hard to run a query.
<img width="1698" alt="Screenshot 2022-10-11 at 16 55 37" src="https://user-images.githubusercontent.com/28104368/195126098-7eb3be67-5922-4f6f-b49a-f58a6f3fc75e.png">
Just tried to flip `(code,le)` to `(le,code)` results in:
<img width="1741" alt="Screenshot 2022-10-11 at 16 55 49" src="https://user-images.githubusercontent.com/28104368/195126213-a4222b40-d00d-4e43-a04a-1c806fb06c0f.png">

**What you expected to happen**:
Let the user type in normaly.

**How to reproduce it (as minimally and precisely as possible)**:
Actually we just installed the helm chart with argocd:
```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.teams: op-cluster-scoped
    argocd.argoproj.io/sync-wave: "50"
spec:
  project: default
  source:
    chart: loki-stack
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.6.5
    helm:
      releaseName: monitoring
      values: |
        loki:
          enabled: true
          persistence:
            enabled: true
            size: 40Gi

        promtail:
          enabled: true
          config:
            lokiAddress: http://monitoring-loki:3100/loki/api/v1/push
          pipelineStages:
          - cri: {}

        fluent-bit:
          enabled: false

        grafana:
          grafana.ini:
            users:
              viewers_can_edit: true
            auth:
              disable_login_form: false
              disable_signout_menu: false
            auth.anonymous:
              enabled: true
              org_role: Viewer
          enabled: true
          sidecar:
            datasources:
              enabled: true
              maxLines: 1000
          image:
            tag: 8.3.5

        prometheus:
          enabled: true

        filebeat:
          enabled: false

        logstash:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSync=true
```
**Anything else we need to know?**:
It worked without problems several months ago but started to do this like 1 month ago. We tried to investigate but could not find any issues?

**Environment**:
- Grafana version: `Image:       grafana/grafana:8.3.5`
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others: AWS cluster
