### ISSUE TITLE
Github login/signup is not working

### ISSUE THREAD

**Issue by marcosnils** [grafana/grafana#5683]
- **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

```
app        | t=2016-07-29T14:42:44+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=181.228.239.46 time_ns=0 size=29
app        | t=2016-07-29T14:43:05+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/github status=302 remote_addr=181.228.239.46 time_ns=0 size=244
app        | t=2016-07-29T14:43:08+0000 lvl=eror msg="login.OAuthLogin(get info from github)" logger=context userId=0 orgId=0 uname= error="Get https://api.github.com/user: oauth2: token expired and refresh token is not set"
app        | t=2016-07-29T14:43:08+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/github status=500 remote_addr=181.228.239.46 time_ns=61ns size=709
```

The GitHub API doesn't provide any refresh_tokens for OAuth (https://developer.github.com/v3/oauth/). However, the oauth2 SDK validates this here: 

https://github.com/grafana/grafana/blob/master/Godeps/_workspace/src/golang.org/x/oauth2/oauth2.go#L256-L258

Any clues?

**Comment by torkelo** [comment]
It is working when I test it here. Make sure you have specified the correct clientId and secret in config and that your github oauth has the correct redirect url and that your grafana root_url option is correct (the address should be the root address you see in browser as it is used when generating the redirect url sent to github)

**Comment by marcosnils** [comment]
hey @torkelo thx for the update. I'm still having issues with this, I'll share my steps to reproduce: 

-  Setup your OAuth app callback url to http://localhost:3000/login/github

-  Run a docker images with the following config:
```bash
docker run -i -p 3000:3000 \
  -e GF_SERVER_ROOT_URL=http://localhost:3000  \
  -e GF_SECURITY_ADMIN_PASSWORD=secret  \
  -e GF_AUTH_GITHUB_ENABLED=true \
  -e GF_AUTH_GITHUB_CLIENT_ID=<client_id> \
  -e GF_AUTH_GITHUB_SECRET=<secret> \
  -e GF_AUTH_GITHUB_SCOPES=user:email,read:org \
  -e GF_AUTH_GITHUB_ALLOW_SIGN_UP=true \
  grafana/grafana:3.1.1
```
- Try to login though the web interface and you'll get this error. 

Thx in advance.

**Comment by torkelo** [comment]
try removing `read:org` and have only `user:email`

**Comment by marcosnils** [comment]
same error.

**Comment by torkelo** [comment]
Very strange, I can replicate the error, but only in when run from docker. exact same config works fine outside docker

**Comment by marcosnils** [comment]
@torkelo maybe because the container uses an updated version of the oauth library?. Can you try updating the oauth library in your gopath?

**Comment by torkelo** [comment]
@marcosnils I tried, github oauth is working fine with the deb package, the same deb package the docker 3.1.1 image is using

**Comment by marcosnils** [comment]
@torkelo I'll help you to debug. Can you please re open the issue in the meantime? Thanks

**Comment by pnovotnak** [comment]
Just wanted to let y'all know that I'm running into this too. Docker 1.11.2, container id: 9cfaa929ff71

**Comment by zihaoyu** [comment]
Running into this too on `master` docker image. Grafana always says organization or team membership not fulfilled when I used `allowed_organizations` or `team_ids` option. I have done the following:

1. Granted access to Grafana app by organization owner.
2. Tried comma-separated team IDs.
3. Tried single word organization name.

If I remove team or org verification at all, Grafana throws a 500 error. From the log:
```
t=2016-09-08T18:16:10+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/github status=302 remote_addr=10.4.97.1 time_ns=0 size=247
t=2016-09-08T18:16:12+0000 lvl=eror msg="login.OAuthLogin(get info from github)" logger=context userId=0 orgId=0 uname= error="json: cannot unmarshal object into Go value of type []social.Record"
t=2016-09-08T18:16:12+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/github status=500 remote_addr=10.4.81.1 time_ns=1.3µs size=709
```

![screen shot 2016-09-08 at 2 16 16 pm](https://cloud.githubusercontent.com/assets/464299/18361198/ed82721e-75ce-11e6-8100-ba33cacb02bd.png)

Please look into this. Thanks.

**Comment by marcosnils** [comment]
a bag of :candy: for whoever fixes this issue :D

**Comment by torkelo** [comment]
strange, working here, are you using github enterprise or regular github?

**Comment by marcosnils** [comment]
@torkelo couple of weeks ago you said you could replicate the issue.

**Comment by torkelo** [comment]
oh, right when I used the docker image there was an issue, I remember now. Could not figure out what is different in the docker image. Bu the error then was 

"Get https://api.github.com/user: oauth2: token expired and refresh token is not set"

 and not 

"json: cannot unmarshal object into Go value of type []social.Record" which seem to be new

**Comment by marcosnils** [comment]
yeah.. not sure about @zihaoyu issue. I'm still experiencing the original issue. Haven't had time to debug yet, no time for the moment :(

**Comment by zihaoyu** [comment]
@marcosnils @torkelo 

After some debugging (by adding logging at a few places), I have found the following:

- Github Oauth can't get basic user info. The oauth client [requests `API_URL`](https://github.com/grafana/grafana/blob/master/pkg/social/github_oauth.go#L180) to get user info, but the `API_URL` is defined as `https://api.github.com` as instructed by [configuration docs](http://docs.grafana.org/installation/configuration/#authgithub).
- I have tried two workarounds and they both work.
  - Change `API_URL` to `https://api.github.com/user`.
  - Append `/user` to all Github API calls, including [user](https://github.com/grafana/grafana/blob/master/pkg/social/github_oauth.go#L180), [emails](https://github.com/grafana/grafana/blob/master/pkg/social/github_oauth.go#L93), [teams](https://github.com/grafana/grafana/blob/master/pkg/social/github_oauth.go#L122) and [orgs](https://github.com/grafana/grafana/blob/master/pkg/social/github_oauth.go#L149).

I do think the second workaround is the proper solution. Please let me know what you think.

**Comment by marcosnils** [comment]
@zihaoyu thanks for investigating and providing an easy fix. I'm not sure which is the proper way to proceed as @torkelo said that it's working for him without using docker which seems weird as it shoudln't be a URL issue.

@torkelo WDYT?

**Comment by torkelo** [comment]
the default value for the github api url is https://api.github.com/user
https://github.com/grafana/grafana/blob/master/conf/defaults.ini#L210

**Comment by marcosnils** [comment]
@zihaoyu @torkelo is correct, just tried your solution and it doesn't work. Here's how I'm running it: 

```
docker run -i -p 3000:3000 \
  -e GF_SERVER_ROOT_URL=http://localhost:3000  \
  -e GF_SECURITY_ADMIN_PASSWORD=secret  \
  -e GF_AUTH_GITHUB_ENABLED=true \
  -e GF_AUTH_GITHUB_CLIENT_ID=<client_id> \
  -e GF_AUTH_GITHUB_SECRET=<secret> \
  -e GF_AUTH_GITHUB_SCOPES=user:email,read:org \
  -e GF_AUTH_GITHUB_API_URL=https://api.github.com/user \
  -e GF_AUTH_GITHUB_ALLOW_SIGN_UP=true \
  grafana/grafana:3.1.1```

**Comment by zihaoyu** [comment]
@torkelo then can we update the documentation? It is misleading.

**Comment by zihaoyu** [comment]
@marcosnils I'm using `grafana/grafana:master` image. I have a few more env vars than you do: `GF_SERVER_DOMAIN`, `GF_AUTH_GITHUB_AUTH_URL`, `GF_AUTH_GITHUB_TOKEN_URL`, `GF_AUTH_GITHUB_ALLOWED_ORGANIZATIONS`. But other than that it's the same.

**Comment by marcosnils** [comment]
@zihaoyu can you please share your `docker run` options that you see that are working?

**Comment by zihaoyu** [comment]
@marcosnils We run Grafana in Kubernetes. Below is the `Deployment` file with some info redacted. I think you can get a similar `docker run` from it.

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: grafana
  name: grafana
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      nodeSelector:
        failure-domain.beta.kubernetes.io/zone: us-west-2c
      containers:
      - name: grafana
        image: grafana/grafana:master
        env:
          - name: GF_SERVER_DOMAIN
            value: grafana.example.com
          - name: GF_SERVER_ROOT_URL
            value: https://grafana.example.com
          - name: GF_AUTH_GITHUB_ENABLED
            value: "true"
          - name: GF_AUTH_GITHUB_CLIENT_ID
            value: ABCDEFG
          - name: GF_AUTH_GITHUB_CLIENT_SECRET
            value: ABCDEFG
          - name: GF_AUTH_GITHUB_SCOPES
            value: user:email,read:org
          - name: GF_AUTH_GITHUB_AUTH_URL
            value: https://github.com/login/oauth/authorize
          - name: GF_AUTH_GITHUB_TOKEN_URL
            value: https://github.com/login/oauth/access_token
          - name: GF_AUTH_GITHUB_API_URL
            value: https://api.github.com/user
          - name: GF_AUTH_GITHUB_ALLOW_SIGN_UP
            value: "true"
          - name: GF_AUTH_GITHUB_ALLOWED_ORGANIZATIONS
            value: ABCDEFG
          - name: GF_SMTP_ENABLED
            value: "true"
          - name: GF_SMTP_HOST
            value: "ABCDEFG"
          - name: GF_SMTP_USER
            value: "ABCDEFG"
          - name: GF_SMTP_PASSWORD
            value: "ABCDEFG"
          - name: GF_SMTP_SKIP_VERIFY
            value: "true"
          - name: GF_SMTP_FROM_ADDRESS
            value: "grafana@example.com"
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-storage
      volumes:
      - name: grafana-storage
        awsElasticBlockStore:
          volumeID: vol-########
          fsType: ext4
```
