### ISSUE TITLE
Alerting: `Alert rules` UI visible in dashboard folder management

### ISSUE THREAD

**Issue by rekor001** [grafana/grafana#56988]
**What happened**:
If i disable both alerting features the dashboard folder management page still shows the `Alert rules` tab:

![image](https://user-images.githubusercontent.com/4604194/195855599-f10fbfdf-8c59-4c6b-897c-71d23cadb452.png)

**What you expected to happen**:
Tab should be hidden

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a new dashboard folder.
2. Go inside the folder and the tab is there

Docker-Compose file:

```yaml
version: '3'

services:
  grafana:
    image: grafana/grafana:8.5.14
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: test
      GF_ALERTING_ENABLED: false
      GF_UNIFIED_ALERTING_ENABLED: false
    ports:
      - 3000:3000
 ```

**Anything else we need to know?**:
Maybe related issue: https://github.com/grafana/grafana/issues/42998

**Environment**:
- Grafana version: `8.5.14`, `9.2.0`
