### ISSUE TITLE
Explore button on panel is visible if explore function is disabled

### ISSUE THREAD

**Issue by rekor001** [grafana/grafana#56989]
**What happened**:

If the `explore` feature is disabled the `Explore` button is still visible on the panel.

![image](https://user-images.githubusercontent.com/4604194/195856807-a042c2f7-d867-440c-ac4a-c0cd32e70895.png)

Furthermore the keyboard shortcut `x` still works and redirects to:

![image](https://user-images.githubusercontent.com/4604194/195856913-85183206-a77f-4413-a88d-bc29dc11796d.png)

**What you expected to happen**:

The `Explore` button should be hidden like in Grafana 8.x

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a new dashboard
2. Add a panel
3. Explore button is available in menu

Docker-Compose file:

```yaml
version: '3'

services:
  grafana:
    image: grafana/grafana:9.2.0
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: test
      GF_EXPLORE_ENABLED: false
    ports:
      - 3000:3000
```

**Environment**:
- Grafana version: `9.2.0`
