### ISSUE TITLE
Provision - error with environment variable interpolation for notification policies

### ISSUE THREAD

**Issue by fabien-github** [grafana/grafana#58550]
**What happened**:
During provision for notifications policies, environment variable interpolation don't seems to work correcly.

**What you expected to happen**:
Follow the same pattern as others provisions endpoint and interpolate variable.

**How to reproduce it (as minimally and precisely as possible)**:
```
# cat docker-compose.yml
version: '2'
services:
  grafana_tmp:
    image: grafana/grafana-oss:9.2.4
    user: root
    volumes:
      - ./notifications_policies.yml:/etc/grafana/provisioning/alerting/notifications_policies.yml:ro
    environment:
      NOTIFIER_EMAIL_REMINDER_FREQUENCY: 4h
```

```
# cat notifications_policies.yml
apiVersion: 1

policies:
  - orgId: 1
    receiver: test
    group_by: [alertname]
    matchers:
      - alertname = test
    group_wait: 30s
    group_interval: 1m
    repeat_interval: ${NOTIFIER_EMAIL_REMINDER_FREQUENCY}
```

```
# docker-compose up
...
grafana_tmp_1  | Failed to start grafana. error: failure to parse file notifications_policies.yml: not a valid duration string: "${NOTIFIER_EMAIL_REMINDER_FREQUENCY}"
grafana_tmp_1  | failure to parse file notifications_policies.yml: not a valid duration string: "${NOTIFIER_EMAIL_REMINDER_FREQUENCY}"
root_grafana_tmp_1 exited with code 1
```

**Anything else we need to know?**:

Not sure maybe related to this PR https://github.com/grafana/grafana/pull/55666

**Environment**:
- Grafana version: 9.2.4
- Data source type & version: None
- OS Grafana is installed on: Docker
- User OS & Browser: None
- Grafana plugins: None
- Others: None
