### ISSUE TITLE
alerting no data and error handling default values not taken into account

### ISSUE THREAD

**Issue by tonypowa** [grafana/grafana#59149]
issue reported by a member of the community forum: https://community.grafana.com/t/alerting-default-configuration-not-taken-into-account/76210

**What happened**:

The default values (i.e. configuration values in grafana.ini config file) that define how Grafana handles [nodata or null values](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#nodata_or_nullvalues) (`nodata_or_nullvalues`) and [error or time out](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#error_or_timeout) (`error_or_timeout`) in alerting are not overridden (or at least not correctly) regardless this is specified in the docker-compose.yml file.

**What you expected to happen**:

When choosing the Alert evaluation behavior (Alerting > New alert rule > Alert evaluation behavior section), the values specified in the docker-compose.yml file (`error_or_timeout, nodata_or_nullvalues` ) should already appear here instead of the default values.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a initial docker-compose.yml file such as this one
```
version: "3"
services:
  grafana:
    image: grafana/grafana:latest
    user: "0"
    ports:
      - "3000:3000"
    restart: unless-stopped
```

2. Start and run the grafana app `docker-compose up -d`
3. Log in to Grafana and check the default config values in Server Admin > Settings menu. 

In this example: 
For `error_or_timeout` the default value is **alerting** 
For `nodata_or_nullvalue`, the default value is **no_data**

4. Stop the container before modifying the .yml file again with `docker compose down -d`
5. Modify the docker-compose.yml file specifying the environment variables that will override the grafana.ini file's default values for alerting. 

```
version: "3"
services:
  grafana:
    image: grafana/grafana:latest
    user: "0"
    ports:
      - "3000:3000"
    environment:
      - GF_ALERTING_ERROR_OR_TIMEOUT=keep_state
      - GF_ALERTING_NODATA_OR_NULLVALUES=alerting
    restart: unless-stopped
```

4. Start and run  again the grafana app `docker-compose up -d`
5. Log in to Grafana. 
6. Finally, go to Alerting > New alert rule > Alert evaluation behavior section. In this case, the override hasn't work (at least as it should). The override for `error_or_timeout` is `error` (this is not what was specified in the .yml file). And the override for `nodata_or_nullvalues` is `no_data` (again, this is not what was intended. Seems to have kept the default value of no_data).

**Anything else we need to know?**:

There is a difference between the docs and the UI that should be addressed too.

nodata_or_nullvalues :

    Docs : Options are alerting , no_data , keep_state , and ok . Default is no_data
    UI : Options are alerting , no_data , and ok . Default is no_data

error_or_timeout :

    Docs : Options are alerting ,keep_state . Default is alerting
    UI : Options are alerting , error , and ok . Default is error

**Environment**:
- Grafana version: latest
- OS Grafana is installed on: ubuntu
