### ISSUE TITLE
Grafana ignores timeout settings and fails at 1 minute when querying Prometheus

### ISSUE THREAD

**Issue by rdauncey53** [grafana/grafana#59287]
**What happened**:
Our Grafana instance has a Prometheus datasource set up (the endpoint is actually a Thanos query-frontend, but they are functionally the same here). We have some queries that fail with a 504 Gateway Timeout, and it looks like they are hitting a 1 minute timeout threshold, even though we have set the timeouts in every possible place that we could find - this happens every time, it isn't intermittent. [Sidenote: all queries that are under this threshold do work].
If we directly query the query-frontend endpoint, the query passes (it takes ~3 minutes), so I'm pretty sure the timeout is in Grafana somewhere.

Grafana, with developer tools tracing the query, has:
<img width="600" alt="image" src="https://user-images.githubusercontent.com/98583473/203775628-041fd465-dad5-4ce8-a16d-ea1a72965be6.png">
<img width="600" alt="image" src="https://user-images.githubusercontent.com/98583473/203775679-9233a3d6-be94-4555-b92d-192b85fb6d68.png">

**What you expected to happen**:
We have the timeout set to 5 minutes everywhere we can think to set it, so I would expect this to timeout at 5 minutes not 1 minute.

**How to reproduce it (as minimally and precisely as possible)**:
Set up a Grafana with a Prometheus datasource.
We have the following Grafana configuration (this is deployed in Kubernetes):
```
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [auth]
    disable_login_form = true
    disable_signout_menu = true
    oauth_auto_login = true
    [auth.azuread]
    allow_sign_up = true
    auth_url = [REDACTED]
    client_id = [REDACTED]
    client_secret = [REDACTED]
    enabled = true
    name = [REDACTED]
    scopes = openid email profile
    token_url = [REDACTED]
    [dashboard_previews]
    rendering_timeout = 40
    thread_count = 12
    [dataproxy]
    keep_alive_seconds = 300
    logging = true
    timeout = 300
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [metrics]
    disable_total_stats = false
    enabled = true
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /usr/share/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    root_url = [REDACTED]
```
We know that the 300s timeout is being applied in some places, because it fixed some templating timeout errors we were hitting.
Our datasources.yaml is:
```
      datasources.yaml:
        apiVersion: 1
        datasources:
        - access: proxy
          isDefault: true
          jsonData:
            customQueryParameters: timeout=300
            queryTimeout: 300s
            timeout: 300
          name: Prometheus
          type: prometheus
          url: [REDACTED - query-frontend endpoint]
```
This displays as expected in the Grafana GUI:
![image](https://user-images.githubusercontent.com/98583473/203777116-f304da75-b595-40c5-903a-8b7da2786ff1.png)

Run a large query (e.g. `topk(10, count by (__name__)({__name__=~".+"}))`).

**Anything else we need to know?**:
Our thanos query (that the thanos query-frontend communicates with) also has a 5m timeout set.

**Environment**:
- Grafana version: 8.5.9 (helm chart version 6.32.10)
- Data source type & version: Prometheus / Thanos (v0.27.0)
- OS Grafana is installed on: Azure Kubernetes Service cluster
- User OS & Browser: MS Edge
- Grafana plugins: Prometheus Alertmanager
