### ISSUE TITLE
Zooming in on Panel reveals "No Data" although data is present

### ISSUE THREAD

**Issue by noahsmindfuck** [grafana/grafana#59408]
**What happened**:
I have a docker-compose setup for Grafana + Promtail + Loki
I have a set of config files written by my software that I am reading from /var/log
I can display the data and it is shown and I love it but the resolution I can select with Grafana (e.g. 1h, 3h, 6h, ...) is not useful for the analysis I need. 
<img width="1310" alt="Screenshot 2022-11-28 at 15 39 17" src="https://user-images.githubusercontent.com/24893086/204307727-a3ad62fb-6c5e-4c8c-84a4-34645762691b.png">

So I am trying to zoom into the data but no matter how I try to access the data, any approach that is NOT selecting a time slot provided in the dropdown at the panel results in a "No Data" output.
<img width="1310" alt="Screenshot 2022-11-28 at 15 51 36" src="https://user-images.githubusercontent.com/24893086/204307866-6f0edbaa-22e0-40fd-b56e-5b89a9111a07.png">

**What you expected to happen**:
I expected to zoom into the data and see fewer data points

**How to reproduce it (as minimally and precisely as possible)**:
Load a log file into Grafana with Loki as data source.
Create a very simple query: {filename="/var/log/nf_transport_new.log"} |= ``
Add transformation to get values:
<img width="1310" alt="Screenshot 2022-11-28 at 15 48 45" src="https://user-images.githubusercontent.com/24893086/204307410-fb8386fd-1569-4472-9a68-e126501eec0c.png">

**Anything else we need to know?**:
This is the log file I am using in case that shows anything :S
[nf_transport_new.log](https://github.com/grafana/grafana/files/10104820/nf_transport_new.log)

**Environment**:
- Grafana version:     
  - image: grafana/grafana:latest
- Data source type & version:
  - image: grafana/promtail:2.4.0
  - image: grafana/loki:2.4.0
- OS Grafana is installed on: MacOS X 10.15.7 (Localhost)
- User OS & Browser: MacOS X 10.15.7 & Safari
- Grafana plugins: 
- Others:

**Comment by noahsmindfuck** [comment]
The query inspection gives the following information:
`{
  "request": {
    "url": "api/ds/query",
    "method": "POST",
    "data": {
      "queries": [
        {
          "datasource": {
            "uid": "nuAArTdVk",
            "type": "loki"
          },
          "editorMode": "builder",
          "expr": "{filename=\"/var/log/nf_transport_new.log\"} |= `` | logfmt",
          "queryType": "range",
          "refId": "A",
          "maxLines": 5000,
          "legendFormat": "",
          "datasourceId": 2,
          "intervalMs": 2000,
          "maxDataPoints": 1236
        }
      ],
      "range": {
        "from": "2022-11-28T11:59:44.084Z",
        "to": "2022-11-28T12:59:44.085Z",
        "raw": {
          "from": "now-3h",
          "to": "now-2h"
        }
      },
      "from": "1669636784084",
      "to": "1669640384085"
    },
    "hideFromInspector": false
  },
  "response": {
    "results": {
      "A": {
        "frames": [
          {
            "schema": {
              "refId": "A",
              "meta": {
                "custom": {
                  "frameType": "LabeledTimeValues"
                },
                "stats": [
                  {
                    "displayName": "Summary: bytes processed per second",
                    "unit": "Bps",
                    "value": 0
                  },
                  {
                    "displayName": "Summary: lines processed per second",
                    "value": 0
                  },
                  {
                    "displayName": "Summary: total bytes processed",
                    "unit": "decbytes",
                    "value": 0
                  },
                  {
                    "displayName": "Summary: total lines processed",
                    "value": 0
                  },
                  {
                    "displayName": "Summary: exec time",
                    "unit": "s",
                    "value": 0.00314196
                  },
                  {
                    "displayName": "Store: total chunks ref",
                    "value": 0
                  },
                  {
                    "displayName": "Store: total chunks downloaded",
                    "value": 0
                  },
                  {
                    "displayName": "Store: chunks download time",
                    "unit": "s",
                    "value": 0
                  },
                  {
                    "displayName": "Store: head chunk bytes",
                    "unit": "decbytes",
                    "value": 0
                  },
                  {
                    "displayName": "Store: head chunk lines",
                    "value": 0
                  },
                  {
                    "displayName": "Store: decompressed bytes",
                    "unit": "decbytes",
                    "value": 0
                  },
                  {
                    "displayName": "Store: decompressed lines",
                    "value": 0
                  },
                  {
                    "displayName": "Store: compressed bytes",
                    "unit": "decbytes",
                    "value": 0
                  },
                  {
                    "displayName": "Store: total duplicates",
                    "value": 0
                  },
                  {
                    "displayName": "Ingester: total reached",
                    "value": 0
                  },
                  {
                    "displayName": "Ingester: total chunks matched",
                    "value": 0
                  },
                  {
                    "displayName": "Ingester: total batches",
                    "value": 0
                  },
                  {
                    "displayName": "Ingester: total lines sent",
                    "value": 0
                  },
                  {
                    "displayName": "Ingester: head chunk bytes",
                    "unit": "decbytes",
                    "value": 0
                  },
                  {
                    "displayName": "Ingester: head chunk lines",
                    "value": 0
                  },
                  {
                    "displayName": "Ingester: decompressed bytes",
                    "unit": "decbytes",
                    "value": 0
                  },
                  {
                    "displayName": "Ingester: decompressed lines",
                    "value": 0
                  },
                  {
                    "displayName": "Ingester: compressed bytes",
                    "unit": "decbytes",
                    "value": 0
                  },
                  {
                    "displayName": "Ingester: total duplicates",
                    "value": 0
                  }
                ],
                "executedQueryString": "Expr: {filename=\"/var/log/nf_transport_new.log\"} |= `` | logfmt"
              },
              "fields": [
                {
                  "name": "labels",
                  "type": "other",
                  "typeInfo": {
                    "frame": "json.RawMessage"
                  }
                },
                {
                  "name": "Time",
                  "type": "time",
                  "typeInfo": {
                    "frame": "time.Time"
                  }
                },
                {
                  "name": "Line",
                  "type": "string",
                  "typeInfo": {
                    "frame": "string"
                  }
                },
                {
                  "name": "tsNs",
                  "type": "string",
                  "typeInfo": {
                    "frame": "string"
                  }
                },
                {
                  "name": "id",
                  "type": "string",
                  "typeInfo": {
                    "frame": "string"
                  }
                }
              ]
            },
            "data": {
              "values": [
                [],
                [],
                [],
                [],
                []
              ]
            }
          }
        ],
        "refId": "A"
      }
    }
  }
}`

**Comment by zuchka** [comment]
Thanks for creating this issue, @noahsmindfuck 

I'm having trouble reproducing on this loki panel. can you try? We'll need verifiable repro steps to move this forward as a bug. thank you!

**Comment by zuchka** [comment]
https://play.grafana.org/d/T512JVH7z/loki-nginx-service-mesh-json-version?orgId=1

**Comment by noahsmindfuck** [comment]
Ok, here's a few files:
- docker-compose.yml
```
version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.4.0
    volumes:
      - /Users/CamCom/grafana-loki/loki:/etc/loki
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.4.0
    volumes:
      - /var/log:/var/log
      - /Users/CamCom/grafana-loki/promtail:/etc/promtail
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    user: "503"
    volumes:
      - /Users/CamCom/grafana-loki/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - loki
```

- loki-config:
```
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

limits_config:
  max_query_length: 0h # Default: 721h

ruler:
  alertmanager_url: http://localhost:9093
```


- promtail config:
```
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

# local machine logs
scrape_configs:
- job_name: local
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/nf_*
```

I didn't do any additional configuration, just a plain install.
@zuchka
