### ISSUE TITLE
Influxdb datasource added using configmap  shows  error "reading InfluxDB. Status Code: 401" with Kubernetes version 1.24.x

### ISSUE THREAD

**Issue by KiranGosavi** [grafana/grafana#59783]
What happened:
After updating from k8s version 1.23.x to v 1.24.x ,  the Influxdb datasource which is added using configmap shows error " reading InfluxDB. Status Code: 401" .  

Strange enough, the same datasource configuration added manually  on Grafana dashboard using admin role works fine and does NOT show any such error . The Influxdb datasource with configmap works fine with K8s version 1.23.x.

How to reproduce it (as minimally and precisely as possible):
Add a Influxdb datasource using configmap in the K8s version 1.24.x.  

 Configmap to add Influxdb datasource

```
apiVersion: v1
kind: ConfigMap
metadata:
xxxxxx
data:
  datasource_influx.yaml: |-
    apiVersion: 1
    datasources:
    - name: InfluxDB
      type: influxdb
      access: proxy
      database: dcs
      url: http://monitoring-influxdb:8086
      basicAuth: true
      basicAuthUser: admin
      user: admin
      secureJsonData:
        password: ${admin-user-password}
        basicAuthPassword: ${admin-user-password}
```
Anything else we need to know?:
Downgrading K8s to v 1.23.x (from 1.24.x) resolved this issue.

**Environment**:
- Grafana version: 9.1.7
- Data source type & version: Influxdb 
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Chrome
- K8s version : 1.24.x
- Infludb version: v2.4.0

![image](https://user-images.githubusercontent.com/33157847/205594806-bb59a82b-0d6f-48d4-9eba-1965fc31c93e.png)
