### ISSUE TITLE
Grafana Prometheus/Cortex Datasource Doesn't Use the Right Logo

### ISSUE THREAD

**Issue by sharkymcdongles** [grafana/grafana#60683]
**What happened**:

My datasource is configured as:

```
apiVersion: 1
datasources:
- access: proxy
  isDefault: true
  jsonData:
    httpMethod: GET
    prometheusType: Cortex
    prometheusVersion: 1.14.0
  name: Cortex
  type: prometheus
  typeLogoUrl: public/app/plugins/datasource/prometheus/img/cortex_logo.svg
  typeName: cortex
  url: http://cortex-nginx/prometheus
```

However, in the GUI and API it overrides my datasource settings to be:
```
 id: 1
  uid: P6693426190CB2316
  orgId: 1
  name: Cortex
  type: prometheus
  typeName: Prometheus
  typeLogoUrl: public/app/plugins/datasource/prometheus/img/prometheus_logo.svg
  access: proxy
  url: http://cortex-nginx/prometheus
  user: ''
  database: ''
  basicAuth: false
  isDefault: true
  jsonData:
    httpMethod: GET
    prometheusType: Cortex
    prometheusVersion: 1.14.0
  readOnly: true
```

**What you expected to happen**:
I expect to see a pretty Cortex logo instead of Prometheus.

**How to reproduce it (as minimally and precisely as possible)**:
Use the same datasource settings as above.

**Environment**:
- Grafana version: [v9.3.1 (89b365f8b1)](https://github.com/grafana/grafana/blob/main/CHANGELOG.md)
- Data source type & version: Cortex 1.14
- OS Grafana is installed on: Docker Image grafana/grafana:9.3.1
- User OS & Browser: All
- Grafana plugins: Prometheus Datasource
- Others:
