### ISSUE TITLE
Cannot perform Healthcheck for Grafana via docker-compose

### ISSUE THREAD

**Issue by usmangt** [grafana/grafana#60805]
**What happened**:

As per the official [documentation](https://grafana.com/docs/grafana/v8.5/http_api/other/#health-api), we do have an API for the Grafana Health check

This works well if used in a non-containerized environment e.g VM

```
$ curl http://ip172-18-0-6-cemb/api/health && echo 'ready'
{
  "commit": "21c1d14e91",
  "database": "ok",
  "version": "9.3.2"
}ready
```

**What you expected to happen**:

Should also work when using it with docker-compose.yml

But it does not. After inspecting the docker container tells that curl is missing:

```
            "Health": {
                "Status": "starting",
                "FailingStreak": 22,
                "Log": [
                    {
                        "Start": "2022-12-28T21:56:07.587148672Z",
                        "End": "2022-12-28T21:56:07.693241842Z",
                        "ExitCode": 127,
                        "Output": "/bin/sh: curl: not found\n"
                    },
                    {
                        "Start": "2022-12-28T21:56:17.696073522Z",
                        "End": "2022-12-28T21:56:17.846120714Z",
                        "ExitCode": 127,
                        "Output": "/bin/sh: curl: not found\n"
                    },

```

**How to reproduce it (as minimally and precisely as possible)**:

Here is the sample docker-compose.yml code which I used. Also reference [example](https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck) of healthcheck from Docker website

```
version: '3.7'
services:
  grafana:
    image: "grafana/grafana-oss:latest"
    volumes:
      - 'grafana-data:/var/lib/grafana'
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f localhost:3000/api/health && echo 'ready'"]
      interval: 10s
      retries: 30
volumes:
   grafana-data: {}
```

Then run

`docker-compose up -d
`
Then examine the container using the command `docker inspect container-id` and check the **Health** section.

Even if you do a 

`docker exec -it container-id /bin/sh
`
and then try to run curl, it will give you an error that the curl command is not found.

It seems that the curl command is not included in the official image build.

The solution could be to add it so that healthcheck can work as per documentation.

**Anything else we need to know?**:

**Environment**: Docker
- Grafana version: 9.3

**Comment by zavodnyuk** [comment]
I also just tried adding health check to container, but faced same issue. Neither `wget` going to work.
I end up with checking if internal command return output about installed plugins, but never tested if this will also fail when app is down.
```
    healthcheck:
      test: ["CMD", "grafana-cli", "plugins", "ls"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
```
