### ISSUE TITLE
Glue: Add sample selector to correlations editor to enable autocomplete

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#60965]
**Requirements**

Check mock-up video in https://github.com/grafana/grafana/issues/55371

| requirement | screenshots from mock-up video |
|------|------|
| In the step where the source data source is selected we need to add a button to open the sample selector in a modal. | <img width="379" alt="Screenshot 2023-01-11 at 09 29 43" src="https://user-images.githubusercontent.com/745532/211756431-97a36eb7-ed74-443d-b756-b0f0173b095f.png"> |
| The sample selector should allow running a query and display results as a table that allows picking one row. | (1) <img width="385" alt="Screenshot 2023-01-11 at 09 29 49" src="https://user-images.githubusercontent.com/745532/211756634-c4a39165-b3ff-482a-a594-7ff73114021f.png"> (2) <img width="377" alt="Screenshot 2023-01-11 at 09 29 56" src="https://user-images.githubusercontent.com/745532/211757252-5b4af712-2ac4-4196-90a6-0d52acfdc3e6.png"> |
| The selected sample/row should be saved in the database so it's reused while editing (could be a separate PR) | - |
| The current sample should be used to display a list of available **target fields** | <img width="369" alt="Screenshot 2023-01-11 at 09 33 01" src="https://user-images.githubusercontent.com/745532/211756867-dfdd3002-ff06-4964-9b48-10205a7925ef.png"> |
| When a sample is selected autocomplete for target field is available | Target field becomes a dropdown. |
| When a sample is selected autocomplete for transformations is available | Field selectors for transformations become dropdowns and result of a transformations shows a preview (#62095) |

**Comment by gelicia** [comment]
Wanted to discuss more options around what we need for the correlation (target field) vs the sampler which is useful to arrive at the target field. There are various edge cases around saving a sample to investigate and figure out what the UI should do.

**Comment by ifrost** [comment]
Alternative approach:

* Do not add "sampler" at this stage.
* Implement #60966 with no pre-populated values, but only with inputs the user has to type in manually.
* At a later stage add "run a sample query" just to get autocomplete for the form. The source query won't be saved, sample won't be saved it will be just to get autocomplete for the currently edited item.

Here's how variable mapping could potentially look like:

Let's say target query is `"SELECT * FROM logs WHERE app=${appName} AND host=${hostName}"`

| variable | mapped to field |
|------|--------|
| appName | `[_____]` (text input) |
| hostName | `[_____]` |

Now when we add *transformations* we can add an extra column

| variable | mapped to field | transform options |
|------|--------|-----|
| appName | `[log_line]`  | `...` |
| hostName | `[log_line]` | `...` |

`transform options` will contain a dropdown with *transformation* (e.g. `logfmt`) and options (e.g. what part we want to extract, e.g. "appName" from the log line). This means we will drop the idea of creating extra fields out of the transformation and rather transform/modify the value inside the field before assigning it to a variable, which is slightly different mental model but should allow achieving the same goals with a clearer flow. 

The main difference between the mental models of the above is:
* In the current proposal: *transformation* modifies existing fields to create more fields. Later fields are assigned to variables. This means applying transformations and selecting fields are two separate config options so it can be provisioned as:

Let's say a sample source query returns a data frame with field `log_line`:

| time | log_line |
|---|----|
|...| `app=test host=001 status=ok` |

In the current proposal the transformations and mappings would be separate. Transformations would create extra fields `app`, `host` and `status` that could be used in mappings section:

```yaml
config:
  target:
    query: "SELECT * FROM logs WHERE app=${appName} AND host=${hostName}"
  transformations:
    - field: log_line
      type: logfmt
  mappings:
    - field: host
      variable: hostName
    - field: app
      variable: appName
```

If we change it a bit so the mapping and transformations go together it'd be:

```yaml
config:
  target:
    query: "SELECT * FROM logs WHERE app=${appName} AND host=${hostName}"
  mappings:
    - field: log_line
      variable: hostName
      transformations:
         - type: logfmt
           options:
             field: host
    - field: log_line
      variable: hostName
      transformations:
         - type: logfmt
           options:
            field: host
```

Which is a bit more verbose but maybe more straightforward. cc @gelicia

**Comment by gelicia** [comment]
Wondering about another example. This is assuming the correlation is a generated provisioning file where the transformation is a big regex of all possible values. This wouldn't work well UX wise but I'm trying to think of more examples outside of logs.

Source:
time | text_value
-- | --
... | This is a freetext written about Superman and Batman. This is not meant to be parseable.

```
config:
  target:
    query: "SELECT * FROM superhero WHERE name=${name}"
  mappings:
    - field: text_value
      variable: name
      transformations:
         - type: regex
           options:
             transformation: (Superman|Batman)
```

We'd run the regex against text_value and get the names as capture groups, then put in a link in the text that is a data link to the query? Would something like that work?

**Comment by ifrost** [comment]
Yes! I think that would work and it'd actually be easier to configure and more consistent with what we currently have for example in Loki. The user would extract only the value instead of extracting multiple fields with one transformation. That should be much simpler.

**Comment by gelicia** [comment]
Defining the field-level example. This is using the "USA generated data" scenario in the test datasource.

This is a simple value move from one field to a variable.

Source:
state | value
-- | --
AL | 23
NM | 30
WY | 43

```
config:
  target:
    query: "SELECT * FROM superhero WHERE name=${stateTest}"
  mappings:
    - field: state
      variable: stateTest
      transformations:
         - type: none
```

**Comment by ifrost** [comment]
> Also wondering if we could make variable optional too. In which case it would just use the field name as the variable name - so no stateTest just state. This would work for the regex example as well, where we would just use text_value instead of name in the target query. This isnt pretty but is simple from a logic standpoint and might make things easier in some cases.

Yep! I think defaulting to field name will be useful. Making explicit `none` transformation seems a bit redundant.

Now regarding extracting key-value pairs vs multiple/single value from the transformation. Here's a bit more complex example (host name contains environment handle and host id):

| field: time | field: message |
|--|--|
| ... | `app=foo host=prod-001` |
| ... | `app=bar host=demo-002` |

Imagine there's also Prometheus metrics for app that look like this: `http_requests{app="foo", env="prod"}`. Now let's provision a correlation that would run this metric:

If `logfmt` expanded key/value pairs:

```yaml
config:
  target:
    query: http_requests{app="${applicationName}", env="${environment}"}
  mappings:
    - field: message
      variable: environment
      transformations:
        - type: regexp
          options: host=(prod|demo)
    - field: message
      transformation:
        - type: logfmt
```

Regexp looks good, but how do I map "app" value from the logline to "${applicationName}"? Could be done with extra mapping at the bottom:

```yaml
config:
  target:
    query: http_requests{app="${applicationName}", env="${environment}"}
  mappings:
    - field: message
      variable: environment
      transformations:
        - type: regexp
          options: host=(prod|demo)
    - field: message
      transformation:
        - type: logfmt
    - field: app
      variable: applicationName
```

I think that would work but it starts getting a bit more complex and I think that something like this wouldn't be more straightforward and scalable:

```
config:
  target:
    query: http_requests{app="${applicationName}", env="${environment}"}
  mappings:
    - field: message
      transformations:
        - type: logfmt
          logField: app
      variable: applicationName
    - field: message
      transformations:
        - type: regexp
          regexp: host=(prod|demo)
      variable: environment
```

The logic is simple. There's a chain of input/output operations. Field value is an input. Transformations (one or many) can modify it and assign to a variable. This way it should be cleaner to combine transformations (e.g. logfmt + regexp).

But the more I think about it, the more it seems we can basically start with any approach. Backend changes would be minimal and most of the logic is in fronted anyway and should be easy to change. I'll try come up with mockups for Correlations Editor to test how adding/editing would look like with this structure.

**Comment by gelicia** [comment]
What about something like this for the above? 
```
config:
  target:
    query: http_requests{app="${applicationName}", env="${environment}"}
  transformations:
    - field: message
      type: logfmt
    - field: message
      type: regexp
      expression: host=(prod|demo)
      variable: environment
  mappings:
    - field: app
      variable: applicationName
```
