### ISSUE TITLE
Grafana-managed Notification Policies can't be provisioned in the matcher contains a "-", but can be provisioned in the UI.

### ISSUE THREAD

**Issue by joeblubaugh** [grafana/grafana#61078]
**What happened**:
When attempting to provision a notification policy in Grafana, use the following YAML:
```yaml
apiVersion: 1 
# List of notification policies 
policies: 
  - orgId: 1
    receiver: autogen-contact-point-default-email
    group_by: ["grafana_folder", "service_identifier"] 

    routes: 
      - receiver: autogen-contact-point-default-email
        matchers: 
           - service_identifier-X = myvalue 
        continue: true
```

Returns this error: 
```
     "failure parsing policies: bad matcher format: service_identifier-X = myvalue"
```

Try to create a notification policy with this matcher in the Grafana Alerting UI, and the creation will succeed.

**What you expected to happen**:
The notification policy should be provisioned via YAML and API calls.

**How to reproduce it (as minimally and precisely as possible)**:
Follow the steps in "What Happened" - no special configuration needed.

**Anything else we need to know?**:
The provisioning system uses Prometheus' validation code for notification policy matchers. In prometheus, label keys may not contain "-", but they are allowed in Grafana-managed alerting label keys. I believe this is the source of the bug.

**Environment**:
- Grafana version: v9.3.1
- Data source type & version: N/A
- OS Grafana is installed on: Linux
- User OS & Browser: macOS / Chrome
- Grafana plugins: none
