### ISSUE TITLE
Cannot reset admin password using docker-compose

### ISSUE THREAD

**Issue by usmangt** [grafana/grafana#61196]
**What happened**:
Trying to reset the grafana default password "admin" to "test123"

Went to the login page and hit refresh to be sure (already logout from any previous admin logged-in session).

Typing the new password for user admin as **test123**

Shows the message Invalid password.

**What you expected to happen**:
New login password for admin to be "test123"

**How to reproduce it (as minimally and precisely as possible)**:

This is the docker-compose.yml file

```
version: "3"
services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    user: "0"
    #user: "$UID:$GID"
    volumes:
    - /opt/grafana-plain/docker_volumes/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
```

Deploy the Grafana container using the command  `docker compose up -d`

Now all set and trying to reset the default password

docker exec -it <grafana-container-id> /bin/sh
`
Now inside the Grafana container, run the command

grafana-cli admin reset-admin-password test123
`
All **GREEN** and got no error message.

Exit from the Container

Now either,
restart the container (`docker compose restart`)
OR
stop and start the container (`docker compose down` and then `docker compose up -d`)
OR
stop the container and start again with flag --force-recreate (`docker compose up -d --force-recreate`)

Went to the login page and hit refresh to be sure (already logout from any previous admin logged-in session).

**Anything else we need to know?**:

This seems to be happening on the current latest version of Grafana [v9.3.2 (21c1d14e91)](https://github.com/grafana/grafana/blob/main/CHANGELOG.md)

While testing the same scenario on version 9.1.x works as expected

Another scenario was that I tested it initially on 9.1.x and then update the image to use the latest 9.3.2 and I simply cannot login.

**Environment**: Docker (docker compose=
- Grafana version: [v9.3.2 (21c1d14e91)](https://github.com/grafana/grafana/blob/main/CHANGELOG.md)
- Docker version 20.10.17, build 100c701
- Docker Compose version v2.6.0
