### ISSUE TITLE
"Create and manage alerting resources using file provisioning" doesn't check out

### ISSUE THREAD

**Issue by stmax82** [grafana/grafana#61317]
**I'm trying to follow the documentation on "Provision alert rules" from here without success:**
https://grafana.com/docs/grafana/v9.3/alerting/set-up/provision-alerting-resources/file-provisioning/

**Following step 1, I manually created an alert rule (and contact points,...):**
![image](https://user-images.githubusercontent.com/6381927/211873216-3781ea6c-85eb-499c-b7b0-bce3d1f2e207.png)
![image](https://user-images.githubusercontent.com/6381927/211871036-123029ac-3f13-4b00-8ed9-8cfed578ff6a.png)

**Step 2 says "Use the [Alerting provisioning API](https://grafana.com/docs/grafana/latest/developers/http_api/alerting/#get-alerts) to extract the alert rule.":**
![image](https://user-images.githubusercontent.com/6381927/211873382-8f47ac64-5e74-4bba-b31b-f698807a6f11.png)

**Which leads to the page "Alerting API":**
https://grafana.com/docs/grafana/latest/developers/http_api/alerting/#get-alerts

**For some reason this page states that "This topic is relevant for the legacy dashboard alerts only.".. ok, weird... step 2 above sent me here to "extract the alert rule" that I created in step 1:**
![image](https://user-images.githubusercontent.com/6381927/211870410-5b4f8b00-9a4e-4a88-9471-609d0f9fa4d0.png)

**What happened**:

Proceeding to call GET /api/alerts anyway, all I get is an empty list and my created alert rule doesn't show up:
![image](https://user-images.githubusercontent.com/6381927/211871217-145cb098-31d4-4b21-be10-14540ff57627.png)

**What you expected to happen**:

According to step 3 from the documentation I should be able to "Copy the contents into a YAML or JSON configuration file in the default provisioning directory"... but that's not going to work with an empty list.

**What more I tried**:

I also tried to retrieve data from the following APIs (which seem to be newer / non-legacy):

* /api/v1/provisioning/contact-points
* /api/v1/provisioning/alert-rules
* /api/v1/provisioning/policies

... then I continued at step 3 and copied the contents into the provisioning directory. But this results in errors when starting grafana:

```
Failed to start grafana. error: failure to parse file my-contact-points.json: yaml: unmarshal errors:
  line 1: cannot unmarshal !!seq into alerting.AlertingFileV1
failure to parse file my-contact-points.json: yaml: unmarshal errors:
  line 1: cannot unmarshal !!seq into alerting.AlertingFileV1
```

**Comment by mellieA** [comment]
@stmax82 it looks like we need to update these docs, thanks for letting us know! 

Were you able to find the solution or do you still need the correct steps to keep configuring your provisioned alerts & contact points?

**Comment by stmax82** [comment]
@mellieA I didn't a solution for provisioning alerting (contact points, alert rules, policies,...) in Grafana 9.3 yet. So far everything I tried (see above) failed.

We're running Grafana in Kubernetes and we're upgrading from an older version where we mounted the required files into /etc/provisioning/notifiers.

If you have any pointers on how I should proceed, please let me know.

**Comment by jgournet** [comment]
We're having the same kind of issues - hoping to get a solution via this ticket ;)

**Comment by stmax82** [comment]
So far I managed to provision a contact point by manually creating the YAML file (as described [here](https://grafana.com/docs/grafana/v9.3/alerting/set-up/provision-alerting-resources/file-provisioning/#provision-contact-points)) and putting it into the new directory /etc/grafana/provisioning/alerting.

Not sure how to provision the alert rules though.

The [docs](https://grafana.com/docs/grafana/v9.3/alerting/set-up/provision-alerting-resources/file-provisioning/#provision-alert-rules) say:

* Create an alert rule in Grafana.
  (ok, easy)
* Use the [Alerting provisioning API](https://grafana.com/docs/grafana/latest/developers/http_api/alerting/#get-alerts) to extract the alert rule.
  (The link is wrong because it points to the legacy alerting API, correct link for the new alerting API is [this](https://grafana.com/docs/grafana/latest/developers/http_api/alerting_provisioning/))
* Copy the contents into a **YAML or JSON** configuration file in the default provisioning directory

The API only generates JSON, no YAML even if I set the "Accept: application/yaml" or "Accept: application/x-yaml" header.

Putting the JSON file into the provisioning directory does not work.. seems like it wants a YAML file.

Where do I get that YAML file from? Converting the JSON 1:1 to YAML doesn't seem to fit the required format.

**Comment by tonypowa** [comment]
> Putting the JSON file into the provisioning directory does not work.. seems like it wants a YAML file.

hi @stmax82 

how did you name your configuration json file? i tried by creating a json file there with the extracted alert rule data (calling `api/v1/provisioning/alert-rules/`) and also reloading the provisioning configs via [api](https://grafana.com/docs/grafana/latest/developers/http_api/admin/#reload-provisioning-configurations) endpoint `/api/admin/provisioning/alerting/reload`, and restarting the grafana service but, no luck.  I will try using your naming. 

Also I see you are provisioning contact points. 

>`Failed to start grafana. error: failure to parse file my-contact-points.jso`

What happens if you skip that and simply provision the new alerts? 

PS:  I agree with you that the api to GET alert rule data in yaml format via api simply does not return it in yaml but in JSON  🙅 We definitely need to revise the tech docs.

**Comment by stmax82** [comment]
@tonypowa 

> how did you name your configuration json file?

The naming doesn't matter, as soon as you place any JSON files into the provisioning directory, Grafana fails. It only likes YAML.

My provisioning folder with a JSON file exported using the API api/v1/provisioning/contact-points:

![image](https://user-images.githubusercontent.com/6381927/213203647-9ea5194a-4e03-400b-bd9c-e93404a3d0db.png)

Content of mycontactpoint.json:

![image](https://user-images.githubusercontent.com/6381927/213203767-83e540f1-5cb4-43dd-80bf-696680f8b985.png)

Grafana fails while starting:

![image](https://user-images.githubusercontent.com/6381927/213204098-14f0b727-477e-433c-b839-d0ba00558d6a.png)

> What happens if you skip that and simply provision the new alerts?

Same.. neither naming nor content seems to matter. We need a YAML files to make it work.

**Comment by armandgrillet** [comment]
The link "but you can re-run it at any time using the Grafana Alerting provisioning API" goes to the legacy API instead of going to https://grafana.com/docs/grafana/latest/developers/http_api/alerting_provisioning/#route-get-alert-rule, fixing that now.

**Comment by BenjaminHerbert** [comment]
Thanks for updating the documentation.

We still have the problem: the provisioning API returns `json`, but this does not seem to be accepted. It seems like the file provisioning is only accepting `yaml`. And it is unclear how to retrieve/generate this. 

Converting the JSON from the API to YAML [does not seem to work](https://github.com/grafana/grafana/issues/61317#issuecomment-1385175632).

**Comment by santihernandezc** [comment]
Hi @stmax82, a [PR](https://github.com/grafana/grafana/pull/58623) that adds an "export" endpoint has just been merged, and the docs have been [updated](https://github.com/grafana/grafana/pull/61840) to reflect this.

**Comment by fabrice-toussaint** [comment]
The issue from @stmax82 is not only about alert rules but also about contact points, notification policies, mute timings and templates. We are currently running into the same problem as well. At this point it is only possible to download the alert rules in the YAML format but not the other settings. These still return only a JSON format and have no /export functionality. 

The docs should also be updated that they only accept YAML files and not JSON files.

**Comment by Sax388** [comment]
@santihernandezc Could you please reopen this issue as the `export` option is missing for contact points where currently provisioning fails when trying to use the JSON provided by the API.

**Comment by brendamuir** [comment]
@JohnnyQQQQ or @alexweav can you help here?

**Comment by hdong69** [comment]
Testing on Grafana v9.4.7 that does not work when using the file provisioning for contact points,....

**Comment by tedparagon** [comment]
I'm trying to do this with v9.5.2 and I think I have the correct YAML format for contact points but the documentation doesn't say where to put the file. The instruction to "Add the file(s) to your GitOps workflow, so that they deploy alongside your Grafana instance(s)." explains _how_ you might deploy the file but not _where_.

I tried placing it in `/etc/grafana/provisioning/contact-points/contact-points.yml` since that seemed as close to the legacy notifiers path. But I'm really just guessing here.

![image](https://github.com/grafana/grafana/assets/114427170/299573f0-5d97-40b1-b607-9b68b5105cb6)

**Comment by jgournet** [comment]
I did it by placing it there:
/etc/grafana/provisioning/alerting/contactpoints.yaml
and it's working (or used to work ... I still haven't finished the upgrade because of all the other pain points)

**Comment by hdong69** [comment]
Hi @jgournet Which Grafana version are you working on ?

**Comment by jgournet** [comment]
@hdong69 : 
sorry for not giving a clear answer:
on my test cluster where I'm trying to upgrade grafana from 8 to 9, I haven't pinned the version ... so looks like this setting has been working since a few months ago, and is still working on ... grafana 10.0.1 ?!?! (what ?!? I did not even realize ! :D )

**Comment by hdong69** [comment]
@jgournet that's a little bit strange...Anyways, thanks for your feedback. Btw, could you please share the compose file which was used to setup?

**Comment by jgournet** [comment]
Sorry, I cannot: we're running grafana in kubernetes, via helm chart - through prometheus stack ... which is templated via terraform
But I can send you my contactpoints.yaml file:
```
contactPoints:
  - orgId: 1
    name: slack-team1
    receivers:
      - name: Slack - team1
        type: slack
        uid: slack-team1
        org_name: Main Org.
        is_default: false
        send_reminder: true
        frequency: 3h
        settings:
          recipient: "#alerts_dev"                                                                                                                                                                                                                                 │
          username: Grafana
          uploadImage: true
          icon_url: https://seeklogo.com/images/G/grafana-logo-15BA0AFA8A-seeklogo.com.png
          token: MYTOKEN
          url: https://slack.com/api/chat.postMessage
  - orgId: 1
    name: opsgenie
    receivers:
      - name: opsgenie
        type: opsgenie
        uid: opsgenie
        org_name: Main Org.
        is_default: true
        send_reminder: true
        frequency: 3h
        settings:
          apiKey: "MYKEY"
          apiUrl: "https://api.opsgenie.com/v2/alerts"
          autoClose: true
          overridePriority: true
          uploadImage: true
policies:
  - orgId: 1
    # root policy - it is used if no routes match the alert
    receiver: opsgenie
    group_by: ['...']
    group_wait: 0s
    group_interval: 5m
    repeat_interval: 3h
    routes:
      - receiver: opsgenie-heartbeat
        group_by: ['...']
        matchers:
          - grafana_heartbeat = to_opsgenie
        group_wait: 0s
        group_interval: 5m
        repeat_interval: 1m
      - receiver: slack-team1
        group_by: ['...']
        matchers:
          - slack = team1
        group_wait: 0s
        group_interval: 5m
        repeat_interval: 3h
```
(it's heavily redacted on the fly ... so hopefully I did not add typos)
