### ISSUE TITLE
Grafana in HA mode does not deduplicate query evaluations

### ISSUE THREAD

**Issue by freeflyerme** [grafana/grafana#61512]
**What happened**:
Running Grafana in HA mode causes double the traffic to downstream metrics systems.

**What you expected to happen**:
Multiple replicas of Grafana would deduplicate alert evaluations and not multiply the load

**How to reproduce it (as minimally and precisely as possible)**:
We ran two instances of Grafana in HA mode, per official documentation [https://grafana.com/docs/grafana-cloud/alerting/set-up/configure-high-availability/]
The Grafana instances uses Prometheus as a metrics source.  

We noticed that with two Grafana instances, we have double the qps on Prometheus.  This results in double the load for downstream systems.  

Does HA configuration only deduplicate the alerts, and not the alert evaluations?  

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.3.1
- Data source type & version: Postgresql
- OS Grafana is installed on: Kubernetes, image: grafana:9.3.1-ubuntu
- User OS & Browser: any
- Grafana plugins:
- Others (configuration snippets below):

Grafana.ini snippet
```
[unified_alerting]
enabled = true
ha_listen_address = "${POD_IP}:9094"
ha_peers = "grafana-alerting.grafana:9094"
ha_advertise_address = "${POD_IP}:9094"
```

Deployment.yaml snippet
```
  containerPorts:
  - name: http
    containerPort: 3000
  - name: grafana-alert
    containerPort: 9094

  servicePorts:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  - name: grafana-alert
    port: 9094
    protocol: TCP
    targetPort: 9094
    ...
   env:
    ...
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
```

grafana-alerting-service.yaml
```
# Creates a headless service for High Availability Alerting
#  https://grafana.com/docs/grafana/latest/alerting/set-up/configure-high-availability/#enable-alerting-high-availability
apiVersion: v1
kind: Service
metadata:
  name: grafana-alerting
  namespace: grafana
  labels:
    app.kubernetes.io/name: grafana-alerting
    app.kubernetes.io/part-of: grafana
spec:
  type: ClusterIP
  clusterIP: 'None'
  ports:
    - port: 9094
  selector:
    app: grafana
```
