### ISSUE TITLE
elastic provisioning: database field not applied

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#61697]
if you have an elastic provisioning file, and apply to to main-branch grafana, the `index` datasource-field (loaded from the `database` yaml-field) is not applied.
it worked in grafana9.3.x.

after some debugging it seems it broke with this PR: https://github.com/grafana/grafana/pull/58649

the important change is the one in `store.go`, if you revert that single change in `store.go`, it starts to work again.

how to reproduce:

create a simple provisioning-yaml, like this:
```yaml
apiVersion: 1

datasources:
  - name: elastic-test
    access: proxy
    type: elasticsearch
    database: "test1"
    url: http://localhost:9200
```

load it into grafana, go to the datasource-config page for the `elastic-test` datasource, and the `index` field will be empty.
