### ISSUE TITLE
Alerting: cannot load external (datasource) Alertmanager when using Pagerduty `routing_key_file` configuration

### ISSUE THREAD

**Issue by carlosjgp** [grafana/grafana#61767]
**What happened**:

Grafana External Alertmanager added from Alertmanager (Prometheus) datasource is not compatible with PagerDuty `routing_key_file` available on Alertmanager 0.25.0

![image](https://user-images.githubusercontent.com/1277613/213442267-4702d883-8f95-47d1-83dd-01250ec9c359.png)

Grafana doesn't load anything related to the AM datasource although it's "healthy"
![image](https://user-images.githubusercontent.com/1277613/213443433-52db4088-5f7b-47e8-8774-db1ca2085458.png)

**What you expected to happen**:
Works with the latest AM version configuration options

**How to reproduce it (as minimally and precisely as possible)**:

Deploy Alertmanager chart version `0.25.0` using a receiver with a PagerDuty receiver with the access tokens on files
https://prometheus.io/docs/alerting/latest/configuration/#pagerduty_config

```yaml
      receivers:
        - name: 'pagerduty_my_service'
          pagerduty_configs:
            - send_resolved: true
              routing_key_file:  /tokens/pagerduty_my_service
```

**Anything else we need to know?**:

N/A

**Environment**:
- Grafana version: [v9.3.2 (21c1d14e91)](https://github.com/grafana/grafana/blob/main/CHANGELOG.md)
- Data source type & version: Alertmanager - Prometheus
- OS Grafana is installed on: EKS - K8s 1.22
- User OS & Browser: Ubuntu Firefox
- Grafana plugins: N/A
- Others:
