### ISSUE TITLE
Spike: investigate why Graphite queries /datasources/proxy instead of /ds/query and if there are technical details prohibiting a migration

### ISSUE THREAD

**Issue by mmandrus** [grafana/grafana#62373]
Grafana metrics has opened a task to migrate `/datasources/proxy` use in graphite to `/ds/query` https://github.com/grafana/grafana/issues/59734

However, Brendan O'Handley expressed concerns with simply doing the tech work:

"This is the first time I’ve heard of someone wanting to migrate from datasource/proxy to /ds/query, so I wonder about the context about why the proxy was there. Is the proxy an older, deprecated version of querying? Where does that happen in the backend? Can we guarantee that all the headers would be set and auth would work when migrating to ds/query? That would be my biggest concern. I think this question needs a significant amount of research so I’ll create an issue"

We've been given the go-ahead to help do this investigation.

**Comment by mecampbellsoup** [comment]
I believe this is affecting us, I've upgraded from 8.2.7 to 9.4.3 and queries to our proxied datasource via `'https://grafana.staging.coreweave.com/api/ds/query'` fail while requests to the deprecated/legacy endpoint of `'https://grafana.staging.coreweave.com/api/datasources/proxy/1/api/v1/query'` work as expected.

This is my datasource configuration:

```
datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://promforward.promforward/
          access: proxy
          editable: true
          version: 1
```
The flow is expected to be:

1. Grafana dashboard makes request to grafana backend for this data source
2. Grafana looks up the data source and sees it's configured as a proxy
3. *Including the cookie from the original request from browser*, the request is proxied to our datasource url

It doesn't seem like our cookie is being passed when hitting `/api/ds` now - is that expected?

Note the absence of any sessionid/authentication value in our HAProxy log, which is where our `promforward.promforward` ingress is managed, and it in turn sets some auth headers specific to our application and proxies to Prometheus.

```
2023-03-03T00:47:17.958028140Z 10.144.171.168:46774 [03/Mar/2023:00:47:17.898] https~ grafana-tenant-staging_grafana-tenant-staging_service/SRV_1 0/0/0/59/+59 400 +285 - - ---- 6/5/4/4/0 0/0 "POST grafana.staging.coreweave.com/api/ds/query HTTP/2.0"
```
