### ISSUE TITLE
Alerting provisioning failing on restart in Kubernetes

### ISSUE THREAD

**Issue by marthanda93** [grafana/grafana#63165]
What happened:
I want to provision alert rules (coming from K8s ConfigMaps) into Grafana running on K8s.
For first time alert rules are working and health is appearing as `OK` but as take restart to add/update rules, Grafana give constantly error: `invalid format of evaluation results for the alert definition: frame cannot uniquely be identified by its labels`
Also state of alert stay in `Pending` state.

```
          model:
            expr: up{job="otel-mtrics"} != 1
            intervalMs: 1000
            legendFormat: "{{ method }} :: {{ handler }} - {{ pod }}"
            maxDataPoints: 43200
            refId: A
```

<img width="1451" alt="image" src="https://user-images.githubusercontent.com/16935593/217723572-1de862ac-07ac-418d-98a6-d3ae30e713a1.png">

<img width="1448" alt="image" src="https://user-images.githubusercontent.com/16935593/217723388-936db62c-7f32-4b5f-aa89-9717f36f9d19.png">

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: grafanapoc
data:
  prometheus.yaml: |-
    apiVersion: 1

    deleteDatasources:
      - name: Graphite
        orgId: 1

    datasources:
      - name: Promscale-PromQL
        type: prometheus
        url: http://xxxxx:9201
        isDefault: true
        editable: true
        access: proxy
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alerting
  namespace: grafanapoc
data:
  alerting.yaml: |
    apiVersion: 1
    groups:
    - name: Engine - Error Rate
      folder: sample
      interval: 1m
      rules:
      - for: 5m
        labels:
          alertname: Engine - Error Rate
          severity: high
        annotations:
          __alertId__: '4'
          description: Elevated Error Rates Observed in "engine"
          message: Elevated Error Rates Observed in "engine"
          summary: Elevated Error Rates Observed in "engine"
        title: Engine - Error Rate
        condition: A
        data:
        - refId: A
          queryType: 'Prometheus'
          relativeTimeRange:
            from: 300
            to: 0
          datasourceUid: 'xxxxxxx'
          model:
            expr: up{job="otel-mtrics"} != 1
            intervalMs: 1000
            legendFormat: "{{ method }} :: {{ handler }} - {{ pod }}"
            maxDataPoints: 43200
            refId: A
        - refId: B
          queryType: 'Prometheus'
          relativeTimeRange:
            from: 300
            to: 0
          datasourceUid: "xxxxxxx"
          model:
            expr: up{job="kubernetes-pods"} != 0
            intervalMs: 1000
            legendFormat: "{{ method }} :: {{ handler }} - {{ pod }}"
            maxDataPoints: 43200
            refId: B
        intervalSeconds: 60
        uid: zPPjDmiVk
        version: 2
        namespace_uid: OceOdmi4k
        namespace_id: 135
        rule_group: Engine - Error Rate
        no_data_state: NoData
        exec_err_state: Alerting
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: grafanapoc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:9.3.6-ubuntu
          ports:
            - name: grafana
              containerPort: 3000
          env:
            - name: GF_AUTH_BASIC_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: Viewer
            - name: GF_LOG_LEVEL
              value: er
            - name: GF_LOG_MODE
              value: console
            - name: GF_METRICS_ENABLED
              value: "true"
            - name: GF_PLUGIN_GRAFANA_IMAGE_RENDERER_RENDERING_IGNORE_HTTPS_ERRORS
              value: "true"
          volumeMounts:
            - mountPath: /etc/grafana/provisioning/alerting/alerting.yaml
              subPath: "alerting.yaml"
              name: grafana-alerting
              readOnly: false
            - mountPath: /tmp
              name: tmp-dir
            - mountPath: /etc/grafana/provisioning/datasources
              name: grafana-datasources
              readOnly: false
      volumes:
        - name: grafana-alerting
          configMap:
            defaultMode: 420
            name: grafana-alerting
        - name : tmp-dir
          emptyDir:
            {}
        - name: grafana-datasources
          configMap:
              defaultMode: 420
              name: grafana-datasources
```
