### ISSUE TITLE
Cannot set maxLines in Loki datasource

### ISSUE THREAD

**Issue by modzilla99** [grafana/grafana#63358]
**What happened**:
When installing the Loki stack, I try to set the `maxLines` option to 5000. But that option never gets set correctly in Grafana.

![grafik](https://user-images.githubusercontent.com/32171364/218996905-59f57a11-da43-4d0c-9762-6c80ebaf790a.png)

**What you expected to happen**:
Grafana should should the option changed to 5000 or rather the value set in the datasource yaml.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy the loki stack with the following values:
```bash
helm install loki grafana/loki-stack -f values.yaml
```
```yaml
grafana:
  enabled: true
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Loki
        type: loki
        url: http://loki-headless:3100
        jsonData:
          maxLines: 5000
```

**Anything else we need to know?**:
I tried with the version provided by the stack and the newest grafana ([9.3.6](https://hub.docker.com/layers/grafana/grafana/9.3.6/images/sha256-825065ced6a481f088d53b1c42fdfb9beadce6f87a07af614be1b1a78461e2bd?context=explore) and [8.5.16](https://hub.docker.com/layers/grafana/grafana/8.5.16/images/sha256-fa3c105fe84006b307f5b6a77beb1558d2f25a28529cc642700497703e8be57d?context=explore))

**Environment**:
- Grafana version: 8.3.5
- Data source type & version: Loki
- OS Grafana is installed on: Kubernetes
- Grafana plugins: -
