### ISSUE TITLE
Loki datasource derived field configuration for URL fieldname is not filled in the GUI(query)

### ISSUE THREAD

**Issue by GNSunny** [grafana/grafana#63651]
Hi, In the newer version of grafana-9.30, for the additional data sources when adding the Loki-data source in the derived fields the url is not getting updated in the query filed in the UI
my config for additionalDatasource is 

```
  additionalDataSources:
    - name: Loki
      type: loki
      url: 'http://loki:3100'
      access: proxy
      isDefault: false
      editable: true
      jsonData:
        timeout: "300"
        derivedFields:
          - datasourceUid: tempo-datasource
            matcherRegex: "traceId=(\\w+)"
            url: '$${__value.raw}'     <<<<<------------------
            name: traceId
    - name: Tempo
      type: tempo
      uid: tempo-datasource
      url: 'http://tempo:3100'
      isDefault: false
      editable: true
```
![image](https://user-images.githubusercontent.com/2715756/220948039-f60b99ce-8acb-42bf-b3fc-1aa4c8e80926.png)

The above query field is not getting updated I have tried replacing `url: '$${__value.raw}` field with `query: '$${__value.raw}` and tried different bits but the query field from the above snapshot never gets updated. 

much appreciated, If anyone help/support with this issue, please?
