### ISSUE TITLE
Redis for Remote Cache broken

### ISSUE THREAD

**Issue by dragoangel** [grafana/grafana#64271]
**What happened**:
I configured Grafana via kube-prometheus-stack with 3 replicas, default SQLite DB LDAP and Grafana Live, Remote cache to Redis via:
```
  grafana.ini:
    server:
      domain: grafana.example.com
      protocol: http
      root_url: "https://%(domain)s/"
    auth.ldap:
      enabled: true
      allow_sign_up: true
      config_file: /etc/grafana/ldap.toml
    unified_alerting:
      ha_peers: monitoring-grafana-headless:9094
      ha_listen_address: ${POD_IP}:9094
      ha_advertise_address: ${POD_IP}:9094
    live:
      ha_engine: redis
      ha_engine_address: monitoring-grafana-redis-master.monitoring.svc.cluster.local:6379
    remote_cache:
      type: redis
      connstr: addr=monitoring-grafana-redis-master.monitoring.svc.cluster.local:6379
```
When I tried to log in I receive set-cookie with session id but no login was been done as another Grafana instance doesn't know about my session. No keys were created in Redis.

I tried different configuration combinations, like:
- using different `connstr`, e.g.:  `addr=monitoring-grafana-redis-master.monitoring.svc.cluster.local:6379,pool_size=100,db=1,ssl=false` and other combinations
- simplifying config by removing `unified_alerting` and `live` settings
- enabling `debug` logging

Logs in Grafana container don't provide any information regarding Redis connection when I get a successful login via LDAP, while the authorization attempt itself gets in the logs. There just looks like no activity at all between Grafana and Redis.

Generally idea was to use Grafana in HA mode, without persistent storage, without PSQL or MySQL database, fully configured via provisioning, with Redis for session storage.

**What you expected to happen**:
I expected that with the configuration from above after login session key will be created in Redis and authorized user can properly work with any instance of Grafana as they check session keys from Redis.

**How to reproduce it (as minimally and precisely as possible)**:
1. Configured LDAP server, secret with connection details in `grafana-monitoring-ldap-toml`
2. Install basic standalone Redis master with persistent storage, for example via Bitnami Redis Helm chart
3. Install `kube-prometheus-stack` Helm chart with Grafana configured as:
- `replicas: 2` or more
- `ingress.enabled: true` and configured
- `headlessService: true`
- `ldap.enable: true` and `ldap.existingSecret: grafana-monitoring-ldap-toml`
- `grafana.ini` section from above
4. Open web browser and navigate to Grafana ingress host
5. Login with your LDAP user credentials

**Anything else we need to know?**:
With `replicas: 1` login is working via LDAP, but Redis is still not used by Grafana at all.

**Environment**:
- Grafana version: 9.4.3
- Data source type & version: -
- OS Grafana is installed on: k8s
- User OS & Browser: any
- Grafana plugins: -
- Others: -
