### ISSUE TITLE
alert rules: UNIQUE constraint failed: dashboard.org_id, dashboard.folder_id, dashboard.title

### ISSUE THREAD

**Issue by ThomasFOC** [grafana/grafana#64525]
**What happened**:
Upgrading from version 9.1.2 we tried to upgrade to the newest version of 9.4.3. This lead to the following error:

```
Error: ✗ alert rules: UNIQUE constraint failed: dashboard.org_id, dashboard.folder_id, dashboard.title
```

This happens during startup and terminates the process. It seems to happen while parsing the provisioned files (see below).

**What you expected to happen**:
Provisioned alert rules can be read without errors after upgrading,

**How to reproduce it (as minimally and precisely as possible)**:
We've used a minimal Grafana `docker-compose.yml` setup:

```yaml
version: '3'

services:
  grafana:
    image: grafana/grafana:9.1.2
    ports:
      - "3000:3000"
    volumes:
      - /srv/docker/grafana/:/var/lib/grafana
      - ./grafana-config/:/etc/grafana/
```

We provisioned a minimal `grafana-config/provisioning/alerting/rules.yml`:

```yaml
apiVersion: 1
groups:
  - orgId: 1
    name: my_rule_group
    folder: my_first_folder
    interval: 60s
    rules:
      - uid: my_id_1
        title: my_first_rule
        condition: A
        data:
          - refId: A
            datasourceUid: '__expr__'
            model:
              conditions:
                - evaluator:
                    params:
                      - 3
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - A
                  reducer:
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: '__expr__'
              expression: 1==0
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
              type: math
        noDataState: Alerting
        for: 60s
```
This provisioned file is derived from the [documentations](https://grafana.com/docs/grafana/latest/alerting/set-up/provision-alerting-resources/file-provisioning/#provision-alert-rules).

Starting this instance leads to _no_ errors, as this works in Grafana 9.1.2 ✔️ .

After stopping the container and upgrading the version from 9.1.2 to version 9.4.3 within the `docker-compose.yml` the following error occurred on `docker logs` (some debug logging was applied via `grafana.ini`) :x: :

```
logger=provisioning.alerting t=2023-03-09T13:46:12.552109646Z level=debug msg="looking for alerting provisioning files" path=/etc/grafana/provisioning/alerting
logger=provisioning.alerting t=2023-03-09T13:46:12.552183446Z level=debug msg="parsing alerting provisioning file" path=/etc/grafana/provisioning/alerting file.Name=rules.yml
logger=provisioning.alerting t=2023-03-09T13:46:12.552635744Z level=info msg="starting to provision alerting"
logger=provisioning.alerting t=2023-03-09T13:46:12.552660944Z level=debug msg="read all alerting files" file_count=1
Error: ✗ alert rules: UNIQUE constraint failed: dashboard.org_id, dashboard.folder_id, dashboard.title
```

It seems only to happen when the provisioned alert rule existed prior to the upgrade, and only when the folder (`my_first_folder` from above) contains an alert rule.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana Version 9.1.0 as Docker image (REPOSITORY: grafana/grafana, TAG 9.4.3, IMAGE ID: 944e84f25bc7)
- OS Grafana is installed on: Docker image OS
- Grafana plugins: none

**Comment by tonypowa** [comment]
👋  hi @ThomasFOC 

Thanks for creating this issue

According  to the[ instructions](https://grafana.com/docs/grafana/latest/alerting/set-up/provision-alerting-resources/file-provisioning/#provision-alert-rules) you made reference to:

After you exported your alerts, did you remember to delete them in Grafana before provisioning via YAML file? 

What happens if you [reload your provisioning config](https://grafana.com/docs/grafana/latest/developers/http_api/admin/#reload-provisioning-configurations))? 
`POST /api/admin/provisioning/alerting/reload`  (use basic auth)

**Comment by pautiina** [comment]
Hello.
I also have this issue.
`INFO [03-16|16:39:35] Starting Grafana                         logger=settings version=9.4.3 commit=cf0a135595 branch=HEAD compiled=2023-03-02T22:28:42+02:00
`
```
ERROR[03-16|16:39:39] Failed to provision dashboard            logger=provisioning error="Failed to provision dashboards: failed to provision config dashboards: can't provision folder \"clickhouse_metrics\" from file system structure: UNIQUE constraint failed: dashboard.org_id, dashboard.folder_id, dashboard.title"
ERROR[03-16|16:39:39] Stopped background service               logger=server service=*provisioning.ProvisioningServiceImpl reason="Failed to provision dashboards: failed to provision config dashboards: can't provision folder \"clickhouse_metrics\" from file system structure: UNIQUE constraint failed: dashboard.org_id, dashboard.folder_id, dashboard.title"
INFO [03-16|16:39:39] Closing tracing                          logger=tracing
INFO [03-16|16:39:39] stopped                                  logger=ticker last_tick=2023-03-16T16:39:30+02:00
Error: ✗ *provisioning.ProvisioningServiceImpl run error: Failed to provision dashboards: failed to provision config dashboards: can't provision folder "clickhouse_metrics" from file system structure: UNIQUE constraint failed: dashboard.org_id, dashboard.folder_id, dashboard.title

```

**Comment by tonypowa** [comment]
hi @ThomasFOC  and @pautiina 

i migrated from 9.1.2 to 9.4.3 and I managed to provision the following alert rule (perhaps you can try the bellow yaml  template? I obtained it via the export button in alerting/list)

![image](https://user-images.githubusercontent.com/45235678/226302892-dca9fc98-548d-4a71-a41b-63bbc34cc570.png)


note: before upgrading, I did not have this alert , otherwise it would have probably crashed as indicated in the docs

![image](https://user-images.githubusercontent.com/45235678/226302223-4869364c-0fdb-4767-9121-48bc59c7ea30.png)


my docker-compose.yml

``` yml
version: '1'


services:
  grafana:
    image: grafana/grafana:9.4.3
    container_name: grafana
    volumes:
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./provisioning/alerting:/etc/grafana/provisioning/alerting
    restart: unless-stopped
    ports:  
      - "3000:3000"  


```

my provisioning file:

``` yaml
apiVersion: 1

groups:
    - orgId: 1
      name: test1
      folder: folder_2
      interval: 1m
      rules:
        - uid: xqhmCkf4z
          title: test1
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: 6QHzCzB4z
              model:
                datasource:
                    type: testdata
                    uid: 6QHzCzB4z
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                refId: A
            - refId: B
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 5m
          isPaused: false


```

![image](https://user-images.githubusercontent.com/45235678/226301102-07932136-2b9d-4354-9e41-4457cef6f170.png)
