### ISSUE TITLE
Error loading Alertmanager config: Missing service or routing key in PagerDuty config

### ISSUE THREAD

**Issue by PrarthiJain** [grafana/grafana#64578]
### What happened:
Configured an alert (on the prometheus alertmanager). Also added a pagerduty contact point and provided pagerduty service_key via `service_key_file`.
Error on Contact points and Notification policies - "Error loading Alertmanager config: Missing service or routing key in PagerDuty config"

### What you expected to happen:
No error in alertmanager pod logs. Prometheus alertmanager UI on grafana should work properly.

### How to reproduce it (as minimally and precisely as possible):
```

receivers:
- name: pd-test
  pagerduty_configs:
    service_key_file: /etc/vm/secrets/pd-test/pd-test-key
```

the key is mounted as an optional volume-mount:
```
    volumes:
      - name: 'pd-test'
        secret:
          secretName: 'pd-test'
          optional: true
    volumeMounts:
       - name: 'pd-test'
         mountPath: '/etc/vm/secrets/pd-test'
         readOnly: true

```
### Screenshot:
![image](https://user-images.githubusercontent.com/46317159/224194934-a9108a4f-ef67-4d79-bdc9-7b46fdbab841.png)
