### ISSUE TITLE
Grafana 9.4 dashboard provisioning not working

### ISSUE THREAD

**Issue by martinduspiva** [grafana/grafana#64595]
After upgrade on Grafana 9.4.x   provisioning of dashboards doesn't working.

I get this error

`logger=provisioning t=2023-03-10T11:44:26.104835139+01:00 level=error msg="Failed to provision dashboard" error="Failed to provision dashboards: failed to provision config bare_metal_servers_2: UNIQUE constraint failed: dashboard.org_id, dashboard.folder_id, dashboard.title"
logger=server t=2023-03-10T11:44:26.104947224+01:00 level=error msg="Stopped background service" service=*provisioning.ProvisioningServiceImpl reason="Failed to provision dashboards: failed to provision config bare_metal_servers_2: UNIQUE constraint failed: dashboard.org_id, dashboard.folder_id, dashboard.title"
logger=ticker t=2023-03-10T11:44:26.105017023+01:00 level=info msg=stopped last_tick=2023-03-10T11:44:20+01:00
logger=tracing t=2023-03-10T11:44:26.105187299+01:00 level=info msg="Closing tracing"
`

I have lot of provisoning dashboards. For example, configuration of two of them:

```
cat /etc/grafana/provisioning/dashboards/bare_metal_servers_2.yaml 
apiVersion: 1

providers:
 - name: 'bare_metal_servers_2'
   orgId: 2
   folder: 'bare_metal_servers'
   type: 'file'
   updateIntervalSeconds: 30
   options:
     path: /var/lib/grafana/dashboards/bare_metal_servers_2/

```

```
cat /etc/grafana/provisioning/dashboards/bare_metal_servers_3.yaml 

apiVersion: 1

providers:
 - name: 'bare_metal_servers_3'
   orgId: 3
   folder: 'bare_metal_servers'
   type: 'file'
   updateIntervalSeconds: 30
   options:
     path: /var/lib/grafana/dashboards/bare_metal_servers_3/

```

On the version 9.3.8 the provisioning works. I didn't find that the provisioning of dashboards changed in version 9.4.x. It's feature or bug?

**Comment by tonypowa** [comment]
hi @martinduspiva 
thanks for creating this issue

the following provisioning template worked for me okay. 


```
apiVersion: 1

providers:
 - name: 'bare_metal_servers_2'
   orgId: 1
   folder: 'folder_2'
   type: 'file'
   updateIntervalSeconds: 30
   options:
     path: /etc/grafana/provisioning/dashboards
```

how i tested it:
`
docker run  -v ./my_grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards -p 3000:3000 -e GF_LOG_MODE=console  grafana/grafana`


```
logger=provisioning.alerting t=2023-03-13T16:57:04.392625056Z level=info msg="starting to provision alerting"
logger=provisioning.alerting t=2023-03-13T16:57:04.39280853Z level=info msg="finished to provision alerting"
```

The only difference I see is that you have more than one org, in your yaml file.  I will need to test to provision for more than one org too, but could you test to provision for one org only?

**Comment by martinduspiva** [comment]
If i let provisioning dashboards for only one org ( org with id 2 ) i got same error.   The issue with provisioning is only  for some of my dashboards . If i set set origIN on 1 for this problematic dashboards  the provisioning begin work.

**Comment by dprokop** [comment]
@tonypowa I've tried to reproduce this, but it seems to be working just fine with multiple organisations (Grafana 9.4.1).

Here's my directories setup:
<img width="297" alt="image" src="https://user-images.githubusercontent.com/2376619/226342593-4ae2d219-59fe-44aa-8169-6491c1ad2491.png">


with the following provisioning files

```yaml
# first.yaml
apiVersion: 1

providers:
  - name: 'dashboards 1'
    folder: 'my folder'
    orgId: 1
    folderUid: ''
    type: file
    allowUiUpdates: false
    updateIntervalSeconds: 60
    options:
      path: /var/lib/grafana/conf/provisioning/dashboards/first
```

```yaml
# second.yaml
apiVersion: 1

providers:
  - name: 'dashboards 2'
    folder: 'my folder'
    orgId: 2
    folderUid: ''
    type: file
    allowUiUpdates: false
    updateIntervalSeconds: 60
    options:
      path: /var/lib/grafana/conf/provisioning/dashboards/second
```


I start grafana with this command:

```
docker run -e GF_PATHS_CONFIG=/var/lib/grafana/grafana.ini  -e GF_PATHS_PROVISIONING=/var/lib/grafana/conf/provisioning --volume "$PWD:/var/lib/grafana" -p 3001:3000 grafana/grafana:9.4.1 
```
