### ISSUE TITLE
Trace to log custom query not working in provisioning file

### ISSUE THREAD

**Issue by jtktam** [grafana/grafana#64659]
**What happened**:

I am configuring the data source in grafana using a provisioning file and everything works except for custom query in the "trace to log" section

**What you expected to happen**:

the use custom query should be toggled on and the query populated

**How to reproduce it (as minimally and precisely as possible)**:

```
datasources:
- name: Tempo
  type: tempo
  uid: tempo
  access: proxy
  orgId: 1
  url: http://tempo:3200
  basicAuth: false
  isDefault: false
  editable: true
  jsonData:
    httpMethod: GET
    tracesToLogs:
      datasourceUid: loki
      spanStartTimeShift: '-1h'
      spanEndTimeShift: '+1h'
      filterByTraceID: false
      filterBySpanID: false
      customQuery: true
      query: '{{exporter="OTLP"} | json | line_format "{{.body}}" | json | trace_id="${__span.traceId}" | span_id="${__span.spanId}"}'
    serviceMap:
      datasourceUid: prometheus
```
<img width="688" alt="image" src="https://user-images.githubusercontent.com/11771887/224571839-82e4daa8-6fec-4dd7-998a-938879bf4107.png">

**Anything else we need to know?**:

if i manually toggle it on and enter the query, everything works fine :) but i want to use the provisioning file since I am using docker containers

**Environment**:
- Grafana version: 

v9.3.3

<img width="294" alt="image" src="https://user-images.githubusercontent.com/11771887/224571870-c3a55857-0ef9-4d1b-9db9-06479492d2fb.png">

- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by jtktam** [comment]
https://grafana.com/docs/grafana/latest/datasources/tempo/#provision-the-data-source

i noticed that the "Use customer query" and "query" itself wasn't in the docs

but I found the keys here:

https://github.com/grafana/grafana/blob/main/public/app/core/components/TraceToLogs/TraceToLogsSettings.tsx

thinking i can just put  query?: string; and customQuery: boolean; into the jsonData section of my provisioning file?

**Comment by bjornbugge** [comment]
Hi @jtktam,

I've had success with (a variant of) the following:
```yaml
    tracesToLogsV2:
      datasourceUid: loki
      spanStartTimeShift: '-1h'
      spanEndTimeShift: '+1h'
      filterByTraceID: false
      filterBySpanID: false
      customQuery: true
      query: '{{exporter="OTLP"} | json | line_format "{{.body}}" | json | trace_id="$${__span.traceId}" | span_id="$${__span.spanId}"}'
```

Note the `tracesToLogsV2` key.  The double dollar signs are needed in my setup due to some YAML interpolation that's done when loading the ConfigMap and initializing Grafana. I've installed Grafana from the kube-prometheus-stack.

**Comment by jtktam** [comment]
Thank you @bjornbugge 

that was the missing piece.. using the "traceToLogsV2" label made it work rightaway.

thank you again

**Comment by usmangt** [comment]
Hi @bjornbugge,

Thanks for providing the solution to this issue. :+1: 

Could you please tell as where did you find this information to add `tracesToLogsV2` as I cannot find it in our Documentation so really curious to know?

**Comment by jtktam** [comment]
> Hi @bjornbugge,
> 
> Thanks for providing the solution to this issue. 👍
> 
> Could you please tell as where did you find this information to add `tracesToLogsV2` as I cannot find it in our Documentation so really curious to know?

Maybe the documentation needs to be updated? :)

**Comment by usmangt** [comment]
> > Hi @bjornbugge,
> > Thanks for providing the solution to this issue. +1
> > Could you please tell as where did you find this information to add `tracesToLogsV2` as I cannot find it in our Documentation so really curious to know?
> 
> Maybe the documentation needs to be updated? :)

Yes totally :smile: , and that is why would appreciate your feedback as I will try to get the right people to get the Docs updated.

**Comment by kroksys** [comment]
`tracesToLogsV2` customQuery works, but there is few issues with it:
- tags do not show up properly (see a video)
- ${__tags} query results in empty string

_Config from grafana data source:_
<img width="650" alt="Screenshot 2023-03-15 at 22 27 40" src="https://user-images.githubusercontent.com/15876796/225434351-60ed18d4-8a34-49f7-8692-80111f7bf2cf.png">


_Config from grafana-datasources.yaml:_
``` 
    tracesToLogsV2:
      datasourceUid: 'loki'
      spanStartTimeShift: '-10m'
      spanEndTimeShift: '10m'
      tags: ['job']
      filterByTraceID: false
      filterBySpanID: false
      customQuery: true
      query: '$${__tags} |="$${__span.traceId}"'
```

Problem with tags:
![Untitled](https://user-images.githubusercontent.com/15876796/225441266-fae6e92c-768b-412b-9c2e-869564a423fc.gif)
