### ISSUE TITLE
Allow further variable overrides in gitlab_oauth

### ISSUE THREAD

**Issue by arukiidou** [grafana/grafana#64746]
Further secure OAuth authentication with gitlab by allowing further variable overrides of gitlab_oauth

- see also
  - https://github.com/grafana/grafana/issues/64648#issuecomment-1466362388
  - https://github.com/grafana/grafana/pull/64649#issuecomment-1467150395

# Functional example

This works with custom builds, but I would like to see it natively available.

## variables

```
      GF_AUTH_GITLAB_ALLOWED_DOMAINS: example.com
      GF_AUTH_GITLAB_TLS_CLIENT_CA: /run/secrets/gitlab-cert
      GF_AUTH_GITLAB_TLS_CLIENT_CERT: /run/secrets/gitlab-cert
      GF_AUTH_GITLAB_TLS_CLIENT_KEY: /run/secrets/gitlab-key
      GF_AUTH_GITLAB_USE_PKCE: true
```

## docker　compose example

```
#################################### GitLab Auth #########################
[auth.gitlab]
#~~~~
#new
allowed_domains = example.com
tls_skip_verify_insecure = false
tls_client_cert =
tls_client_key =
tls_client_ca =
use_pkce = false

```

```Dockerfile
# syntax=docker/dockerfile:1.5

FROM grafana/grafana:9.4.3

COPY ./conf/defaults.ini /usr/share/grafana/conf/defaults.ini
```

```yaml
services:
  grafana:
    build: .
    #image: 'grafana/grafana:9.4.3'
    hostname: grafana.example.com
    restart: always
    environment:
      GF_SERVER_ROOT_URL: https://grafana.example.com
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: Grafana
      GF_AUTH_GITLAB_ENABLED: true
      GF_AUTH_GITLAB_ALLOW_SIGNUP: true
      GF_AUTH_GITLAB_CLIENT_ID: 194d59efb736621770baa45dd8a9a40689a24854fc4e99b74a869a863d8690c2
      GF_AUTH_GITLAB_CLIENT_SECRET: fce2b0c710a99cc9201d1687d9b38b7ddbb3dc4e6714a425e6bb78afcf37e599
      GF_AUTH_GITLAB_ROLE_ATTRIBUTE_PATH: is_admin && 'Admin' && 'GrafanaAdmin' || 'Viewer'
      GF_AUTH_GITLAB_SCOPES: read_user,read_api
      GF_AUTH_GITLAB_AUTH_URL:  https://gitlab.example.com/oauth/authorize
      GF_AUTH_GITLAB_TOKEN_URL: https://gitlab.example.com/oauth/token
      GF_AUTH_GITLAB_API_URL:   https://gitlab.example.com/api/v4
      GF_AUTH_GITLAB_ALLOW_ASSIGN_GRAFANA_ADMIN: true
      GF_AUTH_GITLAB_TLS_SKIP_VERIFY_INSECURE: false
      # some-secure-settings
      GF_AUTH_GITLAB_ALLOWED_DOMAINS: example.com
      GF_AUTH_GITLAB_TLS_CLIENT_CA: /run/secrets/gitlab-cert
      GF_AUTH_GITLAB_TLS_CLIENT_CERT: /run/secrets/gitlab-cert
      GF_AUTH_GITLAB_TLS_CLIENT_KEY: /run/secrets/gitlab-key
      GF_AUTH_GITLAB_USE_PKCE: true
    extra_hosts:
      - "gitlab.example.com:192.168.***.***"
    volumes:
      - grafana-config:/bin
      - grafana:/var/lib/grafana
    secrets:
      - gitlab-cert
      - gitlab-key
```

### trust self-signed cert

```
      GF_AUTH_GITLAB_TLS_SKIP_VERIFY_INSECURE: false
      GF_AUTH_GITLAB_TLS_CLIENT_CA: /run/secrets/gitlab-cert
      GF_AUTH_GITLAB_TLS_CLIENT_CERT: /run/secrets/gitlab-cert
      GF_AUTH_GITLAB_TLS_CLIENT_KEY: /run/secrets/gitlab-key
```

### enable PKCE

`GF_AUTH_GITLAB_USE_PKCE: true`

```
Started GET "/oauth/authorize?client_id=194d59efb736621770baa45dd8a9a40689a24854fc4e99b74a869a863d8690c2&code_challenge=eJmtACxjbVjm0lW-PSreMb5p_Nakys9ytKF-jrinNww&code_challenge_method=S256&redirect_uri=https%3A%2F%2Fgrafana.aruki.com%2Flogin%2Fgitlab&response_type=code&scope=read_user+read_api&state=_MKwiuf4gdQL-FfiGfpkQ9-qxYv72DX69hg3ju0_NO4%3D" for 172.19.0.2 at 2023-03-14 14:31:41 +0000
Processing by Oauth::AuthorizationsController#new as HTML
  Parameters: {"client_id"=>"194d59efb736621770baa45dd8a9a40689a24854fc4e99b74a869a863d8690c2", "code_challenge"=>"eJmtACxjbVjm0lW-PSreMb5p_Nakys9ytKF-jrinNww", "code_challenge_method"=>"S256", "redirect_uri"=>"https://grafana.aruki.com/login/gitlab", "response_type"=>"code", "scope"=>"read_user read_api", "state"=>"_MKwiuf4gdQL-FfiGfpkQ9-qxYv72DX69hg3ju0_NO4="}
  Rendered layout layouts/profile.html.haml (Duration: 604.3ms | Allocations: 254654)
Completed 200 OK in 766ms (Views: 561.3ms | ActiveRecord: 121.2ms | Elasticsearch: 0.0ms | Allocations: 273206)
```

### limits access to specific domains.(GF_AUTH_GITLAB_ALLOWED_DOMAINS)

`GF_AUTH_GITLAB_ALLOWED_DOMAINS: example.com`

![image](https://user-images.githubusercontent.com/10738333/225036796-49b15641-ec42-4351-93c3-53909c0fceed.png)

# refer

Thanks your review, I got it.
Expand a bit,I want to add trust specific self-signed certificate, add enable [PKCE](https://docs.gitlab.com/ee/api/oauth2.html#authorization-code-with-proof-key-for-code-exchange-pkce) 

- GF_AUTH_GITLAB_TLS_CLIENT_CERT
- GF_AUTH_GITLAB_TLS_CLIENT_KEY
- GF_AUTH_GITLAB_TLS_CLIENT_CA
- GF_AUTH_GITLAB_USE_PKCE

_Originally posted by @arukiidou in https://github.com/grafana/grafana/issues/64649#issuecomment-1467150395_
