### ISSUE TITLE
InfluxDB Datasource Provisioning fails to fill in `database` in Grafana 9.4 when basicAuth is used???

### ISSUE THREAD

**Issue by mman** [grafana/grafana#64761]
**What happened**:

Automatic provisioning of InfluxDB data source fails to properly fill in the `database` field under Grafana 9.4.3

**What you expected to happen**: 

Works in Grafana 9.3.8.

**How to reproduce it (as minimally and precisely as possible)**:

I have the following file: `provisioning/datasources/influxdb.yaml`

```
apiVersion: 1

datasources:
  - name: InfluxDB
    uid: datasource-influxdb
    type: influxdb
    access: proxy
    url: ${VGS_INFLUXDB_URL}
    basicAuth: true
    basicAuthUser: ${VGS_INFLUXDB_USERNAME}
    database: venus
    secureJsonData:
      basicAuthPassword: ${VGS_INFLUXDB_PASSWORD}
```

When I use that file in Grafana Docker Image 9.3.8, everything works as expected.

When I upgrade to Grafana Docker Image 9.4.3, data source is provisioned, but `database` filed is ignored.

**Anything else we need to know?**:

Nothing special, pretty standard docker setup. I think I may have discovered the bug after adding the `basicAuth`, `basicAuthUser`, and `basicAuthPassword` properties in InfluxDB provisioning file. I can not however confirm that. Looks like the bug is random.

Full code to test it would be to clone:

```
$ git clone https://github.com/mman/venus-docker-grafana-images.git
$ cd venus-docker-grafana-images
$ git checkout venus-grafana-server-2.5
$ docker compose -f docker-compose-playground.yaml up
```

And then connect to http://localhost:3000 and examine provisioned Grafana Datasources. Under 9.3.8 the InfluxDB datasource is provisioned correctly, under 9.4.3 it will lack the `database` field.

**Environment**:
- Grafana version: 9.4.3
- Data source type & version: InfluxDB
- OS Grafana is installed on: Docker
