### ISSUE TITLE
File Provisioned Notification Policy Rigidity

### ISSUE THREAD

**Issue by navinpai** [grafana/grafana#64782]
**What happened**:
I'm using the [grafana helm chart](https://github.com/grafana/helm-charts/tree/main/charts/grafana) to set up grafana, and overriding it to create some alerts, contact points and notification policies. Everything works fine. However, once Grafana comes up, I can still create new alerts via the UI and add new contact points other than the provisioned one, but can't add any routes at all to the notification policies _(The "+Add Policy" button is missing)_

#### (Notification Policy Page, completely locked out)
<img width="1379" alt="Screenshot 2023-03-15 at 4 32 50 AM" src="https://user-images.githubusercontent.com/408863/225161076-819ce1c3-ef4a-4c70-a64d-ec671939b3ee.png">

#### (Other Alert pages allow new record creation)
<img width="1322" alt="Screenshot 2023-03-15 at 4 33 39 AM" src="https://user-images.githubusercontent.com/408863/225161216-3f4245b3-45f7-4dcf-aa7b-e591eaa0a3d1.png">
<img width="1324" alt="Screenshot 2023-03-15 at 4 34 08 AM" src="https://user-images.githubusercontent.com/408863/225161274-a327a58d-73c4-4ae1-9fa9-083c598d70e4.png">

**What you expected to happen**:
Just like Contact Points and Alerts, the behaviour for Notification Policy should be _"User **cannot** edit Provisioned Policy, but **Can** create new ones"_

**How to reproduce it (as minimally and precisely as possible)**:
The config file I'm using is:

```
    alerting: 
      rules.yaml:
        apiVersion: 1
        groups:
          - orgId: 1
            name: 'my_rule_group'
            folder: my_first_folder
            interval: 60s
            rules:
              - uid: my_id_1
                title: my_first_rule
                ...
      contactpoints.yaml:
        apiVersion: 1
        contactPoints:
          - orgId: 1
            name: 'cp_1'
            receivers:
              - uid: cp_1
                type: email
                ...
      notificationpolicies.yaml:
        apiVersion: 1
        policies:
          - orgId: 1
            receiver: 'cp_1'
            routes:
              - receiver: 'cp_1'
                object_matchers:
                  - - 'type'
                    - '='
                    - 'xyz'
                group_by:
                - grafana_folder
                - alertname
                continue: true
```

**Anything else we need to know?**:

Am I missing something in this setup @JohnnyQQQQ ? This issue may be a dupe of [this issue](https://github.com/grafana/grafana/issues/55073) but I'm not sure if that was tf provisioned or file-provisioned.

**Environment**:
- Grafana version: v9.4.3 (cf0a135595)
- Data source type & version: Should not matter, but VictoriaMetrics
- OS Grafana is installed on: Linux
- User OS & Browser: OSX, Firefox
- Grafana plugins: -
- Others:

**Comment by usmangt** [comment]
Hi @navinpai,

Thanks for opening this issue.

I am not very expert with Helm Charts but I will try to get as many details here as possible.

So, I know how to deploy the helm charts via repo. But the YAML file you attached. Can you please tell me how to use it so that the settings in there get applied?

**Comment by navinpai** [comment]
Hey @usmangt 

Here's an end to end workflow to set this up:

- Create file `values.yaml` with the following content:

```
alerting: 
  rules.yaml:
    apiVersion: 1
    groups:
      - orgId: 1
        name: 'provisioned-rule-group'
        folder: provisioned-folder
        interval: 60s
        rules:
          - uid: prov-id-1
            title: prov-rule-1
            condition: B
            data:
              - refId: A
                datasourceUid: 'wdfcaFAVk'
                relativeTimeRange:
                      from: 600
                      to: 0
                model:
                  expr: "go_memstats_heap_objects{instance=\"instance-1\"}"
                  intervalMs: 1000
                  maxDataPoints: 43200
                  range: true
                  hide: false
                  legendFormat: __auto
                  refId: A                 
              - refId: B
                datasourceUid: '__expr__'
                relativeTimeRange:
                      from: 0
                      to: 0
                model:
                  conditions:
                    - evaluator:
                        params:
                          - 20000
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                          - A
                      reducer:
                        type: last
                      type: query
                  datasource:
                    type: __expr__
                    uid: '__expr__'
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: B
                  type: classic_conditions
            dashboardUid: provisioned-dashboard-1
            panelId: 123
            noDataState: Alerting
            for: 60s
            annotations:
              prov-key: provisioned-value
            labels:
              team: default-team
  contactpoints.yaml:
    apiVersion: 1
    contactPoints:
      - orgId: 1
        name: 'Default Contact Point'
        receivers:
          - uid: default-cp
            type: email
            settings:
              addresses: abc@example.com
              singleEmail: true
            disableResolveMessage: true
  notificationpolicies.yaml:
    apiVersion: 1
    policies:
      - orgId: 1
        receiver: 'grafana-default-email'
        routes:
          - receiver: 'Default Contact Point'
            object_matchers:
              - - 'type'
                - '='
                - 'provisioned'
            group_by:
            - grafana_folder
            - alertname
            continue: true
```
- `helm repo add grafana https://grafana.github.io/helm-charts`
- `helm install my-release grafana/grafana -f values.yaml`

You'll see the service and pods come up, and you can login using the user "admin" and  autoprovisioned password `kubectl get secret my-release-grafana -o jsonpath="{.data.admin-password}" | base64 --decode ; echo`

Then check "Alerts" and you'll see the same states for Notification Policies/Contact Points/Alerts and  as described above where Notification Policies is completely uneditable/unamendable but other 2 pages can have new Contact Points/Alerts created manually as well.

Do let me know if you are able to reproduce this or have any other issues. Thanks! 👍
