### ISSUE TITLE
tracesToMetrics uses exact time not a range when jumps to metrics so the graph is empty

### ISSUE THREAD

**Issue by jonatan-ivanov** [grafana/grafana#64872]
**Describe the bug**
If you setup "tracesToMetrics" and click on the Metrics link on a Span, the dashboard that will be opened will have the exact same timestamp for `From` and `To`, e.g.:
```
From: 2023-03-15 13:45:38
To:   2023-03-15 13:45:38
```

This will result in an empty panel. Though if the user will select a time range, data shows up.

**To Reproduce**
0. Setup Tempo and enable tracesToMetrics feature (see example setup below)
1. Start Tempo `2.0.1` ot `latest`
2. Open a trace, click on the metrics link of one of the spans
3. See that no data is on the rendered graph
4. Modify the time range of the dashboard, the data should show up

**Expected behavior**
Data should be visible out of the box so some kind of default time-range should be defined.

**Environment:**
 - Infrastructure: local, Docker
 - Deployment tool: Docker Compose

**Additional Context**
Example setup:
```
tracesToMetrics:
  datasourceUid: prometheus
  tags: [...]
  queries:
    - name: "Throughput"
      query: "sum(rate(http_server_requests_seconds_count{$$__tags}[$$__rate_interval]))"
```
You can find my whole setup here: [datasource.yml](https://github.com/jonatan-ivanov/teahouse/blob/7c8eacbf3f728bc07ae07b5c775bf7b91de48ee3/docker/grafana/provisioning/datasources/datasource.yml#L26-L33)
