### ISSUE TITLE
MSSQL Data Source  param 'encrypted' in provisioning config should be bool and documented

### ISSUE THREAD

**Issue by jpetzold** [grafana/grafana#64911]
**What happened**:

- I tried to provision a MSSQL Data Source as described in [Documentation](https://grafana.com/docs/grafana/latest/administration/provisioning/#data-sources)
- In the Documentation: I could not find how to set param "Encrypted"= true in provisioning config file, so I set up data source manually and retrieved settings via [api](http://localhost:3008/api/datasources):
 ```
"jsonData": {
            "connMaxLifetime": 14400,
            "connectionTimeout": 0,
            "database": "mydb",
            "encrypt": "true",
            "maxIdleConns": 2,
            "maxOpenConns": 0,
            "tlsSkipVerify": "true"
        },
``` 
- I set the params accordingly in my  datasources.yaml:
```
    jsonData:
      database: mydb
      maxOpenConns: 0 # Grafana v5.4+
      maxIdleConns: 2 # Grafana v5.4+
      connMaxLifetime: 14400 # Grafana v5.4+
      connectionTimeout: 0 # Grafana v9.3+
      encrypt: true
      tlsSkipVerify: true
``` 
- which resulted in "health check failed" after provisioning
- in order to fix that I needed to set
```
      encrypt: 'true' 
      tlsSkipVerify: true
``` 

**What you expected to happen**:

- I would have loved some documentation on how to set the params for encrypt and tlsSkipVerify  in [Documentation](https://grafana.com/docs/grafana/latest/administration/provisioning/#data-sources)
- I would have expected the correct syntax to be 'encrypt: true' instead of 'encrypt: 'true' ' in yaml file.

**How to reproduce it (as minimally and precisely as possible)**:
- provision mssql datasource through provisioning and set  encrypt: true in jsonData (see above)
- in UI go to created datasource and click on 'Test' 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.4.3
- Data source type & version: MSSQL 5.0.0 
- OS Grafana is installed on: Alpine (Official Grafana Docker Image)
- User OS & Browser: Win10 & FF
- Grafana plugins:-
- Others:-
