### ISSUE TITLE
Provisioned datasource's `database` field is missing

### ISSUE THREAD

**Issue by Vonng** [grafana/grafana#65105]
**What happened**:

Provision datasource's `database` field is missing. 

**What you expected to happen**:

The older version of grafana (e.g. 9.3.x) works as expected.

**How to reproduce it (as minimally and precisely as possible)**:

Install grafana, and use the following provisioning config:

`/etc/grafana/provisioning/datasources/pigsty.yml`

```yaml
---
apiVersion: 1

# remove provisioned data sources
deleteDatasources:
  - { name: Prometheus , orgId: 1 }
  - { name: Meta       , orgId: 1 }
  - { name: Loki       , orgId: 1 }

# install following data sources
datasources:

  # Pigsty Monitor Database (Prometheus)
  - name: Prometheus
    uid: ds-prometheus
    type: prometheus
    url: http://127.0.0.1:9090
    access: proxy
    isDefault: true
    editable: true
    version: 1
    jsonData:
      timeInterval: "2s"
      queryTimeout: "60s"
      tlsAuth: false
      tlsAuthWithCACert: false
    secureJsonData: {}

  # Pigsty Meta Database (PostgreSQL)
  - name: Meta
    type: postgres
    uid: ds-meta
    url: 127.0.0.1:5432
    access: proxy
    user: dbuser_view
    database: meta      # <------- This field is missing in grafana datasoure
    editable: true
    jsonData: {
      "connMaxLifetime": 14400,
      "maxIdleConns": 10,
      "maxOpenConns": 64,
      "postgresVersion": 1500,
      "sslmode": "require",
      "tlsAuth": false,
      "tlsAuthWithCACert": false
    }
    secureJsonData:
      password: DBUser.Viewer

  # Pigsty Logging Database (Loki)
  - name: Loki
    type: loki
    uid: ds-loki
    url: http://127.0.0.1:3100
    access: proxy
    editable: true
...
```

And if you list datasource API, you will get 

```yaml
 {'id': 2,
  'uid': 'ds-meta',
  'orgId': 1,
  'name': 'Meta',
  'type': 'postgres',
  'typeName': 'PostgreSQL',
  'typeLogoUrl': 'public/app/plugins/datasource/postgres/img/postgresql_logo.svg',
  'access': 'proxy',
  'url': '127.0.0.1:5432',
  'user': 'dbuser_view',
  'database': '',            # <-------- Problematic
  'basicAuth': False,
  'isDefault': False,
  'jsonData': {'connMaxLifetime': 14400,
   'maxIdleConns': 10,
   'maxOpenConns': 64,
   'postgresVersion': 1500,
   'sslmode': 'require',
   'tlsAuth': False,
   'tlsAuthWithCACert': False},
  'readOnly': False}
```

**Anything else we need to know?**:

check the default `/etc/grafana/provisioning/datasources/sample.yaml`

something looks wierd, like missing a filed and 'database' type is wrong (`boolean` rather than `string`). Guess may have something to do with this issue.

```yaml
# # config file version
apiVersion: 1

# # list of datasources that should be deleted from the database
#deleteDatasources:
#   - name: Graphite
#     orgId: 1

# # list of datasources to insert/update depending
# # on what's available in the database
#datasources:
#   # <string, required> name of the datasource. Required
# - name: Graphite
#   # <string, required> datasource type. Required
#   type: graphite
#   # <string, required> access mode. direct or proxy. Required
#   access: proxy
#   # <int> org id. will default to orgId 1 if not specified
#   orgId: 1
#   # <string> url
#   url: http://localhost:8080
#   # <string> database user, if used
#   user:
#   # <string> database name, if used
#   database:            # <----------- LOOKS LIKE SOMETHING WRONG HERE:
#   # <bool> enable/disable basic auth
#   basicAuth:
#   # <string> basic auth username
#   basicAuthUser:
#   # <bool> enable/disable with credentials headers
#   withCredentials:
#   # <bool> mark as default datasource. Max one per org
#   isDefault:
#   # <map> fields that will be converted to json and stored in json_data
#   jsonData:
#      graphiteVersion: "1.1"
#      tlsAuth: true
#      tlsAuthWithCACert: true
#      httpHeaderName1: "Authorization"
#   # <string> json object of data that will be encrypted.
#   secureJsonData:
#     tlsCACert: "..."
#     tlsClientCert: "..."
#     tlsClientKey: "..."
#     # <openshift\kubernetes token example>
#     httpHeaderValue1: "Bearer xf5yhfkpsnmgo"
#   version: 1
#   # <bool> allow users to edit datasources from the UI.
#   editable: false
```

**Environment**:
- Grafana version: Version 9.4.3 (commit: cf0a135595, branch: HEAD)
- Data source type & version: PostgreSQL
- OS Grafana is installed on: Rocky Linux 9.1 x86_64
- User OS & Browser: MacOS 
- Grafana plugins: N/A
- Others: N/a
