### ISSUE TITLE
Provisioning: Docs: MySQL data source provisioning doesn't work, required manual edit

### ISSUE THREAD

**Issue by jnunezgts** [grafana/grafana#65144]
**What happened**:

When you try to provision a MySQL data source using the YAML file:

```yaml
# Documentation is incorrect.
# https://grafana.com/docs/grafana/latest/datasources/mysql/
# Also password is not correctly provisioned, you need to make the data source is editable and fix it from Grafana UI.
---
apiversion: 1
deleteDatasources:
  - name: "MyDist"
datasources:
  - name: "myDS"
    type: mysql
    url: test.example.com:3306
    user: XXXX
    database: ZZZZ
    uid: "8rT3ffF66"
    jsonData:
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
    secureJsonData:
      password: XXXX
```

1. Password is not recognized. You have to manually edit the data source to make it work with the 'test' button
2. Grafana complains than the configuration file is 'deprecated':

```
logger=provisioning.datasources t=2023-03-21T17:42:13.647847333-04:00 level=warn msg="[Deprecated] the datasource provisioning config is outdated. please upgrade" filename=/etc/grafana/provisioning/datasources/mysql.yaml
```

**What you expected to happen**:

Data source to be properly provisioned without manual edits.

**Environment**:
- Grafana version: 9.2.4
- Data source type & version: MySQL
- OS Grafana is installed on: Linux, Fedora 29
- User OS & Browser: Chrome
- Grafana plugins: 5.0.0
