### ISSUE TITLE
BackendDb: Grafana postgres admin password update

### ISSUE THREAD

**Issue by dlaczeg** [grafana/grafana#65188]
**What happened**:

Admin password is not updated in Posgres DB after changing grafana config.

**What you expected to happen**:

After updating admin password db migrator should update postgres db with new admin password
 
**How to reproduce it (as minimally and precisely as possible)**:

1. connect postgres db to grafana and setup first admin password 

```yaml

  grafana:
    # Use an existing secret for the admin user.
    admin:
      userKey: admin
      passwordKey: password1
    
    grafana.ini: 
      database:
        type: postgres
        host: ${db_url}:5432
        name: grafana
        user: ${db_grafana_user}
        password: ${db_grafana_password}
        ssl_mode: require
```

2. Update password1 to password2

```yaml

  grafana:
    # Use an existing secret for the admin user.
    admin:
      userKey: admin
      passwordKey: password2
    
    grafana.ini: 
      database:
        type: postgres
        host: ${db_url}:5432
        name: grafana
        user: ${db_grafana_user}
        password: ${db_grafana_password}
        ssl_mode: require
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: v9.3.8
- Data source type & version: N/A
- OS Grafana is installed on: AKS 1.23.x + postgres 11
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others:

  - name: kube-prometheus-stack
    version: 45.7.1
