### ISSUE TITLE
grafana phlare explore profiles  lost profile type block and mutex

### ISSUE THREAD

**Issue by linuxwind** [grafana/grafana#65504]
**What happened**:
We deploy grafana phlare on kubernetes. Scrape workload’s profiles by default scrape configs.
annotations to the the pods like this:
```
metadata:
  annotations:
        profiles.grafana.com/block.port: '10000'
        profiles.grafana.com/block.scrape: 'true'
        profiles.grafana.com/cpu.port: '10000'
        profiles.grafana.com/cpu.scrape: 'true'
        profiles.grafana.com/goroutine.port: '10000'
        profiles.grafana.com/goroutine.scrape: 'true'
        profiles.grafana.com/memory.port: '10000'
        profiles.grafana.com/memory.scrape: 'true'
        profiles.grafana.com/mutex.port: '10000'
        profiles.grafana.com/mutex.scrape: 'true'
```

But When Grafana  explore profiles, the profile type only display  CPU,Memory,Goroutine. Can't find Block and Mutex type.

<img width="1856" alt="image" src="https://user-images.githubusercontent.com/1060929/228442599-2269651b-9ab7-416e-901e-a5533f25446c.png">

**Environment**:
- Grafana version: 9.4.7
- Grafana Phlare version:  0.5.3
