### ISSUE TITLE
failed to load dashboard via provisioning

### ISSUE THREAD

**Issue by double-yaya** [grafana/grafana#65521]
What happened:
I provisioned a grafana instance in k8s with prometheus. Datasources work, and stock dashboards work fine,  I use additional dashboard provider/provisioner to a new Dashboard folder, json dashboard files are empty in grafana.

```
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      allowUiUpdates: true
      editable: true
      updateIntervalSeconds: 10
      options:
        path: /var/lib/grafana/dashboards
```

[log]
mode = console 
logs:

```
t=2023-03-29T11:53:45+0000 lvl=eror msg="failed to load dashboard from " logger=provisioning.dashboard type=file name=default file=/var/lib/grafana/dashboards/cluster/Resources_Namespace.json error=EOF
t=2023-03-29T11:53:45+0000 lvl=eror msg="failed to load dashboard from " logger=provisioning.dashboard type=file name=default file=/var/lib/grafana/dashboards/cluster/pod-dashboard.json error=EOF
t=2023-03-29T11:53:45+0000 lvl=eror msg="failed to load dashboard from " logger=provisioning.dashboard type=file name=default file=/var/lib/grafana/dashboards/eslog/TI-Log-event-dashboard.json error=EOF
t=2023-03-29T11:53:45+0000 lvl=eror msg="failed to load dashboard from " logger=provisioning.dashboard type=file name=default file=/var/lib/grafana/dashboards/ti-inf/gpu-dcgm.json error=EOF
t=2023-03-29T11:53:45+0000 lvl=eror msg="failed to load dashboard from " logger=provisioning.dashboard type=file name=default file=/var/lib/grafana/dashboards/cluster/Ceph-Cluster.json error=EOF
t=2023-03-29T11:53:45+0000 lvl=eror msg="failed to load dashboard from " logger=provisioning.dashboard type=file name=default file=/var/lib/grafana/dashboards/cluster/prom-dashboard.json error=EOF
t=2023-03-29T11:53:45+0000 lvl=eror msg="failed to load dashboard from " logger=provisioning.dashboard type=file name=default file=/var/lib/grafana/dashboards/eslog/TI-k8s-log-dashboatd.json error=EOF
t=2023-03-29T11:53:45+0000 lvl=eror msg="failed to load dashboard from " logger=provisioning.dashboard type=file name=default file=/var/lib/grafana/dashboards/ti-inf/Mysql-Tables.json error=EOF
```

What you expected to happen:
auto reload dashboard to grafana ui

Anything else we need to know?:
UI error : Failed to load home dashboard
Environment:

Grafana version:8.3.3
Data source type & version:sqllite3
OS Grafana is installed on:linux
User OS & Browser:Linux + Chrome
Grafana plugins:
Others:
