### ISSUE TITLE
Session information not recorded with HTTP basic auth

### ISSUE THREAD

**Issue by jpds** [grafana/grafana#65620]
**What happened**:

I have Grafana successfully configured to use my webserver's HTTP basic auth for authentication, per the instructions at:

- https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/auth-proxy/

However I've noticed that for my users - none of the session information under the server admin section is recorded. For audit purposes - it'd be useful if Grafana could still save this information.

**Environment**:
- Grafana version: 9.3.8

**Comment by usmangt** [comment]
Hi @jpds, :wave: 

Thanks for opening this issue.


Can you please provide the steps of reproduction so that the community can also try to reproduce it on a test machine? 

OR

share a small screencast/gif file so that we can see how you are

Thanks


Thanks.

**Comment by jpds** [comment]
@usmangt Sure, I'm just using `traefik` as my frontend HTTP server with this configuration:

```
http:
  middlewares:
    grafana-auth:
      basicAuth:
        usersFile: "/usr/local/etc/traefik-users"
        headerField: "X-Webauth-User"
        removeHeader: true

    grafana-route:
      rule: "Host(`grafana.example.com`)"
      middlewares:
      - grafana-auth
      service: grafana-service
      tls:
        certResolver: lets-encr-dns
        domains:
          - main: "grafana.example.com"
      priority: 1000
      entryPoints:
        - websecure
        - websecure-quic

    grafana-service:
      loadBalancer:
        servers:
          - url: "http://10.0.0.2:3000"
        healthCheck:
          path: /api/health
          port: 3000
          interval: "9s"
          timeout: "1s"
```

`/usr/local/etc/traefik-users` simply contains the output of `htpasswd -nB user`.

In `grafana.ini`, I simply enabled:

```
#################################### Auth Proxy ##########################
[auth.proxy]
enabled = true
header_name = X-Webauth-User
header_property = username
auto_sign_up = true
```

If I log in with this basic auth, nothing is recorded in the sessions section for the user:

![image](https://user-images.githubusercontent.com/29158971/229144689-dd5ca242-472e-4e5b-92b6-470232339cf3.png)

If I create a new user and disable the HTTP auth at the `traefik` level, the session is recorded correctly:

![grafana-test1-user](https://user-images.githubusercontent.com/29158971/229145470-4bd2f01a-86b1-4cab-aba2-88f8c26df0d8.png)
