### ISSUE TITLE
Change Default Contact Point and Notification Policy Using File Provision

### ISSUE THREAD

**Issue by ullalaaron** [grafana/grafana#65768]
[Forum Thread Here](https://community.grafana.com/t/how-to-change-default-contact-point-and-notification-policy-using-file-provision/84679)

**What happened**:
Hi there!
I’m on Grafana 9 and I’d like to setup alerting file provisioning as follows:

- Contact points: remove default email received, add my custom slack contact point
- Notification policy: change root policy to use slack contact point

I have tried the following to delete the default contact point and add mine
`/alerting/contact-points.yml
`
```
deleteContactPoints:
  - uid: "" #default contact point UID

contactPoints:
  - name: slack-default
    receivers:
    - uid: slack-contact-point
      type: slack
      settings: #more stuff
```
The result is an inconsistent configuration, as the root notification policy use the default email received contact point.
Specifically the error I'm getting as Grafana starts up:

`grafana_1     | Error: ✗ contact points: change would result in an invalid configuration state: unexpected receiver (grafana-default-email) is undefined`

**What you expected to happen**:
I expect to have a way to change the default contact point in the root notification policy.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.4.7
- Data source type & version: Prometheus
- OS Grafana is installed on: Docker Container on Ubuntu 22
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by Deaddy** [comment]
I have been struggling with this as well and I think the documentation is a bit too implicit here, and my guess is that this is has also been the problem of @ullalaaron.

The default policy is *the* policy with no matchers, as it is at the root of the routing tree, so if one provisions a policy with no matchers, it will replace the default policy.
If one provisions multiple policies with no matchers, it appears that a policy with no matchers replaces[^1] the previous one, so that we end up with only one root/default policy.

That being said, the default policy also has some grouping
( `{"receiver":"grafana-default-email","group_by":["grafana_folder","alertname"]}` ),
so to only change the receiver of the default notification policy, keeping everything else the same, one can use the following yaml snippet:

```
policies:
  - receiver: <your new receiver>
    group_by:
      - 'grafana_folder'
      - 'alertname'
```

I think this could be resolved by a oneliner in the docs, e.g. "To replace the default policy, provision a policy with no matchers", but a more explicit description of the provisioning process, e.g. order of evaluation and possible overrides would probably be even nicer.

[^1]: There is somewhere a sibling setting, I have not tested what happens when using this one.
