### ISSUE TITLE
Devenv: make devenv fails with some blocks when using Docker Compose 2

### ISSUE THREAD

**Issue by xnyo** [grafana/grafana#65933]
**What happened**:

Running `make devenv` fails with some configurations starting from Docker Compose version 2.

I'm not sure about the exact version causing this issue, but I am using Docker Compose 2.17.2

```sh
╰─❯ make devenv sources=tempo           
Deleting docker-compose.yaml
Deleting .env
Adding Compose header to docker-compose.yaml
Adding docker/blocks/tempo/docker-compose.yaml to docker-compose.yaml
yaml: unmarshal errors:
  line 17: mapping key "version" already defined at line 1
  line 18: mapping key "services" already defined at line 2
make: *** [Makefile:205: devenv] Error 15
```

```sh
╭─ ~/grafana/grafana on main *13                                                                                                                 
╰─❯ docker-compose version
Docker Compose version 2.17.2

╭─ ~/grafana/grafana on main *13                                                                                                                 
╰─❯ docker version        
Client:
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.20
 Git commit:        a5ee5b1dfc
 Built:             Sat Feb 11 13:58:04 2023
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.20
  Git commit:       bc3805a0a0
  Built:            Sat Feb 11 13:58:04 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.0
  GitCommit:        1fbd70374134b891f97ce19c70b6e50c7b9f4e0d.m
 runc:
  Version:          1.1.4
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

It seems that the configuration that explicitly specify `version` and/or `services` are affected by this:

- tempo
- auth/freeipa
- traefik
- ha-test-unified-alerting
- ha_test
- local-npm

This is because `devenv/create_docker_compose.sh` generates the `docker-compose` file by:

1. Copying `devenv/docker/compose_header.yml` into `docker-compose.yaml`

2. Appending any specified blocks to it

And since `compose_header.yml` is defined as:

```yml
version: "3.4"
services:

```

any blocks that re-define the `services` key (like [tempo](https://github.com/grafana/grafana/blob/42be20cbf3773c109a6f3f00033b17068e590fb2/devenv/docker/blocks/tempo/docker-compose.yaml#L15-L16)) instead of specifying the services directly (like [prometheus](https://github.com/grafana/grafana/blob/42be20cbf3773c109a6f3f00033b17068e590fb2/devenv/docker/blocks/prometheus/docker-compose.yaml)), cause a duplicate key, and this is not accepted by docker compose v2.

For example, the generated file with `make devenv sources=tempo` looks like this:

```yml
version: "3.4"
services:
x-logging: &default-logging
  driver: loki
  options:
    loki-url: 'http://localhost:3100/api/prom/push'
    labels: namespace
    loki-relabel-config: |
      - action: replace
        source_labels: ["namespace","compose_service"]
        separator: "/"
        target_label: job
      - action: replace
        source_labels: ["container_name"]
        target_label: instance

version: "3"
services:

  db:
    image: grafana/tns-db:9c1ab38
    command:
      - '-log.level=debug'
    ports:
      - 0.0.0.0:8000:80
    environment:
      JAEGER_ENDPOINT: 'http://tempo:14268/api/traces'
      JAEGER_TAGS: job=tns/db
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    labels:
      namespace: tns
    logging: *default-logging

  app:
    image: grafana/tns-app:9c1ab38
    command:
      - '-log.level=debug'
      - 'http://db'
    links:
      - db
    ports:
      - 0.0.0.0:8001:80
    environment:
      JAEGER_ENDPOINT: 'http://tempo:14268/api/traces'
      JAEGER_TAGS: job=tns/app
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    labels:
      namespace: tns
    logging: *default-logging

  loadgen:
    image: grafana/tns-loadgen:9c1ab38
    command:
      - '-log.level=debug'
      - 'http://app'
    links:
      - app
    ports:
      - 0.0.0.0:8002:80
    environment:
      JAEGER_ENDPOINT: 'http://tempo:14268/api/traces'
      JAEGER_TAGS: job=tns/loadgen
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    labels:
      namespace: tns
    logging: *default-logging

  tempo:
    image: grafana/tempo:main-9a8474f
    command:
      - --config.file=/etc/tempo.yaml
      - --search.enabled=true
    volumes:
      - ./docker/blocks/tempo/tempo.yaml:/etc/tempo.yaml
      - ./docker/blocks/tempo/tempo-data:/tmp/tempo
    ports:
      - "14268:14268"  # jaeger ingest
      - "3200:3200"   # tempo
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./docker/blocks/tempo/prometheus.yaml:/etc/prometheus.yaml
    links:
      - app
      - db
      - loadgen
    ports:
      - "9090:9090"
    labels:
      namespace: monitoring
    logging: *default-logging

  loki:
    image: grafana/loki:main
    command:
      - -config.file=/etc/loki/local-config.yaml
      - -table-manager.retention-period=1d
      - -table-manager.retention-deletes-enabled=true
    ports:
      - "3100:3100"
    labels:
      namespace: monitoring
    logging: *default-logging
```

The keys `version` and `services` are present twice.

**What you expected to happen**:

The devenv should be created correctly and it should be able to start with Docker Compose 2

**How to reproduce it (as minimally and precisely as possible)**:

```sh
╭─ ~/grafana/grafana on main *13                                                                                                                 
╰─❯ docker-compose version       
Docker Compose version 2.17.2

╭─ ~/grafana/grafana on main *13                                                                                                                 
╰─❯ make devenv sources=tempo     
Adding Compose header to docker-compose.yaml
Adding docker/blocks/tempo/docker-compose.yaml to docker-compose.yaml
yaml: unmarshal errors:
  line 17: mapping key "version" already defined at line 1
  line 18: mapping key "services" already defined at line 2
make: *** [Makefile:205: devenv] Error 15
```

Instead, with prometheus:

```sh
╭─ ~/grafana/grafana on main *13                                                                                                                 
╰─❯ make devenv sources=prometheus
Adding Compose header to docker-compose.yaml
Adding docker/blocks/prometheus/docker-compose.yaml to docker-compose.yaml
[+] Building 0.0s (0/1)                                                                                                                           
[+] Building 0.1s (9/9) FINISHED
...[redacted, env is created and started correctly]...
```

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:
