### ISSUE TITLE
InfluxDBv1 Datasource Provisioning via File does not set the database value for v9.4.x

### ISSUE THREAD

**Issue by shantanoo-desai** [grafana/grafana#66316]
**What happened**:
When trying to provision datasources especially `InfluxDBv1` with a predefined `datasources.yml` file and mounting it via Docker into a Grafana OSS 9.4.7 container the `database` parameter is not set.

[Kooha-2023-04-11-20-36-20.webm](https://user-images.githubusercontent.com/12070966/231259336-56238a61-65dc-4d40-ba5b-7d5bee956d7a.webm)

### Files
`datasources.yml`

```yaml
apiVersion: 1

datasources:
  - name: Komponist-InfluxDBv1
    type: influxdb
    access: proxy
    database: komponistdb
    user: rw_user
    url: http://komponist_influxdbv1:8086
    jsonData:
      httpMode: GET
    secureJsonData:
      password: test
    editable: true

  - name: Komponist-InfluxDBv2
    type: influxdb
    access: proxy
    url: http://komponist_influxdbv2:8087
    jsonData:
      version: Flux
      organization: komponistorg
      defaultBucket: komponistdb
      tlsSkipVerify: true
    secureJsonData:
      token: testToken
    editable: true

````

**What you expected to happen**:

The Database value should be set for the `InfluxDBv1`

**How to reproduce it (as minimally and precisely as possible)**:

This [Repository](https://github.com/shantanoo-desai/grafana-datasources-bug) provides a basic reproducible example of how to reproduce this bug.

Requirements: Docker v23.0.1 and Docker Compose Version: 2.17.2

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.4.7
- Data source type & version: InfluxDBv1
- OS Grafana is installed on: Linux
- User OS & Browser: Mozilla Firefox
- Grafana plugins: N/A
- Others:
