### ISSUE TITLE
Grafana does not save data when docker host volumes are used

### ISSUE THREAD

**Issue by blade1989** [grafana/grafana#66423]
**What happened**:

When using docker compose with host volumes, the data are not created in the host folders

```yaml
services:
      
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname:  grafana
    restart: always

    user: '1001'

    environment:
      TZ: Europe/Amsterdam
      UID: 1001
      GID: 1001
    volumes:
      - /data/grafana/data:/var/lib/grafana
      - /data/grafana/conf:/etc/grafana
      - /data/grafana/logs:/var/log/grafana
      - /data/grafana/share:/usr/share/grafana

    ports:
      - "3000:3000"
```

But, when running `docker compose up -d` I get the following error:

```bash
grafana  | GF_PATHS_CONFIG='/etc/grafana/grafana.ini' is not readable.
grafana  | GF_PATHS_DATA='/var/lib/grafana' is not writable.
grafana  | You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migrate-to-v51-or-later
grafana  | mkdir: can't create directory '/var/lib/grafana/plugins': Permission denied
grafana  | GF_PATHS_CONFIG='/etc/grafana/grafana.ini' is not readable.
grafana  | GF_PATHS_DATA='/var/lib/grafana' is not writable.
grafana  | You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migrate-to-v51-or-later
grafana  | mkdir: can't create directory '/var/lib/grafana/plugins': Permission denied
```

I changed the directories with `chown -R 472:0` and `user: '1001'`  was added to the compose file, but no luck.

**What you expected to happen**:

For the files in `/etc/grafana` to be accessible on my host server, in the directory: `/data/grafana/conf`

I want all those files accessible so that I can back them up.

**How to reproduce it (as minimally and precisely as possible)**:

Run on Ubuntu 22.04 with the above compose file.

**Anything else we need to know?**:

**Environment**:
- Grafana version:  docker image: grafana/grafana:latest
- Data source type & version:
- OS Grafana is installed on: Ubuntu 22.04
- User OS & Browser: Linux Ubuntu 22.04 (Desktop) Firefox 112
- Grafana plugins: None
- Others: docker version 23.0.3

```[tasklist]
```

**Comment by tonypowa** [comment]
hi @blade1989 
thank you for creating this issue

>volumes:
>      - /data/grafana/data:/var/lib/grafana

`chown 472:root ./data/. `This should allow Grafana to persist its data and survive a restart.

**Comment by blade1989** [comment]
Hey @tonypowa , 

Thanks for the feed back. I executed the above `chown` command for the `/data/` folder and later on also for the `conf/`,`logs/`, and  `share/` folder, but no luck.

Also,after a few attempt I tried it on the `/data/apps/grafana` folder, but no luck.

It kinda looked like the data is not synced from the grafana image to the host. 

I tried copying grafana data from a server, where grafana was installed natively, but that didn't work either.

I got the image up and running with named volumes, and copied all of the grafana directories into my host docker volumes, removed all the container, and `docker compose up -d` again, now it seems to work, in a very roundabout way.


Any suggestions to get it to work at the fist `docker compose up -d`?

**Comment by tonypowa** [comment]
can you try the same but using `docker compose` as the *root* user ?

* few details about my environment:

- my minimal docker-compose.yml

``` yml
version: '1'

services:
  grafana:
    image: grafana/grafana:9.4.3
    container_name: grafana
    volumes:
      - ./data/:/var/lib/grafana # persist Grafana database
    restart: unless-stopped
    ports:  
      - "3000:3000"
```

- create an empty folder where your docker-compose.yml is .In my case: `mkdir ./data`  to match the volume declared in the docker file

- `chown 472:root ./data/`
- double check the permissions:
```
(base) tony@tony-virtual-machine:~/Desktop/my_grafana$ stat data/
  File: data/
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 803h/2051d	Inode: 2800386     Links: 7
Access: (0775/drwxrwxr-x)  Uid: (  472/ UNKNOWN)   Gid: (    0/    root)
Access: 2023-04-14 09:16:23.603658795 +0200
Modify: 2023-04-14 09:23:00.031741994 +0200
Change: 2023-04-14 09:23:00.031741994 +0200
 Birth: 2023-04-14 09:13:11.339618266 +0200
```

- finally, as root user start the container

`sudo docker compose up -d`

good luck!
