### ISSUE TITLE
Error message "user already exists" during login if user email in Oauth provider was changed

### ISSUE THREAD

**Issue by kidiboy** [grafana/grafana#67438]
## What happened:
I use Grafana with oauth identity provider for create and authorize users. Recently, I changed email address for some users. After that these users can't log into Grafana. They see error message "user already exists":
<img width="510" alt="image" src="https://user-images.githubusercontent.com/55297357/234956954-e99fed60-61da-44fa-b587-54da6170fb15.png">
Also, I see a similar error in the logs:
```
vm-grafana           | logger=context userId=0 orgId=0 uname= t=2023-04-27T18:22:44.85169408Z level=info msg="Request Completed" method=GET path=/login/generic_oauth status=302 remote_addr=192.168.1.18 time_ms=112 duration=112.393762ms size=29 referer= handler=/login/:name
vm-grafana           | logger=context userId=0 orgId=0 uname= t=2023-04-27T18:22:46.402488131Z level=info msg="Request Completed" method=GET path=/api/live/ws status=401 remote_addr=172.26.0.200 time_ms=10 duration=10.582009ms size=27 referer= handler=/api/live/ws
vm-grafana           | logger=context userId=0 orgId=0 uname= t=2023-04-27T18:22:47.93712354Z level=info msg="Request Completed" method=GET path=/api/live/ws status=401 remote_addr=172.26.0.200 time_ms=10 duration=10.536387ms size=27 referer= handler=/api/live/ws
vm-grafana           | logger=context userId=0 orgId=0 uname= t=2023-04-27T18:22:56.242141793Z level=info msg="Request Completed" method=GET path=/login/generic_oauth status=302 remote_addr=192.168.1.18 time_ms=10 duration=10.585329ms size=311 referer=https://grafana.example.com/login handler=/login/:name
vm-grafana           | logger=oauth t=2023-04-27T18:22:56.277386158Z level=info msg="state check" queryState=9848277e14ad025c327828984967a1ced9a86e60f7768248755534dd696f66ae cookieState=9848277e14ad025c327828984967a1ced9a86e60f7768248755534dd696f66ae
vm-grafana           | logger=context userId=0 orgId=0 uname= t=2023-04-27T18:22:56.320966992Z level=warn msg="user already exists"
```

## What you expected to happen:
I expected Grafana to update the user email to the actual value from Oauth response during login.

## Anything else we need to know?:
My current configuration to connect to Oath provider:
```toml
[auth.generic_oauth]
enabled = true
name = Example SSO
allow_sign_up = true
client_id = grafana
client_secret = <secret>
scopes = openid email profile offline_access roles
email_attribute_path = email
login_attribute_path = preferred_username
name_attribute_path = full_name
auth_url = https://sso.example.com/realms/example/protocol/openid-connect/auth
token_url = https://sso.example.com/realms/example/protocol/openid-connect/token
api_url = https://sso.example.com/realms/example/protocol/openid-connect/userinfo
role_attribute_path = contains(resource_access.grafana.roles[*], 'admin') && 'GrafanaAdmin' || contains(resource_access.grafana.roles[*], 'editor') && 'Editor' || 'Viewer'
allow_assign_grafana_admin = true
```

## Environment:
- Grafana version: [v9.4.3 (cf0a135595)](https://github.com/grafana/grafana/blob/main/CHANGELOG.md)
- Data source type & version: –
- OS Grafana is installed on: Ubuntu Server 22.04 with Docker 20.10.12 (Image: grafana/grafana:9.4.3)
- User OS & Browser: MacOS Monterey 12.6.3 & Google Chrome Version 111.0.5563.64 (Official Build) (arm64)
- Grafana plugins: – 
- Others: Oauth2.0 provider keycloak
