### ISSUE TITLE
Alerting: Migration to Unified Alerting with RBAC enabled does not assign correct permissions to alerts

### ISSUE THREAD

**Issue by yuri-tceretian** [grafana/grafana#67448]
## What happened:
In Grafana Enterprise, when RBAC is enabled migration to Unified Alerting from dashboards that have custom permissions does not assign correct permissions, which results in a situation when alert rules are visible to only Administrators.

## What you expected to happen:

Rule is visible to the user after migration.

## How to reproduce it (as minimally and precisely as possible):

- Start Grafana Enterprise v 9.5.0 (RBAC is enabled by default) with Legacy alerting enabled
- Create a team and a user that belong to that team
- Create a dashboard in the General folder. The dashboard should contain a panel with the alert rule. 
- Assign permissions to the dashboard: remove all permissions and add the team (any role).
- Confirm that the test user can see the dashboard and alert rule
- Migrate to Unified Alerting.
- Log in with the test user and confirm that no alert rules are visible to the user.
- Log in with admin user and make sure aler rule is available. 

## Environment:
- Grafana version: 9.5.0 Enterprise
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by yuri-tceretian** [comment]
I think this happens due to the fact that folder permission migration already happened and migration to UA happens after. Therefore ACLs that are created https://github.com/grafana/grafana/blob/a8b4a4bb45ae5b595f8016ec554a99c546970e5f/pkg/services/sqlstore/migrations/ualert/ualert.go#L322 are not upgraded to permissions.

**Comment by yuri-tceretian** [comment]
Apparently, this affects and OSS version of the Grafana.

**Comment by yuri-tceretian** [comment]
Basically, migration of rules from dashboard that have custom permissions seems to be broken since #44702 (v8.5.0) that converted ACLs to permissions because legacy->UA migration checks for old ACLs instead of new permissions.

**Comment by VictorLopess** [comment]
Hello. Maybe i'm with this problem or maybe i'm with the problem you have solved in [issue49270](https://github.com/grafana/grafana/pull/49270).

I have some boards from grafana 8.5.0. My new stack is https://github.com/prometheus-community version 46.8.0 (latest). When migrated board from that oldest to newst version, one specific board are not showed for all users. The diffence is that board has a Alert. Search for this problem i found the possible problem: when the board have any alert, the board came with permission only to Admin role. But, this same board, when loaded without alerts, it works fine, with permission for the all 3 roles available (you can see the images below). I'm using minikube to my local env and have tested in two k8s different clusters (all using k8s v1.26).

Board permissions WITH Alerts configured.
![image](https://github.com/grafana/grafana/assets/10835565/9fff3503-cad3-4837-b23f-9e1494e697c4)

The exactly same board, but WITHOUT Alerts configured
![image](https://github.com/grafana/grafana/assets/10835565/8affe270-84c3-4290-8294-89a8d05213d7)

All of my configuration are versioned and have no difference during execution. My grafana.ini in Helm Configuration:

``` 
grafana.ini:
    alerting:
      enabled: true
    unified_alerting:
      enabled: false
    wal:
      enabled: true
    auto_assign_org:
      enabled: true
    auto_assign_org_role: Viewer
    skip_org_role_sync:
      enabled: true
    # Viewers can access and use Explore and perform temporary edits on panels in dashboards they have access to. They cannot save their changes.
    viewers_can_edit:
      enabled: true
    server:
      root_url: http://grafana.local
  defaultDashboardsEnabled: true
  sidecar:
    dashboards:
      enabled: true
      label: label_to_import_board
      searchNamespace: "ALL"
      logLevel: DEBUG
      provider:
        foldersFromFilesStructure: true
        folder: 'Distro'
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: 'Distro'
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
```


The main difference between this two boards (working and not working) is the alert code, a very simple alert in this case. You can see all the code removed to board work again:


![image](https://github.com/grafana/grafana/assets/10835565/29d27be1-441a-4dad-bf10-91838baf3589)
