### ISSUE TITLE
Dashboards: Open dashboards in new tab from new search text box on top of page not working properly if sub path is configured

### ISSUE THREAD

**Issue by hamiteza** [grafana/grafana#67698]
### 
# What went wrong?

**What happened**:
when i click on items that listed in search box, dashboard comes without problem. but when open item link in new tab (ctrl + click) 404 page loads. i am using grafana sup path server.root_url=http://localhost:3000/g and server.serve_from_sub_path=true 
  - 

**What did you expect to happen**:
dashboard load in new tab when using sup path
  - 

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana and search dashboard in text box on top of page

**Step 2**:

- ctrl + click any dashboard

**Step 3**:

- note that sub path activated

### 
# What Grafana version are you using?

Grafana v9.5.1 (bc353e4b2d)

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### Is this a Regression?

None

**Comment by tonypowa** [comment]
hi @hamiteza 
thank you for creating this issue

I have changed the configuration via env override like so:

``` yml
  grafana:
    image: grafana/grafana:9.4.7
 

    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3000/grafana/g
      - GF_SERVER_SERVE_FROM_SUB_PATH=true



```




however, in my case, the new tab was opened correctly

![open_new_tab](https://user-images.githubusercontent.com/45235678/236193862-b2ec53bd-134c-4455-beb3-b96b68896e4d.gif)

| Grafana | 9.5.1 (bc353e4b2d) // Open Source |
Ubuntu 22.04.2 LTS -  Firefox 111.0.1 (64-bit)

How are you running Grafana and on what browser?
