### ISSUE TITLE
Datasource: ElasticSearch Data Links to Tempo do not work in Grafana 9.5

### ISSUE THREAD

**Issue by faustodavid** [grafana/grafana#68386]
### 
# What went wrong?

**What happened**:

 After upgrading Grafana from 9.4.10 to 9.5.2 I need help with the following issues when using the ElasticSearch Data source.
* The Tempo data link does not appear
<img width="638" alt="image" src="https://github.com/grafana/grafana/assets/2423149/55faabf7-73bf-4fa7-ab69-9e4eb9de7934">

* If the trace id field name is `trace.id` then it does not recognize it. it just shows `trace`.
<img width="503" alt="image" src="https://github.com/grafana/grafana/assets/2423149/03707e76-d4f0-48a3-9352-051ac58d2097">

**What did you expect to happen**:

To work as version 9.4.10.

Note, I am using ElasticSearch version 7.10+, in the new Grafana I dont see this option being applied when I look at the UI.

```
jsonData:
  esVersion: "7.10.0"
  logLevelField: "fields.level"
  logMessageField: "message"
  maxConcurrentShardRequests: 5
  timeField: "@timestamp"
  timeInterval: "10s"
  tlsAuth: false
  tlsAuthWithCACert: true
  tlsSkipVerify: true
  httpHeaderName1: "Authorization"
  httpHeaderName2: "hostname"
  dataLinks:
    - datasourceUid: tempo
      name: trace.id
      field: traceid
      url: $${__value.raw}
```

### 
# How do we reproduce it?

**Step 1**:

Add ElasticSearch data source using the version 7.10+ with the following Data Link:
```
  dataLinks:
    - datasourceUid: tempo
      name: trace.id
      field: traceid
      url: $${__value.raw}
```

**Step 2**:

Use Tempo and enable the configuration to log each span
```
log_received_spans:
 enabled: true
 include_all_attributes: true
```

**Step 3**:

Create some traces and go to Grafana Explore and try to see if the DataLink is there.

### 
# What Grafana version are you using?

v9.5.2

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Kubernetes

### Is this a Regression?

None

### Are Datasources involved?

ElasticSearch 7.10+
