### ISSUE TITLE
Couldn't create multiple notification policies using file provisioning 

### ISSUE THREAD

**Issue by dtherhtun** [grafana/grafana#68566]
### 
# What went wrong?

**What happened**:

I'm trying to create multiple notification policies like this - 
https://github.com/grafana/grafana/blob/main/pkg/services/provisioning/alerting/testdata/notificiation_policies/multiple-policies/policies.yml

**What did you expect to happen**:

I thought It will create 2 notification policies. Instead, it only creates one policy and overrides the default policy.
<img width="1111" alt="image" src="https://github.com/grafana/grafana/assets/16239096/0bd5a2da-f2d7-4bcc-9a5b-cb735668e213">

### 
# How do we reproduce it?

This is my configuration file and I was trying to create it through the ArgoCD.
```
apiVersion: v1
data:
  notificationpolicies.yaml: |-
    apiVersion: 1
    policies:
      - receiver: grafana-default-email
        group_by:
          - grafana_folder
          - alertname
      - orgId: 1
        receiver: AlertManager
        matchers:
          - severity =~ "critical|high|medium|low"
        repeat_interval: 15m
        group_interval: 30s
        group_by:
          - grafana_folder
          - alertname    
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: grafana-noti-policies
  labels:
    grafana_alert: '1'
  namespace: kube-prometheus-stack
  ```

### 
# What Grafana version are you using?

9.5.1

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Kubernetes

### Is this a Regression?

None
