### ISSUE TITLE
Google Cloud Monitoring: continuously getting warning message in server logs

### ISSUE THREAD

**Issue by jmuleiro** [grafana/grafana#68659]
### 
# What went wrong?

**What happened**:
I have multiple Grafana managed alerts that use Google Cloud Monitoring/Stackdriver as a data source. Four of them are continuously printing a warning message, which floods the container's logs. The message itself is related to Go HTTP responses handling, I think:
```
logger=tsdb.cloudMonitoring rule_uid=lzdQ7kJVk org_id=1 t=2023-05-17T18:52:00.231175224Z level=warn msg="failed to close response body" error=null
logger=tsdb.cloudMonitoring rule_uid=4KwNIz14z org_id=1 t=2023-05-17T18:52:01.077754667Z level=warn msg="failed to close response body" error=null
logger=tsdb.cloudMonitoring rule_uid=OnDt6gJ4k org_id=1 t=2023-05-17T18:52:06.360785093Z level=warn msg="failed to close response body" error=null
logger=tsdb.cloudMonitoring rule_uid=QE8uVz1Vk org_id=1 t=2023-05-17T18:52:06.913483494Z level=warn msg="failed to close response body" error=null
```
Also, I saw the same message while looking at some dashboards, but it's not remotely as frequent as this message since these alerts are evaluated every 10s.

**What did you expect to happen**:

  - Not applicable

### 
# How do we reproduce it?

**Step 1**
Configure a Cloud Monitoring data source and create a new alert. I'm unsure if this exact configuration will cause the error, but just in case it does, I'm using the Storage service and the Request count metric. This is the rest of the alert config:
![image](https://github.com/grafana/grafana/assets/26482875/4751331e-c0c4-4aae-a629-3fb3b35110a5)

**Step 2**
Configure metadata and make sure the alert condition is evaluated every 1 minute or less. Save the alert.

**Step 3**
Hopefully, this makes the server print multiple log entries similar to the ones I posted above.

### 
# What Grafana version are you using?

Grafana v9.5.2 (cfcea75916)

### 
### Is the bug inside a Dashboard Panel?

N/A

### Grafana Platform?

Kubernetes

### User's OS?

Ubuntu 22.04

### User's Browser?

Brave Browser 1.51.114 Chromium 113.0.5672.92

### Is this a Regression?

No

### Are Datasources involved?

Google Cloud Monitoring 1.0.0

### Anything else to add?
Grafana itself is deployed via Helm chart. Just in case this could be related to my configuration, here is the values.yaml I'm using:
```yaml
admin:
  existingSecret: monitoring-grafana-auth
  userKey: username
  passwordKey: password

persistence:
  enabled: true
  size: 50Gi
  existingClaim: grafana-save

image: 
  repository: docker.io/grafana/grafana
  tag: "9.5.2"
  pullPolicy: IfNotPresent

grafana.ini:
  unified_alerting:
    enabled: true

  alerting:
    enabled: false
  
  database:
    wal: true

rbac:
  create: true
  namespaced: true
  pspEnabled: false

deploymentStrategy:
  type: Recreate

resources:
  requests:
    cpu: 10m
    memory: 200Mi
  limits:
    cpu: 100m
    memory: 500Mi
```
grafana.ini:
```
[alerting]
enabled = false
[analytics]
check_for_updates = true
[database]
wal = true
[grafana_net]
url = https://grafana.net
[log]
mode = console
[paths]
data = /var/lib/grafana/
logs = /var/log/grafana
plugins = /var/lib/grafana/plugins
provisioning = /etc/grafana/provisioning
[unified_alerting]
enabled = true
```
