### ISSUE TITLE
Loki: Kick start your query examples add sum by with labels example

### ISSUE THREAD

**Issue by mellieA** [grafana/grafana#68860]
The query examples for aggregations like sum should explain how to `sum by (labels)` so labels are retained for alerting purposes. 

This question has shown up a few times in the community forum: 

https://community.grafana.com/t/is-it-possible-to-have-labels-in-loki-managed-alerts-summary-description/74674/5?u=grant2

For example, if someone uses the example aggregation as shown in the current kick start example for sum which looks like this:

![image](https://github.com/grafana/grafana/assets/18175287/c31f18ef-2b7b-4fb4-bd3e-365d185d54f6)

The labels are lost and can't be used in the alert: 

![image](https://github.com/grafana/grafana/assets/18175287/7513dc80-3995-4aa7-b2be-d9c6ad54005a)

If they use sum by (label) then the labels are kept and can be used in message templating for alerts: 

![image](https://github.com/grafana/grafana/assets/18175287/230efb41-ee6a-4236-bf82-6191c00cef5e)

**Comment by matyax** [comment]
Thanks for creating the issue @mellieA ! We'll add it to our backlog for consideration.

**Comment by bediverus** [comment]
I would like to say that some metrics behave differently.
example:
`absent_over_time` returns only labels used in the query and probably removes other labels
```
(absent_over_time({job="dockerlogs"} [5m]))
```
return only label `job`
```
sum by(job, container_name, compose_service) (absent_over_time({job="dockerlogs"} [5m]))
```
return only label `job` also
```
sum by(job, container_name, compose_service) (absent_over_time({job="dockerlogs", container_name="nginx-gen"} [5m]))
```
return labels `job` and `container_name`
```
(absent_over_time({job="dockerlogs", container_name=~"nginx-*"} [5m]))
```
return only label `job`

**Comment by andreaskiefersfelden** [comment]
Hi, thanks for your example. If i found it earlier i could save many time.

But i have one question to how can i use the labels in the alerting?
![image](https://github.com/grafana/grafana/assets/117894893/542a2940-8ca1-43b8-bcf5-7b4098867205)
I generated this label but i can't use it in the alerting.

**Comment by bediverus** [comment]
@andreaskiefersfelden this is not relevant to the current discussion.
But I spent a lot of time figuring this out, so I'll try to help you save some time.

If you need to use the metric `absent_over_time`, then you will have to formulate queries using specific labels, for example:
```
groups:
  - name: loki-alerts
    rules:
    - alert: NoLogFromProd
      expr: absent_over_time({container_name="service_prod"}[5m])
      for: 1m
      labels:
        severity: "critical"
        service: "{{ $labels.container_name }}"
        alerttype: "logs"
      annotations:
        description: "No logs for more then 5 min"
        summary: "No logs from {{ $labels.container_name }}"
#=================
    - alert: NoLogFromStaging
      expr: absent_over_time({container_name="service_prod"}[5m])
      for: 1m
      labels:
        severity: "critical"
        service: "{{ $labels.container_name }}"
        alerttype: "logs"
      annotations:
        description: "No logs for more then 5 min"
        summary: "No logs from {{ $labels.container_name }}"
```
### note
When using `absent_over_time({container_name=~"service_*"}[5m])` you won't get `{{ $labels.container_name }}` even if you use `sum by (container_name)`
I was unable to combine these queries into one and get the labels
Only using specific labels.

But many other metrics can be used 'sum by ()' to get labels and use then in alerts.
