### ISSUE TITLE
Auth: AzureAD OAuth - tenantID is not required

### ISSUE THREAD

**Issue by arukiidou** [grafana/grafana#69560]
**What is the chore?**:

- AzureAD OAuth - tenantID is not required
  - This works fine. Reducing the equired configurations from five to three, also reduces configuration issues.

### example(It works.)

```yaml:compose.yml
  grafana:
    image: "grafana/grafana:main"
    restart: always
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_AZUREAD_ENABLED: true
      GF_AUTH_AZUREAD_CLIENT_ID: ******
      GF_AUTH_AZUREAD_CLIENT_SECRET: ******

      # It works fine now.
      GF_AUTH_AZUREAD_AUTH_URL:  https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize
      GF_AUTH_AZUREAD_TOKEN_URL: https://login.microsoftonline.com/organizations/oauth2/v2.0/token
```

![image](https://github.com/grafana/grafana/assets/10738333/47d89bc7-b1ab-4d64-9d5b-bf91c2b2626c)

https://github.com/grafana/grafana/assets/10738333/1ce7fd71-68a4-4679-a02c-bb1a12f3dd0b

**Is there anything else we need to know?**:

- suggest labels
  - https://github.com/grafana/grafana/labels/area%2Fauth%2Foauth
  - https://github.com/grafana/grafana/labels/team%2Fgrafana-authnz
