### ISSUE TITLE
Product-Area-Here: short description of bug here

### ISSUE THREAD

**Issue by casnerano** [grafana/grafana#69950]
### 
# What went wrong?

**What happened**:

In configuration file `etc/grafana/provisioning/alerting/default.yml`

the Point of Contact for the telegram is declared, the ChatId value is taken from the environment variables.

```
contactPoints:
   - orgId: 1

     name: Telegram
     receivers:
       - uid: telegram_notifier
         type: telegram
         settings:
           bottoken: $TELEGRAM_TOKEN
           chatid: $TELEGRAM_CHAT_ID

```

env variable value
`TELEGRAM_CHAT_ID="-808008888"`

When starting grafana, an error pops up:
`Error: ✗ failure to map file default.yml: failure parsing contact points: Telegram: failed to validate receiver of type "telegram": failed to unmarshal settings: json: cannot unmarshal number into Go struct field Config.chatid of type string`

The problem is not solved, even if you wrap the value in quotes:
chatid: "$TELEGRAM_CHAT_ID"

The problem was solved temporarily through a crutch:
env variable value `TELEGRAM_CHAT_ID="808008888"`
```
in config
chatid: |-
   -
   $TELEGRAM_CHAT_ID
```

The problem is that when substituting a value from an environment variable, it is interpreted as a negative number, and not as a string, which the structure expects.

### 
# How do we reproduce it?

In configuration file `etc/grafana/provisioning/alerting/default.yml`

```
contactPoints:
   - orgId: 1

     name: Telegram
     receivers:
       - uid: telegram_notifier
         type: telegram
         settings:
           bottoken: $TELEGRAM_TOKEN
           chatid: $TELEGRAM_CHAT_ID
```

where `$TELEGRAM_CHAT_ID` is number.

### 
# What Grafana version are you using?

v9.5.2

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Docker

### Is this a Regression?

None
