### ISSUE TITLE
iFrame not accessable since version 10.0.0

### ISSUE THREAD

**Issue by AlexKusnezov** [grafana/grafana#70127]
### 
# What went wrong?

**What happened**:

  - Since I updated my docker container from 9.5.3 to 10.0.0. iFrame isn't accessable within Home assitant resulting in a login loop.

**What did you expect to happen**:

  - To log in as it was with v.9.5.3

### 
# How do we reproduce it?

**Step 1**:

- create container with following config:
```
version: '3'
services:
  grafana:
     image: grafana/grafana:9.4.12
     container_name: grafana
     restart: unless-stopped
     environment:
       - GF_SECURITY_ADMIN_USER=edited
       - GF_SECURITY_ADMIN_PASSWORD=edited123
       - GF_AUTH_DISABLE_LOGIN_FORM=false
       - GF_SECURITY_ALLOW_EMBEDDING=true
       - GF_SERVER_ROOT_URL=https://editedout.duckdns.org/grafana
       - GF_SERVER_SERVE_FROM_SUB_PATH=true
       
     ports:
       - '3000:3000'
     volumes:
       - /mnt/grafana:/var/lib/grafana
     user: "0"
```

**Step 2**:

- create an iframe and try to access it, e.g with Home assitant, my config:
```
grafana:
  title: Grafana
  icon: phu:grafana
  url: 'https://edited.duckdns.org/grafana'

grafana_local:
  title: Grafana Lokal
  icon: mdi:chart-areaspline
  url: 'http://192.168.2.109:3000'
```
both were accessable with v.9.5.3
**Step 3**:

- not accessable in v10.0.0

### 
# What Grafana version are you using?

10.0.0

### 
### Grafana Platform?

Docker

### User's OS?

Raspberry Pi OS

### User's Browser?

Google Chrome 114.0.5735.133, Home Assitant Companion App

### Is this a Regression?

Yes
