### ISSUE TITLE
Alerting: Different delivery time for different integrations

### ISSUE THREAD

**Issue by atimin** [grafana/grafana#70130]
### 
# What went wrong?

**What happened**:

 In my Grafana configuration, I have a contact point with 3 integrations: 
- Teams
- Google Chat
- A custom webhook to launch a recording system

I've experienced that notifications are sent to the integrations at different time:

![Screenshot from 2023-06-15 10-52-36](https://github.com/grafana/grafana/assets/67068/7f714a77-6809-40cd-810c-424a8c5b9578)

The time display isn't the issue here, but I'm getting these notifications with a huge delay between them

**What did you expect to happen**:

I was expecting that the notifications would be sent at the same time. For my application,  5-second delay would be ok.    

### 
# How do we reproduce it?

**Step 1**:

- Provision a contact point with valid webhooks:

```yml
  - orgId: 1
    name:  PANDA_FERRUM_PANDIA
    receivers:
      - name: PANDA Teams
        type: teams
        uid: panda-3
        isDefault: false
        settings:
          url: XXXX
          title: |
            {{ template "notification.title" . }}
          message: |
            {{ template "notification.body" . }}
        disableResolveMessage: true

      - uid: ferrum-2
        type: googlechat
        isDefault: true
        name: Ferrum Panda Live
        disableResolveMessage: true
        settings:
          url: YYYY
          title: |
            {{ template "notification.title" . }}
          message: |
            {{ template "notification.body" . }}

      - name: PANDIA Webhook
        type: webhook
        uid: pandia-1
        isDefault: false
        settings:
          url: http://192.168.14.110/trigger
        disableResolveMessage: true
```

**Step 2**:

- Provision notification policies:

```yaml
# config file version
apiVersion: 1

# List of notification policies
policies:
  # <int> organization ID, default = 1
  - orgId: 1
    name: All for PANDA
    receiver: PANDA
    group_by:
      - ...

    routes:
      - matchers:
          - grafana_folder = Customer
        receiver: PANDA_FERRUM_PANDIA
```

**Step 3**:

- Create an alert in the `Customer` folder

** Step 4**:

-  Fire the alert

### 
# What Grafana version are you using?

v9.4.7

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Docker

### User's OS?

Ubuntu 20.04

### User's Browser?

Version 114.0.5735.106 (Official Build) snap (64-bit)

### Is this a Regression?

None

### Are Datasources involved?

InfluxDB
