### ISSUE TITLE
Dashboards with alerts are not loading with correct permissions

### ISSUE THREAD

**Issue by VictorLopess** [grafana/grafana#70206]
### 
# What went wrong?

Hello. I have a problem solved in [issue49270](https://github.com/grafana/grafana/pull/49270) but in the newest version of grafana.

I have some boards from grafana 8.5.0. My new stack is https://github.com/prometheus-community version 46.8.0 (latest). When migrated board from that oldest to newest version, one specific board are not showed for all users. The diffence is that board has a Alert. Search for this problem i found the possible problem: when the board have any alert, the board came with permission only to Admin role. But, this same board, when loaded without alerts, it works fine, with permission for the all 3 roles available (you can see the images below). I'm using minikube to my local env and have tested in two k8s different clusters (all using k8s v1.26).

Board permissions WITH Alerts configured.
![image](https://github.com/grafana/grafana/assets/10835565/9fff3503-cad3-4837-b23f-9e1494e697c4)

The exactly same board, but WITHOUT Alerts configured
![image](https://github.com/grafana/grafana/assets/10835565/8affe270-84c3-4290-8294-89a8d05213d7)

All of my configuration are versioned and have no difference during execution. I use k8s Configmap to host dashboards configs. My grafana.ini in Helm Configuration:

``` 
grafana.ini:
    alerting:
      enabled: true
    unified_alerting:
      enabled: false
    wal:
      enabled: true
    auto_assign_org:
      enabled: true
    auto_assign_org_role: Viewer
    skip_org_role_sync:
      enabled: true
    # Viewers can access and use Explore and perform temporary edits on panels in dashboards they have access to. They cannot save their changes.
    viewers_can_edit:
      enabled: true
    server:
      root_url: http://grafana.local
  defaultDashboardsEnabled: true
  sidecar:
    dashboards:
      enabled: true
      label: label_to_import_board
      searchNamespace: "ALL"
      logLevel: DEBUG
      provider:
        foldersFromFilesStructure: true
        folder: 'Distro'
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: 'Distro'
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
```

The main difference between this two boards (working and not working) is the alert code, a very simple alert in this case. You can see all the code removed to board work again:

![image](https://github.com/grafana/grafana/assets/10835565/29d27be1-441a-4dad-bf10-91838baf3589)

I can resolve this via panel, setting the permission like the second image, but, all of my stack are versioned and is deployed every day. So, every deploy i need to set it again. I looked for a way to set this setting via grafana.ini or another setting that I can do version control, but I didn't find such a setting. If anyone knows how to do this, please share with us.

### 
# How do we reproduce it?

**Step 1**:

I used https://github.com/prometheus-community/helm-charts/releases/tag/kube-prometheus-stack-46.8.0, but I don't know if the problem occurs with other deployment way. So, you need to create the stack following the repository doc first.

**Step 2**:

- After have access to panel, create any simple dashboard WITH any simple alert and save it in `json` format. Create a `configmap` with this `json` content and deploy it in k8s stack.
- Configure kube-prometheus-stack to get boards from configmap and deploy the stack making grafana loading dashbords from configmap.
- At this point, you will can see the dashboard permissions are only to admins.

**Step 3**:

- If you remove the alerts from the same dashboard and redeploy the stack, you will see that all the permissions came correctly, based on the dashboard folder settings inherit.

### 
# What Grafana version are you using?

Grafana v9.5.3 (916d9793aa)

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Kubernetes

### User's OS?

Ubuntu 23.04

### User's Browser?

Firefox 114.0.1 (64-bit) and Chromium Version 114.0.5735.106 (Official Build) snap (64-bit)

### Is this a Regression?

Yes

### Are Datasources involved?

Default Prometheus from kube-prometheus-stack-46.8.0
