### ISSUE TITLE
All text after $ is removed from labels from provisioned alerts

### ISSUE THREAD

**Issue by mathgaming** [grafana/grafana#70484]
### 
# What went wrong?

**What happened**:
I'm using a graphite data source and want a label for part of the alert name.
In the GUI I make an annotation and a label with the following information:
```
          annotations:
            instance: '{{ reReplaceAll "^(([^.]+\\.){3})([^.]+).+" "$3" $labels.name }}'
          labels:
            instance: '{{ reReplaceAll "^(([^.]+\\.){3})([^.]+).+" "$3" $labels.name }}'
```
I export the alerts and see the following in the export.yaml file:
```
          annotations:
            instance: '{{ reReplaceAll "^(([^.]+\\.){3})([^.]+).+" "$3" $labels.name }}'
          labels:
            instance: '{{ reReplaceAll "^(([^.]+\\.){3})([^.]+).+" "$3" $labels.name }}'
```
I restart Grafana with the export.yaml in the folder for provisioned alerts.
Grafana has now removed all dollar signs and the text after them from the label. Like this
```
          annotations:
            instance: '{{ reReplaceAll "^(([^.]+\\.){3})([^.]+).+" "$3" $labels.name }}'
          labels:
            instance: '{{ reReplaceAll "^(([^.]+\\.){3})([^.]+).+" "" .name }}'
```

**What did you expect to happen**:
That the label is unchanged after loading the export from a provisioned file. Like this:
```
          annotations:
            instance: '{{ reReplaceAll "^(([^.]+\\.){3})([^.]+).+" "$3" $labels.name }}'
          labels:
            instance: '{{ reReplaceAll "^(([^.]+\\.){3})([^.]+).+" "$3" $labels.name }}'
```

### 
# How do we reproduce it?

**Step 1**:

- Make an alert with a $ in the label

**Step 2**:

- Export the alerts to a yaml file

**Step 3**:

- Add the exported file to the alerting folder to provision it

**Step 4**:

- Restart Grafana and observe the $ and the text after it is gone.
- You can export the alerts again to confirm it

### 
# What Grafana version are you using?

Grafana: 9.5.3

### 
### Is the bug inside a Dashboard Panel?

No

### Grafana Platform?

Docker

### User's OS?

Ubuntu 20.04

### User's Browser?

Not UI related

### Is this a Regression?

None

### Are Datasources involved?

No

**Comment by owl-king** [comment]
That is exactly what I got while importing the rule from config map.
I use these below in the configmap.
`            
              labels:
                instance: '{{ with $values }}{{ range $k, $v := . }}{{ $v.Labels.instance }}{{ end }}{{ end }}'
                job: '{{ with $values }}{{ range $k, $v := . }}{{ $v.Labels.job }}{{ end }}{{ end }}'
`
I checked the mounted file and its content is correct.But Grafana UI, it becomes
`
instance={{ with }}{{ range , := . }}{{ .Labels.instance }}{{ end }}{{ end }}
job={{ with }}{{ range , := . }}{{ .Labels.job }}{{ end }}{{ end }}
`
I tested with the export function from the UI, and here is what I got
`
          labels:
            instance: '{{ with  }}{{ range ,  := . }}{{ .Labels.instance }}{{ end }}{{ end }}'
            job: '{{ with  }}{{ range ,  := . }}{{ .Labels.job }}{{ end }}{{ end }}'
`

All the variables such as $value, $k, $v are gone. 
Therefor our alert policies base on label are wrong right now.

**Comment by JacobsonMT** [comment]
Hi @mathgaming, thanks for bug report!

There are a few things happening here, but it all revolves around the fact that provisioning files support the interpolation of environment variables. By default, `$variable` style strings in provisioning files will be replaced with the corresponding environment variable (resulting in an empty string if the variable doesn't exist). If you want to include a literal `$` symbol without interpolation, you need to use `$$` instead. More info here: https://grafana.com/docs/grafana/latest/administration/provisioning/#using-environment-variables

Now, you might wonder why there's a difference between annotations and labels. This is because interpolation for annotations was removed: https://github.com/grafana/grafana/pull/54975. So, your labels are being interpolated to an empty string, while your annotations are not being interpolated at all.

The correct format in your case would be:

```yaml
          annotations:
            instance: '{{ reReplaceAll "^(([^.]+\\.){3})([^.]+).+" "$3" $labels.name }}'
          labels:
            instance: '{{ reReplaceAll "^(([^.]+\\.){3})([^.]+).+" "$$3" $$labels.name }}'
```

The state of this is a bit complicated and the documentation is lacking. Also, the export endpoints should use `$$` where needed to ensure the file works correctly. I have created issues to improve the documentation and fix the bug:

- https://github.com/grafana/grafana/issues/71006
- https://github.com/grafana/grafana/issues/71007


Thanks again for the detailed bug report!
