### ISSUE TITLE
Provisioning: Contact point (provisioning/notifiers/*.yaml) not works in Grafana 10.0.1

### ISSUE THREAD

**Issue by AllanAndrade** [grafana/grafana#70528]
### 
# What went wrong?

**What happened**:

  - Contact Points provisioning YAML files are not loaded in Grafana 10.0.1 (image=grafana/grafana-oss:10.0.1). Even the sample file doesn't work (provisioning/notifiers/sample.yaml).
  
NOTE: Datasource and Dashboards provisioning YAML files are successfull loaded as expected.

**What did you expect to happen**:

  - That the Contact Points provisioning YAML files be loaded according to the documentation:  https://grafana.com/docs/grafana/latest/alerting/set-up/provision-alerting-resources/file-provisioning/

### 
# How do we reproduce it?

**Step 1**:

- Create a file called `notifier.yaml` with this content:
```
apiVersion: 1
notifiers:
- name: default-slack-temp
  type: slack
  org_name: Main Org.
  is_default: true
  uid: notifier1
  settings:
    recipient: "XXX"
    token: "xoxb"
    uploadImage: true
    url: https://slack.com
- name: default-email
  type: email
  org_id: 1
  uid: notifier2
  is_default: false
  settings:
    addresses: example11111@example.com

```
**Step 2**:

- At the same folder where is the file `notifier.yaml` run the folowing command:
```
docker run -d -p 8085:3000 --name=grafana \
  --user "$(id -u)" \
  --volume "$PWD/notifier.yaml:/etc/grafana/provisioning/notifiers/notifier.yaml" \
  grafana/grafana-oss:10.0.1
```

**Step 3**:

- On a browser, open the url: http://127.0.0.1:8085/ and make login with user 'admin' and password 'admin'

**Step 4**:

- On menu, click at `Alerting` and them in `Contact points`, and then the `concact point` provisioned from  `notifier.yaml` isn't listed.

### 
# What Grafana version are you using?

10.0.1

### 
### Grafana Platform?

Kubernetes or Docker
