### ISSUE TITLE
Grafana-SMTP: Unable to send test email/configure email alerting

### ISSUE THREAD

**Issue by geolney** [grafana/grafana#70750]
### 
# What went wrong?

**What happened**:

  - I am unable to send a test email and, therefore, unable to set up email alerting via Grafana. When I click on "Send test notification" via the UI I get a successful "Test alert sent", but nothing arrives. 

**What did you expect to happen**:

  - I expected to receive an email in my inbox from grafana in the test template format. 

### 
# How do we reproduce it?

**Step 1**:

- Set-up Grafana v9.2.2 with the grafana.ini smtp enabled like so with SES set-up properly in AWS and verify the <from_address> value that you are using/sending to correctly on AWS side. 
```
smtp:
          enabled: true
          host: email-smtp.eu-west-2.amazonaws.com:587
          user: <user-iam-key>
          from_address: <verified-AWS-SES-email>
          from_name: Grafana
          skip_verify: false
```

**Step 2**:

- Now click on the UI: Alerting -> Contact Points -> Create new Contact point -> set it as 'email' and the address as your <verified-AWS-SES-email> in your grafana.ini

**Step 3**:

- Click test alert -> using predefined template -> Send test notification -> you should receive successful message, but nothing arrives.
- Grafana container logs once pressing the button show:
```
logger=alerting.notifier.email t=2023-06-27T13:51:19.877310434Z level=error msg="Missing receiver"
logger=alerting.notifier.email t=2023-06-27T13:51:19.877357241Z level=error msg="Missing group labels"
```

### 
# What Grafana version are you using?

v9.2.2

### 
### Grafana Platform?

Kubernetes

### User's OS?

Ubuntu 20.04

### User's Browser?

Google Chrome Version 114.0.5735.133 (Official Build) (arm64)

### Is this a Regression?

None

**Comment by flightlesstux** [comment]
Hi @geolney,

Did you check your CloudWatch logs? Maybe we can catch from there what's happening on the SMTP side.

**Comment by flightlesstux** [comment]
Hi @geolney,

I didn't see a `password:` line, maybe it's the problem. And also if the password contains # or ; you have to wrap it with triple quotes. Example: """#password;"""

**Comment by geolney** [comment]
Hi @flightlesstux, apologies for the confusion but I forgot to add that I populate this via a k8s secret in the helmRelease. Before when the secret wasn't present/incorrect I was getting an 'Invalid Credentials' via the Grafana UI when clicking the send test button, so I believe that it is getting the key credentials fine. 
```
valuesFrom:
  - kind: Secret
     name: grafana-smtp-password
     valuesKey: values.yaml
```
