### ISSUE TITLE
Authentication: ldap mapping of grafana_admin fails since v10

### ISSUE THREAD

**Issue by DennyGDeChef** [grafana/grafana#70840]
### 
# What went wrong?

**What happened**:
When logging in via ldap account, all groups are mapped to orgs as expected except grafana_admin.
log output with activated ldap.debug shows:
..... OrgRoles:map[1:Viewer 2:Admin 3:Admin 4:Admin 6:Admin 7:Admin 8:Admin 9:Admin 10:Admin] **IsGrafanaAdmin:0xc003766a69** IsDisabled:false SkipTeamSync:false}]

**What did you expect to happen**:

**IsGrafanaAdmin:true**

**Additional info**:
the same group is mapped several times in the same toml file. It also results in Org Admin for 2, 3, 4, 6, 7, 8, 9, 10 - which works.

### 
# How do we reproduce it?

**Step 1**:

- Setup grafana openLDAP mapping

**Step 2**:

- define a grafana_admin group in ldap and map it in ldap.toml

**Step 3**:

- try to login

### 
# What Grafana version are you using?

10.0.1

### 
### Is the bug inside a Dashboard Panel?

no

### Grafana Platform?

Docker

### User's OS?

RHEL7

### User's Browser?

Firefox 102.12.0esr (64-Bit)

### Is this a Regression?

Yes

**Comment by Jguer** [comment]
Hey @DennyGDeChef , 

- Can you share a redacted version of your `ldap.toml` please?
- What was your previous Grafana version

I think you might be hitting something related to https://github.com/grafana/grafana/pull/58820

**Comment by DennyGDeChef** [comment]
`        [[servers.group_mappings]]
        group_dn = "*"
        org_role = "Viewer"
        org_id = 1

        [[servers.group_mappings]]
        group_dn = "grafana_admins"
        org_role = "Admin"
        grafana_admin = true

        [[servers.group_mappings]]
        group_dn = "grafana_admins"
        org_role = "Admin"
        org_id = 2

        [[servers.group_mappings]]
        group_dn = "grafana_editors"
        org_role = "Editor"
        org_id = 2

        [[servers.group_mappings]]
        group_dn = "grafana_admins"
        org_role = "Admin"
        org_id = 3`
        
previous version was 9.4.3

But I expect the evaluation result in true or false, not 0xc003766a69

**Comment by Jguer** [comment]
Line 476 is ok as extUser.IsGrafanaAdmin is a *bool. It can either be true, false or nil.

I'll see if that log line can be improved

```toml
    [[servers.group_mappings]]
    group_dn = "grafana_admins"
    org_role = "Admin"
    org_id = 1
    grafana_admin = true

    [[servers.group_mappings]]
    group_dn = "grafana_admins"
    org_role = "Admin"
    org_id = 2
    grafana_admin = true
```

Can you try this in your config?
