### ISSUE TITLE
Elasticsearch: Not able to see Logs in explore Metric (1) drop down(no options found) 

### ISSUE THREAD

**Issue by Michael-Coetzee** [grafana/grafana#70895]
### 
# What went wrong?

**What happened**:

  - When upgrading to grafana 10.0.1 from 8.5.* using the latest elasticsearch eck 8.8.1 version,  when i select elasticsearch datasource in explore i am not able to select the 'Logs' dropdown in the Metric (1)  query section, it displays 'no options found' instead. 

**What did you expect to happen**:

  - I was expecting to see the Logs in the list drop down and once selected see logs 

### 
# How do we reproduce it?

**Step 1**:

- Install grafana '9.5+'  -OR- '10.0+' 

**Step 2**:

- Install ECK 8.8.1

**Step 3**:

- Create Datasource with settings:
```
    - access: proxy
      basicAuth: true
      basicAuthUser: nlog
      editable: false
      jsonData:
        esVersion: 8.0.0
        logLevelField: fields.level
        logMessageField: message
        timeField: '@timestamp'
        tlsAuth: false
        tlsAuthWithCACert: false
        tlsSkipVerify: true
        index: '*filebeat*'
      name: filebeat
      secureJsonData:
        basicAuthPassword: <password redacted>
      type: elasticsearch
      uid: filebeat
      url: https://localhost:9200
```

Step 4:

- Check dashbaord: 
![image](https://github.com/grafana/grafana/assets/8096175/e514c17b-a1fd-4457-8345-21b2fa038dbc)
![image](https://github.com/grafana/grafana/assets/8096175/0eb1253a-a35e-4aea-9f47-f7d0a2d57ca8)

### 
# What Grafana version are you using?

10.0.1 -OR- 9.5.1

### 
### Grafana Platform?

Kubernetes version v1.25.6
helm chart version 6.57.2

### User's OS?

NODE: Ubuntu 22.04.2 LTS

### User's Browser?

Firefox

### Is this a Regression?

Yes

### Are Datasources involved?

Elasticsearch 5.0.0

### Anything else to add?

It's a weird thing to see, but if i go back to 8.5.* it works again. 
I am aware that the database field in the datasource is deprecated in favor of index
Could it be related to this?: Elasticsearch dropped support for document type: https://www.elastic.co/guide/en/elasticsearch/reference/7.17/removal-of-types.html#removal-of-types
