### ISSUE TITLE
Alerting: File provisioning rule export endpoints should escape $variables

### ISSUE THREAD

**Issue by JacobsonMT** [grafana/grafana#71006]
Context: https://github.com/grafana/grafana/issues/70484

Alerting file provisioning supports interpolation of environment variables using the `$variable` syntax in most fields. The file provisioning export endpoints should escape all instances of `$variable` to `$$variable` when found in a field that is interpolated. Raw un-interpolated strings are not saved in any fashion, so no need to worry about accidentally escaping a `$variable` that should be an environment variable.

### Example:

A rule with the following config:
```yaml
          annotations:
            instance: '{{ reReplaceAll "^(([^.]+\\.){3})([^.]+).+" "$3" $labels.name }}'
          labels:
            instance: '{{ reReplaceAll "^(([^.]+\\.){3})([^.]+).+" "$3" $labels.name }}'
```

should export to:
```yaml
          annotations:
            instance: '{{ reReplaceAll "^(([^.]+\\.){3})([^.]+).+" "$3" $labels.name }}'
          labels:
            instance: '{{ reReplaceAll "^(([^.]+\\.){3})([^.]+).+" "$$3" $$labels.name }}'
```

Since, annotations are not interpolated but labels are.
