### ISSUE TITLE
Datasources: Prometheus basic auth provisioning not working

### ISSUE THREAD

**Issue by altzan** [grafana/grafana#71012]
### 
# What went wrong?

**What happened**:

  - Basic auth is not taken into account when provisioning a Prometheus data source. The data source works fine if I edit it and add the basic auth information manually. What is more the data source UI in Grafana does not show that these fields are used. They seem like disabled/unused.

**What did you expect to happen**:

  - Basic auth to work with provisioned Prometheus data sources.

### 
# How do we reproduce it?

**YAML file:**

```
---
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://<url>:9090
    basicAuth: true
    basicAuthUser: <user>
    isDefault: true
    secureJsonData:
      basicAuthPassword: <password>
    version: 1
    editable: true

```

Which is based on this example: https://grafana.com/docs/grafana/latest/administration/provisioning/

I've also tried to add the "basicAuth" and "basicAuthUser" fields under the "jsonData" YAML field but this did not work either.

### 
# What Grafana version are you using?

v10.0.1

### 
### Grafana Platform?

Docker

### Is this a Regression?

None

### Are Datasources involved?

Prometheus

**Comment by kacey-lunacare** [comment]
This is working for me on `10.0.1`
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-prometheus-datasources
  namespace: monitoring
data:
  prometheus.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus-data
        type: prometheus
        url: https://prometheus.dev.domain-name.com
        access: proxy
        isDefault: true
        basicAuth: true
        basicAuthUser: admin
        secureJsonData:
          basicAuthPassword: $PROMETHEUS_DATASOURCE_PASSWORD

```
I set up the password via an environment variable in the deployment that references a kubernetes secret.
