### ISSUE TITLE
Data Source Picker: subpath missing when served with subpath on configure a new datasource button

### ISSUE THREAD

**Issue by oliver3Datax** [grafana/grafana#71061]
### 
# Subpath missing when pressing on button "Configure a new data source"

### Subpath missing when serving with subpath 
When you remove all the default widgets from the dashboard and then click on "Add Visualization" and then the on button "Configure a new data source" the link on the button is served without the subpath, resulting on a 404 Error.

![image](https://github.com/grafana/grafana/assets/111345328/6dd6aad2-392d-4e47-9366-cce61ece23dd)

The grafana instance is hosted on a subpath called grafana (see on the bottom left corner, the subpath is missing):

![image](https://github.com/grafana/grafana/assets/111345328/f0b7d77c-ac55-4b9d-a0b1-ba5113da7750)

Maybe this issue https://github.com/grafana/grafana/issues/59480 is somehow connected to this?

Everything else works and every other link is served under the subpath.

This instance will run behind a reverse proxy.

### Configuration of my docker-compose.yml

```yml
version: "2"
services:
  grafana_database:
    image: postgres:14.2-alpine
    hostname: grafana_database
    environment:
      POSTGRES_USER: grafana-example
      POSTGRES_PASSWORD: whatpasswordsecurity?
      POSTGRES_DB: grafana-example
    volumes:
      - grafana-db:/var/lib/postgresql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      grafana:

  grafana:
    image: grafana/grafana-oss:10.0.1
    restart: unless-stopped
    hostname: grafana
    depends_on:
      - grafana_database
    ports:
     - '3000:3000'
    environment:
      GF_DEFAULT_INSTANCE_NAME: grafana-example
      GF_SECURITY_ADMIN_USER: exampleadmin
      GF_SECURITY_ADMIN_PASSWORD: whatpasswordsecurity?
      GF_SECURITY_ADMIN_EMAIL: it@example.com
      GF_SECURITY_COOKIE_SECURE: "true"
      GF_SERVER_DOMAIN: example.com
      GF_SERVER_ENFORCE_DOMAIN: "false"
      GF_SERVER_ROOT_URL: "https://example.com/grafana/"
      GF_SERVE_FROM_SUB_PATH: "true"
      GF_SERVER_PROTOCOL: http
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_USER: grafana-example
      GF_DATABASE_PASSWORD: whatpasswordsecurity?
      GF_DATABASE_HOST: grafana_database:5432
      GF_AUTH_GITLAB_ENABLED: "true"
      GF_AUTH_GITLAB_CLIENT_ID: whatpasswordsecurity?
      GF_AUTH_GITLAB_CLIENT_SECRET: whatpasswordsecurity?
      GF_AUTH_GITLAB_SCOPES: read_api
      GF_AUTH_GITLAB_AUTH_URL: https://example.com/oauth/authorize
      GF_AUTH_GITLAB_TOKEN_URL: https://example.com/oauth/token
      GF_AUTH_GITLAB_API_URL: https://example.com/api/v4
      GF_AUTH_GITLAB_ALLOW_SIGN_UP: "true"
      GF_AUTH_GITLAB_USE_PKCE: "true"
      GF_AUTH_GITLAB_AUTO_LOGIN: "false"
      GF_AUTH_GITLAB_ALLOWED_GROUPS: ops
      GF_AUTH_GITLAB_ALLOW_ASSIGN_GRAFANA_ADMIN: "false"
      GF_AUTH_GITLAB_TLS_SKIP_VERIFY_INSECURE: "false"
    volumes:
     - grafana-data:/var/lib/grafana
    networks:
      grafana:
  
networks:
  grafana:
    external: true

volumes:
  grafana-data:
  grafana-db:
```

### 
# How do we reproduce it?

**Step 1**:

- Host Grafana behind a reverse proxy and serve it under a subpath. (Configure it according to https://grafana.com/tutorials/run-grafana-behind-a-proxy/)

**Step 2**:

- log in as admin and remove all the widgets from the default dashboard

**Step 3**:

- Click on "Add Visualization"

**Step 4**:

- Click on "Configure a new data source"

**Step 5**:

- Get served a 404 error

### 
# What Grafana version are you using?

grafana-oss:10.0.1

### Grafana Platform

Docker

### User's OS?

Debian 11

### User's Browser?

Google Chrome: Version 113.0.5672.126 (Official Build) (64-bit)

### Is this a Regression?

No
