### ISSUE TITLE
HTTP-API: securityScheme api_key type incorrect

### ISSUE THREAD

**Issue by commonism** [grafana/grafana#71076]
### 
# What went wrong?

I tried to use an auth token for authenticating with grafana to use the http api.

**What happened**:

Authentication does not work.

The description document says:

```yaml
  securitySchemes:
    api_key:
      in: header
      name: Authorization
      type: apiKey
    basic:
      scheme: basic
      type: http
```

This results in sending the header
`Authentication: KEY`

which does not work.

### 
# How do we reproduce it?

The docs use 
`Authentication: Bearer KEY`

https://grafana.com/docs/grafana/latest/developers/http_api/auth/
```
POST /api/auth/keys HTTP/1.1
…
Authorization: Bearer eyJrIjoiT0tTcG1pUlY2RnVKZTFVaDFsNFZXdE9ZWmNrMkZYbk
```

The type of the api_key has to be bearer in the description document.

### 
# What Grafana version are you using?

10.0.1

### 
### Grafana Platform?

None

### Is this a Regression?

None

**Comment by commonism** [comment]
To clarify, scheme has to be bearer not type.
```yaml
  securitySchemes:
…
    basic:
      scheme: bearer
      type: http
```
https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#fixed-fields-23
https://swagger.io/docs/specification/authentication/bearer-authentication/
