### ISSUE TITLE
HTTP-API - Parameter name mismatch for DashboardID in renderReportPDF

### ISSUE THREAD

**Issue by commonism** [grafana/grafana#71075]
### 
# What went wrong?

While working with the description document (swagger2 or OpenAPI3)
https://…/public/api-merged.json
https://…/public/openapi3.json

I got errors about the consistency of the description document.

> ERROR:root:('/reports/render/pdf/{dashboardID}', 'get', 'renderReportPDF', 'Parameter name not found in path: DashboardID')

**What did you expect to happen**:

The description document is valid.

### 
# How do we reproduce it?

Looking at the description document (converted to yaml for readbility):

```yaml
  /reports/render/pdf/{dashboardID}:
    get:
      deprecated: true
      description: Please refer to [reports enterprise](#/reports/renderReportPDFs)
        instead. This will be removed in Grafana 10.
      operationId: renderReportPDF
      parameters:
      - in: path
        name: DashboardID
        required: true
        schema:
          format: int64
          type: integer
      - in: path
        name: dashboardID
        required: true
        schema:
          format: int64
          type: integer
…
```

we can see dashboardID & DashboardID referenced.

Assuming DashboardID results due to
https://github.com/grafana/grafana/blob/09330890f3fbd7a4561041a9d52ec5a86d1ff22c/pkg/api/dashboard.go#L1083-L1086

it may be wrong?

### 
# What Grafana version are you using?

10.0.1

### 
### Grafana Platform?

None

### Is this a Regression?

None
