### ISSUE TITLE
Sidecar Alerts: Alerts do not disappear after ConfigMap is deleted

### ISSUE THREAD

**Issue by IrregularLine** [grafana/grafana#71094]
### 
# Grafana sidecar Alert rules do not disappear after ConfigMap is deleted

**What I'm trying to do**:

- Create/Deleting alerts from Loki with Grafana sidecar Alerting

**What happened**:

  - Alerts are successfully loaded into Grafana when I create a ConfigMap with the label 'grafana_alert: "1"'. But when testing if the alerts are deleted when the ConfigMap is deleted nothing happens. The alert continues to run.

**What did you expect to happen**:

  - The Alert rule to be deleted if the ConfigMap is deleted.

### 
# How do we reproduce it?

**Step 1**:

- Enable sidecar Alerting

```YAML
sidecar:
    alerts:
      enabled: true
      searchNamespace: ALL 
```

**Step 2**:

- Create Alert rule with ConfigMap

```YAML
kind: ConfigMap
apiVersion: v1
metadata:
  name: test-alert-1
  labels:
    grafana_alert: "1"
data:
  rules.yaml: |
    apiVersion: 1
    groups:
        - orgId: 1
          name: ' new dashboard'
          folder: test
          interval: 20s
          rules:
            - uid: my_id_1
            ...
```

**Step 3**:

- The Alerting rule will be created on Grafana

**Step 4**:

- Delete the ConfigMap and observe that the Alerting rule is not deleted
- Even deleting the File from the Grafana pod in '/etc/grafana/provisioning/alerting' will not delete the rule, even after restarting the Pod
- The only solution found was to delete the PV of Grafana so that the Alerting rule would dissapear 

### 
# What Grafana version are you using?

9.3.1

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Kubernetes

### Is this a Regression?

None

### Are Datasources involved?

Loki

**Comment by JacobsonMT** [comment]
Unfortunately, this is expected behaviour for all of Grafana's file provisioning syntax. In order to delete a provisioned resource through file provisioning you will have to add the resource to its corresponding delete section. For alert rules this is `deleteRules`:

``` yaml
# List of alert rule UIDs that should be deleted
deleteRules:
  # <int> organization ID, default = 1
- orgId: 1
  # <string, required> unique identifier for the rule
  uid: my_id_1
```

For more information, you can take a look at the docs here: https://grafana.com/docs/grafana/latest/alerting/set-up/provision-alerting-resources/file-provisioning/#provision-alert-rules
