### ISSUE TITLE
Dashboards: Templating init failed e.replace is not a function when I use Erigon Prometheus.

### ISSUE THREAD

**Issue by suxnju** [grafana/grafana#71264]
### 
# What went wrong?

**What happened**:

  - Templating init failed e.replace is not a function when I use Erigon Prometheus.
<img width="1099" alt="screen" src="https://github.com/grafana/grafana/assets/19996579/3e58c8a6-e9df-433b-92ab-d1ee7c15d56e">

**What did you expect to happen**:

  - Some metrics should be shown like

![image](https://www.monkeyvault.net/content/images/size/w1000/2022/08/Screen-Shot-2022-08-28-at-10.55.53-AM-1.png)

### 
# How do we reproduce it?

**Step 0**:

- Run prometheus locally
`./prometheus --config.file=./prometheus.yml --web.listen-address=:9010`

The prometheus.yml is
```
global:
  scrape_interval: 10s
  scrape_timeout: 3s
  evaluation_interval: 5s

scrape_configs:
  - job_name: erigon # example, how to connect prometheus to Erigon
    metrics_path: /debug/metrics/prometheus
    scheme: http
    static_configs:
      - targets:
          - XXX.XXX.XXX.XX:6060
```

**Step 1**:

- Open Grafana and add data source of Prometheus, the URL is set to `http://localhost:9010`

**Step 2**:

- Now import dashboard, the json template is from https://github.com/ledgerwatch/erigon/blob/devel/cmd/prometheus/dashboards/erigon.json

**Step 3**:

- Wait for the browser to crash. Error message says: "Templating init failed e.replace is not a function."

### 
# What Grafana version are you using?

Version 10.0.1 (commit: 5a30620b85, branch: HEAD)

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

A package manager (APT, YUM, BREW, etc.)

### User's OS?

Ubuntu 20.04.6

### User's Browser?

Google Chrome

### Is this a Regression?

None

### Anything else to add?

This bug does not seem to be the first time it has appeared, and many people have mentioned it before
- https://community.grafana.com/t/templating-namespace-error-updating-options-e-replace-is-not-a-function/66691/1
- https://github.com/grafana/grafana/issues/28714

Their fix was to upgrade grafana, but the version we're currently using is the latest.
