### ISSUE TITLE
Alerting: contact point/notifications policies pages are broken "scheme required for webhook url"

### ISSUE THREAD

**Issue by bdossantos** [grafana/grafana#71364]
### 
# What went wrong?

**What happened**:

  - I use Grafana with Alertmanager datasource (mimir)
  - When I define a `webhook_configs` receivers, I have an error on contacts points and notications policies pages
  - When I omit `webhook_configs` alertmanager receivers block,  pages are working and restitute the state of my alertmanager configuration

**What did you expect to happen**:

  - Contact points and notifications policies pages are working when I define a `webhook_configs` receivers in my alertmanager configuration

### 
# How do we reproduce it?

**Step 1**:

- Define an alert manager configuration with a webhook configuration block, eg:

```
global:
  resolve_timeout: 5m
  http_config:
    follow_redirects: true
    enable_http2: true
  smtp_hello: localhost
  smtp_require_tls: true
  slack_api_url: <secret>
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  opsgenie_api_url: https://api.eu.opsgenie.com/
  opsgenie_api_key: <secret>
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
  telegram_api_url: https://api.telegram.org
  webex_api_url: https://webexapis.com/v1/messages

route:
  receiver: slack
  group_by:
  - alertname
  - severity
  continue: false
  routes:
  - receiver: "null"
    matchers:
    - alertname=~"KubeAPIErrorBudgetBurn|InfoInhibitor|KubeClientCertificateExpiration"
    continue: false
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h

inhibit_rules:
- source_matchers:
  - severity="critical"
  target_matchers:
  - severity=~"warning|info"
  equal:
  - namespace
  - alertname
- source_matchers:
  - severity="warning"
  target_matchers:
  - severity="info"
  equal:
  - namespace
  - alertname
- source_matchers:
  - alertname="InfoInhibitor"
  target_matchers:
  - severity="info"
  equal:
  - namespace

receivers:
  - name: "null"
  - name: "opsgenie-heartbeat"
     webhook_configs:
       - url: 'https://api.eu.opsgenie.com/v2/heartbeats/redacted/ping'
          send_resolved: true
          http_config:
              authorization:
                type: GenieKey
                credentials: REDACTED
templates: []
```

**Step 2**:

- Add this Grafana alertmanager datasource (ideally mimir)

**Step 3**:

- Try to access "Notification policies" or "Contacts points" pages

<img width="1066" alt="Screenshot 2023-07-11 at 14 48 55" src="https://github.com/grafana/grafana/assets/245284/61f217dd-3cdb-4295-92cf-e153c57bf5f2">

### 
# What Grafana version are you using?

10.0.1 and 10.0.2

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### Is this a Regression?

None

**Comment by santihernandezc** [comment]
I was not able to reproduce the issue in v10.0.1. I used a Mimir Alertmanager and both screens load correctly.

![Screenshot 2023-07-14 at 14 07 30](https://github.com/grafana/grafana/assets/41638679/b3e671d2-00f1-4d6a-a313-f30245bf3aa3)

I had to fix the example configuration you pasted here, there were a few problems (indentation, reference to a non-existing receiver). I used the following configuration, uploading it via [mimirtool](https://grafana.com/docs/mimir/latest/operators-guide/tools/mimirtool/):

```yaml
global:
  resolve_timeout: 5m
  http_config:
    follow_redirects: true
    enable_http2: true
  smtp_hello: localhost
  smtp_require_tls: true
  slack_api_url: <secret>
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  opsgenie_api_url: https://api.eu.opsgenie.com/
  opsgenie_api_key: <secret>
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
  telegram_api_url: https://api.telegram.org
  webex_api_url: https://webexapis.com/v1/messages

route:
  receiver: opsgenie-heartbeat
  group_by:
    - alertname
    - severity
  continue: false
  routes:
    - receiver: "null"
      matchers:
        - alertname=~"KubeAPIErrorBudgetBurn|InfoInhibitor|KubeClientCertificateExpiration"
      continue: false
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h

inhibit_rules:
  - source_matchers:
      - severity="critical"
    target_matchers:
      - severity=~"warning|info"
    equal:
      - namespace
      - alertname
  - source_matchers:
      - severity="warning"
    target_matchers:
      - severity="info"
    equal:
      - namespace
      - alertname
  - source_matchers:
      - alertname="InfoInhibitor"
    target_matchers:
      - severity="info"
    equal:
      - namespace

receivers:
  - name: "null"
  - name: "opsgenie-heartbeat"
    webhook_configs:
      - url: 'https://api.eu.opsgenie.com/v2/heartbeats/redacted/ping'
        send_resolved: true
        http_config:
          authorization:
            type: GenieKey
            credentials: REDACTED
templates: []
```

You can use Mimirtool to [validate your configuration](https://grafana.com/docs/mimir/latest/operators-guide/tools/mimirtool/#validate-alertmanager-configuration) and fix any errors. If your config is ok and the problem persists, please give us more details about your setup, your Alertmanager configuration, and precise steps to reproduce the issue.

**Comment by bdossantos** [comment]
Hi ! 

Sorry ! The previous configuration was not complete ... I cheated a little to hide "sensitive" infos in routes name, namespaces, etc.

I'm still able to reproduce the bug with the following configuration. Tokens, company name, and sensitive namespaces name are obfuscated : 

```yaml
global:
  resolve_timeout: 5m
  opsgenie_api_url: https://api.eu.opsgenie.com/
  opsgenie_api_key: xxx-xxx-xxx-xxx-xxx-xxx
  slack_api_url: https://hooks.slack.com/services/xxx/xxx

inhibit_rules:
  - source_matchers:
      - severity="critical"
    target_matchers:
      - severity=~"warning|info"
    equal:
      - namespace
      - alertname
  - source_matchers:
      - severity="warning"
    target_matchers:
      - severity="info"
    equal:
      - namespace
      - alertname
  - source_matchers:
      - alertname="InfoInhibitor"
    target_matchers:
      - severity="info"
    equal:
      - namespace

route:
  group_by:
    - alertname
    - severity
  group_interval: 5m
  group_wait: 30s
  receiver: "slack"
  repeat_interval: 12h
  routes:
    # FIXME: enable deadman switch when fully migrated to mimir
    - matchers:
        - alertname="Watchdog"
      repeat_interval: 60s
      receiver: "opsgenie-redacted-heartbeat"
    - matchers:
        - alertname=~"KubeAPIErrorBudgetBurn|InfoInhibitor|KubeClientCertificateExpiration"
      receiver: "null"
    - matchers:
        - alertname=~"PodRestartTooOften|PodRestartTooOftenCritical|KubePodCrashLooping|KubernetesContainerOomKilled"
        - namespace=~"newzzz-(.*)|ns-zzzlook-(.*)"
        - cluster="nonprd-dmz"
      receiver: "slack-frontendeco-alerts"
    - matchers:
        - namespace!~"elastic-kafka|fluentd-kafka|rabbitmq-system|ns-beszzz-(.*)|ns-digitalzzzz-(.*)|ns-myzzzz-(.*)|ns-presales-(.*)|ns-scd-(.*)|ns-selenium-server|ns-lemonzzzzz-(.*)|ns-zzzzzzz-(.*)|ns-bzzz-(.*)|ns-dag-(.*)|ns-mysupport-(.*)|ns-wizzzzz-(.*)"
        - severity="critical"
        - cluster="prd-dmz"
      receiver: "opsgenie-redacted"

receivers:
  - name: "null"
  - name: "slack"
    slack_configs:
      - send_resolved: true
        channel: "#kubernetes-prd-dmz-events"
        title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring Event Notification'
        text: |-
          {{ range .Alerts }}
            *Alert:* `{{ .Labels.severity }}` - {{ .Labels.alertname }} - {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
            *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:> *Runbook:* <{{ .Annotations.runbook }}|:spiral_note_pad:>
            *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
  - name: "slack-frontendeco-alerts"
    slack_configs:
      - api_url: https://hooks.slack.com/services/xxx
        channel: "#frontendeco-dev-alerts"
        send_resolved: true
        title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring Event Notification'
        text: |-
          {{ range .Alerts }}
            *Alert:* `{{ .Labels.severity }}` - {{ .Labels.alertname }} - {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
            *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:> *Runbook:* <{{ .Annotations.runbook }}|:spiral_note_pad:>
            *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
  # FIXME: enable deadman switch when fully migrated to mimir
  - name: "opsgenie-redacted-heartbeat"
    webhook_configs:
      - url: "https://api.eu.opsgenie.com/v2/heartbeats/xxx/ping"
        send_resolved: true
        http_config:
          authorization:
            type: GenieKey
            credentials: xxx-xxx-xxx-xxx-xxx-xxx-xxx-xxx
  - name: "opsgenie-redacted"
    opsgenie_configs:
      - send_resolved: true
```

And I'm able to load grafana page when I comment the following block

```yaml
  # FIXME: enable deadman switch when fully migrated to mimir
  - name: "opsgenie-redacted-heartbeat"
    webhook_configs:
      - url: "https://api.eu.opsgenie.com/v2/heartbeats/xxx/ping"
        send_resolved: true
        http_config:
          authorization:
            type: GenieKey
            credentials: xxx-xxx-xxx-xxx-xxx-xxx-xxx-xxx
```

My conf was extracted with kubectl cp from Mimir's alertmanager pod, and configuration seem valid when I test it thanks to mirmirtool.

Last thing, all my conf is injected to Mimir via `alertmanager.fallbackConfig:` yaml key. I can send you the full non-redacted config (except tokens :)) if needed.

**Comment by gillesdemey** [comment]
This is most definitely an exception that is coming from [upstream Alertmanager](https://github.com/prometheus/alertmanager/blob/487db1383b8cc5c2867c77f110431605bb8ce247/config/notifiers.go#L506-L510) – which makes me wonder if the YAML config is being correctly unmarshalled

**Comment by kelt1k** [comment]
I still have this issue when I'm using not credentials but credentials_file which is mounted to alertmanager as secret 
like this 
```
http_config:
          authorization:
            type: GenieKey
            credentials_file: /tmp/secrets/opsgenie-heartbeat/token
```

**Comment by gillesdemey** [comment]
I think we're stuck at "cannot reproduce" – I've uploaded the following config to my Mimir Alertmanager and cannot manage to reproduce the error. Perhaps this bug is dependent on a specific version of Mimir or Alertmanager? Can you list out the versions of Alertmanager / Mimir you're interacting with? Can you reproduce on the latest version of those?

```yaml
- name: "opsgenie-redacted-heartbeat"
    webhook_configs:
      - url: "https://api.eu.opsgenie.com/v2/heartbeats/xxx/ping"
        send_resolved: true
        http_config:
          authorization:
            type: GenieKey
            credentials: xxx-xxx-xxx-xxx-xxx-xxx-xxx-xxx
```

**Comment by bdossantos** [comment]
I use Mimir installed via helm chart `4.5.0-weekly.243`. I'll try to upgrade to last helm chart version `5.1.0-weekly.247`

**Comment by kelt1k** [comment]
tried today with this config 
```
global:
  resolve_timeout: 5m
  http_config:
    follow_redirects: true
    enable_http2: true
  smtp_hello: localhost
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
  telegram_api_url: https://api.telegram.org
  webex_api_url: https://webexapis.com/v1/messages
route:
  receiver: "null"
  group_by:
  - brand
  - alertname
  - severity
  - k8s_cluster
  - consumergroup
  continue: false
  routes:
  - receiver: heartbeat
    matchers:
    - alertname="Watchdog"
    continue: false
  - receiver: "null"
    matchers:
    - alertname=~"InfoInhibitor|KubeSchedulerDown|KubeControllerManagerDown|KubeAggregatedAPIDown"
    continue: false
  - receiver: opsgenie-techops
    matchers:
    - k8s_cluster=~"prod|monitoring"
    - severity=~"critical"
    continue: false
  - receiver: opsgenie
    matchers:
    - k8s_cluster=~"auto|test|dev|ci"
    - severity=~"warning|critical"
    continue: false
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 30m
inhibit_rules:
- source_matchers:
  - severity="critical"
  target_matchers:
  - severity=~"critical"
  equal:
  - namespace
  - alertname
- source_matchers:
  - severity="warning"
  target_matchers:
  - severity="warning"
  equal:
  - namespace
  - alertname
- source_matchers:
  - alertname="InfoInhibitor"
  target_matchers:
  - severity="info"
  equal:
  - namespace
receivers:
- name: "null"
- name: opsgenie
  opsgenie_configs:
  - send_resolved: true
    http_config:
      follow_redirects: true
      enable_http2: true
    api_key_file: /tmp/secrets/opsgenie/opsgenie-alertmanager-api
    api_url: https://api.opsgenie.com/
    message: '[{{ if eq .GroupLabels.severity "critical" }}P1{{ else if eq .GroupLabels.severity
      "warning" }}P2{{ else if eq .GroupLabels.severity "info" }}P3{{ else }}P4{{
      end }}] {{ .GroupLabels.alertname }}'
    description: "{{ if gt (len .Alerts.Firing) 0 -}}\nAlerts Firing:\n{{ range .Alerts.Firing
      }}\nMessage: {{ .Annotations.description }}   \n{{ if gt (len .Annotations.dashboard)
      0 -}}\nDashboard: {{ .Annotations.dashboard }}\n{{ end }}\nRunbook_url: {{ .Annotations.runbook_url
      }}\n{{ end }}\n{{- end }}\n{{ if gt (len .Alerts.Resolved) 0 -}}\nAlerts Resolved:\n{{
      range .Alerts.Resolved }}\nMessage: {{ .Annotations.description }}  \n{{ if
      gt (len .Annotations.dashboard) 0 -}}\nDashboard: {{ .Annotations.dashboard
      }}\n{{ end }}\n{{ end }}\n{{- end }}"
    source: '{{ template "opsgenie.default.source" . }}'
    details:
      alertname: '{{ .GroupLabels.alertname }}'
      deployment: '{{- if .CommonLabels.deployment -}}{{- .CommonLabels.deployment
        -}}{{- end -}}'
      k8s_cluster: '{{ .CommonLabels.k8s_cluster }}'
      namespace: '{{- if .CommonLabels.exported_namespace -}}{{- .CommonLabels.exported_namespace
        -}}{{- else if .CommonLabels.namespace -}}{{- .CommonLabels.namespace -}}{{-
        end -}}'
      pod: '{{- if .CommonLabels.pod -}}{{- .CommonLabels.pod -}}{{- end -}}'
      severity: '{{ .GroupLabels.severity }}'
    tags: '{{ .CommonLabels.k8s_cluster }}, {{ .GroupLabels.severity }}, {{ .GroupLabels.alertname
      }}, {{ .GroupLabels.namespace }}, {{ range $key, $value := .CommonLabels -}}
      {{ if match "^component.*" "$key" -}} {{ $key }}, {{ end -}} {{ end }}'
    priority: '{{ if eq .GroupLabels.severity "critical" }}P1{{ else if eq .GroupLabels.severity
      "warning" }}P2{{ else if eq .GroupLabels.severity "info" }}P3{{ else }}P4{{
      end }}'
- name: opsgenie-sss
  opsgenie_configs:
  - send_resolved: true
    http_config:
      follow_redirects: true
      enable_http2: true
    api_key_file: /tmp/secrets/opsgenie-sss/opsgenie-sss-alertmanager-api
    api_url: https://api.opsgenie.com/
    message: '[{{ if eq .GroupLabels.severity "critical" }}P1{{ else if eq .GroupLabels.severity
      "warning" }}P2{{ else if eq .GroupLabels.severity "info" }}P3{{ else }}P4{{
      end }}] {{ .CommonAnnotations.summary}}'
    description: "{{ if gt (len .Alerts.Firing) 0 -}}\nAlerts Firing:\n{{ range .Alerts.Firing
      }}\nMessage: {{ .Annotations.description }}   \n{{ if gt (len .Annotations.dashboard)
      0 -}}\nDashboard: {{ .Annotations.dashboard }}\n{{ end }}\nRunbook_url: {{ .Annotations.runbook_url
      }}\n{{ end }}\n{{- end }}\n{{ if gt (len .Alerts.Resolved) 0 -}}\nAlerts Resolved:\n{{
      range .Alerts.Resolved }}\nMessage: {{ .Annotations.description }}  \n{{ if
      gt (len .Annotations.dashboard) 0 -}}\nDashboard: {{ .Annotations.dashboard
      }}\n{{ end }}\n{{ end }}\n{{- end }}"
    source: '{{ template "opsgenie.default.source" . }}'
    details:
      alertname: '{{ .GroupLabels.alertname }}'
      deployment: '{{- if .CommonLabels.deployment -}}{{- .CommonLabels.deployment
        -}}{{- end -}}'
      k8s_cluster: '{{ .CommonLabels.k8s_cluster }}'
      namespace: '{{- if .CommonLabels.exported_namespace -}}{{- .CommonLabels.exported_namespace
        -}}{{- else if .CommonLabels.namespace -}}{{- .CommonLabels.namespace -}}{{-
        end -}}'
      pod: '{{- if .CommonLabels.pod -}}{{- .CommonLabels.pod -}}{{- end -}}'
      severity: '{{ .GroupLabels.severity }}'
    tags: '{{ .CommonLabels.k8s_cluster }}, {{ .GroupLabels.severity }}, {{ .GroupLabels.alertname
      }}, {{ .GroupLabels.namespace }}, {{- if .CommonLabels.exported_namespace -}}{{
      .CommonLabels.exported_namespace }},{{- end -}}'
    priority: '{{ if eq .GroupLabels.severity "critical" }}P1{{ else if eq .GroupLabels.severity
      "warning" }}P2{{ else if eq .GroupLabels.severity "info" }}P3{{ else }}P4{{
      end }}'
- name: opsgenie-techops
  opsgenie_configs:
  - send_resolved: true
    http_config:
      follow_redirects: true
      enable_http2: true
    api_key_file: /tmp/secrets/opsgenie-techops/opsgenie-techops-alertmanager-api
    api_url: https://api.opsgenie.com/
    message: '[{{ if eq .GroupLabels.severity "critical" }}P1{{ else if eq .GroupLabels.severity
      "warning" }}P2{{ else if eq .GroupLabels.severity "info" }}P3{{ else }}P4{{
      end }}] {{ .CommonAnnotations.summary }}'
    description: "{{ if gt (len .Alerts.Firing) 0 -}}\nAlerts Firing:\n{{ range .Alerts.Firing
      }}\nMessage: {{ .Annotations.description }}   \n{{ if gt (len .Annotations.dashboard)
      0 -}}\nDashboard: {{ .Annotations.dashboard }}\n{{ end }}\nRunbook_url: {{ .Annotations.runbook_url
      }}\n{{ end }}\n{{- end }}\n{{ if gt (len .Alerts.Resolved) 0 -}}\nAlerts Resolved:\n{{
      range .Alerts.Resolved }}\nMessage: {{ .Annotations.description }}  \n{{ if
      gt (len .Annotations.dashboard) 0 -}}\nDashboard: {{ .Annotations.dashboard
      }}\n{{ end }}\n{{ end }}\n{{- end }}"
    source: '{{ template "opsgenie.default.source" . }}'
    details:
      alertname: '{{ .GroupLabels.alertname }}'
      deployment: '{{- if .CommonLabels.deployment -}}{{- .CommonLabels.deployment
        -}}{{- end -}}'
      k8s_cluster: '{{ .CommonLabels.k8s_cluster }}'
      namespace: '{{- if .CommonLabels.exported_namespace -}}{{- .CommonLabels.exported_namespace
        -}}{{- else if .CommonLabels.namespace -}}{{- .CommonLabels.namespace -}}{{-
        end -}}'
      pod: '{{- if .CommonLabels.pod -}}{{- .CommonLabels.pod -}}{{- end -}}'
      severity: '{{ .GroupLabels.severity }}'
    tags: '{{ .CommonLabels.k8s_cluster }}, {{ .GroupLabels.severity }}, {{ .GroupLabels.alertname
      }}, {{ .GroupLabels.namespace }}, {{- if .CommonLabels.exported_namespace -}}{{
      .CommonLabels.exported_namespace }},{{- end -}}, {{- if .CommonLabels.component
      -}}{{ .CommonLabels.component }},{{- end -}}'
    priority: '{{ if eq .GroupLabels.severity "critical" }}P1{{ else if eq .GroupLabels.severity
      "warning" }}P2{{ else if eq .GroupLabels.severity "info" }}P3{{ else }}P4{{
      end }}'
- name: heartbeat
  webhook_configs:
  - send_resolved: false
    http_config:
      authorization:
        type: GenieKey
        credentials: <secret>
      follow_redirects: true
      enable_http2: true
    url: <secret>
    url_file: ""
    max_alerts: 0
templates: []
```

I'm using mimir-distributed chart version 4.5.0 image: grafana/mimir:2.9.0

**Comment by j-sokol** [comment]
Hi all, we have the same issue. 

Few details that I haven't seen here in the thread: 

The error in Grafana `Error loading Alertmanager config
unsupported scheme "" for URL` happens when using following fallback config in Mimir:
``` 
    receivers:
    - name: 'monapi'
      webhook_configs:
      - send_resolved: true
        url: 'http://alerts2monapi-default:80/alert' # monitoring-api forwarder
    route:
      group_by: ['alertname', 'service']
      group_wait: 30s
      group_interval: 1m
      repeat_interval: 1m
      receiver: 'monapi'
```

Interesting thing is that when we upload the same config to a tenant (using mimirtool), then error in Grafana disappears.

Alertmanager UI is able to show both fallback and tenant specific configs.

We're running mimir 2.9.0, Grafana 9.5.2
