### ISSUE TITLE
Alerting: Provisioning does not correctly merge when renaming last receiver

### ISSUE THREAD

**Issue by JacobsonMT** [grafana/grafana#71619]
### Description
When moving the last provisioned receiver in a contact point to another contact point, provisioning will create two contact points of the same name instead of merging them.
 
This should affect both terraform and file provisioning.

### Reproduction steps

1. Start a fresh Grafana instance and database.
2. Provision Grafana with the following alerting file:

```yaml
  - orgId: 1
    name: default contact
    receivers:
      - uid: b9bf06f8-bde2-4438-9d4a-bba0522dcd4d
        type: pagerduty
        settings:
          client: some client
          integrationKey: some key
          severity: criticalish
        disableResolveMessage: false
  - orgId: 1
    name: slack test
    receivers:
      - uid: cbfd0976-8228-4126-b672-4419f30a9e50
        type: slack
        settings:
          text: title body test
          title: title test
          url: some secure slack webhook
        disableResolveMessage: true
```
3. Move one receiver to the other contact point:
```yaml
  - orgId: 1
    name: default contact
    receivers:
      - uid: b9bf06f8-bde2-4438-9d4a-bba0522dcd4d
        type: pagerduty
        settings:
          client: some client
          integrationKey: some key
          severity: criticalish
        disableResolveMessage: false
      - uid: cbfd0976-8228-4126-b672-4419f30a9e50
        type: slack
        settings:
          text: title body test
          title: title test
          url: some secure slack webhook
        disableResolveMessage: true
```

Now there will be two contact points with the name `default contact`, one with each receiver.

### Expectation

1. There should be a single contact point with both receivers with the name `default contact`.
2. All references to `slack test` in notification policies should be renamed to `default contact` (Maybe not necessary?)
