### ISSUE TITLE
Grafana does not interpret last element of auth okta allowed_groups array

### ISSUE THREAD

**Issue by damlys** [grafana/grafana#71756]
### What happened?

Grafana throws an error on "Login with Okta":

```
logger=context userId=0 orgId=0 uname= t=2023-07-17T10:26:12.208474928Z level=error msg="login.OAuthLogin(get info from okta)" error="user not a member of one of the required groups"
```

### What did you expect to happen?

I would like to login with Okta.

### Did this work before?

No. It's our first try to integrate Grafana with Okta.

### How do we reproduce it?

1. Deploy Grafana with following configuration
    ```
    grafana.ini:
      auth.okta:
        name: Okta
        icon: okta
        enabled: true
        client_id: SECRET
        client_secret: SECRET
        scopes: openid profile email groups offline_access
        auth_url: SECRET
        token_url: SECRET
        api_url: SECRET
        allowed_domains: >
          example.com
        allowed_groups:
          - Example::DevOps
          - Example::Dev
          - Example::QA
        role_attribute_path: >
          contains(groups[*], 'Example::DevOps') && 'Admin'
          || contains(groups[*], 'Example::Dev') && 'Editor'
          || 'Viewer'
        allow_sign_up: true
        use_pkce: true
    ```
1. Try to login with okta
1. See `level=error msg="login.OAuthLogin(get info from okta)" error="user not a member of one of the required groups"` log in a console
1. Modify `allowed_groups` like that
    ```
    allowed_groups:
      - Example::DevOps
      - Example::Dev
      - Example::QA
      - this-group-does-not-exists
    ```
1. Try to login with okta
1. You are logged in

### Environment (with versions)?

Grafana: v9.2.0 (c7eea48209)
OS: macOS
Browser: Chrome

### Grafana platform?

Kubernetes

**Comment by damlys** [comment]
Btw. I think Grafana is not interpret last element of `allowed_groups` array 🤔

**Comment by Jguer** [comment]
Hey @damlys , thanks for submitting this issue, I've tried to reproduce it in the grafana configuration using the `grafana.ini` directly. allowed_groups is a string in the configuration

JSON list

```ini
[auth.okta]
allowed_groups = ["Example::DevOps", "Example::Dev", "Example::QA"]
```

results in the parsed allowedGroups:
```
[]string len: 3, cap: 4, ["Example::DevOps","Example::Dev","Example::QA"]
```

---

JSON List with end comma (potential mistake)

```ini
[auth.okta]
allowed_groups = ["Example::DevOps", "Example::Dev", "Example::QA",]
```

results in the parsed allowedGroups:
```
[]string len: 0, cap: 0, []
```

---

Space divided

```ini
[auth.okta]
allowed_groups = Example::DevOps Example::Dev Example::QA
```

results in the parsed allowedGroups:
```
[]string len: 3, cap: 3, ["Example::DevOps","Example::Dev","Example::QA"]
```

The evaluation should not pose issues if the `s.allowedGroups` was parsed correctly
https://github.com/grafana/grafana/blob/0ffd3598018e728a3b5fc249dd7212ce11d166da/pkg/login/social/okta_oauth.go#L142

--- 

I think changing your `allowed_groups` to a string will fix your issue. This space separated approach only works when groups do not have whitespace. You'd need to escape a JSON list to work with groups with whitespace in their names 

```
grafana.ini:
  auth.okta:
    name: Okta
    icon: okta
    enabled: true
    client_id: SECRET
    client_secret: SECRET
    scopes: openid profile email groups offline_access
    auth_url: SECRET
    token_url: SECRET
    api_url: SECRET
    allowed_domains: >
      example.com
    allowed_groups: "Example::DevOps Example::Dev Example::QA"
    role_attribute_path: >
      contains(groups[*], 'Example::DevOps') && 'Admin'
      || contains(groups[*], 'Example::Dev') && 'Editor'
      || 'Viewer'
    allow_sign_up: true
    use_pkce: true
```

I still find it curious that your list implementation works, maybe create an issue on https://github.com/grafana/helm-charts/ for the maintainers to investigate why the last value is cut off
