### ISSUE TITLE
[doc] skipTLSVerify -> tlsSkipVerify

### ISSUE THREAD

**Issue by sed-i** [grafana/grafana#72237]
**What is the chore?**:
Doc has incorrect entry:

https://github.com/grafana/grafana/blob/bc0bf0ee4baaa9060631303e1f20aec86b9fe158/docs/sources/datasources/mysql/_index.md?plain=1#L158

**Is there anything else we need to know?**:
The correct key is `tlsSkipVerify`.

**Comment by usmangt** [comment]
Hi @sed-i,

Thanks for opening this issue.

I will forward this to our Engineers so that they can have a look and might be able to tell more details about it.

**Comment by Eve832** [comment]
@lwandz13 can you take a look at this?

**Comment by lwandz13** [comment]
@matyax Can you confirm this should be tlsSkipVerify.

**Comment by matyax** [comment]
@lwandz13 While this is not a data source that my squad is resposible for, I checked the config page in Grafana and the correct key is `tlsSkipVerify` , or at least the one that is configured by that form.

**Comment by matyax** [comment]
https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/mysql/configuration/ConfigurationEditor.tsx#L149-L150

**Comment by lwandz13** [comment]
thank you @matyax

**Comment by joe-macmillan** [comment]
In relation to this key name issue, I have come across the following issue:
**Issue Description:**

On grafana/grafana:10.3.3, provisioning the Chaos Mesh data source with the following YAML configuration does not activate the "Skip TLS Verify" toggle in the data source configuration section:

```yaml
- name: 'Chaos Mesh'
  type: 'chaosmeshorg-datasource'
  access: proxy
  url: https://<chaose-dashboard-url>
  uid: ChaosMeshDataSource
  jsonData:
    tlsSkipVerify: true
  version: 1
```

Neither does the following configuration work:

```yaml
- name: 'Chaos Mesh'
  type: 'chaosmeshorg-datasource'
  access: proxy
  url: https://<chaose-dashboard-url>
  uid: ChaosMeshDataSource
  secureJsonData:
    tlsSkipVerify: true
  version: 1
```
Nor does this:
```yaml
- name: 'Chaos Mesh'
  type: 'chaosmeshorg-datasource'
  access: proxy
  url: https://<chaose-dashboard-url>
  uid: ChaosMeshDataSource
  jsonData:
    skipTLSVerify: true
  version: 1
```

Other values, such as `name` and `url`, seem to be provisioning correctly. However, if I configure the data source manually on the Grafana dashboard, the "Skip TLS Verify" toggle works fine. I expected the provisioning configuration to be as effective as the manual configuration. it seems to be a key name issue.
