### ISSUE TITLE
Grafana UI Login: Can't login to Grafana UI with own Grafana admin credentials

### ISSUE THREAD

**Issue by sshingarapu** [grafana/grafana#72639]
### What happened?

Grafana Operator Version: https://github.com/grafana-operator/grafana-operator/tree/v5.2.0
Environment: GKE
Grafana Version: 10.0.1

Deployed Grafana through grafana operator using helm chart. I had set the admin credentials as user **root** and password **security**. 

Kubernetes secret is created with the above credentials.

```
  apiVersion: v1
  data:
      admin-password: secret
      admin-user: root
   kind: Secret 
  metadata:
    annotations:
      meta.helm.sh/release-name: grafana-operator
      meta.helm.sh/release-namespace: grafana-test2
    creationTimestamp: "2023-07-31T17:40:31Z"
    labels:
      app.kubernetes.io/managed-by: Helm
    name: grafana-deploy-secret
    namespace: grafana-test2
  type: Opaque
```

Referring the above secret in grafana deployment

```
    env:
                - name: GF_SECURITY_ADMIN_USER
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.grafana.clusterName }}-secret
                      key: admin-user
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.grafana.clusterName }}-secret
                      key: admin-password
```

I am able to login with the configured credentials root/secret.

The issue is, If i change the credentials to admin/admin or testadmin/testpassword then can't login to grafana UI and it is throwing the error Invalid username or password.

I can login with only the credentials root and security.

### What did you expect to happen?

I should be able to login with any other credentials which I set other than root/secret.

### Did this work before?

NO

### How do we reproduce it?

1. Deploy grafana operator version 5.2.0
2. Deploy grafana version 10.0.1
3. Create kubernetes secret with admin-user(testadmin) and admin-password(testpassword) 
4. Refer the above secret in grafana deployment. 
5. Now try to login to Grafana UI with the above credentials. It will throw you Invalid username or password

### Environment (with versions)?

Grafana version: v10.0.1 (https://github.com/grafana/grafana/tree/v10.0.1)

### Grafana platform?

Kubernetes
