### ISSUE TITLE
Loki: Multiple log queries are truncated between streams without indication

### ISSUE THREAD

**Issue by hterik** [grafana/grafana#72657]
### What happened?

Assuming Grafana is configured to only fetch max 1000 lines per Loki log query. `maxLines:1000`

If user queries from 2 log streams simultaneously. Each containing 3000 lines within the given query interval.
Then each stream will _individually_ be cut after 1000 lines.  If the time range of the files overlap, this creates a discontinuity in the presented log, as it will first display the oldest 1000 lines from a.log, and then the oldest 1000 lines from b.log -- even if the subsequent 2000 lines in a.log may come earlier.

There is no warning about this, other than the very faint _"Line limit:6 reached"_, which is presented above the log, instead of in the middle where the truncation happens.

Clicking on **Older logs** to find the logs within this cutoff is impossible, since the older logs button takes the offset from the oldest of both streams.

### What did you expect to happen?

Suggestion A: Log output should contain a warning interleaved with the logs whenever any of the log streams get truncated, at the point of cut off.
Suggestion B: In this warning, there should be an alternative to **Older logs** button, that uses the oldest returned entry of a.log, instead of using the oldest entry from both logs.

### Did this work before?

No

### How do we reproduce it?

**datasources.yaml:**
```yaml
datasources:
  - name: Loki
    type: loki
    uid: loki
    url: $LOKI_URL
    jsonData:
      maxLines: 3        # <<<< Set very short for simplicity sake in examples
```

**promtailconfig.yaml:**
```yaml
clients:
scrape_configs:
  - job_name: logfiles
    static_configs:
      - targets:
          - localhost
        labels:
          __path__: ./*.log
    pipeline_stages:
      - regex:
          source: filename
          expression: "/(?P<name>\\w+\\.log)"
      - labels:
          filename: name
      - logfmt:
          mapping:
            t:
            msg:
      - timestamp:
          source: t
          format: RFC3339
```
**a.log:** (One log entry per second, message corresponding to each second)
```
t=2023-08-01T05:01:00Z msg=A1
t=2023-08-01T05:02:00Z msg=A2
t=2023-08-01T05:03:00Z msg=A3
t=2023-08-01T05:04:00Z msg=A4
t=2023-08-01T05:05:00Z msg=A5
t=2023-08-01T05:06:00Z msg=A6
t=2023-08-01T05:07:00Z msg=A7
t=2023-08-01T05:08:00Z msg=A8
t=2023-08-01T05:09:00Z msg=A9
t=2023-08-01T05:10:00Z msg=A10
```

**b.log:** (Same as with a.log, except starting 5 seconds later)
```
t=2023-08-01T05:05:00Z msg=B5
t=2023-08-01T05:06:00Z msg=B6
t=2023-08-01T05:07:00Z msg=B7
t=2023-08-01T05:08:00Z msg=B8
t=2023-08-01T05:09:00Z msg=B9
t=2023-08-01T05:10:00Z msg=B10
t=2023-08-01T05:11:00Z msg=B11
t=2023-08-01T05:12:00Z msg=B12
t=2023-08-01T05:13:00Z msg=B13
t=2023-08-01T05:14:00Z msg=B14
t=2023-08-01T05:15:00Z msg=B15
```

Result:
![image](https://github.com/grafana/grafana/assets/89977373/6c9e917f-a2fc-45c2-b292-14e84f205d1a)

Expected result should be 
```
B15
B14
B13
B12
B11
B10
A10
B9
A9
B8
A8
etc...
A5
A4
A3
A2
A1
```

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: v10.0.3 (eb8dd72637)   (Same issue has been observed since Grafana 8)
OS: Official docker image
Browser: Firefox

### Grafana platform?

Docker

### Datasource(s)?

Loki
