### ISSUE TITLE
Oauth: can't forward oauth token with generic oauth

### ISSUE THREAD

**Issue by morvencao** [grafana/grafana#73023]
### What happened?

Added "oauthPassThru: true" to the datasource configuration:

```yaml
apiVersion: 1
datasources:
- access: proxy
  isDefault: true
  name: Observatorium
  type: prometheus
  url: http://example.observatorium.com:8080/
  jsonData:
    queryTimeout: 300s
    timeInterval: 300s
    oauthPassThru: true
```

And the configurations for Grafana are as follow:

```yaml
[auth]
disable_login_form = true
disable_signout_menu = true
[auth.basic]
enabled = false
[auth.proxy]
auto_sign_up = true
enabled = true
header_name = X-Forwarded-User
[auth.generic_oauth]
enabled = true
name = oauth
allow_sign_up = true
client_id = grafana-proxy-client
client_secret = grafana-proxy-client
scopes = openid profile
auth_url = https://oauth-provider.com/authorize
token_url = https://oauth-provider.com/token
api_url = https://oauth-provider.com/userinfo
auth_provider = generic_oauth
oauth_auto_login = true
```

Before upgrading to 8.3.x, we can see that in the request to datasources, the headers contains oauth token headers:
- `X-Forwarded-Access-Token`
- `Authorization`

After upgrading to 8.3.x, even we have added "oauthPassThru: true" to the datasource configuration, the oauth token headers are missing, and the Grafana report this error:

```
logger=oauthtoken t=2023-08-08T04:14:29.14+0000 lvl=eror msg="failed to get OAuth connector" provider=authproxy error="failed to find oauth provider for \"authproxy\""
```

### What did you expect to happen?

Grafana dashboards can be loaded successfully with metrics from cionfigured datasource. The oauth token can be passed to datasource when query data within Grafana Dashboards.

### Did this work before?

Yes

### How do we reproduce it?

1. Deploy Grafana 8.3.x or later version with configuration and datasources above.
2. Open Grafana UI and check dashboard.
3. Check if dashboards can be loaded with metrics from datasources.

### Environment (with versions)?

Grafana: 8.3.x
OS: Linux_AMD_64
Browser: Chrome

### Grafana platform?

Kubernetes

### Datasource(s)?

Observatorium
