### ISSUE TITLE
404 when using prometheus as datasource

### ISSUE THREAD

**Issue by maokitty** [grafana/grafana#73107]
### What happened?

`INFO [08-09|20:46:16] Request Completed                        logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin method=GET path=/api/prometheus/prometheus/api/v1/rules status=404 remote_addr=[::1] time_ms=3 duration=3.611002ms size=79 referer=http://localhost:3000/datasources/edit/prometheus traceID=00000000000000000000000000000000
ERROR[08-09|20:46:16] Instant query failed                     logger=tsdb.prometheus query=1+1 err="client_error: client error: 404"`

it seems  "/api/prometheus/prometheus" is unnecessary in"/api/prometheus/prometheus/api/v1/rules" 

### What did you expect to happen?

status code 200

### Did this work before?

no

### How do we reproduce it?

config in provisioning

```
apiVersion: 1
datasources:
  # Prometheus backend where metrics are sent
  - name: Prometheus
    type: prometheus
    access: server
    uid: prometheus
    url: http://localhost:9090/
    jsonData:
      #  prometheusVersion: 2.46.0
      #  prometheusType: Prometheus
        httpMethod: GET
    version: 1
  - name: Tempo
    type: tempo
    uid: tempo
    url: http://localhost:3200
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: 'prometheus'
    version: 1
```

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: grafana-9.0.9
OS: mac
prometheus: 2.46.0

### Grafana platform?

A downloaded binary
