### ISSUE TITLE
Grafana 9.2.10: Not able to delete alert rule after deleting dashboard and Data source 

### ISSUE THREAD

**Issue by vivekmakvana** [grafana/grafana#73212]
### What happened?

- I am not getting data of specific windows server host but it was showing up into Prometheus target.
- So, I think made mistake into data source configuration and decide to delete it.
- After deleting the data source and dashboard not able to delete alerts rule. getting error "Error: invalid rule specification at index [0]: failed to validate condition of alert rule 154 Server: failed to build query 'A': data source not found".

### What did you expect to happen?

I think after deleting Data Source and re configure it my server will visible to dashboard.

### Did this work before?

I tried this first time

### How do we reproduce it?

1. Please do that when we delete Data Source alert should be deleted with it.

### Is the bug inside a dashboard panel?

Yes

### Environment (with versions)?

Grafana: 9.2
OS: CentOS 8
Browser: edge, Chrome, Brave

### Grafana platform?

Other

### Datasource(s)?

Prometheus

**Comment by damianszczepanik** [comment]
I observe same error with Grafana v9.5.7

My case is that I have imported configurations from Grafana 8.5 and now I put everything into git so Grafana provisions configuration from files.

```
Labels
alertname 	DatasourceError
grafana_folder 	General Alerting
rule_uid 	e7790de7-042d-4dc1-981d-b8def3249662
rulename 	Blue CPU Load alert

Annotations
Error 	failed to build query 'B': data source not found
```

I have checked query and panels and everything looks fine. How can I get more information what is wrong and how to fix it?

**Comment by yuri-tceretian** [comment]
It looks like a duplicate of https://github.com/grafana/grafana/issues/64593 which was fixed https://github.com/grafana/grafana/pull/68667 and released in version 10.1. In the issue there are some ways to work around the problem like [this](https://github.com/grafana/grafana/issues/64593#issuecomment-1473793078). Please try it.

**Comment by damianszczepanik** [comment]
So i found in alerting entries like this:
```
              datasourceUid: b2sikXdGk
              model:
                datasource:
                    type: influxdb
                    uid: b2sikXdGk
```
and changed it manually to `uid` that was defined in datasource provisioning:
```
              datasourceUid: InfluxDB-telegraf_docker
              model:
                datasource:
                    type: influxdb
                    uid: InfluxDB-telegraf_docker
```

After that change alerting started to work and problem has gone
