### ISSUE TITLE
Auth: Okta OAuth2 doc(use_pkce) is wrong.

### ISSUE THREAD

**Issue by arukiidou** [grafana/grafana#73754]
### What happened?

[Okta OAuth2 doc](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/okta/#configuration-options) is wrong.

![image](https://github.com/grafana/grafana/assets/10738333/8b5531fb-772b-4c34-ac2a-67de677bb3e6)

|  version  |  defaults.ini  | docs  |  collect?  |
|------------------------|-----------------------------------------------|-----------------------------------------------|-----------------------------------------------|
|  v10.0.x  | false  |  false  |  ✅Yes  |
|  v10.1.0  | true  |  false | ❌No  |

### What did you expect to happen?

- After  [v10.1.0](https://github.com/arukiidou/grafana/blob/05c386504b17c322ed72b7b9dc1e5b989b2e0af7/conf/defaults.ini#L629), `use_pkce = true` by default.
  - see: #68073

### Did this work before?

Yes

|  version  |  defaults.ini  | docs  |  collect  |
|------------------------|-----------------------------------------------|-----------------------------------------------|-----------------------------------------------|
|  v10.0.x  | false  |  false  |  ✅Yes  |
|  v10.1.0  | true  |  false | ❌No  |
|  (after fix)  | true  |  true  |  ✅yes   |

### How do we reproduce it?

1. see: https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/okta/
2. see: https://github.com/arukiidou/grafana/blob/05c386504b17c322ed72b7b9dc1e5b989b2e0af7/conf/defaults.ini#L629

- also reproduce docker compose

```
services:
  grafana:
    image: grafana/grafana:10.1.0
    restart: always
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: "grafana"
      GF_SECURITY_ADMIN_PASSWORD: "grafana"
```

![image](https://github.com/grafana/grafana/assets/10738333/f39ccec5-07c8-4f6f-a87d-99b5c363ceb9)

### Environment (with versions)?

Grafana: v10.1.0
OS: any
Browser: any

### Grafana platform?

None
