### ISSUE TITLE
Docker: Can't change admin password in CLI using Swarm Secrets with MySQL as Database

### ISSUE THREAD

**Issue by Trufelli** [grafana/grafana#73921]
### What happened?

Here is my Grafana Stack, using Swarm secrets to pass my Database user password with variable "GF_DATABASE_PASSWORD__FILE":

```
version: "3.9"

services:
  grafana-db:
    image: grafana-db
    environment:
      MARIADB_DATABASE: grafana
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/grafanadb_root_pw
    networks:
      - backend
    secrets:
      - grafanadb_root_pw
      - grafanadb_gwadmingrafana_pw

  grafana:
    image: grafana
    depends_on:
      - grafana-db
    ports:
      - 8080:8080
    environment:
      GF_DATABASE_TYPE: "mysql"
      GF_DATABASE_HOST: "grafana-db:3306"
      GF_DATABASE_NAME: "grafana"
      GF_DATABASE_USER: "gwadmingrafana"
      GF_DATABASE_PASSWORD__FILE: /run/secrets/grafanadb_gwadmingrafana_pw
      GF_SERVER_HTTP_PORT: "8080"
    networks:
      - frontend
      - backend
    secrets:
      - grafanadb_gwadmingrafana_pw

networks:
  frontend:
  backend:
secrets:
  grafanadb_root_pw:
    external: true
  grafanadb_gwadmingrafana_pw:
    external: true
```

When I try to change my Admin password in CLI:

`grafana-cli admin reset-admin-password password`

This is the output that I get:

```
ERROR[08-28|11:47:18] alert migration failure: could not get migration log logger=migrator error="failed to check table existence: Error 1045: Access denied for user 'gwadmingrafana'@'10.0.4.4' (using password: NO)"
```

![print_error](https://github.com/grafana/grafana/assets/16540578/24c2a8f9-038a-4e8e-99c4-2721428352c4)

Here is the same Stack, without using Swarm secrets and passing my Database user password with variable "GF_DATABASE_PASSWORD":

```
version: "3.9"

services:
  grafana-db:
    image: grafana-db
    environment:
      MARIADB_DATABASE: grafana
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/grafanadb_root_pw
    networks:
      - backend
    secrets:
      - grafanadb_root_pw
      - grafanadb_gwadmingrafana_pw

  grafana:
    image: grafana
    depends_on:
      - grafana-db
    ports:
      - 8080:8080
    environment:
      GF_DATABASE_TYPE: "mysql"
      GF_DATABASE_HOST: "grafana-db:3306"
      GF_DATABASE_NAME: "grafana"
      GF_DATABASE_USER: "gwadmingrafana"
      GF_DATABASE_PASSWORD: mypassword
      GF_SERVER_HTTP_PORT: "8080"
    networks:
      - frontend
      - backend
    secrets:
      - grafanadb_gwadmingrafana_pw

networks:
  frontend:
  backend:
secrets:
  grafanadb_root_pw:
    external: true
  grafanadb_gwadmingrafana_pw:
    external: true
```

With this Stack, I can change the Admin password in CLI as expected:

![print_ok](https://github.com/grafana/grafana/assets/16540578/da32abc3-46d4-4118-9d10-cec126c139fb)

### What did you expect to happen?

In both Stacks, I expected to change admin password in CLI

### Did this work before?

No

### How do we reproduce it?

Deploy a Swarm Stack using Secrets and try to change ADMIN password.

### Environment (with versions)?

Grafana: 9.2.6
OS: Oracle Linux Server release 8.7
Browser: Versão 1.57.53 Chromium: 116.0.5845.114 (Versão oficial) 64 bits

### Grafana platform?

Docker
