### ISSUE TITLE
server side expressions: wide frames with multiple values without labels do not work

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#74108]
assume a dataframe that has the following fields:
- timestamp field, named "time"
- numeric field, named "v1" (no labels)
- numeric field, named "v2" (no labels)

if such a dataframe is used in alerting, you can preview it, and save it, but when the alert is run, you get the following error message:

"invalid format of evaluation results for the alert definition: frame cannot uniquely be identified by its labels: has duplicate results with labels {}"

such a dataframe works fine in a grafana visualization, but somehow the expression+alerting situation does not work.

originally reported for the postgresql datasource at https://github.com/grafana/grafana/issues/73852

**Comment by johnp789** [comment]
I might be seeing this issue after upgrading Grafana from 9.2.5 to 10.3.3, using an Elasticsearch data source.  The alert looks fine and shows Normal in green for all four series, although it is a bit odd that the legend shows each series name repeated.  After saving, the alert starts pending right away with the error "Invalid format of evaluation results for the alert definition : frame cannot uniquely be identified by its labels: has duplicate results with labels {}".  This rule should alert if any sensor (group by sensorName) reads greater than 40.

```yaml
apiVersion: 1
groups:
    - orgId: 321
      name: someone
      folder: General Alerting
      interval: 1m
      rules:
        - uid: A7Dxxxxxx
          title: sample-alert-1
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: "000000314"
              model:
                alias: ""
                bucketAggs:
                    - field: sensorName
                      id: "3"
                      settings:
                        min_doc_count: "1"
                        order: desc
                        orderBy: _term
                        size: "10"
                      type: terms
                    - field: '@timestamp'
                      id: "2"
                      settings:
                        interval: auto
                      type: date_histogram
                intervalMs: 1000
                maxDataPoints: 43200
                metrics:
                    - field: temperature
                      id: "1"
                      type: avg
                query: ""
                refId: A
                timeField: '@timestamp'
            - refId: B
              datasourceUid: "-100"
              model:
                conditions:
                    - evaluator:
                        params:
                            - 3
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - A
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: "-100"
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                settings:
                    mode: dropNN
                type: reduce
            - refId: C
              datasourceUid: "-100"
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: $B > 40
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: math
          noDataState: NoData
          execErrState: Alerting
          for: 20m
          annotations:
            HandlerGroup: TEAM-ONE
            summary: 'Temperature alert: value is {{ $values.B.Value }} ºC'
          isPaused: false
```
