### ISSUE TITLE
Swagger behind subpath : Failed to load API definition.

### ISSUE THREAD

**Issue by DB-CL** [grafana/grafana#74124]
### What happened?

When I try to access : https://sub.myhost.tld/grafana/swagger-ui I have the message:

```
Failed to load API definition.
Fetch error
Not Found /public/api-merged.json
```

The URL https://sub.myhost.tld/grafana/public/api-merged.json works, but it looks like it's trying https://sub.myhost.tld/public/api-merged.json that does not work. (the subpath is missing).

### What did you expect to happen?

It should display the API reference page

### Did this work before?

I don't know, it's the first time I try

### How do we reproduce it?

1. Install grafana behind a reverse proxy, under a subpath
2. Try to access swagger-ui

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 10.1.0
OS: Official Docker image
Browser: Chrome

My nginx configuration:
```
location /grafana/ {
    proxy_set_header Host $http_host; 
    proxy_http_version 1.1;
    proxy_pass http://localhost:33000/grafana/;
}
```

My docker configuration:
```yaml
  grafana:
      image: grafana/grafana-oss
      container_name: grafana
      ports:
        - "33000:3000/tcp"
      volumes:
        - grafana-storage:/var/lib/grafana
      environment:
        GF_SERVER_DOMAIN: "sub.myhost.tld"
        GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s/grafana/"
        GF_SERVER_SERVE_FROM_SUB_PATH: "true"
      restart: unless-stopped
```

I've tried without the serve from subpath:
  - Nginx => `proxy_pass http://localhost:33000/;`
  - Docker => `GF_SERVER_SERVE_FROM_SUB_PATH: "false"`

And I had exactly the same result.

Please note that Grafana is working fine, I have no issue at all with all the functionnalities of Grafana. It's only swagger-ui that does not work.

Please also note that I have a grafana with an identical setup on another domain that have the same issue.

Finally, I also have a grafana with a working swagger-ui and the only difference I can see is the subpath. I have an nginx reverse proxy, but no subpath, and it's working.

### Grafana platform?

Docker
