### ISSUE TITLE
auth.generic_oauth problem after upgrade to Grafana 10.1.0

### ISSUE THREAD

**Issue by pablozone** [grafana/grafana#74154]
### What happened?

Login failed when I login via OCAS. 
![obraz](https://github.com/grafana/grafana/assets/29774180/18b6683e-8341-456e-8606-33b645a112e7)

in grafana log I found error 
\logger=context traceID=774a474468589938340f3aeb4c418471 userId=0 orgId=0 uname= t=2023-08-31T08:04:40.722352614+02:00 level=info msg="Request Completed" method=GET path=/login/generic_oauth status=302 remote_addr=126.189.112.228 time_ms=0 duration=122.638Âľs size=307 referer=https://grafana.cloud.corpnet.pl/login handler=/login/:name
logger=user.sync traceID=a3c580922471056bf75ce274ff31794b t=2023-08-31T08:04:41.016682036+02:00 level=error msg="Failed to create user" error="user already exists" auth_module=oauth_generic_oauth auth_id=f:4187354b-0a97-476c-801d-5b7f548e61d5:blazepa1
logger=authn.service traceID=a3c580922471056bf75ce274ff31794b t=2023-08-31T08:04:41.016722815+02:00 level=warn msg="Failed to run post auth hook" client=auth.client.generic_oauth id= error="[user.sync.internal] unable to create user"
logger=context traceID=a3c580922471056bf75ce274ff31794b userId=0 orgId=0 uname= t=2023-08-31T08:04:41.024662146+02:00 level=info msg="Request Completed" method=GET path=/login/generic_oauth status=302 remote_addr=126.189.112.228 time_ms=90 duration=90.218383ms size=29 referer= handler=/login/:name

### What did you expect to happen?

I expect to log in user corectly. It seams, this auth.generic_oauth method try to create user every time I log in. Not just log in user with his permissions. Please check

### Did this work before?

Yes. It was ok with my previous version 9.5.2

### How do we reproduce it?

1.
2.
3.

### Environment (with versions)?

Grafana: 10.1.0
OS: CentOS Linux release 7.5.1804 (Core)
Browser: Firefox 115.1.0esr (64 bity)

### Grafana platform?

A downloaded binary

**Comment by Jguer** [comment]
Hi @pablozone, probably your IDP does not support user sub claims or you've migrated between idPs and are relying on email lookups.

These are no longer enabled by default in Grafana

You can check this comment for more details
https://github.com/grafana/grafana/issues/70203#issuecomment-1632083421 

Short version, if you're using a private idP try using the following in your config:

```
[auth]
oauth_allow_insecure_email_lookup=true
```

**Comment by tp-jssk** [comment]
I am running into same issue from upgrading from 9.5.3 to 10.1.1. Setting the `oauth_allow_insecure_email_lookup` flag has no impact.

**Comment by pablozone** [comment]
Confirm. this option does not solve the problem, issue still exists.
[auth]
oauth_allow_insecure_email_lookup=true

**Comment by Jguer** [comment]
Just to confirm @pablozone , you have restarted the instance after applying the settings change?

Can you share a censored version of your `ini` for the 2 relevant sections `auth` and `auth.generic_oauth` (ensure there are not 2 repeated `auth` sections as well)

**Comment by pablozone** [comment]
Yes. I restarted grafana-server after applying the settings change, 

My config: (there is only one auth sections)

[auth]
# Set to true to disable (hide) the login form, useful if you use OAuth, defaults to false
disable_login_form = false
oauth_allow_insecure_email_lookup = true
# Set to true to disable the signout link in the side menu. useful if you use auth.proxy, defaults to false
disable_signout_menu = false
# URL to redirect the user to after sign out
signout_redirect_url =


[auth.generic_oauth]
enabled = true
name = OCAS
allow_sign_up = true
client_id = grafana.cloud.corpnet.pl
client_secret = ***********************
scopes = openid
auth_url = https://ocas.corpnet.pl/auth/realms/corpnet/protocol/openid-connect/auth
token_url = https://ocas.corpnet.pl/auth/realms/corpnet/protocol/openid-connect/token
api_url = https://ocas.corpnet.pl/auth/realms/corpnet/protocol/openid-connect/userinfo
tls_client_ca = /opt/grafana/ssl/signet_combo.pem
skip_org_role_sync = true

**Comment by yanehi** [comment]
Unfortunately I still have the same problem, even after setting `oauth_allow_insecure_email_lookup = true` in grafana.ini (auth) and restarting the grafana server.

**Comment by tp-jssk** [comment]
@pablozone update..... These two settings worked for me in 10.1.1 version. I no longer get `User sync failed` error.

```
[auth]
oauth_allow_insecure_email_lookup = true

[auth.generic_oauth]
skip_org_role_sync = true
```

**Comment by Jguer** [comment]
Awesome, indeed maybe there was a patch added to 10.1.1 that changed the handling of the config, sorry for missing it in your description.

**Comment by franco-viotti** [comment]
Hi, the answer from @tp-jssk solved the problem but the things that users who had the issue and error message "User sync failed" are not getting the roles that are associated with them

**Comment by ZhekeJ** [comment]
Hi guys - i am getting {"traceID":""}, every time i'm trying to login to grafana. Could you please help - i have upgraded the version to 10.2 but no luck

**Comment by thomas-mc-work** [comment]
Just in case for docker users:

    GF_AUTH_OAUTH_ALLOW_INSECURE_EMAIL_LOOKUP: "true"

**Comment by biloocabba** [comment]
Hi Team, I am still getting the same error on 10.1.5 even though I added the below settings:
[auth]
oauth_allow_insecure_email_lookup = true

[auth.generic_oauth]
skip_org_role_sync = true

**Comment by ibarryyan** [comment]
https://github.com/grafana/grafana/issues/74154#issuecomment-1708730038  is ok

**Comment by gregoryb** [comment]
@biloocabba Got the issue 10.3.3 did you solved it ?

**Comment by Dezrin** [comment]
> Just in case for docker users:
> 
> ```
> GF_AUTH_OAUTH_ALLOW_INSECURE_EMAIL_LOOKUP: "true"
> ```

Confirmed working on Docker version 10.4.0 - thank you

**Comment by steefenh** [comment]
we have the same issue with 10.3.3 with both set:
[auth]
oauth_allow_insecure_email_lookup = true

[auth.generic_oauth]
skip_org_role_sync = true

Users are creaed via API only, assigned to teams and simply use oauth to sign in - then user sync failed happend

for some users deleting them and recreate them helped (we upgraded from 9.x.x) but not for all users this solved the user sync failed

**Comment by steefenh** [comment]
now upgraded to 10.4.1 and found in debug log the following:

logger=oauth.generic_oauth t=2024-03-22T09:03:13.023833558+01:00 level=debug msg="User info result" result="Id: https://<OUR OAUTH PROVIDER>, Name: , Email: yemail>, Login: <login>, Role: , Groups: []"
logger=login.authinfo t=2024-03-22T09:03:13.040730564+01:00 level=debug msg="auth info retrieved from cache" cacheKey=authinfo-0-oauth_generic_oauth-https://<OUR OAUTH PROVIDER>
logger=user.sync t=2024-03-22T09:03:13.042790094+01:00 level=debug msg="Syncing user info" id= update="&{ <email> <login> <user id>}"
logger=user.sync t=2024-03-22T09:03:13.043129607+01:00 level=error msg="Failed to update user" error="UNIQUE constraint failed: user.login" 

Seems issue is realted to auth_id in table user_auth when users are created via API and during oauth login always get the same auth_id

Index issue:
sqlite> .schema user_auth
CREATE TABLE `user_auth` (
`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
, `user_id` INTEGER NOT NULL
, `auth_module` TEXT NOT NULL
, `auth_id` TEXT NOT NULL
, `created` DATETIME NOT NULL
, `o_auth_access_token` TEXT NULL, `o_auth_refresh_token` TEXT NULL, `o_auth_token_type` TEXT NULL, `o_auth_expiry` DATETIME NULL, `o_auth_id_token` TEXT NULL);
------>>>>>     CREATE INDEX `IDX_user_auth_auth_module_auth_id` ON `user_auth` (`auth_module`,`auth_id`);
CREATE INDEX `IDX_user_auth_user_id` ON `user_auth` (`user_id`);

**Comment by steefenh** [comment]
request reopen of this issue

**Comment by steefenh** [comment]
created new issue with further information
https://github.com/grafana/grafana/issues/85232

**Comment by mparada-suva** [comment]
What are the consequences of setting `oauth_allow_insecure_email_lookup = true`? Our IdP ist a self-hosted Keycloak but it is hard for me to judge if this change would make the system more vulnerable. Anyone is able to point me in the right direction?

**Comment by l4rm4nd** [comment]
> What are the consequences of setting `oauth_allow_insecure_email_lookup = true`? Our IdP ist a self-hosted Keycloak but it is hard for me to judge if this change would make the system more vulnerable. Anyone is able to point me in the right direction?

https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/#using-the-same-email-address-to-login-with-different-identity-providers

**Comment by trotyoung** [comment]
This configuration works for me! Thank you so much!! But there's a problem, the user is just a Viewer, don't know how to make it Admin or Editor.

``` yaml
  grafana.ini:
    check_for_updates: false
    reporting_enabled: false
    server:
      enable_gzip: true
      root_url: https://< domain name>
    security:
      disable_gravatar: false
    dashboards:
      min_refresh_interval: 60s
    auth:
      oauth_allow_insecure_email_lookup: true
      auto_assign_org: true
      disable_login_form: true
      disable_signout_menu: false
      auto_assign_org_role: Editor
    auth.generic_oauth:
      skip_org_role_sync: true
      name: BitBucket
      enabled: true
      allow_sign_up: true
      sync_tolerance: 5m
      auto_login: false
      client_id: <client_id>
      client_secret: <client_secret>
      scopes: "account email"
      auth_url: https://bitbucket.org/site/oauth2/authorize
      token_url: https://bitbucket.org/site/oauth2/access_token
      api_url: https://api.bitbucket.org/2.0/user
      teams_url: https://api.bitbucket.org/2.0/user/permissions/workspaces
      redirect_uri: https://< domain name>/login/generic_oauth
      team_ids_attribute_path: values[*].workspace.slug
      team_ids: <team_id>
      use_refresh_token: true
```

**Comment by tp-jssk** [comment]
@trotyoung We use `role_attribute_path` to make user admin or editor based on one of the attribute we receive from OIDC provider.

**Comment by trotyoung** [comment]
> [@trotyoung](https://github.com/trotyoung) We use `role_attribute_path` to make user admin or editor based on one of the attribute we receive from OIDC provider.
> 
> for example... `"contains(foo[*], '${var.admin_role}') && 'Admin' || contains(foo[*], '${var.editor_role}') && 'Editor' || 'Viewer'"`

Thank you @tp-jssk, I will try that later, my current configuration assigns everyone as Admin, but it's fine for me.

```yaml
  grafana.ini:
    check_for_updates: false
    reporting_enabled: false
    server:
      enable_gzip: true
      root_url: <grafana_url>
    security:
      disable_gravatar: false
    dashboards:
      min_refresh_interval: 60s
    users:
      allow_sign_up: false
      auto_assign_org: true
      auto_assign_org_id: 1
      auto_assign_org_role: Admin
      allow_assign_grafana_admin: true
      viewers_can_edit: true
      editors_can_admin: true
    auth:
      oauth_allow_insecure_email_lookup: true
      disable_login_form: true
      disable_signout_menu: false
      skip_org_role_sync: false
      role_attribute_path: "'Admin'"
    auth.generic_oauth:
      name: BitBucket
      enabled: true
      sync_tolerance: 5m
      auto_login: false
      client_id: <client_id>
      client_secret: <client_secret>
      scopes: "account email"
      auth_url: https://bitbucket.org/site/oauth2/authorize
      token_url: https://bitbucket.org/site/oauth2/access_token
      api_url: https://api.bitbucket.org/2.0/user
      teams_url: https://api.bitbucket.org/2.0/user/permissions/workspaces
      redirect_uri: <redirect_uri>
      team_ids_attribute_path: values[*].workspace.slug
      team_ids: <team_ids>
      use_refresh_token: true

```
