### ISSUE TITLE
[Feature Request] Add support for sending alert notifications to Prometheus alertmanager.

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#7481]
This would enable people to execute alerts both in Prometheus and Grafana and still use the same notification system. 

The documentation for sending alerts to the alertmanager can be found at https://prometheus.io/docs/alerting/clients/

A better [explanation](https://prometheus.io/docs/alerting/rules/) for labels/annotations

> The LABELS clause allows specifying a set of additional labels to be attached to the alert. Any existing conflicting labels will be overwritten. The label values can be templated.
> 
> The ANNOTATIONS clause specifies another set of labels that are not identifying for an alert instance. They are used to store longer additional information such as alert descriptions or runbook links. The annotation values can be templated.

Grafana should send
 
```json
"labels": {
  "publicImageUrl": "...",
  "alert name": "...",
  "alert description": "..."
},
"generatorUrl": "..."
```

**Comment by bergquist** [comment]
This issue depends on https://github.com/grafana/grafana/issues/6041 since deduping in alert manager would not work otherwise.

**Comment by brian-brazil** [comment]
I don't see that as a hard dependency.

The one things that tends to catch people out with the AM is that you need to continuously send firing alerts, though I doubt that'll be a problem for Grafana.

> Grafana should send PublicImageUrl, Alert name, alert description.

Don't forget the generatorUrl. That should be at a minimum the URL of the grafana, preferably a link to the relevant dashboard.

**Comment by bergquist** [comment]
Grafana only send alert notifications once per state change (alerting -> ok or ok -> alerting) so its currently not possible to send alerts continuously to AM. 

But I guess that could be an option per alert notification channel.

**Comment by brian-brazil** [comment]
That's more something to hardcode I'd say. It's probably wise to resend every now and again with PagerDuty for example, but less so for email.

**Comment by iksaif** [comment]
Proposed implementation:

Step 1
* Have a per-notifier ShouldSendNotification(), which inputs would be PrevAlertState, PrevTimestamp and State.
* Have a default implementation that mimics the old one

Step 2
* Add a generic setting to configure the repeat-interval, which is configurable per-notifier, with custom default values per notifier.

**Comment by iksaif** [comment]
Note: we now have a working implementation, which we will publish a pull request for next week. There is still some additional work to do (in particular to let user define labels and annotations), but the basic features are working.

**Comment by bergquist** [comment]
@iksaif sounds like a good plan. I'd be happy to give feedback on such PR.

**Comment by bergquist** [comment]
#10153 has been merged. Now the https://github.com/grafana/grafana/pull/8644 PR needs to be updated.

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/pull/10192

**Comment by isavcic** [comment]
> Note: we now have a working implementation, which we will publish a pull request for next week. There is still some additional work to do (in particular to let user define labels and annotations), but the basic features are working.

Are there plans in the works to let user add labels/annotations? This is, IMO, a pretty important feature.

Thanks!

**Comment by bergquist** [comment]
https://github.com/grafana/grafana/pull/10989 but it needs some work and attention from our side.

**Comment by mambax** [comment]
Hi all

I'd really like to love that feature, but I can not find any elaborate docs on how to use in combination with alert tags and helm chart templating:

```
      - name: prometheus-alertmanager-et
        type: prometheus-alertmanager
        uid: prometheus-alertmanager-notifier
        is_default: false
        send_reminder: false
        disable_resolve_message: false
        settings:
          url: http://alertmanager.et-1.xxxx.io
```
As some infos depend on the cluster and some on the board, I would need a setting to set ruleTags on settings level.
Like:
```
      - name: prometheus-alertmanager-et-with-tags
        type: prometheus-alertmanager
        ...
        settings:
          url: http://alertmanager.et-1.xxxx.io
          tags:
               cluster: et
               env: dev
```

Is there any documentation?
