### ISSUE TITLE
Alerting: Update ruler proxy to support `keep_firing_for` alert rule field

### ISSUE THREAD

**Issue by rwwiv** [grafana/grafana#75029]
This was added to the Prometheus ruler in [this commit](https://github.com/prometheus/prometheus/commit/ce55e5074d05f570ddc619619e877e011dc270e2) and Mimir ruler was updated to support the new field in [this commit](https://github.com/grafana/mimir/commit/5ac2d2686b3a3e6b5c87c985cca5ace6970b2197).

We need to update [`ApiRuleNode`](https://github.com/grafana/grafana/blob/0815d7f6275eb7b9266c8907ebddf770b12a65c4/pkg/services/ngalert/api/tooling/definitions/cortex-ruler.go#L260) to include this field, though ideally we would support setting this in the UI as well.

---

This can be tested with the following rule group:

```yaml
test-group:
  - name: alerts
    rules:
      - alert: AlwaysFiring
        expr: count(up) >= 0
        keep_firing_for: 1m
```
