### ISSUE TITLE
Datasorce-sidecar: isDefault is not working

### ISSUE THREAD

**Issue by ahmedmahmo** [grafana/grafana#75265]
### What happened?

```yaml
datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus-server.prometheus.svc.cluster.local
    isDefault: true
    editable: true
    uid: prometheus
```

As you see I set `isDefault` to true and `uid` but neither of them is effective. 

### What did you expect to happen?

I expected to have the datasorce set as default and has the right `uid`

### Did this work before?

No

### How do we reproduce it?

1. install helm the latest version
2.enable sidecar for datasource and create a configmap with the data as provided above
3.open grafana, you see that fatasorce is not set to default and the dashboard cannot connect to datasource with the uid `prometheus`

### Environment (with versions)?

Grafana: 
OS: 
Browser:

### Grafana platform?

Kubernetes
