### ISSUE TITLE
Provision: The settings of the datasources in the UI are not saved

### ISSUE THREAD

**Issue by pavel-mokrushin** [grafana/grafana#75722]
### What happened?

All the changes made through the UI are gone. That is, the settings from yaml from provisioning were applied again. Changing the configuration version does not help, I tried to reduce and increase the version of datasource in the file.

I have volume configured for Grafana in docker. The problem is not that the database is being deleted, but that data from the provisioning datasource file is being overwritten in it, and I can’t influence it in any way

First I wrote to the Grafana forum, they confirmed the problem and asked me to write here
https://community.grafana.com/t/the-settings-of-the-datasources-in-the-ui-are-not-saved-when-using-provisioning-after-restarting-grafana/104429

### What did you expect to happen?

When using the datasource settings from provisioning, changes in the UI were saved.

### Did this work before?

is unknown

### How do we reproduce it?

1. Add the datasource configuration to the provisioning folder
 configuration example:
```
-   name: rx-log-metrics
    editable: true
    type: elasticsearch
    access: proxy
    url: 'http://192.168.55.28:9200'
    jsonData:
        timeField: "@timestamp"
        esVersion: 7.16.1
        index: "rx-log-metrics*"
        logMessageField: message
        logLevelField: logLevel
    version: 11
```
2. Restart Grafana
3. In the UI, make changes to the created datasources and save them
4. Restart Grafana
5. In the UI, check whether the changes in the datasources have been preserved

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 10.1
OS: Ubuntu (Grafana in docker)

### Grafana platform?

Docker
