### ISSUE TITLE
Ability to change default width, size and scale for remote image rendering

### ISSUE THREAD

**Issue by suntala** [grafana/grafana#75963]
### Discussed in https://github.com/grafana/grafana/discussions/47211

<div type='discussions-op-text'>

<sup>Originally posted by **laundmo** April  1, 2022</sup>
Currently, the default width/height is hard-coded to 1000x500 here: https://github.com/grafana/grafana/blob/f1c3177e79f21e1292afa02efa393f5e52dc231a/public/app/features/dashboard/components/ShareModal/utils.ts#L106

The reason i set up the image renderer in the first place was to produce higher quality images than screenshotting would give me. Having to edit the URL by hand for this is really not great.

I propose being able to set a default server-wide for these parameters, and down the line in the future making them easily configurable in the ShareModal. Especially, being able to set the `scale` parameter is essential to take full advantage of the image renderer.</div>

**Comment by lucychen-grafana** [comment]
We've discussed this and decided that this is a nice to have that we will take into consideration with the Sharing Modal redesign

**Comment by khushijain21** [comment]
@natellium is this open for contribution? And can you share the specifics agreed upon for the implementation?

**Comment by ericsirius** [comment]
> ### Discutido em #47211
> Postado originalmente por **laundmo** em 1º de abril de 2022 Atualmente, a largura/altura padrão está codificada para 1000x500 aqui:
> 
> https://github.com/grafana/grafana/blob/f1c3177e79f21e1292afa02efa393f5e52dc231a/public/app/features/dashboard/components/ShareModal/utils.ts#L106
> 
> A razão pela qual configurei o renderizador de imagem em primeiro lugar foi para produzir imagens de qualidade superior do que a captura de tela me proporcionaria. Ter que editar o URL manualmente para isso não é ótimo.
> 
> Proponho ser capaz de definir um padrão para todos esses parâmetros em todo o servidor e, no futuro, torná-los facilmente configuráveis ​​no ShareModal. Principalmente, ser capaz de definir o `scale`parâmetro é essencial para aproveitar ao máximo o renderizador de imagem.

How do you apply it, when it is in docker.....I use docker exec and restart container

**Comment by AgnesToulet** [comment]
@khushijain21 Yes it's open for contribution. We don't have the designs yet to add these parameters in the ShareModal but a good first step would be to add the possibility to configure the `height`, `width` and `scale` defaults in the [configuration file](https://github.com/grafana/grafana/blob/main/conf/defaults.ini#L1505) and use those in the [rendering endpoint](https://github.com/grafana/grafana/blob/main/pkg/api/render.go#L27) instead of the hard-coded ones.

**Comment by Tim-Schwalbe** [comment]
Hi, is this also passed to the external image renderer when an alert image is created? I tried a lot but the alert image looks always the same.

I tried to configure the renderer via environment variables, but as the log shows above the call to the renderer does not change. 
Can someone confirm on this and give me a workaround.

```
{"level":"debug","message":"10.56.1.226 - - [03/Oct/2024:12:18:07 +0000] \"GET /render?deviceScaleFactor=1.000000&domain=grafana.monitoring&encoding=png&height=500&renderKey=Sibb7wTfyW9gqpAO90L1huujXLD6wx2t&timeout=10&timezone=&url=http%3A%2F%2Fgrafana.monitoring%3A80%2Fd-solo%2Fw3R5mU0Vk%2Flogs%3ForgId%3D1%26panelId%3D2%26render%3D1&width=1000 HTTP/1.1\" 
- - \"-\" \"Grafana/11.1.5\"\n"}
{"level":"debug","message":"Connection closed","url":"http://grafana.monitoring:80/d-solo/w3R5mU0Vk/logs?orgId=1&panelId=2&render=1"}
```


```
  env:
    HTTP_HOST: "0.0.0.0"
    RENDERING_ARGS: --no-sandbox,--disable-gpu, --disable-setuid-sandbox, --hide-scrollbars,--disable-infobars
    BROWSER_TZ: Europe/Berlin
    RENDERING_VIEWPORT_WIDTH: 2400
    RENDERING_VIEWPORT_MAX_WIDTH: 4800
    RENDERING_VIEWPORT_HEIGHT: 1080
    RENDERING_VIEWPORT_MAX_HEIGHT: 1200
    RENDERING_VIEWPORT_DEVICE_SCALE_FACTOR: 
    RENDERING_VIEWPORT_MAX_DEVICE_SCALE_FACTOR: 1
    RENDERING_MODE: default
    RENDERING_CLUSTERING_MODE: browser
    RENDERING_CLUSTERING_MAX_CONCURRENCY: 2
    RENDERING_CLUSTERING_TIMEOUT: 90
    RENDERING_VIEWPORT_PAGE_ZOOM_LEVEL: 1
    RENDERING_VERBOSE_LOGGING: true
    LOG_LEVEL: debug
```
