### ISSUE TITLE
Alerting: returned by a data source time series is not filtered by time window

### ISSUE THREAD

**Issue by vanchaxy** [grafana/grafana#76001]
### What happened?

If the data source returns time series outside of the specified window they are still used in the reduce function.

For example, on the screenshot, you can see that all data points in the last 5 minutes if 0 but reduce to max returns 1.

<img width="799" alt="image" src="https://github.com/grafana/grafana/assets/36510601/2ac658c3-689d-473b-b9a2-390620dc2bbf">

Currently, I have this issue with the forked sentry data source because [Sentry ignores a specified time window](https://github.com/getsentry/sentry/issues/57536) but this could be with any other data source with a similar problem.

### What did you expect to happen?

I expect Grafana to use only data points from the selected time window. This is especially confusing because when specifying an alert via provisioning relativeTimeRange is specified under in reduce query but it's completely ignored. E.g.

```
      - refId: B
        datasourceUid: "__expr__"
        model:
          refId: B
          type: reduce
          datasource:
            uid: "-100"
            type: __expr__
          expression: A
          reducer: max
          relativeTimeRange: # doesn't matter, all range from A is using
            from: 900
            to: 0
```

### Did this work before?

No idea, I noticed it only now

### How do we reproduce it?

1. Use a data source that returns time series outside selected window
2. Use any min/max reduce function

### Environment (with versions)?

Grafana: 10.1.2

### Grafana platform?

Kubernetes
