### ISSUE TITLE
Datasource: Failed to add datasource

### ISSUE THREAD

**Issue by olegpixel** [grafana/grafana#76230]
### What happened?

The "Add new data source" functionality is currently not functioning as expected when using the anonymous role (GF_AUTH_ANONYMOUS_ENABLED) and admin permission enabled (GF_AUTH_ANONYMOUS_ORG_ROLE) in a local development environment using latest enterprise Docker image (`grafana/grafana-enterprise:10.1.4`). This issue appears to be specific to recent versions of Grafana, as it worked correctly in older versions.

When attempting to add a new data source the backend returns the following error response:
```
{
    "error": "identifying id not found",
    "message": "Failed to add datasource",
    "traceID": ""
}
```

I've tried different datasources, e.g. Sentry, Elasticsearch, Alertmanager etc - same result for all of them.

Here is a `docker-compose.yaml`:
```
services:
  grafana:
    image: grafana/grafana-enterprise:10.1.4
    container_name: grafana-local
    ports:
      - '3000:3000'
    volumes:
      - grafana-data-local:/var/lib/grafana    
      - ~/work/grafana/license.jwt:/var/lib/grafana/data/license.jwt 
      - ./provisioning:/etc/grafana/provisioning
    environment:
      - TERM=linux
      - GF_DEFAULT_APP_MODE=development
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_USERS_VIEWERS_CAN_EDIT=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_BASIC_ENABLED=false
      - GF_LOG_LEVEL=debug
      - GF_DATAPROXY_LOGGING=true
      - GF_CACHING_ENABLED=true
      - GF_ENTERPRISE_LICENSE_PATH=/var/lib/grafana/data/license.jwt 
volumes:
  grafana-data-local: {}
```

It works perfectly fine with older enterprise versions - `grafana/grafana-enterprise:10.0.x` as well as in the community latest version - `grafana/grafana:10.1.4`.

The issue potentially relates to this recent PR, file `store.go` - https://github.com/grafana/grafana/commit/7431c0ddb15a146352eeb99eca67bca0dc61bec5#diff-13017324694f53fae56046bf90c5ecd1edce16da7647835df47e5828c7879671

![image](https://github.com/grafana/grafana/assets/20262077/8d8fa851-49c5-45b4-a748-9568493b3ef0)
![image](https://github.com/grafana/grafana/assets/20262077/6ff6a832-c6f4-4ba7-bd0b-3dd5047fbcd4)

### What did you expect to happen?

In a local development environment with anonymous role and admin permission, users should be able to successfully add a new data source without encountering the "identifying id not found" error.

### Did this work before?

It works perfectly fine with older enterprise versions - `grafana/grafana-enterprise:10.0.x` as well as in the community latest version - `grafana/grafana:10.1.4`.

### How do we reproduce it?

1. Create a `docker-compose.yaml` file and set environment variables `GF_AUTH_ANONYMOUS_ENABLED=true` and `GF_AUTH_ANONYMOUS_ORG_ROLE=Admin` 
2. Run `docker-compose up --build`
3. Try to add a new datasource, e.g. Sentry or Elasticsearch

### Environment (with versions)?

Grafana: grafana-enterprise:10.1.4
OS: MacOS
Browser: Google Chrome (Version 117.0.5938.149 (Official Build) (arm64))

### Grafana platform?

Docker

### Datasource(s)?

Sentry, Elasticsearch, Alertmanager
