### ISSUE TITLE
Explore: expand rule feature doesn't properly expand a rule

### ISSUE THREAD

**Issue by Rohlik** [grafana/grafana#76320]
### What happened?

I noticed, that the `expand rule` feature, which is part of _Explore_ doesn't work well in some cases.  
For example, rule `slo:sli_error:ratio_rate1h{sloth_service="loki",sloth_slo="Read_Querier_availability"}` is expanded to:
```
(sum(rate(loki_request_duration_seconds_sum{job=~"loki-ingester",route="/logproto.Pusher/Push"}[1h:5m]))) / (sum(rate(loki_request_duration_seconds_count{job=~"loki-ingester",route="/logproto.Pusher/Push{sloth_service="loki", sloth_slo="Read_Querier_availability"}
```
which is messed up and Grafana will start showing errors straight away:  
```
bad_data: invalid parameter "query": 1:220: parse error: unexpected identifier "loki" in label matching, expected "," or "}"
```

The definition of that rule looks like:
```yaml
      - record: slo:sli_error:ratio_rate1h
        expr: |
          (sum(rate(loki_request_duration_seconds_count{job="loki-querier",status_code=~"5.."}[1h:5m])) by (route))
          /
          (sum(rate(loki_request_duration_seconds_count{job="loki-querier"}[1h:5m])) by (route))
        labels:
          exposition: internal
          owner: infra
          sloth_id: loki-Read_Querier_availability
          sloth_service: loki
          sloth_slo: Read_Querier_availability
          sloth_window: 1h
```

### What did you expect to happen?

Correctly expanded rule which is working and which is not messed up.

### Did this work before?

No

### How do we reproduce it?

1. Ensure that you defined the record rule in Mimir (see definition above)
2. Use the Explore section of Grafana
3. Put there `slo:sli_error:ratio_rate1h{sloth_service="loki",sloth_slo="Read_Querier_availability"}` and run that query (now it's working)
4. Click on `Expand rules`
5. See the expanded rule which messed up

### Environment (with versions)?

Grafana: Grafana v10.1.2 (8e428858dd)
OS: Linux
Browser: Chrome 117

### Grafana platform?

Kubernetes

### Datasource(s)?

Mimir
