### ISSUE TITLE
Grafana UI (Alert Manager): TypeError: t.map is not a function

### ISSUE THREAD

**Issue by AlissonRS** [grafana/grafana#76389]
### What happened?

The error `TypeError: t.map is not a function` on Alert Manager UI reported on #57206 is still happening, as per screenshot below.

![image](https://github.com/grafana/grafana/assets/4753901/1e4164c1-fecd-4686-af4c-b943986ee9f6)

### What did you expect to happen?

UI shouldn't crash.

### Did this work before?

This issue was reported back on v9.2.0, a fix was supposed to be done on v9.2.4 (as noted on #57206 ) but this is still happening on v10.0.3.

### How do we reproduce it?

1.
2.
3.

### Environment (with versions)?

Grafana: v10.0.3
OS: docker.io/grafana/grafana:10.0.3
Browser: Brave v1.58.135 (Chromium 117.0.5938.140), but the other guy faced this issue on Firefox

### Grafana platform?

Kubernetes

**Comment by armandgrillet** [comment]
This is very strange as we have removed the bug in 9.2.4, if you reproduce again can you please share a HAR file?

Creating a HAR file in the Brave browser, which is based on Chromium, involves the following steps:

- Open the Brave browser and navigate to the page where you are experiencing issues.
- Access Developer Tools by clicking the menu button (three horizontal lines or dots) and selecting "More Tools > Developer Tools". Alternatively, you can use the shortcut Ctrl + Shift + I on Windows/Linux or Cmd + Option + I on macOS.
- Once the developer panel is open, click on the "Network" tab.
- Look for a round red button at the top-left of the Network tab; this is the recording button. If it's red, it means recording is already in progress. If it's grey, you'll need to click it to start recording.
- Perform the actions on the site that you need to capture.
- Right-click anywhere on the grid of network requests, select "Save all as HAR with content", and save the file to your desired location.

**Comment by AlissonRS** [comment]
@armandgrillet sure, here is the HAR file: 
[grafana.flokifi.com.zip](https://github.com/grafana/grafana/files/13246600/grafana.flokifi.com.zip)

You can also go to https://grafana.flokifi.com/alerting/list

user: test
pass: test123

You might be able to reproduce the bug.

**Comment by gillesdemey** [comment]
Hi! It looks like the response on the Loki ruler endpoints are returning some HTML response – I'm not exactly sure how this could have happened, could there be a proxy that isn't properly redirecting endpoints?

**Comment by AlissonRS** [comment]
@gillesdemey thanks for the reply. I'm not sure if this helps, but I install both Grafana and Loki on the cluster using ArgoCD via Helm, it goes like below as subcharts.

Charts.yaml
```
apiVersion: v2
name: kube-prometheus-stack
description: A Helm chart for prometheus stack
type: application
version: 48.4.0
dependencies:
  - name: kube-prometheus-stack # Prometheus, Grafana, Alertmanager and NodeExporter
    version: 48.4.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: loki # Loki for log aggregation
    version: 5.15.0
    repository: https://grafana.github.io/helm-charts
```

values.yaml
```
### Config for Kube Prometheus Stack ###
### This includes Prometheus, Grafana, AlertManager and a NodeExporter ###
kube-prometheus-stack:
  grafana:
    ingress:
      enabled: true
      hosts:
        - grafana.flokifi.com
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
    additionalDataSources:
    - name: Loki
      uid: loki
      access: proxy
      editable: false
      jsonData:
        maxLines: 1000
      orgId: 1
      type: loki
      timeout: 180
      url: http://loki-gateway.monitoring
    - name: Tempo
      type: tempo
      uid: tempo
      url: http://monitoring-tempo-query-frontend.monitoring:3100
      access: proxy
      basicAuth: false
      jsonData:
        tracesToLogsV2:
          # Field with an internal link pointing to a logs data source in Grafana.
          # datasourceUid value must match the uid value of the logs data source.
          datasourceUid: 'loki'
          spanStartTimeShift: '1h'
          spanEndTimeShift: '-1h'
          tags: ['job', 'instance', 'pod', 'namespace']
          filterByTraceID: false
          filterBySpanID: false
          customQuery: true
          query: 'method="${__span.tags.method}"'
        tracesToMetrics:
          datasourceUid: 'prom'
          spanStartTimeShift: '1h'
          spanEndTimeShift: '-1h'
          tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
          queries:
            - name: 'Sample query'
              query: 'sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[5m]))'
        serviceMap:
          datasourceUid: 'prometheus'
        nodeGraph:
          enabled: true
        search:
          hide: false
        lokiSearch:
          datasourceUid: 'loki'
        traceQuery:
          timeShiftEnabled: true
          spanStartTimeShift: '1h'
          spanEndTimeShift: '-1h'
        spanBar:
          type: 'Tag'
          tag: 'http.path'

### Config for Grafana Loki ###
loki:
  loki:
    auth_enabled: false
    server:
      grpc_server_max_recv_msg_size: 104857600
      grpc_server_max_send_msg_size: 104857600
    limits_config:
      per_stream_rate_limit: 10MB
      per_stream_rate_limit_burst: 10MB
      ingestion_rate_mb: 50
      ingestion_burst_size_mb: 50
      reject_old_samples: false
    ingester:
      max_chunk_age: 100h
    query_range:
      split_queries_by_interval: 0
      parallelise_shardable_queries: false # to solve error notifying frontend issue as per https://github.com/grafana/loki/issues/7649
    querier:
      max_concurrent: 2048
    frontend:
      max_outstanding_per_tenant: 4096
      compress_responses: true
      
    storage:
      bucketNames:
        chunks: flokifi-grafana-loki-chunks
        ruler: flokifi-grafana-loki-ruler
        admin: flokifi-grafana-loki-admin
      type: s3
      s3:
        s3: "s3://flokifi-grafana-loki-chunks"
        region: us-east-1
  backend:
    extraArgs:
      - '-config.expand-env=true'
    extraEnv:
      - name: GRAFANA_LOKI_S3_BUCKET_CHUNKS 
        valueFrom:
          secretKeyRef:
            name: loki-secrets
            key: grafana_loki_s3_bucket_chunks
      - name: GRAFANA_LOKI_S3_BUCKET_RULER 
        valueFrom:
          secretKeyRef:
            name: loki-secrets
            key: grafana_loki_s3_bucket_ruler
      - name: GRAFANA_LOKI_S3_BUCKET_ADMIN 
        valueFrom:
          secretKeyRef:
            name: loki-secrets
            key: grafana_loki_s3_bucket_admin
  monitoring:
    serviceMonitor:
      labels:
        release: monitoring
```
