### ISSUE TITLE
Alerting: POST /api/admin/provisioning/access-control/reload returns "Not found"

### ISSUE THREAD

**Issue by DamianArado** [grafana/grafana#76750]
### What happened?

I'm adding rbac rule for my api_key to create users using API. Here, is the `etc/grafana/provisioning/access-control/sample.yaml` file:
```
# ---
# # config file version
 apiVersion: 2

 # <list> list of roles to insert/update/delete
 roles:
   # <string, required> name of the role you want to create or update. Required.
   - name: 'custom:users:writer'
     # <string> uid of the role. Has to be unique for all orgs.
     uid: customuserswriter1
     # <string> description of the role, informative purpose only.
     description: 'Create, read, write users'
     # <int> version of the role, Grafana will update the role when increased.
     version: 2
     # <int> org id. Defaults to Grafana's default if not specified.
     orgId: 1
     # <list> list of the permissions granted by this role.
     permissions:
       # <string, required> action allowed.
       - action: 'users:read'
         #<string> scope it applies to.
         scope: 'global.users:*'
       - action: 'users:write'
         scope: 'global.users:*'
       - action: 'users:create'
```

After this, I hit my API to reload provisioning at `/api/admin/provisioning/access-control/reload`

this returns:
```
{"message":"Not found"}
```

### What did you expect to happen?

Some response similar to this:
```
{"message":"Notifications config reloaded"}
```

or this:
```
{"message":"Alerting config reloaded"}
```

### Did this work before?

I never tried this before. 

### How do we reproduce it?

1. Add a rbac rule like the one i added above.
2. Try to hit POST /api/admin/provisioning/access-control/reload API
3. Check the result

It may have been the case I missed out something in between adding the rule and hitting the API. Could you please in that case help me with that?  :)

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 9.5+
OS: Linux Ubuntu
Browser: Chrome

### Grafana platform?

Docker
