### ISSUE TITLE
Grafana can not restart if there're any provisioning alert rules

### ISSUE THREAD

**Issue by pznamensky** [grafana/grafana#76795]
### What happened?

So, in Grafana it's possible to add alert rules from [provisioning files](https://grafana.com/docs/grafana/latest/alerting/set-up/provision-alerting-resources/).
This is a great feature that can help us to use GitOps approach.
However, it turned out that when you're trying to restart Grafana, you're getting an error and Grafana cannot start.
This makes this whole idea of using provisioning files for alerts not usable.
The error seems to be the same as in https://github.com/grafana/grafana/issues/75877
```
logger=provisioning.alerting t=2023-10-19T08:14:47.234827703Z level=info msg="starting to provision alerting"
Error: ✗ alert rules: failed to create new rule versions: UNIQUE constraint failed: alert_rule_version.rule_org_id, alert_rule_version.rule_uid, alert_rule_version.version
```

### What did you expect to happen?

Grafana restarts without errors.

### Did this work before?

Nope.

### How do we reproduce it?

1. Add a file with an alert [using provisioning](https://grafana.com/docs/grafana/latest/alerting/set-up/provision-alerting-resources/file-provisioning/#provision-alert-rules)
2. Start Grafana
3. Alert will be added and Grafana will start without errors
4. Restart Grafana
5. Grafana will not be able to start

### Environment (with versions)?

Grafana: v10.0.3
OS: ubuntu 22.04

### Grafana platform?

Docker

**Comment by tonypowa** [comment]
hi @pznamensky 

thank you for opening this issue

could you share details of your docker-compose file and your provisioning file.

**Comment by pznamensky** [comment]
hi @tonypowa 
I'm starting Grafana using plain docker, something like this:
```
/usr/bin/docker run --name grafana \
             --net=host \
             -v /opt/grafana:/var/lib/grafana \
             -v /etc/grafana:/etc/grafana \
             grafana/grafana:10.0.3
```
Example of alerts `/etc/grafana/alerts/test.yaml`:
```
apiVersion: 1
groups:
  - orgId: 1
    name: Nginx errors per min alert
    folder: General Alerting
    interval: 1m
    rules:
      - uid: e8225056-c5b4-468c-8111-bf36926140e2
        title: Nginx errors per min alert
        condition: A
        data:
          - refId: A
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 300
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - B
                  reducer:
                    type: avg
              refId: A
              type: classic_conditions
          - refId: B
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: DHi41MV7k
            model:
              alias: error.log
              bucketAggs:
                - field: '@timestamp'
                  id: "2"
                  settings:
                    interval: auto
                    min_doc_count: 0
                    trimEdges: 0
                  type: date_histogram
              datasource:
                type: elasticsearch
                uid: DHi41MV7k
              interval: 1m
              metrics:
                - field: select field
                  id: "1"
                  type: count
              query: 'programname.keyword: nginx'
              refId: B
              timeField: '@timestamp'
        dashboardUid: "000000007"
        panelId: 29
        noDataState: NoData
        execErrState: Alerting
        for: 5m
        annotations:
          __alertId__: "58"
          __dashboardUid__: "000000007"
          __panelId__: "29"
          message: ""
        labels:
          __contacts__: '"Slack #alerts"'
          rule_uid: e8225056-c5b4-468c-8111-bf36926140e2
        isPaused: false
  - orgId: 1
    name: Too many 500 errors on load balancer
    folder: General Alerting
    interval: 1m
    rules:
      - uid: eea9532d-10ec-4340-818c-546f3780d38c
        title: Too many 50x errors on load balancer
        condition: D
        data:
          - refId: A
            relativeTimeRange:
              from: 60
              to: 0
            datasourceUid: "000000007"
            model:
              alias: "502"
              bucketAggs:
                - field: '@timestamp'
                  id: "2"
                  settings:
                    interval: auto
                    min_doc_count: 0
                    trimEdges: 0
                  type: date_histogram
              datasource:
                type: elasticsearch
                uid: "000000007"
              interval: 1m
              metrics:
                - field: select field
                  id: "1"
                  type: count
              query: status:502
              refId: A
              timeField: '@timestamp'
          - refId: B
            relativeTimeRange:
              from: 60
              to: 0
            datasourceUid: "000000007"
            model:
              alias: "500"
              bucketAggs:
                - field: '@timestamp'
                  id: "2"
                  settings:
                    interval: auto
                    min_doc_count: 0
                    trimEdges: 0
                  type: date_histogram
              datasource:
                type: elasticsearch
                uid: "000000007"
              interval: 1m
              metrics:
                - field: select field
                  id: "1"
                  type: count
              query: status:500
              refId: B
              timeField: '@timestamp'
          - refId: C
            relativeTimeRange:
              from: 60
              to: 0
            datasourceUid: "000000007"
            model:
              alias: "503"
              bucketAggs:
                - field: '@timestamp'
                  id: "2"
                  settings:
                    interval: auto
                    min_doc_count: 0
                    trimEdges: 0
                  type: date_histogram
              datasource:
                type: elasticsearch
                uid: "000000007"
              interval: 1m
              metrics:
                - field: select field
                  id: "1"
                  type: count
              query: status:503
              refId: C
              timeField: '@timestamp'
          - refId: D
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 100
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - B
                  reducer:
                    type: sum
                - evaluator:
                    params:
                      - 50
                    type: gt
                  operator:
                    type: or
                  query:
                    params:
                      - A
                  reducer:
                    type: sum
                - evaluator:
                    params:
                      - 50
                    type: gt
                  operator:
                    type: or
                  query:
                    params:
                      - C
                  reducer:
                    type: sum
                - evaluator:
                    params:
                      - 50
                    type: gt
                  operator:
                    type: or
                  query:
                    params:
                      - A
                  reducer:
                    type: sum
              refId: D
              type: classic_conditions
        dashboardUid: "000000007"
        panelId: 13
        noDataState: Alerting
        execErrState: Alerting
        for: 2m
        annotations:
          __alertId__: "48"
          __dashboardUid__: "000000007"
          __panelId__: "13"
          message: ""
        labels:
          __contacts__: '"PagerDuty","Slack #alerts"'
          rule_uid: eea9532d-10ec-4340-818c-546f3780d38c
        isPaused: false

```
