### ISSUE TITLE
Alerting: noDataState field is being ignored for provisioned alerts

### ISSUE THREAD

**Issue by droslean** [grafana/grafana#77100]
### What happened?

Provision an alert:
```yaml
apiVersion: 1
groups:
- orgId: 1
  name: test
  folder: test
  interval: 5m
  rules:
  - uid: a5aec58a-41ab-494c-8a65-29e1f33417fb
    title: test-errors
    condition: A
    data:
    - refId: A
      queryType: instant
      relativeTimeRange:
        from: 600
        to: 0
      datasourceUid: XXXXXXXXXX
      model:
        datasource:
          type: loki
          uid: XXXXXXXXXX
        editorMode: code
        expr: sum by (namespace, container, app) (count_over_time({namespace="test", container="website"} | json | level="error" [5m])) > 0
        hide: false
        intervalMs: 1000
        maxDataPoints: 43200
        queryType: instant
        refId: A
    noDataState: OK
    execErrState: Error
    for: 5m
    isPaused: false

```

Grafana is still triggering the `DatasourceNoData` alert.

Trying to manually export the alert it seems that the `noDataState` value is different

```yaml
apiVersion: 1
groups:
- orgId: 1
  name: test
  folder: test
  interval: 5m
  rules:
  - uid: a5aec58a-41ab-494c-8a65-29e1f33417fb
    title: test-errors
    condition: A
    data:
    - refId: A
      queryType: instant
      relativeTimeRange:
        from: 600
        to: 0
      datasourceUid: XXXXXXXXXX
      model:
        datasource:
          type: loki
          uid: XXXXXXXXXX
        editorMode: code
        expr: sum by (namespace, container, app) (count_over_time({namespace="test", container="website"} | json | level="error" [5m])) > 0
        hide: false
        intervalMs: 1000
        maxDataPoints: 43200
        queryType: instant
        refId: A
    noDataState: NoData
    execErrState: Error
    for: 5m
    isPaused: false

```

### What did you expect to happen?

I would expect the provisioned alert to be exactly as the given configuration but its not. 

`noDataState: OK` instead of `noDataState: NoData` 

### Did this work before?

No

### How do we reproduce it?

1. Provision the alert in question
2. Export the alert
3. Check the differences in the noDataState filed.

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: docker.io/grafana/grafana:10.1.2
OS: ??
Browser: ALL

### Grafana platform?

Kubernetes
