### ISSUE TITLE
Provisioning: datasource and dashboard org by name

### ISSUE THREAD

**Issue by sathieu** [grafana/grafana#77282]
**Why is this needed**:

We are using multiple Orgs. Each org has a loki and a prometheus datasource. We also populate dashboards specific to some Orgs.

Currently we need to keep a map of Org names to Org IDs, to properly [provision](https://grafana.com/docs/grafana/latest/administration/provisioning/) datasources and dashboards. We are using somethink like this:

```yaml
# datasources.yaml.j2 (Jinja2)
apiVersion: 1
datasources:
  {% for org in orgs %}
  - name: Loki {{ org.name }}
    orgId:  {{ org.id }}  # <===== HERE
    type: loki
    access: proxy
    url: http://<REDACTED>
    jsonData:
        httpHeaderName1: X-Scope-OrgID
    secureJsonData:
        httpHeaderValue1: {{ org.name }}
  {% endfor %}
```

**What would you like to be added**:

Allow to use Org **name** in datasources and dashboards provisioned.

```yaml
# datasources.yaml.j2 (Jinja2)
apiVersion: 1
datasources:
  {% for org in orgs %}
  - name: Loki {{ org.name }}
    orgName:  {{ org.name }}  # <===== HERE
    type: loki
    access: proxy
    url: http://<REDACTED>
    jsonData:
        httpHeaderName1: X-Scope-OrgID
    secureJsonData:
        httpHeaderValue1: {{ org.name }}
  {% endfor %}
```

This is done in https://github.com/grafana/grafana/pull/76937.

**Who is this feature for?**

Users of [file provisioning](https://grafana.com/docs/grafana/latest/administration/provisioning/) having multiple Orgs.
