### ISSUE TITLE
Data source: can't lookup IP address when I use mDNS(.local) in URL or Host field 

### ISSUE THREAD

**Issue by WangLei1993** [grafana/grafana#77335]
### What happened?

When I update the docker image to the latest version, any data source which I use mDNS(.local) in URL or Host field can't lookup IP address for any query.

After a long time to search, I find the reason:

In Ubuntu based image, it use "gnu libc" dynamic library which support NSS (Name Service Switch). But the golang backend use "musl libc" static library which is  in building image like "golang:1.20.10-alpine3.18". And the "musl libc" do not support NSS. Thus, when golang backend using static library, an error occurs.
 
So the following may be the solution：

Use dynamic library rather than static library in building the go backend. That is to say, do not use `go build -ldflags "-linkmode 'external' -extldflags '-static'"`. Like what to do in previous version.

Or

Use Ubuntu based golang image rather than Alpine based golang image `golang:1.20.10-alpine3.18` in building Ubuntu based docker image. In Alpine based image, it can be done nothing.

### What did you expect to happen?

mDNS can be used in data source, IP address can be found.

### Did this work before?

Yes, before docker image version `grafana/grafana:9.5.9-ubuntu` or `grafana/grafana:10.0.4-ubuntu`, it use dynamic library and work well. But in these versions and future versions, it is bad. 

### How do we reproduce it?

1. make sure a mDNS can be done, like `influxdb.local` 
2. make sure avahi daemon is work well in docker host machine
3. use the latest docker image version like `grafana/grafana:main-ubuntu` to make a new image with avahi-utils
4. run the image and then in data source to use mDNS(.local) in URL or Host field

Dockerfile
```
FROM grafana/grafana:main-ubuntu
USER root
RUN apt-get update && apt-get install avahi-utils -y
```

docker-compose.yml
```
version: "3"

services:
  grafana:
    image: cubestone/grafana:latest_with_mdns
    container_name: grafana
    privileged: true
    environment:
      - GF_PATHS_CONFIG=/data/config/grafana.ini
      - GF_PATHS_PROVISIONING=/data/config/provisioning
      - GF_PATHS_DATA=/data/data/grafana
      - GF_PATHS_PLUGINS=/data/data/grafana/plugins
      - GODEBUG=netdns=cgo+2
    volumes:
      - ./data:/data
      - /run/avahi-daemon/socket:/run/avahi-daemon/socket
      - /var/run/dbus:/var/run/dbus
    ports:
      - 3000:3000
    restart: unless-stopped
 
networks:
  default:
    external:
      name: app_net
```

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: docker image version `grafana/grafana:9.5.9-ubuntu` or `grafana/grafana:10.0.4-ubuntu` and future versions 
OS: my docker host version is `Linux nas 5.15.0-88-generic #98-Ubuntu SMP Mon Oct 2 15:18:56 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux` but any OS may be ok 
Browser: any browser may ok

### Grafana platform?

Docker

### Datasource(s)?

any may ok when use mDNS(.local) in URL or Host field
