### ISSUE TITLE
Alerting: Provisioned alert rule for TimescaleDB is missing $__timeFilter() macro

### ISSUE THREAD

**Issue by chaevan** [grafana/grafana#77466]
### What happened?

I am trying to provision Grafana in Kubernetes with a group of alert rules predefined in the config, but am experiencing an issue where a macro `$__timeFilter("time")` that appears in the configured alert's SQL query is being reduced to just `("time")` in the query that ends up uploaded in Grafana.

To do this, I am first creating an alert via the UI, and then downloading the YAML of the alert, which gives me the following:
```
apiVersion: 1
groups:
    - orgId: 1
      name: group
      folder: Field
      interval: 1m
      rules:
        - uid: d69e140f-7984-4198-8c3b-c86e4b82ecf6
          title: gb-signal-alert
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: cloud-tsdb
              model:
                datasource:
                    type: postgres
                    uid: cloud-tsdb
                editorMode: code
                format: table
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                rawQuery: true
                rawSql: |-
                    SELECT
                    "time" AS "time",
                    m.subtopic,
                    m.num_value AS "signal",
                    m.device_id
                    FROM messages m
                    JOIN devices d
                    ON d.id = m.device_id
                    WHERE
                    $__timeFilter("time") AND
                    m.name = 'signal' AND
                    d.serial LIKE 'GB%'
                    ORDER BY 1
                refId: A
                sql:
                    columns:
                        - parameters: []
                          type: function
                    groupBy:
                        - property:
                            type: string
                          type: groupBy
                    limit: 50
            - refId: B
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: mean
                refId: B
                settings:
                    mode: dropNN
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - -80
                        type: lt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: OK
          execErrState: Error
          for: 5m
          annotations: {}
          labels:
            domain: field
          isPaused: false
```
Note the `$__timeFilter("time")` in the SQL.

I am then including all of this directly in the YAML configuration for the Grafana helm chart, like so (just showing the beginning of this section for brevity):

```
.
.
.
alerting:
  rules.yaml:
    apiVersion: 1
    groups:
      - orgId: 1
        name: group
        folder: Field
        interval: 1m
        rules:
          - uid: d69e140f-7984-4198-8c3b-c86e4b82ecf6
            title: gb-signal-alert
            condition: C
            data:
              - refId: A
.
.
.
```

However, when I then deploy Grafana with this configuration, the query is not the same one that I have loaded, as the macro is disappearing. The query I see in the Alerting view is:

```
datasource:
  type: postgres
  uid: cloud-tsdb
editorMode: code
format: table
hide: false
intervalMs: 1000
maxDataPoints: 43200
rawQuery: true
rawSql: |-
  SELECT
  "time" AS "time",
  m.subtopic,
  m.num_value AS "signal",
  m.device_id
  FROM messages m
  JOIN devices d
  ON d.id = m.device_id
  WHERE
  ("time") AND
  m.name = 'signal' AND
  d.serial LIKE 'GB%'
  ORDER BY 1
refId: A
sql:
  columns:
    - parameters: []
      type: function
  groupBy:
    - property:
        type: string
      type: groupBy
  limit: 50
```
Note that the SQL WHERE clause now just contains `("time")`, not the original macro.

The same behaviour appears to have been raised in #54076 and #54369 , but these should have been fixed by #54293 in the versions where I have experienced this behaviour.

### What did you expect to happen?

For the query shown in the alerting panel to be exactly the same as the query provisioned in the configuration, i.e. for $__timeFilter("time) to be present in the uploaded query.

### Did this work before?

N/A, first time trying this feature

### How do we reproduce it?

1. Deploy Grafana 10.2.0 in Kubernetes, configured with a TimescaleDB datasource and an alert rule that contains the `__$timeFilter()` macro.
2. Observe that the query seen in the Alerting view does not include the macro, which leads to SQL errors (e.g., in the case of my query, `failed to execute query [A]: db query error: pq: argument of AND must be type boolean, not type timestamp with time zone`)

### Environment (with versions)?

Grafana: 10.2.0 (also experienced on 9.5.7)
OS: Running the official `grafana/grafana` docker image in Kubernetes
Browser: Safari 16.5

### Grafana platform?

Kubernetes

### Datasource(s)?

TimescaleDB v2.9.1
