### ISSUE TITLE
Printed flot graphs lost all colors from legend

### ISSUE THREAD

**Issue by maklaut** [grafana/grafana#775]
I don't have color printer. But printed in pdf (Chrome or Foxit Reader, Windows 7) flot graphs lost all colors from legend.

**Comment by jessetan** [comment]
This is caused by the following CSS in grafana.light.min.HASH.css:
```css
@media print {
    * {
        text-shadow: none!important;
        color: #000!important;
        background: transparent!important;
        box-shadow: none!important
    }
```
Removing the `color` statement disables the color override and keeps the graph colors when printing.
This line is probably meant to ensure white text remains visible when printing on white paper, but is not useful for legends.
It would make more sense to allow legends to keep their color, which allows the printer to render it to greyscale the same way it does the colored graphs.
A possible workaround is to put `!important` in the color statement of the inline style of the legend item, although I don't like to use `!important`.
