### ISSUE TITLE
Alerting: External Alertmanager configurations with ambiguous true/false values can't be modified through Grafana UI

### ISSUE THREAD

**Issue by rwwiv** [grafana/grafana#77956]
**Summary**

When an external Alertmanager has `true` or `false` in a config field that is typed as a string in the Go model, any action that modifies or saves that config in the UI will fail due to a bug in how we decode and re-encode the data when proxying requests. 

**Details**

Grafana creates an intermediary Go struct called `GettableApiAlertingConfig` to translate between the proxied YAML Alertmanager API response and its own JSON response and enforce typing. However, when decoding the YAML response for a config into a `GettableApiAlertingConfig` we also decode that config into a `map[string]interface{}` to avoid redacting secrets when re-encoding (see [here](https://github.com/grafana/grafana/blob/main/pkg/services/ngalert/api/tooling/definitions/alertmanager.go#L660)). The `go-yaml` library infers basic types when decoding this way, which leads to `true` and `false` being interpreted as booleans instead of strings. 

For example, consider the following minimal Alertmanager config:

```yaml
global:
receivers:
  - name: empty-receiver
route:
  receiver: empty-receiver
  routes:
    - receiver: empty-receiver
      continue: false
      match_re:
        label_1: ".*"
        label_2: false
      
templates: []
```

An external Alertmanager will decode the value of `route.routes[0].match_re.label_2` as string `"false"` because of the `UnmarshalYAML` method defined for the field type `Regexp` (see [here](https://github.com/prometheus/alertmanager/blob/ce6efba023b0397cb522d64e910684e48d12455f/config/config.go#L952)). When Grafana proxies the request it will do the same but also decode it as boolean `false` into the `map` mentioned above, which is what's encoded into the response body.

This means that whenever the UI requests the Alertmanager config it will receive an incorrect JSON representation of that config. Then when this incorrect representation is saved the action will fail due to type checking on the backend.
