### ISSUE TITLE
Elasticsearch error: Authentication to data source failed

### ISSUE THREAD

**Issue by Kelphils** [grafana/grafana#78027]
### What happened?

**What happened:**
When I provision the elasticsearch datasource using basic authentication, with CA Certificate enabled, and Skip TLS Verification enabled I get:
Elasticsearch error: Authentication to data source failed

My provision datasources.yaml:
```
apiVersion: 1

datasources:

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: ${ELASTIC_HOSTS}
    basicAuth: true
    basicAuthUser: ${ELASTIC_USER}
    basicAuthPassword: ${ELASTIC_PASSWORD}
    isDefault: false
    jsonData:
      index: '.ds-metricbeat-*'
      tlsSkipVerify: true
      interval: Daily
      timeField: "@timestamp"
      maxConcurrentShardRequests: 5
      tlsAuthWithCACert: true
    secureJsonData:
      tlsCaCert: ${CA_CERT}
      xpack: true
    readOnly: false
```

**However**, when I create the datasource inside grafana using exactly the same parameters (not provisioning) including the content of the exact ca cert used in datasource provisioning file which is found on this path **_"/usr/share/grafana/certs/ca/ca.crt"_** in the grafana container, it connects fine.

<img width="1512" alt="Screenshot 2023-11-12 at 10 31 41" src="https://github.com/grafana/grafana/assets/53217748/6b577c87-5347-450a-b9a1-07f367986545">
<img width="1512" alt="Screenshot 2023-11-12 at 10 30 37" src="https://github.com/grafana/grafana/assets/53217748/bdf25d7a-011a-44fa-b295-8dc80dc6ce56">

      

### What did you expect to happen?

**What I expected to happen:**
That grafana connects the provisioned elasticsearch database using basic-auth, ca certificate without any authentication error

**What I see when inspect the grafana container server logs after I attempt to Test on the console:**
`2023-11-12 11:11:50 logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/uid/P31C819B24CF3C3C7// remote_addr=192.168.65.1 referer=http://localhost:3000/datasources/edit/P31C819B24CF3C3C7 t=2023-11-12T10:11:50.266010214Z level=info msg="Authentication to data source failed" body="{\"error\":{\"root_cause\":[{\"type\":\"security_exception\",\"reason\":\"unable to authenticate user [elastic] for REST request [/]\",\"header\":{\"WWW-Authenticate\":[\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\",\"Bearer realm=\\\"security\\\"\",\"ApiKey\"]}}],\"type\":\"security_exception\",\"reason\":\"unable to authenticate user [elastic] for REST request [/]\",\"header\":{\"WWW-Authenticate\":[\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\",\"Bearer realm=\\\"security\\\"\",\"ApiKey\"]}},\"status\":401}" statusCode=401`

### Did this work before?

No

### How do we reproduce it?

How to reproduce it (as minimally and precisely as possible):
`git clone https://github.com/peasead/elastic-container.git`
To use elasticsearch datasource as provisioning, add the content of file below to the file path **_"provisioning/datasources/datasource.yml "_**:

```
apiVersion: 1

datasources:

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: ${ELASTIC_HOSTS}
    basicAuth: true
    basicAuthUser: ${ELASTIC_USER}
    basicAuthPassword: ${ELASTIC_PASSWORD}
    isDefault: false
    jsonData:
      index: '.ds-metricbeat-*'
      tlsSkipVerify: true
      interval: Daily
      timeField: "@timestamp"
      maxConcurrentShardRequests: 5
      tlsAuthWithCACert: true
    secureJsonData:
      tlsCaCert: ${CA_CERT}
      xpack: true
    readOnly: false
```
 Add **Grafana Service** to docker compose file:
 
```
volumes:
  grafanadata:
    driver: local
  metricbeatdata01:
    driver: local


  grafana:
    depends_on:
      elasticsearch:
        condition: service_healthy
    image: grafana/grafana:${GRAFANA_VERSION}
    container_name: ecp-grafana
    restart: always
    labels:
      co.logs/module: grafana
    environment:
      - GF_USERS_ALLOW_SIGN_UP=true
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTIC_HOSTS=https://ecp-elasticsearch:9200
      - CA_CERT=/usr/share/grafana/certs/ca/ca.crt
    volumes:
      - certs:/usr/share/grafana/certs:z
      - grafanadata:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning:ro
    user: root
    ports:
      - ${GRAFANA_PORT}:3000
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -I -s http://localhost:3000 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 20
```

 Add **Elasticsearch Metricbeat Service** to docker compose file:
 
```
  metricbeat:
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
    image: docker.elastic.co/beats/metricbeat:${STACK_VERSION}
    container_name: ecp-metricbeat
    user: root
    volumes:
      - certs:/usr/share/metricbeat/certs:z
      - metricbeatdata01:/usr/share/metricbeat/data
      - "./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro"
      - "/proc:/hostfs/proc:ro"
      - "/:/hostfs:ro"

    environment:
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTIC_HOSTS=https://ecp-elasticsearch:9200
      - KIBANA_HOSTS=https://ecp-kibana:5601
      - CA_CERT=certs/ca/ca.crt
      - ES_CERT=certs/elasticsearch/elasticsearch.crt
      - ES_KEY=certs/elasticsearch/elasticsearch.key
      - KB_CERT=certs/kibana/kibana.crt
      - KB_KEY=certs/kibana/kibana.key
    command: -strict.perms=false
    
```
 Add **Elasticsearch Metricbeat Modules config** to metricbeat.yml file:
    
```
metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

metricbeat.modules:
- module: elasticsearch
  xpack.enabled: true
  period: 10s
  hosts: ${ELASTIC_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  ssl:
    enabled: true
    certificate_authorities: ${CA_CERT}
    

- module: kibana
  metricsets: 
    - stats
  period: 10s
  hosts: ${KIBANA_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  xpack.enabled: true
  ssl:
    enabled: true
    certificate_authorities: ${CA_CERT}

- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    #- "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true


processors:
  - add_host_metadata: ~
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: ${ELASTIC_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  ssl:
    enabled: true
    certificate_authorities: ${CA_CERT}
```

### Environment (with versions)?

Grafana: V9.5.13
OS: Mac
Browser: Chrome
Elastic products: V8.7.1

### Grafana platform?

Docker

**Comment by rmacian** [comment]
Same here but a little bit different. My password is under secureJsonData:
 
`  datasources.yaml: |-
    apiVersion: 1
    datasources:
    - name: Elasticsearch
      type: elasticsearch
      access: proxy
      url: https://elasticsearch-es-http:9200
      database: core*
      basicAuth: true
      basicAuthUser: elastic
      secureJsonData:
        basicAuthPassword: ${ELASTIC_PASSWORD}
      jsonData:
        esVersion: "80"
        timeInterval: "1m"
        timeField: "@timestamp"
        tlsSkipVerify: "true"`

As you, creating the datasource from portal it works fine. It looks like is not getting skiptlsverify despite configuration in portal looks exactly the same

`logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/uid/q_rBfANIk/_mapping remote_addr=X.X.92.33 referer= t=2023-11-29T15:58:52.746306131Z level=error msg="Proxy request failed" err="tls: failed to verify certificate: x509: certificate signed by unknown authority"
logger=context userId=1 orgId=1 uname=admin t=2023-11-29T15:58:52.746359239Z level=error msg="Request Completed" method=GET path=/api/datasources/proxy/uid/q_rBfANIk/_mapping status=502 remote_addr=X.X.92.33 time_ms=45 duration=45.117434ms size=0 referer= handler=/api/datasources/proxy/uid/:uid/*`

**Comment by Kelphils** [comment]
Thank you for this, after adding my password under secureJsonData it worked. But the underlying issue still remains and should be fixed. When I configure the elastic datasource on the grafana console with just basic auth and ca cert enabled ( using the content of my ca cert ) it connects fine but when I setup this same configuration using datasource provisioning with docker compose it's unable to connect and throws an error regarding authentication. It only works when I enable `tlsSkipVerify: true`, found below is the datasource provisioning configuration which doesn't work, but the same configuration works when setup on the console
```
apiVersion: 1

datasources:

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: ${ELASTIC_HOSTS}
    basicAuth: true
    basicAuthUser: ${ELASTIC_USER}
    isDefault: true
    jsonData:
      index: '.ds-metricbeat-*'
      timeInterval: "10s"
      timeField: "@timestamp"
      maxConcurrentShardRequests: 5
      tlsAuthWithCACert: true 
    secureJsonData:
      tlsCaCert: ${CA_CERT}
      basicAuthPassword: ${ELASTIC_PASSWORD}
      xpack: true
    readOnly: false
```

**Comment by QuinnBast** [comment]
Hi, this is happening to me as well. Mine seems to take the `skipTlsVerify` setting, however, it seems to always be missing the password:


This is my datasource:

```
datasources:
  - name: Elastic
    type: elasticsearch
    uid: elasticsearch
    access: proxy
    basicAuth: true
    basicAuthUser: thisIsMyUser
    secureJsonData:
      basicAuthPassword: thisIsMyPassword
    editable: true
    database: "logstash*"
    url: https://elasticsearch-es-http.elasticsearch:9200
    jsonData:
      tlsSkipVerify: true
      esVersion: "7.12.0"
      timeField: "@timestamp"
      maxConcurrentShardRequests: 256
      logMessageField: message
      dataLinks:
      - datasourceUid: tempo
        field: "message.traceId"
        url: "$${__value.raw}"
```

The logs say:

```
logger=provisioning.datasources t=2025-04-23T23:46:07.820420656Z level=info msg="inserting datasource from configuration" name=Elastic uid=elasticsearch
```

But if I create Grafana and immediately try to query it, I get 401 unauthorized:

![Image](https://github.com/user-attachments/assets/71819e66-6e05-4a54-9bf9-41268d8f780e)

```
logger=tsdb.elasticsearch endpoint=queryData pluginId=elasticsearch dsName=Elastic dsUID=elasticsearch uname=admin fromAlert=false entity=client t=2025-04-23T23:46:46.77782783Z level=error msg="Error received from Elasticsearch" error="Post \"https://elasticsearch-es-http.elasticsearch:9200/_msearch?max_concurrent_shard_requests=256\": 401 Unauthorized" status=error duration=89.149056ms stage=databaseRequest statusSource=downstream
```

However, if I go to the Data Sources tab and manually enter the password and save the datasource and then go back to the explore view, I am able to view my logs

![Image](https://github.com/user-attachments/assets/c96c267e-b568-4b5c-a184-62fe7dd510a3)
