### ISSUE TITLE
Alerting: `$labels` is replaced by empty string into template used to define label (via provisioning)

### ISSUE THREAD

**Issue by davidB** [grafana/grafana#78118]
### What happened?

Context: alert's rules provisioned from configmap into kubernetes cluster (via helm).

`$labels`, used to define a label into a provisioned alert's rule, disappear when rule on the UI (and the yaml got from a copy)

if in configmap
```
apiVersion: 1
groups:
  - orgId: 1
    ...
    rules:
      data:
        ...
        labels:
          namespace: "{{ $labels.k8s_namespace_name }}"
```

Then in UI, or yaml of copied rules, we got `namespace: "{{ .k8s_namespace_name }}"`

### What did you expect to happen?

I expect to be able to use `$labels` in expressions defining another label, like in annotations or alert rules created from web UI.

### Did this work before?

I don't know, but it works for label defined with web UI.

### How do we reproduce it?

1. create a provisioned alert rule with a label defined with `{{ $labels.xyz }}`
2. from web UI look at the alert rule, the label will be displayed with value `{{ .xyz}}`

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 10.1.4
OS:
Browser: Arc (chromium based)

### Grafana platform?

Kubernetes
