### ISSUE TITLE
Flamegraph: Loki Query Links don't work in Pyroscope

### ISSUE THREAD

**Issue by aurbina83** [grafana/grafana#78159]
### What happened?

With the following datasources

```yaml
datasources:
- name: Loki
  type: loki
  url: http://loki:3100
  isDefault: true
  editable: true
  jsonData:
    derivedFields:
      - name: "request_tag"
        matcherRegex: '"request_id"\s*:\s*"(\w+)"'
        url: 'process_cpu:cpu:nanoseconds:cpu:nanoseconds{request_tag="$${__value.raw}"}'
        datasourceUid: pyroscope
      - name: "dd_tag"
        matcherRegex: '"dd\.trace_id"\s*:\s*"(\w+)"'
        url: 'process_cpu:cpu:nanoseconds:cpu:nanoseconds{dd_tag="$${__value.raw}"}'
        datasourceUid: pyroscope
- name: Pyroscope
  type: grafana-pyroscope-datasource
  uid: pyroscope
  url: http://pyroscope:4040
 ```
  
 I am able to generate the `link` in my Loki logs, which produces the following link (decoded) 
```
http://localhost:8201/explore?left={"range":{"from":"now-6h","to":"now"},"datasource":"pyroscope","queries":[{"query":"process_cpu:cpu:nanoseconds:cpu:nanoseconds{request_tag=\"087bbafe3df90ea2d5d00a4292e798e50a5511c375285323ab893ce045545374\"}"}]}
```

![Screenshot 2023-11-14 at 9 44 51 PM](https://github.com/grafana/grafana/assets/11808182/86ac7379-9a11-4c18-b26a-37a97842bb9b)

 
 However, it this doesn't produce anything.
 
![Screenshot 2023-11-14 at 9 45 23 PM](https://github.com/grafana/grafana/assets/11808182/b9230e46-fa02-4a91-8041-5cc1354b596c)

 
 Here is the url (decoded) that is in the browser after clicking the link
 
 ```
http://localhost:8201/explore?panes={"8pT":{"datasource":"P8E80F9AEF21F6940","queries":[{"refId":"A","expr":"{container=\"web-python-1\"} |= `` | json","queryType":"range","datasource":{"type":"loki","uid":"P8E80F9AEF21F6940"},"editorMode":"builder"}],"range":{"from":"now-6h","to":"now"}},"PaG":{"datasource":"pyroscope","queries":[{"groupBy":[],"labelSelector":"{}","queryType":"both","query":"process_cpu:cpu:nanoseconds:cpu:nanoseconds{request_tag=\"087bbafe3df90ea2d5d00a4292e798e50a5511c375285323ab893ce045545374\"}","refId":"A","profileTypeId":"process_cpu:cpu:nanoseconds:cpu:nanoseconds"}],"range":{"from":"1699994555394","to":"1700016155394"}}}&schemaVersion=1&orgId=1
```

However, when I manually put in that tag, I get my profile snapshot

![Screenshot 2023-11-14 at 9 47 42 PM](https://github.com/grafana/grafana/assets/11808182/e3d96e9c-f044-4639-af1d-34d76eb01bc4)

```
http://localhost:8201/explore?panes={"8pT":{"datasource":"P8E80F9AEF21F6940","queries":[{"refId":"A","expr":"{container=\"carta-web-python-1\"} |= `` | json","queryType":"range","datasource":{"type":"loki","uid":"P8E80F9AEF21F6940"},"editorMode":"builder"}],"range":{"from":"now-6h","to":"now"}},"PaG":{"datasource":"pyroscope","queries":[{"groupBy":[],"labelSelector":"{request_tag=\"087bbafe3df90ea2d5d00a4292e798e50a5511c375285323ab893ce045545374\"}","queryType":"both","query":"process_cpu:cpu:nanoseconds:cpu:nanoseconds{request_tag=\"087bbafe3df90ea2d5d00a4292e798e50a5511c375285323ab893ce045545374\"}","refId":"A","profileTypeId":"process_cpu:cpu:nanoseconds:cpu:nanoseconds"}],"range":{"from":"1699994555394","to":"1700016155394"}}}&schemaVersion=1&orgId=1
```

When clicking the link, here are some requests that are made

```
http://localhost:8201/api/datasources/correlations?sourceUID=pyroscope
```
```
http://localhost:8201/api/datasources/uid/pyroscope/resources/profileTypes
```
```
http://localhost:8201/api/datasources/uid/pyroscope/resources/labelNames?query=NaN&start=1699995505000&end=1700017110000
```
```
http://localhost:8201/api/query-history
```
```
http://localhost:8201/api/datasources/uid/pyroscope/resources/labelNames?query=process_cpu%3Acpu%3Ananoseconds%3Acpu%3Ananoseconds%7B%7D&start=1699995505000&end=1700017110000
```

### What did you expect to happen?

I expect the proper query to generate in order to fill the proper tag and it's value into the query editor and for the profile to load.

### Did this work before?

Not that I'm aware of.

### How do we reproduce it?

Making use of the configs above.

```python
import secrets
from logging import getLogger
from time import sleep

# using pyroscope-io==0.8.5
import pyroscope

pyroscope.configure(application_name="app",  server_address="http://localhost:4040")

# set up your log formatter line or json, change matcherRegex for loki accordingly
logger = getLogger("profile-logger")

def create_dummy_id():
  return secrets.token_hex(32)

def some_function():
    request_id = create_dummy_id()
    with pyroscope.tag_wrapper(tags={"request_tag": request_id}):
        time.sleep(4)
        logger.info("Profile Captured", extra={"request_id": request_id)
```

Go to Loki in Grafana, look for log, click link.

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: grafana-oss:10.2.0
OS: MacOS Ventura 13.5.2
Browser: Chrome 119.0.6045.123

### Grafana platform?

Docker
