### ISSUE TITLE
Datasources: Tempo unusable after upgrade to Grafana 10.1.5 from 10.0.5 - rpc error: code = Unavailable desc = connection closed before server preface received

### ISSUE THREAD

**Issue by mroberts91** [grafana/grafana#78356]
## Overview
After upgrading our deployment of Grafana OSS to `10.1.5` using the latest Helm Chart `7.0.6`, we noticed that we could no longer execute Tempo queries.

In the datasource edit screen for our Tempo datasource. Clicking `Save & Test` indicates that the Tempo source is successfully configured and can be connected to. But when you go to the explorer, any query operation is presented with the error `RPC error: code = Unavailable desc = connection closed before server preface received`.

Checking the logs in Tempo `gateway` and Tempo `query-frontend`, Grafana is making successful `HTTP/1.1` requests with 200 status code responses. But there is also an additional `PRI * HTTP/2.0` request that receives a 400 response from the Tempo gateway.

Tempo Gateway Logs after expanding the `Service Name` dropdown in the Tempo Explorer screen.
```logs
172.22.65.219 - - [17/Nov/2023:14:38:52 +0000]  400 "PRI * HTTP/2.0" 158 "-" "-" "-"
172.22.65.219 - - [17/Nov/2023:14:38:52 +0000]  200 "GET /api/v2/search/tag/resource.service.name/values HTTP/1.1" 306 "-" "Grafana/10.1.5" "10.204.195.71, 172.22.66.69, 172.22.66.69"
172.22.65.219 - - [17/Nov/2023:14:38:52 +0000]  200 "GET /api/v2/search/tag/span.undefined/values HTTP/1.1" 2 "-" "Grafana/10.1.5" "10.204.195.71, 172.22.66.69, 172.22.66.69"
172.22.65.219 - - [17/Nov/2023:14:38:52 +0000]  200 "GET /api/v2/search/tag/name/values HTTP/1.1" 3285 "-" "Grafana/10.1.5" "10.204.195.71, 172.22.66.69, 172.22.66.69"
172.22.65.219 - - [17/Nov/2023:14:38:52 +0000]  200 "GET /api/v2/search/tags HTTP/1.1" 768 "-" "Grafana/10.1.5" "10.204.195.71, 172.22.66.69, 172.22.66.69"
```

Leaving Tempo at the latest available version and re-deploying Grafana back to version `10.0.5` resulted in Tempo becoming usable again, and Grafana is no longer attempting that pre-connect handshake request over `HTTP/2.0`

## Environment Setup
- All ingress traffic to Grafana from end users and Tempo ingester traffic is managed through SSL offloading load balancers.
- Requests made from Grafana to the Tempo Gateway are internal cluster traffic over standard HTTP without SSL.

### Grafana (Chart `7.0.6`, App: `10.1.5`)
values.yaml
```yaml
replicas: 1

persistence:
  type: pvc
  enabled: true
  storageClassName: efs

initChownData:
  enabled: false
adminPassword:

ingress:
  enabled: true
  ingressClassName: "alb"
  hosts:
    - [[External Ingress FQDN]]
  path: /
  tls: []

grafana.ini:
  server:
    enable_gzip: true
    root_url: [[External Ingress URL]]
  auth.sigv4_auth_enabled: true
  auth.azuread:
    enabled: true
    name: Azure AD
    allow_sign_up: true
    client_id: [[AAD Info]]
    client_secret: [[AAD Info]]
    scopes: openid email profile
    auth_url: [[AAD Info]]
    token_url: [[AAD Info]]
    allowed_domains:
    allowed_groups:
    role_attribute_strict: false
    auto_assign_org_role: Viewer
    skip_org_role_sync: true
    allow_assign_grafana_admin: true
  feature_toggles:
    enableDatagridEditing: true
    metricsSummary: true
    traceQLStreaming: true
    correlations: true
    nestedFolders: true
    editPanelCSVDragAndDrop: true
  feature_management:
    allow_editing: true


plugins:
  - grafana-synthetic-monitoring-app
  - novatec-sdg-panel
  - mckn-funnel-panel

sidecar:
  datasources:
    reloadURL: "https://[[External Ingress URL]]/api/admin/provisioning/datasources/reload"
  plugins:
    enabled: true
    label: grafana_plugin
    labelValue: "1"
    reloadURL: "https://[[External Ingress URL]]/api/admin/provisioning/plugins/reload"
```

### Tempo-Distributed (Chart: `1.7.0`, App: `2.3.0`)
values.yaml
```yaml
multitenancyEnabled: true
traces:
  otlp:
    http:
      enabled: true
    grpc:
      enabled: true

storage:
  trace:
    backend: s3
    s3:
      bucket: [[Some Bucket]]
      endpoint: "s3.us-west-2.amazonaws.com"
      region: "us-west-2"
gateway:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: "alb"
    annotations:
    hosts:
      - host: [[External Ingress FQDN]]
        paths:
          - path: /
            pathType: Prefix
    tls: []
```

### What did you expect to happen?

Tempo queries to continue to operate as expected.

### Did this work before?

Yes, we are currently deployed with Gafana `10.0.5` and Tempo `2.3.0` and it is working just fine.

### How do we reproduce it?

1. Deploy Grafana `10.1.5` and Tempo-Distributed `2.3.0`
2. Create Tempo Datasource using the Tempo-Distributed deployment as the target
  a. Using a standard HTTP URL for the datasource, e.x `http://tempo-gateway` 
3. Go to the Grafana Data Source Explorer
4. Attempt to execute any query to the Tempo datasource

### Environment (with versions)?

Grafana: `10.1.5`
Tempo: `2.3.0`
Grafana Helm Chart: `7.0.6`
Tempo-Distributed Helm Chart: `1.7.0`
K8s: `1.24.17-eks-4f4795d`
OS: `Windows 10`
Browser: `119.0.6045.160`

### Grafana platform?

Kubernetes

### Datasource(s)?

Tempo 5.0.0
