### ISSUE TITLE
Google Oath2: group mapping dosent work in version 10.2.2 

### ISSUE THREAD

**Issue by dekelummanu** [grafana/grafana#79961]
### What happened?

I upgrade my Grafana version to 10.2.2 so I would be able to map google groups to grafana. I tried multiple veration of the implementation but I always get the default viewer role

### What did you expect to happen?

Grafana will map the GrafanaAdmin role to the relevent group

### Did this work before?

No, its just working if I am mapping specific user to a role

### How do we reproduce it?

Setup the following grafana.ini:

```
grafana.ini:
      server:
        serve_from_sub_path: true
      security:
        disable_initial_admin_creation: true
      auth.basic:
        enabled: false
        disable_login_form: true
      auth.google:
        enabled: true
        allow_sign_up: true
        auto_login: false
        client_id: $__file{/etc/secrets/auth_generic_oauth/client_id}
        client_secret: $__file{/etc/secrets/auth_generic_oauth/client_secret}
        scopes: openid email profile https://www.googleapis.com/auth/cloud-identity.groups.readonly
        auth_url: https://accounts.google.com/o/oauth2/v2/auth
        token_url: https://oauth2.googleapis.com/token
        api_url: https://openidconnect.googleapis.com/v1/userinfo
        #allowed_domains: example.com
        #hosted_domain: example.com
        use_pkce: true
        allow_assign_grafana_admin: true
        skip_org_role_sync: false
        role_attribute_path: contains(groups[*], 'example@example.com') && 'Admin' || 'Viewer'
```

### Environment (with versions)?

Grafana: 10.2.2
OS:
Browser:

### Grafana platform?

Kubernetes
