### ISSUE TITLE
Alerting: provisioning of alerting aren't protected from changes

### ISSUE THREAD

**Issue by dragoangel** [grafana/grafana#80347]
### What happened?

Provisioned policies and contact-points can be modified via `/alerting/admin`

### What did you expect to happen?

Editing and saving of configuration in `/alerting/admin` page should be blocked from modifications if there any provisioned alerting resources like policies, contact-points and notification templates exist - it not fully works this way.

- Resetting to defaults also should be blocked, but in practice, it doesn't.
- Contact-points aren't protected from changes

Resetting could be allowed ONLY if it will re-apply all provisioned resources before ending "reset process", but now the reset button just resets all settings to real Grafana defaults.

### Did this work before?

Nope

### How do we reproduce it?

1. Provision alerting (policies and contact-points)
2. Check that you can't modify policies as they provisioned
3. Check that you can't modify contact-points as they provisioned (but it's doesn't work and you will get modified they provisioned contact-point)
4. Reset settings in Alerting Admin

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 10.1.5
OS: any
Browser: any

### Grafana platform?

Kubernetes

### Datasource(s)?

N/A

**Comment by tonypowa** [comment]
hi @dragoangel 

can you share your contact point .yaml config file? I am trying to provision a contact point but it is just not working for me at the moment. Ensure you redact any sensitive info

thank you

**Comment by dragoangel** [comment]
Hi @tonypowa , I don't have  any sensetive info in my Grafana provisioning, as I use it to send alerts just to Alertmanager, he is reponsible for everything in my case, so I have nothing to hide 😁 at this part

```
apiVersion: 1
contactPoints:
  - name: prometheus-alertmanager
    receivers:
      - uid: prometheus-alertmanager-0
        type: prometheus-alertmanager
        settings:
          url: http://alertmanager-monitoring-0.alertmanager-operated:9093/
      - uid: prometheus-alertmanager-1
        type: prometheus-alertmanager
        settings:
          url: http://alertmanager-monitoring-1.alertmanager-operated:9093/
      - uid: prometheus-alertmanager-2
        type: prometheus-alertmanager
        settings:
          url: http://alertmanager-monitoring-2.alertmanager-operated:9093/
deleteContactPoints:
  - uid: '' # default contact point uid
policies:
  - receiver: prometheus-alertmanager
    group_by: ['...']
    group_wait: 0s
    group_internval: 0s
    repeat_interval: 1m
```
