### ISSUE TITLE
Grafana Tempo datasource: Service graphs does not show any data

### ISSUE THREAD

**Issue by gunpuz** [grafana/grafana#80344]
### What happened?

Grafana tempo does not show any data for service graphs.

![image](https://github.com/grafana/grafana/assets/39419120/176e6062-31ac-400a-a159-01b33cd7f88e)

### What did you expect to happen?

Service graphs are shown

### Did this work before?

- No, not the service graphs, but Traces did work

### How do we reproduce it?

Tempo config (for helm chart grafana/tempo)
```yaml
metrics_generator:
  storage:
    path: "/tmp/tempo"
    remote_write:
      - url: "http://prometheus-server.grafana:80/api/v1/write"
        send_exemplars: true
```

I assume that for service graphs to work you need extra features enabled in grafana.
In grafana Tempo example it is also enabled: https://github.com/grafana/tempo/blob/a6f4f0d74e30b851ae63c652063db724e2888144/example/docker-compose/local/docker-compose.yaml#L45C1-L45C80

Grafana config (for grafana operator)
```yaml
env:
  - name: GF_FEATURE_TOGGLES_ENABLE
    value: "traceQLStreaming metricsSummary"
```
But this results in issue below:
![image](https://github.com/grafana/grafana/assets/39419120/e82325be-32e4-496c-8d8a-bd05b583779f)

If grafana features are not enabled, then there is no error querying the traces, but service graphs are not shown

### Environment (with versions)?

Grafana: Grafana v10.2.2

### Grafana platform?

Kubernetes

### Datasource(s)?

Grafana tempo
