### ISSUE TITLE
Alerting: add provisioning of ngalert `alertmanagersChoice`

### ISSUE THREAD

**Issue by dragoangel** [grafana/grafana#80349]
**Why is this needed**:

Most usable cases when you have Grafana and external Alertmanager is k8s environment with kube-prometheus-stack

To have proper handling in helm charts and to be aligned with other provisioning we need provide possibility to configure `alertmanagersChoice` via provisioning that will protect this settings from modifications.

**What would you like to be added**:

Add new provisioning resource in API:
```yaml
apiVersion: 1
alertmanagers:
  choice: internal|external|all
```

**Who is this feature for?**

To provide proper customization of settings via provisioning related to important part of Grafana

**Comment by stevehipwell** [comment]
CC @mellieA

**Comment by dragoangel** [comment]
I also have big concerns in a way Grafana handles Prometheus alertmanager that is deployed in HA mode.
It sends alert only to one IP, when on practice it should use all IPs from headless service for alertmanager, as by the standart alertmanager do not have alerts replication between alertmanagers, only silences are replicated. Now this can be achieved by setting contact points for each alertmanager directly into one contact in helm template like:
```yaml
    apiVersion: 1
    contactPoints:
      - name: prometheus-alertmanager
        receivers:
        {{- if gt ( .Values.alertmanager.alertmanagerSpec.replicas | int ) 1 }}
        {{- range $i, $e := until ( .Values.alertmanager.alertmanagerSpec.replicas | int ) }}
          - uid: prometheus-alertmanager-{{$i}}
            type: prometheus-alertmanager
            settings:
              url: http://alertmanager-monitoring-{{$i}}.alertmanager-operated:9093/
        {{- end }}
        {{- else }}
          - uid: prometheus-alertmanager
            type: prometheus-alertmanager
            settings:
              url: http://alertmanager-monitoring.alertmanager-operated:9093/
        {{- end }}
```

But in general this is workaround and not a solution, especially if we moving to datasources from contact points, as having datasources for each alertmanager of one HA cluster is even sounds wrong.

`alertmanager-operated` is headless service that returns all pods in HA, Grafana should take them all as one, and send alert to all of them
