### ISSUE TITLE
Grafana HA: memberlist Failed to Join

### ISSUE THREAD

**Issue by AndreOrlovE** [grafana/grafana#80507]
### What happened?

Grafana in HA mode tries to join "old" PODs IP
```
level=debug memberlist="2024/01/13 17:19:05 [DEBUG] memberlist: Failed to join 10.92.6.162:9094: dial tcp 10.92.6.162:9094: i/o timeout\n"
level=debug memberlist="2024/01/13 17:18:55 [DEBUG] memberlist: Failed to join 10.92.7.29:9094: dial tcp 10.92.7.29:9094: i/o timeout\n"
```

### What did you expect to happen?

Grafana should do a retry to resolve current IPs of the headless service

### Did this work before?

N/A

### How do we reproduce it?

1. Installing Grafana helm chart
```
- name: grafana
  version: "7.1.0"
  repository: "https://grafana.github.io/helm-charts"
```

values.yaml (partially)
```
grafana:
  replicas: 2
  headlessService: true
  grafana.ini:
    database:
      type: postgres
      ...
    unified_alerting:
      enabled: true
      ha_peers: grafana-headless.grafana:9094
      ha_listen_address: ${POD_IP}:9094
      ha_advertise_address: ${POD_IP}:9094

  # https://grafana.com/docs/grafana/latest/alerting/set-up/configure-high-availability/
  envValueFrom:
    POD_IP:
      fieldRef:
        fieldPath: status.podIP
```

2. Getting EP of the Headless service
```
kubectl get ep
grafana-headless                                 10.92.6.162:9094,10.92.7.29:9094
```

3. Restart PODs:
`kubectl rollout restart deploy/grafana`

4. Checking Headless service:
```
kubectl get ep
grafana-headless                                 10.92.2.73:9094,10.92.9.5:9094
```
5. Checking logs
```
level=debug memberlist="2024/01/13 17:19:05 [DEBUG] memberlist: Failed to join 10.92.6.162:9094: dial tcp 10.92.6.162:9094: i/o timeout\n"
level=debug memberlist="2024/01/13 17:18:55 [DEBUG] memberlist: Failed to join 10.92.7.29:9094: dial tcp 10.92.7.29:9094: i/o timeout\n"
```

Grafana is trying to join IPs, which were used by the "old" pods (before rollout restart)

### Environment (with versions)?

Grafana: v10.2.3 (1e84fede54)
Helm 7.1.0

### Grafana platform?

Kubernetes

**Comment by tonypowa** [comment]
Hi @AndreOrlovE 

Thank you very much for your detailed report

Could you please provide the Grafana logs after the restart happens? 

Have you configured any liveness or readiness probes for your Grafana pods?

`note for reviewer`; please reroute if the issue does not belong to your squad

**Comment by AndreOrlovE** [comment]
@tonypowa hi!
we have the following configuration:
```
    livenessProbe:
      failureThreshold: 10
      httpGet:
        path: /api/health
        port: 3000
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 30
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /api/health
        port: 3000
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
```
it comes by default
https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L73
