### ISSUE TITLE
[Bug] Hipchat alert channel to private server fails with webhook 400 (bad response)

### ISSUE THREAD

**Issue by xrl** [grafana/grafana#8072]
Please include this information:
- What Grafana version are you using?
`grafana/grafana:4.2.0`
- What datasource are you using?
Nothing yet, still in the configuration screen for alert channels
- What OS are you running grafana on?
Docker on CoreOS managed by Kubernetes.
- What did you do?
Configure the webhook, reusing credentials I have with my python script that runs with the Hypchat lib. Those webhooks work. Here's the configuration screen:
![image](https://cloud.githubusercontent.com/assets/693059/24820917/811b5cf8-1ba0-11e7-9366-b9d05a01d053.png)

- What was the expected result?
I should see a test message in my hipchat alerts room.
- What happened instead?
The grafana UI has a red toast alert saying "failed to send alert notification". Grafana container's stdout reports error:
```
t=2017-04-07T21:43:33+0000 lvl=info msg="Sending notification" logger=alerting.notifier type=hipchat id=0 isDefault=false
t=2017-04-07T21:43:33+0000 lvl=info msg="Executing hipchat notification" logger=alerting.notifier.hipchat ruleId=0 notification=Hipchat
t=2017-04-07T21:43:33+0000 lvl=eror msg="Failed to send hipchat notification" logger=alerting.notifier.hipchat error="Webhook response status 400 Bad Request" webhook=Hipchat
t=2017-04-07T21:43:33+0000 lvl=eror msg="Failed to send alert notifications" logger=context userId=0 orgId=1 uname= error="Webhook response status 400 Bad Request"
t=2017-04-07T21:43:33+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=1 uname= method=POST path=/api/alert-notifications/test status=500 remote_addr=10.233.85.0 time_ms=40ns size=48
```

**Comment by devkid** [comment]
Can you [enable debug mode](http://docs.grafana.org/installation/configuration/#level)? This should print the full response in the logs.

**Comment by xrl** [comment]
Ah, interesting. Looks like the issue is how I configure grafana for mounting inside of kubernetes reverse proxy. Here's the debug output:

```
t=2017-04-10T21:04:13+0000 lvl=info msg="Sending notification" logger=alerting.notifier type=hipchat id=0 isDefault=false
t=2017-04-10T21:04:13+0000 lvl=info msg="Executing hipchat notification" logger=alerting.notifier.hipchat ruleId=0 notification=hipchat
t=2017-04-10T21:04:13+0000 lvl=dbug msg="Sending webhook" logger=notifications.webhook url="https://my.server.com/v2/room/1234/notification?auth_token=ASDF" http method=
t=2017-04-10T21:04:14+0000 lvl=dbug msg="Webhook failed" logger=notifications.webhook statuscode="400 Bad Request" body="{\n  \"error\": {\n    \"code\": 400,\n    \"message\": \"Invalid protocol used by url /api/v1/proxy/namespaces/metrics/services/grafana/\",\n    \"type\": \"Bad Request\"\n  }\n}"
t=2017-04-10T21:04:14+0000 lvl=eror msg="Failed to send hipchat notification" logger=alerting.notifier.hipchat error="Webhook response status 400 Bad Request" webhook=hipchat
t=2017-04-10T21:04:14+0000 lvl=eror msg="Failed to send alert notifications" logger=context userId=0 orgId=1 uname= error="Webhook response status 400 Bad Request"
t=2017-04-10T21:04:14+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=1 uname= method=POST path=/api/alert-notifications/test status=500 remote_addr=10.233.85.0 time_ms=292ns size=48
```

Which jives with my grafana kube yaml:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
  namespace: metrics
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:4.2.0
        ports:
          - containerPort: 3000
            protocol: TCP
        volumeMounts:
        - mountPath: /var
          name: grafana-storage
        env:
        - name: INFLUXDB_HOST
          value: influxdb
        - name: GRAFANA_PORT
          value: "3000"
          # The following env variables are required to make Grafana accessible via
          # the kubernetes api-server proxy. On production clusters, we recommend
          # removing these env variables, setup auth for grafana, and expose the grafana
          # service using a LoadBalancer or a public IP.
        - name: GF_AUTH_BASIC_ENABLED
          value: "false"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: Admin
        - name: GF_SERVER_ROOT_URL
          # If you're only using the API Server proxy, set this value instead:
          value: /api/v1/proxy/namespaces/metrics/services/grafana/
          # value: /
        - name: GF_LOG_LEVEL
          value: "debug"
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-storage
```

Looks like I need to fully qualify the `GF_SERVER_ROOT_URL`.
