### ISSUE TITLE
Mapping value to text does't work in singlestat panel

### ISSUE THREAD

**Issue by andreevym** [grafana/grafana#8128]
Configuration:
```
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    links:
      - influxdb
    networks:
      - net
```

From Logs on start:

> grafana     | t=2017-04-14T10:56:55+0000 lvl=info msg="Starting Grafana" logger=main version=4.2.0 commit=349f3eb compiled=2017-03-22T10:06:41+0000

Case:

![image](https://cloud.githubusercontent.com/assets/8217718/25043153/87fb5060-2126-11e7-9ed7-ab8b3995f31c.png)
![image](https://cloud.githubusercontent.com/assets/8217718/25043166/9a7a9930-2126-11e7-920b-ae2dcfe0b8ee.png)
