### ISSUE TITLE
[Question] Does a "login" API method exist ?

### ISSUE THREAD

**Issue by JeromeVi** [grafana/grafana#8160]
Please include this information:
- What Grafana version are you using?  4.2
- What datasource are you using? Prometheus
- What OS are you running grafana on? macOS Sierra
- What did you do? Looking into the doc to find a API method to log an user.
- What was the expected result? A method like `POST grafana_url/api/user/login data{username,password}´ 
- What happened instead? I founded nothing

So as I said, I'm looking for a API method to log an user.
My goal is to avoid the login page of Grafana.

So is there a method that would do the job ?

Thank you

**Comment by torkelo** [comment]
since login is not really the preferred way to authenticate api calls the login call is not part of the /api/ namespace and docs.

But if you have chrome dev tools network tab open (with preserve log checked), and login you can see the frontend making a call to POST /login with a json body with user, and password. You will get cookies back in the response that need to be included in subsequent calls.

**Comment by JeromeVi** [comment]
@torkelo  thank you for the fast answer ! If you could just help me to find this `POST /login` I'd be grateful

**Comment by JeromeVi** [comment]
@torkelo if you can just help me a little bit I'd be grateful ! I made a POST method and in my term I have : 
```
 { statusCode: 200,
   content: '{"message":"Logged in"}',
   headers:
    { 'content-type': 'application/json',
      'set-cookie':
       [ 'grafana_sess=75670a9e5d7c2535; Path=/; HttpOnly',
         'grafana_user=Guest; Path=/; Max-Age=604800',
         'grafana_remember=bcbf40b31bf4d057b39b7deb50c0e921163e59d6a87f119e; Path=/; Max-Age=604800' ],
      date: 'Wed, 19 Apr 2017 06:13:04 GMT',
      'content-length': '23',
      connection: 'close' },
   data: { message: 'Logged in' } }
```

but it keeps displaying the login page... any ideas ?

**Comment by torkelo** [comment]
so you include all the cookies when you make the request after the login call?

**Comment by JeromeVi** [comment]
Hmm I don't understand 100%, for the moment I made a HTTP.call and it returns me the code that I posted just before.

What you say is that I need to take the cookies that I get here `set-cookie:[....`  in the browser right ?

**Comment by torkelo** [comment]
if your going to fake being a browser I suggest reading how cookies work :)

**Comment by torkelo** [comment]
it's much easier to use the HTTP api with basic auth or an api key, no login required

**Comment by JeromeVi** [comment]
Thank you for the advice :) 

Nah but look I'll put some screenshots to show you my problem.
In my app user can display a Graph and it's like this: 
![capture d ecran 2017-04-19 a 08 26 41](https://cloud.githubusercontent.com/assets/22610050/25166125/0d3f3726-24da-11e7-8cc3-9e6ed5a6df32.png)

And I want to avoid this step of login. That's why I need to make a "login call" you see ?

Maybe you have a better idea ?

**Comment by torkelo** [comment]
are you using an iframe? maybe you need to enable anonymous access in that case. 

How do you make the login call in the iframe?

**Comment by JeromeVi** [comment]
Yes I use an iframe.

For the moment I made a listener on the right-menu "Grafana monit" who make a call and returns the code that I posted before.

Does anonymous access make the same access rights as a "viewer user" ?

**Comment by torkelo** [comment]
you can configure what permission anonymous users get  http://docs.grafana.org/installation/configuration/#auth-anonymous

**Comment by JeromeVi** [comment]
it sounds good ! I'll try to implement this way and then I come back here to give you a feedback

**Comment by JeromeVi** [comment]
Here for the feedback, so I added in my docker-compose:
```
mgmt-app:
    image: gitlab-${DOCKERADM_ENV}:5005/xyx/mgmt-docker-gui:lab
    container_name: mgmt-app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker:/root/.docker
    environment:
      - ROOT_URL=http://localhost:80
      - MONGO_URL=mongodb://mgmt-mongo:27017/meteor
      - GF_SECURITY_ADMIN_USER=admin_grafana
      - GF_SECURITY_ADMIN_PASSWORD=changeme
      - GF_AUTH_ANONYMOUS=true
      - DOCKERADM_ENV=$DOCKERADM_ENV
    ports:
      - 80:80
    restart: always
```

but I think it's not right because I still have the login page..

**Comment by torkelo** [comment]
there is no key named GF_AUTH_ANONYMOUS, only a section. should be GF_AUTH_ANONYMOUS_ENABLED=true

**Comment by JeromeVi** [comment]
hmm it's pretty strange because it still show me this login page. 

  mgmt-app:
  ```
  image: gitlab-${DOCKERADM_ENV}:5005/xyx/mgmt-docker-gui:lab
    container_name: mgmt-app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker:/root/.docker
    environment:
      - ROOT_URL=http://localhost:80
      - MONGO_URL=mongodb://mgmt-mongo:27017/meteor
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SECURITY_ADMIN_USER=admin_grafana
      - GF_SECURITY_ADMIN_PASSWORD=changeme
      - DOCKERADM_ENV=$DOCKERADM_ENV
    ports:
      - 80:80
    restart: always

  grafana:
    image: gitlab-${DOCKERADM_ENV}:5005/docker/grafana
    container_name: grafana
    volumes:
      - mgmt_grafana_data:/var/lib/grafana
    environment:
      # - GF_SECURITY_ADMIN_USER=admin_grafana
      # - GF_SECURITY_ADMIN_PASSWORD=changeme
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - 3000:3000
    labels:
      org.label-schema.group: "monitoring"
```

My docker-compose is like this. I'll keep working on that and come back here when it'll work
