### ISSUE TITLE
Tempo: Grafana Tempo Datasource "Loki Search" using the wrong query

### ISSUE THREAD

**Issue by victoruzunovjuro** [grafana/grafana#81653]
### What happened?

I have configured Tempo and Loki datasources in Grafana with traces to logs  and vice verca. Config:

```yaml
     - name: Loki
        type: loki
        uid: loki
        orgId: 1
        access: proxy
        url: http://loki-gateway
        isDefault: false
        jsonData:
          maxLines: 5000
          timeout: 300
          manageAlerts: false
          derivedFields:
            - datasourceUid: "tempo"
              matcherRegex: '"customTrace":"(.*?)"'
              name: TraceID
              url: '{.customTrace="$${__value.raw}"}'
              urlDisplayLabel: 'Open Tempo'
      - name: Tempo
        type: tempo
        uid: tempo
        orgId: 1
        access: proxy
        url: http://tempo-gateway
        isDefault: false
        jsonData:
          tracesToLogsV2:
            datasourceUid: "loki"
            tags: ['customTrace']
            spanStartTimeShift: "-15m"
            spanEndTimeShift: "15m"
            filterByTraceID: false
            filterBySpanID: false
            customQuery: true
            query: '{app="$${__span.tags["service.name"]}"} |= "$${__span.tags.customtrace}"'
          nodeGraph:
            enabled: true
          serviceMap:
            datasourceUid: 1
          lokiSearch:
            datasourceUid: "loki"
 ```

The problem lies in the integration of Tempo's datasource's "Loki Search" feature. When executing a query through this function, it generates a table displaying TraceIDs for each log entry. However, these TraceIDs are hyperlinked to Tempo but those links do not include URL defined in Loki's derived fields. Consequently, attempting to access the trace via these links results in a 404 error as they are not valid traces. In contrast, when the same query is performed directly within Loki's datasource, the log entry links to Tempo correctly incorporate the URL in the query, ensuring successful navigation to Tempo.

For example, after parsing the URL of the link from Tempo's "Loki Search" feature the query in the link is: `[{"query":"some_id"}]`, while from the Loki's datasource it's `[{"query":"{.customtrace=\"some_id\"}","queryType":"traceql"}]}`.

### What did you expect to happen?

I expect both of the hyperlinks to to work the same way.

### Did this work before?

I don't think so.

### How do we reproduce it?

1. Integrate Tempo and Loki as datasources in Grafana, ensuring the "Logs to Traces" and "Traces to Logs" functionalities are correctly configured.
2. For the Loki datasource, establish derived fields that format URLs as `url: '{.customtrace="$${__value.raw}"}'`.
3. Navigate to Loki and conduct a search to find a log entry that contains a link directing to Tempo.
4. Examine the structure of the link's queries, which should resemble: `queries: [{"query":"{.customtrace=\"some_id\"}","queryType":"traceql"}]}`.
5. Access the Loki Search feature within the Tempo datasource and execute the identical query.
6. The outcome will be presented in a table format, where each trace ID is associated with a hyperlink. Notably, the structure of the link's query will differ, appearing as `"queries":[{"query":"some_id"}]`.

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 10.3.1
OS: any
Browser: any

### Grafana platform?

None
