### ISSUE TITLE
Authentication: User logins sometimes breaks Grafana (OpenShift oauth-rpoxy)

### ISSUE THREAD

**Issue by R-Studio** [grafana/grafana#82262]
### What happened?

Sometimes when I log in to Grafana, I get the following errors and Grafana hangs for about 30 seconds (get a 504 Gateway time-out):
```
logger=user.sync t=2024-02-08T15:47:27.385024849Z level=error msg="Failed to fetch user" error="context canceled" auth_module=authproxy auth_id=<REDACTED>
logger=authn.service t=2024-02-08T15:47:27.385095343Z level=error msg="Failed to run post auth hook" client=auth.client.proxy id= error="[user.sync.internal] unable to retrieve user"
```

### What did you expect to happen?

Grafana runs without any hangs.

### Did this work before?

I have not noticed this with Grafana 9.2.1 and I cannot reproduce it.

### How do we reproduce it?

_It is really not easy to reproduce it._
1. Deploy Grafana with the Grafana Operator v5.6.2 on OpenShift with a OpenShift oauth-proxy container.
2. Open a icognito browser tab and login with OpenShift (SAML)
3. Go to Explore wait until the Prometheus metrics are loaded (in code view)
4. Repeat step 1-3 for 1-10 times.

### Is the bug inside a dashboard panel?

no, the whole Grafana hangs for all users and sometime even the ReadinessProbe on `/api/health` fails and I have configured a timeout of 30 seconds.

### Environment (with versions)?

Grafana: 10.1.6, 10.2.3, 10.3.1
OS: Grafana Docker Image on OpenShift Workernodes
Browser: Edge, Chrome
OpenShift oauth-proxy: 4.12, 4.13, 4.14

### Grafana platform?

Kubernetes

### Datasource(s)?

Prometheus 2.39.x

**Comment by R-Studio** [comment]
# Grafana Custom Resource
```yaml
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
  name: grafana-oauth
  namespace: grafana
  labels:
    app: grafana
    app.kubernetes.io/managed-by: Helm
spec:
  client:
    preferIngress: false
  config:
    security:
      admin_password: <REDACTED>
      admin_user: <REDACTED>
      disable_gravatar: 'true'
    plugins:
      enable_alpha: 'false'
      plugin_admin_enabled: 'true'
    server:
      root_url: 'https://grafana.apps.mydomain.com'
      serve_from_sub_path: 'true'
    log:
      level: warn
      mode: console
    analytics:
      check_for_plugin_updates: 'false'
      check_for_updates: 'false'
      enabled: 'false'
      reporting_enabled: 'false'
    auth.anonymous:
      enabled: 'false'
    auth.basic:
      enabled: 'true'
    auth:
      disable_login_form: 'false'
      disable_signout_menu: 'false'
      oauth_allow_insecure_email_lookup: 'true'
      oauth_auto_login: 'false'
      skip_org_role_sync: 'true'
    users:
      auto_assign_org: 'true'
      auto_assign_org_id: '1'
      auto_assign_org_role: Viewer
    auth.proxy:
      auto_sign_up: 'true'
      enabled: 'true'
      header_name: X-Forwarded-User
      header_property: username
      skip_org_role_sync: 'true'
    database:
      wal: 'true'
  deployment:
    spec:
      replicas: 1
      strategy:
        type: Recreate
      template:
        spec:
          containers:
            - args:
                - '-provider=openshift'
                - '-pass-basic-auth=false'
                - '-https-address=:9091'
                - '-http-address='
                - '-email-domain=*'
                - '-upstream=http://localhost:3000'
                - '-tls-cert=/etc/tls/private/tls.crt'
                - '-tls-key=/etc/tls/private/tls.key'
                - >-
                  -client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token
                - '-cookie-secret-file=/etc/proxy/secrets/session_secret'
                - '-cookie-expire=24h'
                - '-openshift-service-account=grafana-oauth-sa'
                - '-openshift-ca=/etc/pki/tls/cert.pem'
                - >-
                  -openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                - '-openshift-ca=/etc/proxy/certs/ca-bundle.crt'
                - '-skip-provider-button=true'
                - '-skip-auth-regex=^/metrics'
                - '-skip-auth-regex=^/api/health'
              image: >-
                <REDACTED>/openshift/origin-oauth-proxy:4.12
              name: grafana-proxy
              ports:
                - containerPort: 9091
                  name: https
                  protocol: TCP
              resources:
                limits:
                  cpu: 400m
                  memory: 250Mi
                requests:
                  cpu: 50m
                  memory: 50Mi
              volumeMounts:
                - mountPath: /etc/tls/private
                  name: secret-grafana-tls
                  readOnly: false
                - mountPath: /etc/proxy/secrets
                  name: secret-grafana-proxy
                  readOnly: false
                - mountPath: /etc/proxy/certs
                  name: configmap-ocp-injected-certs
                  readOnly: false
            - image: '<REDACTED>/grafana/grafana:10.3.1'
              name: grafana
              readinessProbe:
                failureThreshold: 2
                timeoutSeconds: 30
              resources:
                limits:
                  cpu: '2'
                  memory: 16Gi
                requests:
                  cpu: 300m
                  memory: 128Mi
              volumeMounts:
                - mountPath: /var/lib/grafana
                  name: grafana-data
                - mountPath: /etc/grafana-secrets/grafana-tls
                  name: secret-grafana-tls
                - mountPath: /etc/grafana-secrets/grafana-proxy
                  name: secret-grafana-proxy
                - mountPath: /etc/grafana-configmaps/ocp-injected-certs
                  name: configmap-ocp-injected-certs
                - mountPath: /etc/grafana/provisioning/plugins
                  name: grafana-provision-plugins
                - mountPath: /etc/grafana/provisioning/dashboards
                  name: grafana-provision-dashboards
                - mountPath: /etc/grafana/provisioning/notifiers
                  name: grafana-provision-notifiers
                - mountPath: /etc/grafana/provisioning/alerting
                  name: grafana-provision-alerting
                - mountPath: /etc/grafana/provisioning/datasources
                  name: grafana-provision-datasources
          imagePullSecrets:
            - name: <REDACTED>
          volumes:
            - name: grafana-data
              persistentVolumeClaim:
                claimName: grafana-oauth-pvc
            - name: secret-grafana-tls
              secret:
                secretName: grafana-tls
            - name: secret-grafana-proxy
              secret:
                secretName: grafana-proxy
            - configMap:
                defaultMode: 420
                name: ocp-injected-certs
              name: configmap-ocp-injected-certs
            - emptyDir:
                sizeLimit: 1Gi
              name: grafana-provision-plugins
            - emptyDir:
                sizeLimit: 100Mi
              name: grafana-provision-dashboards
            - emptyDir:
                sizeLimit: 100Mi
              name: grafana-provision-notifiers
            - emptyDir:
                sizeLimit: 100Mi
              name: grafana-provision-alerting
            - emptyDir:
                sizeLimit: 100Mi
              name: grafana-provision-datasources
  persistentVolumeClaim:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: <REDACTED>
  route:
    spec:
      host: grafana.apps.mydomain.com
      port:
        targetPort: https
      tls:
        termination: reencrypt
      to:
        kind: Service
        name: grafana-oauth-service
        weight: 100
      wildcardPolicy: None
  service:
    metadata:
      annotations:
        service.beta.openshift.io/serving-cert-secret-name: grafana-tls
    spec:
      ports:
        - name: https
          port: 9091
          protocol: TCP
          targetPort: https
  serviceAccount:
    metadata:
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        serviceaccounts.openshift.io/oauth-redirectreference.primary: >-
          {"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"grafana-oauth-route"}}
```

Unfortunately I haven't found an example `Grafana` resource for OpenShift in version `grafana.integreatly.org/v1beta1`
