### ISSUE TITLE
x509: failed to load system roots and noroots provided (after Github OAuth)

### ISSUE THREAD

**Issue by olalonde** [grafana/grafana#8226]
I'm getting an error after logging with Github for the first time:

```
t=2017-04-26T22:33:05+0000 lvl=eror msg=login.OAuthLogin(NewTransportWithCode) logger=context userId=0 orgId=0 uname= error="Post https://github.com/login/oauth/access_token: x509: failed to load system roots and noroots provided"
t=2017-04-26T22:33:05+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/github status=500 remote_addr=104.193.169.246 time_ms=56ns size=702
```

I'm using the following K8s manifest file:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitoring-grafana
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: grafana
    spec:
      containers:
      - name: grafana
        image: gcr.io/google_containers/heapster-grafana-amd64:v4.0.2
        ports:
          - containerPort: 3000
            protocol: TCP
        volumeMounts:
        - mountPath: /var
          name: grafana-storage
        env:
        - name: INFLUXDB_HOST
          value: monitoring-influxdb
        - name: GRAFANA_PORT
          value: "3000"
          # The following env variables are required to make Grafana accessible via
          # the kubernetes api-server proxy. On production clusters, we recommend
          # removing these env variables, setup auth for grafana, and expose the grafana
          # service using a LoadBalancer or a public IP.
        - name: GF_AUTH_BASIC_ENABLED
          value: "false"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "false"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: Admin
        - name: GF_SERVER_ROOT_URL
          # If you're only using the API Server proxy, set this value instead:
          # value: /api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/
          value: http://monitoring.staging.me.com/
        # Custom config for enabling Github auth
        - name: GF_AUTH_GITHUB_ENABLED
          value: "true"
        - name: GF_AUTH_GITHUB_ALLOWED_ORGANIZATIONS
          value: "myorghere"
        - name: GF_AUTH_GITHUB_ALLOW_SIGN_UP
          value: "true"
        - name: GF_AUTH_GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: me-monitoring-github-oauth
              key: clientId
        - name: GF_AUTH_GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: me-monitoring-github-oauth
              key: clientSecret
      volumes:
      - name: grafana-storage
        emptyDir: {}

```

**Comment by olalonde** [comment]
I'm guessing this is because the Docker image doesn't contain root certificates? https://github.com/kubernetes/heapster/blob/master/grafana/Dockerfile

**Comment by olalonde** [comment]
Fixed by mounting ssl certs from host:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitoring-grafana
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: grafana
    spec:
      containers:
      - name: grafana
        image: gcr.io/google_containers/heapster-grafana-amd64:v4.0.2
        ports:
          - containerPort: 3000
            protocol: TCP
        volumeMounts:
        - mountPath: /var
          name: grafana-storage
        - mountPath: /etc/ssl/certs
          name: etc-ssl-certs
        env:
        - name: INFLUXDB_HOST
          value: monitoring-influxdb
        - name: GRAFANA_PORT
          value: "3000"
          # The following env variables are required to make Grafana accessible via
          # the kubernetes api-server proxy. On production clusters, we recommend
          # removing these env variables, setup auth for grafana, and expose the grafana
          # service using a LoadBalancer or a public IP.
        - name: GF_AUTH_BASIC_ENABLED
          value: "true"
        - name: GRAFANA_PASSWD
          valueFrom:
            secretKeyRef:
              name: me-monitoring-basic-auth
              key: password
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: me-monitoring-basic-auth
              key: password
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "false"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: Admin
        - name: GF_USERS_ALLOW_SIGN_UP
          value: "false"
        - name: GF_SERVER_PROTOCOL
          value: "http"
        - name: GF_SERVER_DOMAIN
          value: "monitoring.staging.me.com"
        - name: GF_SERVER_ROOT_URL
          # If you're only using the API Server proxy, set this value instead:
          # value: /api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/
          value: http://monitoring.staging.me.com/
        # Custom config for enabling Github auth
        - name: GF_AUTH_GITHUB_ENABLED
          value: "true"
        - name: GF_AUTH_GITHUB_ALLOWED_ORGANIZATIONS
          value: "blockai me"
        - name: GF_AUTH_GITHUB_ALLOW_SIGN_UP
          value: "true"
        - name: GF_AUTH_GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: me-monitoring-github-oauth
              key: clientId
        - name: GF_AUTH_GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: me-monitoring-github-oauth
              key: clientSecret
      volumes:
      - name: grafana-storage
        emptyDir: {}
      - name: etc-ssl-certs
        hostPath:
          path: /etc/ssl/certs
```
