### ISSUE TITLE
add logging for not available `deleteDatasources`

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82664]
### Discussed in https://github.com/grafana/grafana/discussions/70333

<div type='discussions-op-text'>

<sup>Originally posted by **rdxmb** June 19, 2023</sup>
When having these lines in `datasource.yaml`

```
apiVersion: 1
deleteDatasources:
  - name: existing
  - name: nonexisting
datasources:
# ---- SNIP
```

there is no output about the nonexisting datasource (like `datasource nonexisting does not exist, ignoring ...` ), even when loglevel is `debug`.

In my case, `nonexisting` had I typo when I initially had provisioned it. As I did not remember the typo, I first did not see what's the problem, as the datasource was not removed. </div>
