### ISSUE TITLE
Alerting: Fix inconsistent behavior between loki and mimir when using filesystem provisioned alerts 

### ISSUE THREAD

**Issue by jmichalek132** [grafana/grafana#83032]
### What happened?

When using Mimir with [local storage](https://grafana.com/docs/mimir/latest/references/architecture/components/ruler/#local-storage) the Grafana Alerting page offers the option to edit & remove the alerts however, Mimir doesn't support these operations when using local storage.
![Screenshot 2024-02-18 143515](https://github.com/grafana/grafana/assets/7171250/472d303f-3b8e-427b-95d1-de5fe147211b)

So when users try either of the options they get an error message.

### What did you expect to happen?

When using Loki with the same local storage, the options are missing, which makes sense since Loki also doesn't support edit / delete with the local storage. I would expect Grafana to behave the same way with Mimir.
 
![Screenshot 2024-02-18 143412](https://github.com/grafana/grafana/assets/7171250/063f20e0-21ff-489f-8154-6afc23f2278c)

### Did this work before?

Not sure.

### How do we reproduce it?

Running mimir:
1. Run mimir locally using https://github.com/grafana/mimir/tree/main/development
2. Edit https://github.com/grafana/mimir/blob/main/development/mimir-microservices-mode/config/mimir.yaml#L81 
to use backend local:
```yaml
  backend: local
  local:
    directory: "/mimir/config/rules"
```
3. Create rules folder in https://github.com/grafana/mimir/tree/main/development/mimir-microservices-mode/config and alert file
```yaml
groups:
  - name: tempo_alerts
    rules:
      - alert: TempoRequestLatency
        annotations:
          summary: |
            {{ $labels.service_component }} {{ $labels.route }} is experiencing s 99th percentile latency.
          runbook_url: https://github.com/grafana/tempo/tree/main/operations/tempo-mixin/runbook.md#TempoRequestLatency
        expr: |
          cluster_namespace_job_route:tempo_request_duration_seconds:99quantile{route!~"metrics|/frontend.Frontend/Process|debug_pprof",deployment_environment="prod"} > 3
        for: 15m
        labels:
          severity: crit
```
4. Run mimir `./development/mimir-microservices-mode/compose-up.sh`
5. Visit the alerting page `http://localhost:3000/alerting/list`

Running Loki:
1. Run loki locally using https://github.com/grafana/loki/tree/main/production/docker
2. Edit https://github.com/grafana/loki/blob/main/production/docker/config/datasources.yaml#L5
to enable alert management:
```yaml
  - access: proxy
    basicAuth: false
    jsonData:
      manageAlerts: true
      httpHeaderName1: "X-Scope-OrgID"
    secureJsonData:
      httpHeaderValue1: "docker"
    editable: true
    isDefault: true
    name: loki
    type: loki
    uid: loki
    url: http://loki-gateway
    version: 1
```
3. Update nginx config to allow Grafana calling the backend target
Insert here https://github.com/grafana/loki/blob/main/production/docker/config/nginx.conf#L26
```
  upstream backend {
    server loki-backend:3100;
  }
```
Insert here https://github.com/grafana/loki/blob/main/production/docker/config/nginx.conf#L67
```

    # Ruler
    location = /ruler/ring {
      proxy_pass       http://backend$request_uri;
    }
    location = /api/prom/rules {
      proxy_pass       http://backend$request_uri;
    }
    location ^~ /api/prom/rules/ {
      proxy_pass       http://backend$request_uri;
    }
    location = /loki/api/v1/rules {
      proxy_pass       http://backend$request_uri;
    }
    location ^~ /loki/api/v1/rules/ {
      proxy_pass       http://backend$request_uri;
    }
    location = /prometheus/api/v1/alerts {
      proxy_pass       http://backend$request_uri;
    }
    location = /prometheus/api/v1/rules {
      proxy_pass       http://backend$request_uri;
    }
```
4. Run Loki `docker-compose up`
5. Visit the alerting page `http://localhost:3000/alerting/list`

### Environment (with versions)?

Grafana: 10.3.3
OS: Ubuntu
Browser: Chrome

### Grafana platform?

Kubernetes

### Datasource(s)?

Mimir & Loki
