### ISSUE TITLE
Upgrading to 10.3.3 causes "frame cannot uniquely be identified by it's labels" errors for alerts that were previously working fine

### ISSUE THREAD

**Issue by danfinn** [grafana/grafana#83448]
### What happened?

We recently attempted to upgrade from 10.2.3 to 10.3.3 for the recent security fix.  Unfortunately we quickly saw that this caused errors with multiple alerts and from multiple datasource types.  The error is:

```
Invalid format of evaluation results for the alert definition : frame cannot uniquely be identified by its labels: has duplicate results with labels {}
```

Revert back to 10.2.3 fixes the issue.

I found another person having the same issue:
https://www.reddit.com/r/grafana/comments/1ay5egy/getting_this_alert_error_in_grafana_1033_what_am/

### What did you expect to happen?

alerts to continue to function

### Did this work before?

yes

### How do we reproduce it?

1. upgrade to 10.3.3
2. check alerts for above error
3.

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 10.3.3
OS: mac
Browser: chrome

### Grafana platform?

Kubernetes

**Comment by tonypowa** [comment]
hi @danfinn 

Can you list the specific datasource types that you observed this error with?

Is there any chance you could provide us with a minimal reproducible example or the steps you took before the error showed up, beyond just upgrading Grafana?

**Comment by danfinn** [comment]
It looks like we were seeing this with both prometheus and elasticsearch datasources which is all that we use for alerts.  As far as a reproducible example, I'm not sure what you mean.  Would you like the yaml for one of the alerts?  We have existing alerts, we upgraded to 10.3.3 and we started getting this error, there were no other changes made on our end.

**Comment by tonypowa** [comment]
hi @danfinn 

yes the yaml could be helpful thank you!

In the meantime I am routing this issue to the Alerting team

**Comment by danfinn** [comment]
here is one example of an alert that caused this error:

```
     - orgId: 1
       name: Elasticsearch
       folder: Elasticsearch
       interval: 1m
       rules:
         - uid: e6076bf4-4864-4927-8fe9-252c969b03e1
           title: Elasticsearch heap size per node
           condition: C
           data:
             - refId: JVM by node
               relativeTimeRange:
                 from: 1800
                 to: 0
               datasourceUid: 2b206d77-decd-47ad-b41c-a5465022c1f6
               model:
                 alias: ""
                 bucketAggs:
                     - field: elasticsearch.node.name.keyword
                       id: "2"
                       settings:
                         min_doc_count: "1"
                         order: desc
                         orderBy: _term
                         size: "10"
                       type: terms
                     - field: '@timestamp'
                       id: "3"
                       settings:
                         interval: 10m
                         min_doc_count: "0"
                         timeZone: utc
                         trimEdges: "0"
                       type: date_histogram
                 datasource:
                     type: elasticsearch
                     uid: 2b206d77-decd-47ad-b41c-a5465022c1f6
                 hide: false
                 intervalMs: 1000
                 maxDataPoints: 43200
                 metrics:
                     - field: elasticsearch.node.stats.jvm.mem.heap.used.pct
                       id: "1"
                       type: max
                 query: 'event.dataset: elasticsearch.node.stats'
                 refId: JVM by node
                 timeField: '@timestamp'
             - refId: reduce JVM
               relativeTimeRange:
                 from: 1800
                 to: 0
               datasourceUid: __expr__
               model:
                 conditions:
                     - evaluator:
                         params: []
                         type: gt
                       operator:
                         type: and
                       query:
                         params:
                             - B
                       reducer:
                         params: []
                         type: last
                       type: query
                 datasource:
                     type: __expr__
                     uid: __expr__
                 expression: JVM by node
                 hide: false
                 intervalMs: 1000
                 maxDataPoints: 43200
                 reducer: max
                 refId: reduce JVM
                 settings:
                     mode: dropNN
                 type: reduce
             - refId: C
               relativeTimeRange:
                 from: 1800
                 to: 0
               datasourceUid: __expr__
               model:
                 conditions:
                     - evaluator:
                         params:
                             - 85
                         type: gt
                       operator:
                         type: and
                       query:
                         params:
                             - C
                       reducer:
                         params: []
                         type: last
                       type: query
                 datasource:
                     type: __expr__
                     uid: __expr__
                 expression: reduce JVM
                 hide: false
                 intervalMs: 1000
                 maxDataPoints: 43200
                 refId: C
                 type: threshold
           dashboardUid: ""
           panelId: 0
           noDataState: NoData
           execErrState: Error
           for: 30m
           annotations:
             summary: Elasticsearch heap size is above 85% on one or more nodes, please investigate.
           labels:
             BMAP_PagerDuty: "True"
             Teams: "True"
           isPaused: false
```
