### ISSUE TITLE
[auth.proxy] With basic authentication with htpassword

### ISSUE THREAD

**Issue by sistemmsn** [grafana/grafana#83652]
### What happened?

I am trying to configure the reverse proxy server with basic authentication, it works and everything, but when I logoff it gives an error and the console appears that ws:localhost/grafana/api/live/ws fails, that happens with the simple The fact of having it in the proxy, I don't know if it affects

![image](https://github.com/grafana/grafana/assets/38023703/89a77bdc-7e85-4903-951e-3afcc98d6f26)

![image](https://github.com/grafana/grafana/assets/38023703/1c7d0155-cd3f-48da-b5b8-368d1c6c0e9b)

### What did you expect to happen?

I want to use htpassword as a password manager from the browser

```
<VirtualHost *:80>
	ServerAdmin webmaster@authproxy
	ServerName authproxy
	ErrorLog "logs/authproxy-error_log"
	CustomLog "logs/authproxy-access_log" common

	<Proxy *>
		AuthType Basic
        AuthName GrafanaAuthProxy
		AuthBasicProvider file
		AuthUserFile /opt/nagios/etc/htpasswd.users
		Require valid-user

		RewriteEngine On
		RewriteRule .* - [E=PROXY_USER:%{LA-U:REMOTE_USER},NS]
		RequestHeader set X-WEBAUTH-USER "%{PROXY_USER}e"
	</Proxy>

RequestHeader unset Authorization
ProxyRequests Off
ProxyPass /grafana http://grafana:3000/
ProxyPassReverse /grafana http://grafana:3000/

</VirtualHost>

```
That my configuration I also tried using nginx according to the Grafana documentation, but it gives the same result

https://grafana.com/tutorials/run-grafana-behind-a-proxy/

![image](https://github.com/grafana/grafana/assets/38023703/ea1d88b8-8b32-45dd-bc4d-884ce31a7811)

### Did this work before?

Well, it is functional, but I don't know if it is a good result.

### How do we reproduce it?

```
version: "3.9"
    
services:


 grafana:
   container_name: grafana
   hostname: grafana
   image: grafana/grafana
   restart: always
   volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./grafana.ini:/etc/grafana/grafana.ini
      - gdb:/var/lib/grafana
   environment:
     GF_INSTALL_PLUGINS: sni-pnp-datasource, briangann-gauge-panel
   networks:
    proxy:

 httpd:
    build:
      context: .
      dockerfile: Dockerfile-httpd
    container_name: httpd
    hostname: httpd
    ports:
      - 80:80
    volumes:
      - ./grafana.conf:/etc/httpd/conf.d/grafana.conf
      - ./htpasswd.users:/opt/nagios/etc/htpasswd.users  
    networks:
     proxy:

volumes:
  gdb:


networks:
  proxy:
    external: true
```

grafana.ini

```
[server]


# The public facing domain name used to access grafana from a browser
domain = localhost

# Redirect to correct domain if host header does not match domain
# Prevents DNS rebinding attacks
;enforce_domain = false

# The full public facing url you use in browser, used for redirects and emails
# If you use reverse proxy and sub path specify full url (with sub path)
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/

;root_url = http://grafana:3000/grafana/

# Serve Grafana from subpath specified in `root_url` setting. By default it is set to `false` for compatibility reasons.
serve_from_sub_path = true


#################################### Security ####################################
[security]


# set to true if you want to allow browsers to render Grafana in a <frame>, <iframe>, <embed> or <object>. default is false.
allow_embedding = true


#################################### Dashboards History ##################
[dashboards]
# Number dashboard versions to keep (per dashboard). Default: 20, Minimum: 1
;versions_to_keep = 20

# Minimum dashboard refresh interval. When set, this will restrict users to set the refresh interval of a dashboard lower than given interval. Per default this is 5 seconds.
# The interval string is a possibly signed sequence of decimal numbers, followed by a unit suffix (ms, s, m, h, d), e.g. 30s or 1m.
min_refresh_interval = 1m

# Path to the default home dashboard. If this value is empty, then Grafana uses StaticRootPath + "dashboards/home.json"
;default_home_dashboard_path =

#################################### Users ###############################
[users]
# disable user signup / registration
allow_sign_up = false

# Allow non admin users to create organizations
;allow_org_create = true

# Set to true to automatically assign new users to the default organization (id 1)
auto_assign_org = true

# Set this value to automatically add new users to the provided organization (if auto_assign_org above is set to true)
;auto_assign_org_id = 1

# Default role new users will be automatically assigned
auto_assign_org_role = Admin


#################################### Anonymous Auth ######################
[auth.anonymous]
# enable anonymous access
;enabled = false

# specify organization name that should be used for unauthenticated users
;org_name = Main Org.

# specify role for unauthenticated users
;org_role = Viewer

# mask the Grafana version number for unauthenticated users
;hide_version = false
[panels]
# If set to true Grafana will allow script tags in text panels. Not recommended as it enable XSS vulnerabilities.
disable_sanitize_html = true
################################## Feature Management ##############################################
[feature_management]
hidden_toggles =
read_only_toggles =

[auth.proxy]
enabled = true
header_name = X-WEBAUTH-USER
enable_login_token = true
header_property = username
auto_sign_up = true

[auth]
login_cookie_name = grafana_session

```

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: version 10.2.3
OS: Docker 
Browser: Chrome and edge

### Grafana platform?

Other
