### ISSUE TITLE
Alerting: Emailing using Google's SMTP server timeouts

### ISSUE THREAD

**Issue by cloudvlad** [grafana/grafana#83758]
### What happened?

The Grafana Helm chart was deployed. As part of it, the following configurations for the SMTP server were added so we can send emails when some of the alert rules are triggered:
```
  grafana:
    grafana.ini:
      smtp:
        enabled: true
        host: smtp.google.com:587 # or 465
        user: notifications-mail@google.com
        password: << Google App Password >>
        skip_verify: false
        from_address: notifications-mail@google.com
        from_name: Grafana
```
Although the configurations above are picked up by the Grafana pods and accordingly added to the grafana.ini file in the pod itself, when sending emails manually through the test functionality, a following timeout popup is shown:
`Failed to send test alert.:the receiver timed out: failed to send notification to email address personal-mail@google.com: dial tcp 64.233.166.27:465: i/o timeout`

I also tried pining the SMTP server of Google from the Grafana pod itself, which was successful

![image](https://github.com/grafana/grafana/assets/66917571/3b9268bb-6fee-4c14-846e-5afcabb58d54)
![image](https://github.com/grafana/grafana/assets/66917571/d114a03b-1f08-4c30-9e7c-a349a64358e9)

### What did you expect to happen?

It was expected that after an alert rule was triggered, or a notification was sent manually, indeed the one in question would be sent successfully.

### Did this work before?

Not tested.

### How do we reproduce it?

1. Create Kubernetes cluster
2. Deploy the Grafana Helm chart (+ Prometheus [25.10.0](https://artifacthub.io/packages/helm/prometheus-community/prometheus/25.10.0) )
3. Try sending an email using the Grafana Test email functionality incorporating Google SMTP.

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

OS: Ubuntu 22.04.2 LTS
Kubernetes Server version: v1.27.2
Grafana Helm chart version: [7.2.5](https://artifacthub.io/packages/helm/grafana/grafana/7.2.5)

### Grafana platform?

Kubernetes
