### ISSUE TITLE
PostgreSQL: table dropdown empty, code-editor works

### ISSUE THREAD

**Issue by PhilippDehner** [grafana/grafana#83833]
### What happened?

- I clicked on the table selector in the query builder (PostgreSQL)
- Nothing happened (empty dropdown) even though the database connection works
- Enter the table name manually is also not possible

### What did you expect to happen?

The available tables are shown in the dropdown in the query builder

### Did this work before?

In previous grafana versions there was an old / another query builder

### How do we reproduce it?

- I added a postgresql datasource via provisioned datasource:
```
apiVersion: 1
datasources:
- name: TestDB
  type: postgres
  orgId: 1
  uid: postgres_test
  url: postgres:5432
  database: TestDB
  user: test
  secureJsonData:
    password: "test"
  jsonData:
    sslmode: "disable"
    postgresVersion: 1300
    timescaledb: false
```

- I opened the explorer tab with this datasource. 

- I added the same datasource manually in the GUI of grafana
- I opened the explorer tab and clicked on the table selector

### Environment (with versions)?

Grafana: 10.3.3
OS: Windows (grafana in docker, WSL)
Browser: Firefox 123

### Grafana platform?

Docker

### Datasource(s)?

PostgreSQL
