### ISSUE TITLE
Dashboard: Unable to logout

### ISSUE THREAD

**Issue by faraonc** [grafana/grafana#84108]
### What happened?

Clicking the "Sign Out" does not perform a logout.

This is the configuration that we have running.
```
      auth:
        disable_signout_menu: false
        disable_login_form: false
        signout_redirect_url: https://*****/.pomerium/sign_out

      auth.jwt:
        enabled: true
        header_name: *****
        email_claim: email
        jwk_set_url: https://*****/.well-known/pomerium/jwks.json
        cache_ttl: 60m
        auto_sign_up: true
        username_claim: name
        signout_redirect_url: https://*****/.pomerium/sign_out
        skip_org_role_sync: true
```

These are the logs from grafana instance

```
logger=login.authinfo.store t=2024-03-07T23:13:20.06451902Z level=debug msg="Updated user_auth" user_id=10 auth_id=116854288800683668488 auth_module=jwt rows=1
logger=accesscontrol.service t=2024-03-07T23:13:20.071753651Z level=debug msg="Using cached permissions" key=rbac-permissions-1-user-10
logger=authn.service t=2024-03-07T23:13:20.074302441Z level=debug msg="Client do not support specialized logout logic" client=auth.client.jwt
logger=http.server t=2024-03-07T23:13:20.074331284Z level=error msg="Failed perform proper logout" error="user token not found"
logger=http.server t=2024-03-07T23:13:20.074361975Z level=info msg="Successful Logout" userID=10
logger=context userId=10 orgId=1 uname="******" t=2024-03-07T23:13:20.07488499Z level=error msg="Request error" error="runtime error: invalid memory address or nil pointer dereference" stack="runtime/panic.go:261 (0x50b7537)\nruntime/signal_unix.go:861 (0x50b7505)\ngithub.com/grafana/grafana/pkg/api/login.go:268 (0x88bc752)\ngithub.com/grafana/grafana/pkg/api/response/web_hack.go:40 (0x61d794f)\nnet/http/server.go:2136 (0x54102c8)\ngithub.com/grafana/grafana/pkg/web/macaron.go:131 (0x61ca3ce)\nnet/http/server.go:2136 (0x54102c8)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x61ca472)\nnet/http/server.go:2136 (0x54102c8)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x61ca472)\nnet/http/server.go:2136 (0x54102c8)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x61ca472)\nnet/http/server.go:2136 (0x54102c8)\ngithub.com/grafana/grafana/pkg/services/contexthandler/contexthandler.go:144 (0x88ddbf7)\nnet/http/server.go:2136 (0x54102c8)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x61ca472)\nnet/http/server.go:2136 (0x54102c8)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x61ca472)\nnet/http/server.go:2136 (0x54102c8)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x61ca472)\nnet/http/server.go:2136 (0x54102c8)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x61ca472)\nnet/http/server.go:2136 (0x54102c8)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x61ca472)\nnet/http/server.go:2136 (0x54102c8)\ngithub.com/grafana/grafana/pkg/web/render.go:44 (0x61caf5d)\nnet/http/server.go:2136 (0x54102c8)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x61ca472)\nnet/http/server.go:2136 (0x54102c8)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x61ca472)\nnet/http/server.go:2136 (0x54102c8)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x61ca472)\nnet/http/server.go:2136 (0x54102c8)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x61ca472)\nnet/http/server.go:2136 (0x54102c8)\ngithub.com/grafana/grafana/pkg/middleware/csrf/csrf.go:66 (0x7efb91a)\nnet/http/server.go:2136 (0x54102c8)\ngithub.com/grafana/grafana/pkg/middleware/recovery.go:180 (0x88b6c7d)\nnet/http/server.go:2136 (0x54102c8)\ngithub.com/grafana/grafana/pkg/middleware/loggermw/logger.go:72 (0x7efc936)\nnet/http/server.go:2136 (0x54102c8)\ngithub.com/grafana/grafana/pkg/middleware/request_metrics.go:83 (0x67c4a15)\nnet/http/server.go:2136 (0x54102c8)\ngithub.com/grafana/grafana/pkg/middleware/request_tracing.go:88 (0x88b7955)\nnet/http/server.go:2136 (0x54102c8)\ngithub.com/grafana/grafana/pkg/middleware/requestmeta/request_metadata.go:66 (0x88dcc95)\nnet/http/server.go:2136 (0x54102c8)\ngithub.com/grafana/grafana/pkg/web/context.go:52 (0x61c8eb6)\ngithub.com/grafana/grafana/pkg/web/router.go:155 (0x61cc62d)\ngithub.com/grafana/grafana/pkg/web/router.go:211 (0x61cd194)\ngithub.com/grafana/grafana/pkg/web/macaron.go:163 (0x61ca89c)\nnet/http/server.go:2938 (0x5412fad)\nnet/http/server.go:2009 (0x540ee93)\nruntime/asm_amd64.s:1650 (0x50d6a40)\n"
logger=context userId=10 orgId=1 uname="******" t=2024-03-07T23:13:20.074956406Z level=info msg="Request Completed" method=GET path=/logout status=302 remote_addr=10.104.1.29 time_ms=25 duration=25.604445ms size=29 referer="https://******/?orgId=1" handler=/logout
```

### What did you expect to happen?

Gets logged out.

### Did this work before?

It works with version `9.3.1`.
```
  auth:
    disable_signout_menu: false
    disable_login_form: false
    signout_redirect_url: https://******/.pomerium/sign_out

  auth.jwt:
    enabled: true
    header_name: ******
    email_claim: email
    jwk_set_url: https://******/.well-known/pomerium/jwks.json
    cache_ttl: 60m
    auto_sign_up: true
    username_claim: name
```

This is not an upgrade but a fresh deployment.

### How do we reproduce it?

1. In the UI, click the profile icon
2. Click "Sign Out"
3. It goes back to the dashboard`

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 10.3.4
OS: MacOS, Ubuntu
Browser: CHrome

### Grafana platform?

Kubernetes
