### ISSUE TITLE
Error checking server process execution privilege. error: could not get current OS user to detect process privileges

### ISSUE THREAD

**Issue by ajaufura** [grafana/grafana#84134]
### What happened?

I am getting the following error when running the Grafana docker container with docker-compose and also not be able to access the UI :  

Error checking server process execution privilege. error: could not get current OS user to detect process privileges
Error: ✗ failed to get config section log. console: section "log.console" does not exist

Here is part of my docker compose file :  
grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "1000"
    volumes:
    - /home/pi/appdata/loki_stack/grafana:/var/lib/grafana

    ports:
      - "3000:3000"
    restart: always

The grafana folder permissions :  
drwxr-xr-x 7 pi pi 4096 Mar  8 02:00 grafana

I am using the correct uid : 
id -u : 1000

Docker & docker compose version :
docker -v : Docker version 25.0.4, build 1a576c5
docker compose version : Docker Compose version v2.24.7

However, when i tested with the image grafana/grafana:10.3.1, I am not having the previous error and I can access the UI.

### What did you expect to happen?

I expect no errors and be able to access the UI.

### Did this work before?

Yes, I had no issue with this docker compose configuration before on the same host.

### How do we reproduce it?

1. Deploy the container using the image grafana/grafana:latest with docker compose
2. Use the "id -u" value for the "user" in the compose file
3. Check the logs and try to access the UI

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by tonypowa** [comment]
Hello @ajaufura 

Try:

1. define the docker-compose.yml

``` yml
version: '1'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - /home/pi/appdata/loki_stack/grafana/:/var/lib/grafana # persists Grafana database
    restart: unless-stopped
    ports:  
      - "3000:3000"
```

2. Where docker-compose.yml is:

`chown 472:root path-to-the-mounted-volume` . Eg. `chown 472:root ./grafana-db/` 

3. run as root `sudo docker compose up -d`
