### ISSUE TITLE
Provisioning/Alerting: Environment variable substitution not working for annotations

### ISSUE THREAD

**Issue by eloo-abi** [grafana/grafana#84250]
### What happened?

Hi, 
we are working on enhancing our alerting right now and for this we want to use the environment variable substitution a bit more but have discovered that it is not working as expected.

We use currently env substitution for the labels in our alert files which is working.
But it looks like it is, for unknown reasons, not working when we try it in annotations which is unexpected.

We deploy our Grafana instance with Helm and use the provisioning path for setting up our alerts like this:

```
    extraConfigmapMounts:
      - name: grafana-alerts-provisioning
        subPath: ""
        mountPath: /etc/grafana/provisioning/alerting
        configMap: grafana-alerts
        readOnly: true
```

Below you can see that we have tested a few combinations for the annotations but in the screenshot you see its not rendered. 
But for the labels its working as expected.

### What did you expect to happen?

Environments variables are substituted in annotations in the same way as in labels.

### Did this work before?

no

### How do we reproduce it?

Alert file
```
apiVersion: 1
groups:
  - orgId: 1
    name: Kyverno
    folder: folder
    interval: 1m
    rules:
      - uid: 6pbn5054k
        title: Temporary role found
        condition: C
        data: ...
        noDataState: OK
        execErrState: Error
        for: 5m
        annotations:
          category: '{{ $labels.category }}'
          description: A temporary role was found
          policy: '{{ $labels.policy }}'
          severity: '{{ $labels.severity }}'
          summary: Temporary role found
          link: https://link.$AWS_REGION.$CLUSTER.tld/#/cluster-policy-reports/kyverno?policies={{$labels.policy}}
          link2: https://link.${AWS_REGION}.${CLUSTER}.tld/#/cluster-policy-reports/kyverno?policies={{$labels.policy}}
          link3: "https://link.${AWS_REGION}.${CLUSTER}.tld/#/cluster-policy-reports/kyverno?policies={{$labels.policy}}"
          link4: "https://link.$${AWS_REGION}.$${CLUSTER}.tld/#/cluster-policy-reports/kyverno?policies={{$labels.policy}}"
        labels:
          link: https://link.$AWS_REGION.$CLUSTER.tld/#/cluster-policy-reports/kyverno?policies={{$$labels.policy}}
          cluster: $CLUSTER
          level: error
          region: $REGION
          audiences: platform
        isPaused: false
```

Results in rendered label but not rendered in annotations

![image](https://github.com/grafana/grafana/assets/49561925/6c83fb0c-36fe-4864-8572-cbc2c2a52b3c)

### Environment (with versions)?

Grafana: v10.3.3 (252761264e)
OS:
Browser:

### Grafana platform?

Kubernetes

**Comment by wasim-nihal** [comment]
Hi @JohnnyQQQQ, is this open for contribution? I'd like to open a PR for the same.

**Comment by JohnnyQQQQ** [comment]
Yes it is. You can see how to implement it by taking a look at how we do it for labels here https://github.com/grafana/grafana/blob/bd2b248f0e3a0fe7724549af2880007c3af2da19/pkg/services/provisioning/alerting/rules_types.go#L123-L130

So instead of doing `alertRule.Annotations = rule.Annotations.Raw` for the annotations, we should do something similar to this.

**Comment by JohnnyQQQQ** [comment]
After a bit of further research, I now remember why we removed it. Please check out https://github.com/grafana/grafana/issues/54850

We might want to find a way to support both.

**Comment by wasim-nihal** [comment]
Sure, I will explore a bit of template expansion and make changes to support both kinds of expansions.

**Comment by wasim-nihal** [comment]
@JohnnyQQQQ , after looking into the codebase of the environment variable expander, I see it is possible to prevent the expansion and preserve the original formatting by prefixing the expression with an additional `$`.

For example, `{{ $labels.instance }}` can be modified to `{{ $$labels.instance }}` to prevent environment variable expansion and let the template expander take care to expand down the line. And, for users wanting to use env variable expansion can use `${ENV_VARIABLE}`

I have validated these scenarios with from the binary build from the above commit (that uses `.Value()` for annotations)

Please do let me know your thoughts on this.

### Snippet of alert rule used for local testing:
```
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            description: this is example annotation description
            summary: 'Alert fired for {{ $$labels.instance }}'
            annotationEnv: ${ENV_ANNOTATION}
          labels:
            something: newthing
            instanceIs: '{{ $$labels.instance }}'
          isPaused: false
          notification_settings:
            receiver: myslack
```

### Test Notification Received on Slack:
<img width="386" alt="image" src="https://github.com/grafana/grafana/assets/38865967/b5518148-0f33-4fb5-bebe-85edd2b5ef3b">
