### ISSUE TITLE
Ability to declarativily define a dashboard as Shared Public.

### ISSUE THREAD

**Issue by reefland** [grafana/grafana#85313]
**Why is this needed**:

Following gitops, I have all my `datasources`, ` dashboardProviders` and `dashboards` predefined, external authentication  and do not have a need for Grafana persistent storage. This is working great until I had the need to share dashboards externally.  I don't see anything documented within how dashboard or dashboardProviders are defined to make dashboards "public".

Yes, I can use the GUI to share > public and generate a public URL but this is lost without persistence and this is not declarative.

**What would you like to be added**:

This is probably not ideal, but marking a specific provider with something like `makePublic: true` (default `false`):
```
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: public
          orgId: 1
          folder: Public Dashboards
          makePublic: true
          type: file
          options:
            path: /var/lib/grafana/dashboards/public-dashboard-folder
```
Where any dashboard assigned to this provider would automatically be shared as Public.  

I think a better idea is something at a per dashboard level.  Something in Grafana to enable helm to allow:
```
  dashboards:
    public:
        url: https://raw.githubusercontent.com/<USER>/<repo>/grafana-dashboard.json
        makePublic: true
        datasource:
          - { name: DS_PROMETHEUS, value: Prometheus }
```

Where `makePublic:` can be `false` (default) or `true`.

Ideally with either scenario:
* The GUI would only be required to fetch the generated public URL.
* The dynamically generated URL should be reproducible without needing persistence (based on hash of specific fields?) or allow a GUID to be specified instead of generated??

**Who is this feature for?**

Users who configure Grafana via declarative GitOps.

**Comment by ole-kaas** [comment]
We have solved it by calling the API when Grafana is deployed by Helm. We also found a quick and dirty solution where we use sqlite to manipulate the db file directly. But we found it to be too sketchy

## Public dashboards
Grafana has no way of setting a dashboard to public in a declarative way.  It is possible to enable "public" on a dashboard by using the Grafana API. This requires a few steps to do this when Grafana is deployed:

  * Let the Helm chart create an initial admin user and source the admin user/password from a created secret.
  * Provide the admin user/password secret from a key vault, sealed secret or other safe method.
  * Build a "/scripts/setup.sh" script that will:
    * Check that Grafana API is available
    * Login to Grafana API, create a Grafana service account, and request a token for the account
    * Loop through "public dashboard" entries (using the token):
       * check once pr. second that dashboard exists
       * Send the API payload that will make the dashboard public
       * Timeout 30 seconds - skip to next dashboard entry.
  * Build a "scripts/run.sh" wrapper script that will:
    * run the "/scripts/setup.sh" in background
    * start Grafana (run the original /run.sh script)
    * The setup.sh script will now run in the background doing its thing while Grafana starts up.
  * Dump the scripts in a configMap together with the dashboard IDs and API payloads. Mount the configMap in the main Grafana container on /scripts path.
  * Configure Helm chart to run the /scripts/run.sh instead of the /run.sh on startup. 

ConfigMap:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-cm
  namespace: monitoring
  annotations:
    internal.config.kubernetes.io/needsHashSuffix: enabled
data:
  run.sh: |
    sh /scripts/setup.sh 2>&1 | tee /tmp/setup.log &
    exec sh /run.sh
  setup.sh: |
    START_TIME=$(date +%s)
    START_DATE=$(date)

    while true; do
      sleep 1
      curl --silent --fail http://localhost:3000/api/health | tee /tmp/health || continue
      (grep '"database":' /tmp/health | grep '"ok"') >/dev/null && break
    done

    BASE_URL="http://$GF_SECURITY_ADMIN_USER:$GF_SECURITY_ADMIN_PASSWORD@localhost:3000"
    USERID=$(curl --silent --fail -H "Content-Type: application/json" -d '{"name":"api-calls", "role": "Admin"}' ${BASE_URL}/api/serviceaccounts | sed -E 's/.+"id":([0-9]+).+/\1/')
    TOKEN=$(curl --silent --fail -H "Content-Type: application/json" -d '{"name":"api-token"}' ${BASE_URL}/api/serviceaccounts/${USERID}/tokens | sed -E 's/.+"key":"([^"]+)".+/\1/')

    for DASHBOARD in $(find /scripts -maxdepth 1 -iname "*.id" -exec basename -s .id {} \;) ; do
      ID=$(tr -d "\n" < /scripts/${DASHBOARD}.id)
      while true; do
        NOW=$(date +%s)
        DURATION=$((NOW-START_TIME))
        [ $DURATION -lt 30 ] || break
        curl --silent --fail -H "Content-Type: application/json" -H "Authorization: Bearer ${TOKEN}" http://localhost:3000/api/dashboards/uid/${ID} && break
        sleep 1
      done
      curl --silent --fail -H "Content-Type: application/json" -H "Authorization: Bearer ${TOKEN}" -d @/scripts/${DASHBOARD}.json http://localhost:3000/api/dashboards/uid/${ID}/public-dashboards/
    done

    NOW=$(date +%s)
    {
      printf 'Start date: '
      echo $START_DATE
      printf 'End date: '
      date
      echo "Duration: $((NOW-START_TIME))"
    } > /tmp/setup.report

  public-dashboard.id: c9d6355d-90c9-4683-9ad3-4033b8c1cf25
  public-dashboard.json: |
    {
      "accessToken": "7d543d3cdaae410ca7ce6383edabc5ca",
      "timeSelectionEnabled": false,
      "isEnabled": true,
      "annotationsEnabled": false,
      "share": "public"
    }

```

Important Helm values:
```yaml
      admin:
        existingSecret: credentials
        userKey: user
        passwordKey: password
      extraVolumeMounts:
        - mountPath: /scripts
          name: scripts
      extraVolumes:
        - name: scripts
          configMap:
            name: scripts-cm
      command:
        - sh
        - /scripts/run.sh
```

## Quick hack

Below a quick and dirty and unsupported solution, that was a part of the investigation to make dashboards public.

The not selected solution:
```
      lifecycleHooks:
        postStart:
          exec:
           command:
             - /bin/sh
             - -c
             - sleep 30 && cd /tmp && wget https://www.sqlite.org/2024/sqlite-tools-linux-x64-3460000.zip && unzip sqlite-tools-linux-x64-3460000.zip && (/tmp/sqlite3 /var/lib/grafana/grafana.db "REPLACE INTO dashboard_public (uid, dashboard_uid, org_id, time_settings, template_variables, access_token, created_by, updated_by, created_at, updated_at, is_enabled, annotations_enabled, time_selection_enabled, share) VALUES ('d0218b95-6e91-4124-b54e-d1fa27027ba3','c9d6355d-90c9-4683-9ad3-4033b8c1cf25',1,'{}','','7d543d3cdaae410ca7ce6383edabc5ca',1,1,'2024-08-08 06:14:03','2024-08-08 06:14:03',1,0,0,'public');" || true)

```
