### ISSUE TITLE
Alerting: Incorrect indentation in yaml specifaction of alert during export

### ISSUE THREAD

**Issue by mile95** [grafana/grafana#86089]
### What happened?

When modifying a provisioned alert and exporting the alert the indentation level seems incorrect. 

For instance; 
1. goto: https://play.grafana.org/alerting/FEXxVXN7k/modify-export?returnTo=%2Falerting%2Flist 
2. press export
3. select yaml

The code has the incorrect indentation level. 

```yaml
apiVersion: 1
groups:
    - orgId: 1
      name: Multi series alerting
      folder: 'Demo: Grafana Features'
      interval: 1m
      rules:
        - uid: FEXxVXN7k
          title: Multi series alerting
          condition: B
          data:
            - refId: A
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: "000000001"
              model:
                refId: A
                target: aliasByNode(scaleToSeconds(statsd.fakesite.counters.session_start.*.count, 1), 4)
            - refId: B
              datasourceUid: "-100"
              model:
                conditions:
                    - evaluator:
                        params:
                            - 2
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - A
                      reducer:
                        type: avg
                refId: B
                type: classic_conditions
          dashboardUid: 4QfoqzGZk
          panelId: 2
          noDataState: NoData
          execErrState: Alerting
          for: 1m
          annotations:
            __alertId__: "29"
            __dashboardUid__: 4QfoqzGZk
            __panelId__: "2"
            description: ""
            message: ""
            runbook_url: ""
            summary: ""
          labels:
            "": ""
            alertname: Multi series alerting
            rule_uid: FEXxVXN7k
          isPaused: false

```
 

### What did you expect to happen?

I expect the `-orgId` and its attribute to be indented to level 2, not 4.

Like

```yaml
apiVersion: 1
groups:
  - orgId: 1
    name: Multi series alerting
    folder: 'Demo: Grafana Features'
    interval: 1m
    rules:
      - uid: FEXxVXN7k
        title: Multi series alerting
        condition: B
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: '000000001'
            model:
              refId: A
              target: >-
                aliasByNode(scaleToSeconds(statsd.fakesite.counters.session_start.*.count,
                1), 4)
          - refId: B
            datasourceUid: '-100'
            model:
              conditions:
                - evaluator:
                    params:
                      - 2
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - A
                  reducer:
                    type: avg
              refId: B
              type: classic_conditions
        dashboardUid: 4QfoqzGZk
        panelId: 2
        noDataState: NoData
        execErrState: Alerting
        for: 1m
        annotations:
          __alertId__: '29'
          __dashboardUid__: 4QfoqzGZk
          __panelId__: '2'
          description: ''
          message: ''
          runbook_url: ''
          summary: ''
        labels:
          '': ''
          alertname: Multi series alerting
          rule_uid: FEXxVXN7k
        isPaused: false

```

### Did this work before?

I don't know. 

But it is annoying when we are pasting the alert into our IAC since we manually need to format the indentation of the content

### How do we reproduce it?

See "what happened"

I noticed during work that we run Grafana in k8s. I can update the bug report later with the exact version but it is reproducible in the playground. 

### Is the bug inside a dashboard panel?

Nah.

### Environment (with versions)?

Grafana: Grafana v11.1.0-69051 (9d44c8e8cf) (playground and earlier versions as well)
OS: Mac Os
Browser: Chrome but also tested on Firefox

### Grafana platform?

Kubernetes

### Datasource(s)?

Promethues
