### ISSUE TITLE
Alerting: deleting provisioned alert rules not working

### ISSUE THREAD

**Issue by danfinn** [grafana/grafana#86631]
### What happened?

First off I'd like to say that I think this workflow is terrible.  We try to use a gitops workflow and provision everything from file.  This works well however removing them is quite painful at the moment.  If I want to remove something I have to submit a PR to remove it from where it was being provisioned and then I also have to submit another PR to implicitly tell grafana to delete the removed resources.

I needed to remove several datasources and the alerts associated with them.  I created this yaml file in our config to do this:

```
 apiVersion: 1

 deleteDatasources:
   - name: prod2-cust-eastus-logs
     orgId: 1
   - name: prod2-cust-eastus-metrics
     orgId: 1
   - name: prod2-cust-eastus-prometheus
     orgId: 1

 deleteRules:
   - orgId: 1
     uid: ef60c84f-edb7-4342-8465-ac9fbd75d686
   - orgId: 1
     uid: f441ef0c-38f6-45b7-9e1a-9ac68fcd5eb4
   - orgId: 1
     uid: dfc0c295-c074-4ceb-9798-46149aa8f0cc
   - orgId: 1
     uid: e5e0d1f5-5bee-4c3d-998d-22605b5888f1
   - orgId: 1
     uid: a42f16f9-4f82-48fa-8486-421ac3e8aa35
   - orgId: 1
     uid: d1c99fe6-6c9e-4c94-a24a-3c3372b9f03b
   - orgId: 1
     uid: a899da20-bf9e-4076-909b-e25c803a3d0c
   - orgId: 1
     uid: fbc64a41-2ebf-423c-ac2a-6ff07373a884
```

The datasources were removed however the alerts still exist.  I see no errors in the logs about failures related to this, I do see several lines in the logs that I assume are related to this and looks like so:

```
logger=provisioning t=2024-04-19T19:01:14.012360643Z level=info msg="Deleted old alert_configuration(s)" org=1 limit=100 delete_count=1
```

however in the grafana UI I still see these alerts, they have not been removed.  Is there something else I need to do to remove them?

### What did you expect to happen?

to be able to remove alerts that were provisioned from file without multiple PRs and/or significant amounts of effort

### Did this work before?

unsure

### How do we reproduce it?

1. provision alert from file
2. try to remove that alert
3.

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 10.2.3
OS:
Browser: chrome

### Grafana platform?

Kubernetes
