### ISSUE TITLE
Alert rule > Threshold expression > Custom recovery threshold > "stop alerting when" condition does not work

### ISSUE THREAD

**Issue by cristina-defran** [grafana/grafana#87226]
### What happened?

I have an alert rule configured via file provisioning to fire whenever the RAM usage percentage is over 80%. I also set the "stop alerting when" (as seen in the UI, or "unloadEvaluator" as seen in the .yml provisioning file) to when the value is below 75% to avoid flapping. The alert fires whenever it's over 80%, but it resolves if it falls below 80% (making it flap a lot), so the "stop alerting when" condition is not working.

I have this rule definition in my alert group provisioning file:
```
- uid: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  title: RAM usage over 80%
  condition: C
  data:
	- refId: A
	  relativeTimeRange:
		from: 600
		to: 0
	  datasourceUid: XXXXXXXXXXXXXXXXX
	  model:
		disableTextWrap: false
		editorMode: builder
		expr: memory_percent{memory="used"}
		fullMetaSearch: false
		includeNullMetadata: true
		instant: false
		intervalMs: 60000
		legendFormat: __auto
		maxDataPoints: 43200
		range: true
		refId: A
		useBackend: false
	- refId: B
	  relativeTimeRange:
		from: 600
		to: 0
	  datasourceUid: __expr__
	  model:
		conditions:
			- evaluator:
				params: []
				type: gt
			  operator:
				type: and
			  query:
				params:
					- B
			  reducer:
				params: []
				type: last
			  type: query
		datasource:
			type: __expr__
			uid: __expr__
		expression: A
		intervalMs: 1000
		maxDataPoints: 43200
		reducer: mean
		refId: B
		type: reduce
	- refId: C
	  relativeTimeRange:
		from: 600
		to: 0
	  datasourceUid: __expr__
	  model:
		conditions:
			- evaluator:
				params:
					- 80
				type: gt
			  operator:
				type: and
			  query:
				params:
					- C
			  reducer:
				params: []
				type: last
			  type: query
			  unloadEvaluator:
				params:
				  - 75
				type: lt
		datasource:
			type: __expr__
			uid: __expr__
		expression: B
		intervalMs: 1000
		maxDataPoints: 43200
		refId: C
		type: threshold
  dashboardUid: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  panelId: xx
  noDataState: NoData
  execErrState: Error
  for: 5m
  annotations:
	__dashboardUid__: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
	__panelId__: "13"
	summary: RAM usage is at {{ index $values "B" }}%.
  labels:
	alert_type: vm
  isPaused: false
```

The UI shows the alert rule is correctly provisioned:

![image](https://github.com/grafana/grafana/assets/36203653/77d6d42a-6938-4fb8-a28a-a025f49cd8fe)

In the dashboard, you can see how the alerts fire and resolve taken the 80% threshold as the only condition:
![image](https://github.com/grafana/grafana/assets/36203653/538eae58-31ff-4a2c-9916-c64590c646e9)

### What did you expect to happen?

I would expect the alert to not resolve until the value is under 75%.

### Did this work before?

Not sure.

### How do we reproduce it?

1. Provision from a file the alert group with the "unloadEvaluator" field (Custom recovery threshold).
2. Force value over 80%. Alert should fire.
3. Force value under 80%, but over 75%. Alert will resolve, when it shouldn't.

### Environment (with versions)?

Grafana: v10.4.2 (701c851be7)
OS: `grafana/grafana-oss` docker image (679e4be9f918) running on a Ubuntu 22.04 host
Browser: Chrome

### Grafana platform?

Docker
