### ISSUE TITLE
Grafana - could not resolve dashboards:uid:XxxXXX99x: Dashboard not found

### ISSUE THREAD

**Issue by AllezWiggo** [grafana/grafana#87342]
### What happened?

Grafana fails to load a dashboard defined in a configmap.
The sidecar is able to load the json to a /tmp folder:
{"time": "2024-05-03T15:13:40.748693+00:00", "taskName": null, "msg": "Writing /tmp/dashboards/OpsDashboards/ops-dashboard.json (ascii)", "level": "INFO"}
The json can be seen in the said location in the pod as well.
But Grafana container throws following error:
logger=provisioning.dashboard type=file name=sidecarProvider t=2024-05-03T16:49:28.773411742Z level=error msg="failed to save dashboard" file=/tmp/dashboards/OpsDashboards/ops-dashboard.json error="could not resolve dashboards:uid:XxxXXX99x: Dashboard not found"

This happens only for one dashboard json, other dashboards are loaded fine. The dashboard json hasn't changed recently and this used to work before.

### What did you expect to happen?

Expected behaviour is the dashboard should get provisioned successfully.

### Did this work before?

Yes, the dashboard used to get provisioned successfully before.

### How do we reproduce it?

1. Load the dashboard json in a configmap and use proper annotations.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: "grafana-ops-dashboard"
  labels:
    grafana_dashboard: "1"
  annotations:
    grafana_dashboard_folder: "OpsDashboards"
data:
 ops-dashboard.json: |
...
```
2. Wait for sidecar to load the dashboard.
3. Errors can be seen in grafana logs

### Environment (with versions)?

Grafana: v10.2.2
OS: Linux (Kubernetes v1.27.7)
Browser: Chrome Version 124.0.6367.79 (Official Build) (x86_64)

### Grafana platform?

Kubernetes

### Datasource(s)?

Prometheus
