### ISSUE TITLE
Tempo trace query is recursively shifting the time on every new trace search

### ISSUE THREAD

**Issue by AlissonRS** [grafana/grafana#87608]
**Describe the bug**
When searching for traces, you click on a trace from the list, a right panel appears to query by trace id.

If `traceQuery.timeShiftEnabled` is enabled, it shifts the time range by subtracting time from the `range.from` and adding to `range.to` based on the `spanStartTimeShift` and `spanEndTimeShift`. However, on Grafana UI, the original calendar component (from the trace list search on the left side panel) also gets shifted. So every new trace keeps shifting the time recursively.

**To Reproduce**

1. Provision Tempo datasource on Grafana using the configuration below taken from [Grafana Docs](https://grafana.com/docs/grafana/latest/datasources/tempo/configure-tempo-data-source/)
```
  apiVersion: 1
  
  datasources:
    - name: Tempo
      type: tempo
      uid: EbPG8fYoz
      url: http://localhost:3200
      access: proxy
      basicAuth: false
      jsonData:
        tracesToLogsV2:
          # Field with an internal link pointing to a logs data source in Grafana.
          # datasourceUid value must match the uid value of the logs data source.
          datasourceUid: 'loki'
          spanStartTimeShift: '1h'
          spanEndTimeShift: '-1h'
          tags: ['job', 'instance', 'pod', 'namespace']
          filterByTraceID: false
          filterBySpanID: false
          customQuery: true
          query: 'method="${__span.tags.method}"'
        tracesToMetrics:
          datasourceUid: 'prom'
          spanStartTimeShift: '1h'
          spanEndTimeShift: '-1h'
          tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
          queries:
            - name: 'Sample query'
              query: 'sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[5m]))'
        tracesToProfiles:
          datasourceUid: 'grafana-pyroscope-datasource'
          tags: ['job', 'instance', 'pod', 'namespace']
          profileTypeId: 'process_cpu:cpu:nanoseconds:cpu:nanoseconds'
          customQuery: true
          query: 'method="${__span.tags.method}"'
        serviceMap:
          datasourceUid: 'prometheus'
        nodeGraph:
          enabled: true
        search:
          hide: false
        lokiSearch:
          datasourceUid: 'loki'
        traceQuery:
          timeShiftEnabled: true
          spanStartTimeShift: '1h'
          spanEndTimeShift: '-1h'
        spanBar:
          type: 'Tag'
          tag: 'http.path'
```
2. Open to Tempo datasource on Grafana Explorer, search for some traces (e.g. last 15 minutes).
![image](https://github.com/grafana/tempo/assets/4753901/8c619edb-56cc-4a8a-aa88-f9817a881327)

3. Click on a trace, the time range on the calendar component will be decreased by one hour on "from" and "to", because the `spanStartTimeShift` is "1h" and it gets subtracted, and `spanEndTimeShift` is "-1h" so it adds -1h, essentially subtracting too (in my screenshot, my `spanEndTimeShift` is "1h" not "-1h", so it's indeed adding 1h to the end instead of subtracting).
![image](https://github.com/grafana/tempo/assets/4753901/07c368f1-56d0-4dfd-9ca5-38bfe03d2c37)

4. Click another trace from the left panel, the time range should go down by another hour.
![image](https://github.com/grafana/tempo/assets/4753901/a310945d-7535-48d8-b34c-83e13b66b0ed)

5. Keep clicking different traces and notice the calendar time being shifted every time.
![image](https://github.com/grafana/tempo/assets/4753901/6144cb4d-7361-4ec5-bae0-c39bd5f84dba)

**Expected behavior**
The time shift should happen based on the original time range used for querying, shifting shouldn't be recursive.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Additional Context**
I can share some screenshots if needed.
