### ISSUE TITLE
grafana.init: is not handling ssl_mode when database is postgres

### ISSUE THREAD

**Issue by dverzolla** [grafana/grafana#87874]
### What happened?

I'm configuring grafana helm chart and added the config below. Grafana should consider to set `ssl_mode` when using `postgres`, that's not happening.

```yaml
  grafana.ini:
    database:
      type: postgres
      host: host:5432
      name: grafana
      user: grafana
      password: xxx
      ssl_model: require
```

Maybe there is something related with:
https://github.com/grafana/grafana/blob/7d386dc26becc73fff2296b076d21842a4f890de/pkg/services/store/entity/db/dbimpl/dbEngine.go#L48
https://github.com/grafana/grafana/blob/14a814a280d0b8b3fa0bcc57a1dc7ee62c6e0b36/pkg/services/sqlstore/database_config.go#L145

If I set the env var `GF_DATABASE_SSL_MODE`, grafana works as expected.

### What did you expect to happen?

Grafana parses the `ssl_mode` and set into postgres sql connection.

### Did this work before?

Is the first time I am configuring it.

### How do we reproduce it?

Install using helm chart and configure `ssl_mode`.
I am using aws rds postgres v16.

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Helm Chart 58.5.2:

### Grafana platform?

Kubernetes
