### ISSUE TITLE
Grafana UI Error info：Failed to fetch

### ISSUE THREAD

**Issue by qianghong000** [grafana/grafana#88290]
### When I use the ingress nginx proxy，The following error messages frequently appear on the front page：
![image](https://github.com/grafana/grafana/assets/9443696/ea5104b1-eb2d-4614-b1a9-27cfea40335a)

### Check the Grafana logs as follows:
logger=grafana-apiserver t=2024-05-24T12:12:05.747149272Z level=info msg="failed to read in-cluster kubeconfig for delegated authentication: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory"
logger=grafana-apiserver t=2024-05-24T12:12:05.751992015Z level=info msg="Adding GroupVersion playlist.grafana.app v0alpha1 to ResourceManager"
logger=grafana-apiserver t=2024-05-24T12:12:05.752371223Z level=info msg="Adding GroupVersion featuretoggle.grafana.app v0alpha1 to ResourceManager"
logger=plugins.update.checker t=2024-05-24T12:12:06.239725807Z level=info msg="Update check succeeded" duration=742.666434ms
logger=grafana.update.checker t=2024-05-24T12:12:06.262322992Z level=info msg="Update check succeeded" duration=765.253028ms
logger=context userId=0 orgId=0 uname= t=2024-05-24T12:12:07.546814282Z level=info msg="Request Completed" method=GET path=/api/live/ws status=401 remote_addr=113.208.117.34 time_ms=1 duration=1.692055ms size=105 referer= handler=/api/live/ws status_source=server
logger=context userId=1 orgId=2 uname=admin t=2024-05-24T12:12:09.541454851Z level=info msg="Request Completed" method=GET path=/api/live/ws status=-1 remote_addr=113.208.117.34 time_ms=6 duration=6.136714ms size=0 referer= handler=/api/live/ws status_source=server

### The Ingress nginx proxy configuration is as follows:
```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-grafana
  namespace: monitoring
spec:
  ingressClassName: nginx-ingress
  rules:
    - host: grafana.beeselect.net
      http:
        paths:
        - backend:
            service:
              name: grafana
              port:
                number: 3000
          path: /
          pathType: ImplementationSpecific
```

### What did you expect to happen?

The Grafana UI error message disappears

### Did this work before?

It is all fine to access directly using the ip:port

### How do we reproduce it?

1. Added Ingress Nginx proxy
2.  Use prometheus-operator to complete the deployment：https://github.com/prometheus-operator/kube-prometheus?tab=readme-ov-file 

### Environment (with versions)?

Grafana: 11.0.0
OS: Alpine Linux
Browser: google

### Grafana platform?

Kubernetes

### Datasource(s)?

MySQL 5.7.38
