### ISSUE TITLE
Alerting: External Alertmanager stuck in pending

### ISSUE THREAD

**Issue by Brice187** [grafana/grafana#88366]
### What happened?

**Alerting > Admin**

![image](https://github.com/grafana/grafana/assets/2021699/6ac71484-08a9-45d5-9837-e5939a059ed3)

Provisioned External Alertmanager is stuck in status pending forever

When I select **Send alerts to** (**Only External** or **both internal and external** it eventually becomes available

![image](https://github.com/grafana/grafana/assets/2021699/2b400112-f094-4717-ac37-70b84faa968c)

Loglines after selecting one of the mentioned options:

```
logger=ngalert.sender.router t=2024-05-28T08:49:10.483249403Z level=info msg="Creating new sender for the external alertmanagers" org=1 alertmanagers=[https://alertmanager.iznet]                                                │
logger=ngalert.sender.external-alertmanager org=1 cfg=1 t=2024-05-28T08:49:10.483455446Z level=info msg="Synchronizing config with external Alertmanager group"                                                                   │
logger=ngalert.sender.external-alertmanager t=2024-05-28T08:49:10.483458866Z level=info msg="Initiating communication with a group of external Alertmanagers"  
...
logger=ngalert.sender.router rule_uid=bdn1xyt2de0owe org_id=1 t=2024-05-28T08:50:10.211275365Z level=info msg="Sending alerts to local notifier" count=1                                                                          │
logger=ngalert.sender.router rule_uid=bdn1xyt2de0owe org_id=1 t=2024-05-28T08:50:10.211336568Z level=info msg="Sending alerts to external notifier" count=1 
```

### What did you expect to happen?

Grafana (10.4.1) is provisioned in Kubernetes with helmchart 7.3.11

Because the mentioned behaviour is not idempotent, I have to manually activate the external alertmanager.

### Did this work before?

N/A

### How do we reproduce it?

1. Provision an external alertmanager like this:

values.yaml
```
...
datasources:
  alertmanager.yaml:
    apiVersion: 1
    datasources:
      - name: Alertmanager Example
        type: alertmanager
        uid: alertmanager-example
        access: proxy
        url: https://alertmanager.example.com
        jsonData:
          implementation: prometheus
          handleGrafanaManagedAlerts: true
```
2. Check in Grafana **Alerting > Admin** if the Connection becomes available without manipulating the settings manually

### Environment (with versions)?

Grafana: 10.4.1
OS: Debian 12 / Kubernetes v1.30.1
Browser: Firefox 126

### Grafana platform?

Kubernetes

### Datasource(s)?

Alertmanager
