### ISSUE TITLE
K8s Pod: remote error: tls: handshake failure

### ISSUE THREAD

**Issue by sheldygg** [grafana/grafana#88958]
### What happened?

I try install clickhouse datasource plugin to my grafana in k8s.
Grafana was installed by Helm with this values
<details>
  <summary>Values</summary>

  ```yaml
  image:
  # -- The Docker registry
  registry: docker.io
  # -- Docker image repository
  repository: grafana/grafana
  # Overrides the Grafana image tag whose default is the chart appVersion
  tag: "latest"
  sha: ""
  pullPolicy: IfNotPresent

  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ## Can be templated.
  ##
  pullSecrets: []
  #   - myRegistrKeySecretName

persistence:
  type: pvc
  enabled: true
  # storageClassName: default
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  # annotations: {}
  finalizers:
    - kubernetes.io/pvc-protection
  # selectorLabels: {}
  ## Sub-directory of the PV to mount. Can be templated.
  # subPath: ""
  ## Name of an existing PVC. Can be templated.
  # existingClaim:
  ## Extra labels to apply to a PVC.
  extraPvcLabels: {}

  ## If persistence is not enabled, this allows to mount the
  ## local storage in-memory to improve performance
  ##
  inMemory:
    enabled: false
    ## The maximum usage on memory medium EmptyDir would be
    ## the minimum value between the SizeLimit specified
    ## here and the sum of memory limits of all containers in a pod
    ##
    # sizeLimit: 300Mi 
  ```
</details>

Grafana successfully installed and I can login.
Then I add plugin `grafana-clickhouse-datasource` to values like this
```yaml
plugins:
  - grafana-clickhouse-datasource 
```

And my pod take down with this log
`Error: ✗ Get "https://grafana.com/api/plugins/grafana-clickhouse-datasource/versions": remote error: tls: handshake failure`

### What did you expect to happen?

I except what plugin will be successfuly installed and I can add clickhouse datasource.

### Did this work before?

I don't know, never try before.

### How do we reproduce it?

1. Create file with values for Helm https://pastebin.com/p1UbPTQ5
2. Install release with this command `helm install grafana grafana/grafana --values values.yaml -n test-grafana`
3. See what your pod is not running `k get pods -n test-grafana`

### Grafana platform?

Kubernetes
