### ISSUE TITLE
Grafana HA ERROR:  duplicate key value violates unique constraint "UQE_user_login" DETAIL:  Key (login)=(user.email@domain.com) already exists when using Grafana with Postgres HA

### ISSUE THREAD

**Issue by aturcott** [grafana/grafana#89225]
### What happened?

After signing in using SSO with Azure AD, we are getting an "Unauthorized" error on the UI which immediately signs us out. We are also unable to sign in with the admin creds which provides no error message at all. We don't see any errors in the Grafana pod logs but looking at the postgresql logs we saw this error:
```
STATEMENT:  INSERT INTO cache_data (cache_key,data,created_at,expires) VALUES($1,$2,$3,$4)
ERROR:  duplicate key value violates unique constraint "UQE_user_login"
DETAIL:  Key (login)=(user.email@domain.com) already exists.
```
We have had no issues with this in the past and other Grafana instances running on other AKS clusters are using the same setup and have no issue (for now). In the screen recording below you can see the first login attempt as admin failed (yes the password was correct) and the second attempt was successful but I received that "Unauthorized" error and was forcefully logged out.

https://github.com/grafana/grafana/assets/73724286/49175622-6958-40fc-942a-50a45092b728

Here is our Grafana auth config used by every Grafana instance

```yaml
grafana.ini:
    auth:
      oauth_allow_insecure_email_lookup: true
    users:
      viewers_can_edit: true
    auth.azuread:
      name: Azure AD
      enabled: true
      allow_sign_up: true
      auto_login: false
      client_id: ${AZURE_CLIENT_ID}
      client_secret: ${AZURE_CLIENT_SECRET}
      scopes: openid email profile offline_access
      auth_url: https://login.microsoftonline.com/${AZURE_TENANT_ID}/oauth2/v2.0/authorize
      token_url: https://login.microsoftonline.com/${AZURE_TENANT_ID}/oauth2/v2.0/token
      allowed_organizations: ${AZURE_TENANT_ID}
      role_attribute_strict: false
      allow_assign_grafana_admin: false
      skip_org_role_sync: false
      use_pkce: false
```

and our config for this particular isntance
```yaml
grafana:
  replicas: 2
  persistence:
    enabled: false
  grafana.ini:
    server:
      domain: DOMAIN_URL
      root_url: ROOT_URL
    database:
      type: postgres
      host: obs-postgresql-pgpool:5432
      name: grafana
      user: grafana
      password: ${PGPASSWORD}
    unified_alerting:
      ha_redis_address: obs-redis-ha-haproxy:6379
    live:
      ha_engine: redis
      ha_engine_address: obs-redis-ha-haproxy:6379
  envValueFrom:
    PGPASSWORD:
      secretKeyRef:
        name: obs-postgres-credentials
        key: password    
  sidecar:
    datasources:
      alertmanager:
        handleGrafanaManagedAlerts: true
```

and config for Postgres HA
```yaml
persistence:
  enabled: true

postgresql:
  existingSecret: obs-postgres-credentials
  extraVolumeMounts:
    - name: obs-postgres-credentials
      mountPath: "/mnt/secrets-store"
      readOnly: true
  extraVolumes:
    - name: obs-postgres-credentials
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "obs-postgres-credentials"

pgpool:
  image:
    debug: true
  existingSecret: obs-pgpool-credentials
  extraVolumeMounts:
    - name: obs-postgres-credentials
      mountPath: "/mnt/secrets-store"
      readOnly: true
  extraVolumes:
    - name: obs-postgres-credentials
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "obs-postgres-credentials"
```

### What did you expect to happen?

All users, new and existing, should be able to login and stay logged in using SSO with Azure AD. We should also at least be able to sign in with the admin creds.

### Did this work before?

Yes this worked before, we are using v10.4.0 and this has worked on v10.4.0

### How do we reproduce it?

1. Enable SSO with Azure AD, or maybe even SSO with a different provider
2. Enable Grafana HA using Postgres HA
3. Try to sign in with SSO or admin creds

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: v10.4.0
OS: Ubuntu 22.04
Browser: Chrome

### Grafana platform?

Kubernetes
