### ISSUE TITLE
Plugins not visible from dashboard

### ISSUE THREAD

**Issue by P4r4n01dB34r** [grafana/grafana#89261]
### What happened?

Plugins are not visuble or searchable from the dashboard itself, From the logs the errora are:
msg="Failed to get plugins" error="BasicAuth content is invalid."
msg="Failed to get provisioned plugins" error="BasicAuth content is invalid."

### What did you expect to happen?

Be able to browse new adn installed plugins

### Did this work before?

Previous 11

### How do we reproduce it?

1. Have basic auth enabled
2. Update grafana to 11 version

### Environment (with versions)?

Grafana: 11
OS: Debian GNU/Linux 12 (bookworm)
Browser: Mozilla Firefox

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by tsrats** [comment]
I am seeing the same errors on version 11 and 11.1

**Comment by tolzhabayev** [comment]
Could you provide us with how your provisioning yaml files look like? (please remove any sensitive information before adding them)

**Comment by tsrats** [comment]
I am running Grafana in Kubernetes, and have the following mounted via config map:
```
grafana-754b55bc69-xwg4v:/usr/share/grafana# cat /etc/grafana/provisioning/datasources/cloud.yaml
apiVersion: 1
datasources:
    - name: grafanacloud-prom
      type: prometheus
      access: ""
      url: https://prometheus-us-central1.grafana.net/api/prom
      uid: grafanacloud-prom
      basicAuth: true
      basicAuthUser: <removed>
      jsonData:
        exemplarTraceIdDestinations:
            - datasourceUid: grafanacloud-traces
              name: traceId
      secureJsonData:
        basicAuthPassword: <removed>
    - name: grafanacloud-logs
      type: loki
      access: ""
      url: https://logs-prod-us-central1.grafana.net
      uid: grafanacloud-logs
      basicAuth: true
      basicAuthUser: <removed>
      jsonData:
        derivedFields:
            - datasourceUid: grafanacloud-logs
              matcherRegex: traceID=(\w+)
              name: traceID
              url: ${__value.raw}
      secureJsonData:
        basicAuthPassword: <removed>
    - name: grafanacloud-traces
      type: tempo
      access: ""
      url: https://tempo-us-central1.grafana.net/tempo
      uid: grafanacloud-traces
      basicAuth: true
      basicAuthUser: <removed>
      jsonData:
        tracesToLogs:
            datasourceUid: grafanacloud-logs
      secureJsonData:
        basicAuthPassword: <removed>
    - name: grafanacloud-graphite
      type: graphite
      access: ""
      url: https://graphite-blocks-prod-us-central1.grafana.net/graphite
      uid: grafanacloud-graphite
      basicAuth: true
      basicAuthUser: <removed>
      secureJsonData:
        basicAuthPassword: <removed>
```

There is nothing in my provisioning file for plugins:
```
grafana-754b55bc69-xwg4v:/usr/share/grafana# cat /etc/grafana/provisioning/plugins/cloud.yaml 
grafana-754b55bc69-xwg4v:/usr/share/grafana#
```
