### ISSUE TITLE
Datasource provisioning via yaml and directory not executing env variable substitution correctly

### ISSUE THREAD

**Issue by shiang-luong** [grafana/grafana#89519]
### What happened?

Currently dropping an datasource.yml file into /etc/grafana/provisioning works in creating the data sources.  When using environment variable substitution (based on this doc: https://grafana.com/docs/grafana/latest/administration/provisioning/#using-environment-variables), seems like the substitution isn't working and I am ending up with blank instead of the actual value.

example:
apiVersion: 1
datasources:
  - name: 'dev_json_api'
    type: 'marcusolsson-json-datasource'
    url: 'https://dev.com'
    access: 'proxy'
    org_id: 1
    uid: 'devjsonapi'
    is_default" false
    version: 2
    editable: true
    jsonData:
       tlsSkipVerify: true
       queryParams: 'module=API&key=${DEV_APIKEY}'

what I would see in the datasource config would be:
module=API&key=

### What did you expect to happen?

I expect the environment value to be set instead of blank.  
The example should end up being:
'module=API&key=thedevkey

### Did this work before?

based on documentation yes, but I am not sure it was working via file drop to the provisioning folder

### How do we reproduce it?

I am deploy grafana via k8s.
1. Configure an environment variable in the Dockerfile or via configmap
2. Drop an datasource.yml file (containing environment variable created in step 1 to substitute) in /etc/grafana/provisioning
3. Deploy grafana
4. Check the datasource to see that it was created, but the expected values are not correct
5. Can double check env variables exists and have correct values

### Environment (with versions)?

Grafana: 10.4.2
OS: linux
Browser: firefox

### Grafana platform?

Kubernetes

**Comment by filewalkwithme** [comment]
Hi, I was unable to reproduce the issue, both on `10.4.2` and `main`

I used the following file for provisioning:

```
# Configuration file version
apiVersion: 1

# # List of data sources to insert/update depending on what's
# # available in the database.
datasources:
  - name: 'dev_json_api'
    orgId: 1
    type: 'marcusolsson-json-datasource'
    url: 'https://dev.com'
    access: 'proxy'
    org_id: 1
    uid: 'devjsonapi'
    is_default: false
    version: 2
    editable: true
    jsonData:
      tlsSkipVerify: true
      queryParams: 
        'module=API&key=${DEV_APIKEY}'
```

Then I have set `export DEV_APIKEY=foo` and then `make run`

This is what I got on the datasource page (on both `10.4.2` and  `main`):

![image](https://github.com/user-attachments/assets/424a60e2-57f6-4ed2-81a5-e0c3a6583377)

@shiang-luong could you confirm you are still getting the error on newer Grafana versions? Also, I wonder if there are any special characters on the `DEV_APIKEY` environment variable.
