### ISSUE TITLE
Elastic Search provisioning is not working with `unsupported interval`

### ISSUE THREAD

**Issue by Juoper** [grafana/grafana#90166]
### What happened?

When trying to use the provisioned Elasticsearch datasource, we get this error for the test button:
Cannot read properties of undefined (reading 'startOf')
and this log is printed to the console:
`logger=tsdb.elasticsearch endpoint=callResource pluginId=elasticsearch dsName="Elasticsearch Test2" dsUID=mmos-elastic-datasource uname=admin t=2024-07-07T22:31:46.279242052Z level=info msg="Response received from Elasticsearch" statusCode=200 status=ok duration=11.611333ms stage=databaseRequest contentLength=326 resourcePath=
`

when trying to execute a query we get this error:
An error occurred within the plugin
and in the console:
`level=error msg="Internal server error" error="[plugin.downstreamError] client: failed to query data: unsupported interval '10s'" `

When creating the datasource manually it's working fine

### What did you expect to happen?

To execute the query on the elastic server

### Did this work before?

No

### How do we reproduce it?

1.create a grafana deployment with those cofnig maps:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: default
data:
  grafana-datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        uid: mmos-prometheus-datasource
        url: http://mmos-prometheus-entrypoint.default.svc.cluster.local:9090
        jsonData:
          timeInterval: 5s
      - name: Elasticsearch tst
        type: elasticsearch
        access: proxy
        uid: mmos-elastic-datasource
        url: http://quickstart-es-http.default.svc.cluster.local:9200
        isDefault: true
        basicAuth: true
        basicAuthUser: elastic
        secureJsonData:
          basicAuthPassword: "${ELASTIC_LOGGING_PASSWORD}"
          tlsSkipVerify: true
        jsonData:
          esVersion: 8
          timeField: "@timestamp"
          maxConcurrentShardRequests: 5
          interval: "10s"
          logMessageField: "_index:mmos-logs*"
          xpackEnabled: true
```

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    mmos: grafana
  name: grafana
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      mmos: grafana
  template:
    metadata:
      labels:
        mmos: grafana
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      initContainers:
        - name: init-git
          image: alpine:latest
          command:
            - sh
            - -c
            - |
              apk add --no-cache git jq 
              echo $DOCKER_CONFIG_JSON
              GITLAB_SERVER_WITH_PORT=$(echo "$DOCKER_CONFIG_JSON" | jq -r '.auths | keys[0]')
              GITLAB_SERVER=$(echo "$GITLAB_SERVER_WITH_PORT" | sed 's/:5050//')
              USERNAME=$(echo "$DOCKER_CONFIG_JSON" | jq -r --arg GITLAB_SERVER_WITH_PORT "$GITLAB_SERVER_WITH_PORT" '.auths[$GITLAB_SERVER_WITH_PORT].username')
              PASSWORD=$(echo "$DOCKER_CONFIG_JSON" | jq -r --arg GITLAB_SERVER_WITH_PORT "$GITLAB_SERVER_WITH_PORT" '.auths[$GITLAB_SERVER_WITH_PORT].password')
              echo "https://${USERNAME}:${PASSWORD}@${GITLAB_SERVER}"
              echo "https://${USERNAME}:${PASSWORD}@${GITLAB_SERVER}" > /root/.git-credentials
              git config --global credential.helper 'store --file=/root/.git-credentials'
              git clone https://${GITLAB_SERVER}/sssw/mmos/mmos-grafana-dashboards.git /tmp/repo
              cp -r /tmp/repo/dashboards /etc/grafana/provisioning/dashboards
          env:
            - name: DOCKER_CONFIG_JSON
              valueFrom:
                secretKeyRef:
                  name: gitlab-registry
                  key: .dockerconfigjson
          volumeMounts:
            - name: grafana-dashboard
              mountPath: /etc/grafana/provisioning/dashboards
      containers:
        - name: grafana
          image: grafana/grafana:10.2.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http-grafana
              protocol: TCP
          env:
            - name: ELASTIC_LOGGING_USER
              value: elastic
            - name: ELASTIC_LOGGING_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: quickstart-es-elastic-user
                  key: elastic
            - name: GF_SERVER_ROOT_URL
              valueFrom:
                secretKeyRef:
                  name: grafana-smtp-secret
                  key: grafana_url
            - name: GF_SERVER_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: grafana-smtp-secret
                  key: grafana_domain
          #          env:
          #            - name: GF_SMTP_ENABLED
          #              value: "true"
          #            - name: GF_SMTP_HOST
          #              valueFrom:
          #                secretKeyRef:
          #                  name: grafana-smtp-secret
          #                  key: host
          #            - name: GF_SMTP_USER
          #              valueFrom:
          #                secretKeyRef:
          #                  name: grafana-smtp-secret
          #                  key: username
          #            - name: GF_SMTP_PASSWORD
          #              valueFrom:
          #                secretKeyRef:
          #                  name: grafana-smtp-secret
          #                  key: password
          #            - name: GF_SMTP_FROM_ADDRESS
          #              valueFrom:
          #                secretKeyRef:
          #                  name: grafana-smtp-secret
          #                  key: address
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-storage
            - mountPath: /etc/grafana/provisioning/datasources
              name: grafana-datasources
              readOnly: false
            - mountPath: /var/lib/grafana/dashboards
              name: grafana-dashboard
              readOnly: false
            - mountPath: /etc/grafana/provisioning/dashboards
              name: grafana-dashboard-definition
#            - mountPath: /etc/grafana/provisioning/alerting
#              name: alerting-config
#              subPath: alerting.yaml
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-pv-claim2
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
            items:
              - key: grafana-datasources.yaml
                path: grafana-datasources.yaml
        - name: grafana-dashboard
          emptyDir: {}
        - name: grafana-dashboard-definition
          configMap:
            defaultMode: 420
            name: grafana-dashboardsdef
#        - name: alerting-config
#          configMap:
#            name: grafana-provisioning
#            items:
#              - key: alerting.yaml
#                path: alerting.yaml

```
2.
3.

### Environment (with versions)?

Grafana:10.2.4
OS: Ubuntu 22.04 
Browser: Chrome

### Grafana platform?

Kubernetes

### Datasource(s)?

Elasticsearch  8.10.1
