### ISSUE TITLE
Dashboards: link to original dashboard not working when serving from sub_path

### ISSUE THREAD

**Issue by Blaimi** [grafana/grafana#90188]
### What happened?

I serve an instance of grafana in a sub_path behind a reverse-proxy

Creating local snapshots via the "share" button works fine, but when I click the "open original dashboard"-button, it redirects to the dashboard-url _without_ the `sub_path`-prefix. If grafana is also reachable via `/` it redirects to the correct URL, but not if the reverse-proxy only listens on `/<sub_path>`.

Another related "bug": The current and the target URL gets checked by the hostname. Because I can run multiple instances of grafana behind different `sub_path`s, e.g. in `/grafana-1` and `/grafana-2`, this check might not be enough.

### What did you expect to happen?

Clicking on the "open original dashboard"-button of local snapshots redirects to the dashboard, even when grafana is behind a reverse-proxy and a `sub_path` is given.

https://github.com/grafana/grafana/commit/b68fee86e57892784090ca99d23be495e190c8cf fixes the problem but is more an ugly workaround than a stable solution.

### Did this work before?

This was working before https://github.com/grafana/grafana/commit/239888f22983010576bb3a9135a7294e88c0c74a

#### compose.yaml
```yaml
version: '3.7'
services:
  grafana-1:
    image: grafana/grafana-oss
    container_name: grafana-1
    restart: "no"
    volumes:
      - ./grafana-1.ini:/etc/grafana/grafana.ini
      - grafana-1-volume:/var/lib/grafana
    expose:
      - 3000
    networks:
      - grafana_network
    environment:
      - GF_INSTALL_PLUGINS=grafana-testdata-datasource
  grafana-2:
    image: grafana/grafana-oss
    container_name: grafana-2
    restart: "no"
    volumes:
      - ./grafana-2.ini:/etc/grafana/grafana.ini
      - grafana-2-volume:/var/lib/grafana
    expose:
      - 3000
    networks:
      - grafana_network
    environment:
      - GF_INSTALL_PLUGINS=grafana-testdata-datasource
  traefik:
    image: traefik
    ports:
      - "8080:8080"
      - "80:80"
    restart: "no"
    networks:
      - grafana_network
    volumes:
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yaml
      - ./traefik/traefik.conf.d/:/etc/traefik/traefik.conf.d/

networks:
  grafana_network:
volumes:
  grafana-1-volume:
  grafana-2-volume:
```
#### traefik/traefik.yaml
```yaml
entryPoints:
  web:
    address: :80

log:
  level: DEBUG
api:
  insecure: true

accessLog: {}
providers:
  file:
    directory: /etc/traefik/traefik.conf.d/
    watch: true
```

#### traefik/traefik.conf.d/grafana.yaml
```yaml
http:
  routers:
    grafana-1:
      entryPoints:
        - web
      rule: PathPrefix(`/grafana-1`)
      service: grafana-1
    grafana-2:
      entryPoints:
        - web
      rule: PathPrefix(`/grafana-2`)
      service: grafana-2
  services:
    grafana-1:
      loadBalancer:
        servers:
          - url: http://grafana-1:3000
    grafana-2:
      loadBalancer:
        servers:
          - url: http://grafana-2:3000
```

#### grafana-1.ini
```ini
[server]
root_url = http://localhost/grafana-1/
serve_from_sub_path = true
```

#### grafana-2.ini
```ini
[server]
root_url = http://localhost/grafana-2/
serve_from_sub_path = true
```

### Environment (with versions)?

Grafana: docker latest
OS: ubuntu
Browser: firefox as well as chromium

### Grafana platform?

Docker
