### ISSUE TITLE
Grafana OSS: Google OAUTH2 now assigning users to Organizations

### ISSUE THREAD

**Issue by pragyasardana** [grafana/grafana#90343]
### What happened?

Due to requirements, we require all users who will log in to Grafana to be able to view all dashboards across all organizations. 

Values.yaml used:
```
serviceAccount:
  create: true
  name: grafana

rbac:
  namespaced: true

# Secret containing GF_AUTH_GOOGLE_CLIENT_ID and GF_AUTH_GOOGLE_CLIENT_SECRET
envFromSecret: "grafana-env-variables"

grafana.ini:
  server:
    domain: grafana.domain1.com
    root_url: "https://%(domain)s/"
    serve_from_sub_path: true
  users:
    viewers_can_edit: true
  log:
    mode: console
    level: debug
  unified_alerting:
    enabled: false
  alerting:
    enabled: false
  auth.ldap:
    enabled: false
  auth.basic:
    enabled: true
  auth.proxy:
    enabled: false
  auth.google:
    enabled: true
    scopes: "openid email profile https://www.googleapis.com/auth/cloud-identity.groups.readonly"
    auth_url: "https://accounts.google.com/o/oauth2/v2/auth"
    token_url: "https://oauth2.googleapis.com/token"
    api_url: "https://openidconnect.googleapis.com/v1/userinfo"
    use_pkce: true
    allowed_domains: "domain1.com domain2.com"
    allow_sign_up: true
    allow_assign_grafana_admin: true
    role_attribute_path: email=='some_super_user@domain1.com' && 'GrafanaAdmin' 
    skip_org_role_sync: false
    org_mapping: "team_leads@domain1.com:*:admin *:*:Viewer"
    org_attribute_path: groups
```

### What did you expect to happen?

* user `some_super_user@domain1.com` should be able to log in as Grafana Admin which works
* user `some_regular_user@domain1.com` should be able to log in and access the `Main Org` and the `Test Org` as a Viewer. In this case, the user is only able to access the `Main Org` as a Viewer
* user `some_team_lead@domain1.com` should be able to access the `Main Org` and `Test Org` as an Admin. In this case, the user is only a `Main Org` viewer.

### Did this work before?

No. 

### How do we reproduce it?

1. Install Grafana with the above values.yaml.
2. Log in to `grafana.domain1.com` using the admin user and create a `Test Org`
3. Log in as different users and test out the permissions

### Is the bug inside a dashboard panel?

N/A

### Environment (with versions)?

Environment details:
* deployment type: Kubernetes
* Helm Chart Version: 8.0.0
* Replicas: 1
* Grafana Version: 11.0.0

Note: this is a dev environment using SQL Lite Database. 

### Grafana platform?

Kubernetes

### Datasource(s)?

N/A
