### ISSUE TITLE
Feature lokiQuerySplitting causes Loki configuration max_query_bytes_read to work unexpectedly

### ISSUE THREAD

**Issue by kuburoman** [grafana/grafana#90542]
### What happened?

I would like to prevent users from running long queries that process too much data. Especially when they want to run this query over 10+ days. 

Based on Loki documentation max_query_bytes_read should do the trick but thanks to lokiQuerySplitting that limit is only compared with respect to one day and not whole selected range.

### What did you expect to happen?

Query to be blocked. 

Or if this is the expected behavior, a note in Loki documentation on how this is handled in the Grafana and information about lokiQuerySplitting.

### Did this work before?

It work when lokiQuerySplitting was set to false.

### How do we reproduce it?

1. Set max_query_bytes_read little bigger that one day.
2. Run query over multiple days.

### Environment (with versions)?

Grafana: 11.1.0

### Grafana platform?

Kubernetes

### Datasource(s)?

Loki 2.9.8

**Comment by matyax** [comment]
@kuburoman Thank you for reporting this issue. What would be the expected outcome? You can turn the feature flag off, which is what we added to control this behavior.

**Comment by LinTechSo** [comment]
Hi
i think same issue here
any updates?

i investigate it on two client of my loki 3.1.1 cluster
1. client 1 has ~50GB ingest in 24hour
2. client 2 has ~ 1.5 GB ingest in 24hour

i set below configuration
```
      max_cache_freshness_per_query: 10m
      max_entries_limit_per_query: 1000
      max_query_bytes_read: 10737418240B
      query_timeout: 30m
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      retention_period: 24h
      shard_streams:
        desired_rate: 2097152
        enabled: true
      split_queries_by_interval: 15m
      tsdb_max_query_parallelism: 2048
```
so i added `max_query_bytes_read` to issue my consideration but
in two query:
1. client 2 huge qeury in 30d grafana time range: 
This query will process approximately 21.5 GiB grfana says but the query run and loki do not block the query! 
2. clinet 1 huge query in 12h grfana time range:
the query will block with error: the query would read too many bytes (query: 24 GiB, limit: 10 GiB); consider adding more specific stream selectors or reduce the time range of the query

so in long time range loki did not block the query
can someone tell me why?


thanks
