### ISSUE TITLE
Provisioning of postgres datasources not workingArea: Short description of bug

### ISSUE THREAD

**Issue by sdohn-ui** [grafana/grafana#90680]
### What happened?

Hi, I've added in the grafana/latest docker container an provisioning
of a postgres datasource, and put it under: /etc/grafana/provisioning/datasources

The datasource:

```
apiVersion: 1

datasources:
  - name: 'Postgres'
    type: 'postgres'
    url: 'db-test.customers.com:5432'
    user: 'grafana_readonly'
    secureJsonData:
      password: 'SeeSecretServer'
    jsonData:
      database: 'iagent'
      sslmode: 'disable'
      maxOpenConns: 35
      maxIdleConns: 35
      maxIdleConnsAuto: 'true'
      connMaxLifetime: '14400'
      postgresVersion: '14400'
      timescaledb: 'false' 
```

I restartet the docker container, and the datasource is not editable.
When I try to create a dashboard with this datasource I'm getting 
**Data source with UID "P44368ADAD746BC27" not found.**

What am I'm doing wrong.

Thanks and regards from \sdohn

### What did you expect to happen?

The datasource is valid, and can be edited afterwards

### Did this work before?

Never before

### How do we reproduce it?

1. Pull the latest grafana docker container
2. Put my datasource yaml file under /etc/grafana/provisioning/datasources
3. restart the container, and wait that the datasource can be used.

### Environment (with versions)?

Grafana:c grafana version 10.3.4
OS: Win 10
Browser: Firefox 128.0

### Grafana platform?

Docker

**Comment by sdohn-ui** [comment]
Seems that I have to give the orgId and uid in the default.xaml

The following will work for me:

```
apiVersion: 1
datasources:
  - name: grafana-postgresql-datasource
    type: postgres
    access: proxy
    orgId: 1
    uid: grafana-postgresql-datasource
    url: db-test.customers.com:5432
    user: grafana_readonly
    secureJsonData:
      password: 'SeeSecretServer'
    jsonData:
      database: iagent
      sslmode: disable # disable/require/verify-ca/verify-full
      maxOpenConns: 35 # Grafana v5.4+
      maxIdleConns: 35 # Grafana v5.4+
      maxIdleConnsAuto: true # Grafana v9.5.1+
      connMaxLifetime: 14400 # Grafana v5.4+
      postgresVersion: 1400 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: false
    version: 2
    editable: true

```
