### ISSUE TITLE
Alerting: [11.1.0] can't view Prometheus alerting rule & can't add matching labels for cortex alertmanager in "Add notification policy" page

### ISSUE THREAD

**Issue by mousimin** [grafana/grafana#90813]
### What happened?

I am using Grafana 11.1.0, and I observed two "bugs" for it:
1. It will always show "Load..." when I click the view button for prometheus alert rule, but it works for cortex alert rule.
![image](https://github.com/user-attachments/assets/7edcd28b-0c02-4ecc-b72c-a24739875e4c)
2. For the "Add notification policy" page, it will always report error `error validating Alertmanager config: bad matcher format: "a"="b"` when I try to any matching labels (I am using cortex alertmanager here), but it works if use the REST API of cortex.
![image](https://github.com/user-attachments/assets/8d502949-7b82-4840-a3fd-afb8e368afc2)
![image](https://github.com/user-attachments/assets/fb1586c8-036f-4228-9af6-461fa116202d)

cortex REST API:
`curl -i -H "Authorization: Bearer $(TOKEN)"  -H 'Content-Type: application/yaml' -X POST --data-binary @alerts.yaml $(ALERT_URL)/api/v2/alerts`
alerts.yaml :
```
alertmanager_config: |
......
  route:
          - continue: false
            matchers:
              - a=b
            mute_time_intervals: []
            receiver: simin_contact_point
            routes: []
......
```

### What did you expect to happen?

I should be able to view prometheus alerting rules without error
I should be able to add any existing or not-existing matching labels in Add notification policy" page without error

### Did this work before?

this works for Grafana 10.3.5

### How do we reproduce it?

1. install Grafana 11.1.0
2. configure a prometheus datasource and upload some alerting rules
3. click the view button for the rules from Alerting-Alert rules page 
4. click "New child policy" link from Alerting-Notification policies page and add matching labels

### Environment (with versions)?

Grafana: 11.1.0
OS: linux
Browser: chrome

### Grafana platform?

A downloaded binary

### Datasource(s)?

Prometheus and Cortex
