### ISSUE TITLE
Prometheus: customQueryParameters not working for query endpoints

### ISSUE THREAD

**Issue by jacobbaungard** [grafana/grafana#90905]
### What happened?

customQueryParameters do not currently work on Prometheus endpoints: `api/v1/query`, `api/v1/query_range`, `api/v1/query_exemplars`

### What did you expect to happen?

customQueryParameters applied to all Prometheus queries.

### Did this work before?

Yes, unsure when exactly this broke as we're on an ancient version (~8.1).

### How do we reproduce it?

1. Setup a datasource with customQueryParameters, example:
```
apiVersion: 1
datasources:
- access: proxy
  isDefault: true
  name: Prom
  type: prometheus
  url: ....
  jsonData:
    customQueryParameters: max_source_resolution=auto
```
2.
Query Prometheus via Grafana and see that the customQueryParameters are not applied to `api/v1/query`, `api/v1/query_range`, `api/v1/query_exemplars` (we have a proxy between Grafana and Prometheus and are able to log the requests there, as the log below):

```
URL /api/metrics/v1/default/api/v1/labels?end=1721817480&max_source_resolution=auto&max_source_resolution=auto&start=1721813820
...
URL /api/v1/query_range
request body: string=end=1721817300&query=%3Anode_memory_MemAvailable_bytes%3Asum&start=1721813700&step=300
```
Note that the `query_range` request doesn't include the `max_source_resolution=auto` as set by `customQueryParameters`

### Environment (with versions)?

Grafana: 11.1.0
OS:
Browser:

### Grafana platform?

None

### Datasource(s)?

Prometheus
