### ISSUE TITLE
Getting 401 Unauthorized on page /alerting/list 

### ISSUE THREAD

**Issue by rpuserh** [grafana/grafana#91148]
### What happened?

I disabled grafana auth see helm values below. Now when navigating to grafana 127.0.0.1:3000/alerting/list I get error Unauthorized
Quickly looking to browser errors and found this is URL that fails
```http://127.0.0.1:3000/api/user GET 401 Unauthorized```

All Grafana pages works fine except alerting page when auth is disabled for grafana

### What did you expect to happen?

Ill expect to have no errors related to auth when auth is disabled

### Did this work before?

n/a

### How do we reproduce it?

1. deploy grafana on k8s
```
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 50m0s
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      version: 8.3.6
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    replicas: 1
    grafana.ini:
      auth:
        disable_login: true
        disable_login_form: true
        disable_signout_menu: true
      auth.anonymous:
        enabled: true
        org_role: Viewer
      auth.basic:
        enabled: false
      users:
        viewers_can_edit: true
      explore:
        enabled: true
    sidecar:
      datasources:
        enabled: true
      dashboards:
        enabled: true

```
3. add some prometheus datasource
4. Navigate to list alerts, you will see Unauthorized message

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 11.1.0,11.1.3
OS: k8s
Browser: chrome

### Grafana platform?

Kubernetes

### Datasource(s)?

prometheus
