### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by nemobis** [grafana/grafana#91217]
### What happened?

For a few weeks now, our grafana v10.4.5 pods in kubernetes have been restarting very frequently, about every 5-10 minutes. The same happens with  v10.4.6, just released.

Before restarting, they log a panic (log in reverse chronological order here):

```
golang.org/x/sync@v0.6.0/errgroup/errgroup.go:75 +0x96
--
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
golang.org/x/sync@v0.6.0/errgroup/errgroup.go:78 +0x56
golang.org/x/sync/errgroup.(*Group).Go.func1()
github.com/grafana/grafana/pkg/server/server.go:163 +0x11a
github.com/grafana/grafana/pkg/server.(*Server).Run.func1()
github.com/grafana/grafana/pkg/services/cleanup/cleanup.go:81 +0x5c
github.com/grafana/grafana/pkg/services/cleanup.(*CleanUpService).Run(0xc0001529a0, {0x230e2a8, 0xc0010294f0})
github.com/grafana/grafana/pkg/services/cleanup/cleanup.go:117 +0x713
github.com/grafana/grafana/pkg/services/cleanup.(*CleanUpService).clean(0xc0001529a0, {0x230e2a8, 0xc0010294f0})
github.com/grafana/grafana/pkg/services/cleanup/cleanup.go:198 +0x7b
github.com/grafana/grafana/pkg/services/cleanup.(*CleanUpService).deleteExpiredSnapshots(0xc0001529a0, {0x230e270, 0xc003b8cdb0})
github.com/grafana/grafana/pkg/services/dashboardsnapshots/service/service.go:76 +0x25
github.com/grafana/grafana/pkg/services/dashboardsnapshots/service.(*ServiceImpl).DeleteExpiredSnapshots(0xc001d756e0?, {0x230e270?, 0xc003b8cdb0?}, 0xc001110fa8?)
github.com/grafana/grafana/pkg/services/dashboardsnapshots/database/database.go:45 +0xa1
github.com/grafana/grafana/pkg/services/dashboardsnapshots/database.(*DashboardSnapshotStore).DeleteExpiredSnapshots(0x571e685?, {0x230e270?, 0xc003b8cdb0?}, 0xc001b1e401?)
goroutine 1081 [running]:
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x9d46fe1]
panic: runtime error: invalid memory address or nil pointer dereference
stats are ready to report"
```

### What did you expect to happen?

Not a panic.

### Did this work before?

I'm not sure whether this is related to some changes we made recently but I've disabled a plugin which we added recently and it didn't change anything.

### How do we reproduce it?

No idea! Our grafana.ini is something like

```
paths:
  data: /var/lib/grafana
  logs: /var/log/grafana
  plugins: /var/lib/grafana/plugins

server:
  protocol: http
  enforce_domain: False
  enable_gzip: False
  static_root_path: public
  router_logging: False
  serve_from_sub_path: False

database:
  type: postgres

users:
  allow_sign_up: False
  auto_assign_org_role: Viewer
  default_theme: light
  viewers_can_edit: True
  case_insensitive_login: True
emails:
  welcome_email_on_sign_up: False

auth:
  disable_login_form: False
  oauth_auto_login: False
  disable_signout_menu: False

auth.azuread:
  name:  Azure AD
  enabled: true
  allow_sign_up: true
  client_id: ${sp_client_id}
  scopes: openid email profile
  auth_url: https://login.microsoftonline.com/<redacted>/oauth2/v2.0/authorize
  token_url: https://login.microsoftonline.com/<redacted>/oauth2/v2.0/token
  allowed_domains:
  allowed_groups:
  role_attribute_strict: false
  allow_assign_grafana_admin: false

dataproxy:
  timeout: 60

analytics:
  reporting_enabled: "True"

dashboards:
  versions_to_keep: 1000

alerting:
  enabled: false

smtp:
  enabled: True

log:
  mode: console, file
  level: info

metrics:
  enabled: true
  interval_seconds: 10

snapshots:
  external_enabled: False
  public_mode: False
  snapshot_remove_expired: False

unified_alerting:
  enabled: True

plugins:
  allow_loading_unsigned_plugins: uptrends-uptrends-plugin,andrewbmchugh-flow-panel

feature_toggles:
  prometheusMetricEncyclopedia: True
  prometheusWideSeries: False
  nestedFolders: False
  publicDashboards: False
  autoMigrateOldPanels: False
```

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

```

    Image:           docker.io/grafana/grafana:10.4.6
    Image ID:        docker.io/grafana/grafana@sha256:ffef0672f94b4a9141e3979011bbf3357e54df77492381faecc016cbfe170e00

```

### Grafana platform?

Kubernetes

### Datasource(s)?

No
