### ISSUE TITLE
Spike in memory usage overnight causing crash

### ISSUE THREAD

**Issue by bonco4** [grafana/grafana#91496]
### What happened?

Hello, I am having an issue with my grafana server having large spikes in memory usage that causes my server to crash. I have updated the database setting "wal=true" per this issue (https://github.com/grafana/grafana/issues/64664#issuecomment-1471414001), and it made it go a day without running out of memory, but it eventually crashed again. It seems like some process is running in the middle of the night that is using up all the memory. Looking around the timestamps where the memory is being used up, I see messages like this (I don't know if this is relevant) around the first big jump in memory usage (I don't see anything that is clearly responsible)
```

logger=context userId=0 orgId=0 uname= t=2024-08-01T22:38:07.43445741Z level=info msg="Request Completed" method=GET path=/ status=302 remote_addr=198.235.24.17 time_ms=0 duration=100.306µs size=29 referer=http://20.127.188.96:80/ handler=/ status_source=server
logger=cleanup t=2024-08-01T22:45:30.476291282Z level=info msg="Completed cleanup jobs" duration=3.56185ms
logger=plugins.update.checker t=2024-08-01T22:45:30.659740613Z level=info msg="Update check succeeded" duration=55.857471ms
logger=context userId=0 orgId=0 uname= t=2024-08-01T22:54:11.816611084Z level=info msg="Request Completed" method=GET path=/ status=302 remote_addr=185.242.226.75 time_ms=0 duration=86.305µs size=29 referer= handler=/ status_source=server
logger=cleanup t=2024-08-01T22:55:30.476591988Z level=info msg="Completed cleanup jobs" duration=3.978027ms
logger=plugins.update.checker t=2024-08-01T22:55:30.661982233Z level=info msg="Update check succeeded" duration=57.862891ms
logger=licensing t=2024-08-01T23:05:30.437796164Z level=info msg="Validated license token" appURL=https://grafana.novee.app/ source=disk status=NotFound
logger=licensing.renewal t=2024-08-01T23:05:30.437839764Z level=warn msg="failed to load or validate token" err="license token file not found: /var/lib/grafana/license.jwt"
logger=cleanup t=2024-08-01T23:05:30.476137345Z level=info msg="Completed cleanup jobs" duration=3.586036ms
logger=plugins.update.checker t=2024-08-01T23:05:30.661760887Z level=info msg="Update check succeeded" duration=58.344779ms
logger=infra.usagestats t=2024-08-01T23:07:29.414162641Z level=info msg="Usage stats are ready to report"
```
 
 And messages like this around midnight when it ran out of memory fully:
 
```
logger=cleanup t=2024-08-02T04:27:17.989936859Z level=error msg="Failed to delete expired snapshots" error="context deadline exceeded"
logger=cleanup t=2024-08-02T04:28:01.987177732Z level=error msg="Cancelled cleanup job" error="context deadline exceeded" duration=12m11.035459655s
logger=secrets.kvstore t=2024-08-02T04:33:07.096574788Z level=error msg="error getting secret value" orgId=1 type=datasource namespace=prometheus err="context deadline exceeded"
logger=secrets.kvstore t=2024-08-02T04:36:09.556181347Z level=error msg="error getting secret value" orgId=1 type=datasource namespace=prometheus err="context deadline exceeded"
logger=secrets.kvstore t=2024-08-02T04:49:31.724414165Z level=error msg="error getting secret value" orgId=1 type=datasource namespace=prometheus err="context deadline exceeded"
logger=secrets.kvstore t=2024-08-02T04:56:41.248102538Z level=error msg="error getting secret value" orgId=1 type=datasource namespace=prometheus err="context deadline exceeded"
logger=cleanup t=2024-08-02T04:58:49.991332761Z level=error msg="Cancelled cleanup job" error="context deadline exceeded" duration=27m35.295206157s
logger=secrets.kvstore t=2024-08-02T07:08:54.216443536Z level=error msg="error getting secret value" orgId=1 type=datasource namespace=prometheus err="context deadline exceeded"
logger=ngalert.sender.router rule_uid=cdstmqxp8v9xca org_id=1 t=2024-08-02T07:09:09.863397199Z level=info msg="Sending alerts to local notifier" count=1
logger=ngalert.sender.router rule_uid=edsqp2fxok4jka org_id=1 t=2024-08-02T07:09:10.57611006Z level=info msg="Sending alerts to local notifier" count=1
logger=ngalert.sender.router rule_uid=edstn1v42noxsb org_id=1 t=2024-08-02T07:09:09.619409729Z level=info msg="Sending alerts to local notifier" count=1
logger=ngalert.sender.router rule_uid=cdstmzg4vxszke org_id=1 t=2024-08-02T07:09:09.772981815Z level=info msg="Sending alerts to local notifier" count=1
logger=analytics.summaries t=2024-08-02T07:09:13.428128702Z level=error msg="error during daily rollup" err="got error when acquiring lock: context deadline exceeded"
logger=licensing t=2024-08-02T07:09:16.819328439Z level=info msg="Validated license token" appURL=https://grafana.novee.app/ source=disk status=NotFound
logger=licensing.renewal t=2024-08-02T07:09:21.21836482Z level=warn msg="failed to load or validate token" err="license token file not found: /var/lib/grafana/license.jwt"
logger=infra.usagestats t=2024-08-02T07:09:28.369673768Z level=info msg="Usage stats are ready to report"
logger=accesscontrol.store t=2024-08-02T07:09:29.669225284Z level=warn msg="Error retrieving metrics" error="context deadline exceeded"
logger=context userId=0 orgId=0 uname= t=2024-08-02T07:09:32.611603075Z level=info msg="Request Completed" method=GET path=/.env status=302 remote_addr=78.153.140.179 time_ms=33764 duration=33.764181731s size=29 referer= handler=notfound status_source=server
logger=context userId=0 orgId=0 uname= t=2024-08-02T07:09:35.329588064Z level=info msg="Request Completed" method=GET path=/ status=302 remote_addr=64.62.197.135 time_ms=18949 duration=18.949500168s size=29 referer= handler=/ status_source=server
logger=ngalert.sender.router rule_uid=edstmxwu7uwowd org_id=1 t=2024-08-02T07:09:35.224648083Z level=info msg="Sending alerts to local notifier" count=1
logger=licensing t=2024-08-02T07:09:37.265561193Z level=info msg="Validated license token" appURL=https://grafana.novee.app/ source=disk status=NotFound
```

I'm really not sure what to make of this. I am running grafana from a docker-compose file with some other containers in it, and I looked through those logs but don't see anything obvious either. This is my docker compose and env file:

```
services:
  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

  blackbox_exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox_exporter
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox.yml:/config/blackbox.yml
    command:
      - '--config.file=/config/blackbox.yml'

  webserver:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - grafana

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done"

volumes:
  grafana-data:
  prometheus-data:
  certbot-www:
  letsencrypt:
```
```
GF_SECURITY_ADMIN_PASSWORD=
GF_INSTALL_PLUGINS=grafana-worldmap-panel
GF_SMTP_ENABLED=true
GF_SMTP_HOST=smtp.dreamhost.com:465
GF_SMTP_USER=alerts@novee.app
GF_SMTP_PASSWORD=
GF_SMTP_FROM_ADDRESS=alerts@novee.app
GF_SMTP_FROM_NAME=Novee Alerts
GF_SMTP_SKIP_VERIFY=false
GF_SECURITY_ADMIN_PASSWORD=
GF_INSTALL_PLUGINS=grafana-worldmap-panel
GF_SERVER_ROOT_URL=https://grafana.novee.app/
GF_AUTH_GENERIC_OAUTH_ENABLED=true
GF_AUTH_GENERIC_OAUTH_NAME=Auth0
GF_AUTH_GENERIC_OAUTH_CLIENT_ID=
GF_AUTH_GENERIC_OAUTH_SCOPES=openid profile email
GF_AUTH_GENERIC_OAUTH_AUTH_URL=https://dev-bqa8q6hw.us.auth0.com/authorize
GF_AUTH_GENERIC_OAUTH_TOKEN_URL=https://dev-bqa8q6hw.us.auth0.com/oauth/token
GF_AUTH_GENERIC_OAUTH_API_URL=https://dev-bqa8q6hw.us.auth0.com/userinfo
GF_AUTH_GENERIC_OAUTH_REDIRECT_URI=https://grafana.novee.app/login/generic_oauth
GF_AUTH_GENERIC_OAUTH_LOGOUT_URL=https://dev-bqa8q6hw.us.auth0.com/v2/logout
GF_DATABASE_TYPE=sqlite3
GF_DATABASE_WAL=true
```

Finally, here is a screenshot of the memory usage of my server over time. Also included is the log files for my grafana container.
[logs.txt](https://github.com/user-attachments/files/16471826/logs.txt)

![image](https://github.com/user-attachments/assets/a945daa0-b830-4ee8-bebe-11951ce3af99)

### What did you expect to happen?

I expect the memory usage to be relatively consistent over time.

### Did this work before?

No, I have had this issue since I set up this server a ~ 10 days ago.

### How do we reproduce it?

Unsure

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: Grafana v11.1.0 (5b85c4c2fc)
OS: Docker/Ubuntu
Browser: N/A

### Grafana platform?

Docker

### Datasource(s)?

Infinity, Prometheus
