### ISSUE TITLE
Provisioning: Paths in folders appear duplicated

### ISSUE THREAD

**Issue by senpro-ingwersenk** [grafana/grafana#91826]
### What happened?

A collegue of mine noticed the other day that a provisioned dashboard spawned not one but two folders:
![image](https://github.com/user-attachments/assets/5e4dceb5-6b8d-41d3-bf25-9f898ac95ec8)

In the database, this turned out to look something like this:
```
grafana=# select id,uid,org_id,title from folder order by title asc;
   id   |                 uid                  | org_id |                       title
--------+--------------------------------------+--------+---------------------------------------------------
 (...)
 189233 | edtidznhl3dhcd                       |     24 | Zyxel Networks A
 189231 | fdtidzncgavwgf                       |     10 | Zyxel Networks A
  68992 | bdiigoo49v474e                       |     10 | Zyxel Networks A/S
  69230 | bdiigxb76sflsb                       |     24 | Zyxel Networks A/S
(...)

grafana=# select id,uid,title,org_id,folder_id,is_folder from dashboard where folder_uid='edtidznhl3dhcd';
 id  |      uid       | title | org_id | folder_id | is_folder
-----+----------------+-------+--------+-----------+-----------
 537 | bdtidznje0qgwd | S     |     24 |         0 | t
(1 row)

grafana=# select id,uid,title,org_id,folder_id,is_folder from dashboard where folder_uid='fdtidzncgavwgf';
 id  |      uid       | title | org_id | folder_id | is_folder
-----+----------------+-------+--------+-----------+-----------
 535 | fdtidzng9nawwf | S     |     10 |         0 | t
(1 row)

grafana=# select id,uid,title,org_id,folder_id,is_folder from dashboard where folder_uid='bdiigoo49v474e';
 id  |                 uid                  |      title       | org_id | folder_id | is_folder
-----+--------------------------------------+------------------+--------+-----------+-----------
 483 | e82a9abb-6f2a-4cf2-a5f1-e1621b96483e | Switches (Zyxel) |     10 |       482 | f
(1 row)

grafana=# select id,uid,title,org_id,folder_id,is_folder from dashboard where folder_uid='bdiigxb76sflsb';
 id  |                 uid                  |      title       | org_id | folder_id | is_folder
-----+--------------------------------------+------------------+--------+-----------+-----------
 485 | e82a9abb-6f2a-4cf2-a5f1-e1621b96483e | Switches (Zyxel) |     24 |       484 | f
(1 row)
```

The following is the related YAML document from our (private) provisioning repository:
```yaml
apiVersion: 1

providers:
- name: potli-zyxel-switches
  orgId: 10
  folder: "Zyxel Networks A/S"
  type: file
  updateIntervalSeconds: 10
  options:
    path: /etc/grafana/provisioning/dashboards/zyxel/switches.json
- name: wsemo-zyxel-switches
  orgId: 24
  folder: "Zyxel Networks A/S"
  type: file
  updateIntervalSeconds: 10
  options:
    path: /etc/grafana/provisioning/dashboards/zyxel/switches.json
```

Provisioning is done using the git-sync container as a sidecar in Kubernetes with the provisioning mounted in `/etc/grafana/provisioning`.

### What did you expect to happen?

We expected only folders with the exact name "Zyxel Networks A/S" to exist - instead, we got two of them where one version spawned a subfolder "S" with no entireis and references. Considering the slash in the title, we concluded that the name was accidentially treated as a path and thus led to the "duplicate". It is but a hunch, really.

### Did this work before?

We have no evidence of that, this part of the deployment is very new and recent.

### How do we reproduce it?

1. Insert the above YAML snippet into your deployments' provisioning
2. Create a random dashboard to use as a reference for the JSON file.
3. Restart Grafana to make the provisioning take effect
4. You should now see what is visible in the screenshot above.

### Is the bug inside a dashboard panel?

No.

### Environment (with versions)?

Grafana: 11.1.3 (OSS, Hobby)
OS: Linux, Kubernetes (`image: docker.io/grafana/grafana:11.1.3`)
Browser: Brave

### Grafana platform?

Kubernetes

### Datasource(s)?

Not specific to a datasource.

**Comment by papagian** [comment]
thank you for reporting it!
I suspected that this could be a bug related with the slash in the folder name but I couldn't reproduce it. do you happen to provision also alerts into these folders?
However I have noticed that you have two entries pointing to the same `path` and `folder`: what is your use case?
why only the one entry is not enough?
```
apiVersion: 1

providers:
- name: potli-zyxel-switches
  orgId: 10
  folder: "Zyxel Networks A/S"
  type: file
  updateIntervalSeconds: 10
  options:
    path: /etc/grafana/provisioning/dashboards/zyxel/switches.json
- name: wsemo-zyxel-switches
  orgId: 24
  folder: "Zyxel Networks A/S"
  type: file
  updateIntervalSeconds: 10
  options:
    path: /etc/grafana/provisioning/dashboards/zyxel/switches.json
```

**Comment by PW999** [comment]
We actually have a similar issue were subfolders are provisioned twice.

We have the following dashboards in our git repo

![Image](https://github.com/user-attachments/assets/84baebdd-ca97-4b8c-82be-20ed829b0811)

Once rolled out, the subfolder is also created in the root of the project

![Image](https://github.com/user-attachments/assets/31a6cb64-6431-4dff-b4e9-3b7f2cd94c1e)

I can simply delete the empty folder so there's no alerts created in the folder or something like that.

Our dashboard configuration is as follows:
```
apiVersion: 1
providers:
- name: default
  type: file
  updateIntervalSeconds: 30
  # Disable dashboard deletion
  disableDeletion: false
  # Allows users to edit data sources from the Grafana UI
  editable: false
  # Allow updating provisioned dashboards from the UI
  allowUiUpdates: false
  options:
    path: /etc/grafana/provisioning/dashboards
    foldersFromFilesStructure: true
```
