### ISSUE TITLE
Docs: HTTPS setup inadequate for Helm installation method

### ISSUE THREAD

**Issue by jgreenbow** [grafana/grafana#91966]
### What happened?

I installed Grafana using the Helm chart and was setting up HTTPS. I successfully mounted TLS certificates (provided by cert-manager) using the `extraSecretMounts` Helm field. I configured `grafana.ini` to use h2/https and the mounted certs. The docs were generally helpful up to this point. 

However, I could not get a healthy Grafana deployment. Traffic to the service returned 'OpenSSL SSL_connect: Connection reset by peer', and logs showed 'grafana remote error: tls: unknown certificate'.

Helm values excerpts (scrubbed):
```yaml
extraSecretMounts:
- name: tls-cert
  mountPath: /etc/grafana/ssl
  secretName: env1-grafana-tls
  readOnly: true

# ...

grafana.ini:
  # ...
  server:
    protocol: h2 # or https
    domain: env1.domain.name
    root_url: https://env1.domain.name
    cert_file: /etc/grafana/ssl/tls.crt
    cert_key: /etc/grafana/ssl/tls.key
``` 

Resolution ultimately came when I changed the health check protocol. Helm values:

```yaml
readinessProbe:
  httpGet:
    path: /api/health
    port: 3000
    scheme: HTTPS

livenessProbe:
  httpGet:
    path: /api/health
    port: 3000
    scheme: HTTPS
  initialDelaySeconds: 60
  timeoutSeconds: 30
  failureThreshold: 10
```

### What did you expect to happen?

HTTPS setup docs should describe changing the protocol for liveness and readiness probes.

### Did this work before?

No.

### How do we reproduce it?

N/A, static docs

### Environment (with versions)?

Grafana: 7.5, 11.1
OS: bottlerocket 1.20
Browser: chrome

### Grafana platform?

Kubernetes
