### ISSUE TITLE
Docs: Broken links in contribute/**/*.md

### ISSUE THREAD

**Issue by rwielk** [grafana/grafana#92181]
### What happened?

While reading through contribute/**/*.md, I received a couple of 404 error.

### What did you expect to happen?

Links working.

### Did this work before?

Unsure, partially, n/a regarding grafana version from my pov.

### How do we reproduce it?

E.g. Navigate to this contribute/backend/README.me and click Upgrading dependencies.
I'recommend to check for dead links with tooling see #92107

tldr; to get all catched in this case:

```
~/git/grafana   main  cat .linkspector.yml 
dirs:
  - contribute
# remove gitlab anchors to lines to prevent linkspector to write to stderr for github-action to work
replacementPatterns:
  - pattern: "^(.*)#(L\\d+)$"
    replacement: '$1'

~/git/grafana   main  docker run --rm -it -v $PWD:/app --name linkspector umbrelladocs/linkspector bash -c 'linkspector check'
```

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

n/a

### Grafana platform?

None
