### ISSUE TITLE
Docs: Broken links in devenv/**/*.md

### ISSUE THREAD

**Issue by rwielk** [grafana/grafana#92260]
### What happened?

While reading through devenv/**/*.md, I received a couple of 404 error.

### What did you expect to happen?

Links working.

### Did this work before?

Unsure, partially, n/a regarding grafana version from my pov, external links, did not look into archieves ;)

### How do we reproduce it?

E.g. Navigate to this devenv/docker/blocks/collectd/README.md and click on collectd.conf man page.
I'recommend to check for dead links with tooling see https://github.com/grafana/grafana/issues/92107

tldr; to get all catched in this case:

```
~/git/grafana   main ±  cat .linkspector.yml 
dirs:
  - devenv
modifiedFilesOnly: true
# Ignore links for setup dev environment
ignorePatterns:
  - pattern: '^http://localhost(.*)'
  - pattern: '^(.*).loc/$'
# Remove gitlab anchors to lines to prevent linkspector to write to stderr for github-action to work
replacementPatterns:
  - pattern: "^(.*)#(L\\d+)$"
    replacement: '$1'

~/git/grafana   main  docker run --rm -it -v $PWD:/app --name linkspector umbrelladocs/linkspector bash -c 'linkspector check'
```

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

n/a

### Grafana platform?

None
