### ISSUE TITLE
Dashboards: Provisioning wont trigger "Start walking disk" after hitting the reload endpoint (11.1.4 doenst work, 10.4.2 it works)

### ISSUE THREAD

**Issue by CoolZeroNL** [grafana/grafana#92319]
### What happened?

Grafana dashboards are not been provisioned since upgrade from 10.4.2 to 11.1.4 when placing the yaml file, and calling the endpoint: [host]/api/admin/provisioning/dashboards/reload

The provisioning files are been placed after start of grafana, and based on the content (org) in influxdb grafana will be provisent.

For both version, the same setup/script/provisioning is been used, only the dep package of grafana 10.4.2 vs 11.1.4. Each time its a clean deployment of grafana.

**Endpoint call is working**
```bash
*   Trying 127.0.0.1:4001...
* Connected to localhost (127.0.0.1) port 4001 (#0)
* Server auth using Basic with user 'admin'
> POST /api/admin/provisioning/dashboards/reload HTTP/1.1
> Host: localhost:4001
> Authorization: Basic xxxx
> User-Agent: curl/7.88.1
> Accept: application/json
> Content-Type: application/json
>
< HTTP/1.1 200 OK
< Cache-Control: no-store
< Content-Type: application/json
< X-Content-Type-Options: nosniff
< X-Xss-Protection: 1; mode=block
< Date: Thu, 22 Aug 2024 13:49:33 GMT
< Content-Length: 40
<
* Connection #0 to host localhost left intact
{"message":"Dashboards config reloaded"}
```

**11.1.4**

```
logger=settings t=2024-08-22T13:29:01.620875884Z level=info msg="Starting Grafana" version=11.1.4 commit=2355de00c61fdd6609a67f35ab506fae87f09a84 branch=HEAD compiled=2024-08-22T13:29:01Z
logger=settings t=2024-08-22T13:29:01.62153287Z level=info msg="Config loaded from" file=/usr/share/grafana/conf/defaults.ini
logger=settings t=2024-08-22T13:29:01.621577074Z level=info msg="Config loaded from" file=/opt/grafana/grafana.ini
logger=settings t=2024-08-22T13:29:01.621588685Z level=info msg="Config overridden from command line" arg="default.paths.data=/var/lib/grafana"
logger=settings t=2024-08-22T13:29:01.621597666Z level=info msg="Config overridden from command line" arg="default.paths.logs=/var/log/grafana"
logger=settings t=2024-08-22T13:29:01.621605981Z level=info msg="Config overridden from command line" arg="default.paths.plugins=/opt/grafana/plugins"
logger=settings t=2024-08-22T13:29:01.621614648Z level=info msg="Config overridden from command line" arg="default.paths.provisioning=/opt/grafana-data/provisioning"

logger=accesscontrol t=2024-08-22T13:49:33.033917198Z level=debug msg="Evaluating permissions" namespace=user id=1 orgID=1 permissions="action:provisioning:reload scopes:provisioners:dashboards"
logger=accesscontrol.evaluator t=2024-08-22T13:49:33.033989439Z level=debug msg="Matched scope" userscope=provisioners:* targetscope=provisioners:dashboards
logger=provisioning t=2024-08-22T13:49:33.03405155Z level=debug msg="Stop polling for dashboard changes"
logger=provisioning.dashboard t=2024-08-22T13:49:33.034409163Z level=info msg="starting to provision dashboards"
logger=provisioning.dashboard t=2024-08-22T13:49:33.034442978Z level=info msg="finished to provision dashboards"
logger=ngalert.scheduler t=2024-08-22T13:49:40.001104715Z level=debug msg="No changes detected. Skip updating"
```

**10.4.2**
```
logger=settings t=2024-08-22T14:07:01.220085547Z level=info msg="Starting Grafana" version=10.4.2 commit=22809dea50455ae875624827dd277b17621b4ed4 branch=HEAD compiled=2024-08-22T14:07:01Z
logger=settings t=2024-08-22T14:07:01.220421437Z level=info msg="Config loaded from" file=/usr/share/grafana/conf/defaults.ini
logger=settings t=2024-08-22T14:07:01.220440937Z level=info msg="Config loaded from" file=/opt/grafana/grafana.ini
logger=settings t=2024-08-22T14:07:01.220448919Z level=info msg="Config overridden from command line" arg="default.paths.data=/var/lib/grafana"
logger=settings t=2024-08-22T14:07:01.220456363Z level=info msg="Config overridden from command line" arg="default.paths.logs=/var/log/grafana"
logger=settings t=2024-08-22T14:07:01.220463104Z level=info msg="Config overridden from command line" arg="default.paths.plugins=/opt/grafana/plugins"
logger=settings t=2024-08-22T14:07:01.220469882Z level=info msg="Config overridden from command line" arg="default.paths.provisioning=/opt/grafana-data/provisioning"

logger=provisioning t=2024-08-22T14:10:08.183744836Z level=debug msg="Stop polling for dashboard changes"
logger=provisioning.dashboard t=2024-08-22T14:10:08.184876009Z level=info msg="starting to provision dashboards"
logger=provisioning.dashboard type=file name="Shared-Main Org." t=2024-08-22T14:10:08.184911009Z level=debug msg="Start walking disk" path=/opt/grafana/dashboards/shared
logger=provisioning.dashboard type=file name="Shared-Main Org." t=2024-08-22T14:10:08.185896588Z level=debug msg="saving new dashboard" provisioner="Shared-Main Org." file=/opt/grafana/dashboards/shared/Alerts.json folderId=0 folderUid=
logger=accesscontrol.evaluator t=2024-08-22T14:10:08.187226281Z level=debug msg="Matched scope" userscope=folders:* targetscope=folders:uid:general
logger=provisioning.dashboard type=file name=bbq-formainorg t=2024-08-22T14:10:08.625653763Z level=debug msg="Start walking disk" path=/opt/grafana/dashboards/bbq
logger=provisioning.dashboard type=file name=bbq-formainorg t=2024-08-22T14:10:08.628705558Z level=debug msg="provisioned dashboard is up to date" provisioner=bbq-formainorg file=/opt/grafana/dashboards/bbq/BBQ.json folderId=0 folderUid=
logger=provisioning.dashboard t=2024-08-22T14:10:08.701085224Z level=warn msg="the same UID is used more than once" orgId=1 uid=ddi4w1cvk6epsb times=2 providers="[Shared-Main Org. Main Org.]"
logger=provisioning.dashboard t=2024-08-22T14:10:08.701157928Z level=warn msg="dashboards provisioning provider has no database write permissions because of duplicates" provider="Main Org." orgId=1
logger=provisioning.dashboard t=2024-08-22T14:10:08.701170484Z level=info msg="finished to provision dashboards"
```

**Provisioning Files are there:**

**tree /opt/grafana-data/provisioning/**

```
├── dashboards
│   ├── dashboard_MainOrg-shared.yaml
|   └── dashboard_bbq.yaml

1 directory, 2 file
```

**cat /opt/grafana-data/provisioning/dashboards/dashboard_bbq.yaml**

```yaml
---
apiVersion: 1

providers:
  # <string> an unique provider name. Required
  - name: 'bbq'
    # <int> Org id. Default to 1
    orgId: 4
    ....
    options:
      # <string, required> path to dashboard files on disk. Required when using the 'file' type
      path: /opt/grafana/dashboards/bbq
      # <bool> use folder names from filesystem to create folders in Grafana
      foldersFromFilesStructure: true
```

**tree /opt/grafana/dashboards/bbq**

```
/opt/grafana/dashboards/bbq
└── BBQ.json

1 directory, 1 file
```

and:

**cat /opt/grafana-data/provisioning/dashboards/dashboard_MainOrg-shared.yaml**

```yaml
---
apiVersion: 1

providers:
  # <string> an unique provider name. Required
  - name: 'Shared-Main Org.'
    # <int> Org id. Default to 1
    orgId: 1
    ....
    options:
      # <string, required> path to dashboard files on disk. Required when using the 'file' type
      path: /opt/grafana/dashboards/shared
      # <bool> use folder names from filesystem to create folders in Grafana
      foldersFromFilesStructure: true
```      
      
**tree /opt/grafana/dashboards/shared**

```
/opt/grafana/dashboards/shared
└── Alerts.json

1 directory, 1 files
```

### What did you expect to happen?

The dashboards should be loaded.

### Did this work before?

Yes in 10.4.2 it is working.

In 11.1.4, the dashboards are only loaded, whem grafana is been restarted as a services

### How do we reproduce it?

1. deploy grafana
2. start grafana
3. place yaml files
4. call api endpoint

### Environment (with versions)?

Grafana: 11.1.4
OS: Pi5

### Grafana platform?

A downloaded binary
