### ISSUE TITLE
Allow the editing of file provisioned alerts in the UI

### ISSUE THREAD

**Issue by Stono** [grafana/grafana#92454]
This is an extension of https://github.com/grafana/grafana/issues/57911#issuecomment-2022963330.

We want to provision our alerts consistently across environments, however we want to allow the editing of the rules in the UI (because then the process is to export the config and commit it to git).

It would be really good if alert groups in the provisioning yaml had an `editable: true|false` flag, similar to that of dashboards etc.

The current work around is to run a post-deploy script to execute some SQL (`UPDATE provenance_type SET provenance = '' WHERE record_type = 'alertRule'`)

**Comment by shohei-ihaya** [comment]
This is very helpful 👍

**Comment by marcus-clements** [comment]
We need this feature 👍

**Comment by CptOrange16** [comment]
This is needed. It makes no sense to allow other provisioned components to be editable and not these.

Same goes for contact points and notification policy

**Comment by konrad147** [comment]
Hey, I think there are 2 ways you can achieve the desired result:
1. Use the modified export feature - every provisioned rule have the modified export option - this gives you the opportunity to change a read-only rule and immediately export it instead of saving. This is designed exactly for scenarios like yours, where you want to keep the rules in git but still edit in the UI. https://grafana.com/docs/grafana/latest/alerting/set-up/provision-alerting-resources/export-alerting-resources/#modify-alert-rule-and-export-rule-group-without-saving-changes
2. Use the API provisioning - API provisioning supports `X-Disable-Provenance` header which makes the rule or another any resource (like contact point or notification policy) editable in the UI. However, in your scenario I'd consider the first option, as provisioning editable resources might lead to inconsistencies if someone forget to push the changes to git

**Comment by liebsc21** [comment]
I too vote for having the option to allow provisioned alerts to be editable.

**Comment by default-student** [comment]
missing this a lot

**Comment by vi-simon** [comment]
+1 on this, could be very useful, as being said here It makes no sense to allow other provisioned components to be editable and not these.

**Comment by Fyne5** [comment]
Hi friend, how can I run this query? I don't know where to do it.

**Comment by SirBrickAlot** [comment]
+1 on this as it makes managing of those resources unnecessary complicated

**Comment by defanator** [comment]
Would be really nice to have this working without modifying the database.

UPD: here's the workaround with sidecar job that does the db modification -

```yaml
volumes:
  grafana-data:

  grafana:
    container_name: grafana
    image: docker.io/grafana/grafana-enterprise:12.0.0
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana-data:/var/lib/grafana
      [..]
    [..]

  grafana-db-sidecar:
    container_name: grafana-db-sidecar
    image: docker.io/alpine:3.21
    command: |
      sh -c "
        apk add --no-cache sqlite &&
        echo 'Grafana database sidecar ready; database available at /grafana-data/grafana.db' &&
        trap exit SIGINT SIGQUIT SIGTERM &&
        sleep 5 &&
        while true; do
          if [ $(sqlite3 /grafana-data/grafana.db \"SELECT COUNT(*) FROM provenance_type;\") -gt 0 ]; then
            sqlite3 /grafana-data/grafana.db \"UPDATE provenance_type SET provenance='' WHERE record_type='alertRule';\" && break
          fi
          sleep 1
        done ;
        echo 'Database modified!'
      "
    volumes:
      - grafana-data:/grafana-data
    depends_on:
      - grafana
```

(worked for me in a simple local PoC setup)
