### ISSUE TITLE
Regression: Unauthorized error when anonymous auth is enabled

### ISSUE THREAD

**Issue by jhalterman** [grafana/grafana#92634]
### What happened?

Similar to #76995, it appears that when auth is disabled, Grafana is hitting a 401 when making a request to `/api/user/preferences`, which causes an unexpected popup. 

### What did you expect to happen?

No popup should occur. 

### Did this work before?

Yes, in 9.x there is no popup.

### How do we reproduce it?

1. Startup Grafana 11.x with env vars:

```
GF_AUTH_DISABLE_LOGIN_FORM=true
GF_AUTH_ANONYMOUS_ENABLED=true
```

2. Open Grafana.

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 11.2.0
OS: MacOS
Browser: Chrome, Firefox

### Grafana platform?

Docker

### Datasource(s)?

Prometheus

**Comment by grafanabot** [comment]
@jhalterman please add one or more appropriate labels. Here are some tips:

- if you are making an issue, TODO, or reminder for yourself or your team, please add one label that best describes the product or feature area. Please also add the issue to your project board. :rocket:

- if you are making an issue for any other reason (docs typo, you found a bug, etc), please add at least one label that best describes the product or feature that you are discussing (e.g. `area/alerting`, `datasource/loki`, `type/docs`, `type/bug`, etc). [Our issue triage](https://github.com/grafana/grafana/blob/main/ISSUE_TRIAGE.md#3-categorizing-an-issue) doc also provides additional guidance on labeling. :rocket:

 Thank you! :heart:

**Comment by jcreixell** [comment]
I am experiencing this too when running a grafana image via docker (specifically, `grafana/grafana:11.2.0`. Every time I refresh a dashboard, it will show an `Unauthorized` pop-up.

It can be easily reproduced by running the [OTEL demo](https://github.com/open-telemetry/opentelemetry-demo).

**Comment by danielkubat** [comment]
I have very similar setup as OP and facing the same this issue as well:

![Image](https://github.com/user-attachments/assets/6079e2e1-b24f-45ef-a441-dac171791d46)

I'm using `grafana/grafana-oss:11.2.0` image and grafana instance CR is managed using `grafana-operator` with following configuration:

```
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    instance: "grafana"
spec:
  service:
    spec:
      type: LoadBalancer
  config:
    auth:
      disable_login_form: "true"
    auth.anonymous:
      enabled: "true"
      org_role: "Admin"
    auth.basic:
      enabled: "false"
    analytics:
      enabled: "false"
    news:
      news_feed_enabled: "false"
    server:
      enable_gzip: "true"
  deployment:
    spec:
      replicas: 1
      strategy:
        type: RollingUpdate
      revisionHistoryLimit: 0
      template:
        spec:
          containers:
            - name: grafana
              image: grafana/grafana-oss
```
