### ISSUE TITLE
Google OAuth2: always prompts user for permission

### ISSUE THREAD

**Issue by noor-muradi** [grafana/grafana#92718]
### What happened?

Configured Google OAuth2 for Grafana as below, it always re asks user for permission and prompt for accepting consents.

```
    auth.google:
      enabled: true
      allow_sign_up: true
      auto_login: false
      client_id: xxxxxx.apps.googleusercontent.com
      client_secret: xxxxxxxxxxxxxx
      scopes: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/cloud-identity.groups.readonly
      auth_url: https://accounts.google.com/o/oauth2/v2/auth
      token_url: https://oauth2.googleapis.com/token
      api_url: https://openidconnect.googleapis.com/v1/userinfo
      allowed_domains: example.com
      hosted_domain: example.com
      allowed_groups: admins@example.com
      approval_prompt: "auto"
      include_granted_scopes: "true"
      use_pkce: true
      signout_redirect_url: https://grafana.example.com

```

### What did you expect to happen?

Only ask user for permission and consent acceptance once

### Did this work before?

It is the first time configuring it

### How do we reproduce it?

1.
2.
3.

### Environment (with versions)?

Grafana: 11.1.0
OS: Linux
Browser: Chrome

### Grafana platform?

None
