### ISSUE TITLE
Forbidden and 500 error from oncall plugin (grafana 11.1.0)

### ISSUE THREAD

**Issue by daasol** [grafana/grafana#92844]
### What happened?

Hello, I am trying to connect the Oncall plugin(1.9.19) to Grafana(11.1.0).
I am using Grafana OSS with an external Grafana setup.

The endpoints for Oncall and Grafana are correctly configured as follows:

```
externalGrafana:
  url: https://grafana.xxxx.xx
```

```
grafana-oncall-app.yaml:
  apiVersion: 1
  apps:
    - type: grafana-oncall-app
      name: grafana-oncall-app vv1.9.19
      url: https://grafana-oncall.xxx.xx
      org_id: 1
      enabled: true
      jsonData:
        stackId: 5
        orgId: 1
        onCallApiUrl: https://grafana-oncall.xxxx.xx
        grafanaUrl: "https://grafana.xxxx.xx"

```

![Image](https://github.com/user-attachments/assets/19a49490-7761-4ead-aa8e-c9d990cc5db9)

However, when loading the page below, a 500 Internal Server Error occurs in the developer tools for the request to `api/plugins/grafana-oncall-app/resources/plugin/status`.

```
2024-09-03 05:52:36 source=engine:app google_trace_id=none logger=django.request Not Found: /api/plugin-proxy/grafana-oncall-app/api/internal/v1/user
2024-09-03 05:52:36 source=engine:uwsgi status=404 method=GET path=/api/plugin-proxy/grafana-oncall-app/api/internal/v1/user latency=0.024656 google_trace_id=- protocol=HTTP/1.1 resp_size=450 req_body_size=0
```

Looking at the engine logs, the request is being sent to grafana-oncall.xxxx.xx/**api/plugin-proxy/grafana-oncall-app/api/internal/v1/user**, and I am wondering if this could be related to using an incorrect URL.

Based on [this code](https://github.com/grafana/grafana/blob/15de549093eb04e3d94cea3b14810eab6c49ccee/public/app/features/alerting/unified/mocks/server/handlers/plugins/grafana-oncall.ts#L5), is it possible that the URL being used is incorrect?
(error setting up request headers: failed to parse JSON response: invalid character 'F' looking for beginning of value body=Forbidden")

### What did you expect to happen?

.

### Did this work before?

no

### How do we reproduce it?

1. external grafana 
2. grafana oncall 1.9.19 in same k8s cluster
3. oncall plugin enable in grafana

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 11.1.0
OS: 1.9.19
Browser:

### Grafana platform?

None
