### ISSUE TITLE
problem of get css&js file in kubernetes ingress 

### ISSUE THREAD

**Issue by justlooks** [grafana/grafana#9321]
hi ,i  run gafana on  kubernetes and use ingress to export gafana server port, i write ingress rule like this ,all fine ,but i use subdir in url path, i find only index.html can be load,and css file and js file can not be load ,the fail reason is : i need visit  "http://www.mydomain.com/monitor/public/css/xxx.css" but the index.html request "http://www.mydomain.com/public/css/xxx.css" 

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
spec:
  rules:
  - host: ingress.epei360.com
    http:
      paths:
      - path: /
        backend:
         serviceName: grafana
         servicePort: 3000 
```

this is a abnormal example

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
spec:
  rules:
  - host: ingress.epei360.com
    http:
      paths:
      - path: /monitoring
        backend:
         serviceName: grafana
         servicePort: 3000
```
