### ISSUE TITLE
server admin role is missing

### ISSUE THREAD

**Issue by amitpandeyn** [grafana/grafana#93226]
### What happened?

Hi, I have installed Grafana using Helm from official Grafana page in an Azure Kubernetes Service cluster. Everything is working but the default admin user which "admin", does not have server admin privilege . The user has admin role but server admin is missing. I tried various things but nothing seems to be working. Please help.

```
# Administrator credentials when not using an existing secret (see below)
adminUser: admin
# adminPassword: admin

admin:
  ## Name of the secret. Can be templated.
  existingSecret: grafana-admin-secret
  userKey: admin-user
  passwordKey: admin-password

```
### What did you expect to happen?

Expecting admin user to have server admin role as well

![Image](https://github.com/user-attachments/assets/4dda963e-dfe9-4404-933e-db93bc676209)

### Did this work before?

No

### How do we reproduce it?

1. Installed Grafana via helm in AKS by following official Grafana documentation 

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None
