### ISSUE TITLE
ServiceGraph module is not being loaded and thus no metrics tempo_service_graph_* are being generated..

### ISSUE THREAD

**Issue by rapar8** [grafana/grafana#93653]
### What happened?

"No ServiceGraph data available" and module "Service-Graph" not being loaded thus no metrics is being exposed.

Span trace is also generating span.kind =client|server|internal
I'm following [Tempo Configuration- Metrics-generator](https://grafana.com/docs/tempo/latest/configuration/#metrics-generator)
> Docker-compose.yaml

```
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo/tempo.yaml" ]
    container_name: tempo
    hostname: tempo
    volumes:
      - ./o11y-backend/tempo-config.yaml:/etc/tempo/tempo.yaml
      - ./tempo-data:/tmp/tempo
    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"
    networks:
      - inst-java-apps-using-otel
    healthcheck:
      interval: 5s
      retries: 10
      test: wget --no-verbose --tries=1 --spider http://localhost:3200/status || exit 1
```

> Tempo-config.yaml

```
server:
  http_listen_port: 3200

distributor:
  ring:
    kvstore:
      store: "inmemory"
  receivers:
    jaeger:
      protocols:
        thrift_http:
        grpc:
        thrift_binary:
        thrift_compact:
    zipkin:
    otlp:
      protocols:
        http:
        grpc:
    opencensus:

ingester:
  trace_idle_period: 10s
  max_block_bytes: 1_000_000
  max_block_duration: 5m

compactor:
  compaction:
    compaction_window: 1h
    max_block_bytes: 100_000_000
    block_retention: 1h
    compacted_block_retention: 24h

# Metrics-generator configuration block
metrics_generator:
  storage:
    path: /tmp/tempo/metrics_generator_storage
  registry:
    collection_interval: 15s
    external_labels:
      source: tempo
  traces_storage:
    path: /tmp/tempo/traces_storage
  # Processor-specific configuration
  processor:
    span_metrics:
      enable_target_info: true
    service_graphs:
      wait: 10
      max_items: 10000
      workers: 10
      histogram_buckets: [ 0.1, 0.2, 0.4, 0.8, 1.6, 3.2, 6.4, 12.8 ]
      enable_messaging_system_latency_histogram: true
storage:
  trace:
    backend: local
    block:
      bloom_filter_false_positive: .05
      v2_encoding: zstd
    wal:
      path: /tmp/tempo/wal
      v2_encoding: snappy
    local:
      path: /tmp/tempo/blocks
    pool:
      max_workers: 100
      queue_depth: 10000

overrides:
  defaults:
    metrics_generator:
      processors:
        - "service-graphs"
        - "span-metrics"
```

> Tempo Log

```
caller=ring.go:297 msg="ring doesn't exist in KV store yet"
caller=module_service.go:82 msg=starting module=distributor
caller=module_service.go:82 msg=starting module=metrics-generator
caller=basic_lifecycler.go:297 msg="instance not found in the ring" instance=tempo ring=metrics-generator
caller=module_service.go:82 msg=starting module=ingester
caller=module_service.go:82 msg=starting module=compactor
```
> prometheus.yaml

```
global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'otel-collector:6666' ]
  - job_name: 'tempo'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'tempo:3200' ]
```

### What did you expect to happen?

Tempo log should show Module - "**Service-Graph**"
Metrics - "**Tempo_service_graph_***" should be generarted in prometheus.

### Did this work before?

Never worked.

### How do we reproduce it?

https://github.com/rapar8/opentelemetry-java-agent/tree/service-graph

Docker compose up --build

docker logs tempo

### Environment (with versions)?

Grafana: Grafana v11.2.0 (2a88694fd3)
Tempo - 2.6
OS:
Browser:

### Grafana platform?

Docker

**Comment by rapar8** [comment]
Document is missing some field under -  remote_write:

```
metrics_generator:
  storage:
    path: /tmp/tempo/generator/wal
    remote_write:
      - url: http://prometheus:9090/api/v1/write
        send_exemplars: true
```

Tempo log is also being added in Debug:
level=debug ts=2024-09-24T11:01:10.284522042Z caller=instance.go:286 tenant=single-tenant msg="adding processor" processorName=span-metrics
level=debug ts=2024-09-24T11:01:10.284595752Z caller=instance.go:286 tenant=single-tenant msg="adding processor" processorName=service-graphs


![Image](https://github.com/user-attachments/assets/6d899568-5d67-443a-b0cd-93da455a23a9)
