### ISSUE TITLE
Provisioning Tempo Datasource with uid fails

### ISSUE THREAD

**Issue by chewrocca** [grafana/grafana#94156]
### What happened?

Provisioning a Tempo datasource with uid fails.

```yaml
- name: Tempo Development
  type: tempo
  uid: tempo-development
  access: proxy
  basicAuth: false
  url: http://tempo-query-frontend.example.net:8080
  editable: true
  jsonData:
    streamingEnabled:
      search: true
```

In Grafana UI, when you select "Save & Test," you receive the message "Unable to connect with Tempo (Unexpected error). Please check the server logs for more details."

While provisioning _without_ the uid works

```yaml
- name: Tempo Development Test
  type: tempo
  access: proxy
  basicAuth: false
  url: http://tempo-query-frontend.example.net:8080
  editable: true
  jsonData:
    streamingEnabled:
      search: true
```

"Successfully connected to Tempo data source."

### What did you expect to happen?

I expected this to work with a configured uid.  This uid is used elsewhere.  

### Did this work before?

Yes.  This worked before trying with TraceQL Streaming.

This **ALSO** works ***with*** TraceQL Streaming *if* no uid is present in the datasource.yml for the Tempo datasource.

### How do we reproduce it?

1. Using Grafana 11.2.1 
2. Provisioning datasource.yml with two identical Tempo datasources, one *with* a uid and the other without
3. Go to https://grafana.dev.silabs.net/connections/datasources and try to click "Save & Test" with both datasources

### Environment (with versions)?

Grafana: 11.2.1
OS: docker image
Browser: Safari and Chrome

### Grafana platform?

Docker

### Datasource(s)?

Tempo
