### ISSUE TITLE
Alerting: Fail to provision contact point with multiple receivers via config file

### ISSUE THREAD

**Issue by chenlujjj** [grafana/grafana#94666]
### What happened?

I tried to provision a contact point with multiple receivers via config file:
```
apiVersion: 1
contactPoints:
  - orgId: 1
    name: email_slack
    receivers:
      - uid: 0c51dc45-5547-4b57-bac3-100e70043482
        type: email
        settings:
          addresses: 2@qq.com
          singleEmail: false
        disableResolveMessage: false
      - uid: 8ddecf7a-ffd4-4ec0-902d-1b99c4604276
        type: slack
        settings:
          recipient: "222"
          token: "333"
        disableResolveMessage: false

```

But in the web UI, two contact points with the same name are created:
![Image](https://github.com/user-attachments/assets/8187187a-248d-4c01-8fd3-60e10cd66cf9)

And if I view the details, both of them are of "Slack" type.
![Image](https://github.com/user-attachments/assets/5d478a18-6404-4bc5-b420-c00c4ef233de)

### What did you expect to happen?

Only one contact point should be created, it should be integrated with two receivers, like this:
![Image](https://github.com/user-attachments/assets/b913a35c-05b5-4d40-bc9f-d9fed5b686da)

### Did this work before?

Not checked before

### How do we reproduce it?

1. Put the above config file under the `/etc/grafana/provisioning/alerting` folder
2. Restart or reload grafana
3. Checkout the contact points page

### Environment (with versions)?

Grafana: v11.0.0
OS:
Browser:

### Grafana platform?

Kubernetes
