### ISSUE TITLE
Auth: Failing to authenticate requests

### ISSUE THREAD

**Issue by JacobValdemar** [grafana/grafana#95355]
### What happened?

After upgrading from `v11.2.1` to `v11.3.0`, users has started getting logged out every now and then. When users are logged out, Grafana logs the following:

```json
{"client":"auth.client.session","error":"user token not found","level":"warn","logger":"authn.service","msg":"Failed to authenticate request","t":"2024-10-24T13:13:47.95012778Z"}
```

I think it might have something to do with #93849, but I am not sure.

Here is our Auth config:

```yaml
auth.okta:
  enabled: "true"
  auth_url: "https://xyz.okta.com/oauth2/v1/authorize"
  token_url: "https://xyz.okta.com/oauth2/v1/token"
  api_url: "https://xyz.okta.com/oauth2/v1/userinfo"
  allow_sign_up: "true"
  scopes: "openid profile email groups offline_access"
  use_refresh_token: "true"
  role_attribute_strict: "true"
  role_attribute_path: "contains(grafanaRole, 'Grafana-Admin') && 'Admin' || contains(grafanaRole, 'Grafana-Developer') && 'Editor' || contains(grafanaRole, 'Grafana-Viewer') && 'Viewer' || 'Viewer'"
  allow_assign_grafana_admin: "true"
  auto_login: "true"
```

### What did you expect to happen?

I expected Grafana to be able to authenticate requests. We did not change anything in the configuration when upgrading from `v11.2.1` to `v11.3.0`.

### Did this work before?

Users were never logged out on `v11.2.1`. The refresh token seemed to work just fine.

### How do we reproduce it?

1. Log into Grafana
2. Use it for a while
3. After some time (hours) the user will abruptly be logged out

### Is the bug inside a dashboard panel?

No, but it can happen while viewing a dashboard panel.

### Environment (with versions)?

Grafana: v11.3.0
OS: MacOS 15.0
Browser: Firefox v131.0.3

### Grafana platform?

Kubernetes
