### ISSUE TITLE
Auth: Renew an access token using a refresh token doesn't work with AzureAD and custom scopes

### ISSUE THREAD

**Issue by Fresa** [grafana/grafana#95379]
### What happened?

When using custom application scopes, renewing an access token using a refresh token is failing with an error log similar to:
```
2024-10-25 09:23:50.072 logger=oauth_token.sync userID=1 t=2024-10-25T07:23:50.072435412Z level=error msg="Failed to refresh OAuth access token" id=user:1 error="oauth2: \"invalid_request\" \"AADSTS90009: Application 'xxxxxx'(xxxxxx) is requesting a token for itself. This scenario is supported only if resource is specified using the GUID based App Identifier. Trace ID: yyyy Correlation ID: zzzzz Timestamp: 2024-10-25 07:23:50Z\""
2024-10-25 09:23:50.065 logger=oauthtoken userID=1 t=2024-10-25T07:23:50.065682612Z level=error msg="Failed to retrieve oauth access token" provider=oauth_azuread userId=1 error="oauth2: \"invalid_request\" \"AADSTS90009: Application 'xxxxxxx'(xxxxxxx) is requesting a token for itself. This scenario is supported only if resource is specified using the GUID based App Identifier. Trace ID: yyyy Correlation ID: zzzzz Timestamp: 2024-10-25 07:23:50Z\""
```

I have verified renewing an access token manually works when the scope parameter is provided with the same scopes used to get an auth code:
```
curl --location --request POST 'https://login.microsoftonline.com/<tenantid>/oauth2/v2.0/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'client_id=<clientid>' \
--data-urlencode 'scope=openid email profile offline_access <custom scope>' \
--data-urlencode 'refresh_token=<refresh token>'
```

If I remove the custom scope (or all scopes) I get the same error message seen in the logs:
```
curl --location --request POST 'https://login.microsoftonline.com/<tenantid>/oauth2/v2.0/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'client_id=<clientid>' \
--data-urlencode 'scope=openid email profile offline_access' \
--data-urlencode 'refresh_token=<refresh token>'
```

### What did you expect to happen?

The access token is refreshed.

### Did this work before?

Yes, and I think this still works if no custom scope is declared.

### How do we reproduce it?

1. Define a custom API scope in the App registration in Azure (Expose an API)
2. Setup API permissions:
![Image](https://github.com/user-attachments/assets/6a6ec260-663c-400d-9929-e794810a88cd)

4. Use the following azuread configuration in Grafana:    
```
auth.azuread:
      name: Azure AD
      enabled: true
      allow_sign_up: true
      auto_login: false
      client_id: <clientid>
      client_secret: <clientsecret>
      scopes: openid email profile offline_access <custom scope>
      auth_url: https://login.microsoftonline.com/<tenantid>/oauth2/v2.0/authorize
      token_url: https://login.microsoftonline.com/<tenantid>/oauth2/v2.0/token
      allowed_domains:
      allowed_groups:
      allowed_organizations: <tenantid>
      role_attribute_strict: false
      allow_assign_grafana_admin: true
      skip_org_role_sync: false
```
`custom scope` is the custom scope created in step 1, i.e. `api://my-app/my-scope`

3. Login to Grafana using AzureAD
4. Wait for the access token to expire
5. User get's logged out
6. Check the error logs for AADSTS90009 

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: v11.2.2+security-01 (dc86a9eafb)
OS: Windows 11
Browser: Google Chrome Version 130.0.6723.60 (Official Build) (64-bit)

### Grafana platform?

Kubernetes
