### ISSUE TITLE
Email lookup doesn't work in Gitlb oauth provder in Grafana version 11.x

### ISSUE THREAD

**Issue by Vetrenik** [grafana/grafana#95388]
### What happened?

Hi, everyone!

I've configured `auth.gitlab` provider and tried to use `email` lookup in `role_attribute_path` and enabled `oauth_allow_insecure_email_lookup` option, but don't get correct results.

My `JMESPath` request is `email=='admin@example.com' && 'GrafanaAdmin' || contains(groups[*], 'mycompany') && 'Editor' || 'Viewer'`, i tested it in https://jmespath.org/ on following data:

```json
{"sub":"1","sub_legacy":"","name":"Administrator","nickname":"root","email":"admin@example.com","email_verified":true,"profile":"https://gitlab.example.com/root","picture":"","groups":["gitlab-instance-13c96909","mycompany"]}
```

And i've  got correct results (which is `GrafanaAdmin`), but in grafana version `11.3.2` and other `11.x` (i tested several) i get role `editior`. Switched my test env grafana to version `10.3.4` and all works fine

### What did you expect to happen?

Email lookup to work propely

### Did this work before?

In version `10.3.4`

### How do we reproduce it?

1. use Grafana official helm chart
2. set values to
```yaml
grafana:
  assertNoLeakedSecrets: false
  image:
    tag: "11.2.3"
  replicas: 1
  grafana.ini:
    auth:
      oauth_allow_insecure_email_lookup: true
    log:
      level: debug
    auth.gitlab:
      enabled: true
      allow_sign_up: true
      client_id: "<client_id>"
      client_secret: "<client_key>"
      scopes: "openid email profile"
      auth_url: https://<gitlab_address>/oauth/authorize
      token_url: https://<gitlab_address>/oauth/token
      api_url: https://<gitlab_address>/api/v4
      tls_skip_verify_insecure: true
      use_refresh_token: true
      use_pkce: true
      allowed_groups: "[\"Dev.Core\", \"mycompany\"]"
      role_attribute_path: "email=='admin@example.com' && 'GrafanaAdmin' || contains(groups[*], 'mycompany') && 'Editor' || 'Viewer'"
      allow_assign_grafana_admin: true
      skip_org_role_sync: false
      role_attribute_strict: true
  env:
    GF_SERVER_ROOT_URL: "http://<grafana_address>"
  plugins:
    - https://grafana.com/api/plugins/grafana-oncall-app/versions/1.10.2/download;grafana-oncall-app
    - https://github.com/VictoriaMetrics/victoriametrics-datasource/releases/download/v0.8.2/victoriametrics-datasource-v0.8.2.zip;victoriametrics-datasource
```

### Environment (with versions)?

Grafana: 11.2.3
OS: MacOS
Browser: Safari

### Grafana platform?

Kubernetes
