### ISSUE TITLE
Grafana 10: Grafana docker image does not serve the .js file

### ISSUE THREAD

**Issue by MehdiMoradiAzad** [grafana/grafana#95478]
### What happened?

**![Image](https://github.com/user-attachments/assets/82239071-517c-4ca4-9ab5-3bcdf67edb4d)
**
We have 3 instances of Grafana, 2 are on VM and are using the RPM package and another one is on Cloud and is using Grafana docker image. All of them are behind a LoadBalancer. In version 10.4.11 when traffic goes to the cloud instance (docker image), users get this error while there is no problem on VM instances. It seems the Grafana docker image can't serve this file: public/build/runtime.a7730fb295250316509a.js
We also have the issue in grafana:10.4.9 

### What did you expect to happen?

![Image](https://github.com/user-attachments/assets/7a54c18a-210c-42bc-842f-0ceaadf65f9e)

### Did this work before?

Grafana:10.4.10 doesn't have this issue.

### How do we reproduce it?

---

### Environment (with versions)?

Grafana: 10.4.11
OS: Docker Image OSS
Browser: Firefox, Google Chrome, Safari

### Grafana platform?

Docker

**Comment by Proximyst** [comment]
Works fine on Grafana 10.4.11, on both OSS and Enterprise, ran in Docker:

```yaml
services:
  grafana:
    image: grafana/grafana:10.4.11
    # image: grafana/grafana-enterprise:10.4.11
    ports:
      - "3000:3000"
```

Is it possible for you to create a minimal reproducible example?
