### ISSUE TITLE
Support self signed certs for alert notifications

### ISSUE THREAD

**Issue by laughland** [grafana/grafana#9548]
- What Grafana version are you using? `grafana/grafana:master`
- What datasource are you using? `Prometheus`
- What OS are you running grafana on? `CentOS 7 on virtualBox` 
- What did you do? `Tried to add a notification alert channel via the grafana UI`
- What was the expected result? `A notification would be sent`
- What happened instead? 

```
grafana_1        | t=2017-10-16T18:06:24+0000 lvl=eror msg="Failed to send alert notifications" logger=context userId=1 orgId=1 uname=admin error="Post https://mattermost.XXXXXXXXXX.com/hooks/<hook id>: x509: certificate signed by unknown authority"
grafana_1        | t=2017-10-16T18:06:24+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/alert-notifications/test status=500 remote_addr=X.X.X.X time_ms=26 size=48 referer=http://localhost:3000/alerting/notification/1/edit
 ```

To troubleshoot we manually added our certificates with Grafana running in a Docker container:

 `docker run --rm --entrypoint="/bin/bash" -p 3000:3000 -it grafana/grafana`

Our signed certificates were added to `/etc/ssl/certs` and then we ran `c_rehash /etc/ssl/certs`

We curled our mattermost instance `curl https://mattermost.ourdomain.com` successfully:

```
root@4b3ababf117c:/# curl https://mattermost.ourdomain.com
<!DOCTYPE html> <html> <head> <meta http-equiv=X-UA-Compatible content="IE=edge"> <meta name=viewport content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=0"> ....
```

Is there some way to use our self signed certificates with Grafana to add an alerting channel?

**Comment by bergquist** [comment]
There are currently no way of using self signed certs for alert notifications. 

https://github.com/grafana/grafana/blob/master/pkg/services/notifications/webhook.go#L27

**Comment by bergquist** [comment]
@laughland Btw. Im not sure your using the correct path for certs on Centos. https://unix.stackexchange.com/questions/363308/how-do-i-list-all-available-ssl-ca-certificates-on-centos-6/363309#363309

**Comment by laughland** [comment]
Thanks for the quick reply. I tried your suggestions via the links but I with no luck; we cannot get past the `x509: certificate signed by unknown authority`  error.  I'm including more details. 

In my `docker-compose` file I have this section for Prometheus and Alertmanager:
```yaml
 services:
prometheus:
     image: prom/prometheus:latest
     volumes:
       - ./prometheus/:/etc/prometheus/
       - prometheus_data:/prometheus
       #- ./prometheus_snmp/certs/:/etc/pki/tls/certs/
       - /alertmanager/alert.rules:/etc/alertmanager/alert.rules
     command:
       - '--config.file=/etc/prometheus/prometheus.yml'
       - '--storage.local.path=/data'
       - '--alertmanager.url=http://localhost:9093/'
       - '--web.external-url=http://localhost:9090/'

```
#I have a non-self signed cert in the volume defined in the above #`- ./prometheus_snmp/certs/`'
 

```yaml

 alert-manager:
       image: prom/alertmanager:latest
       volumes:
         - ./alertmanager/:/etc/alertmanager/
       command:
         - '--config.file=/etc/alertmanager/alertmanager.yml'
```



In my `prometheus.yml` file I have:

```yaml
global:
  scrape_interval: 500s
  scrape_timeout: 500s

alerting:
  alertmanagers:
  - tls_config:
      insecure_skip_verify: true
      #   ca_file: '/etc/pki/tls/certs/ca-bundle.crt'
    static_configs:
      - targets:
```

I  tried using `insecure_skip_verify: true` but no matter how I have tried to configure this I still get this output when running docker-compose:

```javascript
alert-manager_1  | time="2017-10-31T14:37:47Z" level=error 
msg="Notify for 1 alerts failed: Post https://mattermost.<domain>.com/hooks/<key>:
 x509: certificate signed by unknown authority" source="dispatch.go:264" 
```

We have poured through the docs and still cannot get this to work. (https://prometheus.io/docs/operating/configuration/#%3Cfilename%3E)


Here are details on Docker, Prometheus, Alertmanager versions/tags:

Docker:
```bash
# docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

Prometheus and Alertmanager are using `prom/prometheus:latest` and  `prom/alertmanager:latest` respectively.

Any further details on how to set this up are appreciated. Thanks again.

**Comment by laughland** [comment]
Thanks for the quick reply. I tried your suggestions via the links but I with no luck; we cannot get past the `x509: certificate signed by unknown authority`  error.  I'm including more details. 

In my `docker-compose` file I have this section for Prometheus and Alertmanager:
```yaml
 services:
prometheus:
     image: prom/prometheus:latest
     volumes:
       - ./prometheus/:/etc/prometheus/
       - prometheus_data:/prometheus
       #- ./prometheus_snmp/certs/:/etc/pki/tls/certs/
       - /alertmanager/alert.rules:/etc/alertmanager/alert.rules
     command:
       - '--config.file=/etc/prometheus/prometheus.yml'
       - '--storage.local.path=/data'
       - '--alertmanager.url=http://localhost:9093/'
       - '--web.external-url=http://localhost:9090/'

```
#I have a non-self signed cert in the volume defined in the above #`- ./prometheus_snmp/certs/`'
 

```yaml

 alert-manager:
       image: prom/alertmanager:latest
       volumes:
         - ./alertmanager/:/etc/alertmanager/
       command:
         - '--config.file=/etc/alertmanager/alertmanager.yml'
```



In my `prometheus.yml` file I have:

```yaml
global:
  scrape_interval: 500s
  scrape_timeout: 500s

alerting:
  alertmanagers:
  - tls_config:
      insecure_skip_verify: true
      #   ca_file: '/etc/pki/tls/certs/ca-bundle.crt'
    static_configs:
      - targets:
```

I  tried using `insecure_skip_verify: true` but no matter how I have tried to configure this I still get this output when running docker-compose:

```javascript
alert-manager_1  | time="2017-10-31T14:37:47Z" level=error 
msg="Notify for 1 alerts failed: Post https://mattermost.<domain>.com/hooks/<key>:
 x509: certificate signed by unknown authority" source="dispatch.go:264" 
```

We have poured through the docs and still cannot get this to work. (https://prometheus.io/docs/operating/configuration/#%3Cfilename%3E)


Here are details on Docker, Prometheus, Alertmanager versions/tags:

Docker:
```bash
# docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

Prometheus and Alertmanager are using `prom/prometheus:latest` and  `prom/alertmanager:latest` respectively.

Any further details on how to set this up are appreciated. Thanks again.
