### ISSUE TITLE
When exporting alerts, variables in labels are removed.

### ISSUE THREAD

**Issue by heino** [grafana/grafana#95759]
# What went wrong?

When exporting (in this case provisioned) alertes, variables like $labels is not included in labels.

Same when exporting JSON, YAML or HCL

__Expected result__
```yaml
...
  labels:
    something: '{{ index $$labels something.something" }}'
...
```
__Actual result__
```yaml
...
  labels:
    something: '{{ index  something.something" }}'
...
```

# How do we reproduce it?

Using either "Export rules" or "Export" -> "With modification" on the alerts page

# What Grafana version are you using?

Grafana: v11.3.0

# Optional Questions:

##Is the bug inside a Dashboard Panel?
No

## Grafana Platform?
Docker

## User's OS?
MacOS 15.0.1

## User's Browser?
Not UI related

## Is this a Regression?
None

## Are Datasources involved?
Yes (elasticsearch, but )

## Anything else to add?
Kind of related to #70484, which is left open...
