### ISSUE TITLE
Upgrade to 11.3.0 - DB Migration Failing

### ISSUE THREAD

**Issue by mari-arondeus** [grafana/grafana#95904]
### What happened?

Hey y'all,

I'm in the process of bumping us up from 11.2.2-security-01 to 11.3.0, and I'm running into a DB migration issue with both versions 11.2.3 and 11.3.0. I believe the issue is being caused by MR #94373 - from what I can tell from the logs, the migration tool is attempting to modify service account permissions, but we don't have any service accounts, so it's failing. I tried creating a dummy service account, but that didn't seem to help either. Maybe it has something to do with the version of MariaDB we're running?

Relevant logs:
```
logger=migrator t=2024-11-05T17:33:52.616332701Z level=error msg="Executing migration failed" id="delete orphaned service account permissions" error="failed to delete orphaned service accounts: Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AS p WHERE p.kind = 'serviceaccounts' AND p.identifier IN(?)' at line 1" duration=879.966µs
logger=migrator t=2024-11-05T17:33:52.616364523Z level=error msg="Exec failed" error="failed to delete orphaned service accounts: Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AS p WHERE p.kind = 'serviceaccounts' AND p.identifier IN(?)' at line 1" sql="code migration"
Error: ✗ migration failed (id = delete orphaned service account permissions): failed to delete orphaned service accounts: Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AS p WHERE p.kind = 'serviceaccounts' AND p.identifier IN(?)' at line 1
```

### What did you expect to happen?

We were expecting the migration to upgrade Grafana as normal after DB backup & snapshot.

### Did this work before?

Typically we have no issues upgrading Grafana between versions, following the documented upgrade guide.

### How do we reproduce it?

1. Ensure no service accounts exist in Grafana.
2. Link Grafana to a MariaDB database.
3. Attempt Grafana upgrade from 11.2.2-security-01 to 11.2.3 or later
(steps above are tentative, I have not entirely completed troubleshooting)

### Environment (with versions)?

Grafana: 11.2.2-security-01 -> 11.2.3 / 11.3.0 (enterprise, unlicensed)
OS: RHEL 8.9
Database:  MariaDB (Galera) 11.5.2
Container engine: Docker-CE 26.1.3

### Grafana platform?

Docker

**Comment by trauta** [comment]
Having the same issue while upgrading from 10.4.10 to 10.14.11:

```
{
    "duration": "20.744266ms",
    "error": "failed to delete orphaned service accounts: Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AS p WHERE p.kind = 'serviceaccounts' AND p.identifier IN(?,?)' at line 1",
    "id": "delete orphaned service account permissions",
    "level": "error",
    "logger": "migrator",
    "msg": "Executing migration failed",
    "t": "2024-11-06T09:48:20.879729972+01:00"
}
```

**Comment by Proximyst** [comment]
👋🏻 Thanks for reporting!

Reproduction steps:

1. Run Grafana and MariaDB together. I use Docker with docker-compose.yaml. Use a version before the fix existed.
2. Create a new service account.
3. Make sure it has a permission.
4. Delete the entire service account.
5. Upgrade.
6. Crash!

```yaml
services:
  mariadb:
    image: mariadb:11.5
    environment:
      MARIADB_USER: grafana
      MARIADB_PASSWORD: grafana
      MARIADB_DATABASE: grafana
      MARIADB_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  grafana:
    # Swap the images when you're upgrading.
    image: grafana/grafana-enterprise:10.4.10
    #image: grafana/grafana-enterprise:10.4.11
    environment:
      GF_DATABASE_TYPE: mysql
      GF_DATABASE_HOST: 'mariadb:3306'
      GF_DATABASE_NAME: grafana
      GF_DATABASE_USER: grafana
      GF_DATABASE_PASSWORD: grafana
      GF_DATABASE_SSL_MODE: 'false'
    ports:
      - "3000:3000"
    depends_on:
      mariadb:
        condition: service_healthy
```

```
grafana-1  | logger=migrator t=2024-11-07T13:31:12.80292156Z level=info msg="Executing migration" id="delete orphaned service account permissions"
grafana-1  | logger=migrator t=2024-11-07T13:31:12.803927383Z level=error msg="Executing migration failed" id="delete orphaned service account permissions" error="failed to delete orphaned service accounts: Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AS p WHERE p.kind = 'serviceaccounts' AND p.identifier IN(?)' at line 1" duration=1.005573ms
grafana-1  | logger=migrator t=2024-11-07T13:31:12.80394169Z level=error msg="Exec failed" error="failed to delete orphaned service accounts: Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AS p WHERE p.kind = 'serviceaccounts' AND p.identifier IN(?)' at line 1" sql="code migration"
grafana-1  | Error: ✗ migration failed (id = delete orphaned service account permissions): failed to delete orphaned service accounts: Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AS p WHERE p.kind = 'serviceaccounts' AND p.identifier IN(?)' at line 1
mariadb-1  | 2024-11-07 13:31:12 5 [Warning] Aborted connection 5 to db: 'grafana' user: 'grafana' host: '172.22.0.3' (Got an error reading communication packets)
grafana-1 exited with code 1
```
