### ISSUE TITLE
Product Area: Short description of bug

### ISSUE THREAD

**Issue by jcapote22** [grafana/grafana#95974]
### What happened?

``When creating datasources in Grafana via Kubernetes resources, each datasource appears correctly in the Grafana UI. However, accessing any newly created datasource shows the following error:

"Query error: An error occurred within the plugin"
![Image](https://github.com/user-attachments/assets/e76fe70f-8f28-4fb3-b606-11f9c97e03c9)

These datasources, managed via ArgoCD, are created using Kubernetes resources, allowing configuration as code and ensuring consistency across deployments. In this setup, we manage over 100 datasources, so the current behavior requiring manual activation is particularly challenging.

![Image](https://github.com/user-attachments/assets/9f85a20e-302a-4fd7-be6e-5ef58a1d6693)

Despite this error, the datasource successfully connects after manually clicking the "Save & Test" button in the UI. This manual intervention is problematic when deploying multiple datasources, as it requires opening each datasource individually to connect it, which is inefficient.

same datasource but you give it save and test and it works

![Image](https://github.com/user-attachments/assets/15fa09ec-9fcf-43ec-9c79-69233e86f3a1)

![Image](https://github.com/user-attachments/assets/7f3a6d64-4663-4cb4-9a85-55caee9d2512)

no pod restarts or log errors

![Image](https://github.com/user-attachments/assets/55263b60-2e5c-447b-8f4a-f56a78087cd3)

datasource yaml example

```
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: elasticsearch-peru
  namespace: grafana-operator-system
spec:
  valuesFrom:
    - targetPath: "basicAuthUser"
      valueFrom:
        secretKeyRef:
          name: "extra-credentials"
          key: "user"
    - targetPath: "secureJsonData.basicAuthPassword"
      valueFrom:
        secretKeyRef:
          name: "extra-credentials"
          key: "pass"
  instanceSelector:
    matchLabels:
      grafana: default
  datasource:
    access: proxy
    jsonData:
      timeInterval: 5s
      tlsSkipVerify: false
      index: "banco-pe-omni*"
    secureJsonData:
      "basicAuthPassword": ${pass}
    name: ElasticBFPE
    type: elasticsearch
    url: https://internal url
    basicAuth: true
    basicAuthUser: ${user}
```

### What did you expect to happen?

I expected Grafana to automatically validate and establish connections for each datasource upon creation, without needing to manually interact with the "Save & Test" button.

### Did this work before?

This is a new setup, so it hasn't worked correctly with the current versions. I haven’t encountered this issue in previous versions, but the environment has changed recently.

### How do we reproduce it?

1- Deploy Grafana with Grafana Operator  and Grafana version 11.2.2.
2- Create a datasource using a Kubernetes resource.
3- Access the datasource in the Grafana UI.
4- Observe the initial error "Query error: An error occurred within the plugin".
5- Manually click "Save & Test" in the UI to establish the connection.

### Is the bug inside a dashboard panel?

No, the issue occurs within the datasource configuration UI and not within a dashboard panel.

### Environment (with versions)?

Grafana: 11.2.2
OS: linux (kubernetes)
Browser: chrome Versión 129.0

### Grafana platform?

Kubernetes

### Datasource(s)?

Elasticsearch v8.x
