### ISSUE TITLE
migration error from 4.3.2 -> 4.4.0 

### ISSUE THREAD

**Issue by benmathews** [grafana/grafana#9628]
I am running grafana v4.3.2 in kubernetes with the /var/lib/grafana directory using persistent storage. My grafana deployment looks like this.

```
      - env:
        - name: GF_INSTALL_PLUGINS
          value: alexanderzobnin-zabbix-app,raintank-kubernetes-app
        - name: GF_SERVER_ROOT_URL
          value: '%(protocol)s://%(domain)s:%(http_port)s/grafana/'
        image: grafana/grafana:4.3.2
        name: grafana
        ports:
        - containerPort: 3000
          hostPort: 3000
        resources:
          limits:
            cpu: 200m
            memory: 300Mi
          requests:
            cpu: 10m
            memory: 150Mi
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-storage
```
When updating to v 4.4.0, I get a migration error

```installing alexanderzobnin-zabbix-app @ 3.6.1
from url: https://grafana.com/api/plugins/alexanderzobnin-zabbix-app/versions/3.6.1/download
into: /var/lib/grafana/plugins

✔ Installed alexanderzobnin-zabbix-app successfully 

Restart grafana after installing plugins . <service grafana-server restart>

installing raintank-kubernetes-app @ 0.0.7
from url: https://grafana.com/api/plugins/raintank-kubernetes-app/versions/0.0.7/download
into: /var/lib/grafana/plugins

✔ Installed raintank-kubernetes-app successfully 

Restart grafana after installing plugins . <service grafana-server restart>

t=2017-10-23T20:36:50+0000 lvl=info msg="Starting Grafana" logger=main version=4.4.0 commit=3583057 compiled=2017-07-04T21:42:22+0000
t=2017-10-23T20:36:50+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2017-10-23T20:36:50+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2017-10-23T20:36:50+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2017-10-23T20:36:50+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2017-10-23T20:36:50+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2017-10-23T20:36:50+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.log.mode=console"
t=2017-10-23T20:36:50+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana/"
t=2017-10-23T20:36:50+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2017-10-23T20:36:50+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2017-10-23T20:36:50+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2017-10-23T20:36:50+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2017-10-23T20:36:50+0000 lvl=info msg="Initializing DB" logger=sqlstore dbtype=sqlite3
t=2017-10-23T20:36:50+0000 lvl=info msg="Starting DB migration" logger=migrator
t=2017-10-23T20:36:50+0000 lvl=info msg="Executing migration" logger=migrator id="copy data account to org"
t=2017-10-23T20:36:50+0000 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account to org"
t=2017-10-23T20:36:50+0000 lvl=info msg="Executing migration" logger=migrator id="copy data account_user to org_user"
t=2017-10-23T20:36:50+0000 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account_user to org_user"
t=2017-10-23T20:36:50+0000 lvl=info msg="Executing migration" logger=migrator id="Set dashboard version to 1 where 0"
t=2017-10-23T20:36:50+0000 lvl=eror msg="Executing migration failed" logger=migrator id="Set dashboard version to 1 where 0" error="database disk image is malformed"
t=2017-10-23T20:36:50+0000 lvl=eror msg="Exec failed" logger=migrator error="database disk image is malformed" sql="UPDATE dashboard SET version = 1 WHERE version = 0"
t=2017-10-23T20:36:50+0000 lvl=eror msg="Fail to initialize orm engine" logger=sqlstore error="Sqlstore::Migration failed err: database disk image is malformed\n"
```
