### ISSUE TITLE
Auth: Okta breaks in 11.3, works in 11.2

### ISSUE THREAD

**Issue by jseiser** [grafana/grafana#96677]
### What happened?

When upgrading a working config from 11.2 -> 11.3, no Okta users can login.

### What did you expect to happen?

Auth to continue to work between minor versions.

### Did this work before?

Yes, Grafana < 11.3

### How do we reproduce it?

On 11.2

```
    auth.okta:
      enabled: true
      allow_sign_up: true
      client_id: ${grafana_clientid}
      scopes: "openid profile email groups offline_access"
      auth_url: https://auth.my.okta/oauth2/v1/authorize
      token_url: https://auth.my.okta/oauth2/v1/token
      api_url: https://auth.my.okta/oauth2/v1/userinfo
      role_attribute_path: "contains(groups[*], 'AWS-SSO-ADMIN') && 'Admin' || contains(groups[*], 'MONITORING-SSO-ACCESS') && 'Editor' || 'Viewer'"
      role_attribute_strict: false
      use_refresh_token: true
      allow_assign_grafana_admin: "true"
```

This works, I login, and I am a member of `AWS-SSO-ADMIN` in Okta, so I am an Admin in Grafana.

Upgrade to 11.3, Same config no longer works.

### Is the bug inside a dashboard panel?

No.

### Environment (with versions)?

Grafana: 11.3
OS: All
Browser: All

### Grafana platform?

Kubernetes
