### ISSUE TITLE
Error when querying Loki Logs in Grafana UI

### ISSUE THREAD

**Issue by belmin-devops-eng** [grafana/grafana#96976]
### What happened?

I encountered an error when sending a query to a Loki gateway via the Grafana UI. However, when I ran the same query using the curl command inside the Grafana container or inside the container of the Loki gateway, I successfully retrieved the logs. Additionaly, when I submitted a query via the "Live" button, I also received logs. The label browser worked as well. I have tried to increase the timeout as mentioned in this [issue](https://community.grafana.com/t/increasing-timeout-query-to-loki-datasource/58582), but unfortunately it did not help.

Here are the timeouts that I have tried to set in grafana.ini:

```sh
[analytics]
check_for_updates = false
reporting_enabled = false
[auth]
disable_login_form = true
disable_signout_menu = true
[auth.basic]
enabled = false
[auth.proxy]
auto_sign_up = true
enabled = true
header_name = X-Forwarded-User
[security]
admin_user = system:does-not-exist
cookie_secure = true
[users]
viewers_can_edit = true
default_theme = light
[log]
mode = console
level = trace
[dataproxy]
timeout = 1200
tls_handshake_timeout_seconds = 30
expect_continue_timeout_seconds = 5
evaluation_timeout = 120
max_attempts = 3
[server]
read_timeout = 120
```

The queries, which I have run in the grafana & loki-distributor pods, are:

```sh
# Get labels
curl -k -H "Authorization: Bearer <my-openshift-token>" -H "X-Scope-OrgID: application" https://${GATEWAY_ADDRESS}/api/logs/v1/application/loki/api/v1/labels

# Get logs for specifed container
curl -k -H "Authorization: Bearer <my-openshift-token>" -H "X-Scope-OrgID: application"  -G --data-urlencode 'query={kubernetes_container_name="my-container"}' https://${GATEWAY_ADDRESS}/api/logs/v1/application/loki/api/v1/query_range
```

Here are some screenshots of the error messages in the browser:

![Image](https://github.com/user-attachments/assets/7211e067-7f9e-4253-9d9c-dda8e19072b3)
![Image](https://github.com/user-attachments/assets/41ab1de5-0fa8-4a88-9540-2d7f0f62cf56)

### What did you expect to happen?

I expected to receive the logs for the specified query in the Grafana UI.

### Did this work before?

No, this issue has been present from the beginning.

### How do we reproduce it?

1. Run the query in the Grafana UI.
2. Alternatively, use the label browser to select a label and find values for the selected label.

### Environment (with versions)?

OpenShift Loki-Operator: loki-operator.v5.9.9
Grafana: docker.io/grafana/grafana:10.4.9
Browser: Google Chrome, Microsoft Edge and Firefox
OS: OpenShift 4.15

### Grafana platform?

Kubernetes

### Datasource(s)?

Loki

**Comment by matyax** [comment]
@belmin-devops-eng Did you check the data source configuraration? Does it succeeds when you click "Save and test"?

**Comment by matyax** [comment]
I'm wondering if the issue is not in the URL you're using in the data source configuration, because it's returning HTML as it can be seen in the response: `error from loki: ReadObject: expect { or , or } or n, but found <, error found in #1 byte of ...|<!DOCTYPE h|..., bigger context ...|<!DOCTYPE html>\n<html lang=\"en-us\" data-test-id=\"lo|...`.

For the authentication part, unfortunately I have no experience with that setup but I'll ask around.

**Comment by svennergr** [comment]
Hi @belmin-devops-eng,

I am not that familiar with an OpenShift deployment, but based on 
`curl -k -H "Authorization: Bearer <my-openshift-token>" -H "X-Scope-OrgID: application"  -G --data-urlencode 'query={kubernetes_container_name="my-container"}' https://${GATEWAY_ADDRESS}/api/logs/v1/application/loki/api/v1/query_range`
can you try the following:
1. Confirm you set the same `X-Scope-OrgID: application` header in Grafana's data source setting
2. Make sure the base URL of your data source is the same as `https://${GATEWAY_ADDRESS}/api/logs/v1/application/` - especially the `https` part
3. You do `curl -k` which "ignores" SSL errors. Make sure to do the same in Grafana's data source settings by checking the `Skip TLS certificate validation` option:
![Image](https://github.com/user-attachments/assets/428bfa0b-ccb9-4f9b-a965-844828f5178b)

**Comment by belmin-devops-eng** [comment]
Thanks for responding @matyax @svennergr.

I believe I have identified the cause of the problem. I added a second header (Authorization header with the OpenShift token, see below for my configuration) to the Loki datasource configuration file. After logging in again, I clicked on the Loki datasource and ran a test, which succeded. I then manually started a query, and it worked as well.

It seems that there is an issue with how Grafana relays the "Authorization" header. The handling of this authorization headers seems to be different between a normal query and a live query or the label browser.

The datasource configuration for which the test succeeded is given below.

grafana-datasources (loki.yaml)
```
apiVersion: v1
data:
  loki.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki (Application)
        isDefault: true
        type: loki
        access: proxy
        url: https://${GATEWAY_ADDRESS}/api/logs/v1/application/
        jsonData:
          tlsAuthWithCACert: true
          httpHeaderName1: X-Scope-OrgID
          httpHeaderName2: Authorization
        secureJsonData:
          tlsCACert: ${GATEWAY_SERVICE_CA}
          httpHeaderValue1: application
          httpHeaderValue2: Bearer <my-openshift-token>
      - name: Loki (Infrastructure)
        type: loki
        access: proxy
        url: https://${GATEWAY_ADDRESS}/api/logs/v1/infrastructure/
        jsonData:
          tlsAuthWithCACert: true
          httpHeaderName1: X-Scope-OrgID
          httpHeaderName2: Authorization
        secureJsonData:
          tlsCACert: ${GATEWAY_SERVICE_CA}
          httpHeaderValue1: infrastructure
          httpHeaderValue2: Bearer <my-openshift-token>
      - name: Loki (Audit)
        type: loki
        access: proxy
        url: https://${GATEWAY_ADDRESS}/api/logs/v1/audit/
        jsonData:
          tlsAuthWithCACert: true
          httpHeaderName1: X-Scope-OrgID
          httpHeaderName2: Authorization
        secureJsonData:
          tlsCACert: ${GATEWAY_SERVICE_CA}
          httpHeaderValue1: audit
          httpHeaderValue2: Bearer <my-openshift-token>
kind: ConfigMap
metadata:
  name: loki-datasources
  namespace: your-namespace
```
