### ISSUE TITLE
DataSource Provisioning: prune setting does not work as expected on Kubernetes

### ISSUE THREAD

**Issue by jkleinlercher** [grafana/grafana#97051]
### What happened?

When I create a datasource configmap on Kubernetes with `prune: true` included, the datasource gets deleted immediatly.

datasource configmap:

```
apiVersion: v1
data:
  datasource.yaml: |-
    prune: true
    apiVersion: 1
    datasources:
    - name: datasource-prune-test-jokl2
      type: prometheus
      typeName: prometheus
      uid: datasource-prune-test-jokl2
      basicAuth: false
      url: http://sx-mimir-nginx.mimir.svc:80/prometheus
      access: proxy
      isDefault: false
      jsonData:
        httpMethod: "POST"
        prometheusType: "Mimir"
        prometheusVersion: "2.9.1"
kind: ConfigMap
metadata:
  annotations:
  labels:
    grafana_datasource: "1"
  name: sx-datasource-prune-test-jokl
  namespace: mimir
```

Log events in grafana pod for this datasource `datasource-prune-test-jokl2` :

```
logger=provisioning.datasources t=2024-11-26T14:24:37.036339992Z level=info msg="inserting datasource from configuration" name=datasource-prune-test-jokl2 uid=datasource-prune-test-jokl2
logger=secrets.kvstore t=2024-11-26T14:24:37.046103626Z level=debug msg="secret value inserted" orgId=1 type=datasource namespace=datasource-prune-test-jokl2
logger=secrets.kvstore t=2024-11-26T14:24:43.898270424Z level=debug msg="secret value deleted" orgId=1 type=datasource namespace=datasource-prune-test-jokl2
logger=provisioning.datasources t=2024-11-26T14:24:43.90547255Z level=info msg="deleted datasource based on configuration" name=datasource-prune-test-jokl2
logger=provisioning.datasources t=2024-11-26T14:25:27.959863574Z level=info msg="inserting datasource from configuration" name=datasource-prune-test-jokl2 uid=datasource-prune-test-jokl2
logger=secrets.kvstore t=2024-11-26T14:25:27.971189992Z level=debug msg="secret value inserted" orgId=1 type=datasource namespace=datasource-prune-test-jokl2
logger=secrets.kvstore t=2024-11-26T14:25:28.018526559Z level=debug msg="secret value deleted" orgId=1 type=datasource namespace=datasource-prune-test-jokl2
logger=provisioning.datasources t=2024-11-26T14:25:28.028401966Z level=info msg="deleted datasource based on configuration" name=datasource-prune-test-jokl2
```

Grafana doesn't show the datasource.

### What did you expect to happen?

according to https://github.com/grafana/grafana/issues/94645#issuecomment-2428534214 I expect that the datasources are just marked with `is_prunable: true` and only when the configmap in Kubernetes gets deleted, the datasources get deleted.

### Did this work before?

I don't know

### How do we reproduce it?

1. apply the configmap as described above (the mimir target is very specific to my environment but you can change it)
2. look at the logs from grafana
3. look in grafana if the datasource will get created or not

### Environment (with versions)?

Grafana: Grafana v11.3.1 (64b556c137)
OS: Kubernetes, Grafana installed with grafana helm chart v8.6.1 from repo https://grafana.github.io/helm-charts
Browser: Chrome

### Grafana platform?

Kubernetes
