### ISSUE TITLE
Datasource: Double env expansion when parsing the datasource file

### ISSUE THREAD

**Issue by LeszekBlazewski** [grafana/grafana#97185]
### What happened?

Hey!

Thanks for making Grafana such a great product. For the past few days I have been debugging an issue for failed postgres authentication for the postgres datasource. After testing I have nailed down the issue to be related to datasource file parsing which injects environment variables that contain a `$` in their value.

Details

According to https://grafana.com/docs/grafana/latest/administration/provisioning/#environment-variables

> You can use environment variable interpolation in all three provisioning configuration types. The allowed syntax is either `$ENV_VAR_NAME` or ${ENV_VAR_NAME}, and it can be used only for values, not for keys or larger parts of the configurations. It’s not available in the dashboard’s definition files, just the dashboard provisioning configuration.

> You can use $$ if you have a literal $ in your value and want to avoid interpolation.

I have the following datasource configuration

```yaml
  - name: my-postgres
    type: postgres
    url: my-postgres-dns:5432
    user: grafana
    uid: my-postgres
    secureJsonData:
      password: ${GRAFANA_POSTGRES_DATASOURCE_PASSWORD}
    jsonData:
      database: sample
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1500
```

The ENV value that I am setting for `GRAFANA_POSTGRES_DATASOURCE_PASSWORD` is `Pa$sword` and that is when it breaks. After local debugging session, I have found out that the problem comes from the following code:

[interpolateValue](https://github.com/grafana/grafana/blob/main/pkg/services/provisioning/values/values.go#L315)

In the above function due to the usage of `${syntax}` first expansion happens at [setting.ExpandVar(v)](https://github.com/grafana/grafana/blob/main/pkg/services/provisioning/values/values.go#L319) since the value matches the [regex](https://github.com/grafana/grafana/blob/main/pkg/setting/expanders.go#L45) and then next expansion happens at [os.ExpandEnv(v)](https://github.com/grafana/grafana/blob/main/pkg/services/provisioning/values/values.go#L324) which essentially strips down the `$sword` from the configured env and the final value is set to `Pa` which of course won't work.

In the above case using `$$` does not work in the current [interpolateValue function](https://github.com/grafana/grafana/blob/main/pkg/services/provisioning/values/values.go#L315) because the ENV is evaluated after the `$$` handling part.

If I would use the `$GRAFANA_POSTGRES_DATASOURCE_PASSWORD` syntax in the datasource file the password would be injected properly because it does not match the mentioned [regex](https://github.com/grafana/grafana/blob/main/pkg/setting/expanders.go#L45) and therefore double expansions won't happen. **The docs do not mention that such behaviour is expected.**

Initially I wanted to suggest a fix to make `${ENV}` syntax with a value that includes `$` work but after evaluating how the interpolation function works and how settings expanders have been written I did not come up with a clean solution how to handle this case. I think that expanders are working as expected and it's just the interpolation function that might need a fix. The options I thought about are:

1. Do noting and update the docs regarding this limitation (no support for ${ENV} syntax when the value contains `$`)
2. Remove support for `$ENV` (change [interpolated[i] = os.ExpandEnv(v)](https://github.com/grafana/grafana/blob/main/pkg/services/provisioning/values/values.go#L324) to `interpolated[i] = expanded` so that the env expansion will only work via a config matching [regex](https://github.com/grafana/grafana/blob/main/pkg/setting/expanders.go#L45) (so handled by the expanders). This would be a breaking change (since `$ENV` stops working) so probably not desired.
3. Try to adjust the [func interpolateValue](https://github.com/grafana/grafana/blob/main/pkg/services/provisioning/values/values.go#L315) to prevent double expansion (for example to add a condition for calling [interpolated[i] = os.ExpandEnv(v)](https://github.com/grafana/grafana/blob/main/pkg/services/provisioning/values/values.go#L324) only if the expander did not expand the value already. This might be a breaking change as well if someone would depend on this feature/bug? (not sure if this behaviour is desired)
4. Other implementation I did not come up with 😄 

I am happy to work on this if the bug will be accepted but would need slight guidance in which way this should be implemented or I would simply update the docs.

### What did you expect to happen?

That my injected password that contains `$`  from ENV variable would be configured correctly.

### Did this work before?

I am not sure, I don't think so since git blame says the code has not been adjusted in good few years.

### How do we reproduce it?

1. Set environment variable for grafana: `GRAFANA_POSTGRES_DATASOURCE_PASSWORD=Pa$sword`
2. Try to provision the following datasource
```yaml
  - name: my-postgres
    type: postgres
    url: my-postgres-dns:5432
    user: grafana
    uid: my-postgres
    secureJsonData:
      password: ${GRAFANA_POSTGRES_DATASOURCE_PASSWORD}
    jsonData:
      database: sample
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1500
```
3. Notice what the configured password would be and that you wouldn't be able to connect to the PG datasource (actually this should affect any datasource since it's related to parsing)

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: [v11.3.1 (64b556c137)](https://github.com/grafana/grafana/blob/main/CHANGELOG.md)
OS: Running in Kubernetes, shouldn't matter I guess
Browser: Chrome but it's not related

### Grafana platform?

Kubernetes

### Datasource(s)?

Any since this is regarding parsing of the datasource file
