### ISSUE TITLE
OAuth login fails unless the user is in a Keycloak group containing a required legacy role

### ISSUE THREAD

**Issue by zt4123** [grafana/grafana#97663]
### What happened?

When using Keycloak authentication with Grafana, users are unable to log in unless they are in a group that is mapped to the legacy dba-access-only role. Removing or replacing this role mapping with a different one (dba-access) breaks login for everyone in that group. Additionally, creating a new group and assigning dba-access-only to it allows users in that group to log in successfully. This suggests that the legacy dba-access-only role is somehow implicitly required for successful authentication, even though it is no longer intentionally used.

### Keycloak Configuration Details:
* The Keycloak realm “infrastructure” is used.
* Historically, a Keycloak group “DBA” included a dba-access-only role mapping.
* This dba-access-only role is old and does not provide any special permissions.
* Currently:
* If a user is in a group that includes dba-access-only, the user can log into Grafana.
* If the user is not in such a group, login fails with Login failed InternalError.

### What I Did:
1.	Attempted removing the dba-access-only role from the DBA group and added a newly created dba-access role instead.
	•	Result: Even users in the DBA group now cannot log in. The presence of dba-access (instead of dba-access-only) does not restore access.
2.	Created a new group named “Grafana” and assigned dba-access-only to it.
	•	Result: Users in this new Grafana group can log in successfully, confirming that the dba-access-only role is the key factor, not the particular group.
3.	Verified that no other changes to Grafana’s config or Keycloak realm were impacting login success.
4.	Reverting to any scenario without dba-access-only involved leads to failed logins.

oauth config:
```
auth.generic_oauth:
  enabled: "true"
  name: "XXX SSO"
  allow_sign_up: "true"
  auto_login: "false"
  client_id: "grafana-test"
  client_secret: "xxx"
  auth_url: "https://keycloak.xxx.com/realms/infrastructure/protocol/openid-connect/auth"
  token_url: "https://keycloak.xxx.com/realms/infrastructure/protocol/openid-connect/token"
  api_url: "https://keycloak.xxx.com/realms/infrastructure/protocol/openid-connect/userinfo"
  scopes: "email"
  org_attribute_path: info.roles
  org_mapping: "grafana-gitlab-admin:gitlab:Admin"
```

### Additional Notes:
* This issue persists on multiple deployment methods (Helm, Operator).
* The dba-access-only role is not explicitly configured or required in Grafana’s OIDC settings, yet its presence is mandatory for successful authentication.
* This suggests a bug in Grafana’s OIDC role processing logic or a hidden dependency on this legacy role.

### What did you expect to happen?

* Removing or substituting the dba-access-only role should not block login for all users.
* Users not in a group linked to dba-access-only should still be able to log in, assuming no other restrictions are in place.

### Did this work before?

We never encountered this issue before until a new developer attempted to access Grafana. We followed the same procedure used in previous months to grant them access, but their login attempts failed. Upon investigation, we discovered that the failure occurred because the developer was not in the Keycloak group containing the legacy required role. This problem surfaced only when we tried to onboard someone outside that group.

### How do we reproduce it?

1. Configure Grafana with the above Keycloak OIDC settings.
2. Ensure a Keycloak group (e.g., “DBA”) is associated with dba-access-only.
3. Have a user who is in that group log in: success.
4. Remove dba-access-only from the group and replace it with a different role (e.g., dba-access): The same user now fails to log in.
5. Create a new group “Grafana” and add dba-access-only: A user in this group can log in again, confirming the dependency on the dba-access-only role.

### Environment (with versions)?

Grafana: v11.4.0
OS: Ubuntu 20.04 / Kubernetes 1.27
Browser: Chrome 119
Tested with Grafana deployed via Helm chart on Kubernetes
Tested with Grafana managed by the Grafana Operator

### Grafana platform?

Kubernetes
