### ISSUE TITLE
Alerting: yaml for alerts that is exported through web UI is causing grafana to crash on startup

### ISSUE THREAD

**Issue by danfinn** [grafana/grafana#97804]
### What happened?

grafana 11.3.0 on k8s

Our general workflow is that we create alerts via the UI, we then export the yaml for those alerts from the UI and save that into git.  When grafana is restarted it pulls in this file for provisioning from git.

This morning I added some new alerts and I noticed we are getting a strange error when the grafana pod attempts to restart:
```
logger=ngalert.notifier.alertmanager org=1 t=2024-12-11T16:20:05.501464632Z level=info msg="Applying new configuration to Alertmanager" configHash=daf3073212d3795a32b739cee60d6728
logger=ngalert.state.manager t=2024-12-11T16:20:05.512927075Z level=info msg="Running in alternative execution of Error/NoData mode"
logger=infra.usagestats.collector t=2024-12-11T16:20:05.514848677Z level=info msg="registering usage stat providers" usageStatsProvidersLen=2
logger=provisioning t=2024-12-11T16:20:06.709714942Z level=error msg="Failed to provision alerting" error="failure to map file alerts.yaml: failure parsing rules: rule 'New Blocked SQLs (4 hour interval)' failed to parse: empty duration string"
Error: ✗ failure to map file alerts.yaml: failure parsing rules: rule 'New Blocked SQLs (4 hour interval)' failed to parse: empty duration string
```

so what I've done to try and resolve this is to add the following line to the alerts:

`for: 0s`

and that seems to resolve the error for that particular alert but it seems as though grafana is wanting me to do this to ALL of my alerts (as best as I can tell).  I'd really prefer to not have to do this since we have many alerts.

Here is an example of a complete alert, that was exported via the web UI and that caused the error above:

```
        - uid: 2xymZ3L4z
          title: DFT errors
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: prod2-cust-common-logs
              model:
                alias: ""
                bucketAggs:
                    - field: '@timestamp'
                      id: "2"
                      settings:
                        interval: auto
                      type: date_histogram
                datasource:
                    type: elasticsearch
                    uid: prod2-cust-common-logs
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                metrics:
                    - id: "1"
                      type: count
                query: '"failed to apply delta to file"'
                refId: A
                timeField: '@timestamp'
            - refId: B
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 1
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: ""
          panelId: 0
          noDataState: OK
          execErrState: OK
          annotations:
            summary: failed to apply delta to file error found
          labels:
            BMAP_PagerDuty: "True"
            Teams: "True"
          isPaused: false
```

and the modified version (just one line added) to get it to stop complaining about this alert but then it just moves onto the next one:

```
        - uid: 2xymZ3L4z
          title: DFT errors
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: prod2-cust-common-logs
              model:
                alias: ""
                bucketAggs:
                    - field: '@timestamp'
                      id: "2"
                      settings:
                        interval: auto
                      type: date_histogram
                datasource:
                    type: elasticsearch
                    uid: prod2-cust-common-logs
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                metrics:
                    - id: "1"
                      type: count
                query: '"failed to apply delta to file"'
                refId: A
                timeField: '@timestamp'
            - refId: B
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 1
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: ""
          panelId: 0
          noDataState: OK
          execErrState: OK
          for: 0s
          annotations:
            summary: failed to apply delta to file error found
          labels:
            BMAP_PagerDuty: "True"
            Teams: "True"
          isPaused: false
```

This is pretty odd to me that it just started happening.  We did hit this one other time a couple of weeks ago for the first time but it was only complaining about a single alert, we added the duration statement to that alert and grafana happily started up after that.  I'm not sure why it's now doing this for all of these other alerts.  We have not changed grafana versions recently.

### What did you expect to happen?

grafana to startup without errors with the yaml that it exported

### Did this work before?

yes, this has been working for us for quite some time

### How do we reproduce it?

1. see alert above that is causing issues
2.
3.

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 11.3.0
OS: kubernetes
Browser: chrome

### Grafana platform?

Kubernetes
