### ISSUE TITLE
Windows Exporter Dashboard 2024 issues

### ISSUE THREAD

**Issue by hack3rcon** [grafana/grafana#98502]
Hello,
I’m having some issues that I don’t know if it’s related to my configuration or something else. I did not make any changes to the Grafana configuration file and I just changed the Prometheus configuration file as follows:

```
# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    scrape_timeout: 5s

  - job_name: "Local_Linux"
    scrape_interval: 10s
    static_configs:
      - targets: ["localhost:9100"]

  - job_name: "Windows_10"
    scrape_interval: 10s
    static_configs:
      - targets: ["192.168.1.3:9182"]

  - job_name: "Windows_2"
    scrape_interval: 10s
    static_configs:
      - targets: ["192.168.1.3:9182"]

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

#    static_configs:
#      - targets: ['localhost:9090']

  - job_name: node
    # If prometheus-node-exporter is installed, grab stats about the local
    # machine by default.
    static_configs:
      - targets: ['localhost:9100']
```
As you can see, I have only defined two jobs with different names and the same IP address `192.168.1.3`.
These servers have been added to the dashboard:
[https://pasteboard.co/leFdjPGik4xq.png](url)

When I click on the IP address in the `Instance` section, the server information disappears from the dashboard:
[https://pasteboard.co/cFJ0vND5dYjD.png](url)

Which part of the configuration is this problem related to?

Thank you.
