### ISSUE TITLE
Grafana Live: 401 Unauthorized responses to /api/live/ws

### ISSUE THREAD

**Issue by ecurbelo** [grafana/grafana#98822]
### What happened?

From time to time we received an alert notification for a high number of requests with 401 Unauthorized responses.

Checking the Grafana logs we can see a large number of logs such as the following:
```
logger=context userId=0 orgId=0 uname= t=2025-01-08T06:50:17.360683205Z level=info msg="Request Completed" method=GET path=/api/live/ws status=401 remote_addr=XX.XXX.XXX.XX time_ms=22 duration=22.27281ms size=105 referer= handler=/api/live/ws status_source=server
```

The `remote_addr` corresponds to a user who has been logged in. All users login via Google OAuth. Excerpt of the Helm chart values file:
```
grafana:
  grafana.ini:
    auth.google:
      enabled: true
      allow_sign_up: true
      auto_login: false
      client_id: ${GOOGLE_OAUTH_CLIENT_ID}
      client_secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
      scopes: openid email profile
      auth_url: https://accounts.google.com/o/oauth2/v2/auth
      token_url: https://oauth2.googleapis.com/token
      api_url: https://openidconnect.googleapis.com/v1/userinfo
      allowed_domains: foo.com
      hosted_domain: foo.com
      use_pkce: true
      allow_assign_grafana_admin: true
      skip_org_role_sync: false
      role_attribute_path: contains(email, '@foo.com') && 'GrafanaAdmin' || 'Viewer'   
```

The logs when the feature is not returning 401 looks like this:
```
logger=context userId=6 orgId=1 uname=john.doe@foo.com t=2025-01-08T06:50:39.048697005Z level=info msg="Request Completed" method=GET path=/api/live/ws status=-1 remote_addr=XX.XXX.XXX.XX time_ms=699 duration=699.579164ms size=0 referer= handler=/api/live/ws status_source=server
```

And on the browser we can also check that the websocket is opened successfully on the `GET wss://foo.com/api/live/ws` request:

![Image](https://github.com/user-attachments/assets/c99fb421-0fc3-4086-b0bc-58041413a0b7)

Just in case, i leave some related lines of the nginx configuration (generated by Grafana's Helm Chart):
```
$ kubectl exec -it ingress-nginx-controller-XXXXXXXXX -n ingress-nginx -- bash
ingress-nginx-controller-XXXXXXXXX:/etc/nginx$ cat nginx.conf
[...]
       ## start server foo.com                                                                                            
        server {                                                                                                                      
                server_name foo.com ;
                [...]
                location / {    
                        [...]
                        set $best_http_host      $http_host;
                        proxy_set_header Host                   $best_http_host;                                                                                      
                        proxy_set_header                        Upgrade           $http_upgrade;                                                                                                                                                        
                        proxy_set_header                        Connection        $connection_upgrade;                  
                        proxy_http_version                      1.1;    
                        proxy_pass http://upstream_balancer;
[...]
```

### What did you expect to happen?

All requests to `/api/live/ws` endpoint end successfully (200 OK).

### Did this work before?

I am not sure. 

### How do we reproduce it?

I don't know how to reproduce it. 

My last guess is that maybe it can be related when the user token has expired or cannot obtain the user information, because the logs with 401 status show `userId=0 orgId=0 uname=`.

### Is the bug inside a dashboard panel?

No.

### Environment (with versions)?

Grafana: Grafana v11.4.0 (b58701869e)
OS: Ubuntu
Browser: Firefox 133.0.3 (64-bit)

Helm Chart version: [8.8.2](https://github.com/grafana/helm-charts/tree/grafana-8.8.2/charts/grafana)

### Grafana platform?

Kubernetes
