### ISSUE TITLE
Datasource provisioning: url limited to 255 chars leads to error with multiple hosts datasources like Redis Cluster

### ISSUE THREAD

**Issue by ligreman** [grafana/grafana#98881]
### What happened?

In latests Grafana versions the "url" field in Datasource provisioning files are limited to 255. If a longer url is set, Grafana won't start and shows the error:
"Failed to provision data sources. Datasource provisioning error: [datasource.urlInvalid] max length is 255".

My provision file is:

```
...
  - name: Redis
    type: redis-datasource
    url: redis://host1:6379, redis:/host2:6379, ..., redis://hostN:6379
...
```

So, the url field has more than 255 characters. Multiple hosts are provided separated by commas, as described in the redis datasource documentation: https://redisgrafana.github.io/redis-datasource/configuration/#cluster

### What did you expect to happen?

The url field validation must allow more than 255 characters. The 255 limit can be set per host, so if multiple hosts are provided it must validate each host independently, not all hosts as a whole.

Maybe a higher character limit can be set for the whole url field, to avoid exploiting it. But it must be way higher.

### Did this work before?

Yes, it worked in Grafana 9.X

### How do we reproduce it?

1. Install Grafana 11.X
2. Install Redis datasource plugin https://redisgrafana.github.io/quickstart/#grafana-marketplace
3. Create a datasource provisioning file.
4. Inside the file, create a new datasource with multiple hosts (it does not matter if they really exists, the validation error raises before checking if the host are online). Total characters of the url field must be more than 255.
5. Re/Start Grafana and check the output log for the error
6. Grafana does not starts.
Example provisioning file:
```
apiVersion: 1

datasources:
  - name: redis-datasource
    url: redis://my-hostname-for-testing-the-validation-of-this-field-number-1.foo:6379, redis://my-hostname-for-testing-the-validation-of-this-field-number-2.foo:6379, redis://my-hostname-for-testing-the-validation-of-this-field-number-3.foo:6379, redis://my-hostname-for-testing-the-validation-of-this-field-number-4.foo:6379
    version: 1
    jsonData:
      client: cluster
      tlsSkipVerify: true
```

### Environment (with versions)?

Grafana: 11
OS: Ubuntu 22
Browser: Chrome

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

Redis Datasource
