### ISSUE TITLE
Upgraded to 11.5.0, won't start due to GMS error

### ISSUE THREAD

**Issue by bmrowe** [grafana/grafana#99788]
### What happened?

I've been running grafana:latest and this update to 11.5.0 will not start. See errors below. Going back to 11.4.1 works fine.

<img width="1342" alt="Image" src="https://github.com/user-attachments/assets/4d7d5934-0018-47ce-b3dd-62856ceed511" />

### What did you expect to happen?

Grafana to start

### Did this work before?

Yes. 11.4.1

### How do we reproduce it?

1. Upgrade from Grafana 11.4.1 to 11.5.0
2.
3.

### Environment (with versions)?

Grafana: 11.5.0
OS: Unraid
Browser:

### Grafana platform?

Docker

**Comment by bmrowe** [comment]
Here is the log for 11.4.1 when things start up fine: 

<img width="1381" alt="Image" src="https://github.com/user-attachments/assets/666fd345-19ed-4718-9e38-c4a219190144" />

**Comment by l4rm4nd** [comment]
Can confirm the same issue.

Grafana 11.5.0 bricks and throws:

````
grafana     | logger=ngalert.state.manager t=2025-01-30T16:40:11.923582038Z level=info msg="Running in alternative execution of Error/NoData mode"
grafana     | Error: ✗ initializing GMS client: missing GMS domain
grafana     | Error checking server process execution privilege. error: could not get current OS user to detect process privileges
````

Rolling back to the Docker image tag `11.4.1` works. No issues and Grafana properly spawns up.

**Comment by Eddie84** [comment]
Same issue,
if can help this is my docker-compose file:
```yaml
  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    user: "0"
    depends_on:
      - influxdb
    volumes:
      - ${USERDIR}/grafana/log:/var/log/grafana
      - ${USERDIR}/grafana/data:/var/lib/grafana
      - ${USERDIR}/grafana/provisioning:/etc/grafana/provisioning
      - ${USERDIR}/grafana/config/defaults.ini:/usr/share/grafana/conf/defaults.ini:rw
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=${GF_INSTALL_PLUGINS}
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
 ```
